Repository rust-lang/rust-clippy, pull requests merged in 2018-12, with the labels that each got.

#3483 Mention triage procedure in contributing.md
  CONTRIBUTING.md
Labels: S-waiting-on-review

#3479 Downgrade large_digit_groups to pedantic
  clippy_lints/src/lib.rs
  clippy_lints/src/literal_representation.rs
  tests/ui/literals.rs
  tests/ui/literals.stderr
Labels: S-waiting-on-review

#3478 Remove unsafe_vector_initialization lint
  README.md
  clippy_lints/src/deprecated_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/slow_vector_initialization.rs
  tests/ui/slow_vector_initialization.rs
  tests/ui/slow_vector_initialization.stderr
Labels: S-waiting-on-review

#3490 Extract single_match_else UI test
  clippy_lints/src/matches.rs
  tests/ui/matches.rs
  tests/ui/matches.stderr
  tests/ui/single_match_else.rs
  tests/ui/single_match_else.stderr
Labels: S-waiting-on-review

#3444 Fix dogfood tests
  CONTRIBUTING.md
  ci/base-tests.sh
  tests/dogfood.rs
Labels: S-waiting-on-review

#3494 Added `FORCED_RETURN` lint.
  CHANGELOG.md
  README.md
  clippy_lints/src/implicit_return.rs
  clippy_lints/src/lib.rs
  tests/ui/implicit_return.rs
  tests/ui/implicit_return.stderr
Labels: S-waiting-on-review

#3257 Don't try to determine sysroot. rustc_driver will use default value.
  src/driver.rs
  tests/compile-test.rs
  tests/dogfood.rs
Labels: S-waiting-on-review

#3509 Fix doc_markdown off by one issue
  clippy_lints/src/doc.rs
  tests/ui/doc.rs
  tests/ui/doc.stderr
Labels: S-waiting-on-review

#3552 Make integration tests fail on 'E0463'
  ci/integration-tests.sh
Labels: S-blocked

#3581 fix breakage from rust-lang/rust#57088
  tests/ui/builtin-type-shadow.rs
  tests/ui/builtin-type-shadow.stderr
  tests/ui/enum_variants.rs
  tests/ui/enum_variants.stderr
Labels: S-waiting-on-review

#3591 Match on ast/hir::ExprKind::Err
  clippy_lints/src/loops.rs
  clippy_lints/src/utils/author.rs
  clippy_lints/src/utils/hir_utils.rs
  clippy_lints/src/utils/inspector.rs
  clippy_lints/src/utils/sugg.rs
Labels: S-waiting-on-review

#3558 Merge new_without_default_derive into new_without_default
  CHANGELOG.md
  README.md
  clippy_lints/src/lib.rs
  clippy_lints/src/new_without_default.rs
  tests/ui/methods.rs
  tests/ui/methods.stderr
  tests/ui/new_without_default.rs
  tests/ui/new_without_default.stderr
  tests/ui/rename.rs
  tests/ui/rename.stderr
Labels: S-waiting-on-author

#3593 Update README local run command to remove syspath
  README.md
Labels: S-waiting-on-review

#3599 Use an FxHashSet for valid idents in documentation lint
  clippy_lints/src/doc.rs
  clippy_lints/src/lib.rs
Labels: S-waiting-on-review
