Repository rust-lang/rust-clippy, pull requests merged in 2019-12, with the labels that each got.

#4823 Add `let_underscore_must_use` lint
  CHANGELOG.md
  README.md
  clippy_lints/src/functions.rs
  clippy_lints/src/let_underscore.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/mod.rs
  src/lintlist/mod.rs
  tests/ui/let_underscore.rs
  tests/ui/let_underscore.stderr
Labels: L-lint, S-waiting-on-author

#4911 Update changelog for Rust 1.39 and 1.40
  CHANGELOG.md
Labels: S-waiting-on-review

#4948 rustup "Add span information to `ExprKind::Assign`"
  clippy_lints/src/assign_ops.rs
  clippy_lints/src/eval_order_dependence.rs
  clippy_lints/src/formatting.rs
  clippy_lints/src/functions.rs
  clippy_lints/src/let_if_seq.rs
  clippy_lints/src/loops.rs
  clippy_lints/src/misc.rs
  clippy_lints/src/misc_early.rs
  clippy_lints/src/slow_vector_initialization.rs
  clippy_lints/src/strings.rs
  clippy_lints/src/swap.rs
  clippy_lints/src/temporary_assignment.rs
  clippy_lints/src/utils/author.rs
  clippy_lints/src/utils/hir_utils.rs
  clippy_lints/src/utils/inspector.rs
  clippy_lints/src/write.rs
  tests/ui/author/for_loop.stdout
  tests/ui/missing_const_for_fn/could_be_const.rs
  tests/ui/missing_const_for_fn/could_be_const.stderr
Labels: S-waiting-on-review

#4947 Avoid needless_doctest_main on 'extern crate'
  clippy_lints/src/doc.rs
  tests/ui/needless_doc_main.rs
Labels: S-waiting-on-author

#4967 Rustup to rust-lang/rust#67151
  clippy_lints/src/missing_doc.rs
Labels: S-waiting-on-review

#4634 Add real suggestion to option_map_unwrap_or
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/option_map_unwrap_or.rs
  tests/ui/methods.rs
  tests/ui/methods.stderr
  tests/ui/option_map_unwrap_or.rs
  tests/ui/option_map_unwrap_or.stderr
Labels: S-waiting-on-author

#4970 Fix `replace_consts` lint documentation
  clippy_lints/src/replace_consts.rs
Labels: S-waiting-on-review
