Repository rust-lang/rust-clippy, pull requests merged in 2019-11, with the labels that each got.

#4714 Remove clippy plugin
  Cargo.toml
  src/lib.rs
Labels: C-needs-discussion, S-waiting-on-review

#4772 Use correct TypeckTables when hashing bodies
  clippy_lints/src/utils/hir_utils.rs
  tests/ui/crashes/ice-4760.rs
Labels: S-waiting-on-review

#4769 don't warn on CRLF in `with_newline` lints
  clippy_lints/src/lib.rs
  clippy_lints/src/write.rs
  tests/ui/print_with_newline.rs
  tests/ui/print_with_newline.stderr
  tests/ui/write_with_newline.rs
  tests/ui/write_with_newline.stderr
Labels: S-waiting-on-review

#4794 no more must-use-candidate impls
  clippy_lints/src/functions.rs
  tests/ui/must_use_candidates.fixed
  tests/ui/must_use_candidates.stderr
Labels: S-waiting-on-author

#4816 New lint: zst_offset
  CHANGELOG.md
  README.md
  clippy_lints/src/lib.rs
  clippy_lints/src/methods/mod.rs
  src/lintlist/mod.rs
  tests/ui/zero_offset.rs
  tests/ui/zero_offset.stderr
Labels: S-waiting-on-review

#4820 doc: fix the comment above the lint function
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-review

#4766 Fix false positive in derive_hash_xor_eq
  clippy_lints/src/derive.rs
  tests/ui/derive_hash_xor_eq.rs
  tests/ui/derive_hash_xor_eq.stderr
Labels: S-waiting-on-review

#4730 Fix check_infinite_loop (while_immutable_condition) by checking for break or return inside loop body
  clippy_lints/src/loops.rs
  tests/ui/infinite_loop.rs
  tests/ui/infinite_loop.stderr
Labels: S-waiting-on-author

#4852 rustup cargo install-upgrade
  .travis.yml
  appveyor.yml
  setup-toolchain.sh
Labels: S-waiting-on-rustup

#4848 make use of Result::map_or
  clippy_lints/src/escape.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/methods/mod.rs
  src/driver.rs
  src/lintlist/mod.rs
  tests/ui/result_map_unwrap_or_else.stderr
Labels: S-waiting-on-rustup

#4808 trigger string_lit_as_bytes when literal has escapes
  clippy_lints/src/strings.rs
  tests/ui/string_lit_as_bytes.fixed
  tests/ui/string_lit_as_bytes.rs
  tests/ui/string_lit_as_bytes.stderr
Labels: S-waiting-on-rustup

#4821 Add `as_conversions` lint
  CHANGELOG.md
  README.md
  clippy_lints/src/as_conversions.rs
  clippy_lints/src/lib.rs
  src/lintlist/mod.rs
  tests/ui/as_conversions.rs
  tests/ui/as_conversions.stderr
  tests/ui/types.fixed
  tests/ui/types.rs
Labels: L-lint, S-waiting-on-rustup

#4851 Remove negative float literal checks.
  clippy_lints/src/arithmetic.rs
  tests/ui/arithmetic.rs
Labels: S-waiting-on-rustup

#4847 fixing a typo
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-rustup

#4842 [comparison_chain] #4827 Check `core::cmp::Ord` is implemented
  clippy_lints/src/comparison_chain.rs
  tests/ui/comparison_chain.rs
  tests/ui/comparison_chain.stderr
Labels: S-waiting-on-rustup

#4845 Don't error on clippy.toml of dependencies
  src/driver.rs
Labels: S-waiting-on-rustup

#4856 build: check if RTIM is not installed
  setup-toolchain.sh
Labels: S-waiting-on-rustup

#4865 Fix master deployment
  .github/deploy.sh
Labels: S-waiting-on-review
