Repository rust-lang/rust-clippy, pull requests merged in 2019-03, with the labels that each got.

#3823 Place::Local(x) is now Place::Base(PlaceBase::Local(x))
  clippy_lints/src/redundant_clone.rs
Labels: S-blocked

#3844 Fix two missing_const_for_fn false positives
  clippy_lints/src/missing_const_for_fn.rs
  tests/ui/missing_const_for_fn/cant_be_const.rs
Labels: S-waiting-on-review

#3803 Cognitive Complexity (step 1 out of 3+): name changes
  CHANGELOG.md
  README.md
  clippy_lints/src/assign_ops.rs
  clippy_lints/src/cognitive_complexity.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/utils/attrs.rs
  clippy_lints/src/utils/conf.rs
  tests/ui-toml/conf_deprecated_key/clippy.toml
  tests/ui-toml/conf_deprecated_key/conf_deprecated_key.rs
  tests/ui-toml/conf_deprecated_key/conf_deprecated_key.stderr
  tests/ui-toml/good_toml_no_false_negatives/clippy.toml
  tests/ui-toml/good_toml_no_false_negatives/conf_no_false_negatives.rs
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
  tests/ui/cognitive_complexity.rs
  tests/ui/cognitive_complexity.stderr
  tests/ui/cognitive_complexity_attr_used.rs
  tests/ui/cognitive_complexity_attr_used.stderr
  tests/ui/collapsible_if.fixed
  tests/ui/collapsible_if.rs
  tests/ui/for_loop.rs
  tests/ui/if_same_then_else.rs
  tests/ui/match_same_arms.rs
  tests/ui/rename.rs
  tests/ui/rename.stderr
  tests/ui/renamed_builtin_attr.rs
  tests/ui/renamed_builtin_attr.stderr
  tests/ui/unknown_attribute.rs
  tests/ui/while_loop.rs
Labels: S-waiting-on-author

#3852 Refactor: Cleanup one part of assign_ops lint
  clippy_lints/src/assign_ops.rs
Labels: S-waiting-on-review

#3857 Document match_path, improve match_qpath docs
  clippy_lints/src/utils/mod.rs
Labels: S-waiting-on-review

#3733 Use the new rustc interface
  src/driver.rs
Labels: S-blocked

#3865 Run more doc tests
  clippy_lints/src/bit_mask.rs
  clippy_lints/src/eq_op.rs
  clippy_lints/src/matches.rs
  clippy_lints/src/misc.rs
  clippy_lints/src/needless_continue.rs
  clippy_lints/src/swap.rs
  clippy_lints/src/types.rs
  clippy_lints/src/write.rs
Labels: S-waiting-on-author

#3872 Remove some unused features and `error-pattern`s
  src/driver.rs
  src/lib.rs
  src/main.rs
Labels: S-waiting-on-review

#3869 Fix `use_self` false positive on nested functions
  clippy_lints/src/use_self.rs
  tests/ui/use_self.fixed
  tests/ui/use_self.rs
  tests/ui/use_self.stderr
Labels: S-waiting-on-review

#3877 casting integer literal to float is unnecessary
  clippy_lints/src/types.rs
  tests/ui/cast.rs
  tests/ui/cast.stderr
  tests/ui/cast_lossless_float.fixed
  tests/ui/cast_lossless_float.rs
  tests/ui/cast_lossless_float.stderr
  tests/ui/cast_size.rs
  tests/ui/cast_size.stderr
  tests/ui/float_cmp_const.rs
  tests/ui/float_cmp_const.stderr
Labels: S-waiting-on-author
