Repository rust-lang/rust-clippy, pull requests merged in 2020-11, with the labels that each got.

#6037 single_char_insert_str: lint using insert_str() on single-char literals and suggest insert()
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/utils/paths.rs
  src/lintlist/mod.rs
  tests/ui/single_char_add_str.fixed
  tests/ui/single_char_add_str.rs
  tests/ui/single_char_add_str.stderr
  tests/ui/single_char_pattern.fixed
  tests/ui/single_char_pattern.rs
  tests/ui/single_char_pattern.stderr
  tests/ui/single_char_push_str.fixed
  tests/ui/single_char_push_str.rs
  tests/ui/single_char_push_str.stderr
Labels: S-waiting-on-author

#6101 Add lint: from_iter_instead_of_collect
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/lifetimes.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/utils/paths.rs
  src/lintlist/mod.rs
  tests/ui/from_iter_instead_of_collect.rs
  tests/ui/from_iter_instead_of_collect.stderr
  tests/ui/get_unwrap.fixed
  tests/ui/get_unwrap.rs
Labels: S-waiting-on-author

#6165 Add lint 'ref_option_ref' #1377
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/ref_option_ref.rs
  src/lintlist/mod.rs
  tests/ui/option_if_let_else.fixed
  tests/ui/option_if_let_else.rs
  tests/ui/option_if_let_else.stderr
  tests/ui/ref_option_ref.rs
  tests/ui/ref_option_ref.stderr
Labels: S-waiting-on-review

#6233 add manual_ok_or lint
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_ok_or.rs
  src/lintlist/mod.rs
  tests/ui/manual_ok_or.fixed
  tests/ui/manual_ok_or.rs
  tests/ui/manual_ok_or.stderr
Labels: S-waiting-on-review

#6270 Clarify allow/warn/deny documentation. Remove enable/disable.
  README.md
Labels: S-waiting-on-review

#6284 Use const sym where possible
  clippy_lints/src/attrs.rs
  clippy_lints/src/booleans.rs
  clippy_lints/src/bytecount.rs
  clippy_lints/src/cognitive_complexity.rs
  clippy_lints/src/doc.rs
  clippy_lints/src/explicit_write.rs
  clippy_lints/src/fallible_impl_from.rs
  clippy_lints/src/format.rs
  clippy_lints/src/functions.rs
  clippy_lints/src/get_last_with_len.rs
  clippy_lints/src/if_let_some_result.rs
  clippy_lints/src/inherent_to_string.rs
  clippy_lints/src/inline_fn_without_body.rs
  clippy_lints/src/loops.rs
  clippy_lints/src/manual_non_exhaustive.rs
  clippy_lints/src/manual_unwrap_or.rs
  clippy_lints/src/map_clone.rs
  clippy_lints/src/map_identity.rs
  clippy_lints/src/map_unit_fn.rs
  clippy_lints/src/match_on_vec_items.rs
  clippy_lints/src/matches.rs
  clippy_lints/src/methods/inefficient_to_string.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/option_map_unwrap_or.rs
  clippy_lints/src/methods/unnecessary_lazy_eval.rs
  clippy_lints/src/missing_doc.rs
  clippy_lints/src/missing_inline.rs
  clippy_lints/src/needless_borrow.rs
  clippy_lints/src/needless_pass_by_value.rs
  clippy_lints/src/new_without_default.rs
  clippy_lints/src/non_expressive_names.rs
  clippy_lints/src/option_if_let_else.rs
  clippy_lints/src/panic_in_result_fn.rs
  clippy_lints/src/partialeq_ne_impl.rs
  clippy_lints/src/pass_by_ref_or_value.rs
  clippy_lints/src/ptr.rs
  clippy_lints/src/ptr_offset_with_cast.rs
  clippy_lints/src/question_mark.rs
  clippy_lints/src/ranges.rs
  clippy_lints/src/redundant_clone.rs
  clippy_lints/src/repeat_once.rs
  clippy_lints/src/returns.rs
  clippy_lints/src/strings.rs
  clippy_lints/src/swap.rs
  clippy_lints/src/try_err.rs
  clippy_lints/src/types.rs
  clippy_lints/src/unnecessary_sort_by.rs
  clippy_lints/src/unwrap.rs
  clippy_lints/src/unwrap_in_result.rs
  clippy_lints/src/useless_conversion.rs
  clippy_lints/src/utils/internal_lints.rs
  clippy_lints/src/utils/mod.rs
  clippy_lints/src/write.rs
  tests/ui/match_type_on_diag_item.stderr
Labels: S-waiting-on-review

#5911 Add lint for 'field_reassign_with_default` #568
  CHANGELOG.md
  clippy_lints/src/default.rs
  clippy_lints/src/default_trait_access.rs
  clippy_lints/src/lib.rs
  src/lintlist/mod.rs
  tests/ui/field_reassign_with_default.rs
  tests/ui/field_reassign_with_default.stderr
Labels: S-waiting-on-author

#6294 Fix suggestion to add unneeded space in `manual_async`
  clippy_lints/src/manual_async_fn.rs
  clippy_lints/src/unused_unit.rs
  clippy_lints/src/utils/mod.rs
  tests/ui/manual_async_fn.fixed
  tests/ui/manual_async_fn.rs
  tests/ui/manual_async_fn.stderr
Labels: S-waiting-on-review

#6272 Fix unnecessary_lazy_eval suggestion applicability
  clippy_lints/src/methods/unnecessary_lazy_eval.rs
  tests/ui/unnecessary_lazy_eval_unfixable.rs
  tests/ui/unnecessary_lazy_eval_unfixable.stderr
Labels: S-waiting-on-review

#6110 "Respect" enums in `interior_mutable_const`
  clippy_lints/src/non_copy_const.rs
  tests/ui/borrow_interior_mutable_const/auxiliary/helper.rs
  tests/ui/borrow_interior_mutable_const/enums.rs
  tests/ui/borrow_interior_mutable_const/enums.stderr
  tests/ui/borrow_interior_mutable_const/others.rs
  tests/ui/borrow_interior_mutable_const/others.stderr
  tests/ui/borrow_interior_mutable_const/traits.rs
  tests/ui/borrow_interior_mutable_const/traits.stderr
  tests/ui/declare_interior_mutable_const/enums.rs
  tests/ui/declare_interior_mutable_const/enums.stderr
  tests/ui/declare_interior_mutable_const/others.rs
  tests/ui/declare_interior_mutable_const/others.stderr
  tests/ui/declare_interior_mutable_const/traits.rs
  tests/ui/declare_interior_mutable_const/traits.stderr
Labels: S-waiting-on-review

#6134 Check when `from_utf8` is called from sliced byte array from string
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/strings.rs
  clippy_lints/src/utils/paths.rs
  src/lintlist/mod.rs
  tests/ui/string_from_utf8_as_bytes.fixed
  tests/ui/string_from_utf8_as_bytes.rs
  tests/ui/string_from_utf8_as_bytes.stderr
Labels: S-waiting-on-review

#6287 Readme improvements
  README.md
Labels: S-waiting-on-review

#6298 Fix `await_holding_refcell_ref` examples for clarify
  clippy_lints/src/await_holding_invalid.rs
Labels: S-waiting-on-review

#6304 FROM_ITER_INSTEAD_OF_COLLECT: avoid unwrapping unconditionally
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-review

#6301 do not trigger map_clone in the case of &mut
  clippy_lints/src/map_clone.rs
  tests/ui/map_clone.fixed
  tests/ui/map_clone.rs
Labels: S-waiting-on-review

#6205 Enable empty_loop lint for no_std crates
  clippy_lints/src/loops.rs
  clippy_lints/src/utils/mod.rs
  tests/ui/crashes/ice-360.stderr
  tests/ui/empty_loop.stderr
  tests/ui/empty_loop_no_std.rs
  tests/ui/empty_loop_no_std.stderr
Labels: S-waiting-on-author

#6271 Fix vec_box scope error
  clippy_lints/src/types.rs
  tests/ui/vec_box_sized.fixed
  tests/ui/vec_box_sized.rs
  tests/ui/vec_box_sized.stderr
Labels: S-waiting-on-review

#6293 Fix example used in cargo_common_metadata
  clippy_lints/src/cargo_common_metadata.rs
Labels: S-waiting-on-review

#6267 Fix or_fun_call for index operator
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/utils/eager_or_lazy.rs
  tests/ui/or_fun_call.fixed
  tests/ui/or_fun_call.rs
  tests/ui/or_fun_call.stderr
Labels: S-waiting-on-review

#6278 Fix bad suggestions for `deref_addrof` and `try_err` lints
  clippy_lints/src/reference.rs
  clippy_lints/src/try_err.rs
  tests/ui/deref_addrof.fixed
  tests/ui/deref_addrof.rs
  tests/ui/deref_addrof.stderr
  tests/ui/try_err.fixed
  tests/ui/try_err.rs
  tests/ui/try_err.stderr
Labels: S-waiting-on-review

#6305 Add `let_underscore_drop`
  CHANGELOG.md
  clippy_lints/src/let_underscore.rs
  clippy_lints/src/lib.rs
  src/lintlist/mod.rs
  tests/ui/filter_methods.rs
  tests/ui/filter_methods.stderr
  tests/ui/let_underscore_drop.rs
  tests/ui/let_underscore_drop.stderr
  tests/ui/map_clone.fixed
  tests/ui/map_clone.rs
  tests/ui/map_clone.stderr
  tests/ui/map_flatten.fixed
  tests/ui/map_flatten.rs
  tests/ui/map_flatten.stderr
Labels: S-waiting-on-author

#6269 Fix map_clone with deref and clone
  clippy_lints/src/map_clone.rs
  tests/ui/map_clone.fixed
  tests/ui/map_clone.rs
Labels: S-waiting-on-author

#6329 Rustup
  clippy_lints/src/utils/ast_utils.rs
  tests/ui/crashes/ice-6250.stderr
Labels: S-waiting-on-review

#6320 Fix suggestion in `manual_range_contains` when using float
  clippy_lints/src/ranges.rs
  tests/ui/range_contains.fixed
  tests/ui/range_contains.rs
  tests/ui/range_contains.stderr
Labels: S-waiting-on-review

#6336 Rustup
  clippy_lints/src/utils/sugg.rs
  tests/ui/cast_ref_to_mut.rs
  tests/ui/cast_ref_to_mut.stderr
Labels: S-waiting-on-review

#6119 Add a case to `lint_search_is_some` to handle searching strings
  clippy_lints/src/methods/mod.rs
  src/lintlist/mod.rs
  tests/ui/methods.rs
  tests/ui/methods.stderr
  tests/ui/search_is_some.rs
  tests/ui/search_is_some.stderr
  tests/ui/search_is_some_fixable.fixed
  tests/ui/search_is_some_fixable.rs
  tests/ui/search_is_some_fixable.stderr
Labels: S-waiting-on-author

#6337 Remove `expect()` calls to avoid ICEs in `deref_addrof` lint
  clippy_lints/src/reference.rs
  tests/ui/crashes/ice-6332.rs
Labels: S-waiting-on-review

#6070 Add new lint `unnecessary_wrap`
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/methods/bind_instead_of_map.rs
  clippy_lints/src/redundant_clone.rs
  clippy_lints/src/unnecessary_wraps.rs
  clippy_lints/src/utils/mod.rs
  clippy_lints/src/utils/visitors.rs
  src/lintlist/mod.rs
  tests/ui/derive_ord_xor_partial_ord.rs
  tests/ui/derive_ord_xor_partial_ord.stderr
  tests/ui/doc_errors.rs
  tests/ui/doc_errors.stderr
  tests/ui/drop_ref.rs
  tests/ui/drop_ref.stderr
  tests/ui/forget_ref.rs
  tests/ui/forget_ref.stderr
  tests/ui/let_underscore_must_use.rs
  tests/ui/let_underscore_must_use.stderr
  tests/ui/manual_unwrap_or.fixed
  tests/ui/manual_unwrap_or.rs
  tests/ui/map_err.rs
  tests/ui/map_err.stderr
  tests/ui/map_flatten.fixed
  tests/ui/map_flatten.rs
  tests/ui/map_flatten.stderr
  tests/ui/needless_lifetimes.rs
  tests/ui/option_map_unit_fn_fixable.fixed
  tests/ui/option_map_unit_fn_fixable.rs
  tests/ui/option_map_unit_fn_fixable.stderr
  tests/ui/option_option.rs
  tests/ui/option_option.stderr
  tests/ui/or_fun_call.fixed
  tests/ui/or_fun_call.rs
  tests/ui/or_fun_call.stderr
  tests/ui/panic_in_result_fn.rs
  tests/ui/panic_in_result_fn.stderr
  tests/ui/question_mark.fixed
  tests/ui/question_mark.rs
  tests/ui/question_mark.stderr
  tests/ui/redundant_pattern_matching.fixed
  tests/ui/redundant_pattern_matching.rs
  tests/ui/redundant_pattern_matching.stderr
  tests/ui/result_unit_error.rs
  tests/ui/result_unit_error.stderr
  tests/ui/try_err.fixed
  tests/ui/try_err.rs
  tests/ui/try_err.stderr
  tests/ui/unit_arg.rs
  tests/ui/unit_arg.stderr
  tests/ui/unnecessary_clone.rs
  tests/ui/unnecessary_wraps.rs
  tests/ui/unnecessary_wraps.stderr
  tests/ui/useless_conversion.fixed
  tests/ui/useless_conversion.rs
  tests/ui/useless_conversion.stderr
  tests/ui/wildcard_imports.fixed
  tests/ui/wildcard_imports.rs
  tests/ui/wildcard_imports.stderr
Labels: S-waiting-on-review

#6340 Improve doc about `map_clone`
  clippy_lints/src/map_clone.rs
Labels: S-waiting-on-review

#6345 Revert "Add `rustfmt::skip` as a work around"
  tests/ui/cast_ref_to_mut.rs
  tests/ui/cast_ref_to_mut.stderr
Labels: S-waiting-on-review

#6347 Changelog Rust 1.48
  CHANGELOG.md
  doc/changelog_update.md
Labels: S-waiting-on-review

#6354 Downgrade the await holding lints from correctness
  clippy_lints/src/await_holding_invalid.rs
  clippy_lints/src/lib.rs
  src/lintlist/mod.rs
Labels: S-waiting-on-review

#6364 revisiting a typo
  tests/ui/manual_ok_or.fixed
  tests/ui/manual_ok_or.rs
Labels: S-waiting-on-review

#6363 a typo
  clippy_lints/src/assertions_on_constants.rs
Labels: S-waiting-on-review

#6361 Small grammar, punctuation, and code style improvements to docs
  clippy_lints/src/len_zero.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/regex.rs
  clippy_lints/src/unit_return_expecting_ord.rs
  clippy_lints/src/useless_conversion.rs
  src/lintlist/mod.rs
Labels: S-waiting-on-review

#6317 Add exteranal macros for as_conversions
  tests/ui/as_conversions.rs
  tests/ui/as_conversions.stderr
  tests/ui/auxiliary/macro_rules.rs
Labels: S-waiting-on-review

#6369 Disable unnecessary_cast for cfg-dependant types
  clippy_lints/src/types.rs
  tests/ui/unnecessary_cast.rs
Labels: S-waiting-on-review

#6201 Add support for minimum supported rust version
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_non_exhaustive.rs
  clippy_lints/src/manual_strip.rs
  clippy_lints/src/matches.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/utils/attrs.rs
  clippy_lints/src/utils/conf.rs
  clippy_lints/src/utils/mod.rs
  tests/ui-toml/invalid_min_rust_version/clippy.toml
  tests/ui-toml/invalid_min_rust_version/invalid_min_rust_version.rs
  tests/ui-toml/invalid_min_rust_version/invalid_min_rust_version.stderr
  tests/ui-toml/min_rust_version/clippy.toml
  tests/ui-toml/min_rust_version/min_rust_version.rs
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
  tests/ui/min_rust_version_attr.rs
  tests/ui/min_rust_version_invalid_attr.rs
  tests/ui/min_rust_version_invalid_attr.stderr
  tests/ui/min_rust_version_multiple_inner_attr.rs
  tests/ui/min_rust_version_multiple_inner_attr.stderr
  tests/ui/min_rust_version_no_patch.rs
  tests/ui/min_rust_version_outer_attr.rs
  tests/ui/min_rust_version_outer_attr.stderr
Labels: S-waiting-on-review

#6333 Added lint str_to_string
  clippy_lints/src/deprecated_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/strings.rs
  src/lintlist/mod.rs
  tests/ui/deprecated.rs
  tests/ui/deprecated.stderr
  tests/ui/deprecated_old.rs
  tests/ui/deprecated_old.stderr
  tests/ui/str_to_string.rs
  tests/ui/str_to_string.stderr
  tests/ui/string_to_string.rs
  tests/ui/string_to_string.stderr
Labels: S-waiting-on-review

#6379 update readme for specifying msrv
  README.md
Labels: S-waiting-on-review

#6362 Fix rust-lang/rust#79255 - Incorrect try suggestion for float cast
  clippy_lints/src/types.rs
  tests/ui/unnecessary_cast_fixable.fixed
  tests/ui/unnecessary_cast_fixable.rs
  tests/ui/unnecessary_cast_fixable.stderr
Labels: S-waiting-on-author

#6389 Rustup
  clippy_dev/src/update_lints.rs
  clippy_lints/src/attrs.rs
  src/driver.rs
  src/lintlist/lint.rs
  src/lintlist/mod.rs
Labels: S-waiting-on-review

#6386 Remove mention of possibility to specify the MSRV with a tilde/caret
  README.md
Labels: S-waiting-on-review

#6360 Trigger modulo_one lint also on -1.
  clippy_lints/src/misc.rs
  tests/ui/modulo_one.rs
  tests/ui/modulo_one.stderr
Labels: S-waiting-on-review

#6086 Add suspicious_operation_groupings lint
  CHANGELOG.md
  clippy_lints/src/eq_op.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/suspicious_operation_groupings.rs
  clippy_lints/src/utils/ast_utils.rs
  clippy_lints/src/utils/ast_utils/ident_iter.rs
  tests/ui/eq_op.rs
  tests/ui/eq_op.stderr
  tests/ui/suspicious_operation_groupings.rs
  tests/ui/suspicious_operation_groupings.stderr
Labels: S-waiting-on-review

#6396 Rustup?
  clippy_lints/src/items_after_statements.rs
  clippy_lints/src/redundant_closure_call.rs
  tests/ui/item_after_statement.rs
Labels: S-waiting-on-review

#6290 do not trigger MATCH_LIKE_MATCHES_MACRO lint with attrs
  clippy_lints/src/matches.rs
Labels: S-waiting-on-rustup

#6397 Fix a false positive in `unnecessary_wraps`
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/unnecessary_wraps.rs
  clippy_lints/src/utils/mod.rs
  tests/ui/unnecessary_wraps.rs
Labels: S-waiting-on-rustup

#6398 issue_6357 update unreachable macro usage
  clippy_lints/src/panic_unimplemented.rs
  tests/ui/panicking_macros.stderr
Labels: S-waiting-on-author
