Repository rust-lang/rust-clippy, pull requests merged in 2020-08, with the labels that each got.

#5864 Fix ui-cargo tests in CI
  tests/compile-test.rs
Labels: S-waiting-on-review

#5856 Remove old Symbol reexport
  clippy_lints/src/attrs.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/lifetimes.rs
  clippy_lints/src/loops.rs
  clippy_lints/src/shadow.rs
  clippy_lints/src/utils/mod.rs
Labels: S-waiting-on-rustup

#5852 Add lint for duplicate methods of trait bounds
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/trait_bounds.rs
  src/lintlist/mod.rs
  tests/ui/trait_duplication_in_bounds.rs
  tests/ui/trait_duplication_in_bounds.stderr
Labels: S-waiting-on-rustup

#5846 Handle mapping to Option in `map_flatten` lint
  clippy_lints/src/methods/mod.rs
  tests/ui/map_flatten.fixed
  tests/ui/map_flatten.rs
  tests/ui/map_flatten.stderr
Labels: S-waiting-on-rustup

#5848 Add derive_ord_xor_partial_ord lint
  CHANGELOG.md
  clippy_lints/src/derive.rs
  clippy_lints/src/lib.rs
  src/lintlist/mod.rs
  tests/ui/derive_ord_xor_partial_ord.rs
  tests/ui/derive_ord_xor_partial_ord.stderr
Labels: S-waiting-on-rustup

#5837 needless_collect: catch x: Vec<_> = iter.collect(); x.into_iter() ...
  clippy_lints/src/loops.rs
  tests/ui/needless_collect_indirect.rs
  tests/ui/needless_collect_indirect.stderr
Labels: S-waiting-on-rustup

#5865 Remove obsolete known problems unnecessary_fold
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-review

#5857 try_err: Consider Try impl for Poll when generating suggestions
  clippy_lints/src/try_err.rs
  clippy_lints/src/utils/paths.rs
  tests/ui/try_err.fixed
  tests/ui/try_err.rs
  tests/ui/try_err.stderr
Labels: S-waiting-on-review

#5859 manual_async_fn: take input lifetimes into account
  clippy_lints/src/manual_async_fn.rs
  tests/ui/await_holding_lock.rs
  tests/ui/await_holding_lock.stderr
  tests/ui/manual_async_fn.fixed
  tests/ui/manual_async_fn.rs
  tests/ui/manual_async_fn.stderr
Labels: S-waiting-on-review

#5809 Stable sort primitive
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/stable_sort_primitive.rs
  clippy_lints/src/utils/mod.rs
  src/lintlist/mod.rs
  tests/ui/stable_sort_primitive.fixed
  tests/ui/stable_sort_primitive.rs
  tests/ui/stable_sort_primitive.stderr
  tests/ui/unnecessary_sort_by.fixed
  tests/ui/unnecessary_sort_by.rs
  tests/ui/unnecessary_sort_by.stderr
Labels: S-waiting-on-review

#5877 Fix ICE in `loops` module
  clippy_lints/src/loops.rs
  tests/ui/crashes/ice-5872.rs
  tests/ui/crashes/ice-5872.stderr
  tests/ui/needless_collect.fixed
  tests/ui/needless_collect.rs
  tests/ui/needless_collect.stderr
Labels: S-waiting-on-rustup

#5882 Prevent compile parts of rustc when using `cargo dev ra-setup`
  clippy_dev/src/ra_setup.rs
Labels: S-waiting-on-review

#5874 Make the docs clearer for new contributors
  CONTRIBUTING.md
  doc/basics.md
Labels: S-waiting-on-rustup

#5871 Lint .min(x).max(y) with x < y
  clippy_lints/src/minmax.rs
  tests/ui/min_max.rs
  tests/ui/min_max.stderr
Labels: S-waiting-on-rustup

#5869 New lint against `Self` as an arbitrary self type
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/needless_arbitrary_self_type.rs
  clippy_lints/src/trait_bounds.rs
  src/lintlist/mod.rs
  tests/ui/extra_unused_lifetimes.rs
  tests/ui/extra_unused_lifetimes.stderr
  tests/ui/len_without_is_empty.rs
  tests/ui/len_without_is_empty.stderr
  tests/ui/len_zero.fixed
  tests/ui/len_zero.rs
  tests/ui/needless_arbitrary_self_type.fixed
  tests/ui/needless_arbitrary_self_type.rs
  tests/ui/needless_arbitrary_self_type.stderr
  tests/ui/option_map_unit_fn_fixable.fixed
  tests/ui/option_map_unit_fn_fixable.rs
  tests/ui/result_map_unit_fn_fixable.fixed
  tests/ui/result_map_unit_fn_fixable.rs
Labels: S-waiting-on-rustup

#5870 enable #[allow(clippy::unsafe_derive_deserialize)]
  clippy_lints/src/derive.rs
  tests/ui/unsafe_derive_deserialize.rs
Labels: S-waiting-on-rustup

#5825 Add the new lint `same_item_push`
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/loops.rs
  src/lintlist/mod.rs
  tests/ui/same_item_push.rs
  tests/ui/same_item_push.stderr
Labels: S-waiting-on-rustup

#5887 Fix CHANGELOG's commit range links
  CHANGELOG.md
Labels: S-waiting-on-review

#5889 Avoid or_fun_call for const_fn with no args
  clippy_lints/src/utils/mod.rs
  tests/ui/or_fun_call.fixed
  tests/ui/or_fun_call.rs
Labels: S-waiting-on-review

#5888 make a bunch of lints texts adhere to rustc dev guide
  clippy_lints/src/attrs.rs
  clippy_lints/src/bytecount.rs
  clippy_lints/src/checked_conversions.rs
  clippy_lints/src/default_trait_access.rs
  clippy_lints/src/double_comparison.rs
  clippy_lints/src/double_parens.rs
  clippy_lints/src/drop_bounds.rs
  clippy_lints/src/functions.rs
  clippy_lints/src/misc_early.rs
  clippy_lints/src/needless_bool.rs
  clippy_lints/src/neg_cmp_op_on_partial_ord.rs
  clippy_lints/src/neg_multiply.rs
  clippy_lints/src/overflow_check_conditional.rs
  clippy_lints/src/path_buf_push_overwrite.rs
  clippy_lints/src/ptr.rs
  clippy_lints/src/ranges.rs
  clippy_lints/src/redundant_static_lifetimes.rs
  clippy_lints/src/reference.rs
  clippy_lints/src/suspicious_trait_impl.rs
  clippy_lints/src/unwrap.rs
  clippy_lints/src/utils/attrs.rs
  src/lintlist/mod.rs
  tests/ui-toml/functions_maxlines/test.stderr
  tests/ui/bool_comparison.stderr
  tests/ui/builtin-type-shadow.stderr
  tests/ui/bytecount.stderr
  tests/ui/checked_conversions.stderr
  tests/ui/checked_unwrap/complex_conditionals.stderr
  tests/ui/checked_unwrap/complex_conditionals_nested.stderr
  tests/ui/checked_unwrap/simple_conditionals.stderr
  tests/ui/cmp_null.stderr
  tests/ui/default_trait_access.stderr
  tests/ui/double_comparison.stderr
  tests/ui/double_parens.stderr
  tests/ui/drop_bounds.stderr
  tests/ui/empty_line_after_outer_attribute.stderr
  tests/ui/functions_maxlines.stderr
  tests/ui/neg_cmp_op_on_partial_ord.stderr
  tests/ui/neg_multiply.stderr
  tests/ui/overflow_check_conditional.stderr
  tests/ui/path_buf_push_overwrite.stderr
  tests/ui/range.stderr
  tests/ui/redundant_static_lifetimes.stderr
  tests/ui/redundant_static_lifetimes_multiple.stderr
  tests/ui/renamed_builtin_attr.stderr
  tests/ui/suspicious_arithmetic_impl.stderr
  tests/ui/unknown_attribute.stderr
  tests/ui/unnecessary_ref.stderr
  tests/ui/unneeded_field_pattern.stderr
Labels: S-waiting-on-review

#5892 unnecessary-mut-passed: make lint message say if fn is a function or a method
  clippy_lints/src/mut_reference.rs
  tests/ui/mut_reference.stderr
Labels: S-waiting-on-review

#5885 Add example of false positive to PTR_ARG docs.
  clippy_lints/src/ptr.rs
Labels: S-waiting-on-review

#5893 fix remaining lint messages
  clippy_lints/src/duration_subsec.rs
  clippy_lints/src/enum_clike.rs
  clippy_lints/src/enum_variants.rs
  clippy_lints/src/if_let_some_result.rs
  clippy_lints/src/if_not_else.rs
  clippy_lints/src/implicit_saturating_sub.rs
  clippy_lints/src/inherent_impl.rs
  clippy_lints/src/int_plus_one.rs
  clippy_lints/src/map_clone.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/mutex_atomic.rs
  clippy_lints/src/stable_sort_primitive.rs
  clippy_lints/src/use_self.rs
  src/lintlist/mod.rs
  tests/ui/duration_subsec.stderr
  tests/ui/enum_clike_unportable_variant.stderr
  tests/ui/enum_variants.stderr
  tests/ui/if_let_some_result.stderr
  tests/ui/if_not_else.stderr
  tests/ui/impl.stderr
  tests/ui/implicit_saturating_sub.stderr
  tests/ui/int_plus_one.stderr
  tests/ui/iter_next_slice.stderr
  tests/ui/map_clone.stderr
  tests/ui/mutex_atomic.stderr
  tests/ui/stable_sort_primitive.stderr
Labels: S-waiting-on-rustup

#5884 Add the other overloadable operations to suspicious_arithmetic_impl
  clippy_lints/src/suspicious_trait_impl.rs
  tests/ui/suspicious_arithmetic_impl.rs
  tests/ui/suspicious_arithmetic_impl.stderr
Labels: S-waiting-on-author

#5897 write.rs: don't clone TokenStream
  clippy_lints/src/write.rs
Labels: S-waiting-on-rustup

#5900 Fix: keep parenthesis for suggestion in `useless_conversion` lint
  clippy_lints/src/useless_conversion.rs
  tests/ui/useless_conversion.fixed
  tests/ui/useless_conversion.rs
  tests/ui/useless_conversion.stderr
Labels: S-waiting-on-review

#5899 Change Rc<Box<T>> recommendation to be Rc<T> instead of Box<T>
  clippy_lints/src/types.rs
  tests/ui/redundant_allocation.fixed
  tests/ui/redundant_allocation.stderr
Labels: S-waiting-on-review

#5901 Add reference to rustc-dev-guide about lint message
  doc/adding_lints.md
Labels: S-waiting-on-review

#5905 docs: typo in `temporary_cstring_as_ptr`: s/point/&s
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-review

#5912 Parse doctests in needless_doctest_main
  clippy_lints/src/doc.rs
  tests/ui/needless_doc_main.rs
  tests/ui/needless_doc_main.stderr
Labels: S-waiting-on-review

#5831 Don't use `to_string` in impl Display
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/to_string_in_display.rs
  src/lintlist/mod.rs
  tests/ui/to_string_in_display.rs
  tests/ui/to_string_in_display.stderr
Labels: S-waiting-on-author

#5881 Lint `push_str` with a single-character string literal
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/utils/paths.rs
  src/lintlist/mod.rs
  tests/ui/single_char_push_str.fixed
  tests/ui/single_char_push_str.rs
  tests/ui/single_char_push_str.stderr
Labels: S-waiting-on-review

#5903 Needless return
  clippy_lints/src/let_and_return.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/returns.rs
  clippy_lints/src/unused_unit.rs
  src/lintlist/mod.rs
  tests/ui/needless_return.fixed
  tests/ui/needless_return.rs
  tests/ui/needless_return.stderr
Labels: S-waiting-on-review

#5907 appreciative too_large_for_stack in useless `vec!`
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/conf.rs
  clippy_lints/src/vec.rs
  tests/ui/vec.fixed
  tests/ui/vec.rs
Labels: S-waiting-on-review

#5725 should_impl_trait - ignore methods with lifetime params
  clippy_lints/src/methods/mod.rs
  tests/ui/methods.rs
  tests/ui/methods.stderr
  tests/ui/should_impl_trait/corner_cases.rs
  tests/ui/should_impl_trait/method_list_1.rs
  tests/ui/should_impl_trait/method_list_1.stderr
  tests/ui/should_impl_trait/method_list_2.rs
  tests/ui/should_impl_trait/method_list_2.stderr
Labels: S-waiting-on-rustup

#5720 Add unnecessary lazy evaluation lint
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/unnecessary_lazy_eval.rs
  src/lintlist/mod.rs
  tests/ui/unnecessary_lazy_eval.fixed
  tests/ui/unnecessary_lazy_eval.rs
  tests/ui/unnecessary_lazy_eval.stderr
Labels: S-waiting-on-author

#5894 Warn about explicit self-assignment
  CHANGELOG.md
  clippy_lints/src/assign_ops.rs
  clippy_lints/src/booleans.rs
  clippy_lints/src/copies.rs
  clippy_lints/src/double_comparison.rs
  clippy_lints/src/eq_op.rs
  clippy_lints/src/floating_point_arithmetic.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/question_mark.rs
  clippy_lints/src/self_assignment.rs
  clippy_lints/src/swap.rs
  clippy_lints/src/utils/hir_utils.rs
  clippy_lints/src/utils/internal_lints.rs
  clippy_lints/src/utils/mod.rs
  src/lintlist/mod.rs
  tests/ui/self_assignment.rs
  tests/ui/self_assignment.stderr
Labels: S-waiting-on-review

#5915 deps: bump cargo_metadata and semver
  Cargo.toml
  clippy_lints/Cargo.toml
Labels: S-waiting-on-review

#5908 Fix FP for `same_item_push`
  clippy_lints/src/loops.rs
  tests/ui/same_item_push.rs
Labels: S-waiting-on-author

#5919 transmute: avoid suggesting from/to bits in const
  clippy_lints/src/transmute.rs
  tests/ui/transmute.rs
  tests/ui/transmute.stderr
  tests/ui/transmute_float_to_int.rs
  tests/ui/transmute_float_to_int.stderr
Labels: S-waiting-on-review

#5935 stable_sort_primitive: print the type that is being sorted in the lint message
  clippy_lints/src/stable_sort_primitive.rs
  clippy_lints/src/utils/mod.rs
  tests/ui/stable_sort_primitive.stderr
Labels: S-waiting-on-review

#5920 Fix FP for `redundant_closure_call`
  clippy_lints/src/redundant_closure_call.rs
  tests/ui/redundant_closure_call_early.stderr
  tests/ui/redundant_closure_call_fixable.stderr
  tests/ui/redundant_closure_call_late.rs
Labels: S-waiting-on-review

#5947 Improve documentation related to the sync process
  CONTRIBUTING.md
Labels: S-waiting-on-review

#5952 Added a lint which corrects expressions like (a - b) < f32::EPSILON, according to #5819
  CHANGELOG.md
  clippy_lints/src/float_equality_without_abs.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/paths.rs
  src/lintlist/mod.rs
  tests/ui/float_equality_without_abs.rs
  tests/ui/float_equality_without_abs.stderr
Labels: S-waiting-on-rustup

#5958 Various fmt test improvements
  .cargo/config
  tests/fmt.rs
Labels: S-waiting-on-review

#5961 Re-enable len_zero for ranges now that `is_empty` is stable on them
  clippy_lints/src/len_zero.rs
  tests/ui/len_zero.fixed
  tests/ui/len_zero.rs
  tests/ui/len_zero_ranges.fixed
  tests/ui/len_zero_ranges.rs
  tests/ui/len_zero_ranges.stderr
Labels: S-waiting-on-review

#5951 Fix incorrect suggestion when `clone_on_ref_ptr` is triggered in macros
  clippy_lints/src/methods/mod.rs
  tests/ui/unnecessary_clone.rs
  tests/ui/unnecessary_clone.stderr
Labels: S-waiting-on-review

#5964 Fix typo
  clippy_lints/src/utils/mod.rs
Labels: S-waiting-on-review

#5949 Fix fp in `borrow_interior_mutable_const`
  clippy_lints/src/non_copy_const.rs
  tests/ui/borrow_interior_mutable_const.rs
  tests/ui/borrow_interior_mutable_const.stderr
Labels: S-waiting-on-review

#5946 Fix `let_and_return` bad suggestion
  clippy_lints/src/returns.rs
  tests/ui/let_and_return.rs
  tests/ui/let_and_return.stderr
Labels: S-waiting-on-author

#5966 Corrects the float_equality_without_abs lint
  clippy_lints/src/float_equality_without_abs.rs
  tests/ui/float_equality_without_abs.stderr
Labels: S-waiting-on-review

#5968 Fix the wrong use of `snippet_with_applicability`
  clippy_lints/src/write.rs
Labels: S-waiting-on-review

#5957 Adding new lint to prevent usage of 'unwrap' inside functions that re…
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/unwrap_in_result.rs
  src/lintlist/mod.rs
  tests/ui/unwrap_in_result.rs
  tests/ui/unwrap_in_result.stderr
Labels: S-waiting-on-review

#5971 Fix FP in `to_string_in_display`
  clippy_lints/src/to_string_in_display.rs
  tests/ui/to_string_in_display.rs
Labels: S-waiting-on-review

#5774 Fix FP in `new_ret_no_self`: trigger in trait def instead of impl block
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/utils/mod.rs
  tests/ui/new_ret_no_self.rs
  tests/ui/new_ret_no_self.stderr
Labels: S-waiting-on-author

#5970 Update changelog to beta 1.47
  CHANGELOG.md
Labels: S-waiting-on-review

#5982 [beta] Backport: Re-enable len_zero for ranges now that `is_empty` is stable on them
  clippy_lints/src/len_zero.rs
  tests/ui/len_zero.fixed
  tests/ui/len_zero.rs
  tests/ui/len_zero_ranges.fixed
  tests/ui/len_zero_ranges.rs
  tests/ui/len_zero_ranges.stderr
Labels: S-waiting-on-review

#5988 Syntax-highlight `single_char_push_str` lint
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-review

#5984 or_fn_call: ignore nullary associated const fns
  clippy_lints/src/utils/mod.rs
  tests/ui/or_fun_call.fixed
  tests/ui/or_fun_call.rs
  tests/ui/or_fun_call.stderr
Labels: S-waiting-on-review

#5909 Add a lint for an async block/closure that yields a type that is itself awaitable.
  CHANGELOG.md
  clippy_lints/src/async_yields_async.rs
  clippy_lints/src/lib.rs
  src/lintlist/mod.rs
  tests/ui/async_yields_async.fixed
  tests/ui/async_yields_async.rs
  tests/ui/async_yields_async.stderr
Labels: S-waiting-on-review

#5992 Fix the wrong suggestion when using macro in `collapsible_if`
  clippy_lints/src/utils/sugg.rs
  tests/ui/collapsible_if.fixed
  tests/ui/collapsible_if.rs
  tests/ui/collapsible_if.stderr
Labels: S-waiting-on-review
