Repository rust-lang/rust-clippy, pull requests merged in 2020-01, with the labels that each got.

#4978 Fix bad `explicit_into_iter_loop` suggestion
  clippy_lints/src/loops.rs
  tests/ui/for_loop_fixable.fixed
  tests/ui/for_loop_fixable.rs
  tests/ui/for_loop_fixable.stderr
Labels: S-waiting-on-review

#5009 Travis: Use windows-msvc target for Windows build
  .travis.yml
Labels: S-waiting-on-review

#5002 build: Use rustfmt from lastest nightly that contains it
  .travis.yml
Labels: S-waiting-on-rustup

#5010 Make utils::remove_blocks non-recursive
  clippy_lints/src/utils/mod.rs
Labels: S-waiting-on-review

#5011 Split up `collapsible_if` ui test
  tests/ui/collapsible_else_if.fixed
  tests/ui/collapsible_else_if.rs
  tests/ui/collapsible_else_if.stderr
  tests/ui/collapsible_if.fixed
  tests/ui/collapsible_if.rs
  tests/ui/collapsible_if.stderr
Labels: S-waiting-on-review

#5033 Split up `use_self` ui test
  tests/ui/use_self.fixed
  tests/ui/use_self.rs
  tests/ui/use_self.stderr
  tests/ui/use_self_trait.fixed
  tests/ui/use_self_trait.rs
  tests/ui/use_self_trait.stderr
Labels: S-waiting-on-rustup

#4945 add `option_as_ref_deref` lint
  CHANGELOG.md
  README.md
  clippy_lints/src/lib.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/utils/paths.rs
  src/lintlist/mod.rs
  tests/ui/option_as_ref_deref.fixed
  tests/ui/option_as_ref_deref.rs
  tests/ui/option_as_ref_deref.stderr
Labels: S-waiting-on-author

#5027 Lint vectored IO in unused_io_amount lint
  clippy_lints/src/unused_io_amount.rs
  tests/ui/unused_io_amount.rs
  tests/ui/unused_io_amount.stderr
Labels: S-waiting-on-review

#5097 Resolve FIXME: String::new is now a const fn
  tests/ui/missing_const_for_fn/could_be_const.rs
  tests/ui/missing_const_for_fn/could_be_const.stderr
Labels: S-waiting-on-review

#5107 Revive test in `enum_clike_unportable_variant`
  tests/ui/enum_clike_unportable_variant.rs
  tests/ui/enum_clike_unportable_variant.stderr
Labels: S-waiting-on-rustup

#5111 Update changelog
  CHANGELOG.md
Labels: S-waiting-on-review
