Repository rust-lang/rust-clippy, pull requests merged in 2020-02, with the labels that each got.

#5119 Tweak documentation in `multiple_crate_versions`
  clippy_lints/src/multiple_crate_versions.rs
Labels: S-waiting-on-review

#5120 Split up `drop_forget_ref` ui test
  tests/ui/drop_forget_ref.stderr
  tests/ui/drop_ref.rs
  tests/ui/drop_ref.stderr
  tests/ui/forget_ref.rs
  tests/ui/forget_ref.stderr
Labels: S-waiting-on-review

#5127 improve 'iter_nth_zero' documentation
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-review

#5129 Use `checked_sub` to avoid index out of bounds
  clippy_lints/src/misc_early.rs
Labels: S-waiting-on-review

#5135 Few improvement to `utils::conf` module
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/conf.rs
Labels: S-waiting-on-author

#5132 Do not lint `unnecessary_unwrap` in external macros
  clippy_lints/src/unwrap.rs
  tests/ui/checked_unwrap/simple_conditionals.rs
  tests/ui/checked_unwrap/simple_conditionals.stderr
Labels: S-waiting-on-review

#5139 dev: Use bytecount for faster line count
  clippy_dev/Cargo.toml
  clippy_dev/src/stderr_length_check.rs
  clippy_lints/src/missing_doc.rs
Labels: S-waiting-on-author

#5140 Minor edit to text region replacement
  clippy_dev/src/lib.rs
  clippy_dev/src/main.rs
Labels: S-waiting-on-rustup

#5145 Fix error E0460 when compiled on Rustc repo
  tests/cargo/mod.rs
  tests/compile-test.rs
  tests/dogfood.rs
Labels: S-waiting-on-author

#5151 Fix run-pass tests when CARGO_TARGET_DIR is not set
  tests/cargo/mod.rs
Labels: S-waiting-on-review

#5152 Rustup to rust-lang/rust#68725
  clippy_lints/src/utils/diagnostics.rs
Labels: S-waiting-on-review

#5158 Impl DefaultCallbacks on our side
  src/driver.rs
Labels: S-waiting-on-rustup

#5170 Fix false positive in `zero_prefixed_literal`
  clippy_lints/src/misc_early.rs
  tests/ui/literals.rs
  tests/ui/literals.stderr
Labels: S-waiting-on-review

#5171 Improve deployment and documentation
  .github/deploy.sh
  util/gh-pages/versions.html
  util/versions.py
Labels: S-waiting-on-review

#4809 Typo in literal_representation.rs
  clippy_lints/src/literal_representation.rs
Labels: S-waiting-on-author

#5190 I like to move it, move it
  .github/deploy_key.enc
  .travis.yml
  Cargo.toml
  README.md
  appveyor.yml
  ci/base-tests.sh
Labels: C-needs-discussion, S-waiting-on-review

#5204 Update License
  LICENSE-APACHE
  LICENSE-MIT
  README.md
  rustc_tools_util/README.md
  tests/ui/mem_replace.fixed
  tests/ui/mem_replace.rs
  tests/ui/mem_replace.stderr
Labels: S-waiting-on-review

#5200 Move unneeded_field_pattern to restriction group
  clippy_lints/src/lib.rs
  clippy_lints/src/misc_early.rs
  src/lintlist/mod.rs
Labels: S-waiting-on-rustup

#4897 Add lint to improve floating-point expressions
  CHANGELOG.md
  README.md
  clippy_lints/src/floating_point_arithmetic.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/mul_add.rs
  src/lintlist/mod.rs
  tests/ui/floating_point_exp.fixed
  tests/ui/floating_point_exp.rs
  tests/ui/floating_point_exp.stderr
  tests/ui/floating_point_log.fixed
  tests/ui/floating_point_log.rs
  tests/ui/floating_point_log.stderr
  tests/ui/floating_point_mul_add.fixed
  tests/ui/floating_point_mul_add.rs
  tests/ui/floating_point_mul_add.stderr
  tests/ui/floating_point_powf.fixed
  tests/ui/floating_point_powf.rs
  tests/ui/floating_point_powf.stderr
  tests/ui/mul_add.rs
  tests/ui/mul_add.stderr
  tests/ui/mul_add_fixable.fixed
  tests/ui/mul_add_fixable.rs
  tests/ui/mul_add_fixable.stderr
Labels: S-waiting-on-author
