Repository rust-lang/rust-clippy, pull requests merged in 2020-07, with the labels that each got.

#5759 Fix multiple_crate_versions error
  tests/ui-cargo/multiple_crate_versions/fail/Cargo.lock
Labels: S-waiting-on-review

#5760 Deprecate regex_macro lint
  clippy_lints/src/deprecated_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/regex.rs
  clippy_lints/src/utils/paths.rs
  src/lintlist/mod.rs
  tests/ui/deprecated.rs
  tests/ui/deprecated.stderr
  tests/ui/regex.rs
Labels: S-waiting-on-review

#5761 Improvements for `type_repetition_in_bounds` lint
  clippy_lints/src/lib.rs
  clippy_lints/src/trait_bounds.rs
  clippy_lints/src/utils/conf.rs
  clippy_lints/src/utils/hir_utils.rs
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
  tests/ui/type_repetition_in_bounds.rs
  tests/ui/type_repetition_in_bounds.stderr
Labels: S-waiting-on-rustup

#4841 Added restriction lint: pattern-type-mismatch
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/pattern_type_mismatch.rs
  src/lintlist/mod.rs
  tests/ui/pattern_type_mismatch/mutability.rs
  tests/ui/pattern_type_mismatch/mutability.stderr
  tests/ui/pattern_type_mismatch/pattern_alternatives.rs
  tests/ui/pattern_type_mismatch/pattern_alternatives.stderr
  tests/ui/pattern_type_mismatch/pattern_structs.rs
  tests/ui/pattern_type_mismatch/pattern_structs.stderr
  tests/ui/pattern_type_mismatch/pattern_tuples.rs
  tests/ui/pattern_type_mismatch/pattern_tuples.stderr
  tests/ui/pattern_type_mismatch/syntax.rs
  tests/ui/pattern_type_mismatch/syntax.stderr
Labels: L-lint, S-waiting-on-rustup

#5301 Suggest `Option::map_or`(_else) for `if let Some { y } else { x }`
  CHANGELOG.md
  clippy_lints/src/attrs.rs
  clippy_lints/src/if_let_mutex.rs
  clippy_lints/src/len_zero.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/literal_representation.rs
  clippy_lints/src/loops.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/unnecessary_filter_map.rs
  clippy_lints/src/minmax.rs
  clippy_lints/src/misc.rs
  clippy_lints/src/option_if_let_else.rs
  clippy_lints/src/returns.rs
  clippy_lints/src/shadow.rs
  clippy_lints/src/types.rs
  clippy_lints/src/use_self.rs
  clippy_lints/src/utils/attrs.rs
  clippy_lints/src/utils/mod.rs
  clippy_lints/src/utils/numeric_literal.rs
  clippy_lints/src/utils/sugg.rs
  clippy_lints/src/write.rs
  src/lintlist/mod.rs
  tests/compile-test.rs
  tests/ui/option_if_let_else.fixed
  tests/ui/option_if_let_else.rs
  tests/ui/option_if_let_else.stderr
Labels: S-waiting-on-author

#5771 single_match_else - single expr/stmt else block corner case
  clippy_lints/src/matches.rs
  tests/ui/single_match_else.rs
  tests/ui/single_match_else.stderr
Labels: S-waiting-on-review

#5781 Fix a broken link in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: S-waiting-on-review

#5769 new lint: match_like_matches_macro
  CHANGELOG.md
  clippy_lints/src/comparison_chain.rs
  clippy_lints/src/eq_op.rs
  clippy_lints/src/escape.rs
  clippy_lints/src/eta_reduction.rs
  clippy_lints/src/formatting.rs
  clippy_lints/src/functions.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/lifetimes.rs
  clippy_lints/src/loops.rs
  clippy_lints/src/matches.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/misc.rs
  clippy_lints/src/misc_early.rs
  clippy_lints/src/missing_inline.rs
  clippy_lints/src/new_without_default.rs
  clippy_lints/src/non_copy_const.rs
  clippy_lints/src/precedence.rs
  clippy_lints/src/redundant_pattern_matching.rs
  clippy_lints/src/regex.rs
  clippy_lints/src/shadow.rs
  clippy_lints/src/temporary_assignment.rs
  clippy_lints/src/types.rs
  clippy_lints/src/unnamed_address.rs
  clippy_lints/src/use_self.rs
  clippy_lints/src/utils/ast_utils.rs
  clippy_lints/src/utils/mod.rs
  clippy_lints/src/utils/numeric_literal.rs
  src/driver.rs
  src/lintlist/mod.rs
  tests/ui/find_map.rs
  tests/ui/find_map.stderr
  tests/ui/match_expr_like_matches_macro.fixed
  tests/ui/match_expr_like_matches_macro.rs
  tests/ui/match_expr_like_matches_macro.stderr
  tests/ui/neg_cmp_op_on_partial_ord.rs
  tests/ui/redundant_pattern_matching.fixed
  tests/ui/redundant_pattern_matching.rs
  tests/ui/redundant_pattern_matching.stderr
  tests/ui/redundant_pattern_matching_const_result.fixed
  tests/ui/redundant_pattern_matching_const_result.rs
Labels: S-waiting-on-review

#5784 Fix out of bounds access by checking length equality BEFORE accessing by index.
  clippy_lints/src/unnested_or_patterns.rs
Labels: S-waiting-on-review

#5756 unnecessary_sort_by: avoid linting if key borrows
  clippy_lints/src/let_and_return.rs
  clippy_lints/src/unnecessary_sort_by.rs
  clippy_lints/src/utils/mod.rs
  tests/ui/unnecessary_sort_by.fixed
  tests/ui/unnecessary_sort_by.rs
Labels: S-waiting-on-rustup

#5752 Move range_minus_one to pedantic
  clippy_lints/src/lib.rs
  clippy_lints/src/ranges.rs
  src/lintlist/mod.rs
  tests/ui/range_plus_minus_one.fixed
  tests/ui/range_plus_minus_one.rs
  tests/ui/range_plus_minus_one.stderr
Labels: S-waiting-on-rustup

#5443 Some accuracy lints for floating point operations
  clippy_lints/src/floating_point_arithmetic.rs
  tests/ui/floating_point_hypot.fixed
  tests/ui/floating_point_hypot.rs
  tests/ui/floating_point_hypot.stderr
  tests/ui/floating_point_log.fixed
  tests/ui/floating_point_log.rs
  tests/ui/floating_point_log.stderr
  tests/ui/floating_point_logbase.fixed
  tests/ui/floating_point_logbase.rs
  tests/ui/floating_point_logbase.stderr
  tests/ui/floating_point_mul_add.fixed
  tests/ui/floating_point_mul_add.rs
  tests/ui/floating_point_mul_add.stderr
  tests/ui/floating_point_powf.fixed
  tests/ui/floating_point_powf.rs
  tests/ui/floating_point_powf.stderr
  tests/ui/floating_point_powi.fixed
  tests/ui/floating_point_powi.rs
  tests/ui/floating_point_powi.stderr
  tests/ui/floating_point_rad.fixed
  tests/ui/floating_point_rad.rs
  tests/ui/floating_point_rad.stderr
Labels: S-waiting-on-author

#5773 Add a lint for `.repeat(1)`
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/repeat_once.rs
  src/lintlist/mod.rs
  tests/ui/repeat_once.fixed
  tests/ui/repeat_once.rs
  tests/ui/repeat_once.stderr
Labels: S-waiting-on-author

#5732 Rename collapsable_if fix suggestion to "collapse nested if block"
  clippy_lints/src/collapsible_if.rs
  tests/ui/collapsible_else_if.stderr
  tests/ui/collapsible_if.stderr
Labels: S-waiting-on-author

#5737 Reprise: new lint: Unintentional return of unit from closures expecting Ord
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/unit_return_expecting_ord.rs
  src/lintlist/mod.rs
  tests/ui/unit_return_expecting_ord.rs
  tests/ui/unit_return_expecting_ord.stderr
Labels: S-waiting-on-rustup

#5793 improve advice in iter_nth_zero
  clippy_lints/src/methods/mod.rs
  tests/ui/iter_nth_zero.stderr
Labels: S-waiting-on-author

#5798 Add test for `needless_range_loop` issue
  tests/ui/needless_range_loop2.rs
Labels: S-waiting-on-review

#5788 Removing RHS snippet from SHADOW_UNRELATED message.
  clippy_lints/src/shadow.rs
  tests/ui/shadow.stderr
Labels: S-waiting-on-rustup

#5806 Fix deploy script for beta deployment
  .github/deploy.sh
Labels: S-waiting-on-review

#5807 Changelog
  CHANGELOG.md
Labels: S-waiting-on-review

#5810 fix typos (found by codespell)
  clippy_lints/src/deprecated_lints.rs
  clippy_lints/src/dereference.rs
  clippy_lints/src/inherent_impl.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/missing_const_for_fn.rs
  clippy_lints/src/modulo_arithmetic.rs
  clippy_lints/src/option_if_let_else.rs
  clippy_lints/src/utils/numeric_literal.rs
  tests/ui/manual_async_fn.fixed
  tests/ui/manual_async_fn.rs
  tests/ui/manual_async_fn.stderr
  tests/ui/never_loop.rs
  tests/ui/precedence.fixed
  tests/ui/precedence.rs
  tests/ui/vec_resize_to_zero.rs
Labels: S-waiting-on-review

#5811 Panic multiple args
  clippy_lints/src/panic_unimplemented.rs
  tests/ui/panicking_macros.rs
  tests/ui/panicking_macros.stderr
Labels: S-waiting-on-review

#5814 Fix typo
  clippy_lints/src/vec_resize_to_zero.rs
Labels: S-waiting-on-review

#5815 Redundant pattern bugfix
  clippy_lints/src/matches.rs
  tests/ui/redundant_pattern_matching.fixed
  tests/ui/redundant_pattern_matching.rs
  tests/ui/redundant_pattern_matching.stderr
Labels: S-waiting-on-rustup

#5800 redundant_closure_call - don't lint when used more than once
  clippy_lints/src/lib.rs
  clippy_lints/src/misc_early.rs
  clippy_lints/src/redundant_closure_call.rs
  src/lintlist/mod.rs
  tests/ui/redundant_closure_call.stderr
  tests/ui/redundant_closure_call_early.rs
  tests/ui/redundant_closure_call_early.stderr
  tests/ui/redundant_closure_call_fixable.stderr
  tests/ui/redundant_closure_call_late.rs
  tests/ui/redundant_closure_call_late.stderr
Labels: S-waiting-on-review

#5824 Ignore not really redundant clones of ManuallyDrop
  clippy_lints/src/redundant_clone.rs
  clippy_lints/src/utils/paths.rs
  tests/ui/redundant_clone.fixed
  tests/ui/redundant_clone.rs
  tests/ui/redundant_clone.stderr
Labels: S-waiting-on-review

#5832 Update Usage section of README.md
  README.md
Labels: S-waiting-on-rustup

#5829 Use `(std::)f64::EPSILON` in the examples as suggested in the lints
  clippy_lints/src/misc.rs
Labels: S-waiting-on-rustup

#5845 Fix FP `useless_conversion`
  clippy_lints/src/useless_conversion.rs
  tests/ui/useless_conversion.fixed
  tests/ui/useless_conversion.rs
  tests/ui/useless_conversion.stderr
Labels: S-waiting-on-review

#5820 Fix FP for `suspicious_arithmetic_impl` from `suspicious_trait_impl` …
  clippy_lints/src/suspicious_trait_impl.rs
  tests/ui/suspicious_arithmetic_impl.rs
Labels: S-waiting-on-review

#5850 Small fix: `chmod` 644 `clippy_lints/src/utils/ast_utils.rs`
  clippy_lints/src/utils/ast_utils.rs
Labels: S-waiting-on-review

#5840 Basic instruction for new contributors
  CONTRIBUTING.md
  doc/adding_lints.md
  doc/basics.md
Labels: S-waiting-on-review
