Repository rust-lang/rust-clippy, pull requests merged in 2020-12, with the labels that each got.

#6308 add `internal-lints` feature to enable clippys internal lints (off by default)
  .github/workflows/clippy_bors.yml
  Cargo.toml
  clippy_dev/src/lib.rs
  clippy_dev/src/update_lints.rs
  clippy_lints/Cargo.toml
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/diagnostics.rs
  clippy_lints/src/utils/mod.rs
  clippy_lints/src/utils/paths.rs
  tests/compile-test.rs
  tests/dogfood.rs
  tests/ui-internal/collapsible_span_lint_calls.fixed
  tests/ui-internal/collapsible_span_lint_calls.rs
  tests/ui-internal/collapsible_span_lint_calls.stderr
  tests/ui-internal/custom_ice_message.rs
  tests/ui-internal/custom_ice_message.stderr
  tests/ui-internal/default_lint.rs
  tests/ui-internal/default_lint.stderr
  tests/ui-internal/invalid_paths.rs
  tests/ui-internal/invalid_paths.stderr
  tests/ui-internal/lint_without_lint_pass.rs
  tests/ui-internal/lint_without_lint_pass.stderr
  tests/ui-internal/match_type_on_diag_item.rs
  tests/ui-internal/match_type_on_diag_item.stderr
  tests/ui-internal/outer_expn_data.fixed
  tests/ui-internal/outer_expn_data.rs
  tests/ui-internal/outer_expn_data.stderr
Labels: S-waiting-on-rustup

#6395 switch Version/VersionReq usages to RustcVersion
  clippy_lints/Cargo.toml
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_non_exhaustive.rs
  clippy_lints/src/manual_strip.rs
  clippy_lints/src/matches.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/utils/mod.rs
  tests/ui/min_rust_version_attr.rs
  tests/ui/min_rust_version_attr.stderr
  tests/ui/min_rust_version_no_patch.rs
Labels: S-waiting-on-rustup

#6402 Add Collapsible match lint
  CHANGELOG.md
  clippy_lints/src/collapsible_match.rs
  clippy_lints/src/default.rs
  clippy_lints/src/if_let_some_result.rs
  clippy_lints/src/implicit_return.rs
  clippy_lints/src/implicit_saturating_sub.rs
  clippy_lints/src/large_const_arrays.rs
  clippy_lints/src/large_stack_arrays.rs
  clippy_lints/src/let_if_seq.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/loops.rs
  clippy_lints/src/manual_strip.rs
  clippy_lints/src/matches.rs
  clippy_lints/src/methods/manual_saturating_arithmetic.rs
  clippy_lints/src/needless_bool.rs
  clippy_lints/src/question_mark.rs
  clippy_lints/src/strings.rs
  clippy_lints/src/trait_bounds.rs
  clippy_lints/src/transmuting_null.rs
  clippy_lints/src/types.rs
  clippy_lints/src/utils/higher.rs
  clippy_lints/src/utils/hir_utils.rs
  clippy_lints/src/utils/visitors.rs
  tests/ui/collapsible_match.rs
  tests/ui/collapsible_match.stderr
  tests/ui/collapsible_match2.rs
  tests/ui/collapsible_match2.stderr
Labels: S-waiting-on-rustup

#6407 CONTRIBUTING: update bors queue url from buildbot2.rlo to bors.rlo
  CONTRIBUTING.md
Labels: S-waiting-on-rustup

#6415 Rollup of 4 pull requests
  .github/workflows/clippy_bors.yml
  CHANGELOG.md
  CONTRIBUTING.md
  Cargo.toml
  clippy_dev/src/lib.rs
  clippy_dev/src/update_lints.rs
  clippy_lints/Cargo.toml
  clippy_lints/src/collapsible_match.rs
  clippy_lints/src/default.rs
  clippy_lints/src/if_let_some_result.rs
  clippy_lints/src/implicit_return.rs
  clippy_lints/src/implicit_saturating_sub.rs
  clippy_lints/src/large_const_arrays.rs
  clippy_lints/src/large_stack_arrays.rs
  clippy_lints/src/let_if_seq.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/loops.rs
  clippy_lints/src/manual_non_exhaustive.rs
  clippy_lints/src/manual_strip.rs
  clippy_lints/src/matches.rs
  clippy_lints/src/methods/manual_saturating_arithmetic.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/needless_bool.rs
  clippy_lints/src/question_mark.rs
  clippy_lints/src/strings.rs
  clippy_lints/src/trait_bounds.rs
  clippy_lints/src/transmuting_null.rs
  clippy_lints/src/types.rs
  clippy_lints/src/utils/diagnostics.rs
  clippy_lints/src/utils/higher.rs
  clippy_lints/src/utils/hir_utils.rs
  clippy_lints/src/utils/mod.rs
  clippy_lints/src/utils/paths.rs
  clippy_lints/src/utils/visitors.rs
  tests/compile-test.rs
  tests/dogfood.rs
  tests/ui-internal/collapsible_span_lint_calls.fixed
  tests/ui-internal/collapsible_span_lint_calls.rs
  tests/ui-internal/collapsible_span_lint_calls.stderr
  tests/ui-internal/custom_ice_message.rs
  tests/ui-internal/custom_ice_message.stderr
  tests/ui-internal/default_lint.rs
  tests/ui-internal/default_lint.stderr
  tests/ui-internal/invalid_paths.rs
  tests/ui-internal/invalid_paths.stderr
  tests/ui-internal/lint_without_lint_pass.rs
  tests/ui-internal/lint_without_lint_pass.stderr
  tests/ui-internal/match_type_on_diag_item.rs
  tests/ui-internal/match_type_on_diag_item.stderr
  tests/ui-internal/outer_expn_data.fixed
  tests/ui-internal/outer_expn_data.rs
  tests/ui-internal/outer_expn_data.stderr
  tests/ui/collapsible_match.rs
  tests/ui/collapsible_match.stderr
  tests/ui/collapsible_match2.rs
  tests/ui/collapsible_match2.stderr
  tests/ui/min_rust_version_attr.rs
  tests/ui/min_rust_version_attr.stderr
  tests/ui/min_rust_version_no_patch.rs
Labels: rollup

#6394 Add lint size_of_in_element_count
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/size_of_in_element_count.rs
  clippy_lints/src/utils/paths.rs
  tests/ui/size_of_in_element_count.rs
  tests/ui/size_of_in_element_count.stderr
Labels: S-waiting-on-author

#6416 Moved map_err_ignore to restriction and updated help message
  clippy_lints/src/lib.rs
  clippy_lints/src/map_err_ignore.rs
  tests/ui/map_err.rs
  tests/ui/map_err.stderr
Labels: S-waiting-on-review

#6419 Fix a style of texts in `size_of_in_element_count`
  clippy_lints/src/size_of_in_element_count.rs
  tests/ui/size_of_in_element_count.stderr
Labels: S-waiting-on-review

#6418 Turn unnecessary_wraps applicability to MaybeIncorrect
  clippy_lints/src/unnecessary_wraps.rs
Labels: S-waiting-on-review

#6421 Added a lint-fraction-readability flag to the configuration
  clippy_lints/src/lib.rs
  clippy_lints/src/literal_representation.rs
  clippy_lints/src/utils/conf.rs
  tests/ui-toml/lint_decimal_readability/clippy.toml
  tests/ui-toml/lint_decimal_readability/test.rs
  tests/ui-toml/lint_decimal_readability/test.stderr
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
  tests/ui/unreadable_literal.fixed
  tests/ui/unreadable_literal.rs
  tests/ui/unreadable_literal.stderr
Labels: S-waiting-on-review

#6370 Fix FP in `unnecessary_lazy_evaluations`
  clippy_lints/src/doc.rs
  clippy_lints/src/missing_const_for_fn.rs
  clippy_lints/src/needless_pass_by_value.rs
  clippy_lints/src/pass_by_ref_or_value.rs
  clippy_lints/src/redundant_clone.rs
  clippy_lints/src/types.rs
  clippy_lints/src/unnecessary_wraps.rs
  clippy_lints/src/utils/ast_utils.rs
  clippy_lints/src/utils/mod.rs
  clippy_lints/src/utils/usage.rs
  tests/ui/unnecessary_lazy_eval_unfixable.rs
Labels: S-waiting-on-review

#6330 Add Redundant else lint
  CHANGELOG.md
  clippy_lints/src/functions.rs
  clippy_lints/src/len_zero.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/matches.rs
  clippy_lints/src/methods/unnecessary_filter_map.rs
  clippy_lints/src/non_expressive_names.rs
  clippy_lints/src/redundant_else.rs
  tests/ui/redundant_else.rs
  tests/ui/redundant_else.stderr
Labels: S-waiting-on-author

#6432 Rustup
  clippy_lints/src/loops.rs
  clippy_lints/src/utils/hir_utils.rs
  clippy_lints/src/utils/inspector.rs
Labels: S-waiting-on-review

#6188 Add --no-deps option to avoid running on path dependencies in workspaces
  README.md
  clippy_workspace_tests/path_dep/Cargo.toml
  clippy_workspace_tests/path_dep/src/lib.rs
  clippy_workspace_tests/subcrate/Cargo.toml
  src/driver.rs
  src/main.rs
  tests/dogfood.rs
Labels: S-waiting-on-author

#6218 Add lint for maps with zero-sized value types
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/zero_sized_map_values.rs
  tests/ui/zero_sized_btreemap_values.rs
  tests/ui/zero_sized_btreemap_values.stderr
  tests/ui/zero_sized_hashmap_values.rs
  tests/ui/zero_sized_hashmap_values.stderr
Labels: S-waiting-on-author

#6424 Add MSRV to more lints specified in #6097
  clippy_lints/src/checked_conversions.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/mem_replace.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/missing_const_for_fn.rs
  clippy_lints/src/ranges.rs
  clippy_lints/src/redundant_field_names.rs
  clippy_lints/src/redundant_static_lifetimes.rs
  clippy_lints/src/use_self.rs
  doc/adding_lints.md
  tests/ui/min_rust_version_attr.rs
  tests/ui/min_rust_version_attr.stderr
Labels: S-waiting-on-review

#6401 📌 Pin Clippy to a nightly 📌
  .github/workflows/clippy.yml
  .github/workflows/clippy_bors.yml
  .github/workflows/clippy_dev.yml
  CONTRIBUTING.md
  doc/basics.md
  rust-toolchain
  setup-toolchain.sh
  tests/integration.rs
Labels: S-waiting-on-review

#6413 Rewrite update-all-references bash scripts in Rust
  clippy_dev/src/bless.rs
  clippy_dev/src/lib.rs
  clippy_dev/src/main.rs
  doc/adding_lints.md
  doc/basics.md
  tests/ui-cargo/update-all-references.sh
  tests/ui-cargo/update-references.sh
  tests/ui-toml/update-all-references.sh
  tests/ui-toml/update-references.sh
  tests/ui/update-all-references.sh
  tests/ui/update-references.sh
Labels: S-waiting-on-author

#6382 Fix FP of `manual_range_contains` in `const fn`
  clippy_lints/src/ranges.rs
  tests/ui/range_contains.fixed
  tests/ui/range_contains.rs
Labels: S-waiting-on-review

#6318 Use article_and_description for missing docs
  clippy_lints/src/missing_doc.rs
  tests/ui/missing-doc-crate-missing.stderr
  tests/ui/missing-doc-impl.stderr
Labels: S-waiting-on-review

#6442 clone_double_ref: print reference type in lint message
  clippy_lints/src/methods/mod.rs
  tests/ui/unnecessary_clone.stderr
Labels: S-waiting-on-review

#6441 Pass Clippy args also trough RUSTFLAGS
  Cargo.toml
  README.md
  src/driver.rs
  src/main.rs
  tests/dogfood.rs
Labels: S-waiting-on-author

#6450 cargo dev fmt: don't format entire rustc repo if we ran ra_setup previously
  CONTRIBUTING.md
  clippy_dev/src/fmt.rs
  clippy_dev/src/main.rs
  clippy_dev/src/ra_setup.rs
  doc/basics.md
Labels: S-waiting-on-review

#6435 Fixing a false positive for the `match_single_binding` lint #5552
  clippy_lints/src/matches.rs
  tests/ui/match_single_binding.fixed
  tests/ui/match_single_binding.rs
  tests/ui/match_single_binding.stderr
Labels: S-waiting-on-author

#6452 bump pinned nightly from nightly-2020-12-09 to nightly-2020-12-14
  rust-toolchain
Labels: S-waiting-on-review

#6448 New internal lint: Interning defined symbol
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_ok_or.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/ref_option_ref.rs
  clippy_lints/src/strings.rs
  clippy_lints/src/unnecessary_wraps.rs
  clippy_lints/src/utils/internal_lints.rs
  clippy_lints/src/utils/paths.rs
  tests/ui-internal/interning_defined_symbol.fixed
  tests/ui-internal/interning_defined_symbol.rs
  tests/ui-internal/interning_defined_symbol.stderr
Labels: S-waiting-on-review

#6461 Typo in create_dir doc comment
  clippy_lints/src/create_dir.rs
Labels: S-waiting-on-review

#6458 needless_doctest_main: handle correctly parse errors
  clippy_lints/src/doc.rs
  clippy_lints/src/lib.rs
  tests/ui/needless_doc_main.rs
Labels: S-waiting-on-review

#6465 add more lints to msrv docs
  clippy_lints/src/utils/conf.rs
Labels: S-waiting-on-review

#6468 Renamed the good first issue label for rustbot
  triagebot.toml
Labels: S-waiting-on-review

#6470 Renamed the good first issue label in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: S-waiting-on-review

#6464 make needless_update ignore non_exhaustive structs
  clippy_lints/src/needless_update.rs
  tests/ui/needless_update.rs
  tests/ui/needless_update.stderr
Labels: S-waiting-on-review

#6471 Fix blessing of new reference files
  clippy_dev/src/bless.rs
Labels: S-waiting-on-review

#6473 UI Tests: Separate suspicious_else_formatting tests
  tests/ui/formatting.rs
  tests/ui/formatting.stderr
  tests/ui/suspicious_else_formatting.rs
  tests/ui/suspicious_else_formatting.stderr
Labels: S-waiting-on-review

#6477 Adapted the website search for better matching
  util/gh-pages/index.html
Labels: S-waiting-on-review

#6488 readme: remove paragraph about installing clippy manually on ci, if it is missing on a nightly
  README.md
Labels: S-waiting-on-review

#6485 Don't trigger large_enum_variant in external macros
  clippy_lints/src/large_enum_variant.rs
  tests/ui/auxiliary/macro_rules.rs
  tests/ui/large_enum_variant.rs
  tests/ui/large_enum_variant.stderr
Labels: S-waiting-on-review

#6497 remove clone in manual_async_fn lint
  clippy_lints/src/manual_async_fn.rs
  clippy_lints/src/unused_unit.rs
  clippy_lints/src/utils/mod.rs
Labels: S-waiting-on-review

#6476 Added from_over_into lint
  CHANGELOG.md
  clippy_lints/src/from_over_into.rs
  clippy_lints/src/lib.rs
  tests/ui/from_over_into.rs
  tests/ui/from_over_into.stderr
  tests/ui/min_rust_version_attr.rs
  tests/ui/min_rust_version_attr.stderr
  tests/ui/unused_unit.fixed
  tests/ui/unused_unit.rs
  tests/ui/unused_unit.stderr
Labels: S-waiting-on-review

#6494 readme: remove paragraph about executing clippy via "cargo run .."
  README.md
Labels: S-waiting-on-review

#6498 Revert "Pass Clippy args also trough RUSTFLAGS"
  Cargo.toml
  README.md
  src/driver.rs
  src/main.rs
  tests/dogfood.rs
Labels: S-waiting-on-review

#6496 ci: test cargo clippy --fix -Zunstable-options
  .github/workflows/clippy.yml
Labels: S-blocked, S-waiting-on-review

#6483 Website issue tracker link and better search performance
  util/gh-pages/index.html
Labels: S-waiting-on-review

#6504 fix ci on master branch; run the --fix test in the correct directory
  .github/workflows/clippy.yml
Labels: S-waiting-on-review

#6505 Fix a style of texts in `map_err_ignore`
  clippy_lints/src/map_err_ignore.rs
  tests/ui/map_err.stderr
Labels: S-waiting-on-review

#6495 ISSUE_TEMPLATE: add templates for false negative and false positive tickets.
  .github/ISSUE_TEMPLATE/false_negative.md
  .github/ISSUE_TEMPLATE/false_positive.md
Labels: S-waiting-on-review

#6375 Reassign default private
  clippy_lints/src/default.rs
  tests/ui/field_reassign_with_default.rs
  tests/ui/field_reassign_with_default.stderr
Labels: S-waiting-on-review

#6506 Lint "&PathBuf instead of &Path" in PTR_ARG
  clippy_dev/src/ra_setup.rs
  clippy_lints/src/ptr.rs
  tests/ui/ptr_arg.rs
  tests/ui/ptr_arg.stderr
Labels: S-waiting-on-review

#6510 don't ignore expression after first not matched method call in PtrCloneVisitor
  clippy_lints/src/utils/ptr.rs
  tests/ui/ptr_arg.rs
  tests/ui/ptr_arg.stderr
Labels: S-waiting-on-review
