Repository rust-lang/rust-clippy, pull requests merged in 2020-09, with the labels that each got.

#5999 Fix a fp in `transmute_ptr_to_ptr`
  clippy_lints/src/transmute.rs
  tests/ui/transmute_ptr_to_ptr.rs
Labels: S-waiting-on-review

#5996 Allow GraphQL in docs without backticks
  clippy_lints/src/utils/conf.rs
  tests/ui/doc.rs
  tests/ui/doc.stderr
Labels: S-waiting-on-author

#6003 Update ui stderr with improved rustc output
  tests/ui/issue-3145.stderr
Labels: S-waiting-on-review

#5994 useless_attribute: Permit wildcard_imports and enum_glob_use
  clippy_lints/src/attrs.rs
  tests/ui/useless_attribute.fixed
  tests/ui/useless_attribute.rs
  tests/ui/useless_attribute.stderr
Labels: S-waiting-on-review

#6004 Simplify `clippy::default_trait_access`
  clippy_lints/src/default_trait_access.rs
Labels: S-waiting-on-review

#6009 Show line count and max lines in too_many_lines lint message
  clippy_lints/src/functions.rs
  tests/ui-toml/functions_maxlines/test.stderr
  tests/ui/functions_maxlines.stderr
Labels: S-waiting-on-review

#5997 Fix FP in `same_item_push`
  clippy_lints/src/loops.rs
  tests/ui/same_item_push.rs
Labels: S-waiting-on-review

#6006 Restrict unnecessary_sort_by to non-reference, Copy types
  clippy_lints/src/unnecessary_sort_by.rs
  tests/ui/unnecessary_sort_by.fixed
  tests/ui/unnecessary_sort_by.rs
Labels: S-waiting-on-review

#6016 Restrict `same_item_push` to suppress false positives
  clippy_lints/src/loops.rs
  tests/ui/same_item_push.rs
  tests/ui/same_item_push.stderr
Labels: S-waiting-on-author

#6024 print the unit type `()` in related lint messages.
  clippy_lints/src/map_unit_fn.rs
  tests/ui/option_map_unit_fn_fixable.stderr
  tests/ui/result_map_unit_fn_fixable.stderr
  tests/ui/result_map_unit_fn_unfixable.stderr
Labels: S-waiting-on-review

#6023 link to the Box docs in related lint documentation.
  clippy_lints/src/types.rs
Labels: S-waiting-on-rustup

#5931 improve the suggestion of the lint `unit-arg`
  clippy_lints/src/types.rs
  clippy_lints/src/utils/mod.rs
  tests/ui/unit_arg.rs
  tests/ui/unit_arg.stderr
  tests/ui/unit_arg_empty_blocks.stderr
Labels: S-waiting-on-rustup

#6028 Fix typo
  clippy_lints/src/await_holding_lock.rs
Labels: S-waiting-on-review

#6030 fix some use of `snippet` in `types.rs`
  clippy_lints/src/types.rs
Labels: S-waiting-on-rustup

#6032 into_iter_on_ref: rephrase lint message: will not move the x -> will not consume the x
  clippy_lints/src/methods/mod.rs
  tests/ui/into_iter_on_ref.stderr
Labels: S-waiting-on-rustup

#6036 Downgrade `verbose_bit_mask` to pedantic
  clippy_lints/src/bit_mask.rs
  clippy_lints/src/lib.rs
  src/lintlist/mod.rs
  tests/ui/trailing_zeros.rs
  tests/ui/trailing_zeros.stderr
Labels: S-waiting-on-review

#6035 useless_conversion: show type in error message.
  clippy_lints/src/useless_conversion.rs
  tests/ui/useless_conversion.stderr
  tests/ui/useless_conversion_try.stderr
Labels: S-waiting-on-review

#5998 Add map_err_ignore lint
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/map_err_ignore.rs
  src/lintlist/mod.rs
  tests/ui/drop_ref.rs
  tests/ui/drop_ref.stderr
  tests/ui/map_err.rs
  tests/ui/map_err.stderr
Labels: S-waiting-on-review

#6013 Internal lint: suggest `is_type_diagnostic_item` over `match_type` where applicable
  clippy_lints/src/lib.rs
  clippy_lints/src/loops.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/option_if_let_else.rs
  clippy_lints/src/utils/diagnostics.rs
  clippy_lints/src/utils/internal_lints.rs
  clippy_lints/src/utils/mod.rs
  doc/common_tools_writing_lints.md
  tests/ui/match_type_on_diag_item.rs
  tests/ui/match_type_on_diag_item.stderr
Labels: S-waiting-on-review

#6045 Remove an extra blank line in `shadow_same`
  clippy_lints/src/shadow.rs
Labels: S-waiting-on-review

#6043 clarify margin of error in wording of float comparison operator lint messages
  clippy_lints/src/misc.rs
  tests/ui/float_cmp.stderr
  tests/ui/float_cmp_const.stderr
Labels: S-waiting-on-review

#6055 Bump pulldown-cmark v0.8
  clippy_lints/Cargo.toml
Labels: S-waiting-on-review

#6056 Add S-* label modifier to triagebot
  triagebot.toml
Labels: S-waiting-on-review

#6042 {print,write}-with-newline: do not suggest empty format string
  clippy_lints/src/write.rs
  tests/ui/print_with_newline.rs
  tests/ui/print_with_newline.stderr
  tests/ui/write_with_newline.rs
  tests/ui/write_with_newline.stderr
Labels: S-waiting-on-review

#6048 Add note to `shadow_unrelated`
  clippy_lints/src/shadow.rs
Labels: S-waiting-on-rustup

#6038 Add `manual-strip` lint
  CHANGELOG.md
  clippy_lints/src/doc.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/loops.rs
  clippy_lints/src/manual_strip.rs
  clippy_lints/src/misc_early.rs
  clippy_lints/src/redundant_clone.rs
  clippy_lints/src/utils/paths.rs
  src/lintlist/mod.rs
  tests/ui/let_if_seq.rs
  tests/ui/let_if_seq.stderr
  tests/ui/manual_strip.rs
  tests/ui/manual_strip.stderr
Labels: S-waiting-on-review

#6025 Extend invalid_atomic_ordering for compare_exchange{,_weak} and fetch_update
  clippy_lints/src/atomic_ordering.rs
  src/lintlist/mod.rs
  tests/ui/atomic_ordering_exchange.rs
  tests/ui/atomic_ordering_exchange.stderr
  tests/ui/atomic_ordering_exchange_weak.rs
  tests/ui/atomic_ordering_exchange_weak.stderr
  tests/ui/atomic_ordering_fetch_update.rs
  tests/ui/atomic_ordering_fetch_update.stderr
Labels: S-waiting-on-rustup

#5937 option_if_let_else - distinguish pure from impure else expressions
  clippy_lints/src/methods/bind_instead_of_map.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/unnecessary_lazy_eval.rs
  clippy_lints/src/option_if_let_else.rs
  clippy_lints/src/utils/eager_or_lazy.rs
  clippy_lints/src/utils/mod.rs
  clippy_lints/src/utils/sugg.rs
  clippy_lints/src/utils/usage.rs
  tests/ui/option_if_let_else.fixed
  tests/ui/option_if_let_else.rs
  tests/ui/option_if_let_else.stderr
  tests/ui/unnecessary_lazy_eval.fixed
  tests/ui/unnecessary_lazy_eval.rs
  tests/ui/unnecessary_lazy_eval.stderr
Labels: S-waiting-on-author

#6034 Treat refs to arrays the same as owned arrays in `indexing_slicing` and `out_of_bounds_indexing`
  clippy_lints/src/bytecount.rs
  clippy_lints/src/duration_subsec.rs
  clippy_lints/src/entry.rs
  clippy_lints/src/fallible_impl_from.rs
  clippy_lints/src/format.rs
  clippy_lints/src/indexing_slicing.rs
  clippy_lints/src/inherent_to_string.rs
  clippy_lints/src/len_zero.rs
  clippy_lints/src/match_on_vec_items.rs
  clippy_lints/src/matches.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/misc.rs
  clippy_lints/src/mut_key.rs
  clippy_lints/src/open_options.rs
  clippy_lints/src/path_buf_push_overwrite.rs
  clippy_lints/src/repeat_once.rs
  clippy_lints/src/strings.rs
  clippy_lints/src/swap.rs
  clippy_lints/src/unwrap_in_result.rs
  clippy_lints/src/utils/internal_lints.rs
  clippy_lints/src/utils/mod.rs
  tests/ui/indexing_slicing_index.rs
  tests/ui/indexing_slicing_index.stderr
  tests/ui/indexing_slicing_slice.stderr
Labels: S-waiting-on-author

#6046 Change the criteria of `interior_mutable_const`
  clippy_lints/src/non_copy_const.rs
  tests/ui/borrow_interior_mutable_const.rs
  tests/ui/borrow_interior_mutable_const.stderr
  tests/ui/declare_interior_mutable_const.rs
  tests/ui/declare_interior_mutable_const.stderr
Labels: S-waiting-on-author

#6069 Forbid redundant_pattern_matching triggering in macros
  clippy_lints/src/matches.rs
  tests/ui/crashes/ice-2636.rs
  tests/ui/crashes/ice-2636.stderr
  tests/ui/redundant_pattern_matching.fixed
  tests/ui/redundant_pattern_matching.rs
  tests/ui/redundant_pattern_matching.stderr
Labels: S-waiting-on-review

#6044 Add `rc_buffer` lint for checking Rc<String> and friends
  CHANGELOG.md
  clippy_lints/src/consts.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/types.rs
  clippy_lints/src/utils/paths.rs
  src/lintlist/mod.rs
  tests/ui/rc_buffer.rs
  tests/ui/rc_buffer.stderr
  tests/ui/rc_buffer_arc.rs
  tests/ui/rc_buffer_arc.stderr
  tests/ui/rc_buffer_redefined_string.rs
  tests/ui/rc_buffer_redefined_string.stderr
Labels: S-waiting-on-review

#6076 Fix a FP in `explicit_counter_loop`
  clippy_lints/src/loops.rs
  tests/ui/explicit_counter_loop.rs
Labels: S-waiting-on-review

#6077 Revert: or_fun_call should lint calls to `const fn`s with no args
  clippy_lints/src/utils/mod.rs
  tests/ui/or_fun_call.fixed
  tests/ui/or_fun_call.rs
  tests/ui/or_fun_call.stderr
Labels: S-waiting-on-review

#6084 UI tests cleanup
  tests/compile-test.rs
  tests/ui/auxiliary/proc_macro_attr.rs
  tests/ui/auxiliary/proc_macro_derive.rs
  tests/ui/crashes/associated-constant-ice.rs
  tests/ui/crashes/auxiliary/proc_macro_crash.rs
  tests/ui/crashes/cc_seme.rs
  tests/ui/crashes/enum-glob-import-crate.rs
  tests/ui/crashes/ice-1588.rs
  tests/ui/crashes/ice-1782.rs
  tests/ui/crashes/ice-1969.rs
  tests/ui/crashes/ice-2499.rs
  tests/ui/crashes/ice-2594.rs
  tests/ui/crashes/ice-2727.rs
  tests/ui/crashes/ice-2760.rs
  tests/ui/crashes/ice-2774.rs
  tests/ui/crashes/ice-2862.rs
  tests/ui/crashes/ice-2865.rs
  tests/ui/crashes/ice-3151.rs
  tests/ui/crashes/ice-3462.rs
  tests/ui/crashes/ice-3741.rs
  tests/ui/crashes/ice-3747.rs
  tests/ui/crashes/ice-4727.rs
  tests/ui/crashes/ice-4760.rs
  tests/ui/crashes/ice-700.rs
  tests/ui/crashes/ice_exacte_size.rs
  tests/ui/crashes/if_same_then_else.rs
  tests/ui/crashes/issue-825.rs
  tests/ui/crashes/issues_loop_mut_cond.rs
  tests/ui/crashes/match_same_arms_const.rs
  tests/ui/crashes/mut_mut_macro.rs
  tests/ui/crashes/needless_borrow_fp.rs
  tests/ui/crashes/needless_lifetimes_impl_trait.rs
  tests/ui/crashes/procedural_macro.rs
  tests/ui/crashes/regressions.rs
  tests/ui/crashes/returns.rs
  tests/ui/crashes/single-match-else.rs
  tests/ui/crashes/trivial_bounds.rs
  tests/ui/crashes/used_underscore_binding_macro.rs
Labels: S-waiting-on-review

#6079 Fix FP in `print_stdout`
  clippy_lints/src/write.rs
  clippy_workspace_tests/build.rs
  tests/ui/print_stdout_build_script.rs
Labels: S-waiting-on-author

#6081 New Lint: disallowed_method
  CHANGELOG.md
  README.md
  clippy_lints/src/disallowed_method.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/conf.rs
  src/lintlist/mod.rs
  tests/ui-toml/toml_disallowed_method/clippy.toml
  tests/ui-toml/toml_disallowed_method/conf_disallowed_method.rs
  tests/ui-toml/toml_disallowed_method/conf_disallowed_method.stderr
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
Labels: S-waiting-on-review

#6090 lints: clarify rc_buffer and add caveats
  clippy_lints/src/types.rs
Labels: S-waiting-on-review

#6093 needless arbitrary self: handle macros
  clippy_lints/src/needless_arbitrary_self_type.rs
  tests/ui/auxiliary/proc_macro_attr.rs
  tests/ui/needless_arbitrary_self_type_unfixable.rs
  tests/ui/needless_arbitrary_self_type_unfixable.stderr
Labels: S-waiting-on-review

#6092 Add lint for inline assembly syntax style preference
  CHANGELOG.md
  clippy_lints/src/asm_syntax.rs
  clippy_lints/src/lib.rs
  src/lintlist/mod.rs
  tests/ui/asm_syntax.rs
  tests/ui/asm_syntax.stderr
Labels: S-waiting-on-author
