Repository rust-lang/rust-clippy, pull requests merged in 2020-03, with the labels that each got.

#5242 add test for #5238
  tests/ui/crashes/ice-5238.rs
Labels: S-waiting-on-review

#5250 Whitelist unused attribute for use items.
  clippy_lints/src/attrs.rs
  tests/ui/useless_attribute.fixed
  tests/ui/useless_attribute.rs
  tests/ui/useless_attribute.stderr
Labels: S-waiting-on-review

#5259 Use lang items instead of get_trait_def_id where possible
  clippy_lints/src/doc.rs
  clippy_lints/src/inherent_to_string.rs
  clippy_lints/src/neg_cmp_op_on_partial_ord.rs
  clippy_lints/src/utils/paths.rs
Labels: S-waiting-on-review

#5256 Use `try_eval_usize` over `eval_usize`
  clippy_lints/src/consts.rs
  clippy_lints/src/indexing_slicing.rs
  clippy_lints/src/methods/mod.rs
  tests/ui/crashes/ice-5223.rs
Labels: S-waiting-on-review

#5264 Rustup to rust-lang/rust#69506
  tests/ui/author/blocks.rs
  tests/ui/author/blocks.stdout
  tests/ui/swap.fixed
  tests/ui/swap.rs
Labels: S-waiting-on-review

#5246 Detect usage of custom floating-point abs implementation
  clippy_lints/src/floating_point_arithmetic.rs
  tests/ui/floating_point_abs.fixed
  tests/ui/floating_point_abs.rs
  tests/ui/floating_point_abs.stderr
Labels: S-waiting-on-rustup

#5258 Add lint for .. use in fully binded struct
  CHANGELOG.md
  README.md
  clippy_lints/src/lib.rs
  clippy_lints/src/matches.rs
  src/lintlist/mod.rs
  tests/ui/rest_pat_in_fully_bound_structs.rs
  tests/ui/rest_pat_in_fully_bound_structs.stderr
Labels: S-waiting-on-author

#5257 Resolve false positives of unnecessary_cast for non-decimal integers
  clippy_lints/src/float_literal.rs
  clippy_lints/src/floating_point_arithmetic.rs
  clippy_lints/src/literal_representation.rs
  clippy_lints/src/types.rs
  clippy_lints/src/utils/mod.rs
  clippy_lints/src/utils/numeric_literal.rs
  clippy_lints/src/utils/sugg.rs
  tests/ui/unnecessary_cast_fixable.fixed
  tests/ui/unnecessary_cast_fixable.rs
Labels: S-waiting-on-author

#5235 Fix deploy script for tag deploys
  .github/deploy.sh
Labels: S-waiting-on-review

#5230 Macro use
  CHANGELOG.md
  README.md
  clippy_lints/src/lib.rs
  clippy_lints/src/macro_use.rs
  src/lintlist/mod.rs
  tests/ui/macro_use_import.rs
  tests/ui/macro_use_import.stderr
Labels: S-waiting-on-rustup

#5291 Fix match single binding when in a let stmt
  clippy_lints/src/matches.rs
  tests/ui/match_single_binding.fixed
  tests/ui/match_single_binding.rs
  tests/ui/match_single_binding.stderr
Labels: S-waiting-on-author

#5292 Improve placeholder in map_unit_fn
  clippy_lints/src/map_unit_fn.rs
  tests/ui/option_map_unit_fn_fixable.fixed
  tests/ui/option_map_unit_fn_fixable.rs
  tests/ui/option_map_unit_fn_fixable.stderr
Labels: S-waiting-on-author

#5299 Clean-up docs
  CONTRIBUTING.md
  doc/adding_lints.md
Labels: S-waiting-on-review

#5272 add lint on File::read_to_string and File::read_to_end
  CHANGELOG.md
  README.md
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/paths.rs
  clippy_lints/src/verbose_file_reads.rs
  src/lintlist/mod.rs
  tests/ui/verbose_file_reads.rs
  tests/ui/verbose_file_reads.stderr
Labels: S-waiting-on-author

#5304 Extend `redundant_clone` to the case that cloned value is not consumed
  clippy_lints/src/redundant_clone.rs
  tests/ui/format.fixed
  tests/ui/format.rs
  tests/ui/redundant_clone.fixed
  tests/ui/redundant_clone.rs
  tests/ui/redundant_clone.stderr
Labels: S-waiting-on-rustup

#5308 Update Changelog
  CHANGELOG.md
  doc/changelog_update.md
Labels: S-waiting-on-review

#5316 Don't convert Path to lossy str
  tests/integration.rs
Labels: S-waiting-on-review

#5318 rustup https://github.com/rust-lang/rust/pull/69589/
  clippy_lints/src/dbg_macro.rs
  clippy_lints/src/non_expressive_names.rs
  clippy_lints/src/utils/sugg.rs
  clippy_lints/src/write.rs
Labels: S-blocked

#5329 integer_arithmetic: detect integer arithmetic on references.
  clippy_dev/src/stderr_length_check.rs
  clippy_lints/src/arithmetic.rs
  tests/ui/arithmetic.stderr
  tests/ui/checked_unwrap/complex_conditionals.rs
  tests/ui/checked_unwrap/complex_conditionals.stderr
  tests/ui/checked_unwrap/complex_conditionals_nested.rs
  tests/ui/checked_unwrap/complex_conditionals_nested.stderr
  tests/ui/float_arithmetic.rs
  tests/ui/float_arithmetic.stderr
  tests/ui/integer_arithmetic.rs
  tests/ui/integer_arithmetic.stderr
Labels: S-waiting-on-author

#5335 Update changelog to 1.43.0 beta
  CHANGELOG.md
Labels: S-waiting-on-review

#5336 rustup https://github.com/rust-lang/rust/pull/69920/
  clippy_lints/src/lib.rs
  clippy_lints/src/missing_inline.rs
  clippy_lints/src/trivially_copy_pass_by_ref.rs
  clippy_lints/src/utils/attrs.rs
  clippy_lints/src/utils/author.rs
  clippy_lints/src/utils/inspector.rs
Labels: S-blocked

#5323 Improvement: Don't show function body in needless_lifetimes
  clippy_lints/src/lifetimes.rs
  tests/ui/issue_4266.stderr
  tests/ui/needless_lifetimes.stderr
Labels: S-waiting-on-author

#5353 Fix documentation generation for configurable lints
  util/lintlib.py
Labels: S-waiting-on-review

#5350 Fix single binding closure
  clippy_lints/src/matches.rs
  tests/ui/match_single_binding.fixed
  tests/ui/match_single_binding.rs
  tests/ui/match_single_binding.stderr
Labels: S-waiting-on-rustup

#5319 Lint for `pub(crate)` items that are not crate visible due to the visibility of the module that contains them
  CHANGELOG.md
  README.md
  clippy_lints/src/lib.rs
  clippy_lints/src/redundant_pub_crate.rs
  clippy_lints/src/utils/conf.rs
  clippy_lints/src/utils/numeric_literal.rs
  src/lintlist/mod.rs
  tests/ui/redundant_pub_crate.fixed
  tests/ui/redundant_pub_crate.rs
  tests/ui/redundant_pub_crate.stderr
  tests/ui/wildcard_imports.fixed
  tests/ui/wildcard_imports.rs
  tests/ui/wildcard_imports.stderr
Labels: S-waiting-on-author

#5364 Move useless_transmute to nursery
  clippy_lints/src/lib.rs
  clippy_lints/src/transmute.rs
  src/lintlist/mod.rs
  tests/ui/transmute_ptr_to_ptr.stderr
Labels: S-waiting-on-review

#5376 Move verbose_file_reads to restriction
  clippy_lints/src/lib.rs
  clippy_lints/src/verbose_file_reads.rs
  src/lintlist/mod.rs
Labels: S-waiting-on-rustup

#5373 Document how to create releases and backports
  .github/deploy.sh
  .github/workflows/deploy.yml
  doc/backport.md
  doc/release.md
  util/gh-pages/versions.html
  util/versions.py
Labels: C-needs-discussion, S-waiting-on-review

#5365 Issue4983 bool updates
  clippy_lints/src/needless_bool.rs
  tests/ui/bool_comparison.fixed
  tests/ui/bool_comparison.rs
  tests/ui/bool_comparison.stderr
Labels: S-waiting-on-review

#5294 Lint unnamed address comparisons
  CHANGELOG.md
  README.md
  clippy_lints/src/lib.rs
  clippy_lints/src/unnamed_address.rs
  clippy_lints/src/utils/paths.rs
  src/lintlist/mod.rs
  tests/ui/fn_address_comparisons.rs
  tests/ui/fn_address_comparisons.stderr
  tests/ui/vtable_address_comparisons.rs
  tests/ui/vtable_address_comparisons.stderr
Labels: S-waiting-on-author, S-waiting-on-review

#5293 don't emit lifetime lint warnings for code inside macros.
  clippy_lints/src/lifetimes.rs
Labels: S-waiting-on-author
