Repository rust-lang/rust-clippy, pull requests merged in 2020-05, with the labels that each got.

#5536 Fix the bugs of `manual_memcpy`, simplify the suggestion and refactor it
  clippy_lints/src/loops.rs
  tests/ui/manual_memcpy.rs
  tests/ui/manual_memcpy.stderr
Labels: S-waiting-on-author

#5555 Move match_on_vec_items to pedantic
  clippy_lints/src/lib.rs
  clippy_lints/src/match_on_vec_items.rs
  src/lintlist/mod.rs
Labels: S-waiting-on-review

#5550 Implement the manual_non_exhaustive lint
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_non_exhaustive.rs
  src/lintlist/mod.rs
  tests/ui/manual_non_exhaustive.rs
  tests/ui/manual_non_exhaustive.stderr
Labels: S-waiting-on-author

#5559 Fix FP on while-let-on-iterator
  clippy_lints/src/utils/mod.rs
  tests/ui/while_let_on_iterator.fixed
  tests/ui/while_let_on_iterator.rs
  tests/ui/while_let_on_iterator.stderr
Labels: S-waiting-on-review

#5558 Fix `unnecessary_unwrap` lint when checks are done in parameters
  clippy_lints/src/unwrap.rs
  tests/ui/checked_unwrap/simple_conditionals.rs
  tests/ui/checked_unwrap/simple_conditionals.stderr
Labels: S-waiting-on-review

#5560 Fix match on vec items: match on vec[..]
  clippy_lints/src/match_on_vec_items.rs
  clippy_lints/src/utils/paths.rs
  tests/ui/match_on_vec_items.rs
Labels: S-waiting-on-author

#5576 Add the manual_async_fn lint
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_async_fn.rs
  clippy_lints/src/utils/paths.rs
  src/lintlist/mod.rs
  tests/ui/future_not_send.rs
  tests/ui/future_not_send.stderr
  tests/ui/manual_async_fn.fixed
  tests/ui/manual_async_fn.rs
  tests/ui/manual_async_fn.stderr
Labels: S-waiting-on-author

#5541 Extend example for the `unneeded_field_pattern` lint
  clippy_lints/src/misc_early.rs
Labels: S-waiting-on-rustup

#5564 Allow `use super::*;` glob imports
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/conf.rs
  clippy_lints/src/wildcard_imports.rs
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
  tests/ui/wildcard_imports.fixed
  tests/ui/wildcard_imports.rs
  tests/ui/wildcard_imports.stderr
Labels: S-waiting-on-author

#5587 Rustup
  clippy_lints/src/bytecount.rs
  clippy_lints/src/inline_fn_without_body.rs
  clippy_lints/src/len_zero.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/map_clone.rs
  clippy_lints/src/non_expressive_names.rs
  clippy_lints/src/unsafe_removed_from_name.rs
  clippy_lints/src/utils/hir_utils.rs
  clippy_lints/src/utils/internal_lints.rs
  clippy_lints/src/utils/mod.rs
  clippy_lints/src/utils/ptr.rs
  clippy_lints/src/utils/usage.rs
  tests/ui/implicit_saturating_sub.fixed
  tests/ui/implicit_saturating_sub.rs
Labels: S-waiting-on-review

#5590 Fix ICE caused in unwrap module
  clippy_lints/src/unwrap.rs
  tests/ui/crashes/ice-5579.rs
Labels: S-waiting-on-author

#5583 Reversed empty ranges
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/loops.rs
  clippy_lints/src/ranges.rs
  src/lintlist/mod.rs
  tests/ui/for_loop_fixable.fixed
  tests/ui/for_loop_fixable.rs
  tests/ui/for_loop_fixable.stderr
  tests/ui/for_loop_unfixable.rs
  tests/ui/for_loop_unfixable.stderr
  tests/ui/manual_memcpy.rs
  tests/ui/reversed_empty_ranges_fixable.fixed
  tests/ui/reversed_empty_ranges_fixable.rs
  tests/ui/reversed_empty_ranges_fixable.stderr
  tests/ui/reversed_empty_ranges_loops_fixable.fixed
  tests/ui/reversed_empty_ranges_loops_fixable.rs
  tests/ui/reversed_empty_ranges_loops_fixable.stderr
  tests/ui/reversed_empty_ranges_loops_unfixable.rs
  tests/ui/reversed_empty_ranges_loops_unfixable.stderr
  tests/ui/reversed_empty_ranges_unfixable.rs
  tests/ui/reversed_empty_ranges_unfixable.stderr
Labels: S-waiting-on-author

#5592 unused_unit: lint also in type parameters and where clauses
  clippy_lints/src/returns.rs
  tests/ui/unused_unit.fixed
  tests/ui/unused_unit.rs
  tests/ui/unused_unit.stderr
Labels: S-waiting-on-author

#5596 Fix comparison_chain false positive
  clippy_lints/src/comparison_chain.rs
  tests/ui/comparison_chain.rs
Labels: S-waiting-on-review

#5563 Merge some lints together
  CHANGELOG.md
  clippy_lints/src/blocks_in_if_conditions.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/loops.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/option_map_unwrap_or.rs
  src/lintlist/mod.rs
  tests/ui/blocks_in_if_conditions.fixed
  tests/ui/blocks_in_if_conditions.rs
  tests/ui/blocks_in_if_conditions.stderr
  tests/ui/blocks_in_if_conditions_closure.rs
  tests/ui/blocks_in_if_conditions_closure.stderr
  tests/ui/expect.rs
  tests/ui/expect.stderr
  tests/ui/for_loops_over_fallibles.rs
  tests/ui/for_loops_over_fallibles.stderr
  tests/ui/map_unwrap_or.rs
  tests/ui/map_unwrap_or.stderr
  tests/ui/result_map_unwrap_or_else.rs
  tests/ui/result_map_unwrap_or_else.stderr
  tests/ui/unwrap.rs
  tests/ui/unwrap.stderr
Labels: C-needs-discussion, S-waiting-on-review

#5529 Improve `option_and_then_some` lint
  CHANGELOG.md
  clippy_lints/src/eq_op.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/loops.rs
  clippy_lints/src/matches.rs
  clippy_lints/src/methods/bind_instead_of_map.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/needless_pass_by_value.rs
  clippy_lints/src/types.rs
  clippy_lints/src/utils/diagnostics.rs
  src/lintlist/mod.rs
  tests/ui/bind_instead_of_map.fixed
  tests/ui/bind_instead_of_map.rs
  tests/ui/bind_instead_of_map.stderr
  tests/ui/bind_instead_of_map_multipart.rs
  tests/ui/bind_instead_of_map_multipart.stderr
  tests/ui/blocks_in_if_conditions.fixed
  tests/ui/blocks_in_if_conditions.rs
  tests/ui/option_map_or_none.fixed
  tests/ui/option_map_or_none.rs
Labels: S-waiting-on-review

#5568 Rename lint `identity_conversion` to `useless_conversion`
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/useless_conversion.rs
  src/lintlist/mod.rs
  tests/ui/useless_conversion.fixed
  tests/ui/useless_conversion.rs
  tests/ui/useless_conversion.stderr
Labels: S-waiting-on-rustup

#5621 Rustup
  clippy_lints/src/loops.rs
  clippy_lints/src/utils/author.rs
  clippy_lints/src/utils/hir_utils.rs
  clippy_lints/src/utils/inspector.rs
  clippy_lints/src/utils/sugg.rs
  clippy_lints/src/write.rs
  mini-macro/src/lib.rs
  tests/ui/auxiliary/proc_macro_derive.rs
  tests/ui/crashes/ice-3741.rs
  tests/ui/ptr_offset_with_cast.fixed
  tests/ui/ptr_offset_with_cast.rs
  tests/ui/ptr_offset_with_cast.stderr
Labels: S-waiting-on-review

#5582 New lint: `match_wildcard_for_single_variants`
  CHANGELOG.md
  clippy_lints/src/float_literal.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/matches.rs
  clippy_lints/src/misc_early.rs
  clippy_lints/src/missing_const_for_fn.rs
  clippy_lints/src/needless_pass_by_value.rs
  clippy_lints/src/trivially_copy_pass_by_ref.rs
  clippy_lints/src/utils/mod.rs
  src/lintlist/mod.rs
  tests/compile-test.rs
  tests/ui/match_wildcard_for_single_variants.fixed
  tests/ui/match_wildcard_for_single_variants.rs
  tests/ui/match_wildcard_for_single_variants.stderr
Labels: S-waiting-on-rustup

#5622 Downgrade `match_wild_err_arm` to pedantic and update help messages
  clippy_lints/src/lib.rs
  clippy_lints/src/matches.rs
  src/lintlist/mod.rs
  tests/ui/future_not_send.stderr
  tests/ui/match_wild_err_arm.stderr
Labels: S-waiting-on-author

#5614 Test cargo lints
  clippy_dev/src/new_lint.rs
  clippy_lints/src/cargo_common_metadata.rs
  clippy_lints/src/multiple_crate_versions.rs
  doc/adding_lints.md
  tests/compile-test.rs
  tests/ui-cargo/cargo_common_metadata/fail/Cargo.toml
  tests/ui-cargo/cargo_common_metadata/fail/src/main.rs
  tests/ui-cargo/cargo_common_metadata/fail/src/main.stderr
  tests/ui-cargo/cargo_common_metadata/pass/Cargo.toml
  tests/ui-cargo/cargo_common_metadata/pass/src/main.rs
  tests/ui-cargo/multiple_crate_versions/fail/Cargo.toml
  tests/ui-cargo/multiple_crate_versions/fail/src/main.rs
  tests/ui-cargo/multiple_crate_versions/fail/src/main.stderr
  tests/ui-cargo/multiple_crate_versions/pass/Cargo.toml
  tests/ui-cargo/multiple_crate_versions/pass/src/main.rs
  tests/ui-cargo/update-all-references.sh
  tests/ui-cargo/update-references.sh
  tests/ui-cargo/wildcard_dependencies/fail/Cargo.toml
  tests/ui-cargo/wildcard_dependencies/fail/src/main.rs
  tests/ui-cargo/wildcard_dependencies/fail/src/main.stderr
  tests/ui-cargo/wildcard_dependencies/pass/Cargo.toml
  tests/ui-cargo/wildcard_dependencies/pass/src/main.rs
Labels: S-waiting-on-author

#5632 Rustup
  clippy_lints/src/future_not_send.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/needless_pass_by_value.rs
  clippy_lints/src/utils/mod.rs
  setup-toolchain.sh
Labels: S-waiting-on-review

#5639 Clarify the documentation of the `unnecessary_mut_passed` lint
  clippy_lints/src/mut_reference.rs
Labels: S-waiting-on-rustup

#5616 new_without_default: do not suggest deriving
  clippy_lints/src/new_without_default.rs
  tests/ui/new_without_default.rs
  tests/ui/new_without_default.stderr
Labels: S-waiting-on-rustup

#5635 option_option test case #4298
  tests/ui/option_option.rs
  tests/ui/option_option.stderr
Labels: S-waiting-on-review

#5641 Add common lint tools doc
  doc/adding_lints.md
  doc/common_tools_writing_lints.md
Labels: S-waiting-on-author

#4429 Update 'or_fun_call' to ignore calls to len
  clippy_lints/src/methods/mod.rs
  tests/ui/or_fun_call.fixed
  tests/ui/or_fun_call.rs
Labels: S-waiting-on-review

#5647 ptr_arg: honor `allow` attribute on arguments
  clippy_lints/src/ptr.rs
  clippy_lints/src/utils/sugg.rs
  tests/ui/ptr_arg.rs
Labels: S-waiting-on-review

#5562 Update contributing section about syncing Clippy
  CONTRIBUTING.md
Labels: S-waiting-on-review

#5638 reversed_empty_ranges: add suggestion for &slice[N..N]
  clippy_lints/src/ranges.rs
  tests/ui/reversed_empty_ranges_fixable.fixed
  tests/ui/reversed_empty_ranges_fixable.rs
  tests/ui/reversed_empty_ranges_fixable.stderr
  tests/ui/reversed_empty_ranges_unfixable.rs
  tests/ui/reversed_empty_ranges_unfixable.stderr
Labels: S-waiting-on-rustup

#5609 Make empty_line_after_outer_attr an early lint
  clippy_lints/Cargo.toml
  clippy_lints/src/attrs.rs
  tests/compile-test.rs
  tests/ui/auxiliary/proc_macro_attr.rs
  tests/ui/empty_line_after_outer_attribute.rs
  tests/ui/empty_line_after_outer_attribute.stderr
Labels: S-waiting-on-author

#5648 Add license symlink
  rustc_tools_util/LICENSE-APACHE
  rustc_tools_util/LICENSE-MIT
Labels: S-waiting-on-review

#5650 Bump actions/cache from v1 to v2
  .github/workflows/clippy.yml
  .github/workflows/clippy_bors.yml
Labels: S-waiting-on-review

#5651 Register redundant_field_names and non_expressive_names as early passes
  clippy_lints/src/lib.rs
  clippy_lints/src/new_without_default.rs
  clippy_lints/src/non_expressive_names.rs
  clippy_lints/src/redundant_field_names.rs
  src/driver.rs
Labels: S-waiting-on-review

#5653 rustup https://github.com/rust-lang/rust/pull/72342, allow unused_crate_dependencies
  tests/ui/cognitive_complexity.rs
  tests/ui/cognitive_complexity_attr_used.rs
Labels: S-waiting-on-review

#5631 Extend useless conversion
  clippy_lints/src/useless_conversion.rs
  clippy_lints/src/utils/paths.rs
  src/lintlist/mod.rs
  tests/ui/useless_conversion.stderr
  tests/ui/useless_conversion_try.rs
  tests/ui/useless_conversion_try.stderr
Labels: S-waiting-on-rustup

#5652 Fail bors on missing changelog
  .github/workflows/clippy_bors.yml
Labels: S-waiting-on-review

#5665 Rustup
  clippy_lints/src/needless_pass_by_value.rs
  clippy_lints/src/write.rs
  src/driver.rs
  tests/compile-test.rs
Labels: S-waiting-on-review

#5655 cargo_dev: add ra-setup
  clippy_dev/src/lib.rs
  clippy_dev/src/main.rs
  clippy_dev/src/ra_setup.rs
Labels: S-waiting-on-rustup

#5663 add testcase that no longer ICEs
  tests/ui/crashes/ice-3969.rs
  tests/ui/crashes/ice-3969.stderr
Labels: S-waiting-on-rustup

#5656 len_zero: skip ranges if feature `range_is_empty` is not enabled
  clippy_lints/src/len_zero.rs
  tests/ui/len_zero.fixed
  tests/ui/len_zero.rs
  tests/ui/len_zero_ranges.fixed
  tests/ui/len_zero_ranges.rs
  tests/ui/len_zero_ranges.stderr
Labels: S-waiting-on-rustup

#5637 new lint: vec_resize_to_zero
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/paths.rs
  clippy_lints/src/vec_resize_to_zero.rs
  src/lintlist/mod.rs
  tests/ui/vec_resize_to_zero.rs
  tests/ui/vec_resize_to_zero.stderr
Labels: S-waiting-on-rustup

#5667 moved cast_ptr_alignment to pedantic and expanded documentation
  clippy_lints/src/lib.rs
  clippy_lints/src/types.rs
  src/lintlist/mod.rs
Labels: S-waiting-on-author

#5669 Increase cargo_metadata version to 0.9.1
  Cargo.toml
  clippy_lints/Cargo.toml
Labels: S-waiting-on-review

#4455 Rework suggestion generation of `unit_arg` lint
  clippy_lints/src/types.rs
  tests/ui/unit_arg.fixed
  tests/ui/unit_arg.rs
  tests/ui/unit_arg.stderr
  tests/ui/unit_arg_empty_blocks.rs
  tests/ui/unit_arg_empty_blocks.stderr
Labels: S-waiting-on-author, S-waiting-on-review

#5662 cargo-ui tests: check that <dir>/src exists before processing test
  tests/compile-test.rs
Labels: S-waiting-on-author

#5661 CONTRIBUTING: explain how to use cargo dev ra-setup
  CONTRIBUTING.md
Labels: S-waiting-on-author
