Repository rust-lang/rust-clippy, pull requests merged in 2020-04, with the labels that each got.

#5400 Rustups
  clippy_lints/src/loops.rs
  clippy_lints/src/redundant_clone.rs
  clippy_lints/src/utils/higher.rs
  clippy_lints/src/utils/paths.rs
  tests/ui/or_fun_call.fixed
  tests/ui/or_fun_call.rs
  tests/ui/or_fun_call.stderr
  tests/ui/unit_arg.fixed
  tests/ui/unit_arg.rs
Labels: S-waiting-on-review

#5402 Allow let_underscore_must_use to be ignored
  clippy_lints/src/let_underscore.rs
  tests/ui/let_underscore_must_use.rs
Labels: S-waiting-on-review

#5349 useless Rc<Rc<T>>, Rc<Box<T>>, Rc<&T>, Box<&T>
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/types.rs
  clippy_lints/src/utils/paths.rs
  src/lintlist/mod.rs
  tests/ui/must_use_candidates.fixed
  tests/ui/must_use_candidates.rs
  tests/ui/redundant_allocation.fixed
  tests/ui/redundant_allocation.rs
  tests/ui/redundant_allocation.stderr
Labels: S-waiting-on-author

#5403 Improve docs for option_option
  clippy_lints/src/types.rs
Labels: S-waiting-on-review

#5429 Use assoc int and float consts instead of module level ones
  clippy_lints/src/checked_conversions.rs
  clippy_lints/src/float_literal.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/misc.rs
  clippy_lints/src/neg_cmp_op_on_partial_ord.rs
  clippy_lints/src/types.rs
  clippy_lints/src/utils/diagnostics.rs
  clippy_lints/src/zero_div_zero.rs
  src/lintlist/mod.rs
  tests/ui/absurd-extreme-comparisons.rs
  tests/ui/absurd-extreme-comparisons.stderr
  tests/ui/cmp_nan.rs
  tests/ui/cmp_nan.stderr
  tests/ui/crashes/mut_mut_macro.rs
  tests/ui/enum_clike_unportable_variant.rs
  tests/ui/enum_clike_unportable_variant.stderr
  tests/ui/float_cmp.rs
  tests/ui/float_cmp.stderr
  tests/ui/float_cmp_const.rs
  tests/ui/float_cmp_const.stderr
  tests/ui/if_same_then_else.rs
  tests/ui/if_same_then_else2.rs
  tests/ui/if_same_then_else2.stderr
  tests/ui/zero_div_zero.stderr
Labels: S-waiting-on-rustup

#5425 Ehance opt_as_ref_deref lint.
  clippy_lints/src/loops.rs
  clippy_lints/src/methods/mod.rs
  tests/ui/option_as_ref_deref.fixed
  tests/ui/option_as_ref_deref.rs
  tests/ui/option_as_ref_deref.stderr
Labels: S-waiting-on-rustup

#5424 Incorrect suspicious_op_assign_impl
  clippy_lints/src/suspicious_trait_impl.rs
  tests/ui/suspicious_arithmetic_impl.rs
  tests/ui/suspicious_arithmetic_impl.stderr
Labels: S-waiting-on-rustup

#5422 CONTRIBUTING.md: fix broken triage link
  CONTRIBUTING.md
Labels: S-waiting-on-rustup

#5420 Downgrade new_ret_no_self to pedantic
  clippy_lints/src/lib.rs
  clippy_lints/src/methods/mod.rs
  src/lintlist/mod.rs
Labels: S-waiting-on-rustup

#5419 Downgrade unreadable_literal to pedantic
  clippy_lints/src/lib.rs
  clippy_lints/src/literal_representation.rs
  src/lintlist/mod.rs
  tests/ui/approx_const.rs
  tests/ui/inconsistent_digit_grouping.fixed
  tests/ui/inconsistent_digit_grouping.rs
  tests/ui/inconsistent_digit_grouping.stderr
Labels: S-waiting-on-rustup

#5415 Add new lint for `Result<T, E>.map_or(None, Some(T))`
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/methods/mod.rs
  src/lintlist/mod.rs
  tests/ui/result_map_or_into_option.fixed
  tests/ui/result_map_or_into_option.rs
  tests/ui/result_map_or_into_option.stderr
Labels: S-waiting-on-rustup

#5417 Update doc links and mentioned names in docs
  CONTRIBUTING.md
  doc/adding_lints.md
Labels: S-waiting-on-rustup

#5412 Downgrade inefficient_to_string to pedantic
  clippy_lints/src/lib.rs
  clippy_lints/src/methods/mod.rs
  src/lintlist/mod.rs
Labels: S-waiting-on-rustup

#5410 Downgrade trivially_copy_pass_by_ref to pedantic
  clippy_lints/src/lib.rs
  clippy_lints/src/trivially_copy_pass_by_ref.rs
  src/lintlist/mod.rs
  tests/ui-toml/toml_trivially_copy/test.rs
  tests/ui-toml/toml_trivially_copy/test.stderr
  tests/ui/clone_on_copy_mut.rs
  tests/ui/debug_assert_with_mut_call.rs
  tests/ui/eta.fixed
  tests/ui/eta.rs
  tests/ui/eta.stderr
  tests/ui/extra_unused_lifetimes.rs
  tests/ui/extra_unused_lifetimes.stderr
  tests/ui/float_arithmetic.rs
  tests/ui/float_arithmetic.stderr
  tests/ui/infinite_iter.rs
  tests/ui/infinite_iter.stderr
  tests/ui/infinite_loop.rs
  tests/ui/infinite_loop.stderr
  tests/ui/integer_arithmetic.rs
  tests/ui/integer_arithmetic.stderr
  tests/ui/mut_from_ref.rs
  tests/ui/mut_reference.rs
  tests/ui/needless_borrow.fixed
  tests/ui/needless_borrow.rs
  tests/ui/needless_borrow.stderr
  tests/ui/needless_lifetimes.rs
  tests/ui/new_ret_no_self.rs
  tests/ui/trivially_copy_pass_by_ref.rs
  tests/ui/trivially_copy_pass_by_ref.stderr
  tests/ui/useless_asref.fixed
  tests/ui/useless_asref.rs
  tests/ui/useless_asref.stderr
  tests/ui/wrong_self_convention.rs
Labels: S-waiting-on-rustup

#5409 Downgrade let_unit_value to pedantic
  clippy_lints/src/lib.rs
  clippy_lints/src/types.rs
  src/lintlist/mod.rs
  tests/ui/doc_unsafe.rs
  tests/ui/redundant_pattern_matching.fixed
  tests/ui/redundant_pattern_matching.rs
  tests/ui/uninit.rs
  tests/ui/uninit.stderr
Labels: S-waiting-on-rustup

#5406 Fix update_lints
  clippy_dev/src/lib.rs
  clippy_dev/src/update_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/matches.rs
  tests/matches.rs
Labels: S-waiting-on-rustup

#5428 Move cognitive_complexity to nursery
  clippy_lints/src/assign_ops.rs
  clippy_lints/src/cognitive_complexity.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/mutable_debug_assertion.rs
  clippy_lints/src/types.rs
  src/lintlist/mod.rs
  tests/ui/collapsible_else_if.fixed
  tests/ui/collapsible_else_if.rs
  tests/ui/collapsible_if.fixed
  tests/ui/collapsible_if.rs
  tests/ui/debug_assert_with_mut_call.rs
  tests/ui/for_loop_fixable.fixed
  tests/ui/for_loop_fixable.rs
  tests/ui/for_loop_fixable.stderr
  tests/ui/for_loop_unfixable.rs
  tests/ui/for_loop_unfixable.stderr
  tests/ui/if_same_then_else2.rs
  tests/ui/if_same_then_else2.stderr
  tests/ui/rename.fixed
  tests/ui/rename.rs
  tests/ui/rename.stderr
  tests/ui/while_let_on_iterator.rs
Labels: S-waiting-on-rustup

#5437 Check fn header along with decl when suggesting to implement trait
  clippy_lints/src/methods/mod.rs
  tests/ui/methods.rs
  tests/ui/methods.stderr
Labels: S-waiting-on-author

#5411 Downgrade implicit_hasher to pedantic
  clippy_lints/src/lib.rs
  clippy_lints/src/types.rs
  src/lintlist/mod.rs
  tests/ui/crashes/ice-3717.rs
  tests/ui/crashes/ice-3717.stderr
  tests/ui/implicit_hasher.rs
  tests/ui/implicit_hasher.stderr
  tests/ui/mut_key.rs
  tests/ui/mut_key.stderr
Labels: S-waiting-on-rustup

#5442 Revert "Downgrade new_ret_no_self to pedantic"
  clippy_lints/src/lib.rs
  clippy_lints/src/methods/mod.rs
  src/lintlist/mod.rs
Labels: S-waiting-on-review

#5461 Temporarily disable rustfmt integration test
  .github/workflows/clippy_bors.yml
  tests/integration.rs
Labels: S-waiting-on-review

#5458 Cleanup: Use rustc's is_proc_macro_attr
  clippy_lints/src/utils/attrs.rs
Labels: S-waiting-on-review

#5453 Fixes #5405: redundant clone false positive with arrays
  clippy_lints/src/redundant_clone.rs
  tests/ui/redundant_clone.fixed
  tests/ui/redundant_clone.rs
  tests/ui/redundant_clone.stderr
Labels: S-waiting-on-review

#5457 Cleanup: Use our `sym!` macro more
  clippy_lints/src/get_last_with_len.rs
  clippy_lints/src/loops.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/needless_pass_by_value.rs
  clippy_lints/src/ptr.rs
  clippy_lints/src/swap.rs
  clippy_lints/src/types.rs
Labels: S-waiting-on-review

#5460 result_map_unit_fn: Fix incorrect UI tests
  tests/ui/result_map_unit_fn_unfixable.rs
  tests/ui/result_map_unit_fn_unfixable.stderr
Labels: S-waiting-on-review

#5449 Make use of more diagnostic items
  clippy_lints/src/booleans.rs
  clippy_lints/src/cognitive_complexity.rs
  clippy_lints/src/doc.rs
  clippy_lints/src/fallible_impl_from.rs
  clippy_lints/src/if_let_some_result.rs
  clippy_lints/src/loops.rs
  clippy_lints/src/map_clone.rs
  clippy_lints/src/map_unit_fn.rs
  clippy_lints/src/matches.rs
  clippy_lints/src/mem_replace.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/option_map_unwrap_or.rs
  clippy_lints/src/question_mark.rs
  clippy_lints/src/types.rs
  clippy_lints/src/unwrap.rs
  clippy_lints/src/utils/paths.rs
Labels: S-waiting-on-review

#5452 Refactor: Use rustc's `match_def_path`
  clippy_lints/src/utils/mod.rs
Labels: S-waiting-on-review

#5345 Add lint for float in array comparison
  clippy_lints/src/consts.rs
  clippy_lints/src/misc.rs
  tests/ui/float_cmp.rs
  tests/ui/float_cmp.stderr
  tests/ui/float_cmp_const.rs
  tests/ui/float_cmp_const.stderr
Labels: S-waiting-on-author

#5467 rustup https://github.com/rust-lang/rust/pull/71116
  clippy_lints/src/utils/author.rs
Labels: S-waiting-on-author

#5468 Zero single char names
  clippy_lints/src/non_expressive_names.rs
  clippy_lints/src/utils/conf.rs
  tests/ui-toml/zero_single_char_names/clippy.toml
  tests/ui-toml/zero_single_char_names/zero_single_char_names.rs
Labels: S-waiting-on-rustup

#5466 large_enum_variant: Report sizes of variants
  clippy_lints/src/large_enum_variant.rs
  tests/ui/large_enum_variant.stderr
Labels: S-waiting-on-rustup

#5430 Disallow bit-shifting in integer_arithmetic
  clippy_lints/src/arithmetic.rs
  src/lintlist/mod.rs
  tests/ui/integer_arithmetic.rs
  tests/ui/integer_arithmetic.stderr
Labels: S-waiting-on-rustup

#5248 Add lint on large non scalar const
  CHANGELOG.md
  clippy_lints/src/large_const_arrays.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/conf.rs
  src/lintlist/mod.rs
  tests/ui/large_const_arrays.fixed
  tests/ui/large_const_arrays.rs
  tests/ui/large_const_arrays.stderr
  util/lintlib.py
Labels: L-lint, S-waiting-on-rustup

#5226 Add lint for explicit deref and deref_mut method calls
  CHANGELOG.md
  clippy_lints/src/dereference.rs
  clippy_lints/src/lib.rs
  src/lintlist/mod.rs
  tests/ui/dereference.fixed
  tests/ui/dereference.rs
  tests/ui/dereference.stderr
Labels: S-waiting-on-rustup

#5363 add --fix support to `cargo-clippy`
  src/main.rs
Labels: S-waiting-on-author

#5474 Reenable rustfmt integration test
  .github/workflows/clippy_bors.yml
Labels: S-waiting-on-rustup

#5473 Map flatten for option
  clippy_lints/src/methods/mod.rs
  tests/ui/map_flatten.fixed
  tests/ui/map_flatten.rs
  tests/ui/map_flatten.stderr
Labels: S-waiting-on-rustup

#5475 [fix] Minor typo in GH Actions 'clippy_dev'
  .github/workflows/clippy_dev.yml
Labels: S-waiting-on-rustup

#5476 Do not lint in macros for match lints
  clippy_lints/src/matches.rs
  tests/ui/infallible_destructuring_match.fixed
  tests/ui/infallible_destructuring_match.rs
  tests/ui/infallible_destructuring_match.stderr
  tests/ui/match_single_binding.fixed
  tests/ui/match_single_binding.rs
  tests/ui/match_single_binding.stderr
  tests/ui/rest_pat_in_fully_bound_structs.rs
  tests/ui/rest_pat_in_fully_bound_structs.stderr
Labels: S-waiting-on-rustup

#5482 Cleanup: Rename 'db' variables to 'diag'
  clippy_lints/src/assign_ops.rs
  clippy_lints/src/attrs.rs
  clippy_lints/src/bit_mask.rs
  clippy_lints/src/booleans.rs
  clippy_lints/src/collapsible_if.rs
  clippy_lints/src/copies.rs
  clippy_lints/src/derive.rs
  clippy_lints/src/empty_enum.rs
  clippy_lints/src/entry.rs
  clippy_lints/src/eq_op.rs
  clippy_lints/src/eta_reduction.rs
  clippy_lints/src/fallible_impl_from.rs
  clippy_lints/src/format.rs
  clippy_lints/src/functions.rs
  clippy_lints/src/identity_conversion.rs
  clippy_lints/src/implicit_return.rs
  clippy_lints/src/inherent_impl.rs
  clippy_lints/src/inline_fn_without_body.rs
  clippy_lints/src/int_plus_one.rs
  clippy_lints/src/large_const_arrays.rs
  clippy_lints/src/large_enum_variant.rs
  clippy_lints/src/let_if_seq.rs
  clippy_lints/src/loops.rs
  clippy_lints/src/map_unit_fn.rs
  clippy_lints/src/matches.rs
  clippy_lints/src/mem_discriminant.rs
  clippy_lints/src/mem_replace.rs
  clippy_lints/src/methods/inefficient_to_string.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/option_map_unwrap_or.rs
  clippy_lints/src/misc.rs
  clippy_lints/src/misc_early.rs
  clippy_lints/src/modulo_arithmetic.rs
  clippy_lints/src/needless_borrow.rs
  clippy_lints/src/needless_borrowed_ref.rs
  clippy_lints/src/needless_pass_by_value.rs
  clippy_lints/src/new_without_default.rs
  clippy_lints/src/non_copy_const.rs
  clippy_lints/src/ptr.rs
  clippy_lints/src/ranges.rs
  clippy_lints/src/redundant_clone.rs
  clippy_lints/src/redundant_pattern_matching.rs
  clippy_lints/src/redundant_pub_crate.rs
  clippy_lints/src/redundant_static_lifetimes.rs
  clippy_lints/src/returns.rs
  clippy_lints/src/shadow.rs
  clippy_lints/src/slow_vector_initialization.rs
  clippy_lints/src/swap.rs
  clippy_lints/src/transmute.rs
  clippy_lints/src/types.rs
  clippy_lints/src/unwrap.rs
  clippy_lints/src/utils/attrs.rs
  clippy_lints/src/utils/diagnostics.rs
  clippy_lints/src/utils/sugg.rs
Labels: S-waiting-on-review

#5445 Fixes issue #4892.
  clippy_lints/src/precedence.rs
  tests/ui/precedence.fixed
  tests/ui/precedence.rs
Labels: S-waiting-on-author

#5423 add lint futures_not_send
  CHANGELOG.md
  clippy_lints/src/future_not_send.rs
  clippy_lints/src/lib.rs
  src/lintlist/mod.rs
  tests/ui/future_not_send.rs
  tests/ui/future_not_send.stderr
Labels: S-waiting-on-author

#5483 fix redundant_pattern_matching lint
  clippy_lints/src/redundant_pattern_matching.rs
  tests/ui/redundant_pattern_matching.fixed
  tests/ui/redundant_pattern_matching.rs
  tests/ui/redundant_pattern_matching.stderr
Labels: S-waiting-on-author

#5427 Add lint named implicit_saturating_sub
  CHANGELOG.md
  clippy_lints/src/implicit_saturating_sub.rs
  clippy_lints/src/lib.rs
  src/lintlist/mod.rs
  tests/ui/implicit_saturating_sub.fixed
  tests/ui/implicit_saturating_sub.rs
  tests/ui/implicit_saturating_sub.stderr
Labels: S-waiting-on-author

#5488 Cleanup: future_not_send: use `utils::return_ty` function
  clippy_lints/src/future_not_send.rs
Labels: S-waiting-on-review

#5489 Cleanup: `node_id` -> `hir_id`
  clippy_lints/src/derive.rs
  clippy_lints/src/loops.rs
  clippy_lints/src/missing_inline.rs
Labels: S-waiting-on-review

#5491 Fix issue #2907.
  clippy_lints/src/types.rs
  tests/ui/borrow_box.rs
  tests/ui/borrow_box.stderr
Labels: S-waiting-on-review

#5141 Fixes issue 5095
  clippy_lints/src/as_conversions.rs
  clippy_lints/src/assertions_on_constants.rs
  clippy_lints/src/atomic_ordering.rs
  clippy_lints/src/cognitive_complexity.rs
  clippy_lints/src/comparison_chain.rs
  clippy_lints/src/copies.rs
  clippy_lints/src/copy_iterator.rs
  clippy_lints/src/dbg_macro.rs
  clippy_lints/src/derive.rs
  clippy_lints/src/drop_forget_ref.rs
  clippy_lints/src/else_if_without_else.rs
  clippy_lints/src/empty_enum.rs
  clippy_lints/src/enum_variants.rs
  clippy_lints/src/eta_reduction.rs
  clippy_lints/src/eval_order_dependence.rs
  clippy_lints/src/excessive_bools.rs
  clippy_lints/src/formatting.rs
  clippy_lints/src/functions.rs
  clippy_lints/src/identity_conversion.rs
  clippy_lints/src/if_not_else.rs
  clippy_lints/src/indexing_slicing.rs
  clippy_lints/src/inherent_to_string.rs
  clippy_lints/src/int_plus_one.rs
  clippy_lints/src/integer_division.rs
  clippy_lints/src/large_stack_arrays.rs
  clippy_lints/src/let_underscore.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/loops.rs
  clippy_lints/src/main_recursion.rs
  clippy_lints/src/matches.rs
  clippy_lints/src/mem_replace.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/misc_early.rs
  clippy_lints/src/needless_continue.rs
  clippy_lints/src/option_env_unwrap.rs
  clippy_lints/src/ptr.rs
  clippy_lints/src/regex.rs
  clippy_lints/src/returns.rs
  clippy_lints/src/trait_bounds.rs
  clippy_lints/src/transmute.rs
  clippy_lints/src/types.rs
  clippy_lints/src/unnamed_address.rs
  clippy_lints/src/unused_self.rs
  clippy_lints/src/utils/diagnostics.rs
  clippy_lints/src/utils/internal_lints.rs
  clippy_lints/src/verbose_file_reads.rs
  clippy_lints/src/zero_div_zero.rs
  doc/adding_lints.md
  tests/ui/collapsible_span_lint_calls.fixed
  tests/ui/collapsible_span_lint_calls.rs
  tests/ui/collapsible_span_lint_calls.stderr
  tests/ui/empty_enum.stderr
Labels: S-waiting-on-review

#5332 If let else mutex
  CHANGELOG.md
  README.md
  clippy_lints/src/if_let_mutex.rs
  clippy_lints/src/lib.rs
  doc/adding_lints.md
  src/lintlist/mod.rs
  tests/ui/if_let_mutex.rs
  tests/ui/if_let_mutex.stderr
Labels: L-lint, S-waiting-on-author

#5495 Update the changelog update documentation
  doc/changelog_update.md
Labels: S-waiting-on-review

#5496 util/fetch_prs_between.sh: Add Markdown formatted link
  util/fetch_prs_between.sh
Labels: S-waiting-on-review

#5439 Lint for holding locks across await points
  CHANGELOG.md
  clippy_lints/src/await_holding_lock.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/paths.rs
  src/lintlist/mod.rs
  tests/ui/await_holding_lock.rs
  tests/ui/await_holding_lock.stderr
Labels: S-waiting-on-review

#5498 Update CHANGELOG.md for Rust 1.43 and 1.44
  CHANGELOG.md
Labels: S-waiting-on-review

#5523 Add lifetime test case for `new_ret_no_self`
  tests/ui/new_ret_no_self.rs
Labels: S-waiting-on-rustup

#5517 Deploy time travel
  .github/workflows/clippy_bors.yml
  .github/workflows/deploy.yml
Labels: S-waiting-on-rustup

#5516 Add a note to the beta sections of release.md
  doc/release.md
Labels: S-waiting-on-rustup

#5505 Avoid running cargo+internal lints when not enabled
  clippy_lints/src/cargo_common_metadata.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/multiple_crate_versions.rs
  clippy_lints/src/utils/internal_lints.rs
  clippy_lints/src/utils/mod.rs
  clippy_lints/src/wildcard_dependencies.rs
Labels: S-waiting-on-rustup

#5408 Downgrade match_bool to pedantic
  clippy_lints/src/lib.rs
  clippy_lints/src/matches.rs
  src/lintlist/mod.rs
  tests/ui/implicit_return.fixed
  tests/ui/implicit_return.rs
  tests/ui/implicit_return.stderr
  tests/ui/match_bool.rs
  tests/ui/match_bool.stderr
  tests/ui/needless_return.fixed
  tests/ui/needless_return.rs
Labels: S-waiting-on-rustup

#5530 map_clone: avoid suggesting `copied()` for &mut
  clippy_lints/src/map_clone.rs
  tests/ui/map_clone.fixed
  tests/ui/map_clone.rs
  tests/ui/map_clone.stderr
Labels: S-waiting-on-review

#5525 Don't trigger while_let_on_iterator when the iterator is recreated every iteration
  clippy_lints/src/loops.rs
  tests/ui/while_let_on_iterator.fixed
  tests/ui/while_let_on_iterator.rs
  tests/ui/while_let_on_iterator.stderr
Labels: S-waiting-on-review

#5511 Fix redundant_pattern_matching lint
  clippy_lints/src/redundant_pattern_matching.rs
  tests/ui/redundant_pattern_matching.fixed
  tests/ui/redundant_pattern_matching.rs
  tests/ui/redundant_pattern_matching.stderr
Labels: S-waiting-on-author

#5533 rustup to https://github.com/rust-lang/rust/pull/70043
  clippy_lints/src/redundant_pub_crate.rs
Labels: S-waiting-on-review

#5509 Use more diagnostic items
  clippy_lints/src/entry.rs
  clippy_lints/src/format.rs
  clippy_lints/src/if_let_mutex.rs
  clippy_lints/src/inherent_to_string.rs
  clippy_lints/src/loops.rs
  clippy_lints/src/methods/inefficient_to_string.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/mutex_atomic.rs
  clippy_lints/src/needless_pass_by_value.rs
  clippy_lints/src/ptr.rs
  clippy_lints/src/redundant_clone.rs
  clippy_lints/src/strings.rs
  clippy_lints/src/swap.rs
  clippy_lints/src/types.rs
  clippy_lints/src/utils/paths.rs
Labels: S-waiting-on-author

#5534 Remove util/dev script
  util/dev
Labels: S-waiting-on-review

#5506 Implement mismatched_target_os lint
  CHANGELOG.md
  clippy_lints/src/attrs.rs
  clippy_lints/src/lib.rs
  src/lintlist/mod.rs
  tests/ui/mismatched_target_os_non_unix.fixed
  tests/ui/mismatched_target_os_non_unix.rs
  tests/ui/mismatched_target_os_non_unix.stderr
  tests/ui/mismatched_target_os_unix.fixed
  tests/ui/mismatched_target_os_unix.rs
  tests/ui/mismatched_target_os_unix.stderr
Labels: S-waiting-on-author

#5522 New lint `match_vec_item`
  CHANGELOG.md
  clippy_lints/src/consts.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/match_on_vec_items.rs
  src/lintlist/mod.rs
  tests/ui/match_on_vec_items.rs
  tests/ui/match_on_vec_items.stderr
Labels: S-waiting-on-author
