Repository rust-lang/rust-clippy, pull requests merged in 2020-10, with the labels that each got.

#5978 needless-lifetime - nested elision sites
  clippy_lints/src/lifetimes.rs
  clippy_lints/src/utils/paths.rs
  tests/ui/crashes/ice-2774.stderr
  tests/ui/crashes/needless_lifetimes_impl_trait.stderr
  tests/ui/needless_lifetimes.rs
  tests/ui/needless_lifetimes.stderr
Labels: S-waiting-on-review

#6102 Don't emit a lint for the suggestion leading to errors in `needless_range_loop`
  clippy_lints/src/loops.rs
  tests/ui/needless_range_loop2.rs
Labels: S-waiting-on-review

#6104 Allow exponent separator
  clippy_lints/src/utils/numeric_literal.rs
  tests/ui/inconsistent_digit_grouping.fixed
  tests/ui/inconsistent_digit_grouping.rs
Labels: S-waiting-on-review

#6098 Downgrade interior_mutable_const lints to warn by default
  clippy_lints/src/lib.rs
  clippy_lints/src/non_copy_const.rs
  src/lintlist/mod.rs
Labels: S-waiting-on-author

#6105 Lint for invisible Unicode characters other than ZWSP
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/unicode.rs
  src/lintlist/mod.rs
  tests/ui/unicode.rs
  tests/ui/unicode.stderr
Labels: S-waiting-on-author

#6114 Do not lint float fractions in `mistyped_literal_suffixes`
  clippy_lints/src/literal_representation.rs
  tests/ui/mistyped_literal_suffix.fixed
  tests/ui/mistyped_literal_suffix.rs
  tests/ui/mistyped_literal_suffix.stderr
Labels: S-waiting-on-review

#6078 unnecessary sort by: avoid dereferencing the suggested closure parameter
  clippy_lints/src/unnecessary_sort_by.rs
  tests/ui/unnecessary_sort_by.fixed
  tests/ui/unnecessary_sort_by.rs
  tests/ui/unnecessary_sort_by.stderr
Labels: S-waiting-on-review

#6127 Reinstate test for forbid(clippy::restriction)
  tests/ui/attrs.rs
  tests/ui/attrs.stderr
  tests/ui/blanket_clippy_restriction_lints.rs
  tests/ui/blanket_clippy_restriction_lints.stderr
Labels: S-waiting-on-review

#6124 Use more concrete explanation for methods
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-review

#6120 Replace some lazy_static usage with once_cell feature
  clippy_dev/Cargo.toml
  clippy_dev/src/lib.rs
  clippy_lints/Cargo.toml
  clippy_lints/src/lib.rs
  clippy_lints/src/macro_use.rs
  clippy_lints/src/utils/conf.rs
  tests/cargo/mod.rs
  tests/compile-test.rs
  tests/dogfood.rs
Labels: S-waiting-on-review

#6128 Downgrade rc_buffer to restriction
  clippy_lints/src/lib.rs
  clippy_lints/src/types.rs
  src/lintlist/mod.rs
Labels: S-waiting-on-review

#6132 Fix unicode regexen with bytes::Regex
  clippy_lints/src/regex.rs
  tests/ui/regex.rs
Labels: S-waiting-on-review

#6138 Add note that we follow a rustc no merge-commit policy
  doc/basics.md
Labels: S-waiting-on-review

#6117 Downgrade string_lit_as_bytes to nursery
  clippy_lints/src/lib.rs
  clippy_lints/src/strings.rs
  src/lintlist/mod.rs
Labels: S-waiting-on-author

#6133 clippy_lints: Do not warn against Box parameter in C FFI
  clippy_lints/src/escape.rs
  tests/ui/escape_analysis.rs
Labels: S-waiting-on-author

#6115 Add changelog for 1.48 beta
  CHANGELOG.md
Labels: S-waiting-on-review

#6136 Clippy dev subcommand to build and serve website
  clippy_dev/Cargo.toml
  clippy_dev/src/lib.rs
  clippy_dev/src/main.rs
  clippy_dev/src/serve.rs
  doc/adding_lints.md
Labels: S-waiting-on-review

#6146 clippy_lint: Fix doc on 'option_if_let_else'
  clippy_lints/src/option_if_let_else.rs
Labels: S-waiting-on-review

#6131 Rename tables to typecheck_result()
  doc/common_tools_writing_lints.md
Labels: S-waiting-on-review

#6130 New lint: Recommend using `ptr::eq` when possible
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/ptr_eq.rs
  src/lintlist/mod.rs
  tests/ui/ptr_eq.fixed
  tests/ui/ptr_eq.rs
  tests/ui/ptr_eq.stderr
Labels: S-waiting-on-review

#6152 Fixes ICE 6139
  clippy_lints/src/types.rs
  tests/ui/crashes/ice-6139.rs
Labels: S-waiting-on-review

#5727 Expands `manual_memcpy` to lint ones with loop counters
  clippy_lints/src/loops.rs
  clippy_lints/src/utils/mod.rs
  clippy_lints/src/utils/sugg.rs
  tests/ui/manual_memcpy.stderr
  tests/ui/manual_memcpy/with_loop_counters.rs
  tests/ui/manual_memcpy/with_loop_counters.stderr
  tests/ui/manual_memcpy/without_loop_counters.rs
  tests/ui/manual_memcpy/without_loop_counters.stderr
Labels: S-waiting-on-author

#6107 Ref style link false positive
  clippy_lints/src/doc.rs
Labels: S-waiting-on-review

#6154 Fix two ICEs caused by ty.is_{sized,freeze}
  clippy_lints/src/mut_key.rs
  clippy_lints/src/types.rs
  tests/ui/crashes/ice-6153.rs
Labels: S-waiting-on-review

#6157 New lint: result-unit-err
  CHANGELOG.md
  clippy_lints/src/functions.rs
  clippy_lints/src/lib.rs
  src/lintlist/mod.rs
  tests/ui/doc_errors.rs
  tests/ui/doc_errors.stderr
  tests/ui/double_must_use.rs
  tests/ui/double_must_use.stderr
  tests/ui/result_unit_error.rs
  tests/ui/result_unit_error.stderr
Labels: S-waiting-on-author

#6158 Remove the generated files by `update-references.sh` if they are empty
  doc/adding_lints.md
  tests/ui-cargo/update-references.sh
  tests/ui-toml/update-references.sh
  tests/ui/update-references.sh
Labels: S-waiting-on-review

#6163 Remove lazy_static completely and use once_cell feature instead
  Cargo.toml
  clippy_dev/src/update_lints.rs
  src/driver.rs
  src/lintlist/mod.rs
Labels: S-waiting-on-review

#6169 Fix FP in `same_functions_in_if_condition` lint about condition as macro
  clippy_lints/src/copies.rs
  tests/ui/same_functions_in_if_condition.rs
Labels: S-waiting-on-review

#6174 Add a known problem for transmute_ptr_to_ref lint
  clippy_lints/src/transmute.rs
Labels: S-waiting-on-review

#6173 README: sort en/disabling section, fix typos, add note
  README.md
Labels: S-waiting-on-review

#6123 add lint manual_unwrap_or
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_unwrap_or.rs
  clippy_lints/src/option_if_let_else.rs
  clippy_lints/src/utils/eager_or_lazy.rs
  clippy_lints/src/utils/usage.rs
  src/lintlist/mod.rs
  tests/ui/manual_unwrap_or.fixed
  tests/ui/manual_unwrap_or.rs
  tests/ui/manual_unwrap_or.stderr
  tests/ui/shadow.rs
  tests/ui/shadow.stderr
Labels: S-waiting-on-author

#6195 Rustup
  clippy_lints/src/utils/paths.rs
Labels: S-waiting-on-review

#6166 Suggest a compatible shell for setup-toolchain.sh
  doc/basics.md
Labels: S-waiting-on-review

#6167 Identical arguments on assert macro family
  clippy_lints/src/eq_op.rs
  clippy_lints/src/mutable_debug_assertion.rs
  clippy_lints/src/utils/higher.rs
  tests/ui/auxiliary/proc_macro_derive.rs
  tests/ui/double_parens.rs
  tests/ui/eq_op_macros.rs
  tests/ui/eq_op_macros.stderr
  tests/ui/used_underscore_binding.rs
Labels: S-waiting-on-author

#6193 Add more infomation about LintStore registration
  doc/adding_lints.md
Labels: S-waiting-on-review

#6203 Fix links to labeled issues
  CONTRIBUTING.md
Labels: S-waiting-on-review

#6135 Add large_types_passed_by_value lint
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/pass_by_ref_or_value.rs
  clippy_lints/src/trivially_copy_pass_by_ref.rs
  clippy_lints/src/utils/conf.rs
  src/lintlist/mod.rs
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
  tests/ui/large_types_passed_by_value.rs
  tests/ui/large_types_passed_by_value.stderr
Labels: S-waiting-on-author

#6190 manual_unwrap_or / support Result::unwrap_or
  clippy_lints/src/manual_unwrap_or.rs
  src/lintlist/mod.rs
  tests/ui/manual_unwrap_or.fixed
  tests/ui/manual_unwrap_or.rs
  tests/ui/manual_unwrap_or.stderr
Labels: S-waiting-on-author

#6187 Lint unnecessary int-to-int and float-to-float casts
  clippy_lints/src/types.rs
  tests/ui/cast_size_32bit.stderr
  tests/ui/eq_op.rs
  tests/ui/eq_op.stderr
  tests/ui/unnecessary_cast_fixable.fixed
  tests/ui/unnecessary_cast_fixable.rs
  tests/ui/unnecessary_cast_fixable.stderr
Labels: S-waiting-on-author

#6029 Add lint for holding RefCell Ref across an await
  CHANGELOG.md
  clippy_lints/src/await_holding_invalid.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/paths.rs
  src/lintlist/mod.rs
  tests/ui/await_holding_refcell_ref.rs
  tests/ui/await_holding_refcell_ref.stderr
Labels: S-waiting-on-author

#6109 Add linter for a single element for loop
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/loops.rs
  src/lintlist/mod.rs
  tests/ui/if_same_then_else2.rs
  tests/ui/if_same_then_else2.stderr
  tests/ui/single_element_loop.fixed
  tests/ui/single_element_loop.rs
  tests/ui/single_element_loop.stderr
Labels: S-waiting-on-author

#6181 Add new lint for undropped ManuallyDrop values
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/undropped_manually_drops.rs
  src/lintlist/mod.rs
  tests/ui/undropped_manually_drops.rs
  tests/ui/undropped_manually_drops.stderr
Labels: S-waiting-on-author

#6162 Update empty_loop documentation/message.
  clippy_lints/src/loops.rs
  tests/ui/crashes/ice-360.stderr
  tests/ui/empty_loop.stderr
  tests/ui/empty_loop_no_std.rs
Labels: S-waiting-on-author

#6103 Add lint for `&mut Mutex::lock`
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/mut_mutex_lock.rs
  src/lintlist/mod.rs
  tests/ui/mut_mutex_lock.fixed
  tests/ui/mut_mutex_lock.rs
  tests/ui/mut_mutex_lock.stderr
Labels: S-waiting-on-author

#6177 New lint: manual-range-contains
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/ranges.rs
  src/lintlist/mod.rs
  tests/ui/range_contains.fixed
  tests/ui/range_contains.rs
  tests/ui/range_contains.stderr
Labels: S-waiting-on-review

#6198 needless-lifetime / multiple where clause predicates regression
  clippy_lints/src/lifetimes.rs
  tests/ui/needless_lifetimes.rs
Labels: S-waiting-on-review

#6211 No lint with `cfg!` and fix sugg for macro in `needless_bool` lint
  clippy_lints/src/needless_bool.rs
  tests/ui/bool_comparison.fixed
  tests/ui/bool_comparison.rs
  tests/ui/bool_comparison.stderr
Labels: S-waiting-on-review

#6222 Remove redundant `expect_local()` call
  clippy_lints/src/functions.rs
  clippy_lints/src/loops.rs
  clippy_lints/src/utils/mod.rs
  clippy_lints/src/utils/usage.rs
Labels: S-waiting-on-review

#6183 Hex bin digit grouping
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/literal_representation.rs
  clippy_lints/src/utils/numeric_literal.rs
  src/lintlist/mod.rs
  tests/ui/large_digit_groups.fixed
  tests/ui/large_digit_groups.stderr
  tests/ui/literals.rs
  tests/ui/literals.stderr
  tests/ui/unreadable_literal.fixed
  tests/ui/unreadable_literal.stderr
Labels: S-waiting-on-rustup

#6194 Remove an extra blank line in doc examples
  clippy_lints/src/blocks_in_if_conditions.rs
  clippy_lints/src/escape.rs
  clippy_lints/src/matches.rs
  clippy_lints/src/misc_early.rs
Labels: S-waiting-on-rustup

#6202 Fix an invalid suggestion in `needless_collect` test
  clippy_lints/src/loops.rs
  tests/ui/needless_collect_indirect.rs
  tests/ui/needless_collect_indirect.stderr
Labels: S-waiting-on-rustup

#6244 New internal lint: Invalid paths
  clippy_lints/src/derive.rs
  clippy_lints/src/float_equality_without_abs.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/internal_lints.rs
  clippy_lints/src/utils/mod.rs
  clippy_lints/src/utils/paths.rs
  tests/ui/invalid_paths.rs
  tests/ui/invalid_paths.stderr
Labels: S-waiting-on-review

#6257 Rustup
  .github/driver.sh
  clippy_lints/src/deprecated_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/utils/paths.rs
  src/lintlist/mod.rs
  tests/ui/cstring.rs
  tests/ui/cstring.stderr
  tests/ui/deprecated.rs
  tests/ui/deprecated.stderr
Labels: S-waiting-on-review

#6263 use diff -u in driver.sh test
  .github/driver.sh
Labels: S-waiting-on-review

#6264 cargo dev ra-setup: don't inject deps multiple times if we have already done so
  clippy_dev/src/ra_setup.rs
Labels: S-waiting-on-review

#6212 No lint in macro for `toplevel_ref_arg`
  clippy_lints/src/misc.rs
  tests/ui/auxiliary/macro_rules.rs
  tests/ui/toplevel_ref_arg.fixed
  tests/ui/toplevel_ref_arg.rs
  tests/ui/toplevel_ref_arg.stderr
  tests/ui/toplevel_ref_arg_non_rustfix.rs
  tests/ui/toplevel_ref_arg_non_rustfix.stderr
Labels: S-waiting-on-author

#6176 Lint items after statements in local macro expansions
  clippy_lints/src/items_after_statements.rs
  tests/ui/item_after_statement.rs
  tests/ui/item_after_statement.stderr
Labels: S-waiting-on-review

#6226 Add lint for comparing to empty slices instead of using .is_empty()
  CHANGELOG.md
  clippy_lints/src/len_zero.rs
  clippy_lints/src/lib.rs
  src/lintlist/mod.rs
  tests/ui/comparison_to_empty.fixed
  tests/ui/comparison_to_empty.rs
  tests/ui/comparison_to_empty.stderr
Labels: S-waiting-on-review

#6227 Add lint for replacing `.map().collect()` with `.try_for_each()`
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/methods/mod.rs
  src/lintlist/mod.rs
  tests/ui/map_collect_result_unit.fixed
  tests/ui/map_collect_result_unit.rs
  tests/ui/map_collect_result_unit.stderr
Labels: S-waiting-on-review

#6248 Replace `E-easy` with `good first issue` in `CONTRIBUTING.md`
  CONTRIBUTING.md
Labels: S-waiting-on-review

#6200 fix the error-causing suggestion of 'borrowed_box'
  clippy_lints/src/types.rs
  tests/ui/borrow_box.rs
  tests/ui/borrow_box.stderr
Labels: S-waiting-on-author

#6229 Update the existing arithmetic lint
  clippy_lints/src/arithmetic.rs
  tests/ui/integer_arithmetic.rs
  tests/ui/integer_arithmetic.stderr
Labels: S-waiting-on-review

#6197 Improve suggestions for several lints
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/option_map_unwrap_or.rs
  tests/ui/filter_map_next.rs
  tests/ui/filter_map_next.stderr
  tests/ui/filter_map_next_fixable.fixed
  tests/ui/filter_map_next_fixable.rs
  tests/ui/filter_map_next_fixable.stderr
  tests/ui/filter_methods.stderr
  tests/ui/find_map.stderr
  tests/ui/iter_skip_next.stderr
  tests/ui/map_unwrap_or.rs
  tests/ui/map_unwrap_or.stderr
  tests/ui/map_unwrap_or_fixable.fixed
  tests/ui/map_unwrap_or_fixable.rs
  tests/ui/map_unwrap_or_fixable.stderr
  tests/ui/methods.rs
  tests/ui/methods.stderr
  tests/ui/methods_fixable.fixed
  tests/ui/methods_fixable.rs
  tests/ui/methods_fixable.stderr
  tests/ui/option_map_or_none.stderr
  tests/ui/skip_while_next.stderr
Labels: S-waiting-on-author

#6277 Rustup
  .github/driver.sh
  clippy_lints/src/lib.rs
  clippy_lints/src/redundant_clone.rs
Labels: S-waiting-on-review

#6276 Fix typo in adding_lints.md
  doc/adding_lints.md
Labels: S-waiting-on-review
