Repository rust-lang/rust-clippy, pull requests merged in 2020-06, with the labels that each got.

#5623 New lint: Use Reverse with sort_by_key
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/unnecessary_sort_by.rs
  src/lintlist/mod.rs
  tests/ui/unnecessary_sort_by.fixed
  tests/ui/unnecessary_sort_by.rs
  tests/ui/unnecessary_sort_by.stderr
Labels: S-waiting-on-review

#5673 Add regression test for endless loop / update `pulldown_cmark`
  clippy_lints/Cargo.toml
  tests/ui/crashes/regressions.rs
Labels: S-waiting-on-review

#5597 New lint: iter_next_slice
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/loops.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/needless_continue.rs
  src/lintlist/mod.rs
  tests/ui/into_iter_on_ref.fixed
  tests/ui/into_iter_on_ref.rs
  tests/ui/into_iter_on_ref.stderr
  tests/ui/iter_next_slice.fixed
  tests/ui/iter_next_slice.rs
  tests/ui/iter_next_slice.stderr
  tests/ui/needless_collect.fixed
  tests/ui/needless_collect.stderr
Labels: S-waiting-on-author

#5664 Give corrected code
  clippy_lints/src/assign_ops.rs
  clippy_lints/src/double_parens.rs
  clippy_lints/src/drop_bounds.rs
  clippy_lints/src/duration_subsec.rs
  clippy_lints/src/enum_variants.rs
  clippy_lints/src/eq_op.rs
  clippy_lints/src/escape.rs
  clippy_lints/src/eta_reduction.rs
  clippy_lints/src/eval_order_dependence.rs
  clippy_lints/src/fallible_impl_from.rs
  clippy_lints/src/floating_point_arithmetic.rs
  clippy_lints/src/format.rs
  clippy_lints/src/functions.rs
  clippy_lints/src/implicit_saturating_sub.rs
  clippy_lints/src/int_plus_one.rs
  clippy_lints/src/integer_division.rs
  clippy_lints/src/items_after_statements.rs
  clippy_lints/src/literal_representation.rs
  clippy_lints/src/matches.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/misc.rs
  clippy_lints/src/misc_early.rs
  clippy_lints/src/mut_reference.rs
  clippy_lints/src/mutex_atomic.rs
  clippy_lints/src/needless_bool.rs
  clippy_lints/src/needless_borrow.rs
  clippy_lints/src/needless_pass_by_value.rs
  clippy_lints/src/needless_update.rs
  clippy_lints/src/ptr.rs
  clippy_lints/src/question_mark.rs
  clippy_lints/src/reference.rs
  clippy_lints/src/regex.rs
  clippy_lints/src/shadow.rs
  clippy_lints/src/single_component_path_imports.rs
  clippy_lints/src/slow_vector_initialization.rs
  clippy_lints/src/strings.rs
  clippy_lints/src/vec.rs
  clippy_lints/src/verbose_file_reads.rs
  clippy_lints/src/wildcard_imports.rs
  clippy_lints/src/write.rs
  clippy_lints/src/zero_div_zero.rs
  src/lintlist/mod.rs
Labels: S-waiting-on-author

#5672 Add regression test for `string_lit_as_bytes` issue
  tests/ui/string_lit_as_bytes.fixed
  tests/ui/string_lit_as_bytes.rs
  tests/ui/string_lit_as_bytes.stderr
Labels: S-waiting-on-review

#5678 Make use of slice pattern
  clippy_lints/src/utils/mod.rs
Labels: S-waiting-on-review

#5677 Fix false negative of `checked_conversion` lint
  clippy_lints/src/checked_conversions.rs
  tests/ui/checked_conversions.fixed
  tests/ui/checked_conversions.rs
  tests/ui/checked_conversions.stderr
  tests/ui/checked_conversions.stdout
Labels: S-waiting-on-review

#5681 match_wildcard_for_single_variants: remove empty line at start of lint example.
  clippy_lints/src/matches.rs
Labels: S-waiting-on-review

#5686 Reorder sections of release documentation
  doc/release.md
Labels: S-waiting-on-review

#5671 Update changelog for stable:1.44 beta:1.45
  CHANGELOG.md
  doc/changelog_update.md
Labels: S-waiting-on-author

#5687 Replace all remaining occurrences of submodule with subtree
  doc/changelog_update.md
  doc/release.md
Labels: S-waiting-on-review

#5688 Fix cargo tests when running inside the rustlang/rust repo
  clippy_dev/src/new_lint.rs
  clippy_lints/src/cargo_common_metadata.rs
  clippy_lints/src/multiple_crate_versions.rs
  clippy_lints/src/utils/mod.rs
  clippy_lints/src/wildcard_dependencies.rs
  tests/compile-test.rs
  tests/ui-cargo/cargo_common_metadata/fail/Cargo.toml
  tests/ui-cargo/cargo_common_metadata/pass/Cargo.toml
  tests/ui-cargo/multiple_crate_versions/5041_allow_dev_build/Cargo.toml
  tests/ui-cargo/multiple_crate_versions/fail/Cargo.toml
  tests/ui-cargo/multiple_crate_versions/pass/Cargo.toml
  tests/ui-cargo/wildcard_dependencies/fail/Cargo.toml
  tests/ui-cargo/wildcard_dependencies/pass/Cargo.toml
Labels: S-waiting-on-review

#5528 Cleanup: Use rustc's `same_type` for our `same_tys`
  clippy_lints/src/copies.rs
  clippy_lints/src/loops.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/new_without_default.rs
  clippy_lints/src/types.rs
  clippy_lints/src/useless_conversion.rs
  clippy_lints/src/utils/mod.rs
Labels: S-waiting-on-author

#5674 Add doc for checking if type defines specific method
  doc/common_tools_writing_lints.md
Labels: S-waiting-on-review

#5691 Rustup
  .github/workflows/clippy_bors.yml
  clippy_lints/src/future_not_send.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/mod.rs
  clippy_lints/src/write.rs
  tests/ui/or_fun_call.fixed
  tests/ui/or_fun_call.stderr
Labels: S-waiting-on-review

#5378 New lint: `unnested_or_patterns`
  CHANGELOG.md
  clippy_lints/src/await_holding_lock.rs
  clippy_lints/src/formatting.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/methods/manual_saturating_arithmetic.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/misc.rs
  clippy_lints/src/no_effect.rs
  clippy_lints/src/suspicious_trait_impl.rs
  clippy_lints/src/transmute.rs
  clippy_lints/src/unnested_or_patterns.rs
  clippy_lints/src/unwrap.rs
  clippy_lints/src/utils/ast_utils.rs
  clippy_lints/src/utils/hir_utils.rs
  clippy_lints/src/utils/mod.rs
  src/lintlist/mod.rs
  tests/ui/neg_cmp_op_on_partial_ord.rs
  tests/ui/neg_cmp_op_on_partial_ord.stderr
  tests/ui/unnested_or_patterns.fixed
  tests/ui/unnested_or_patterns.rs
  tests/ui/unnested_or_patterns.stderr
  tests/ui/unnested_or_patterns2.fixed
  tests/ui/unnested_or_patterns2.rs
  tests/ui/unnested_or_patterns2.stderr
  tests/ui/wildcard_enum_match_arm.fixed
  tests/ui/wildcard_enum_match_arm.rs
  tests/ui/wildcard_enum_match_arm.stderr
Labels: L-lint, S-waiting-on-review

#5680 let_and_return: avoid "does not live long enough" errors
  clippy_lints/src/let_and_return.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/returns.rs
  clippy_lints/src/utils/mod.rs
  src/lintlist/mod.rs
  tests/ui/let_and_return.rs
  tests/ui/let_and_return.stderr
  tests/ui/let_return.rs
Labels: S-waiting-on-review

#5692 reversed_empty_ranges: avoid linting N..N except in for loop arguments
  clippy_lints/src/ranges.rs
  tests/ui/reversed_empty_ranges_fixable.fixed
  tests/ui/reversed_empty_ranges_fixable.rs
  tests/ui/reversed_empty_ranges_fixable.stderr
  tests/ui/reversed_empty_ranges_unfixable.rs
  tests/ui/reversed_empty_ranges_unfixable.stderr
Labels: S-waiting-on-review

#5702 if_same_then_else: don't assume multiplication is always commutative
  clippy_lints/src/utils/hir_utils.rs
  tests/ui/if_same_then_else.rs
Labels: S-waiting-on-review

#5695 New lint: suggest `ptr::read` instead of `mem::replace(..., uninitialized())`
  clippy_lints/src/mem_replace.rs
  tests/ui/repl_uninit.rs
  tests/ui/repl_uninit.stderr
Labels: S-waiting-on-review

#5724 redundant_pattern_matching: avoid non-`const fn` calls in const contexts
  clippy_lints/src/redundant_pattern_matching.rs
  tests/ui/redundant_pattern_matching.fixed
  tests/ui/redundant_pattern_matching.rs
  tests/ui/redundant_pattern_matching.stderr
  tests/ui/redundant_pattern_matching_const_result.fixed
  tests/ui/redundant_pattern_matching_const_result.rs
  tests/ui/redundant_pattern_matching_const_result.stderr
Labels: S-waiting-on-rustup

#5716 Fix typo in wildcard_imports
  clippy_lints/src/wildcard_imports.rs
Labels: S-waiting-on-rustup

#5713 Use lints in Clippy that are enabled in rustc bootstrap
  clippy_lints/src/lib.rs
  clippy_lints/src/loops.rs
  clippy_lints/src/suspicious_trait_impl.rs
  clippy_lints/src/trivially_copy_pass_by_ref.rs
  clippy_lints/src/utils/sugg.rs
  src/driver.rs
  src/main.rs
Labels: S-waiting-on-rustup

#5710 typo
  clippy_lints/src/new_without_default.rs
Labels: S-waiting-on-rustup

#5712 Remove `bar` from blacklisted names
  clippy_lints/src/utils/conf.rs
  tests/ui/blacklisted_name.rs
  tests/ui/blacklisted_name.stderr
Labels: S-waiting-on-rustup

#5709 Fix ICE in consts::binop
  clippy_lints/src/consts.rs
  tests/ui/crashes/ice-5389.rs
Labels: S-waiting-on-rustup

#5705 Downgrade unnested_or_patterns to pedantic
  clippy_lints/src/lib.rs
  clippy_lints/src/unnested_or_patterns.rs
  src/lintlist/mod.rs
Labels: S-waiting-on-rustup

#5178 clippy-driver: pass all args to rustc if --rustc is present
  .github/driver.sh
  src/driver.rs
Labels: S-waiting-on-rustup

#5735 Add more specific GitHub issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/blank_issue.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/ice.md
  .github/ISSUE_TEMPLATE/new_lint.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: S-waiting-on-author

#5738 Improve end of expression check in for loop lints
  clippy_lints/src/loops.rs
Labels: S-waiting-on-review

#5740 Remove unused allowed unused attributes
  clippy_lints/src/lib.rs
  src/driver.rs
Labels: S-waiting-on-review

#5694 #5626: lint iterator.map(|x| x)
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/map_identity.rs
  src/lintlist/mod.rs
  tests/ui/map_flatten.fixed
  tests/ui/map_flatten.rs
  tests/ui/map_flatten.stderr
  tests/ui/map_identity.fixed
  tests/ui/map_identity.rs
  tests/ui/map_identity.stderr
Labels: S-waiting-on-author

#5745 clone_on_copy - add machine applicability
  clippy_lints/src/methods/mod.rs
  tests/ui/clone_on_copy.fixed
  tests/ui/clone_on_copy.rs
  tests/ui/clone_on_copy.stderr
  tests/ui/unnecessary_clone.rs
  tests/ui/unnecessary_clone.stderr
Labels: S-waiting-on-review

#5701 cmp_owned: handle when PartialEq is not implemented symmetrically
  clippy_lints/src/misc.rs
  tests/ui/cmp_owned/asymmetric_partial_eq.fixed
  tests/ui/cmp_owned/asymmetric_partial_eq.rs
  tests/ui/cmp_owned/asymmetric_partial_eq.stderr
Labels: S-waiting-on-review

#5748 Change a noun to a verb to make the sentence complete
  clippy_lints/src/await_holding_lock.rs
Labels: S-waiting-on-review

#5750 Lint enabling the whole restriction group
  CHANGELOG.md
  clippy_lints/src/attrs.rs
  clippy_lints/src/lib.rs
  src/lintlist/mod.rs
  tests/ui/attrs.rs
  tests/ui/attrs.stderr
Labels: S-waiting-on-rustup

#5758 Require `or_patterns` to suggest nesting them
  clippy_lints/src/unnested_or_patterns.rs
  tests/ui/unnested_or_patterns3.rs
Labels: S-waiting-on-review
