Repository rust-lang/rust-clippy, pull requests merged in 2021-12, with the labels that each got.

#7993 `no_std_swap`: Fix typo in TODO
  tests/ui/crate_level_checks/no_std_swap.rs
  tests/ui/crate_level_checks/no_std_swap.stderr
Labels: S-waiting-on-review

#8049 Add test for pattern_type_mismatch.
  tests/ui/pattern_type_mismatch/mutability.rs
Labels: S-waiting-on-review

#7463 Fix `any()` not taking reference in `search_is_some` lint
  clippy_lints/src/methods/search_is_some.rs
  clippy_utils/src/sugg.rs
  tests/ui/search_is_some.rs
  tests/ui/search_is_some.stderr
  tests/ui/search_is_some_fixable.fixed
  tests/ui/search_is_some_fixable.rs
  tests/ui/search_is_some_fixable.stderr
  tests/ui/search_is_some_fixable_none.fixed
  tests/ui/search_is_some_fixable_none.rs
  tests/ui/search_is_some_fixable_none.stderr
  tests/ui/search_is_some_fixable_some.fixed
  tests/ui/search_is_some_fixable_some.rs
  tests/ui/search_is_some_fixable_some.stderr
Labels: S-waiting-on-author

#8067 Escape backslash in single_char_pattern.rs
  clippy_lints/src/methods/utils.rs
  tests/ui/single_char_pattern.fixed
  tests/ui/single_char_pattern.rs
  tests/ui/single_char_pattern.stderr
Labels: S-waiting-on-review

#8061 Fixed same_name_method description
  clippy_lints/src/same_name_method.rs
  tests/ui/same_name_method.stderr
Labels: S-waiting-on-review

#8040 Updated known problems section for pre-expansion lints about level attributes
  clippy_lints/src/dbg_macro.rs
  clippy_lints/src/write.rs
  util/gh-pages/index.html
Labels: S-waiting-on-review

#8054 Upgrade map_flatten to complexity
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_complexity.rs
  clippy_lints/src/lib.register_pedantic.rs
  clippy_lints/src/methods/mod.rs
  tests/ui/option_env_unwrap.rs
  tests/ui/option_env_unwrap.stderr
  tests/ui/option_filter_map.fixed
  tests/ui/option_filter_map.rs
  tests/ui/option_filter_map.stderr
Labels: S-waiting-on-review

#8074 Consider NonNull as a pointer type
  clippy_lints/src/non_send_fields_in_send_ty.rs
  clippy_utils/src/paths.rs
  tests/ui/non_send_fields_in_send_ty.rs
  tests/ui/non_send_fields_in_send_ty.stderr
Labels: S-waiting-on-review

#8072 Enable rustbot shortcuts for rust-clippy
  triagebot.toml
Labels: S-waiting-on-review

#8077 Fix some false negatives for [`single_char_pattern`]
  clippy_lints/src/map_unit_fn.rs
  clippy_lints/src/methods/single_char_pattern.rs
  clippy_lints/src/nonstandard_macro_braces.rs
  clippy_lints/src/self_named_constructors.rs
  clippy_lints/src/unicode.rs
  clippy_lints/src/write.rs
  tests/ui/single_char_pattern.fixed
  tests/ui/single_char_pattern.rs
  tests/ui/single_char_pattern.stderr
Labels: S-waiting-on-review

#8042 Peel blocks and statements utils
  clippy_lints/src/assertions_on_constants.rs
  clippy_lints/src/bytecount.rs
  clippy_lints/src/collapsible_match.rs
  clippy_lints/src/derivable_impls.rs
  clippy_lints/src/floating_point_arithmetic.rs
  clippy_lints/src/if_then_some_else_none.rs
  clippy_lints/src/implicit_saturating_sub.rs
  clippy_lints/src/loops/manual_flatten.rs
  clippy_lints/src/loops/never_loop.rs
  clippy_lints/src/manual_map.rs
  clippy_lints/src/map_clone.rs
  clippy_lints/src/matches.rs
  clippy_lints/src/methods/bind_instead_of_map.rs
  clippy_lints/src/methods/filter_map.rs
  clippy_lints/src/methods/option_as_ref_deref.rs
  clippy_lints/src/methods/unnecessary_fold.rs
  clippy_lints/src/needless_bool.rs
  clippy_lints/src/no_effect.rs
  clippy_lints/src/option_if_let_else.rs
  clippy_lints/src/question_mark.rs
  clippy_lints/src/strings.rs
  clippy_lints/src/utils/internal_lints.rs
  clippy_lints/src/utils/internal_lints/metadata_collector.rs
  clippy_utils/src/lib.rs
Labels: S-waiting-on-author

#8080 Fix FP on `question_mark` if returned object is not local
  clippy_lints/src/question_mark.rs
  tests/ui/question_mark.fixed
  tests/ui/question_mark.rs
Labels: S-waiting-on-review

#8085 `needless_lifetimes` Known problems typo
  clippy_lints/src/lifetimes.rs
Labels: S-waiting-on-review

#8075 Clarify the purpose of the non_send lint
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_nursery.rs
  clippy_lints/src/lib.register_suspicious.rs
  clippy_lints/src/non_send_fields_in_send_ty.rs
  tests/ui-toml/strict_non_send_fields_in_send_ty/test.stderr
  tests/ui/non_send_fields_in_send_ty.stderr
Labels: S-waiting-on-author

#8086 Fix bad suggestion on `option_if_let_else` when there is complex subpat
  clippy_lints/src/option_if_let_else.rs
  tests/ui/option_if_let_else.fixed
  tests/ui/option_if_let_else.rs
  tests/ui/option_if_let_else.stderr
Labels: S-waiting-on-review

#8030 Ignore associated types in traits when considering type complexity
  clippy_lints/src/types/mod.rs
  tests/ui/type_complexity.rs
  tests/ui/type_complexity.stderr
Labels: S-waiting-on-review

#8071 Add new lint to warn when #[must_use] attribute should be used on a method
  CHANGELOG.md
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_suspicious.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/return_self_not_must_use.rs
  clippy_utils/src/hir_utils.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/sugg.rs
  tests/ui/auxiliary/option_helpers.rs
  tests/ui/deref_addrof.fixed
  tests/ui/deref_addrof.rs
  tests/ui/deref_addrof.stderr
  tests/ui/return_self_not_must_use.rs
  tests/ui/return_self_not_must_use.stderr
  tests/ui/should_impl_trait/corner_cases.rs
  tests/ui/should_impl_trait/method_list_1.rs
  tests/ui/should_impl_trait/method_list_1.stderr
  tests/ui/should_impl_trait/method_list_2.rs
  tests/ui/should_impl_trait/method_list_2.stderr
Labels: S-waiting-on-review

#8096 Remove lintcheck log and add `--filter` option to lintcheck
  .gitignore
  lintcheck-logs/lintcheck_crates_logs.txt
  lintcheck/src/main.rs
Labels: S-waiting-on-review

#8110 Update lintcheck output to use tables and add markdown support
  lintcheck/src/main.rs
Labels: S-waiting-on-review

#8100 Fix `blocks_in_if_conditions` false positive
  clippy_lints/src/blocks_in_if_conditions.rs
  tests/ui/blocks_in_if_conditions_closure.rs
Labels: S-waiting-on-review

#7978 Add `unnecessary_to_owned` lint
  CHANGELOG.md
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_perf.rs
  clippy_lints/src/methods/implicit_clone.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/unnecessary_iter_cloned.rs
  clippy_lints/src/methods/unnecessary_to_owned.rs
  clippy_lints/src/unit_return_expecting_ord.rs
  clippy_utils/src/ty.rs
  clippy_utils/src/usage.rs
  tests/ui/unnecessary_iter_cloned.fixed
  tests/ui/unnecessary_iter_cloned.rs
  tests/ui/unnecessary_iter_cloned.stderr
  tests/ui/unnecessary_to_owned.fixed
  tests/ui/unnecessary_to_owned.rs
  tests/ui/unnecessary_to_owned.stderr
Labels: S-waiting-on-review

#8136 Update changelog
  CHANGELOG.md
Labels: S-waiting-on-review

#8143 Ensure that RETURN_SELF_NOT_MUST_USE is not emitted if the method already has `#[must_use]`
  clippy_lints/src/return_self_not_must_use.rs
  tests/ui/return_self_not_must_use.rs
Labels: S-waiting-on-review

#8146 Don't emit RETURN_SELF_NOT_MUST_USE lint if `Self` already is marked as `#[must_use]`
  clippy_lints/src/return_self_not_must_use.rs
  tests/ui/return_self_not_must_use.rs
Labels: S-waiting-on-review

#8138 Fix `SAFETY` comment tag casing in undocumented_unsafe_blocks
  clippy_lints/src/undocumented_unsafe_blocks.rs
  tests/ui/crashes/ice-7868.stderr
  tests/ui/undocumented_unsafe_blocks.rs
  tests/ui/undocumented_unsafe_blocks.stderr
Labels: S-waiting-on-review

#8150 Test clippy_utils in CI
  .github/workflows/clippy.yml
  .github/workflows/clippy_bors.yml
  clippy_utils/src/lib.rs
  clippy_utils/src/str_utils.rs
Labels: S-waiting-on-review

#8163 Improve `unwrap_or_else_default` when handling `unwrap_or_else(XXX::new)`
  clippy_lints/src/methods/unwrap_or_else_default.rs
  clippy_utils/src/lib.rs
  tests/ui/unwrap_or_else_default.fixed
  tests/ui/unwrap_or_else_default.rs
  tests/ui/unwrap_or_else_default.stderr
Labels: S-waiting-on-review

#8165 fix [`shadow_reuse`] false negative for if let bindings
  clippy_lints/src/shadow.rs
  tests/ui/shadow.rs
  tests/ui/shadow.stderr
Labels: S-waiting-on-review

#8167 fix an ICE on unwrapping a None
  clippy_lints/src/casts/unnecessary_cast.rs
Labels: S-waiting-on-review

#8133 Fix 8128
  clippy_lints/src/methods/iter_skip_next.rs
  tests/ui/iter_skip_next.fixed
  tests/ui/iter_skip_next.rs
  tests/ui/iter_skip_next.stderr
  tests/ui/iter_skip_next_unfixable.rs
  tests/ui/iter_skip_next_unfixable.stderr
Labels: S-waiting-on-review

#8170 new lint: `init-numbered-fields`
  CHANGELOG.md
  clippy_lints/src/init_numbered_fields.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_style.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/macro_use.rs
  clippy_utils/src/lib.rs
  tests/ui/numbered_fields.fixed
  tests/ui/numbered_fields.rs
  tests/ui/numbered_fields.stderr
Labels: S-waiting-on-review

#8181 Fixed some typos in README and CONTRIBUTING
  CONTRIBUTING.md
  README.md
Labels: S-waiting-on-review

#8182 cache test item names
  clippy_utils/src/lib.rs
Labels: S-waiting-on-review

#8127 Fix `enum_variants` FP on prefixes that are not camel-case
  clippy_lints/src/enum_variants.rs
  clippy_utils/src/str_utils.rs
  tests/ui/enum_variants.rs
  tests/ui/enum_variants.stderr
Labels: S-waiting-on-review

#8187 Fixed issues with to_radians and to_degrees lints
  clippy_lints/src/floating_point_arithmetic.rs
  tests/ui/floating_point_rad.fixed
  tests/ui/floating_point_rad.rs
  tests/ui/floating_point_rad.stderr
Labels: S-waiting-on-review

#8183 Limit the ``[`identity_op`]`` lint to integral operands.
  clippy_lints/src/identity_op.rs
  clippy_utils/src/consts.rs
  tests/ui/identity_op.rs
  tests/ui/identity_op.stderr
Labels: S-waiting-on-review

#8117 update: ```Sugg::not()``` replacing the comparison operator. #7320
  clippy_lints/src/floating_point_arithmetic.rs
  clippy_lints/src/loops/manual_memcpy.rs
  clippy_lints/src/needless_bool.rs
  clippy_lints/src/ranges.rs
  clippy_utils/src/sugg.rs
  tests/ui/manual_memcpy/with_loop_counters.stderr
  tests/ui/needless_bool/fixable.fixed
  tests/ui/needless_bool/fixable.rs
  tests/ui/needless_bool/fixable.stderr
  tests/ui/short_circuit_statement.fixed
  tests/ui/short_circuit_statement.stderr
Labels: S-waiting-on-author

#8179 Extend unused_io_amount to cover async io.
  Cargo.toml
  clippy_lints/src/unused_io_amount.rs
  clippy_utils/src/paths.rs
  tests/compile-test.rs
  tests/ui/unused_io_amount.rs
  tests/ui/unused_io_amount.stderr
Labels: S-needs-discussion, S-waiting-on-review

#8193 fix [`redundant_closure`] fp with `Rc<F>`/`Arc<F>`
  clippy_lints/src/eta_reduction.rs
  tests/ui/eta.fixed
  tests/ui/eta.rs
Labels: S-waiting-on-review
