Repository rust-lang/rust-clippy, pull requests merged in 2021-03, with the labels that each got.

#6813 lintcheck, do some refactoring and add more sources
  clippy_dev/lintcheck_crates.toml
  clippy_dev/src/lintcheck.rs
  lintcheck-logs/lintcheck_crates_logs.txt
Labels: S-waiting-on-review

#6822 Rustfmt version "Two"
  clippy_lints/src/await_holding_invalid.rs
  clippy_lints/src/float_literal.rs
  clippy_lints/src/infinite_iter.rs
  clippy_lints/src/inherent_to_string.rs
  clippy_lints/src/loops.rs
  clippy_lints/src/mutable_debug_assertion.rs
  clippy_lints/src/needless_continue.rs
  clippy_lints/src/open_options.rs
  clippy_utils/src/camel_case.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/ptr.rs
  rustfmt.toml
  tests/lint_message_convention.rs
  tests/ui-toml/upper_case_acronyms_aggressive/upper_case_acronyms.rs
  tests/ui-toml/upper_case_acronyms_aggressive/upper_case_acronyms.stderr
  tests/ui/auxiliary/macro_rules.rs
  tests/ui/blocks_in_if_conditions.fixed
  tests/ui/blocks_in_if_conditions.rs
  tests/ui/blocks_in_if_conditions.stderr
  tests/ui/checked_unwrap/simple_conditionals.rs
  tests/ui/crashes/ice-6256.rs
  tests/ui/crashes/ice-6256.stderr
  tests/ui/dbg_macro.rs
  tests/ui/dbg_macro.stderr
  tests/ui/default_trait_access.fixed
  tests/ui/default_trait_access.rs
  tests/ui/doc_panics.rs
  tests/ui/doc_panics.stderr
  tests/ui/float_cmp.rs
  tests/ui/float_cmp.stderr
  tests/ui/float_cmp_const.rs
  tests/ui/float_cmp_const.stderr
  tests/ui/floating_point_abs.fixed
  tests/ui/floating_point_abs.rs
  tests/ui/floating_point_abs.stderr
  tests/ui/if_let_some_result.fixed
  tests/ui/if_let_some_result.rs
  tests/ui/if_let_some_result.stderr
  tests/ui/implicit_return.fixed
  tests/ui/implicit_return.rs
  tests/ui/implicit_return.stderr
  tests/ui/needless_lifetimes.rs
  tests/ui/needless_lifetimes.stderr
  tests/ui/redundant_clone.fixed
  tests/ui/redundant_clone.rs
  tests/ui/redundant_clone.stderr
  tests/ui/unnecessary_wraps.rs
  tests/ui/unnecessary_wraps.stderr
  tests/ui/upper_case_acronyms.rs
  tests/ui/use_self.fixed
  tests/ui/use_self.rs
  tests/ui/use_self.stderr
Labels: S-waiting-on-review

#6716 Refactor: arrange transmute lints
  clippy_lints/src/transmute.rs
  clippy_lints/src/transmute/crosspointer_transmute.rs
  clippy_lints/src/transmute/mod.rs
  clippy_lints/src/transmute/transmute_float_to_int.rs
  clippy_lints/src/transmute/transmute_int_to_bool.rs
  clippy_lints/src/transmute/transmute_int_to_char.rs
  clippy_lints/src/transmute/transmute_int_to_float.rs
  clippy_lints/src/transmute/transmute_ptr_to_ptr.rs
  clippy_lints/src/transmute/transmute_ptr_to_ref.rs
  clippy_lints/src/transmute/transmute_ref_to_ref.rs
  clippy_lints/src/transmute/transmutes_expressible_as_ptr_casts.rs
  clippy_lints/src/transmute/unsound_collection_transmute.rs
  clippy_lints/src/transmute/useless_transmute.rs
  clippy_lints/src/transmute/utils.rs
  clippy_lints/src/transmute/wrong_transmute.rs
Labels: S-waiting-on-review

#6791 New lint: `iter_count`
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/methods/iter_count.rs
  clippy_lints/src/methods/mod.rs
  tests/ui/auxiliary/option_helpers.rs
  tests/ui/iter_count.fixed
  tests/ui/iter_count.rs
  tests/ui/iter_count.stderr
  tests/ui/needless_collect.fixed
  tests/ui/needless_collect.rs
Labels: S-waiting-on-review

#6801 Fix `manual_map` false positives
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_map.rs
  clippy_utils/src/lib.rs
  tests/ui/manual_map_option.fixed
  tests/ui/manual_map_option.rs
  tests/ui/manual_map_option.stderr
Labels: S-waiting-on-review

#6824 Refactor: organize loops file into loops module (Delegated)
  clippy_lints/src/loops.rs
  clippy_lints/src/loops/empty_loop.rs
  clippy_lints/src/loops/explicit_counter_loop.rs
  clippy_lints/src/loops/explicit_into_iter_loop.rs
  clippy_lints/src/loops/explicit_iter_loop.rs
  clippy_lints/src/loops/for_kv_map.rs
  clippy_lints/src/loops/for_loops_over_fallibles.rs
  clippy_lints/src/loops/iter_next_loop.rs
  clippy_lints/src/loops/manual_flatten.rs
  clippy_lints/src/loops/manual_memcpy.rs
  clippy_lints/src/loops/mod.rs
  clippy_lints/src/loops/mut_range_bound.rs
  clippy_lints/src/loops/needless_collect.rs
  clippy_lints/src/loops/needless_range_loop.rs
  clippy_lints/src/loops/never_loop.rs
  clippy_lints/src/loops/same_item_push.rs
  clippy_lints/src/loops/single_element_loop.rs
  clippy_lints/src/loops/utils.rs
  clippy_lints/src/loops/while_immutable_condition.rs
  clippy_lints/src/loops/while_let_loop.rs
  clippy_lints/src/loops/while_let_on_iterator.rs
Labels: S-waiting-on-review

#6825 Move naive_bytecount to pedantic
  clippy_lints/src/bytecount.rs
  clippy_lints/src/lib.rs
Labels: S-waiting-on-review

#6839 lintcheck: fix clippy warnings
  clippy_dev/src/lintcheck.rs
Labels: S-waiting-on-review

#6833 Fix false-positive in `use_self`
  clippy_lints/src/use_self.rs
  tests/ui/use_self.fixed
  tests/ui/use_self.rs
Labels: S-waiting-on-review

#6843 Compare empty blocks for equality based on tokens
  clippy_utils/src/hir_utils.rs
  clippy_utils/src/lib.rs
  tests/ui/match_same_arms2.rs
  tests/ui/match_same_arms2.stderr
Labels: S-waiting-on-review

#6846 lintcheck: add test (but don't run on ci)
  clippy_dev/src/lintcheck.rs
  clippy_dev/test_sources.toml
  lintcheck-logs/lintcheck_crates_logs.txt
Labels: S-waiting-on-review

#6849 Dogfood and CI fixes
  .github/workflows/clippy.yml
  .github/workflows/clippy_bors.yml
  clippy_dev/src/lib.rs
  clippy_dev/src/lintcheck.rs
  clippy_lints/src/transmute/transmute_int_to_char.rs
  clippy_lints/src/transmute/transmute_ptr_to_ref.rs
  clippy_lints/src/transmute/transmute_ref_to_ref.rs
  clippy_lints/src/use_self.rs
  src/main.rs
  tests/dogfood.rs
Labels: S-waiting-on-review

#6852 Remove a couple MIR usages
  clippy_lints/src/async_yields_async.rs
  clippy_lints/src/await_holding_invalid.rs
  clippy_lints/src/doc.rs
  clippy_lints/src/implicit_return.rs
Labels: S-waiting-on-review

#6848 lintcheck: add --fix mode which tries to apply lint suggestions to th…
  clippy_dev/src/lintcheck.rs
  clippy_dev/src/main.rs
Labels: S-waiting-on-review

#6854 useless_format: fix examples in the description
  clippy_lints/src/format.rs
Labels: S-waiting-on-review

#6823 Use diagnostic or language items instead of paths
  clippy_lints/src/case_sensitive_file_extension_comparisons.rs
  clippy_lints/src/derive.rs
  clippy_lints/src/lifetimes.rs
  clippy_lints/src/map_clone.rs
  clippy_lints/src/redundant_clone.rs
  clippy_lints/src/types.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/paths.rs
Labels: S-waiting-on-review

#6853 `len_without_is_empty` will now consider multiple impl blocks
  clippy_lints/src/len_zero.rs
  clippy_utils/src/lib.rs
  tests/ui/len_without_is_empty.rs
  tests/ui/len_without_is_empty.stderr
Labels: S-waiting-on-review

#6807 migrate paths to newly-added diagnostic items
  clippy_lints/src/misc.rs
  clippy_lints/src/path_buf_push_overwrite.rs
  clippy_lints/src/ptr.rs
  clippy_lints/src/redundant_clone.rs
  clippy_lints/src/to_string_in_display.rs
  clippy_lints/src/types.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/paths.rs
Labels: S-waiting-on-review

#6864 Add msrv to contents in adding lints md
  doc/adding_lints.md
Labels: S-waiting-on-review

#6834 Let Cargo track CLIPPY_ARGS
  README.md
  src/driver.rs
  tests/dogfood.rs
Labels: S-waiting-on-review

#6725 Refactor types lints
  clippy_lints/src/types/borrowed_box.rs
  clippy_lints/src/types/box_vec.rs
  clippy_lints/src/types/linked_list.rs
  clippy_lints/src/types/mod.rs
  clippy_lints/src/types/option_option.rs
  clippy_lints/src/types/rc_buffer.rs
  clippy_lints/src/types/redundant_allocation.rs
  clippy_lints/src/types/utils.rs
  clippy_lints/src/types/vec_box.rs
Labels: S-waiting-on-review

#6871 Fix redundant closure with macros
  clippy_lints/src/eta_reduction.rs
  tests/ui/eta.fixed
  tests/ui/eta.rs
  tests/ui/eta.stderr
Labels: S-waiting-on-review

#6869 Opt-in to rustc_private for `rust-analyzer`
  Cargo.toml
  clippy_lints/Cargo.toml
  clippy_utils/Cargo.toml
Labels: S-waiting-on-review

#6873 Refactor casts lint
  clippy_lints/src/casts/cast_lossless.rs
  clippy_lints/src/casts/cast_possible_truncation.rs
  clippy_lints/src/casts/cast_possible_wrap.rs
  clippy_lints/src/casts/cast_precision_loss.rs
  clippy_lints/src/casts/cast_ptr_alignment.rs
  clippy_lints/src/casts/cast_ref_to_mut.rs
  clippy_lints/src/casts/cast_sign_loss.rs
  clippy_lints/src/casts/char_lit_as_u8.rs
  clippy_lints/src/casts/fn_to_numeric_cast.rs
  clippy_lints/src/casts/fn_to_numeric_cast_with_truncation.rs
  clippy_lints/src/casts/mod.rs
  clippy_lints/src/casts/ptr_as_ptr.rs
  clippy_lints/src/casts/unnecessary_cast.rs
  clippy_lints/src/casts/utils.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/types/mod.rs
  clippy_utils/src/lib.rs
Labels: S-waiting-on-review

#6868 Don't assume lang items will exist.
  clippy_lints/src/derive.rs
  clippy_lints/src/lifetimes.rs
  clippy_lints/src/map_clone.rs
  clippy_utils/src/lib.rs
Labels: S-waiting-on-review

#6866 Fix ICE 6840 - make is_normalizable more strict
  clippy_utils/src/lib.rs
  tests/ui/crashes/ice-6840.rs
Labels: S-waiting-on-review

#6876 Improve doc on `map_flatten`
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-review

#6878 Set Clippy authors to "The Rust Clippy Developers"
  Cargo.toml
  clippy_dev/Cargo.toml
  clippy_dummy/Cargo.toml
  clippy_lints/Cargo.toml
  mini-macro/Cargo.toml
  rustc_tools_util/Cargo.toml
Labels: S-waiting-on-review

#6814 Fix false positives on procedural macros of `missing_inline_in_public_items` lint
  clippy_lints/src/missing_inline.rs
  tests/ui/missing_inline_executable.rs
  tests/ui/missing_inline_proc_macro.rs
Labels: S-waiting-on-review

#6881 Rustup
  clippy_lints/src/attrs.rs
  clippy_lints/src/cognitive_complexity.rs
  clippy_lints/src/derive.rs
  clippy_lints/src/doc.rs
  clippy_lints/src/entry.rs
  clippy_lints/src/exhaustive_items.rs
  clippy_lints/src/functions.rs
  clippy_lints/src/future_not_send.rs
  clippy_lints/src/inline_fn_without_body.rs
  clippy_lints/src/loops/empty_loop.rs
  clippy_lints/src/loops/explicit_iter_loop.rs
  clippy_lints/src/loops/for_kv_map.rs
  clippy_lints/src/loops/manual_memcpy.rs
  clippy_lints/src/loops/needless_collect.rs
  clippy_lints/src/macro_use.rs
  clippy_lints/src/main_recursion.rs
  clippy_lints/src/matches.rs
  clippy_lints/src/methods/iter_count.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/misc.rs
  clippy_lints/src/missing_const_for_fn.rs
  clippy_lints/src/missing_doc.rs
  clippy_lints/src/missing_inline.rs
  clippy_lints/src/needless_borrow.rs
  clippy_lints/src/needless_pass_by_value.rs
  clippy_lints/src/panic_in_result_fn.rs
  clippy_lints/src/partialeq_ne_impl.rs
  clippy_lints/src/pass_by_ref_or_value.rs
  clippy_lints/src/redundant_clone.rs
  clippy_lints/src/returns.rs
  clippy_lints/src/swap.rs
  clippy_lints/src/types/mod.rs
  clippy_lints/src/unnecessary_wraps.rs
  clippy_lints/src/utils/author.rs
  clippy_lints/src/utils/inspector.rs
  clippy_lints/src/zero_sized_map_values.rs
  clippy_utils/src/eager_or_lazy.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/paths.rs
  clippy_utils/src/qualify_min_const_fn.rs
  rust-toolchain
  src/driver.rs
  tests/versioncheck.rs
Labels: S-waiting-on-review

#6884 move lintcheck into its own crate
  .cargo/config
  .gitignore
  clippy_dev/Cargo.toml
  clippy_dev/src/fmt.rs
  clippy_dev/src/lib.rs
  clippy_dev/src/main.rs
  doc/basics.md
  lintcheck-logs/lintcheck_crates_logs.txt
  lintcheck/Cargo.toml
  lintcheck/README.md
  lintcheck/lintcheck_crates.toml
  lintcheck/src/main.rs
  lintcheck/test_sources.toml
Labels: S-waiting-on-review

#6826 Refactor: arrange lints in `methods` module
  clippy_lints/src/methods/bind_instead_of_map.rs
  clippy_lints/src/methods/bytes_nth.rs
  clippy_lints/src/methods/clone_on_copy.rs
  clippy_lints/src/methods/clone_on_ref_ptr.rs
  clippy_lints/src/methods/expect_fun_call.rs
  clippy_lints/src/methods/expect_used.rs
  clippy_lints/src/methods/filetype_is_file.rs
  clippy_lints/src/methods/filter_flat_map.rs
  clippy_lints/src/methods/filter_map.rs
  clippy_lints/src/methods/filter_map_flat_map.rs
  clippy_lints/src/methods/filter_map_map.rs
  clippy_lints/src/methods/filter_map_next.rs
  clippy_lints/src/methods/filter_next.rs
  clippy_lints/src/methods/flat_map_identity.rs
  clippy_lints/src/methods/from_iter_instead_of_collect.rs
  clippy_lints/src/methods/get_unwrap.rs
  clippy_lints/src/methods/inefficient_to_string.rs
  clippy_lints/src/methods/inspect_for_each.rs
  clippy_lints/src/methods/into_iter_on_ref.rs
  clippy_lints/src/methods/iter_cloned_collect.rs
  clippy_lints/src/methods/iter_count.rs
  clippy_lints/src/methods/iter_next_slice.rs
  clippy_lints/src/methods/iter_nth.rs
  clippy_lints/src/methods/iter_nth_zero.rs
  clippy_lints/src/methods/iter_skip_next.rs
  clippy_lints/src/methods/iterator_step_by_zero.rs
  clippy_lints/src/methods/manual_saturating_arithmetic.rs
  clippy_lints/src/methods/map_collect_result_unit.rs
  clippy_lints/src/methods/map_flatten.rs
  clippy_lints/src/methods/map_unwrap_or.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/ok_expect.rs
  clippy_lints/src/methods/option_as_ref_deref.rs
  clippy_lints/src/methods/option_map_or_none.rs
  clippy_lints/src/methods/option_map_unwrap_or.rs
  clippy_lints/src/methods/or_fun_call.rs
  clippy_lints/src/methods/search_is_some.rs
  clippy_lints/src/methods/single_char_insert_string.rs
  clippy_lints/src/methods/single_char_pattern.rs
  clippy_lints/src/methods/single_char_push_string.rs
  clippy_lints/src/methods/skip_while_next.rs
  clippy_lints/src/methods/string_extend_chars.rs
  clippy_lints/src/methods/suspicious_map.rs
  clippy_lints/src/methods/uninit_assumed_init.rs
  clippy_lints/src/methods/unnecessary_filter_map.rs
  clippy_lints/src/methods/unnecessary_fold.rs
  clippy_lints/src/methods/unnecessary_lazy_eval.rs
  clippy_lints/src/methods/unwrap_used.rs
  clippy_lints/src/methods/useless_asref.rs
  clippy_lints/src/methods/wrong_self_convention.rs
  clippy_lints/src/methods/zst_offset.rs
Labels: S-waiting-on-review

#6891 Use sym::Iterator instead of paths::ITERATOR
  clippy_lints/src/blocks_in_if_conditions.rs
  clippy_lints/src/copy_iterator.rs
  clippy_lints/src/loops/iter_next_loop.rs
  clippy_lints/src/loops/needless_collect.rs
  clippy_lints/src/loops/utils.rs
  clippy_lints/src/loops/while_let_on_iterator.rs
  clippy_lints/src/map_clone.rs
  clippy_lints/src/map_identity.rs
  clippy_lints/src/matches.rs
  clippy_lints/src/methods/filter_flat_map.rs
  clippy_lints/src/methods/filter_map.rs
  clippy_lints/src/methods/filter_map_flat_map.rs
  clippy_lints/src/methods/filter_map_identity.rs
  clippy_lints/src/methods/filter_map_map.rs
  clippy_lints/src/methods/filter_map_next.rs
  clippy_lints/src/methods/filter_next.rs
  clippy_lints/src/methods/flat_map_identity.rs
  clippy_lints/src/methods/from_iter_instead_of_collect.rs
  clippy_lints/src/methods/inspect_for_each.rs
  clippy_lints/src/methods/iter_nth_zero.rs
  clippy_lints/src/methods/iter_skip_next.rs
  clippy_lints/src/methods/iterator_step_by_zero.rs
  clippy_lints/src/methods/map_collect_result_unit.rs
  clippy_lints/src/methods/map_flatten.rs
  clippy_lints/src/methods/search_is_some.rs
  clippy_lints/src/methods/skip_while_next.rs
  clippy_lints/src/methods/unnecessary_filter_map.rs
  clippy_lints/src/methods/unnecessary_fold.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/paths.rs
Labels: S-waiting-on-review

#6865 `explicit_deref_methods` improvements
  clippy_lints/src/dereference.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_map.rs
  clippy_utils/src/lib.rs
  tests/ui/dereference.stderr
  tests/ui/explicit_deref_methods.fixed
  tests/ui/explicit_deref_methods.rs
  tests/ui/explicit_deref_methods.stderr
Labels: S-waiting-on-review

#6820 mem_replace_with_default: recognize some std library ctors
  clippy_lints/src/mem_replace.rs
  clippy_utils/src/lib.rs
  tests/ui/mem_replace.fixed
  tests/ui/mem_replace.rs
  tests/ui/mem_replace.stderr
Labels: S-waiting-on-author

#6859 Implement new lint: if_then_some_else_none
  CHANGELOG.md
  clippy_lints/src/if_then_some_else_none.rs
  clippy_lints/src/lib.rs
  tests/ui/if_then_some_else_none.rs
  tests/ui/if_then_some_else_none.stderr
Labels: S-waiting-on-author

#6895 replace span_lint with span_lint_and_sugg along with error message
  clippy_lints/src/casts/unnecessary_cast.rs
  tests/ui/unnecessary_cast.stderr
Labels: S-waiting-on-review

#6831 Fix suspicious_map false positives
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/suspicious_map.rs
  clippy_utils/src/lib.rs
  tests/ui/suspicious_map.rs
  tests/ui/suspicious_map.stderr
Labels: S-waiting-on-review

#6828 wrong_self_convention: fix lint in case of `to_*_mut` method
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/wrong_self_convention.rs
  tests/ui/def_id_nocore.stderr
  tests/ui/wrong_self_convention.stderr
  tests/ui/wrong_self_conventions_mut.rs
  tests/ui/wrong_self_conventions_mut.stderr
Labels: S-waiting-on-review

#6889 Refactor unit types
  clippy_lints/src/lib.rs
  clippy_lints/src/types/mod.rs
  clippy_lints/src/unit_types/let_unit_value.rs
  clippy_lints/src/unit_types/mod.rs
  clippy_lints/src/unit_types/unit_arg.rs
  clippy_lints/src/unit_types/unit_cmp.rs
  clippy_lints/src/unit_types/utils.rs
Labels: S-waiting-on-author

#6915 Do not show docs link when lint doesn't start with "clippy::"
  clippy_utils/src/diagnostics.rs
Labels: S-waiting-on-review

#6912 Get rid of some unused dependecies
  Cargo.toml
  clippy_lints/Cargo.toml
  clippy_utils/Cargo.toml
  clippy_utils/src/lib.rs
Labels: S-waiting-on-review

#6917 Fix false-positive `manual_unwrap_or` inside const fn
  clippy_lints/src/manual_unwrap_or.rs
  tests/ui/manual_unwrap_or.fixed
  tests/ui/manual_unwrap_or.rs
Labels: S-waiting-on-review

#6888 docs: update RA setup documentation
  CONTRIBUTING.md
  clippy_dev/src/fmt.rs
  clippy_dev/src/ide_setup.rs
  clippy_dev/src/lib.rs
  clippy_dev/src/main.rs
  doc/basics.md
Labels: A-documentation, S-waiting-on-review

#6821 Write literal suggestion
  clippy_lints/src/write.rs
  tests/ui/print.stderr
  tests/ui/print_literal.stderr
  tests/ui/write_literal.stderr
  tests/ui/write_literal_2.rs
  tests/ui/write_literal_2.stderr
Labels: S-waiting-on-author

#6805 upper_case_acronyms: don't warn on public items
  clippy_lints/src/upper_case_acronyms.rs
  tests/ui-toml/upper_case_acronyms_aggressive/upper_case_acronyms.rs
  tests/ui/upper_case_acronyms.rs
Labels: S-waiting-on-review

#6856 Fix `manual_map` suggestion for `if let.. else ... if let.. else` chain
  clippy_lints/src/manual_map.rs
  clippy_utils/src/lib.rs
  tests/ui/manual_map_option.fixed
  tests/ui/manual_map_option.rs
  tests/ui/manual_map_option.stderr
Labels: S-waiting-on-review

#6863 `match_wildcard` improvements
  clippy_lints/src/attrs.rs
  clippy_lints/src/doc.rs
  clippy_lints/src/eval_order_dependence.rs
  clippy_lints/src/loops/never_loop.rs
  clippy_lints/src/matches.rs
  clippy_lints/src/redundant_clone.rs
  clippy_lints/src/types/mod.rs
  clippy_lints/src/unnecessary_wraps.rs
  clippy_utils/src/lib.rs
  tests/ui/match_wildcard_for_single_variants.fixed
  tests/ui/match_wildcard_for_single_variants.rs
  tests/ui/match_wildcard_for_single_variants.stderr
  tests/ui/wildcard_enum_match_arm.fixed
  tests/ui/wildcard_enum_match_arm.stderr
Labels: S-waiting-on-review

#6928 or_fun_call: trigger on unsafe blocks
  clippy_lints/src/methods/or_fun_call.rs
  tests/ui/or_fun_call.fixed
  tests/ui/or_fun_call.rs
  tests/ui/or_fun_call.stderr
Labels: S-waiting-on-review

#6935 needless_question_mark: don't lint if Some(..) is inside a macro def and the ? is not.
  clippy_lints/src/needless_question_mark.rs
  tests/ui/needless_question_mark.fixed
  tests/ui/needless_question_mark.rs
  tests/ui/needless_question_mark.stderr
Labels: S-waiting-on-review

#6924 wrong_self_convention: `to_` convention respects `Copy` types
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/wrong_self_convention.rs
  tests/ui/def_id_nocore.stderr
  tests/ui/use_self.fixed
  tests/ui/use_self.rs
  tests/ui/wrong_self_convention.rs
  tests/ui/wrong_self_convention.stderr
  tests/ui/wrong_self_conventions_mut.stderr
Labels: S-waiting-on-review

#6939 Fix bad suggestion for generics in `new_without_default` lint
  clippy_lints/src/new_without_default.rs
  tests/ui/new_without_default.rs
  tests/ui/new_without_default.stderr
Labels: S-waiting-on-review

#6941 Fix bad suggestion for `match_single_binding` lint
  clippy_lints/src/matches.rs
  tests/ui/match_single_binding2.fixed
  tests/ui/match_single_binding2.rs
  tests/ui/match_single_binding2.stderr
Labels: S-waiting-on-review

#6945 Fix suggestion with generics for `field_reassign_with_default` lint
  clippy_lints/src/default.rs
  tests/ui/field_reassign_with_default.rs
  tests/ui/field_reassign_with_default.stderr
Labels: S-waiting-on-review

#6942 search_is_some: add checking for `is_none()`
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/search_is_some.rs
  tests/ui/search_is_some.rs
  tests/ui/search_is_some.stderr
  tests/ui/search_is_some_fixable.fixed
  tests/ui/search_is_some_fixable.rs
  tests/ui/search_is_some_fixable.stderr
Labels: S-waiting-on-review

#6896 Refactor lints in methods module
  clippy_lints/src/methods/chars_cmp.rs
  clippy_lints/src/methods/chars_cmp_with_unwrap.rs
  clippy_lints/src/methods/chars_last_cmp.rs
  clippy_lints/src/methods/chars_last_cmp_with_unwrap.rs
  clippy_lints/src/methods/chars_next_cmp.rs
  clippy_lints/src/methods/chars_next_cmp_with_unwrap.rs
  clippy_lints/src/methods/clone_on_copy.rs
  clippy_lints/src/methods/clone_on_ref_ptr.rs
  clippy_lints/src/methods/filter_flat_map.rs
  clippy_lints/src/methods/filter_map_flat_map.rs
  clippy_lints/src/methods/filter_map_map.rs
  clippy_lints/src/methods/from_iter_instead_of_collect.rs
  clippy_lints/src/methods/get_unwrap.rs
  clippy_lints/src/methods/inefficient_to_string.rs
  clippy_lints/src/methods/into_iter_on_ref.rs
  clippy_lints/src/methods/iter_cloned_collect.rs
  clippy_lints/src/methods/iter_count.rs
  clippy_lints/src/methods/iter_next_slice.rs
  clippy_lints/src/methods/iter_nth.rs
  clippy_lints/src/methods/iter_skip_next.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/single_char_add_str.rs
  clippy_lints/src/methods/single_char_insert_string.rs
  clippy_lints/src/methods/single_char_pattern.rs
  clippy_lints/src/methods/single_char_push_string.rs
  clippy_lints/src/methods/string_extend_chars.rs
  clippy_lints/src/methods/utils.rs
Labels: S-waiting-on-review

#6950 Ignore str::len() in or_fun_call lint.
  clippy_lints/src/methods/or_fun_call.rs
  tests/ui/or_fun_call.fixed
  tests/ui/or_fun_call.rs
  tests/ui/or_fun_call.stderr
Labels: S-waiting-on-review

#6957 Factor out `SpanlessEq::eq_ty_kind`
  clippy_lints/src/methods/mod.rs
  clippy_utils/src/hir_utils.rs
Labels: S-waiting-on-review

#6962 Fix false positive in `manual_flatten`
  clippy_lints/src/loops/manual_flatten.rs
  clippy_lints/src/methods/utils.rs
  tests/ui/manual_flatten.rs
  tests/ui/manual_flatten.stderr
Labels: S-waiting-on-review

#6952 Fix `new_ret_no_self` false positive
  clippy_lints/src/methods/mod.rs
  clippy_utils/src/ty.rs
  tests/ui/new_ret_no_self.rs
Labels: S-waiting-on-review

#6959 Check for `.to_string().into_bytes()` in string_lit_to_bytes
  clippy_lints/src/strings.rs
  tests/ui/string_lit_as_bytes.fixed
  tests/ui/string_lit_as_bytes.rs
  tests/ui/string_lit_as_bytes.stderr
Labels: S-waiting-on-review

#6961 Update changelog for 1.52
  CHANGELOG.md
Labels: S-waiting-on-review

#6975 Improve `redundant_slicing`
  clippy_lints/src/redundant_slicing.rs
  tests/ui/redundant_slicing.rs
  tests/ui/redundant_slicing.stderr
Labels: S-waiting-on-review

#6977 Add MSRV options to `unnested_or_patterns`
  clippy_lints/src/lib.rs
  clippy_lints/src/unnested_or_patterns.rs
  clippy_lints/src/utils/conf.rs
  doc/adding_lints.md
  tests/ui/min_rust_version_attr.rs
  tests/ui/min_rust_version_attr.stderr
Labels: S-waiting-on-review

#6980 `len_without_is_empty` improvements
  clippy_lints/src/len_zero.rs
  tests/ui/len_without_is_empty.rs
  tests/ui/len_without_is_empty.stderr
Labels: S-waiting-on-review

#6979 Add missing lints to MSRV config doc
  clippy_lints/src/utils/conf.rs
Labels: S-waiting-on-review

#6991 redundant_pattern_matching: look inside Refs
  clippy_lints/src/matches.rs
  tests/ui/match_ref_pats.stderr
Labels: S-waiting-on-review

#6993 Improve `expl_impl_clone_on_copy`
  clippy_lints/src/derive.rs
  tests/ui/derive.rs
  tests/ui/derive.stderr
Labels: S-waiting-on-review

#6996 Allow missing panics doc if the panics occur only when debug-assertions is specified
  clippy_lints/src/doc.rs
  tests/ui/missing_panics_doc.rs
  tests/ui/missing_panics_doc.stderr
Labels: S-waiting-on-review

#7003 Use uppercase for MSRV
  doc/adding_lints.md
Labels: S-waiting-on-review

#6990 Organize functions into functions module
  clippy_lints/src/functions.rs
  clippy_lints/src/functions/mod.rs
  clippy_lints/src/functions/must_use.rs
  clippy_lints/src/functions/not_unsafe_ptr_arg_deref.rs
  clippy_lints/src/functions/result_unit_err.rs
  clippy_lints/src/functions/too_many_arguments.rs
  clippy_lints/src/functions/too_many_lines.rs
  clippy_lints/src/lib.rs
Labels: S-waiting-on-author

#7000 Improve `clone_on_copy`
  clippy_lints/src/methods/clone_on_copy.rs
  tests/ui/clone_on_copy.fixed
  tests/ui/clone_on_copy.rs
  tests/ui/clone_on_copy.stderr
  tests/ui/clone_on_copy_mut.rs
Labels: S-waiting-on-review

#7004 Fix `manual_map` at the end of an if chain
  clippy_lints/src/manual_map.rs
  clippy_utils/src/lib.rs
  tests/ui/manual_map_option.fixed
  tests/ui/manual_map_option.rs
  tests/ui/manual_map_option.stderr
Labels: S-waiting-on-review

#7007 result_unit_err: Fix typo
  clippy_lints/src/functions/result_unit_err.rs
  tests/ui/len_without_is_empty.stderr
  tests/ui/result_unit_error.stderr
Labels: S-waiting-on-review

#6938 Refactor types
  clippy_lints/src/absurd_extreme_comparisons.rs
  clippy_lints/src/implicit_hasher.rs
  clippy_lints/src/invalid_upcast_comparisons.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/types/mod.rs
  clippy_lints/src/types/type_complexity.rs
  tests/ui/linkedlist.rs
  tests/ui/linkedlist.stderr
  tests/ui/option_option.rs
  tests/ui/option_option.stderr
  tests/ui/type_complexity.rs
  tests/ui/type_complexity.stderr
  tests/ui/vec_box_sized.fixed
  tests/ui/vec_box_sized.rs
  tests/ui/vec_box_sized.stderr
Labels: S-waiting-on-review

#6981 disable upper_case_acronyms for pub items - enum edition
  clippy_lints/src/upper_case_acronyms.rs
  tests/ui-toml/upper_case_acronyms_aggressive/upper_case_acronyms.rs
  tests/ui-toml/upper_case_acronyms_aggressive/upper_case_acronyms.stderr
  tests/ui/upper_case_acronyms.rs
  tests/ui/upper_case_acronyms.stderr
Labels: S-waiting-on-review

#6706 New Lint: needless_for_each
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/matches.rs
  clippy_lints/src/needless_for_each.rs
  tests/lint_message_convention.rs
  tests/ui/needless_for_each_fixable.fixed
  tests/ui/needless_for_each_fixable.rs
  tests/ui/needless_for_each_fixable.stderr
  tests/ui/needless_for_each_unfixable.rs
  tests/ui/needless_for_each_unfixable.stderr
Labels: S-waiting-on-review

#6913 Destructure args in `methods`
  clippy_lints/src/methods/bind_instead_of_map.rs
  clippy_lints/src/methods/bytes_nth.rs
  clippy_lints/src/methods/expect_used.rs
  clippy_lints/src/methods/filetype_is_file.rs
  clippy_lints/src/methods/filter_map.rs
  clippy_lints/src/methods/filter_map_identity.rs
  clippy_lints/src/methods/filter_map_next.rs
  clippy_lints/src/methods/filter_next.rs
  clippy_lints/src/methods/flat_map_identity.rs
  clippy_lints/src/methods/get_unwrap.rs
  clippy_lints/src/methods/iter_cloned_collect.rs
  clippy_lints/src/methods/iter_count.rs
  clippy_lints/src/methods/iter_next_slice.rs
  clippy_lints/src/methods/iter_nth.rs
  clippy_lints/src/methods/iter_nth_zero.rs
  clippy_lints/src/methods/iter_skip_next.rs
  clippy_lints/src/methods/iterator_step_by_zero.rs
  clippy_lints/src/methods/manual_saturating_arithmetic.rs
  clippy_lints/src/methods/map_collect_result_unit.rs
  clippy_lints/src/methods/map_flatten.rs
  clippy_lints/src/methods/map_unwrap_or.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/ok_expect.rs
  clippy_lints/src/methods/option_as_ref_deref.rs
  clippy_lints/src/methods/option_map_or_none.rs
  clippy_lints/src/methods/option_map_unwrap_or.rs
  clippy_lints/src/methods/search_is_some.rs
  clippy_lints/src/methods/skip_while_next.rs
  clippy_lints/src/methods/string_extend_chars.rs
  clippy_lints/src/methods/suspicious_map.rs
  clippy_lints/src/methods/uninit_assumed_init.rs
  clippy_lints/src/methods/unnecessary_filter_map.rs
  clippy_lints/src/methods/unnecessary_fold.rs
  clippy_lints/src/methods/unnecessary_lazy_eval.rs
  clippy_lints/src/methods/unwrap_used.rs
  clippy_lints/src/methods/useless_asref.rs
  clippy_lints/src/methods/zst_offset.rs
Labels: S-waiting-on-author

#7008 lintcheck: warn if we get a bad exit status while running clippy
  lintcheck-logs/lintcheck_crates_logs.txt
  lintcheck/src/main.rs
Labels: S-waiting-on-review
