Repository rust-lang/rust-clippy, pull requests merged in 2021-09, with the labels that each got.

#7617 Reference new diagnostic item docs in our docs :)
  doc/common_tools_writing_lints.md
Labels: S-waiting-on-review

#7619 Update README.md
  README.md
Labels: S-waiting-on-review

#7584 Extend unnecessary_unwrap to look for expect in addition to unwrap
  clippy_lints/src/unwrap.rs
  clippy_utils/src/usage.rs
  tests/ui/checked_unwrap/complex_conditionals.stderr
  tests/ui/checked_unwrap/complex_conditionals_nested.stderr
  tests/ui/checked_unwrap/simple_conditionals.rs
  tests/ui/checked_unwrap/simple_conditionals.stderr
Labels: S-waiting-on-author

#7570 Add the `derivable_impls` lint
  CHANGELOG.md
  clippy_lints/src/derivable_impls.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/mem_replace.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/ty.rs
  tests/ui/derivable_impls.rs
  tests/ui/derivable_impls.stderr
  tests/ui/mem_replace.fixed
  tests/ui/mem_replace.rs
  tests/ui/mem_replace.stderr
Labels: S-waiting-on-author

#7629 Make `approx_const` MSRV aware
  clippy_lints/src/approx_const.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/conf.rs
  clippy_utils/src/msrvs.rs
  tests/ui/approx_const.stderr
  tests/ui/min_rust_version_attr.rs
  tests/ui/min_rust_version_attr.stderr
  tests/ui/proc_macro.stderr
Labels: S-waiting-on-review

#7627 Updating issue templates again for rustbot
  .github/ISSUE_TEMPLATE/blank_issue.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/false_positive.md
  doc/adding_lints.md
Labels: S-waiting-on-review

#7638 Avoid slice indexing in Clippy (down with the ICEs)
  clippy_lints/src/blocks_in_if_conditions.rs
  clippy_lints/src/casts/cast_ptr_alignment.rs
  clippy_lints/src/floating_point_arithmetic.rs
  clippy_lints/src/if_let_mutex.rs
  clippy_lints/src/if_let_some_result.rs
  clippy_lints/src/loops/needless_range_loop.rs
  clippy_lints/src/mem_forget.rs
  clippy_lints/src/methods/or_fun_call.rs
  clippy_lints/src/methods/utils.rs
  clippy_lints/src/misc.rs
  clippy_lints/src/mut_mutex_lock.rs
  clippy_lints/src/open_options.rs
  clippy_lints/src/ptr_offset_with_cast.rs
  clippy_lints/src/strings.rs
  clippy_lints/src/to_string_in_display.rs
  clippy_lints/src/undropped_manually_drops.rs
  clippy_lints/src/unused_io_amount.rs
  clippy_lints/src/utils/internal_lints.rs
Labels: S-waiting-on-review

#7596 New lint: option_needless_deref
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/loops/never_loop.rs
  clippy_lints/src/needless_option_as_deref.rs
  tests/ui/needless_option_as_deref.fixed
  tests/ui/needless_option_as_deref.rs
  tests/ui/needless_option_as_deref.stderr
Labels: S-waiting-on-review

#7634 Fix documentation of eval_order_dependence
  clippy_lints/src/eval_order_dependence.rs
Labels: S-waiting-on-review

#7642 Add `TAU` to `approx_constant`
  clippy_lints/src/approx_const.rs
  clippy_utils/src/msrvs.rs
  tests/ui/approx_const.rs
  tests/ui/approx_const.stderr
Labels: S-waiting-on-review

#7607 `mut_range_bound` check for immediate break after mutation
  clippy_lints/src/loops/mod.rs
  clippy_lints/src/loops/mut_range_bound.rs
  tests/ui/mut_range_bound.rs
  tests/ui/mut_range_bound.stderr
Labels: S-waiting-on-author

#7631 Use binary-dep-depinfo to resolve UI test dependencies
  .cargo/config
  Cargo.toml
  clippy_utils/Cargo.toml
  tests/compile-test.rs
  tests/dogfood.rs
  tests/fmt.rs
  tests/integration.rs
  tests/lint_message_convention.rs
  tests/missing-test-files.rs
  tests/versioncheck.rs
Labels: S-waiting-on-review, I-sync-blocker

#7621 Allow giving reasons for `disallowed_methods`
  clippy_lints/src/disallowed_method.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/conf.rs
  tests/ui-toml/toml_disallowed_method/clippy.toml
  tests/ui-toml/toml_disallowed_method/conf_disallowed_method.stderr
Labels: S-waiting-on-review

#7610 Add new lint `iter_not_returning_iterator`
  CHANGELOG.md
  clippy_lints/src/iter_not_returning_iterator.rs
  clippy_lints/src/lib.rs
  tests/ui/iter_not_returning_iterator.rs
  tests/ui/iter_not_returning_iterator.stderr
Labels: S-waiting-on-review

#7660 Fix derivable impl false positives
  clippy_lints/src/derivable_impls.rs
  tests/ui/derivable_impls.rs
Labels: S-waiting-on-review

#7663 Fix result order for `manual_split_once` when `rsplitn` is used
  clippy_lints/src/methods/manual_split_once.rs
  tests/ui/manual_split_once.fixed
  tests/ui/manual_split_once.rs
  tests/ui/manual_split_once.stderr
Labels: S-waiting-on-review

#7661 Fix various redundant_closure bugs
  clippy_lints/src/disallowed_type.rs
  clippy_lints/src/eta_reduction.rs
  clippy_lints/src/format.rs
  clippy_lints/src/loops/while_let_loop.rs
  clippy_lints/src/ptr.rs
  clippy_utils/src/ast_utils.rs
  clippy_utils/src/eager_or_lazy.rs
  tests/ui/eta.fixed
  tests/ui/eta.rs
  tests/ui/eta.stderr
  tests/ui/map_flatten.fixed
  tests/ui/map_flatten.rs
  tests/ui/map_flatten.stderr
  tests/ui/semicolon_if_nothing_returned.rs
  tests/ui/semicolon_if_nothing_returned.stderr
Labels: S-waiting-on-review

#7646 Target directory cleanup
  .cargo/config
  clippy_dev/src/bless.rs
  src/main.rs
  tests/cargo/mod.rs
  tests/compile-test.rs
  tests/dogfood.rs
Labels: S-waiting-on-review

#7670 Updating issue templates to avoid @rustbot triggers
  .github/ISSUE_TEMPLATE/blank_issue.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/false_positive.md
Labels: S-waiting-on-review

#7640 Improve accuracy of `mut_key`
  clippy_lints/src/mut_key.rs
  tests/ui/mut_key.rs
  tests/ui/mut_key.stderr
Labels: S-waiting-on-review

#7671 Downgrade many_single_char_names to pedantic
  clippy_lints/src/lib.rs
  clippy_lints/src/non_expressive_names.rs
  clippy_utils/src/hir_utils.rs
  tests/ui-toml/toml_trivially_copy/test.rs
  tests/ui-toml/toml_trivially_copy/test.stderr
  tests/ui/deref_addrof.fixed
  tests/ui/deref_addrof.rs
  tests/ui/eq_op.rs
  tests/ui/eta.fixed
  tests/ui/eta.rs
  tests/ui/eta.stderr
  tests/ui/eval_order_dependence.rs
  tests/ui/eval_order_dependence.stderr
  tests/ui/explicit_deref_methods.fixed
  tests/ui/explicit_deref_methods.rs
  tests/ui/float_cmp.rs
  tests/ui/float_cmp.stderr
  tests/ui/for_loop_fixable.fixed
  tests/ui/for_loop_fixable.rs
  tests/ui/infinite_loop.rs
  tests/ui/infinite_loop.stderr
  tests/ui/inherent_to_string.rs
  tests/ui/inherent_to_string.stderr
  tests/ui/logic_bug.rs
  tests/ui/many_single_char_names.rs
  tests/ui/match_single_binding.fixed
  tests/ui/match_single_binding.rs
  tests/ui/needless_pass_by_value.rs
  tests/ui/needless_pass_by_value.stderr
  tests/ui/nonminimal_bool.rs
  tests/ui/nonminimal_bool_methods.rs
  tests/ui/op_ref.rs
  tests/ui/op_ref.stderr
  tests/ui/overflow_check_conditional.rs
  tests/ui/overflow_check_conditional.stderr
  tests/ui/ptr_arg.rs
  tests/ui/repeat_once.fixed
  tests/ui/repeat_once.rs
  tests/ui/trivially_copy_pass_by_ref.rs
  tests/ui/trivially_copy_pass_by_ref.stderr
Labels: S-waiting-on-review

#7678 add #3414 test
  tests/ui/wrong_self_convention2.rs
Labels: S-waiting-on-review

#7653 New lint: `same_name_method`
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/same_name_method.rs
  tests/ui/same_name_method.rs
  tests/ui/same_name_method.stderr
Labels: S-waiting-on-review

#7657 `needless_borrow` checks for mutable borrow
  clippy_lints/src/needless_borrow.rs
  tests/ui/needless_borrow.fixed
  tests/ui/needless_borrow.rs
  tests/ui/needless_borrow.stderr
Labels: S-waiting-on-review

#7690 Change `while_let_on_iterator` suggestion to use `by_ref()`
  clippy_lints/src/loops/while_let_on_iterator.rs
  tests/ui/while_let_on_iterator.fixed
  tests/ui/while_let_on_iterator.stderr
Labels: S-waiting-on-review

#7694 Retry on some download errors in lintcheck
  lintcheck/src/main.rs
Labels: S-waiting-on-review

#7679 add #4546 test
  clippy_lints/src/methods/mod.rs
  tests/ui/wrong_self_convention2.rs
Labels: S-waiting-on-review

#7704 Tweak pedantic description for occasional FPs
  README.md
Labels: S-waiting-on-review

#7693 Expand box_vec lint to box_collection
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/types/box_collection.rs
  clippy_lints/src/types/box_vec.rs
  clippy_lints/src/types/mod.rs
  clippy_lints/src/utils/conf.rs
  tests/ui/box_collection.rs
  tests/ui/box_collection.stderr
  tests/ui/box_vec.stderr
Labels: S-waiting-on-review

#7707 Don't lint `suspicious_else_formatting` inside proc-macros
  clippy_lints/src/formatting.rs
  tests/ui/auxiliary/proc_macro_suspicious_else_formatting.rs
  tests/ui/suspicious_else_formatting.rs
  tests/ui/suspicious_else_formatting.stderr
Labels: S-waiting-on-review

#7715 Avoid needless heap allocation in box_collection
  clippy_lints/src/types/box_collection.rs
Labels: S-waiting-on-review

#7669 New lint `if_then_panic`
  CHANGELOG.md
  clippy_lints/src/if_then_panic.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/internal_lints.rs
  clippy_utils/src/higher.rs
  tests/compile-test.rs
  tests/integration.rs
  tests/ui/fallible_impl_from.rs
  tests/ui/fallible_impl_from.stderr
  tests/ui/if_then_panic.fixed
  tests/ui/if_then_panic.rs
  tests/ui/if_then_panic.stderr
  tests/ui/ptr_arg.rs
  tests/ui/ptr_arg.stderr
Labels: S-waiting-on-review

#7722 Stop suggesting a float truncation that is not shorter
  clippy_lints/src/float_literal.rs
  tests/ui/excessive_precision.fixed
  tests/ui/excessive_precision.stderr
Labels: S-waiting-on-review

#7692 Demote float_cmp to pedantic
  clippy_lints/src/lib.rs
  clippy_lints/src/misc.rs
Labels: S-waiting-on-review

#7664 bump clippy crates to edition 2021
  Cargo.toml
  clippy_dev/Cargo.toml
  clippy_lints/Cargo.toml
  clippy_lints/src/matches.rs
  clippy_utils/Cargo.toml
Labels: S-waiting-on-review

#7727 Update changelog to 1.56
  CHANGELOG.md
Labels: S-waiting-on-review

#7733 Rustup
  Cargo.toml
  clippy_dev/Cargo.toml
  clippy_dummy/Cargo.toml
  clippy_lints/Cargo.toml
  clippy_lints/src/attrs.rs
  clippy_lints/src/cargo_common_metadata.rs
  clippy_lints/src/cognitive_complexity.rs
  clippy_lints/src/copies.rs
  clippy_lints/src/doc.rs
  clippy_lints/src/escape.rs
  clippy_lints/src/fallible_impl_from.rs
  clippy_lints/src/implicit_hasher.rs
  clippy_lints/src/large_const_arrays.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/loops/for_kv_map.rs
  clippy_lints/src/loops/iter_next_loop.rs
  clippy_lints/src/loops/mod.rs
  clippy_lints/src/loops/needless_range_loop.rs
  clippy_lints/src/loops/while_let_on_iterator.rs
  clippy_lints/src/macro_use.rs
  clippy_lints/src/methods/manual_split_once.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/module_style.rs
  clippy_lints/src/redundant_clone.rs
  clippy_lints/src/regex.rs
  clippy_lints/src/tabs_in_doc_comments.rs
  clippy_lints/src/utils/internal_lints.rs
  clippy_lints/src/utils/internal_lints/metadata_collector.rs
  clippy_utils/Cargo.toml
  clippy_utils/src/higher.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/paths.rs
  clippy_utils/src/qualify_min_const_fn.rs
  lintcheck/Cargo.toml
  rust-toolchain
  tests/ui-internal/invalid_paths.stderr
  tests/ui/default_trait_access.fixed
  tests/ui/default_trait_access.rs
Labels: S-waiting-on-review

#7711 Improve depinfo error
  tests/compile-test.rs
Labels: S-waiting-on-review

#7734 Make `doc_unsafe` warn on unsafe traits as well
  clippy_lints/src/doc.rs
  tests/ui/def_id_nocore.rs
  tests/ui/def_id_nocore.stderr
  tests/ui/doc_unsafe.rs
  tests/ui/doc_unsafe.stderr
Labels: S-waiting-on-review

#7736 Fix typo ("asynx" corrected to "async")
  clippy_lints/src/await_holding_invalid.rs
Labels: S-waiting-on-review

#7673 Move code generated by `update_lints` to includes
  clippy_dev/src/lib.rs
  clippy_dev/src/update_lints.rs
  clippy_lints/src/lib.deprecated.rs
  clippy_lints/src/lib.mods.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_cargo.rs
  clippy_lints/src/lib.register_complexity.rs
  clippy_lints/src/lib.register_correctness.rs
  clippy_lints/src/lib.register_internal.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_nursery.rs
  clippy_lints/src/lib.register_pedantic.rs
  clippy_lints/src/lib.register_perf.rs
  clippy_lints/src/lib.register_restriction.rs
  clippy_lints/src/lib.register_style.rs
  clippy_lints/src/lib.register_suspicious.rs
  clippy_lints/src/lib.rs
  util/etc/pre-commit.sh
Labels: S-waiting-on-review

#7684 fix for issue #7683
  clippy_utils/src/lib.rs
  tests/ui/derivable_impls.rs
  tests/ui/derivable_impls.stderr
Labels: S-waiting-on-author

#7677 fix bug for large_enum_variants
  clippy_lints/src/large_enum_variant.rs
  tests/ui/large_enum_variant.rs
  tests/ui/large_enum_variant.stderr
Labels: S-waiting-on-review

#7338 Re-write shadow lints
  clippy_lints/src/lib.register_pedantic.rs
  clippy_lints/src/lib.register_restriction.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/shadow.rs
  clippy_utils/src/lib.rs
  tests/ui/approx_const.rs
  tests/ui/for_loop_fixable.fixed
  tests/ui/for_loop_fixable.rs
  tests/ui/for_loop_fixable.stderr
  tests/ui/for_loop_unfixable.rs
  tests/ui/for_loop_unfixable.stderr
  tests/ui/integer_arithmetic.rs
  tests/ui/integer_arithmetic.stderr
  tests/ui/map_clone.fixed
  tests/ui/map_clone.rs
  tests/ui/modulo_arithmetic_float.rs
  tests/ui/modulo_arithmetic_float.stderr
  tests/ui/modulo_arithmetic_integral.rs
  tests/ui/modulo_arithmetic_integral.stderr
  tests/ui/modulo_arithmetic_integral_const.rs
  tests/ui/modulo_arithmetic_integral_const.stderr
  tests/ui/shadow.rs
  tests/ui/shadow.stderr
Labels: S-waiting-on-review
