Repository rust-lang/rust-clippy, pull requests merged in 2021-05, with the labels that each got.

#7150 `Conf` macro improvements
  clippy_lints/src/default.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/conf.rs
  tests/ui-toml/bad_toml_type/conf_bad_type.stderr
  tests/ui-toml/conf_deprecated_key/conf_deprecated_key.stderr
Labels: S-waiting-on-review

#7154 `Conf` macro improvements part 2
  clippy_lints/src/utils/conf.rs
  doc/adding_lints.md
  tests/ui-toml/conf_deprecated_key/conf_deprecated_key.stderr
  util/lintlib.py
Labels: S-waiting-on-review

#7156 [single_char_pattern] add strip_prefix and strip_suffix
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/single_char_pattern.rs
  tests/ui/single_char_pattern.fixed
  tests/ui/single_char_pattern.rs
  tests/ui/single_char_pattern.stderr
Labels: S-waiting-on-review

#7157 SpanlessHash add Pat
  clippy_utils/src/hir_utils.rs
Labels: S-waiting-on-review

#7167 Fix unused_unit macro false positive
  clippy_lints/src/unused_unit.rs
  tests/ui/unused_unit.fixed
  tests/ui/unused_unit.rs
Labels: S-waiting-on-review

#7163 needless_collect: Lint cases with type annotations for indirect usage and recognize `BinaryHeap`
  clippy_lints/src/loops/needless_collect.rs
  tests/ui/copy_iterator.rs
  tests/ui/needless_collect_indirect.rs
  tests/ui/needless_collect_indirect.stderr
Labels: S-waiting-on-author

#6887 A metadata collection monster
  .gitignore
  Cargo.toml
  clippy_lints/Cargo.toml
  clippy_lints/src/lib.rs
  clippy_lints/src/slow_vector_initialization.rs
  clippy_lints/src/utils/internal_lints.rs
  clippy_lints/src/utils/internal_lints/metadata_collector.rs
  clippy_lints/src/utils/mod.rs
  clippy_utils/Cargo.toml
  clippy_utils/src/diagnostics.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/paths.rs
  tests/dogfood.rs
Labels: S-waiting-on-review

#7170 Fix stack overflow issue in `redundant_pattern_matching`
  clippy_lints/src/matches.rs
  tests/ui/crashes/ice-7169.rs
  tests/ui/crashes/ice-7169.stderr
Labels: I-sync-blocker, S-waiting-on-review

#7174 Fix eval_order_dependence async false positive
  clippy_lints/src/eval_order_dependence.rs
  tests/ui/eval_order_dependence.rs
  tests/ui/eval_order_dependence.stderr
Labels: S-waiting-on-review

#7175 Fix unnecessary_filter_map false positive
  clippy_lints/src/methods/unnecessary_filter_map.rs
  tests/ui/unnecessary_filter_map.rs
Labels: S-waiting-on-review

#7166 Refactor: arrange lints in misc_early module
  clippy_lints/src/misc_early.rs
  clippy_lints/src/misc_early/builtin_type_shadow.rs
  clippy_lints/src/misc_early/double_neg.rs
  clippy_lints/src/misc_early/mixed_case_hex_literals.rs
  clippy_lints/src/misc_early/mod.rs
  clippy_lints/src/misc_early/redundant_pattern.rs
  clippy_lints/src/misc_early/unneeded_field_pattern.rs
  clippy_lints/src/misc_early/unneeded_wildcard_pattern.rs
  clippy_lints/src/misc_early/unseparated_literal_suffix.rs
  clippy_lints/src/misc_early/zero_prefixed_literal.rs
  tests/ui/builtin_type_shadow.rs
  tests/ui/builtin_type_shadow.stderr
Labels: S-waiting-on-review

#7177 Add a missing lint to MSRV config doc
  clippy_lints/src/utils/conf.rs
Labels: S-waiting-on-review

#7180 Update CHANGELOG.md
  CHANGELOG.md
Labels: S-waiting-on-review

#7185 Fix duplicated "Rust 1.52" version section header
  CHANGELOG.md
Labels: S-waiting-on-review

#7182 For `to_*` variant don't lint in trait impl taking `self` when non-`Copy` type
  clippy_lints/src/methods/wrong_self_convention.rs
  tests/ui/wrong_self_convention2.rs
  tests/ui/wrong_self_convention2.stderr
Labels: S-waiting-on-review

#7183 Handle write!(buf, "\n") case better
  clippy_lints/src/write.rs
  tests/ui/write_with_newline.stderr
Labels: S-waiting-on-review

#7165 Fix needless_quesiton_mark false positive
  clippy_lints/src/needless_question_mark.rs
  tests/ui/needless_question_mark.fixed
  tests/ui/needless_question_mark.rs
  tests/ui/needless_question_mark.stderr
Labels: S-waiting-on-review

#7197 Metadata collection monster eating deprecated lints
  clippy_lints/src/deprecated_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/internal_lints/metadata_collector.rs
Labels: S-waiting-on-review

#6966 `while_let_on_iterator` Improvements
  clippy_lints/src/doc.rs
  clippy_lints/src/loops/while_let_on_iterator.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/sugg.rs
  clippy_utils/src/visitors.rs
  tests/ui/while_let_on_iterator.fixed
  tests/ui/while_let_on_iterator.rs
  tests/ui/while_let_on_iterator.stderr
Labels: S-waiting-on-review

#7095 match_single_binding: Fix invalid suggestion when match scrutinee has side effects
  clippy_lints/src/matches.rs
  tests/ui/match_single_binding.fixed
  tests/ui/match_single_binding.rs
  tests/ui/match_single_binding.stderr
  tests/ui/match_single_binding2.fixed
  tests/ui/match_single_binding2.rs
  tests/ui/match_single_binding2.stderr
Labels: S-waiting-on-review

#7215 Trigger [`wrong_self_convention`] only if it has implicit self
  clippy_lints/src/methods/mod.rs
  tests/ui/wrong_self_convention2.rs
  tests/ui/wrong_self_convention2.stderr
Labels: S-waiting-on-review

#7188 `needless_collect` enhancements
  clippy_lints/src/loops/needless_collect.rs
  tests/ui/needless_collect.fixed
  tests/ui/needless_collect.rs
  tests/ui/needless_collect.stderr
Labels: S-waiting-on-review

#7222 Add sized trait for `wrong_self_convention` lint test
  tests/ui/wrong_self_convention2.rs
Labels: S-waiting-on-review

#7217 Add `cargo collect-metadata` as an cargo alias for the metadata collection lint
  .cargo/config
  tests/dogfood.rs
Labels: S-waiting-on-review

#7214 Metadata collection monster searching for Clippy's configuration options
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/conf.rs
  clippy_lints/src/utils/internal_lints/metadata_collector.rs
Labels: S-waiting-on-review

#7216 Stop linting `else if let` pattern in [`option_if_let_else`] lint
  clippy_lints/src/option_if_let_else.rs
  tests/ui/option_if_let_else.fixed
  tests/ui/option_if_let_else.stderr
Labels: S-waiting-on-review

#7225 New lint: `unused_async`
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/unused_async.rs
  tests/ui/unused_async.rs
  tests/ui/unused_async.stderr
Labels: S-waiting-on-review

#7233 Fix a `manual_unwrap_or` FP with deref coercion
  clippy_lints/src/manual_unwrap_or.rs
  tests/ui/manual_unwrap_or.fixed
  tests/ui/manual_unwrap_or.rs
Labels: S-waiting-on-review

#7223 Fix FPs about generic args
  clippy_lints/src/use_self.rs
  clippy_lints/src/useless_conversion.rs
  clippy_utils/src/ty.rs
  tests/ui/use_self.fixed
  tests/ui/use_self.rs
  tests/ui/use_self.stderr
  tests/ui/useless_conversion.fixed
  tests/ui/useless_conversion.rs
  tests/ui/useless_conversion.stderr
Labels: S-waiting-on-review

#7133 Add `needless_bitwise_bool` lint
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/needless_bitwise_bool.rs
  tests/ui/needless_bitwise_bool.fixed
  tests/ui/needless_bitwise_bool.rs
  tests/ui/needless_bitwise_bool.stderr
Labels: S-waiting-on-review

#7234 Remove dead code after #7216
  clippy_lints/src/option_if_let_else.rs
Labels: S-waiting-on-review

#7201 Remove powi, "square can be computed more efficiently"
  clippy_lints/src/floating_point_arithmetic.rs
  tests/ui/floating_point_powi.fixed
  tests/ui/floating_point_powi.rs
  tests/ui/floating_point_powi.stderr
Labels: S-waiting-on-author

#7235 Fix another manual_unwrap_or deref FP
  clippy_lints/src/manual_unwrap_or.rs
  tests/ui/manual_unwrap_or.fixed
  tests/ui/manual_unwrap_or.rs
Labels: S-waiting-on-bors

#7237 Add the command to add upstream remote
  doc/basics.md
Labels: S-waiting-on-bors

#7239 CI: update rustup before installing the toolchain on windows
  .github/workflows/clippy_bors.yml
Labels: S-waiting-on-bors

#7240 Rollup of 3 pull requests
  .github/workflows/clippy_bors.yml
  clippy_lints/src/manual_unwrap_or.rs
  doc/basics.md
  tests/ui/manual_unwrap_or.fixed
  tests/ui/manual_unwrap_or.rs
Labels: rollup

#7241 Deny warnings in every main sub-crate
  Cargo.toml
  clippy_dev/src/lib.rs
  clippy_dev/src/main.rs
  clippy_lints/Cargo.toml
  clippy_utils/Cargo.toml
  clippy_utils/src/lib.rs
  clippy_utils/src/ty.rs
Labels: S-waiting-on-review

#7242 Fix ICE in `implicit_return`
  clippy_lints/src/implicit_return.rs
  tests/ui/crashes/ice-7231.rs
Labels: S-waiting-on-review

#7089 Don't lint `multiple_inherent_impl` with generic arguments
  clippy_lints/src/inherent_impl.rs
  clippy_lints/src/lib.rs
  tests/ui/impl.rs
  tests/ui/impl.stderr
Labels: S-waiting-on-author

#7246 Adding the default lint level to the metadata collection
  clippy_lints/src/utils/internal_lints/metadata_collector.rs
Labels: S-waiting-on-review

#7258 Updated years in copyrigths
  COPYRIGHT
  LICENSE-APACHE
  LICENSE-MIT
  README.md
Labels: S-waiting-on-review

#7105 fix `needless_borrow` suggestion
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/needless_borrow.rs
  clippy_utils/src/higher.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/visitors.rs
  tests/ui/needless_borrow.fixed
  tests/ui/needless_borrow.rs
  tests/ui/needless_borrow.stderr
  tests/ui/needless_borrow_pat.rs
  tests/ui/needless_borrow_pat.stderr
  tests/ui/ref_binding_to_reference.rs
  tests/ui/ref_binding_to_reference.stderr
Labels: S-waiting-on-review

#7254 Move `needless_borrow` to style
  clippy_lints/src/lib.rs
  clippy_lints/src/needless_borrow.rs
  clippy_lints/src/ptr.rs
  clippy_lints/src/single_component_path_imports.rs
  clippy_lints/src/unused_io_amount.rs
  clippy_lints/src/utils/internal_lints/metadata_collector.rs
  clippy_utils/src/consts.rs
  clippy_utils/src/higher.rs
  clippy_utils/src/hir_utils.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/numeric_literal.rs
  clippy_utils/src/ptr.rs
  clippy_utils/src/qualify_min_const_fn.rs
  clippy_utils/src/ty.rs
  clippy_utils/src/usage.rs
Labels: S-waiting-on-review

#7263 Fix `redundant_closure` for `vec![]` macro in a closure with arguments
  clippy_lints/src/eta_reduction.rs
  tests/ui/eta.fixed
  tests/ui/eta.rs
  tests/ui/eta.stderr
Labels: S-waiting-on-review

#7264 Fix invalid syntax in `from_iter_instead_of_collect` suggestion
  clippy_lints/src/methods/from_iter_instead_of_collect.rs
  tests/ui/from_iter_instead_of_collect.fixed
  tests/ui/from_iter_instead_of_collect.rs
  tests/ui/from_iter_instead_of_collect.stderr
Labels: S-waiting-on-review

#7255 Allow wparam and lparam in similar_names
  clippy_lints/src/non_expressive_names.rs
  tests/ui/similar_names.rs
  tests/ui/similar_names.stderr
Labels: S-waiting-on-review

#7266 Downgrade suspicious_op..._groupings to Nursery
  clippy_lints/src/lib.rs
  clippy_lints/src/suspicious_operation_groupings.rs
Labels: S-waiting-on-review

#7267 Some SpanlessHash improvements
  clippy_lints/src/trait_bounds.rs
  clippy_utils/src/hir_utils.rs
  clippy_utils/src/lib.rs
Labels: S-waiting-on-review

#7256 Adding the ability to invalidate caches to force metadata collection
  Cargo.toml
  tests/dogfood.rs
Labels: S-waiting-on-review

#7280 Add macro_use clippy_utils
  clippy_lints/src/lib.rs
Labels: S-waiting-on-review

#7187 Add avoid_breaking_exported_api config option
  README.md
  build.rs
  clippy.toml
  clippy_lints/src/deprecated_lints.rs
  clippy_lints/src/enum_variants.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/wrong_self_convention.rs
  clippy_lints/src/pass_by_ref_or_value.rs
  clippy_lints/src/unnecessary_wraps.rs
  clippy_lints/src/upper_case_acronyms.rs
  clippy_lints/src/utils/conf.rs
  rustc_tools_util/src/lib.rs
  tests/clippy.toml
  tests/compile-test.rs
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
  tests/ui/def_id_nocore.rs
  tests/ui/deprecated.rs
  tests/ui/deprecated.stderr
  tests/ui/enum_variants.rs
  tests/ui/enum_variants.stderr
  tests/ui/module_name_repetitions.rs
  tests/ui/trivially_copy_pass_by_ref.stderr
  tests/ui/unnecessary_wraps.rs
  tests/ui/wrong_self_convention.rs
  tests/ui/wrong_self_convention.stderr
  tests/ui/wrong_self_convention2.rs
  tests/ui/wrong_self_convention2.stderr
Labels: S-waiting-on-author

#7282 Fix allow on some statement lints
  clippy_lints/src/loops/needless_collect.rs
  clippy_lints/src/misc.rs
  clippy_lints/src/no_effect.rs
  clippy_utils/src/diagnostics.rs
  tests/ui/needless_collect_indirect.rs
  tests/ui/no_effect.rs
Labels: S-waiting-on-review

#7281 Fix missing_docs_in_private_items false negative
  clippy_lints/src/missing_doc.rs
  tests/ui/missing-doc-impl.rs
  tests/ui/missing-doc-impl.stderr
Labels: S-waiting-on-review

#7283 Document to only push the created tag and not everything
  doc/release.md
Labels: S-waiting-on-review

#7284 Remove clippy_utils::consts re-export
  clippy_lints/src/absurd_extreme_comparisons.rs
  clippy_lints/src/arithmetic.rs
  clippy_lints/src/assertions_on_constants.rs
  clippy_lints/src/bit_mask.rs
  clippy_lints/src/casts/cast_sign_loss.rs
  clippy_lints/src/consts.rs
  clippy_lints/src/duration_subsec.rs
  clippy_lints/src/enum_clike.rs
  clippy_lints/src/erasing_op.rs
  clippy_lints/src/floating_point_arithmetic.rs
  clippy_lints/src/identity_op.rs
  clippy_lints/src/indexing_slicing.rs
  clippy_lints/src/invalid_upcast_comparisons.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/loops/while_immutable_condition.rs
  clippy_lints/src/manual_strip.rs
  clippy_lints/src/manual_unwrap_or.rs
  clippy_lints/src/matches.rs
  clippy_lints/src/methods/iter_nth_zero.rs
  clippy_lints/src/methods/iterator_step_by_zero.rs
  clippy_lints/src/minmax.rs
  clippy_lints/src/misc.rs
  clippy_lints/src/modulo_arithmetic.rs
  clippy_lints/src/neg_multiply.rs
  clippy_lints/src/ranges.rs
  clippy_lints/src/regex.rs
  clippy_lints/src/repeat_once.rs
  clippy_lints/src/transmuting_null.rs
  clippy_lints/src/utils/internal_lints.rs
  clippy_lints/src/vec.rs
  clippy_lints/src/zero_div_zero.rs
Labels: S-waiting-on-review

#7285 Move mini-macro to tests/ui/auxilary
  Cargo.toml
  mini-macro/Cargo.toml
  mini-macro/src/lib.rs
  tests/ui/auxiliary/proc_macro_derive.rs
  tests/ui/crashes/procedural_macro.rs
  tests/ui/macro_use_imports.fixed
  tests/ui/macro_use_imports.rs
  tests/ui/macro_use_imports.stderr
  tests/ui/unseparated_prefix_literals.fixed
  tests/ui/unseparated_prefix_literals.rs
  tests/ui/unseparated_prefix_literals.stderr
Labels: S-waiting-on-review

#7287 Fix ICE in `too_many_lines`
  clippy_lints/src/functions/too_many_lines.rs
  tests/ui/crashes/auxiliary/ice-7272-aux.rs
  tests/ui/crashes/ice-7272.rs
Labels: S-waiting-on-review

#7292 Add lint `suspicious_splitn`
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/suspicious_splitn.rs
  tests/ui/single_char_pattern.fixed
  tests/ui/single_char_pattern.rs
  tests/ui/single_char_pattern.stderr
  tests/ui/suspicious_splitn.rs
  tests/ui/suspicious_splitn.stderr
Labels: S-waiting-on-review

#7294 Improve message for `not_unsafe_ptr_arg_deref` lint
  clippy_lints/src/functions/not_unsafe_ptr_arg_deref.rs
  tests/ui/functions.stderr
Labels: S-waiting-on-review
