Repository rust-lang/rust-clippy, pull requests merged in 2021-01, with the labels that each got.

#6526 make clippy version number correspond to rustc version number.
  Cargo.toml
  clippy_lints/Cargo.toml
  tests/versioncheck.rs
Labels: S-waiting-on-review

#6530 Initial support for Rust 2021.
  clippy_lints/src/macro_use.rs
  clippy_lints/src/single_component_path_imports.rs
Labels: S-waiting-on-review

#6520 Update CHANGELOG for Rust 1.50
  CHANGELOG.md
Labels: S-waiting-on-review

#6531 field_reassign_with_default: don't expand macros in suggestion
  clippy_lints/src/default.rs
  tests/ui/field_reassign_with_default.rs
  tests/ui/field_reassign_with_default.stderr
Labels: S-waiting-on-review

#6537 [beta] Backport of #6375 - field_reassign_with_default fix
  clippy_lints/src/default.rs
  tests/ui/field_reassign_with_default.rs
  tests/ui/field_reassign_with_default.stderr
Labels: S-waiting-on-author

#6525 Fix blessing of test output in subdirectories
  clippy_dev/src/bless.rs
Labels: S-waiting-on-review

#6544 collapsible_if: split collapsible_else_if into its own lint so we can enable/disable it particularly
  CHANGELOG.md
  clippy_lints/src/collapsible_if.rs
  clippy_lints/src/lib.rs
  tests/ui/collapsible_else_if.fixed
  tests/ui/collapsible_else_if.rs
  tests/ui/collapsible_else_if.stderr
  tests/ui/if_same_then_else2.rs
  tests/ui/if_same_then_else2.stderr
Labels: S-waiting-on-review

#6507 Needless Question Mark Lint
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/needless_question_mark.rs
  tests/ui/needless_question_mark.fixed
  tests/ui/needless_question_mark.rs
  tests/ui/needless_question_mark.stderr
  tests/ui/try_err.fixed
  tests/ui/try_err.rs
  tests/ui/unit_arg.rs
  tests/ui/unit_arg.stderr
Labels: S-waiting-on-author

#6548 Add ui-internal to cargo dev bless
  clippy_dev/src/bless.rs
Labels: S-waiting-on-review

#6538 New lint: vec_init_then_push
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/vec_init_then_push.rs
  tests/ui/clone_on_copy.fixed
  tests/ui/clone_on_copy.rs
  tests/ui/clone_on_copy.stderr
  tests/ui/vec_init_then_push.rs
  tests/ui/vec_init_then_push.stderr
Labels: S-waiting-on-review

#6547 Curse outdated test output
  clippy_dev/src/bless.rs
  clippy_dev/src/main.rs
Labels: S-waiting-on-review

#6542 Add a new lint `ptr_as_ptr`
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/types.rs
  tests/ui/ptr_as_ptr.fixed
  tests/ui/ptr_as_ptr.rs
  tests/ui/ptr_as_ptr.stderr
Labels: S-waiting-on-review

#6551 Tiny Symbol cleanup
  clippy_lints/src/utils/mod.rs
  clippy_lints/src/utils/sym_helper.rs
Labels: S-waiting-on-review

#6553 Fix derive and macro related false positives in `field_reassign_with_default`
  clippy_lints/src/default.rs
  clippy_lints/src/needless_borrow.rs
  tests/ui/auxiliary/macro_rules.rs
  tests/ui/auxiliary/proc_macro_derive.rs
  tests/ui/field_reassign_with_default.rs
  tests/ui/field_reassign_with_default.stderr
Labels: S-waiting-on-review

#6558 Fix typo: `irrevelent` -> `irrelevant`
  clippy_lints/src/ref_option_ref.rs
Labels: S-waiting-on-review

#6566 Reduce the span in `from_over_into` to impl header
  clippy_lints/src/from_over_into.rs
  tests/ui/from_over_into.stderr
Labels: S-waiting-on-review

#6569 Internal lint symbol comparisons
  clippy_lints/src/attrs.rs
  clippy_lints/src/if_let_mutex.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_async_fn.rs
  clippy_lints/src/map_clone.rs
  clippy_lints/src/map_identity.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/minmax.rs
  clippy_lints/src/missing_doc.rs
  clippy_lints/src/needless_pass_by_value.rs
  clippy_lints/src/option_if_let_else.rs
  clippy_lints/src/shadow.rs
  clippy_lints/src/swap.rs
  clippy_lints/src/unnecessary_sort_by.rs
  clippy_lints/src/useless_conversion.rs
  clippy_lints/src/utils/attrs.rs
  clippy_lints/src/utils/hir_utils.rs
  clippy_lints/src/utils/internal_lints.rs
  clippy_lints/src/utils/paths.rs
  clippy_lints/src/vec_init_then_push.rs
  clippy_lints/src/wildcard_imports.rs
  clippy_lints/src/write.rs
  tests/ui-internal/interning_defined_symbol.fixed
  tests/ui-internal/interning_defined_symbol.rs
  tests/ui-internal/interning_defined_symbol.stderr
  tests/ui-internal/unnecessary_symbol_str.fixed
  tests/ui-internal/unnecessary_symbol_str.rs
  tests/ui-internal/unnecessary_symbol_str.stderr
Labels: S-waiting-on-review

#6571 Fix FP for `boxed_local` lint in default trait fn impl
  clippy_lints/src/escape.rs
  tests/ui/escape_analysis.rs
  tests/ui/escape_analysis.stderr
Labels: S-waiting-on-review

#6565 Small fixes of doc in `needless_question_mark`
  clippy_lints/src/needless_question_mark.rs
Labels: S-waiting-on-review

#6575 Change env var used for testing Clippy
  doc/adding_lints.md
  src/driver.rs
  tests/compile-test.rs
Labels: S-waiting-on-review

#6557 Catch `pointer::cast` too in `cast_ptr_alignment`
  clippy_lints/src/types.rs
  clippy_lints/src/utils/mod.rs
  tests/ui/cast_alignment.rs
  tests/ui/cast_alignment.stderr
Labels: S-waiting-on-author

#6462 Roadmap for 2021
  doc/roadmap-2021.md
Labels: S-waiting-on-review

#6584 Make a reference a link in doc
  clippy_lints/src/comparison_chain.rs
  clippy_lints/src/eta_reduction.rs
  clippy_lints/src/loops.rs
  clippy_lints/src/types.rs
  clippy_lints/src/use_self.rs
Labels: S-waiting-on-review

#6555 Remove duplication in the manual_ok_or lint example
  clippy_lints/src/manual_ok_or.rs
Labels: S-waiting-on-review

#6589 Add notes of prioritization labels to doc
  CONTRIBUTING.md
Labels: S-waiting-on-review

#6574 single_match: suggest `if` over `if let` when possible
  clippy_lints/src/matches.rs
  clippy_lints/src/utils/mod.rs
  tests/ui/single_match.rs
  tests/ui/single_match.stderr
  tests/ui/single_match_else.stderr
Labels: S-waiting-on-review

#6500 Case sensitive file extensions
  CHANGELOG.md
  clippy_lints/Cargo.toml
  clippy_lints/src/case_sensitive_file_extension_comparisons.rs
  clippy_lints/src/lib.rs
  tests/compile-test.rs
  tests/ui/case_sensitive_file_extension_comparisons.rs
  tests/ui/case_sensitive_file_extension_comparisons.stderr
Labels: S-waiting-on-review

#6549 Fix FP with empty return for `needless_return` lint
  clippy_lints/src/returns.rs
  tests/ui/needless_return.fixed
  tests/ui/needless_return.rs
  tests/ui/needless_return.stderr
Labels: S-waiting-on-review

#6582 Fix the ICE 6539
  clippy_lints/src/zero_sized_map_values.rs
  tests/ui/crashes/ice-6539.rs
Labels: S-waiting-on-review

#6528 New lint: redundant_slicing
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/map_unit_fn.rs
  clippy_lints/src/redundant_slicing.rs
  tests/ui/redundant_slicing.rs
  tests/ui/redundant_slicing.stderr
Labels: S-waiting-on-review

#6585 Explicitly document false positives
  clippy_lints/src/await_holding_invalid.rs
Labels: S-waiting-on-review

#6606 Add test for `needless_return` lint
  tests/ui/needless_return.fixed
  tests/ui/needless_return.rs
  tests/ui/needless_return.stderr
Labels: S-waiting-on-review

#6608 Add a note to `as_conversions`
  clippy_lints/src/as_conversions.rs
Labels: S-waiting-on-review

#6577 New Lint: inspect_then_for_each
  CHANGELOG.md
  clippy_lints/src/lib.rs
  clippy_lints/src/methods/inspect_for_each.rs
  clippy_lints/src/methods/mod.rs
  tests/ui/inspect_for_each.rs
  tests/ui/inspect_for_each.stderr
Labels: S-waiting-on-author

#6578 size_of_in_element_count: Disable lint on division by byte-size
  clippy_lints/src/size_of_in_element_count.rs
  tests/ui/size_of_in_element_count/expressions.rs
  tests/ui/size_of_in_element_count/expressions.stderr
  tests/ui/size_of_in_element_count/functions.rs
  tests/ui/size_of_in_element_count/functions.stderr
Labels: S-waiting-on-review

#6475 Add new lint `upper_case_acronyms`
  CHANGELOG.md
  clippy_lints/src/cognitive_complexity.rs
  clippy_lints/src/int_plus_one.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/serde_api.rs
  clippy_lints/src/upper_case_acronyms.rs
  tests/ui/complex_types.rs
  tests/ui/complex_types.stderr
  tests/ui/crashes/ice-6256.rs
  tests/ui/crashes/ice-6256.stderr
  tests/ui/enum_variants.rs
  tests/ui/needless_question_mark.fixed
  tests/ui/needless_question_mark.rs
  tests/ui/needless_question_mark.stderr
  tests/ui/suspicious_operation_groupings.rs
  tests/ui/transmute_ptr_to_ptr.rs
  tests/ui/unnested_or_patterns.fixed
  tests/ui/unnested_or_patterns.rs
  tests/ui/upper_case_acronyms.rs
  tests/ui/upper_case_acronyms.stderr
  tests/ui/use_self.fixed
  tests/ui/use_self.rs
Labels: S-waiting-on-author

#6567 Fix path_to_res for enum inherent items
  clippy_lints/src/utils/mod.rs
  tests/ui-internal/invalid_paths.rs
Labels: S-waiting-on-review

#6611 Fix the reversed suggestion message of `stable_sort_primitive`.
  clippy_lints/src/stable_sort_primitive.rs
  tests/ui/stable_sort_primitive.stderr
Labels: S-waiting-on-review

#6532 match_like_matches_macro: strip refs in suggestion
  clippy_lints/src/matches.rs
  tests/ui/match_expr_like_matches_macro.fixed
  tests/ui/match_expr_like_matches_macro.rs
  tests/ui/match_expr_like_matches_macro.stderr
Labels: S-waiting-on-review

#6605 Doc markdown
  clippy_lints/src/utils/conf.rs
  tests/ui/doc.rs
  tests/ui/doc.stderr
Labels: S-waiting-on-review

#6609 Fix a wrong suggestion of `ref_in_deref`
  clippy_lints/src/reference.rs
  tests/ui/unnecessary_ref.fixed
  tests/ui/unnecessary_ref.rs
  tests/ui/unnecessary_ref.stderr
Labels: S-waiting-on-review

#6621 Improve the example in `ref_in_deref`
  clippy_lints/src/reference.rs
Labels: S-waiting-on-review

#6591 `manual_filter_map` and `manual_find_map`
  CHANGELOG.md
  clippy_dev/src/ra_setup.rs
  clippy_lints/src/deprecated_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/loops.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/utils/hir_utils.rs
  tests/ui/filter_methods.stderr
  tests/ui/find_map.stderr
  tests/ui/manual_filter_map.fixed
  tests/ui/manual_filter_map.rs
  tests/ui/manual_filter_map.stderr
  tests/ui/manual_find_map.fixed
  tests/ui/manual_find_map.rs
  tests/ui/manual_find_map.stderr
Labels: S-waiting-on-review

#6619 Improve collapsible_match
  clippy_lints/src/collapsible_match.rs
  clippy_lints/src/main_recursion.rs
  clippy_lints/src/ptr.rs
  clippy_lints/src/utils/higher.rs
  clippy_lints/src/utils/mod.rs
  tests/ui/collapsible_match2.rs
  tests/ui/collapsible_match2.stderr
Labels: S-waiting-on-review

#6403 Similar names ignore underscore prefixed names
  clippy_lints/src/non_expressive_names.rs
  tests/ui/similar_names.rs
Labels: S-waiting-on-review

#6630 Documentation for adding configuration to a lint and common abbreviations
  doc/adding_lints.md
  doc/basics.md
Labels: S-waiting-on-review

#6617 New lint: exhaustive_enums, exhaustive_structs
  CHANGELOG.md
  clippy_lints/src/exhaustive_items.rs
  clippy_lints/src/lib.rs
  tests/ui/exhaustive_items.fixed
  tests/ui/exhaustive_items.rs
  tests/ui/exhaustive_items.stderr
Labels: S-waiting-on-review

#6469 add "cargo dev crater" to run clippy on a fixed set of crates and diff the lint warnings
  .cargo/config
  clippy_dev/Cargo.toml
  clippy_dev/lintcheck_crates.toml
  clippy_dev/src/lib.rs
  clippy_dev/src/lintcheck.rs
  clippy_dev/src/main.rs
  lintcheck-logs/logs.txt
Labels: C-needs-discussion, S-waiting-on-review

#6645 Fix website syntax highlighting
  util/export.py
Labels: S-waiting-on-review

#6654 No lazy static regex
  clippy_lints/Cargo.toml
  clippy_lints/src/case_sensitive_file_extension_comparisons.rs
  clippy_lints/src/utils/diagnostics.rs
Labels: S-waiting-on-review

#6656 clippy_dev: Pass stderr to CommandFailed
  clippy_dev/src/fmt.rs
Labels: S-waiting-on-review

#6603 Do not lint when range is completely included into another one
  clippy_lints/src/matches.rs
  tests/ui/match_overlapping_arm.rs
  tests/ui/match_overlapping_arm.stderr
Labels: S-waiting-on-author
