Repository rust-lang/rust-clippy, pull requests merged in 2022-05, with the labels that each got.

#8730 [FP] identity_op in front of if
  clippy_lints/src/identity_op.rs
  tests/ui/identity_op.rs
  tests/ui/identity_op.stderr
Labels: S-waiting-on-review

#8783 Move only_used_in_recursion to nursery
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_complexity.rs
  clippy_lints/src/lib.register_nursery.rs
  clippy_lints/src/only_used_in_recursion.rs
Labels: S-waiting-on-review

#8779 Easier readability for `needless_late_init` message
  clippy_lints/src/needless_late_init.rs
  tests/ui/needless_late_init.stderr
  tests/ui/needless_late_init_fixable.stderr
Labels: S-waiting-on-review

#8780 Ignore type aliases in `init_numbered_fields`
  clippy_lints/src/init_numbered_fields.rs
  tests/ui/numbered_fields.fixed
  tests/ui/numbered_fields.rs
Labels: S-waiting-on-review

#8575 add `trim_split_whitespace`
  CHANGELOG.md
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_style.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/strings.rs
  tests/ui/trim_split_whitespace.fixed
  tests/ui/trim_split_whitespace.rs
  tests/ui/trim_split_whitespace.stderr
Labels: S-waiting-on-review

#8789 Added missing `### What it does`
  clippy_lints/src/casts/mod.rs
Labels: S-waiting-on-review

#8790 Lint `empty_lint_after_outer_attr` on argumentless macros
  clippy_lints/src/attrs.rs
Labels: S-waiting-on-review

#8778 Fix `cast_lossless` to avoid warning on `usize` to `f64` conversion.
  clippy_lints/src/casts/cast_lossless.rs
  tests/ui/cast_size_32bit.stderr
Labels: S-waiting-on-review

#8793 Pass through extra args in `cargo dev lint`
  clippy_dev/src/lint.rs
  clippy_dev/src/main.rs
Labels: S-waiting-on-review

#8794 Address `unnecessary_to_owned` false positive
  clippy_lints/src/methods/unnecessary_to_owned.rs
  tests/ui/recursive_format_impl.stderr
  tests/ui/unnecessary_to_owned.fixed
  tests/ui/unnecessary_to_owned.rs
  tests/ui/unnecessary_to_owned.stderr
Labels: S-waiting-on-review

#8802 Optionally allow `expect` and `unwrap` in tests
  clippy_lints/src/approx_const.rs
  clippy_lints/src/attrs.rs
  clippy_lints/src/borrow_as_ptr.rs
  clippy_lints/src/casts/cast_abs_to_unsigned.rs
  clippy_lints/src/casts/cast_lossless.rs
  clippy_lints/src/casts/cast_slice_different_sizes.rs
  clippy_lints/src/casts/mod.rs
  clippy_lints/src/casts/ptr_as_ptr.rs
  clippy_lints/src/checked_conversions.rs
  clippy_lints/src/from_over_into.rs
  clippy_lints/src/if_then_some_else_none.rs
  clippy_lints/src/index_refutable_slice.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_bits.rs
  clippy_lints/src/manual_non_exhaustive.rs
  clippy_lints/src/manual_strip.rs
  clippy_lints/src/map_clone.rs
  clippy_lints/src/matches/mod.rs
  clippy_lints/src/mem_replace.rs
  clippy_lints/src/methods/cloned_instead_of_copied.rs
  clippy_lints/src/methods/err_expect.rs
  clippy_lints/src/methods/expect_used.rs
  clippy_lints/src/methods/filter_map_next.rs
  clippy_lints/src/methods/is_digit_ascii_radix.rs
  clippy_lints/src/methods/map_unwrap_or.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/option_as_ref_deref.rs
  clippy_lints/src/methods/str_splitn.rs
  clippy_lints/src/methods/unnecessary_to_owned.rs
  clippy_lints/src/methods/unwrap_used.rs
  clippy_lints/src/missing_const_for_fn.rs
  clippy_lints/src/ranges.rs
  clippy_lints/src/redundant_field_names.rs
  clippy_lints/src/redundant_static_lifetimes.rs
  clippy_lints/src/unnested_or_patterns.rs
  clippy_lints/src/use_self.rs
  clippy_lints/src/utils/conf.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/qualify_min_const_fn.rs
  doc/adding_lints.md
  tests/ui-toml/expect_used/clippy.toml
  tests/ui-toml/expect_used/expect_used.rs
  tests/ui-toml/expect_used/expect_used.stderr
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
  tests/ui-toml/unwrap_used/clippy.toml
  tests/ui-toml/unwrap_used/unwrap_used.rs
  tests/ui-toml/unwrap_used/unwrap_used.stderr
Labels: S-waiting-on-review

#8805 Recommend let chains over if_chain in docs
  CONTRIBUTING.md
  clippy_lints/src/bit_mask.rs
  doc/adding_lints.md
  doc/common_tools_writing_lints.md
Labels: S-waiting-on-review

#8797 Replace `#[allow]` with `#[expect]` in Clippy
  clippy_lints/src/booleans.rs
  clippy_lints/src/cognitive_complexity.rs
  clippy_lints/src/default.rs
  clippy_lints/src/default_numeric_fallback.rs
  clippy_lints/src/dereference.rs
  clippy_lints/src/doc.rs
  clippy_lints/src/double_comparison.rs
  clippy_lints/src/entry.rs
  clippy_lints/src/enum_clike.rs
  clippy_lints/src/enum_variants.rs
  clippy_lints/src/eq_op.rs
  clippy_lints/src/floating_point_arithmetic.rs
  clippy_lints/src/implicit_hasher.rs
  clippy_lints/src/implicit_return.rs
  clippy_lints/src/int_plus_one.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/literal_representation.rs
  clippy_lints/src/loops/mod.rs
  clippy_lints/src/loops/needless_range_loop.rs
  clippy_lints/src/loops/while_let_on_iterator.rs
  clippy_lints/src/macro_use.rs
  clippy_lints/src/manual_map.rs
  clippy_lints/src/manual_non_exhaustive.rs
  clippy_lints/src/matches/match_same_arms.rs
  clippy_lints/src/matches/match_single_binding.rs
  clippy_lints/src/matches/match_wild_enum.rs
  clippy_lints/src/matches/redundant_pattern_match.rs
  clippy_lints/src/misc.rs
  clippy_lints/src/needless_pass_by_value.rs
  clippy_lints/src/neg_multiply.rs
  clippy_lints/src/new_without_default.rs
  clippy_lints/src/non_expressive_names.rs
  clippy_lints/src/pass_by_ref_or_value.rs
  clippy_lints/src/pattern_type_mismatch.rs
  clippy_lints/src/ptr.rs
  clippy_lints/src/redundant_clone.rs
  clippy_lints/src/reference.rs
  clippy_lints/src/regex.rs
  clippy_lints/src/uninit_vec.rs
  clippy_lints/src/unused_unit.rs
  clippy_lints/src/useless_conversion.rs
  clippy_lints/src/vec.rs
  clippy_lints/src/write.rs
  clippy_utils/src/ast_utils.rs
  clippy_utils/src/attrs.rs
  clippy_utils/src/consts.rs
  clippy_utils/src/eager_or_lazy.rs
  clippy_utils/src/hir_utils.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/paths.rs
  clippy_utils/src/source.rs
  clippy_utils/src/sugg.rs
  clippy_utils/src/ty.rs
  clippy_utils/src/usage.rs
Labels: S-needs-discussion

#8809 Ignore unfulfilled_lint_expectations in metadata collection
  tests/dogfood.rs
Labels: S-waiting-on-review

#8769 introduce rc_clone_in_vec_init lint
  CHANGELOG.md
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_suspicious.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/rc_clone_in_vec_init.rs
  tests/ui/rc_clone_in_vec_init/arc.rs
  tests/ui/rc_clone_in_vec_init/arc.stderr
  tests/ui/rc_clone_in_vec_init/rc.rs
  tests/ui/rc_clone_in_vec_init/rc.stderr
Labels: S-waiting-on-review

#8796 New lint: [`derive_partial_eq_without_eq`]
  CHANGELOG.md
  clippy_dev/src/update_lints.rs
  clippy_lints/src/checked_conversions.rs
  clippy_lints/src/derive.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_style.rs
  clippy_lints/src/loops/utils.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/str_splitn.rs
  clippy_utils/src/numeric_literal.rs
  tests/ui/absurd-extreme-comparisons.rs
  tests/ui/assign_ops2.rs
  tests/ui/cmp_owned/asymmetric_partial_eq.fixed
  tests/ui/cmp_owned/asymmetric_partial_eq.rs
  tests/ui/cmp_owned/with_suggestion.fixed
  tests/ui/cmp_owned/with_suggestion.rs
  tests/ui/cmp_owned/without_suggestion.rs
  tests/ui/crashes/ice-6254.rs
  tests/ui/crashes/ice-6254.stderr
  tests/ui/derive_hash_xor_eq.rs
  tests/ui/derive_hash_xor_eq.stderr
  tests/ui/derive_partial_eq_without_eq.fixed
  tests/ui/derive_partial_eq_without_eq.rs
  tests/ui/derive_partial_eq_without_eq.stderr
  tests/ui/equatable_if_let.fixed
  tests/ui/equatable_if_let.rs
  tests/ui/unit_cmp.rs
  tests/ui/unit_cmp.stderr
Labels: S-waiting-on-review

#8818 Use the traits added to the Rust 2021 Edition prelude
  clippy_lints/src/checked_conversions.rs
  clippy_lints/src/enum_clike.rs
  clippy_lints/src/excessive_bools.rs
  clippy_lints/src/fallible_impl_from.rs
  clippy_lints/src/index_refutable_slice.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/redundant_clone.rs
  clippy_lints/src/regex.rs
  clippy_lints/src/tabs_in_doc_comments.rs
  clippy_utils/src/consts.rs
  clippy_utils/src/sugg.rs
  tests/ui-toml/unwrap_used/unwrap_used.rs
  tests/ui-toml/unwrap_used/unwrap_used.stderr
  tests/ui/auxiliary/proc_macro_suspicious_else_formatting.rs
  tests/ui/checked_conversions.fixed
  tests/ui/checked_conversions.rs
  tests/ui/checked_conversions.stderr
  tests/ui/crashes/auxiliary/proc_macro_crash.rs
  tests/ui/from_iter_instead_of_collect.fixed
  tests/ui/from_iter_instead_of_collect.rs
  tests/ui/from_iter_instead_of_collect.stderr
  tests/ui/get_unwrap.fixed
  tests/ui/get_unwrap.rs
  tests/ui/get_unwrap.stderr
  tests/ui/infinite_iter.rs
  tests/ui/infinite_iter.stderr
  tests/ui/manual_str_repeat.fixed
  tests/ui/manual_str_repeat.rs
  tests/ui/map_err.rs
  tests/ui/map_err.stderr
  tests/ui/methods.rs
  tests/ui/methods.stderr
  tests/ui/useless_conversion_try.rs
  tests/ui/useless_conversion_try.stderr
Labels: S-waiting-on-review

#8799 Some lintcheck cleanup
  lintcheck/Cargo.toml
  lintcheck/lintcheck_crates.toml
  lintcheck/src/config.rs
  lintcheck/src/main.rs
Labels: S-waiting-on-review

#8825 Tweak some words improved representation
  clippy_dev/src/main.rs
  clippy_dev/src/new_lint.rs
  clippy_lints/src/assign_ops.rs
  clippy_lints/src/casts/cast_slice_different_sizes.rs
  clippy_lints/src/casts/mod.rs
  clippy_lints/src/default_union_representation.rs
  clippy_lints/src/derive.rs
  clippy_lints/src/main_recursion.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/mutable_debug_assertion.rs
  clippy_lints/src/needless_bitwise_bool.rs
  clippy_lints/src/pass_by_ref_or_value.rs
  clippy_lints/src/redundant_clone.rs
  clippy_lints/src/transmute/mod.rs
  doc/adding_lints.md
  tests/ui/blacklisted_name.rs
Labels: S-waiting-on-review

#8832 Add `duplicate_mod` lint
  CHANGELOG.md
  clippy_lints/src/duplicate_mod.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_suspicious.rs
  clippy_lints/src/lib.rs
  clippy_utils/src/diagnostics.rs
  tests/ui-cargo/duplicate_mod/fail/Cargo.toml
  tests/ui-cargo/duplicate_mod/fail/src/a.rs
  tests/ui-cargo/duplicate_mod/fail/src/b.rs
  tests/ui-cargo/duplicate_mod/fail/src/c.rs
  tests/ui-cargo/duplicate_mod/fail/src/from_other_module.rs
  tests/ui-cargo/duplicate_mod/fail/src/main.rs
  tests/ui-cargo/duplicate_mod/fail/src/main.stderr
  tests/ui-cargo/duplicate_mod/fail/src/other_module/mod.rs
Labels: S-waiting-on-review

#8621 Rename `eval_order_dependence` to `mixed_read_write_expression`, move to nursery
  CHANGELOG.md
  clippy_dev/src/update_lints.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_complexity.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_restriction.rs
  clippy_lints/src/lib.register_suspicious.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/mixed_read_write_in_expression.rs
  clippy_lints/src/renamed_lints.rs
  tests/ui/branches_sharing_code/shared_at_top.rs
  tests/ui/branches_sharing_code/valid_if_blocks.rs
  tests/ui/mixed_read_write_in_expression.rs
  tests/ui/mixed_read_write_in_expression.stderr
  tests/ui/rename.fixed
  tests/ui/rename.rs
  tests/ui/rename.stderr
  tests/ui/self_assignment.rs
Labels: S-waiting-on-review

#8699 Don't lint `vec_init_then_push` when further extended
  clippy_lints/src/vec_init_then_push.rs
  clippy_utils/src/higher.rs
  clippy_utils/src/visitors.rs
  tests/ui/vec_init_then_push.rs
  tests/ui/vec_init_then_push.stderr
Labels: S-waiting-on-author

#8761 `undocumented_unsafe_blocks` does not trigger on unsafe trait impls
  clippy_lints/src/undocumented_unsafe_blocks.rs
  tests/ui/undocumented_unsafe_blocks.rs
  tests/ui/undocumented_unsafe_blocks.stderr
Labels: S-waiting-on-review

#8835 Fix ICE in `let_unit_value` when calling a static or const callable type
  clippy_lints/src/unit_types/let_unit_value.rs
  tests/ui/crashes/ice-8821.rs
  tests/ui/crashes/ice-8821.stderr
Labels: S-waiting-on-review

#8814 add suggestions to rc_clone_in_vec_init
  clippy_lints/src/rc_clone_in_vec_init.rs
  tests/ui/rc_clone_in_vec_init/arc.rs
  tests/ui/rc_clone_in_vec_init/arc.stderr
  tests/ui/rc_clone_in_vec_init/rc.rs
  tests/ui/rc_clone_in_vec_init/rc.stderr
Labels: S-waiting-on-review

#8807 Fix `cmp_owned` on copy types
  clippy_lints/src/misc.rs
  tests/ui/cmp_owned/without_suggestion.rs
  tests/ui/cmp_owned/without_suggestion.stderr
Labels: S-waiting-on-review

#8823 Improve "unknown field" error messages
  Cargo.toml
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/conf.rs
  src/main.rs
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
Labels: S-waiting-on-review

#8839 Add copy lint name button
  util/gh-pages/index.html
  util/gh-pages/script.js
Labels: S-waiting-on-review

#8838 [dbg_macro] tolerates use of `dbg!` in items which have `#[cfg(test)]` attribute
  clippy_lints/src/dbg_macro.rs
  clippy_utils/src/lib.rs
  tests/ui/dbg_macro.rs
Labels: S-waiting-on-review

#8840 Mini changelog update for Rust 1.61.0
  CHANGELOG.md
Labels: S-waiting-on-review

#8841 Remove code block from `pub_enum_variant_names`
  clippy_lints/src/deprecated_lints.rs
Labels: S-waiting-on-review

#8848 Auto-detect preferred colorscheme
  util/gh-pages/script.js
Labels: S-waiting-on-review

#8870 Strip `clippy::` prefix from search strings
  util/gh-pages/script.js
Labels: S-waiting-on-review

#8872 update dependencies
  Cargo.toml
  clippy_dev/Cargo.toml
  clippy_dev/src/main.rs
  clippy_dev/src/serve.rs
  lintcheck/Cargo.toml
  lintcheck/src/config.rs
Labels: S-waiting-on-review

#8881 Fix imports for "Checking if a type defines a specific method"
  doc/common_tools_writing_lints.md
Labels: S-waiting-on-review

#8880 Add some testcases for recent rustfix update
  tests/ui/map_flatten_fixable.fixed
  tests/ui/map_flatten_fixable.rs
  tests/ui/map_flatten_fixable.stderr
Labels: S-waiting-on-review

#8862 `get_last_with_len`: lint `VecDeque` and any deref to slice
  clippy_lints/src/get_last_with_len.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_complexity.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/methods/get_last_with_len.rs
  clippy_lints/src/methods/mod.rs
  tests/ui/get_last_with_len.fixed
  tests/ui/get_last_with_len.rs
  tests/ui/get_last_with_len.stderr
Labels: S-waiting-on-review

#8882 feat(lint): impl lint about use first() instead of get(0)
  CHANGELOG.md
  clippy_lints/src/get_first.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_style.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/methods/iter_next_slice.rs
  clippy_utils/src/paths.rs
  tests/ui-toml/unwrap_used/unwrap_used.rs
  tests/ui/debug_assert_with_mut_call.rs
  tests/ui/get_first.fixed
  tests/ui/get_first.rs
  tests/ui/get_first.stderr
  tests/ui/get_unwrap.fixed
  tests/ui/get_unwrap.rs
  tests/ui/iter_next_slice.fixed
  tests/ui/iter_next_slice.rs
  tests/ui/iter_next_slice.stderr
  tests/ui/needless_lifetimes.rs
  tests/ui/needless_lifetimes.stderr
Labels: S-waiting-on-review

#8889 Remove newlines in [`match_str_case_mismatch`] example
  clippy_lints/src/match_str_case_mismatch.rs
Labels: S-waiting-on-review

#8866 Add new lint `[unused_rounding]`
  CHANGELOG.md
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_nursery.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/unused_rounding.rs
  tests/ui/unused_rounding.fixed
  tests/ui/unused_rounding.rs
  tests/ui/unused_rounding.stderr
Labels: S-waiting-on-review

#8896 Only return `DefId`s to `Fn`-like definitions in `clippy_utils::fn_def_id`
  clippy_utils/src/lib.rs
  tests/ui/crashes/ice-8850.rs
  tests/ui/crashes/ice-8850.stderr
Labels: S-waiting-on-review

#8885 Support `Weak` in [`rc_clone_in_vec_init`]
  clippy_lints/src/rc_clone_in_vec_init.rs
  tests/ui/rc_clone_in_vec_init/arc.stderr
  tests/ui/rc_clone_in_vec_init/rc.stderr
  tests/ui/rc_clone_in_vec_init/weak.rs
  tests/ui/rc_clone_in_vec_init/weak.stderr
Labels: S-waiting-on-review

#8892 Fix `empty_line_after_outer_attribute` false positive
  Cargo.toml
  clippy_lints/src/attrs.rs
  tests/compile-test.rs
  tests/ui/empty_line_after_outer_attribute.rs
  tests/ui/empty_line_after_outer_attribute.stderr
Labels: S-waiting-on-review

#8385 add doc_link_with_quotes lint
  CHANGELOG.md
  clippy_lints/src/doc_link_with_quotes.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_pedantic.rs
  clippy_lints/src/lib.rs
  tests/ui/doc_link_with_quotes.rs
  tests/ui/doc_link_with_quotes.stderr
Labels: S-waiting-on-review

#8899 Fix `[use_self]` false negative with on struct and tuple struct patterns
  clippy_lints/src/use_self.rs
  tests/ui/use_self.fixed
  tests/ui/use_self.rs
  tests/ui/use_self.stderr
Labels: S-waiting-on-review

#8913 Fix #8748
  clippy_lints/src/shadow.rs
  tests/ui/shadow.rs
Labels: S-waiting-on-review

#8912 needless_late_init: fix ICE when all branches return the never type
  clippy_lints/src/needless_late_init.rs
  tests/ui/needless_late_init.fixed
  tests/ui/needless_late_init.rs
  tests/ui/needless_late_init.stderr
Labels: S-waiting-on-review

#8918 Add lint `almost_complete_letter_range`
  CHANGELOG.md
  clippy_lints/src/almost_complete_letter_range.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_suspicious.rs
  clippy_lints/src/lib.rs
  clippy_utils/src/msrvs.rs
  clippy_utils/src/source.rs
  tests/ui/almost_complete_letter_range.fixed
  tests/ui/almost_complete_letter_range.rs
  tests/ui/almost_complete_letter_range.stderr
Labels: S-waiting-on-review

#8876 `cast_abs_to_unsigned`: do not remove cast if it's required
  clippy_lints/src/casts/cast_abs_to_unsigned.rs
  tests/ui/cast_abs_to_unsigned.fixed
  tests/ui/cast_abs_to_unsigned.rs
  tests/ui/cast_abs_to_unsigned.stderr
Labels: S-waiting-on-review

#8884 Fix `manual_range_contains` false negative with chains of `&&` and `||`
  clippy_lints/src/ranges.rs
  tests/ui/range_contains.fixed
  tests/ui/range_contains.rs
  tests/ui/range_contains.stderr
Labels: S-waiting-on-review
