Repository rust-lang/rust-clippy, pull requests merged in 2022-12, with the labels that each got.

#10007 Fix ICE in `result_large_err` with uninhabited enums
  clippy_lints/src/functions/result.rs
  tests/ui/result_large_err.rs
Labels: S-waiting-on-review

#10010 Rustup
  clippy_dev/src/setup/git_hook.rs
  clippy_lints/src/attrs.rs
  clippy_lints/src/bool_assert_comparison.rs
  clippy_lints/src/casts/cast_possible_truncation.rs
  clippy_lints/src/crate_in_macro_def.rs
  clippy_lints/src/dereference.rs
  clippy_lints/src/derive.rs
  clippy_lints/src/doc.rs
  clippy_lints/src/eta_reduction.rs
  clippy_lints/src/future_not_send.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/lifetimes.rs
  clippy_lints/src/manual_async_fn.rs
  clippy_lints/src/matches/match_wild_enum.rs
  clippy_lints/src/matches/try_err.rs
  clippy_lints/src/methods/iter_overeager_cloned.rs
  clippy_lints/src/methods/unnecessary_iter_cloned.rs
  clippy_lints/src/methods/unnecessary_to_owned.rs
  clippy_lints/src/needless_pass_by_value.rs
  clippy_lints/src/neg_cmp_op_on_partial_ord.rs
  clippy_lints/src/ptr.rs
  clippy_lints/src/suspicious_operation_groupings.rs
  clippy_lints/src/types/borrowed_box.rs
  clippy_lints/src/unit_return_expecting_ord.rs
  clippy_lints/src/utils/internal_lints/unnecessary_def_path.rs
  clippy_utils/src/ast_utils.rs
  clippy_utils/src/eager_or_lazy.rs
  clippy_utils/src/hir_utils.rs
  clippy_utils/src/paths.rs
  clippy_utils/src/qualify_min_const_fn.rs
  clippy_utils/src/ty.rs
  declare_clippy_lint/Cargo.toml
  declare_clippy_lint/src/lib.rs
  rust-toolchain
  src/driver.rs
  tests/ui-internal/unnecessary_def_path_hardcoded_path.stderr
  tests/ui/async_yields_async.stderr
  tests/ui/author/blocks.stdout
  tests/ui/result_map_unit_fn_unfixable.stderr
Labels: S-waiting-on-review

#10012 Don't lint `string_lit_as_bytes` in match scrutinees
  clippy_lints/src/strings.rs
  tests/ui/string_lit_as_bytes.fixed
  tests/ui/string_lit_as_bytes.rs
Labels: S-waiting-on-review

#9966 Fix manual_let_else produces a wrong suggestion with or-patterns
  clippy_lints/src/manual_let_else.rs
  tests/ui/manual_let_else_match.rs
  tests/ui/manual_let_else_match.stderr
Labels: S-waiting-on-review

#10006 Don't suggest removing `mut` from references in `redundant_static_lifetimes`
  clippy_lints/src/redundant_static_lifetimes.rs
  tests/ui/redundant_static_lifetimes.fixed
  tests/ui/redundant_static_lifetimes.rs
  tests/ui/redundant_static_lifetimes.stderr
Labels: S-waiting-on-review

#10008 Treat custom enum discriminant values as constants
  clippy_utils/src/lib.rs
  tests/ui/cast_lossless_integer.fixed
  tests/ui/cast_lossless_integer.rs
Labels: S-waiting-on-review

#10013 Don't lint `manual_assert` in `else if`
  clippy_lints/src/manual_assert.rs
  tests/ui/manual_assert.edition2018.fixed
  tests/ui/manual_assert.edition2021.fixed
  tests/ui/manual_assert.edition2021.stderr
  tests/ui/manual_assert.rs
Labels: S-waiting-on-review

#9982 Don't lint `from_over_into` for opaque types
  clippy_lints/src/from_over_into.rs
  tests/ui/from_over_into.fixed
  tests/ui/from_over_into.rs
  tests/ui/from_over_into.stderr
Labels: S-waiting-on-review

#9962 `comparison_to_empty`: peel derefs in suggestions
  clippy_lints/src/len_zero.rs
  tests/ui/len_zero.fixed
  tests/ui/len_zero.rs
  tests/ui/len_zero.stderr
Labels: S-waiting-on-review

#10022 Don't lint `implicit_clone` when the type doesn't implement clone
  clippy_lints/src/methods/implicit_clone.rs
  tests/ui/implicit_clone.fixed
  tests/ui/implicit_clone.rs
Labels: S-waiting-on-review

#10026 Add missing slash to produce function documentation
  clippy_utils/src/ty.rs
Labels: S-waiting-on-review

#10023 Fix `zero_ptr` suggestion for `no_std` crates
  clippy_lints/src/lib.rs
  clippy_lints/src/misc.rs
  tests/ui/zero_ptr_no_std.fixed
  tests/ui/zero_ptr_no_std.rs
  tests/ui/zero_ptr_no_std.stderr
Labels: S-waiting-on-bors

#10036 Add beta-nominated label to triagebot
  triagebot.toml
Labels: S-waiting-on-bors

#9840 [`arithmetic-side-effects`]: Consider user-provided pairs
  clippy_lints/src/lib.rs
  clippy_lints/src/operators/arithmetic_side_effects.rs
  clippy_lints/src/operators/mod.rs
  clippy_lints/src/utils/conf.rs
  tests/ui-toml/arithmetic_side_effects_allowed/arithmetic_side_effects_allowed.rs
  tests/ui-toml/arithmetic_side_effects_allowed/arithmetic_side_effects_allowed.stderr
  tests/ui-toml/arithmetic_side_effects_allowed/clippy.toml
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
  tests/ui/arithmetic_side_effects.stderr
Labels: S-waiting-on-review

#9826 Add semicolon-outside/inside-block lints
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/semicolon_block.rs
  tests/ui/semicolon_inside_block.fixed
  tests/ui/semicolon_inside_block.rs
  tests/ui/semicolon_inside_block.stderr
  tests/ui/semicolon_outside_block.fixed
  tests/ui/semicolon_outside_block.rs
  tests/ui/semicolon_outside_block.stderr
Labels: S-waiting-on-review

#10004 Don't suggest keeping borrows in `identity_op`
  clippy_lints/src/operators/identity_op.rs
  tests/ui/identity_op.fixed
  tests/ui/identity_op.rs
  tests/ui/identity_op.stderr
Labels: S-waiting-on-review

#10047 Add 1.58 MSRV for `collapsible_str_replace`
  clippy_lints/src/methods/mod.rs
  clippy_utils/src/msrvs.rs
  tests/ui/collapsible_str_replace.fixed
  tests/ui/collapsible_str_replace.rs
  tests/ui/collapsible_str_replace.stderr
Labels: S-waiting-on-review

#10043 Add lint `almost_complete_digit_range`
  CHANGELOG.md
  clippy_lints/src/almost_complete_range.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/renamed_lints.rs
  tests/ui/almost_complete_letter_range.stderr
  tests/ui/almost_complete_range.fixed
  tests/ui/almost_complete_range.rs
  tests/ui/almost_complete_range.stderr
  tests/ui/auxiliary/macro_rules.rs
  tests/ui/needless_parens_on_range_literals.fixed
  tests/ui/needless_parens_on_range_literals.rs
  tests/ui/rename.fixed
  tests/ui/rename.rs
  tests/ui/rename.stderr
Labels: S-waiting-on-review

#10055 uninlined_format_args: Ignore assert! and debug_assert! before 2021 edition
  clippy_lints/src/format_args.rs
  clippy_utils/src/macros.rs
  tests/ui/uninlined_format_args_panic.edition2018.fixed
  tests/ui/uninlined_format_args_panic.edition2021.fixed
  tests/ui/uninlined_format_args_panic.edition2021.stderr
  tests/ui/uninlined_format_args_panic.rs
Labels: S-waiting-on-review

#10059 Fix badge
  book/src/README.md
Labels: S-waiting-on-review

#10053 improve `manual_is_ascii_check ` check
  clippy_lints/src/manual_is_ascii_check.rs
  tests/ui/manual_is_ascii_check.fixed
  tests/ui/manual_is_ascii_check.rs
  tests/ui/manual_is_ascii_check.stderr
Labels: S-waiting-on-review

#9927 Cleanup `rustc_tool_util` and add a convenient macro for `build.rs`
  Cargo.toml
  build.rs
  rustc_tools_util/CHANGELOG.md
  rustc_tools_util/Cargo.toml
  rustc_tools_util/README.md
  rustc_tools_util/src/lib.rs
  src/driver.rs
  src/main.rs
  tests/versioncheck.rs
Labels: S-waiting-on-review

#10073 Changelog 1.66
  CHANGELOG.md
  clippy_lints/src/box_default.rs
  clippy_lints/src/casts/mod.rs
  clippy_lints/src/disallowed_macros.rs
  clippy_lints/src/format_args.rs
  clippy_lints/src/implicit_saturating_add.rs
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-review

#10086 Fix new_return_no_self with recursive bounds
  clippy_utils/src/ty.rs
  tests/ui/new_ret_no_self.rs
  tests/ui/new_ret_no_self.stderr
Labels: S-waiting-on-review

#10094 fix logic in IncrementVisitor
  clippy_lints/src/loops/utils.rs
  tests/ui/explicit_counter_loop.rs
Labels: S-waiting-on-review

#10096 fix: not suggest seek_to_start_instead_of_rewind when expr is used
  clippy_lints/src/methods/seek_to_start_instead_of_rewind.rs
  tests/ui/seek_to_start_instead_of_rewind.fixed
  tests/ui/seek_to_start_instead_of_rewind.rs
  tests/ui/seek_to_start_instead_of_rewind.stderr
Labels: S-waiting-on-review

#10097 Rustup
  Cargo.toml
  clippy_lints/Cargo.toml
  clippy_lints/src/dereference.rs
  clippy_lints/src/derive.rs
  clippy_lints/src/disallowed_types.rs
  clippy_lints/src/from_over_into.rs
  clippy_lints/src/future_not_send.rs
  clippy_lints/src/invalid_utf8_in_unchecked.rs
  clippy_lints/src/large_include_file.rs
  clippy_lints/src/len_zero.rs
  clippy_lints/src/macro_use.rs
  clippy_lints/src/manual_retain.rs
  clippy_lints/src/matches/match_same_arms.rs
  clippy_lints/src/methods/needless_collect.rs
  clippy_lints/src/methods/option_map_unwrap_or.rs
  clippy_lints/src/missing_enforced_import_rename.rs
  clippy_lints/src/redundant_pub_crate.rs
  clippy_lints/src/single_component_path_imports.rs
  clippy_lints/src/unnecessary_self_imports.rs
  clippy_lints/src/unsafe_removed_from_name.rs
  clippy_lints/src/utils/author.rs
  clippy_lints/src/utils/internal_lints/invalid_paths.rs
  clippy_lints/src/utils/internal_lints/lint_without_lint_pass.rs
  clippy_lints/src/utils/internal_lints/metadata_collector.rs
  clippy_lints/src/wildcard_imports.rs
  clippy_utils/Cargo.toml
  clippy_utils/src/ast_utils.rs
  clippy_utils/src/check_proc_macro.rs
  clippy_utils/src/consts.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/paths.rs
  clippy_utils/src/qualify_min_const_fn.rs
  clippy_utils/src/ty.rs
  clippy_utils/src/usage.rs
  declare_clippy_lint/Cargo.toml
  rust-toolchain
  tests/ui-internal/unnecessary_def_path_hardcoded_path.stderr
  tests/ui/macro_use_imports.stderr
Labels: S-waiting-on-review

#10020 Identify more cases of useless `into_iter()` calls
  clippy_lints/src/useless_conversion.rs
  tests/ui/useless_conversion.fixed
  tests/ui/useless_conversion.rs
  tests/ui/useless_conversion.stderr
Labels: S-waiting-on-review

#10101 Move manual_clamp to nursery
  clippy_lints/src/manual_clamp.rs
Labels: S-waiting-on-review, beta-nominated

#10103 Fix overflow ICE in large_stack/const_arrays
  clippy_lints/src/large_const_arrays.rs
  clippy_lints/src/large_stack_arrays.rs
  clippy_lints/src/utils/conf.rs
  tests/ui/crashes/ice-10044.rs
  tests/ui/crashes/ice-10044.stderr
Labels: S-waiting-on-review

#10063 add [`permissions_set_readonly_false`] #9702
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/permissions_set_readonly_false.rs
  tests/ui/permissions_set_readonly_false.rs
  tests/ui/permissions_set_readonly_false.stderr
Labels: S-waiting-on-review

#10091 fix manual_filter false positive
  clippy_lints/src/matches/manual_filter.rs
  tests/ui/manual_filter.fixed
  tests/ui/manual_filter.rs
Labels: S-waiting-on-review

#10109 Fix FP in needless_return when using yeet
  clippy_lints/src/returns.rs
  tests/ui/needless_return.fixed
  tests/ui/needless_return.rs
  tests/ui/needless_return.stderr
Labels: S-waiting-on-review

#10056 Avoid `match_wildcard_for_single_variants` on guarded wild matches
  clippy_lints/src/matches/match_wild_enum.rs
  clippy_utils/src/sugg.rs
  tests/ui/match_wildcard_for_single_variants.fixed
  tests/ui/match_wildcard_for_single_variants.rs
  tests/ui/match_wildcard_for_single_variants.stderr
Labels: S-waiting-on-review

#9701 Improve `possible_borrower`
  clippy_lints/src/casts/cast_slice_different_sizes.rs
  clippy_lints/src/dereference.rs
  clippy_lints/src/format_args.rs
  clippy_lints/src/large_enum_variant.rs
  clippy_lints/src/len_zero.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/loops/explicit_counter_loop.rs
  clippy_lints/src/manual_async_fn.rs
  clippy_lints/src/manual_strip.rs
  clippy_lints/src/methods/inefficient_to_string.rs
  clippy_lints/src/methods/iter_skip_next.rs
  clippy_lints/src/methods/option_map_unwrap_or.rs
  clippy_lints/src/methods/str_splitn.rs
  clippy_lints/src/methods/unnecessary_lazy_eval.rs
  clippy_lints/src/needless_late_init.rs
  clippy_lints/src/octal_escapes.rs
  clippy_lints/src/operators/misrefactored_assign_op.rs
  clippy_lints/src/redundant_clone.rs
  clippy_lints/src/same_name_method.rs
  clippy_lints/src/swap.rs
  clippy_lints/src/transmute/transmute_undefined_repr.rs
  clippy_lints/src/transmute/transmutes_expressible_as_ptr_casts.rs
  clippy_lints/src/transmute/useless_transmute.rs
  clippy_lints/src/types/redundant_allocation.rs
  clippy_lints/src/unit_types/unit_arg.rs
  clippy_lints/src/write.rs
  clippy_utils/src/diagnostics.rs
  clippy_utils/src/mir/maybe_storage_live.rs
  clippy_utils/src/mir/mod.rs
  clippy_utils/src/mir/possible_borrower.rs
  tests/ui/manual_retain.fixed
  tests/ui/manual_retain.rs
  tests/ui/needless_borrow.fixed
  tests/ui/needless_borrow.rs
  tests/ui/needless_borrow.stderr
  tests/ui/redundant_clone.fixed
  tests/ui/redundant_clone.rs
  tests/ui/redundant_clone.stderr
Labels: S-waiting-on-review

#10111 Changelog fix
  CHANGELOG.md
Labels: S-waiting-on-review

#10098 Add size_of_ref lint
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/size_of_ref.rs
  tests/ui/size_of_ref.rs
  tests/ui/size_of_ref.stderr
Labels: S-waiting-on-review

#10116 `not_unsafe_ptr_arg_deref` update documentation
  clippy_lints/src/functions/mod.rs
Labels: S-waiting-on-review

#10113 fix incorrect suggestion in `suboptimal_flops`
  clippy_lints/src/floating_point_arithmetic.rs
  tests/ui/floating_point_powi.fixed
  tests/ui/floating_point_powi.rs
  tests/ui/floating_point_powi.stderr
Labels: S-waiting-on-review

#10119 fix codeblocks in the document
  clippy_lints/src/utils/internal_lints/metadata_collector.rs
Labels: S-waiting-on-review

#10060 Fix [match_single_binding] suggestion introduced an extra semicolon
  clippy_lints/src/matches/match_single_binding.rs
  tests/ui/match_single_binding.fixed
  tests/ui/match_single_binding.rs
  tests/ui/match_single_binding.stderr
Labels: S-waiting-on-review

#10126 Rustup
  CHANGELOG.md
  rust-toolchain
  tests/ui/borrow_interior_mutable_const/others.rs
Labels: S-waiting-on-review

#10115 Move `mutex_atomic` to `restriction`
  clippy_lints/src/mutex_atomic.rs
Labels: S-waiting-on-review
