Repository rust-lang/rust-clippy, pull requests merged in 2022-08, with the labels that each got.

#9223 unwrap_used: Don't recommend using `expect` when the `expect_used` lint is not allowed
  clippy_lints/src/methods/expect_used.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/unwrap_used.rs
  tests/ui-toml/expect_used/expect_used.stderr
  tests/ui/expect.stderr
  tests/ui/unwrap_expect_used.rs
  tests/ui/unwrap_expect_used.stderr
Labels: S-waiting-on-review

#9270 Make it easier to find the developer guide
  CONTRIBUTING.md
Labels: S-waiting-on-review

#9273 Move [`assertions_on_result_states`] to restriction
  clippy_lints/src/assertions_on_result_states.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_restriction.rs
  clippy_lints/src/lib.register_style.rs
  tests/ui/assertions_on_result_states.fixed
  tests/ui/assertions_on_result_states.rs
  tests/ui/assertions_on_result_states.stderr
Labels: S-waiting-on-review

#9254 Enable test empty_loop_no_std on windows
  tests/ui/empty_loop_no_std.rs
  tests/ui/empty_loop_no_std.stderr
Labels: S-waiting-on-review

#9279 chore: a few small improvements to code quality
  clippy_lints/src/checked_conversions.rs
  clippy_lints/src/create_dir.rs
  clippy_lints/src/from_str_radix_10.rs
  clippy_lints/src/loops/manual_memcpy.rs
  clippy_lints/src/loops/needless_range_loop.rs
  clippy_lints/src/manual_ok_or.rs
  clippy_lints/src/map_err_ignore.rs
  clippy_lints/src/map_unit_fn.rs
  clippy_lints/src/matches/match_as_ref.rs
  clippy_lints/src/matches/try_err.rs
  clippy_lints/src/mem_replace.rs
  clippy_lints/src/path_buf_push_overwrite.rs
  clippy_lints/src/question_mark.rs
  clippy_lints/src/ranges.rs
  clippy_lints/src/regex.rs
  clippy_lints/src/slow_vector_initialization.rs
  clippy_lints/src/stable_sort_primitive.rs
  clippy_lints/src/useless_conversion.rs
  clippy_lints/src/verbose_file_reads.rs
Labels: S-waiting-on-review

#9264 Add `elapsed_instant` lint
  CHANGELOG.md
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_pedantic.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_instant_elapsed.rs
  clippy_utils/src/paths.rs
  tests/ui/manual_instant_elapsed.fixed
  tests/ui/manual_instant_elapsed.rs
  tests/ui/manual_instant_elapsed.stderr
Labels: S-waiting-on-review

#9053 Fix suggestions for `async` closures in redundant_closure_call
  clippy_lints/src/redundant_closure_call.rs
  clippy_utils/src/sugg.rs
  tests/ui/redundant_closure_call_fixable.fixed
  tests/ui/redundant_closure_call_fixable.rs
  tests/ui/redundant_closure_call_fixable.stderr
Labels: S-waiting-on-review

#9282 add paren before '?' when suggesting deref for clone_on_copy
  clippy_lints/src/methods/clone_on_copy.rs
  tests/ui/clone_on_copy.fixed
  tests/ui/clone_on_copy.rs
  tests/ui/clone_on_copy.stderr
Labels: S-waiting-on-review

#9284 fix typo in tests/ui/redundant_allocation.rs
  tests/ui/redundant_allocation.rs
  tests/ui/redundant_allocation.stderr
Labels: S-waiting-on-review

#9266 Fix cast_abs_to_unsigned with code in parens
  clippy_lints/src/casts/cast_abs_to_unsigned.rs
  tests/ui/cast_abs_to_unsigned.fixed
  tests/ui/cast_abs_to_unsigned.rs
  tests/ui/cast_abs_to_unsigned.stderr
Labels: S-waiting-on-review

#9292 Fix some typos
  clippy_lints/src/missing_const_for_fn.rs
  clippy_lints/src/utils/internal_lints.rs
  tests/ui-internal/check_clippy_version_attribute.stderr
Labels: S-waiting-on-review

#9294 Enable test for def_id_nocore for windows
  tests/ui/def_id_nocore.rs
  tests/ui/def_id_nocore.stderr
Labels: S-waiting-on-review

#9302 Move `significant_drop_in_scrutinee` into `nursey`
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_nursery.rs
  clippy_lints/src/lib.register_suspicious.rs
  clippy_lints/src/matches/mod.rs
Labels: S-waiting-on-review

#8694 More proc-macro detection
  clippy_lints/src/default.rs
  clippy_lints/src/formatting.rs
  clippy_lints/src/matches/mod.rs
  clippy_lints/src/missing_doc.rs
  clippy_lints/src/unit_types/mod.rs
  clippy_lints/src/unit_types/unit_arg.rs
  clippy_utils/src/check_proc_macro.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/source.rs
  tests/ui/default_trait_access.fixed
  tests/ui/default_trait_access.rs
  tests/ui/default_trait_access.stderr
  tests/ui/missing_doc.rs
  tests/ui/missing_doc.stderr
  tests/ui/missing_doc_crate.rs
  tests/ui/missing_doc_crate_missing.rs
  tests/ui/missing_doc_crate_missing.stderr
  tests/ui/missing_doc_impl.rs
  tests/ui/missing_doc_impl.stderr
  tests/ui/unit_arg.rs
  tests/ui/unit_arg.stderr
Labels: S-waiting-on-review

#9126 `explicit_auto_deref` changes
  clippy_lints/src/dereference.rs
  clippy_utils/src/ty.rs
  tests/ui/explicit_auto_deref.fixed
  tests/ui/explicit_auto_deref.rs
  tests/ui/explicit_auto_deref.stderr
Labels: S-waiting-on-review

#9306 Rename `logic_bug` to `overly_complex_bool_expr`
  CHANGELOG.md
  clippy_lints/src/booleans.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_correctness.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/renamed_lints.rs
  tests/ui/diverging_sub_expression.rs
  tests/ui/expect_tool_lint_rfc_2383.rs
  tests/ui/expect_tool_lint_rfc_2383.stderr
  tests/ui/overly_complex_bool_expr.rs
  tests/ui/overly_complex_bool_expr.stderr
  tests/ui/rename.fixed
  tests/ui/rename.rs
  tests/ui/rename.stderr
Labels: S-waiting-on-review

#9288 Add partialeq_to_none lint
  CHANGELOG.md
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_style.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/partialeq_to_none.rs
  tests/ui/ifs_same_cond.rs
  tests/ui/manual_assert.edition2018.fixed
  tests/ui/manual_assert.edition2021.fixed
  tests/ui/manual_assert.fixed
  tests/ui/manual_assert.rs
  tests/ui/partialeq_to_none.fixed
  tests/ui/partialeq_to_none.rs
  tests/ui/partialeq_to_none.stderr
  tests/ui/same_functions_in_if_condition.rs
  tests/ui/same_functions_in_if_condition.stderr
Labels: S-waiting-on-review

#9308 Use `check_proc_macro` for `missing_const_for_fn`
  clippy_lints/src/missing_const_for_fn.rs
  clippy_utils/src/check_proc_macro.rs
  tests/ui/missing_const_for_fn/cant_be_const.rs
Labels: S-waiting-on-review

#9289 Extend `if_then_some_else_none` to also suggest `bool::then_some`
  clippy_lints/src/if_then_some_else_none.rs
  tests/ui/if_then_some_else_none.stderr
Labels: S-waiting-on-review

#9324 1.63 Changelog
  CHANGELOG.md
Labels: S-waiting-on-review

#9326 Update lint versions for 1.63 release
  clippy_lints/src/borrow_deref_ref.rs
  clippy_lints/src/doc_link_with_quotes.rs
  clippy_lints/src/duplicate_mod.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/mismatching_type_param_order.rs
  clippy_lints/src/rc_clone_in_vec_init.rs
  clippy_lints/src/unused_rounding.rs
Labels: S-waiting-on-review

#9187 Add lint recommending using `std::iter::once` and `std::iter::empty`
  CHANGELOG.md
  clippy_lints/src/dereference.rs
  clippy_lints/src/derive.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_nursery.rs
  clippy_lints/src/methods/iter_on_single_or_empty_collections.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/redundant_slicing.rs
  clippy_lints/src/utils/conf.rs
  clippy_lints/src/utils/internal_lints/metadata_collector.rs
  tests/ui/iter_on_empty_collections.fixed
  tests/ui/iter_on_empty_collections.rs
  tests/ui/iter_on_empty_collections.stderr
  tests/ui/iter_on_single_items.fixed
  tests/ui/iter_on_single_items.rs
  tests/ui/iter_on_single_items.stderr
Labels: S-waiting-on-review

#9329 Skip `unnecessary_to_owned` when `t != t.to_string()`
  clippy_lints/src/methods/unnecessary_to_owned.rs
  tests/ui/unnecessary_to_owned.fixed
  tests/ui/unnecessary_to_owned.rs
Labels: S-waiting-on-review

#9318 Fix if_let_mutex not checking Mutexes behind refs
  clippy_lints/src/if_let_mutex.rs
  tests/ui/if_let_mutex.rs
  tests/ui/if_let_mutex.stderr
Labels: S-waiting-on-review

#9328 Remove extra dereference from the borrow_deref_ref lint example
  clippy_lints/src/borrow_deref_ref.rs
Labels: S-waiting-on-review

#9340 Fix example
  clippy_lints/src/escape.rs
Labels: S-waiting-on-review

#9327 Fix [`non_ascii_literal`] in tests
  clippy_lints/src/unicode.rs
  tests/ui/unicode.fixed
  tests/ui/unicode.rs
  tests/ui/unicode.stderr
Labels: S-waiting-on-review

#9343 Use `CARGO_TARGET_DIR` in compile-test
  tests/compile-test.rs
Labels: S-waiting-on-review

#9341 suggest map_or in case_sensitive_file_extension_comparisons
  clippy_lints/src/case_sensitive_file_extension_comparisons.rs
Labels: S-waiting-on-review

#9344 Handle `CARGO_TARGET_DIR` not being set in compile-test
  tests/compile-test.rs
Labels: S-waiting-on-review

#9345 Fix typo in as_undescore docs
  clippy_lints/src/as_underscore.rs
Labels: S-waiting-on-review

#9287 `transmute_undefined_repr` fix
  clippy_lints/src/transmute/transmute_undefined_repr.rs
  tests/ui/transmute_undefined_repr.rs
  tests/ui/transmute_undefined_repr.stderr
Labels: S-waiting-on-review

#9338 unwrap_used and expect_used: trigger on uses of their _err variants
  clippy_lints/src/methods/expect_used.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/unwrap_used.rs
  tests/ui/expect.rs
  tests/ui/expect.stderr
  tests/ui/unwrap.rs
  tests/ui/unwrap.stderr
  tests/ui/unwrap_expect_used.rs
  tests/ui/unwrap_expect_used.stderr
Labels: S-waiting-on-review

#9136 Enhance `needless_borrow` to consider trait implementations
  clippy_dev/src/bless.rs
  clippy_dev/src/fmt.rs
  clippy_dev/src/update_lints.rs
  clippy_lints/src/dereference.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/methods/unnecessary_to_owned.rs
  clippy_utils/src/msrvs.rs
  rustc_tools_util/src/lib.rs
  tests/check-fmt.rs
  tests/dogfood.rs
  tests/integration.rs
  tests/lint_message_convention.rs
  tests/ui/needless_borrow.fixed
  tests/ui/needless_borrow.rs
  tests/ui/needless_borrow.stderr
  tests/ui/regex.rs
  tests/ui/same_item_push.rs
  tests/ui/verbose_file_reads.rs
  tests/workspace.rs
Labels: S-waiting-on-review

#9348 Don't lint on match pattern-binding in ´question_mark`
  clippy_lints/src/question_mark.rs
  tests/ui/question_mark.fixed
  tests/ui/question_mark.rs
Labels: S-waiting-on-review

#9295 Add `manual_empty_string_creations` lint
  CHANGELOG.md
  clippy_dev/src/new_lint.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_style.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_async_fn.rs
  clippy_lints/src/manual_empty_string_creations.rs
  clippy_lints/src/methods/option_map_unwrap_or.rs
  clippy_lints/src/misc_early/unneeded_wildcard_pattern.rs
  clippy_lints/src/unnecessary_wraps.rs
  clippy_utils/src/msrvs.rs
  tests/ui/case_sensitive_file_extension_comparisons.rs
  tests/ui/case_sensitive_file_extension_comparisons.stderr
  tests/ui/format.fixed
  tests/ui/format.rs
  tests/ui/identity_op.fixed
  tests/ui/identity_op.rs
  tests/ui/manual_empty_string_creations.fixed
  tests/ui/manual_empty_string_creations.rs
  tests/ui/manual_empty_string_creations.stderr
  tests/ui/or_fun_call.fixed
  tests/ui/or_fun_call.rs
  tests/ui/or_fun_call.stderr
  tests/ui/string_add.rs
  tests/ui/string_add_assign.fixed
  tests/ui/string_add_assign.rs
  tests/ui/unnecessary_owned_empty_strings.fixed
  tests/ui/unnecessary_owned_empty_strings.rs
  tests/ui/unnecessary_owned_empty_strings.stderr
  tests/ui/useless_conversion_try.rs
  tests/ui/useless_conversion_try.stderr
Labels: S-waiting-on-review

#8957 More lint pass merges
  clippy_lints/src/as_underscore.rs
  clippy_lints/src/borrow_as_ptr.rs
  clippy_lints/src/bytecount.rs
  clippy_lints/src/bytes_count_to_len.rs
  clippy_lints/src/case_sensitive_file_extension_comparisons.rs
  clippy_lints/src/casts/as_underscore.rs
  clippy_lints/src/casts/borrow_as_ptr.rs
  clippy_lints/src/casts/mod.rs
  clippy_lints/src/get_first.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_complexity.rs
  clippy_lints/src/lib.register_correctness.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_nursery.rs
  clippy_lints/src/lib.register_pedantic.rs
  clippy_lints/src/lib.register_restriction.rs
  clippy_lints/src/lib.register_style.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_ok_or.rs
  clippy_lints/src/map_clone.rs
  clippy_lints/src/map_err_ignore.rs
  clippy_lints/src/methods/bytecount.rs
  clippy_lints/src/methods/bytes_count_to_len.rs
  clippy_lints/src/methods/case_sensitive_file_extension_comparisons.rs
  clippy_lints/src/methods/get_first.rs
  clippy_lints/src/methods/manual_ok_or.rs
  clippy_lints/src/methods/map_clone.rs
  clippy_lints/src/methods/map_err_ignore.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/mut_mutex_lock.rs
  clippy_lints/src/methods/open_options.rs
  clippy_lints/src/methods/path_buf_push_overwrite.rs
  clippy_lints/src/methods/range_zip_with_len.rs
  clippy_lints/src/methods/repeat_once.rs
  clippy_lints/src/methods/stable_sort_primitive.rs
  clippy_lints/src/methods/unit_hash.rs
  clippy_lints/src/methods/unnecessary_sort_by.rs
  clippy_lints/src/methods/vec_resize_to_zero.rs
  clippy_lints/src/methods/verbose_file_reads.rs
  clippy_lints/src/mut_mutex_lock.rs
  clippy_lints/src/path_buf_push_overwrite.rs
  clippy_lints/src/ranges.rs
  clippy_lints/src/repeat_once.rs
  clippy_lints/src/stable_sort_primitive.rs
  clippy_lints/src/transmute/mod.rs
  clippy_lints/src/transmute/transmuting_null.rs
  clippy_lints/src/transmuting_null.rs
  clippy_lints/src/unit_hash.rs
  clippy_lints/src/vec_resize_to_zero.rs
  clippy_lints/src/verbose_file_reads.rs
  tests/ui/vec_resize_to_zero.rs
  tests/ui/vec_resize_to_zero.stderr
Labels: S-waiting-on-author

#9349 Refactor `FormatArgsExpn`
  clippy_lints/src/format.rs
  clippy_lints/src/format_args.rs
  clippy_lints/src/format_impl.rs
  clippy_lints/src/methods/uninit_assumed_init.rs
  clippy_lints/src/transmute/transmuting_null.rs
  clippy_utils/Cargo.toml
  clippy_utils/src/lib.rs
  clippy_utils/src/macros.rs
  clippy_utils/src/paths.rs
  tests/ui/format_args.fixed
  tests/ui/format_args.rs
  tests/ui/format_args.stderr
Labels: S-waiting-on-review

#8804 Rework `only_used_in_recursion`
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_complexity.rs
  clippy_lints/src/lib.register_nursery.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/only_used_in_recursion.rs
  clippy_lints/src/redundant_static_lifetimes.rs
  tests/ui/only_used_in_recursion.rs
  tests/ui/only_used_in_recursion.stderr
  tests/ui/only_used_in_recursion2.rs
  tests/ui/only_used_in_recursion2.stderr
Labels: S-waiting-on-review

#9258 Add [`unused_peekable`] lint
  CHANGELOG.md
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_suspicious.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/unused_peekable.rs
  clippy_utils/src/paths.rs
  clippy_utils/src/ty.rs
  tests/ui/unused_peekable.rs
  tests/ui/unused_peekable.stderr
Labels: S-waiting-on-review

#9355 Fix typos
  clippy_lints/src/manual_empty_string_creations.rs
  clippy_utils/src/macros.rs
Labels: S-waiting-on-review

#9269 Lint `collapsible_str_replace`
  CHANGELOG.md
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_perf.rs
  clippy_lints/src/methods/collapsible_str_replace.rs
  clippy_lints/src/methods/mod.rs
  tests/ui/collapsible_str_replace.fixed
  tests/ui/collapsible_str_replace.rs
  tests/ui/collapsible_str_replace.stderr
Labels: S-waiting-on-author

#8857 Add test for #8855
  tests/ui/format_args.fixed
  tests/ui/format_args.rs
  tests/ui/format_args.stderr
Labels: S-blocked

#8696 check for if-some-or-ok-else-none-or-err
  clippy_lints/src/option_if_let_else.rs
  tests/ui/option_if_let_else.fixed
  tests/ui/option_if_let_else.rs
  tests/ui/option_if_let_else.stderr
Labels: S-waiting-on-review

#8992 feat(fix): Do not lint if the target code is inside a loop
  clippy_lints/src/loops/needless_collect.rs
  tests/compile-test.rs
  tests/ui/needless_collect_indirect.rs
  tests/ui/needless_collect_indirect.stderr
Labels: S-waiting-on-review

#9092 Fix false positives of needless_match
  clippy_lints/src/matches/needless_match.rs
  tests/ui/needless_match.fixed
  tests/ui/needless_match.rs
  tests/ui/needless_match.stderr
Labels: S-waiting-on-review

#9259 Fix `to_string_in_format_args` false positive
  clippy_lints/src/format_args.rs
  tests/ui/format_args.fixed
  tests/ui/format_args.rs
  tests/ui/format_args.stderr
Labels: S-waiting-on-review

#9366 Rename `manual_empty_string_creation` and move to pedantic
  CHANGELOG.md
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_pedantic.rs
  clippy_lints/src/lib.register_style.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_string_new.rs
  tests/ui/manual_string_new.fixed
  tests/ui/manual_string_new.rs
  tests/ui/manual_string_new.stderr
  tests/ui/unnecessary_owned_empty_strings.fixed
  tests/ui/unnecessary_owned_empty_strings.rs
Labels: S-waiting-on-review

#9370 Replace `contains_ty(..)` with `Ty::contains(..)`
  clippy_lints/src/dereference.rs
  clippy_lints/src/escape.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/unnecessary_to_owned.rs
  clippy_lints/src/self_named_constructors.rs
  clippy_utils/src/ty.rs
Labels: S-waiting-on-review

#9379 new lint
  CHANGELOG.md
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_suspicious.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/multi_assignments.rs
  tests/ui/multi_assignments.rs
  tests/ui/multi_assignments.stderr
Labels: S-waiting-on-review

#9374 uninit_vec: Vec::spare_capacity_mut is stable
  clippy_lints/src/uninit_vec.rs
Labels: S-waiting-on-review

#9381 Don't lint `needless_return` if `return` has attrs
  clippy_lints/src/returns.rs
  tests/ui/needless_return.fixed
  tests/ui/needless_return.rs
Labels: S-waiting-on-review

#8984 Implemented `suspicious_to_owned` lint to check if `to_owned` is called on a `Cow`
  CHANGELOG.md
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_suspicious.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/suspicious_to_owned.rs
  tests/compile-test.rs
  tests/ui/suspicious_to_owned.rs
  tests/ui/suspicious_to_owned.stderr
Labels: S-waiting-on-author

#9276 Ignore `match_like_matches_macro` when there is comment
  clippy_lints/src/matches/match_like_matches.rs
  clippy_utils/src/lib.rs
  tests/ui/match_expr_like_matches_macro.fixed
  tests/ui/match_expr_like_matches_macro.rs
Labels: S-waiting-on-author

#9389 Don't lint literal `None` from expansion
  clippy_lints/src/partialeq_to_none.rs
  tests/ui/partialeq_to_none.fixed
  tests/ui/partialeq_to_none.rs
  tests/ui/partialeq_to_none.stderr
Labels: S-waiting-on-review

#9388 Rustup
  .github/workflows/clippy.yml
  .github/workflows/clippy_bors.yml
  clippy_lints/src/crate_in_macro_def.rs
  clippy_lints/src/dereference.rs
  clippy_lints/src/double_parens.rs
  clippy_lints/src/matches/match_same_arms.rs
  clippy_lints/src/octal_escapes.rs
  clippy_lints/src/option_env_unwrap.rs
  clippy_lints/src/precedence.rs
  clippy_lints/src/suspicious_operation_groupings.rs
  clippy_lints/src/unused_peekable.rs
  clippy_lints/src/unused_rounding.rs
  clippy_lints/src/unused_unit.rs
  clippy_lints/src/utils/author.rs
  clippy_lints/src/utils/internal_lints.rs
  clippy_lints/src/write.rs
  clippy_utils/src/ast_utils.rs
  clippy_utils/src/attrs.rs
  clippy_utils/src/consts.rs
  clippy_utils/src/lib.rs
  rust-toolchain
  src/driver.rs
  tests/ui/semicolon_if_nothing_returned.rs
  tests/ui/semicolon_if_nothing_returned.stderr
Labels: S-waiting-on-review

#9385 remove parenthesis from `unnecessary_cast` suggestion
  clippy_lints/src/casts/unnecessary_cast.rs
  tests/ui/unnecessary_cast.fixed
  tests/ui/unnecessary_cast.rs
  tests/ui/unnecessary_cast.stderr
Labels: S-waiting-on-review

#9247 New lint: Raw slice pointer cast
  CHANGELOG.md
  clippy_lints/src/casts/cast_slice_from_raw_parts.rs
  clippy_lints/src/casts/mod.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_suspicious.rs
  tests/ui/cast_raw_slice_pointer_cast.fixed
  tests/ui/cast_raw_slice_pointer_cast.rs
  tests/ui/cast_raw_slice_pointer_cast.stderr
Labels: S-waiting-on-review

#9395 Fix `suspicious_to_owned` test when `c_char` is `u8`
  tests/ui/suspicious_to_owned.rs
Labels: S-waiting-on-review

#9394 Fix missing parens in `suboptimal_flops` suggestion
  clippy_lints/src/floating_point_arithmetic.rs
  tests/ui/floating_point_exp.fixed
  tests/ui/floating_point_exp.rs
  tests/ui/floating_point_exp.stderr
  tests/ui/floating_point_log.fixed
  tests/ui/floating_point_log.rs
  tests/ui/floating_point_log.stderr
  tests/ui/floating_point_logbase.fixed
  tests/ui/floating_point_logbase.rs
  tests/ui/floating_point_logbase.stderr
  tests/ui/floating_point_powf.fixed
  tests/ui/floating_point_powf.rs
  tests/ui/floating_point_powf.stderr
  tests/ui/floating_point_powi.fixed
  tests/ui/floating_point_powi.rs
  tests/ui/floating_point_powi.stderr
  tests/ui/floating_point_rad.fixed
  tests/ui/floating_point_rad.rs
  tests/ui/floating_point_rad.stderr
Labels: S-waiting-on-review

#9373 Initial implementation `result_large_err`
  CHANGELOG.md
  clippy_lints/src/functions/mod.rs
  clippy_lints/src/functions/result.rs
  clippy_lints/src/functions/result_unit_err.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_perf.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/conf.rs
  clippy_utils/src/ty.rs
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
  tests/ui/result_large_err.rs
  tests/ui/result_large_err.stderr
Labels: S-waiting-on-review

#9397 Fix the emission order of `trait_duplication_in_bounds`
  clippy_lints/src/trait_bounds.rs
  tests/ui/trait_duplication_in_bounds.fixed
  tests/ui/trait_duplication_in_bounds.stderr
  tests/ui/trait_duplication_in_bounds_unfixable.stderr
Labels: S-waiting-on-review, I-sync-blocker

#9403 match_wild_err_arm: Fix typo in note text
  clippy_lints/src/matches/match_wild_err_arm.rs
  tests/ui/match_wild_err_arm.edition2018.stderr
  tests/ui/match_wild_err_arm.edition2021.stderr
Labels: S-waiting-on-review
