Repository rust-lang/rust-clippy, pull requests merged in 2022-09, with the labels that each got.

#9406 Correctly handle unescape warnings
  clippy_dev/src/update_lints.rs
  clippy_lints/src/write.rs
  clippy_utils/src/macros.rs
  tests/ui/crashes/ice-9405.rs
  tests/ui/crashes/ice-9405.stderr
Labels: S-waiting-on-review

#9404 Fix `suboptimal_float` not linting on `{const}.powf({const})`
  clippy_lints/src/floating_point_arithmetic.rs
  tests/ui/floating_point_powf.fixed
  tests/ui/floating_point_powf.rs
  tests/ui/floating_point_powf.stderr
Labels: S-waiting-on-review

#9417 Don't use `hir_ty_to_ty` in `result_large_err`
  clippy_lints/src/functions/result.rs
  tests/ui/crashes/ice-9414.rs
Labels: S-waiting-on-review

#9418 Fix `mut_mutex_lock` when Mutex is behind immutable deref
  clippy_lints/src/methods/mut_mutex_lock.rs
  tests/ui/mut_mutex_lock.fixed
  tests/ui/mut_mutex_lock.rs
Labels: S-waiting-on-review

#9400 Use `approx_ty_size` for `large_enum_variant`
  clippy_lints/src/large_enum_variant.rs
  src/docs/large_enum_variant.txt
  tests/ui/large_enum_variant.rs
  tests/ui/large_enum_variant.stderr
  tests/ui/result_large_err.rs
  tests/ui/result_large_err.stderr
Labels: S-needs-discussion, S-waiting-on-review

#9424 Fix `unnecessary_to_owned` false positive
  clippy_lints/src/methods/unnecessary_to_owned.rs
  tests/ui/unnecessary_to_owned.fixed
  tests/ui/unnecessary_to_owned.rs
  tests/ui/unnecessary_to_owned.stderr
Labels: S-waiting-on-review

#9425 fix wording for `derivable_impls`
  clippy_lints/src/derivable_impls.rs
  src/docs/derivable_impls.txt
Labels: S-waiting-on-review

#9342 Suggest `Entry::or_default` for `Entry::or_insert(Default::default())`
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/or_fun_call.rs
  src/docs/or_fun_call.txt
  tests/ui/or_fun_call.fixed
  tests/ui/or_fun_call.stderr
Labels: S-waiting-on-author

#9421 Suggest `unwrap_or_default` when closure returns `"".to_string`
  clippy_lints/src/methods/unwrap_or_else_default.rs
  tests/ui/unwrap_or_else_default.fixed
  tests/ui/unwrap_or_else_default.rs
  tests/ui/unwrap_or_else_default.stderr
Labels: S-waiting-on-review

#9441 Fix hang in `vec_init_then_push`
  clippy_lints/src/vec_init_then_push.rs
  tests/ui/vec_init_then_push.rs
  tests/ui/vec_init_then_push.stderr
Labels: S-waiting-on-review

#9365 [Arithmetic] Consider literals
  clippy_lints/src/operators/arithmetic.rs
  clippy_lints/src/operators/mod.rs
  src/docs/arithmetic.txt
  tests/ui/arithmetic.fixed
  tests/ui/arithmetic.rs
  tests/ui/arithmetic.stderr
Labels: S-waiting-on-review

#9443 Rename the arithmetic lint
  CHANGELOG.md
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_restriction.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/operators/arithmetic_side_effects.rs
  clippy_lints/src/operators/mod.rs
  clippy_lints/src/utils/conf.rs
  src/docs.rs
  src/docs/arithmetic_side_effects.txt
  tests/ui-toml/arithmetic_allowed/clippy.toml
  tests/ui-toml/arithmetic_side_effects_allowed/arithmetic_side_effects_allowed.rs
  tests/ui-toml/arithmetic_side_effects_allowed/clippy.toml
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
  tests/ui/arithmetic_side_effects.rs
  tests/ui/arithmetic_side_effects.stderr
Labels: S-waiting-on-review

#9446 Fix `range_{plus,minus}_one` bad suggestions
  clippy_lints/src/ranges.rs
  tests/ui/range_plus_minus_one.fixed
  tests/ui/range_plus_minus_one.rs
  tests/ui/range_plus_minus_one.stderr
Labels: S-waiting-on-review

#9448 Replace u128 with u64 in large_enum_variant uitest
  tests/ui/large_enum_variant.rs
  tests/ui/large_enum_variant.stderr
Labels: S-waiting-on-review

#9453 [`assertions_on_result_states`]: Fix suggestion when `assert!` is not in a statement.
  clippy_lints/src/assertions_on_result_states.rs
  clippy_lints/src/methods/err_expect.rs
  clippy_lints/src/methods/ok_expect.rs
  clippy_utils/src/ty.rs
  tests/ui/assertions_on_result_states.fixed
  tests/ui/assertions_on_result_states.rs
  tests/ui/assertions_on_result_states.stderr
Labels: S-waiting-on-review

#9457 Do not expand macro in `nonminimal_bool` suggestions
  clippy_lints/src/booleans.rs
  tests/ui/nonminimal_bool.rs
  tests/ui/nonminimal_bool.stderr
Labels: S-waiting-on-review

#9410 Use macro callsite when creating `Sugg` helper
  clippy_utils/src/sugg.rs
  tests/ui/collapsible_if.fixed
  tests/ui/collapsible_if.rs
  tests/ui/collapsible_if.stderr
Labels: S-waiting-on-review

#9458 Use `visit_expr_field` for `ParamPosition`
  clippy_utils/src/macros.rs
Labels: S-waiting-on-review

#9469 Fix FormatArgsExpn parsing of FormatSpec positions
  clippy_utils/src/macros.rs
  tests/ui/explicit_write.fixed
  tests/ui/explicit_write.rs
  tests/ui/explicit_write.stderr
Labels: S-waiting-on-review

#9466 Don't lint `large_stack_array` inside static items
  clippy_lints/src/large_stack_arrays.rs
  tests/ui/large_stack_arrays.rs
  tests/ui/large_stack_arrays.stderr
Labels: S-waiting-on-review

#9464 Don't panic on invalid shift while constfolding
  clippy_utils/src/consts.rs
  tests/ui/crashes/ice-9463.rs
  tests/ui/crashes/ice-9463.stderr
Labels: S-waiting-on-review

#9452 Fix dev book
  book/src/development/common_tools_writing_lints.md
Labels: S-waiting-on-review

#9454 Do not lint `use_self` in proc macro expansion
  clippy_lints/src/use_self.rs
  tests/ui/use_self.fixed
  tests/ui/use_self.rs
Labels: S-waiting-on-review

#9474 [arithmetic-side-effects] More non-overflowing ops
  clippy_lints/src/operators/arithmetic_side_effects.rs
  tests/ui/arithmetic_side_effects.rs
  tests/ui/arithmetic_side_effects.stderr
Labels: S-waiting-on-review

#9467 Fix `almost_complete_letter_range` false positive.
  clippy_lints/src/almost_complete_letter_range.rs
  tests/ui/almost_complete_letter_range.fixed
  tests/ui/almost_complete_letter_range.rs
  tests/ui/almost_complete_letter_range.stderr
  tests/ui/auxiliary/macro_rules.rs
Labels: S-waiting-on-author

#8518 Migrate write.rs to a late pass
  clippy_lints/src/format.rs
  clippy_lints/src/format_args.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_suspicious.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/renamed_lints.rs
  clippy_lints/src/utils/conf.rs
  clippy_lints/src/write.rs
  clippy_utils/src/macros.rs
  src/docs.rs
  src/docs/positional_named_format_parameters.txt
  src/docs/print_literal.txt
  src/docs/print_stderr.txt
  src/docs/print_stdout.txt
  src/docs/write_literal.txt
  tests/ui/eprint_with_newline.rs
  tests/ui/eprint_with_newline.stderr
  tests/ui/format.fixed
  tests/ui/format.rs
  tests/ui/format.stderr
  tests/ui/positional_named_format_parameters.fixed
  tests/ui/positional_named_format_parameters.rs
  tests/ui/positional_named_format_parameters.stderr
  tests/ui/print_literal.rs
  tests/ui/print_literal.stderr
  tests/ui/print_with_newline.rs
  tests/ui/print_with_newline.stderr
  tests/ui/println_empty_string.stderr
  tests/ui/rename.fixed
  tests/ui/rename.rs
  tests/ui/rename.stderr
  tests/ui/write_literal.rs
  tests/ui/write_literal.stderr
  tests/ui/write_literal_2.rs
  tests/ui/write_literal_2.stderr
  tests/ui/write_with_newline.rs
  tests/ui/write_with_newline.stderr
  tests/ui/writeln_empty_string.stderr
Labels: S-waiting-on-author

#9476 `bool_to_int_with_if` inverse case patch
  clippy_lints/src/bool_to_int_with_if.rs
  clippy_lints/src/dereference.rs
  clippy_lints/src/methods/unnecessary_to_owned.rs
  clippy_utils/src/sugg.rs
  tests/ui/bool_to_int_with_if.fixed
  tests/ui/bool_to_int_with_if.rs
  tests/ui/bool_to_int_with_if.stderr
  tests/ui/len_without_is_empty.rs
Labels: S-waiting-on-review

#9475 Make module-style lints resilient to --remap-path-prefix
  clippy_lints/src/module_style.rs
  tests/ui-cargo/module_style/fail_mod_remap/Cargo.toml
  tests/ui-cargo/module_style/fail_mod_remap/src/bad.rs
  tests/ui-cargo/module_style/fail_mod_remap/src/bad/inner.rs
  tests/ui-cargo/module_style/fail_mod_remap/src/main.rs
  tests/ui-cargo/module_style/fail_mod_remap/src/main.stderr
Labels: S-waiting-on-review

#9478 Update rust-analyzer documentation, mention linkedProjects
  CONTRIBUTING.md
Labels: S-waiting-on-review

#9481 Fix indents
  book/src/development/common_tools_writing_lints.md
Labels: S-waiting-on-review

#9409 Add `iter_kv_map` lint
  CHANGELOG.md
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_complexity.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/methods/iter_kv_map.rs
  clippy_lints/src/methods/mod.rs
  src/docs.rs
  src/docs/iter_kv_map.txt
  tests/ui/iter_kv_map.fixed
  tests/ui/iter_kv_map.rs
  tests/ui/iter_kv_map.stderr
Labels: S-waiting-on-author

#9488 Add `#[allow(unused)]` to test in `cargo dev new_lint`
  book/src/development/adding_lints.md
  clippy_dev/src/new_lint.rs
Labels: S-waiting-on-review

#9483 [arithmetic-side-effects] Finish non-overflowing ops
  clippy_lints/src/operators/arithmetic_side_effects.rs
  tests/ui/arithmetic_side_effects.rs
  tests/ui/arithmetic_side_effects.stderr
Labels: S-waiting-on-review

#9502 [arithmetic-side-effects] Add more tests
  tests/ui/arithmetic_side_effects.rs
  tests/ui/arithmetic_side_effects.stderr
Labels: S-waiting-on-review

#9505 Fix ICE in `unnecessary_to_owned`
  clippy_lints/src/methods/unnecessary_to_owned.rs
  tests/ui/unnecessary_to_owned.fixed
  tests/ui/unnecessary_to_owned.rs
Labels: S-waiting-on-review

#9471 Add matches! checking to nonstandard_macro_braces
  clippy_lints/src/nonstandard_macro_braces.rs
  tests/ui-toml/nonstandard_macro_braces/conf_nonstandard_macro_braces.rs
  tests/ui-toml/nonstandard_macro_braces/conf_nonstandard_macro_braces.stderr
Labels: S-waiting-on-review

#9501 Changelog for Rust 1.64 :apple:
  CHANGELOG.md
  clippy_lints/src/default_instead_of_iter_empty.rs
  clippy_lints/src/dereference.rs
  clippy_lints/src/loops/mod.rs
  clippy_lints/src/manual_rem_euclid.rs
  clippy_lints/src/manual_retain.rs
Labels: S-waiting-on-review

#9519 uninit_vec: fix false positive with set_len(0)
  clippy_lints/src/uninit_vec.rs
  tests/ui/uninit_vec.rs
Labels: S-waiting-on-review

#9523 Upgrade `compiletest-rs` dependency
  Cargo.toml
Labels: S-waiting-on-review

#9496 [`never_loop`]: Fix FP with let..else statements.
  clippy_lints/src/loops/never_loop.rs
  tests/ui/never_loop.rs
  tests/ui/never_loop.stderr
Labels: S-waiting-on-review

#9527 fallout2: rework clippy_dev & _lints fmt inlining
  clippy_dev/src/fmt.rs
  clippy_dev/src/new_lint.rs
  clippy_dev/src/serve.rs
  clippy_dev/src/setup/git_hook.rs
  clippy_dev/src/setup/intellij.rs
  clippy_dev/src/setup/vscode.rs
  clippy_dev/src/update_lints.rs
  clippy_lints/src/utils/internal_lints.rs
  clippy_lints/src/utils/internal_lints/metadata_collector.rs
Labels: S-waiting-on-review

#9531 Fix ICE in `needless_pass_by_value` with unsized `dyn Fn`
  clippy_lints/src/needless_pass_by_value.rs
  tests/ui/crashes/ice-9459.rs
Labels: S-waiting-on-review

#9535 Moved derive_partial_eq_without_eq to nursery
  clippy_lints/src/derive.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_nursery.rs
  clippy_lints/src/lib.register_style.rs
Labels: S-waiting-on-review

#9533 Fix panic when displaying the backtrace of failing integration tests
  tests/integration.rs
Labels: S-waiting-on-review

#9233 new uninlined_format_args lint to inline explicit arguments
  CHANGELOG.md
  clippy_lints/src/format_args.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_pedantic.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/conf.rs
  clippy_lints/src/write.rs
  clippy_utils/src/macros.rs
  clippy_utils/src/msrvs.rs
  clippy_utils/src/source.rs
  src/docs.rs
  src/docs/uninlined_format_args.txt
  tests/ui/uninlined_format_args.fixed
  tests/ui/uninlined_format_args.rs
  tests/ui/uninlined_format_args.stderr
Labels: S-waiting-on-review

#9487 Silence [`question_mark`] in const context
  clippy_lints/src/question_mark.rs
  tests/ui/question_mark.fixed
  tests/ui/question_mark.rs
Labels: S-waiting-on-review

#9539 Don't lint `*_interior_mutable_const` on unions due to potential ICE.
  clippy_lints/src/non_copy_const.rs
  tests/ui/crashes/ice-9445.rs
Labels: S-waiting-on-review

#9507 [arithmetic-side-effects] Consider references
  clippy_lints/src/operators/arithmetic_side_effects.rs
  tests/ui/arithmetic_side_effects.rs
  tests/ui/arithmetic_side_effects.stderr
Labels: S-waiting-on-review

#9497 [`needless_return`] Recursively remove unneeded semicolons
  clippy_lints/src/returns.rs
  tests/ui/needless_return.fixed
  tests/ui/needless_return.rs
  tests/ui/needless_return.stderr
Labels: S-waiting-on-review

#9511 add `box-default` lint
  CHANGELOG.md
  clippy_lints/src/box_default.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_perf.rs
  clippy_lints/src/lib.rs
  src/docs.rs
  src/docs/box_default.txt
  tests/ui/box_collection.rs
  tests/ui/box_default.rs
  tests/ui/box_default.stderr
Labels: S-waiting-on-review

#9491 [`drop_copy`]: Do not lint idiomatic in match arm
  clippy_lints/src/drop_forget_ref.rs
  tests/ui/drop_forget_copy.rs
  tests/ui/drop_forget_copy.stderr
Labels: S-waiting-on-review

#9545 Don't lint unstable moves in `std_instead_of_core`
  clippy_lints/src/std_instead_of_core.rs
  tests/ui/std_instead_of_core.rs
  tests/ui/std_instead_of_core.stderr
Labels: S-waiting-on-review

#9490 fix [`needless_borrow`], [`explicit_auto_deref`] FPs on unions
  clippy_lints/src/dereference.rs
  tests/ui/needless_borrow.fixed
  tests/ui/needless_borrow.rs
Labels: S-waiting-on-review

#9550 Fix typo
  clippy_lints/src/option_if_let_else.rs
Labels: S-waiting-on-review

#9551 [`unnecessary_lazy_evaluations`] Do not suggest switching to early evaluation when type has custom `Drop`
  clippy_utils/src/eager_or_lazy.rs
  tests/ui/unnecessary_lazy_eval.fixed
  tests/ui/unnecessary_lazy_eval.rs
  tests/ui/unnecessary_lazy_eval.stderr
Labels: S-waiting-on-review

#9486 [`unnecessary_lazy_eval`] Do not lint in external macros
  clippy_lints/src/methods/unnecessary_lazy_eval.rs
  tests/ui/unnecessary_lazy_eval.fixed
  tests/ui/unnecessary_lazy_eval.rs
  tests/ui/unnecessary_lazy_eval.stderr
Labels: S-waiting-on-review

#9556 [`redundant_closure`] Fix suggestion causes error for `impl FnMut`
  clippy_lints/src/eta_reduction.rs
  tests/ui/eta.fixed
  tests/ui/eta.rs
  tests/ui/eta.stderr
Labels: S-waiting-on-review

#9510 Add `cargo lintcheck --recursive` to check dependencies of crates
  lintcheck/Cargo.toml
  lintcheck/README.md
  lintcheck/lintcheck_crates.toml
  lintcheck/src/config.rs
  lintcheck/src/driver.rs
  lintcheck/src/main.rs
  lintcheck/src/recursive.rs
Labels: S-waiting-on-review
