Repository rust-lang/rust-clippy, pull requests merged in 2022-11, with the labels that each got.

#9743 Improve `needless_lifetimes`
  clippy_lints/src/booleans.rs
  clippy_lints/src/dereference.rs
  clippy_lints/src/doc.rs
  clippy_lints/src/fallible_impl_from.rs
  clippy_lints/src/implicit_hasher.rs
  clippy_lints/src/index_refutable_slice.rs
  clippy_lints/src/indexing_slicing.rs
  clippy_lints/src/invalid_upcast_comparisons.rs
  clippy_lints/src/lifetimes.rs
  clippy_lints/src/loops/mut_range_bound.rs
  clippy_lints/src/map_unit_fn.rs
  clippy_lints/src/matches/manual_filter.rs
  clippy_lints/src/matches/significant_drop_in_scrutinee.rs
  clippy_lints/src/matches/single_match.rs
  clippy_lints/src/methods/chars_cmp_with_unwrap.rs
  clippy_lints/src/methods/chars_last_cmp.rs
  clippy_lints/src/methods/chars_last_cmp_with_unwrap.rs
  clippy_lints/src/methods/chars_next_cmp.rs
  clippy_lints/src/methods/chars_next_cmp_with_unwrap.rs
  clippy_lints/src/methods/filter_map.rs
  clippy_lints/src/methods/inefficient_to_string.rs
  clippy_lints/src/methods/iter_nth_zero.rs
  clippy_lints/src/methods/iter_on_single_or_empty_collections.rs
  clippy_lints/src/methods/manual_saturating_arithmetic.rs
  clippy_lints/src/methods/map_clone.rs
  clippy_lints/src/methods/map_err_ignore.rs
  clippy_lints/src/methods/option_as_ref_deref.rs
  clippy_lints/src/methods/suspicious_map.rs
  clippy_lints/src/mixed_read_write_in_expression.rs
  clippy_lints/src/mut_key.rs
  clippy_lints/src/needless_continue.rs
  clippy_lints/src/operators/op_ref.rs
  clippy_lints/src/pattern_type_mismatch.rs
  clippy_lints/src/ptr_offset_with_cast.rs
  clippy_lints/src/redundant_closure_call.rs
  clippy_lints/src/slow_vector_initialization.rs
  clippy_lints/src/utils/internal_lints/lint_without_lint_pass.rs
  clippy_utils/src/diagnostics.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/qualify_min_const_fn.rs
  clippy_utils/src/sugg.rs
  tests/ui/crashes/ice-2774.stderr
  tests/ui/crashes/needless_lifetimes_impl_trait.stderr
  tests/ui/issue_4266.stderr
  tests/ui/mut_from_ref.rs
  tests/ui/needless_lifetimes.rs
  tests/ui/needless_lifetimes.stderr
  tests/ui/transmute.rs
  tests/ui/trivially_copy_pass_by_ref.rs
  tests/ui/trivially_copy_pass_by_ref.stderr
Labels: S-waiting-on-review

#9772 Shrink `missing_{safety,errors,panics}_doc` spans
  clippy_lints/src/doc.rs
  tests/ui/doc_errors.stderr
  tests/ui/doc_unsafe.stderr
  tests/ui/missing_panics_doc.stderr
Labels: S-waiting-on-review

#9773 Fix ICE in `redundant_allocation`
  clippy_lints/src/types/redundant_allocation.rs
  tests/ui/crashes/ice-9746.rs
Labels: S-waiting-on-review

#9761 Changelog for Rust 1.65
  CHANGELOG.md
  clippy_lints/src/casts/mod.rs
  clippy_lints/src/functions/mod.rs
  clippy_lints/src/manual_instant_elapsed.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/partialeq_to_none.rs
  clippy_lints/src/unused_peekable.rs
Labels: S-waiting-on-review

#9779 fix turbofish in suggest message
  clippy_lints/src/methods/unnecessary_join.rs
  tests/ui/unnecessary_join.stderr
Labels: S-waiting-on-review

#9753 Update CONTRIBUTING.md with changelog guidance
  CONTRIBUTING.md
Labels: S-waiting-on-review

#9799 Update lint `suspicious_to_owned`
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-review

#9797 Add allow-print-in-tests config
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/conf.rs
  clippy_lints/src/write.rs
  tests/ui-toml/print_macro/clippy.toml
  tests/ui-toml/print_macro/print_macro.rs
  tests/ui-toml/print_macro/print_macro.stderr
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
Labels: S-waiting-on-review

#9760 Add new lint [`let_underscore_future`]
  CHANGELOG.md
  clippy_lints/foo.txt
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/let_underscore.rs
  tests/ui/let_underscore_future.rs
  tests/ui/let_underscore_future.stderr
  tests/ui/let_underscore_lock.stderr
  tests/ui/let_underscore_must_use.stderr
Labels: S-waiting-on-review

#9804 Update CoC to rust-lang/rust's
  CODE_OF_CONDUCT.md
Labels: S-waiting-on-review

#9705 Move needless_collect to nursery
  clippy_lints/src/loops/mod.rs
  tests/ui/needless_collect_indirect.rs
  tests/ui/needless_collect_indirect.stderr
Labels: S-waiting-on-review

#9765 Add `manual_is_ascii_check` lint
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_is_ascii_check.rs
  clippy_utils/src/msrvs.rs
  tests/ui/manual_is_ascii_check.fixed
  tests/ui/manual_is_ascii_check.rs
  tests/ui/manual_is_ascii_check.stderr
Labels: S-waiting-on-review

#9818 Fixed Typo
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-review

#9791 Address issues 9739 and 9782
  clippy_lints/src/dereference.rs
  tests/ui/needless_borrow.fixed
  tests/ui/needless_borrow.rs
  tests/ui/needless_borrow.stderr
Labels: S-waiting-on-review

#9817 Update lint example for `collapsible_str_replace`
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-review

#9813 Fix `explicit_auto_deref` fp
  clippy_lints/src/dereference.rs
  tests/ui/explicit_auto_deref.fixed
  tests/ui/explicit_auto_deref.rs
Labels: S-waiting-on-review

#9828 fix: cognitive_complexity for async fn
  clippy_lints/src/cognitive_complexity.rs
  tests/ui/cognitive_complexity.rs
  tests/ui/cognitive_complexity.stderr
Labels: S-waiting-on-review

#9830 Make `bool_to_int_with_if` a pedantic lint
  clippy_lints/src/bool_to_int_with_if.rs
Labels: S-waiting-on-review

#9662 `result_large_err` show largest variants in err msg
  clippy_lints/src/functions/result.rs
  clippy_lints/src/large_enum_variant.rs
  clippy_utils/src/ty.rs
  tests/ui/result_large_err.rs
  tests/ui/result_large_err.stderr
Labels: S-waiting-on-review

#9834 refac: remove unnecessary mutability
  clippy_lints/src/manual_is_ascii_check.rs
Labels: S-waiting-on-review

#9836 Fix is_async_fn to check FnKind::Method
  clippy_utils/src/lib.rs
  tests/ui/cognitive_complexity.rs
  tests/ui/cognitive_complexity.stderr
Labels: S-waiting-on-review

#9835 Avoid linting unsized mutable reference
  clippy_lints/src/mut_mut.rs
  tests/ui/mut_mut.rs
Labels: S-waiting-on-review

#9698 [`fn_params_excessive_bools`] Make it possible to allow the lint at the method level
  clippy_lints/src/excessive_bools.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/trailing_empty_array.rs
  clippy_utils/src/hir_utils.rs
  clippy_utils/src/lib.rs
  tests/ui/fn_params_excessive_bools.rs
  tests/ui/fn_params_excessive_bools.stderr
Labels: S-waiting-on-review

#9822 Add `unnecessary_safety_doc` lint
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/doc.rs
  tests/ui/auxiliary/doc_unsafe_macros.rs
  tests/ui/doc_unnecessary_unsafe.rs
  tests/ui/doc_unnecessary_unsafe.stderr
Labels: S-waiting-on-review

#9829 Make it clear that `or_fun_call` can be a false-positive
  clippy_lints/src/methods/mod.rs
  tests/ui/unwrap_or.rs
Labels: S-waiting-on-review

#9837 fix never_loop false positive
  clippy_lints/src/loops/never_loop.rs
  tests/ui/never_loop.rs
Labels: S-waiting-on-review

#9570 feat: lint unchecked subtraction of a 'Duration' from an 'Instant'
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/instant_subtraction.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_instant_elapsed.rs
  clippy_lints/src/utils/conf.rs
  tests/ui/manual_instant_elapsed.fixed
  tests/ui/manual_instant_elapsed.rs
  tests/ui/manual_instant_elapsed.stderr
  tests/ui/unchecked_duration_subtraction.fixed
  tests/ui/unchecked_duration_subtraction.rs
  tests/ui/unchecked_duration_subtraction.stderr
Labels: S-waiting-on-author

#9849 Allow return types for closures with lifetime binder
  clippy_lints/src/unused_unit.rs
  tests/ui/unused_unit.fixed
  tests/ui/unused_unit.rs
  tests/ui/unused_unit.stderr
Labels: S-waiting-on-review

#9859 Avoid generating files via doctest
  clippy_lints/foo.txt
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-review

#9858 `never_loop`: don't emit AlwaysBreaks if it targets a block
  clippy_lints/src/loops/never_loop.rs
  tests/ui/never_loop.rs
  tests/ui/never_loop.stderr
Labels: S-waiting-on-review

#9850 Preserve `ref` on `infallible_destructuring_match` suggestion
  clippy_lints/src/matches/infallible_destructuring_match.rs
  tests/ui/infallible_destructuring_match.fixed
  tests/ui/infallible_destructuring_match.rs
  tests/ui/infallible_destructuring_match.stderr
Labels: S-waiting-on-review

#9863 Fix typo in `expect_used` and `unwrap_used` warning messages
  clippy_lints/src/methods/expect_used.rs
  clippy_lints/src/methods/unwrap_used.rs
  tests/ui-toml/expect_used/expect_used.stderr
  tests/ui-toml/unwrap_used/unwrap_used.stderr
  tests/ui/expect.stderr
  tests/ui/get_unwrap.stderr
  tests/ui/unwrap.stderr
  tests/ui/unwrap_expect_used.stderr
Labels: S-waiting-on-review

#9855 Extend `needless_borrowed_reference` to structs and tuples, ignore _
  clippy_lints/src/enum_variants.rs
  clippy_lints/src/int_plus_one.rs
  clippy_lints/src/len_zero.rs
  clippy_lints/src/needless_borrowed_ref.rs
  clippy_lints/src/unsafe_removed_from_name.rs
  clippy_utils/src/consts.rs
  clippy_utils/src/hir_utils.rs
  tests/ui/match_expr_like_matches_macro.fixed
  tests/ui/match_expr_like_matches_macro.rs
  tests/ui/match_expr_like_matches_macro.stderr
  tests/ui/needless_borrowed_ref.fixed
  tests/ui/needless_borrowed_ref.rs
  tests/ui/needless_borrowed_ref.stderr
Labels: S-waiting-on-review

#9871 Allow manual swap in const fn
  clippy_lints/src/swap.rs
  tests/ui/swap.fixed
  tests/ui/swap.rs
Labels: S-waiting-on-review

#9800 Return multiple resolutions from `def_path_res`
  clippy_lints/src/await_holding_invalid.rs
  clippy_lints/src/disallowed_macros.rs
  clippy_lints/src/disallowed_methods.rs
  clippy_lints/src/disallowed_types.rs
  clippy_lints/src/missing_enforced_import_rename.rs
  clippy_lints/src/mut_key.rs
  clippy_lints/src/utils/conf.rs
  clippy_lints/src/utils/internal_lints/interning_defined_symbol.rs
  clippy_lints/src/utils/internal_lints/invalid_paths.rs
  clippy_lints/src/utils/internal_lints/unnecessary_def_path.rs
  clippy_utils/src/lib.rs
  tests/ui-toml/await_holding_invalid_type/await_holding_invalid_type.stderr
  tests/ui-toml/toml_disallowed_methods/clippy.toml
  tests/ui-toml/toml_disallowed_methods/conf_disallowed_methods.rs
  tests/ui-toml/toml_disallowed_methods/conf_disallowed_methods.stderr
Labels: S-waiting-on-review

#9879 Fix `#[allow]` for `module_name_repetitions` & `single_component_path_imports`
  clippy_lints/src/attrs.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/single_component_path_imports.rs
  tests/ui/single_component_path_imports.stderr
  tests/ui/single_component_path_imports_nested_first.stderr
  tests/ui/useless_attribute.fixed
  tests/ui/useless_attribute.rs
  tests/ui/useless_attribute.stderr
Labels: S-waiting-on-review

#9870 Keep original literal notation in suggestion
  clippy_lints/src/unused_rounding.rs
  tests/ui/unused_rounding.fixed
  tests/ui/unused_rounding.rs
  tests/ui/unused_rounding.stderr
Labels: S-waiting-on-review

#9592 [arithmetic-side-effects] Detect overflowing associated constants of integers
  clippy_lints/src/operators/arithmetic_side_effects.rs
  tests/ui-toml/arithmetic_side_effects_allowed/arithmetic_side_effects_allowed.rs
  tests/ui/arithmetic_side_effects.rs
  tests/ui/arithmetic_side_effects.stderr
Labels: S-waiting-on-review

#9873 Move `line_span` to source.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/source.rs
Labels: S-waiting-on-review

#9770 Add new lint [`misnamed-getters`]
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/functions/misnamed_getters.rs
  clippy_lints/src/functions/mod.rs
  tests/ui/misnamed_getters.rs
  tests/ui/misnamed_getters.stderr
Labels: S-waiting-on-review

#9745 Fix `redundant_closure_for_method_calls` suggestion
  clippy_lints/src/eta_reduction.rs
  tests/ui/eta.fixed
  tests/ui/eta.rs
  tests/ui/eta.stderr
Labels: S-waiting-on-review

#9930 Use `walk_generic_arg`
  clippy_lints/src/lifetimes.rs
Labels: S-waiting-on-review

#9924 Add `clippy_utils::msrv::Msrv` to keep track of the current MSRV
  book/src/development/adding_lints.md
  clippy_dev/src/new_lint.rs
  clippy_lints/src/almost_complete_letter_range.rs
  clippy_lints/src/approx_const.rs
  clippy_lints/src/attrs.rs
  clippy_lints/src/casts/cast_abs_to_unsigned.rs
  clippy_lints/src/casts/cast_lossless.rs
  clippy_lints/src/casts/cast_slice_different_sizes.rs
  clippy_lints/src/casts/cast_slice_from_raw_parts.rs
  clippy_lints/src/casts/mod.rs
  clippy_lints/src/casts/ptr_as_ptr.rs
  clippy_lints/src/checked_conversions.rs
  clippy_lints/src/dereference.rs
  clippy_lints/src/format_args.rs
  clippy_lints/src/from_over_into.rs
  clippy_lints/src/if_then_some_else_none.rs
  clippy_lints/src/index_refutable_slice.rs
  clippy_lints/src/instant_subtraction.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_bits.rs
  clippy_lints/src/manual_clamp.rs
  clippy_lints/src/manual_is_ascii_check.rs
  clippy_lints/src/manual_let_else.rs
  clippy_lints/src/manual_non_exhaustive.rs
  clippy_lints/src/manual_rem_euclid.rs
  clippy_lints/src/manual_retain.rs
  clippy_lints/src/manual_strip.rs
  clippy_lints/src/matches/mod.rs
  clippy_lints/src/mem_replace.rs
  clippy_lints/src/methods/cloned_instead_of_copied.rs
  clippy_lints/src/methods/err_expect.rs
  clippy_lints/src/methods/filter_map_next.rs
  clippy_lints/src/methods/is_digit_ascii_radix.rs
  clippy_lints/src/methods/map_clone.rs
  clippy_lints/src/methods/map_unwrap_or.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/option_as_ref_deref.rs
  clippy_lints/src/methods/str_splitn.rs
  clippy_lints/src/methods/unnecessary_to_owned.rs
  clippy_lints/src/missing_const_for_fn.rs
  clippy_lints/src/ranges.rs
  clippy_lints/src/redundant_field_names.rs
  clippy_lints/src/redundant_static_lifetimes.rs
  clippy_lints/src/transmute/mod.rs
  clippy_lints/src/transmute/transmute_ptr_to_ref.rs
  clippy_lints/src/unnested_or_patterns.rs
  clippy_lints/src/use_self.rs
  clippy_lints/src/utils/internal_lints/msrv_attr_impl.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/msrvs.rs
  clippy_utils/src/paths.rs
  clippy_utils/src/qualify_min_const_fn.rs
  tests/ui-internal/invalid_msrv_attr_impl.fixed
  tests/ui-internal/invalid_msrv_attr_impl.rs
  tests/ui/min_rust_version_attr.rs
  tests/ui/min_rust_version_attr.stderr
Labels: S-waiting-on-review

#3875 RFC: syntax tree patterns
  rfcs/0001-syntax-tree-patterns.md
Labels: S-needs-discussion, C-an-interesting-project, S-waiting-on-review

#9941 Fix remark for `rfcs/0001-syntax-tree-patterns.md`
  rfcs/0001-syntax-tree-patterns.md
Labels: S-waiting-on-review

#9851 Lint unnecessary safety comments
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/undocumented_unsafe_blocks.rs
  clippy_utils/src/visitors.rs
  tests/ui/undocumented_unsafe_blocks.rs
  tests/ui/undocumented_unsafe_blocks.stderr
  tests/ui/unnecessary_safety_comment.rs
  tests/ui/unnecessary_safety_comment.stderr
Labels: S-waiting-on-review

#9944 Move syntax tree patterns RFC to the book
  book/src/SUMMARY.md
  book/src/development/proposals/syntax-tree-patterns.md
  rfcs/0001-syntax-tree-patterns.md
Labels: S-waiting-on-review

#9945 Re-enable `uninlined_format_args` on multiline `format!`
  clippy_lints/src/format_args.rs
  clippy_utils/src/ty.rs
  lintcheck/src/main.rs
  tests/ui/uninlined_format_args.fixed
  tests/ui/uninlined_format_args.stderr
Labels: S-waiting-on-review

#9950 Improve `EXIT` lint docs
  clippy_lints/src/exit.rs
Labels: S-waiting-on-review

#9919 Link to a list of configurable lints in documentation
  README.md
  book/src/configuration.md
Labels: S-waiting-on-review

#9963 Migrate from highfive to triagebot
  triagebot.toml
Labels: S-waiting-on-review

#9967 Remove blank lines when needless_return returns no value
  clippy_lints/src/returns.rs
  tests/ui/needless_return.fixed
  tests/ui/needless_return.rs
  tests/ui/needless_return.stderr
Labels: S-waiting-on-review

#9865 Add allow-mixed-uninlined-format-args config
  clippy_lints/src/format_args.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/conf.rs
  tests/ui-toml/allow_mixed_uninlined_format_args/clippy.toml
  tests/ui-toml/allow_mixed_uninlined_format_args/uninlined_format_args.fixed
  tests/ui-toml/allow_mixed_uninlined_format_args/uninlined_format_args.rs
  tests/ui-toml/allow_mixed_uninlined_format_args/uninlined_format_args.stderr
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
  tests/ui/uninlined_format_args.fixed
  tests/ui/uninlined_format_args.stderr
Labels: S-waiting-on-review

#9980 Don't lint `unnecessary_cast` in mixed macro context
  clippy_lints/src/casts/unnecessary_cast.rs
  tests/ui/unnecessary_cast.fixed
  tests/ui/unnecessary_cast.rs
  tests/ui/unnecessary_cast.stderr
Labels: S-waiting-on-review

#9981 Don't lint `unnecessary_operation` in mixed macro contexts
  clippy_lints/src/no_effect.rs
  tests/ui/unnecessary_operation.fixed
  tests/ui/unnecessary_operation.rs
Labels: S-waiting-on-review

#9975 Move `index_refutable_slice` to `pedantic`
  clippy_lints/src/index_refutable_slice.rs
Labels: S-waiting-on-review

#9989 Move `unnecessary_unsafety_doc` to `pedantic`
  clippy_lints/src/doc.rs
  tests/ui/unnecessary_unsafety_doc.rs
  tests/ui/unnecessary_unsafety_doc.stderr
Labels: S-waiting-on-review, beta-nominated

#9987 Don't cross contexts while building the suggestion for `redundant_closure_call`
  clippy_lints/src/collapsible_if.rs
  clippy_lints/src/redundant_closure_call.rs
  clippy_utils/src/source.rs
  clippy_utils/src/sugg.rs
  tests/ui/redundant_closure_call_fixable.fixed
  tests/ui/redundant_closure_call_fixable.rs
  tests/ui/redundant_closure_call_fixable.stderr
Labels: S-waiting-on-review

#9997 Don't lint `explicit_auto_deref` when the initial type is neither a reference, nor a receiver
  clippy_lints/src/dereference.rs
  tests/ui/explicit_auto_deref.fixed
  tests/ui/explicit_auto_deref.rs
Labels: S-waiting-on-review

#9996 Fix `unnecessary_cast` suggestion when taking a reference
  clippy_lints/src/casts/unnecessary_cast.rs
  tests/ui/unnecessary_cast.fixed
  tests/ui/unnecessary_cast.rs
  tests/ui/unnecessary_cast.stderr
Labels: S-waiting-on-review

#10001 Fix ICE in `unused_rounding`
  clippy_lints/src/unused_rounding.rs
  tests/ui/unused_rounding.fixed
  tests/ui/unused_rounding.rs
  tests/ui/unused_rounding.stderr
Labels: S-waiting-on-review

#9943 manual_let_else: keep macro call on suggestion blocks
  clippy_lints/src/manual_let_else.rs
  tests/ui/manual_let_else.rs
  tests/ui/manual_let_else.stderr
Labels: S-waiting-on-review
