Repository rust-lang/rust-clippy, pull requests merged in 2022-06, with the labels that each got.

#8869 Set correct `ParamEnv` for `derive_partial_eq_without_eq`
  clippy_lints/src/derive.rs
  clippy_utils/src/ty.rs
  tests/ui/derive_partial_eq_without_eq.fixed
  tests/ui/derive_partial_eq_without_eq.rs
Labels: S-waiting-on-review

#8908 Make docs more consistent
  clippy_lints/src/approx_const.rs
  clippy_lints/src/as_conversions.rs
  clippy_lints/src/assign_ops.rs
  clippy_lints/src/attrs.rs
  clippy_lints/src/blocks_in_if_conditions.rs
  clippy_lints/src/booleans.rs
  clippy_lints/src/bytecount.rs
  clippy_lints/src/cognitive_complexity.rs
  clippy_lints/src/collapsible_if.rs
  clippy_lints/src/comparison_chain.rs
  clippy_lints/src/copies.rs
  clippy_lints/src/derivable_impls.rs
  clippy_lints/src/double_comparison.rs
  clippy_lints/src/double_parens.rs
  clippy_lints/src/duration_subsec.rs
  clippy_lints/src/else_if_without_else.rs
  clippy_lints/src/empty_enum.rs
  clippy_lints/src/entry.rs
  clippy_lints/src/enum_variants.rs
  clippy_lints/src/eq_op.rs
  clippy_lints/src/equatable_if_let.rs
  clippy_lints/src/escape.rs
  clippy_lints/src/excessive_bools.rs
  clippy_lints/src/explicit_write.rs
  clippy_lints/src/fallible_impl_from.rs
  clippy_lints/src/float_literal.rs
  clippy_lints/src/floating_point_arithmetic.rs
  clippy_lints/src/format.rs
  clippy_lints/src/formatting.rs
  clippy_lints/src/loops/mod.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/minmax.rs
  clippy_lints/src/misc.rs
  clippy_lints/src/mutable_debug_assertion.rs
  clippy_lints/src/trait_bounds.rs
  doc/adding_lints.md
Labels: S-waiting-on-review

#8905 [1/N] Implement Arithmetic lint
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_restriction.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/numeric_arithmetic.rs
Labels: S-waiting-on-review

#8906 remove `large_enum_variant` suggestion for `Copy` types
  clippy_lints/src/large_enum_variant.rs
  tests/ui/large_enum_variant.rs
  tests/ui/large_enum_variant.stderr
Labels: S-waiting-on-review

#8902 When setting suggestion for significant_drop_in_scrutinee, add suggestion for MoveAndClone for non-ref
  clippy_lints/src/significant_drop_in_scrutinee.rs
  clippy_utils/src/lib.rs
  tests/ui/significant_drop_in_scrutinee.rs
  tests/ui/significant_drop_in_scrutinee.stderr
Labels: S-waiting-on-review

#8932 `needless_return` checks for macro expr in return stmts
  clippy_lints/src/methods/option_map_or_none.rs
  clippy_lints/src/returns.rs
  tests/ui/needless_return.fixed
  tests/ui/needless_return.rs
  tests/ui/needless_return.stderr
Labels: S-waiting-on-review

#8831 Add new lint `mismatching_type_param_order`
  CHANGELOG.md
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_pedantic.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/mismatching_type_param_order.rs
  tests/ui/mismatching_type_param_order.rs
  tests/ui/mismatching_type_param_order.stderr
Labels: S-waiting-on-review

#8934 add [`as_underscore`] lint
  CHANGELOG.md
  clippy_lints/src/as_underscore.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_restriction.rs
  clippy_lints/src/lib.rs
  tests/ui/as_underscore.fixed
  tests/ui/as_underscore.rs
  tests/ui/as_underscore.stderr
Labels: S-waiting-on-review

#8937 Merge various passes into `Matches`
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_complexity.rs
  clippy_lints/src/lib.register_correctness.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_pedantic.rs
  clippy_lints/src/lib.register_restriction.rs
  clippy_lints/src/lib.register_style.rs
  clippy_lints/src/lib.register_suspicious.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_map.rs
  clippy_lints/src/manual_unwrap_or.rs
  clippy_lints/src/match_on_vec_items.rs
  clippy_lints/src/matches/collapsible_match.rs
  clippy_lints/src/matches/manual_map.rs
  clippy_lints/src/matches/manual_unwrap_or.rs
  clippy_lints/src/matches/match_like_matches.rs
  clippy_lints/src/matches/match_on_vec_items.rs
  clippy_lints/src/matches/match_str_case_mismatch.rs
  clippy_lints/src/matches/mod.rs
  clippy_lints/src/matches/needless_match.rs
  clippy_lints/src/matches/redundant_pattern_match.rs
  clippy_lints/src/matches/significant_drop_in_scrutinee.rs
  clippy_lints/src/matches/try_err.rs
  clippy_lints/src/try_err.rs
Labels: S-waiting-on-review

#8843 Collect renamed lints
  clippy_lints/src/utils/internal_lints/metadata_collector.rs
Labels: S-waiting-on-review

#8930 fix(manual_find_map and manual_filter_map): check clone method
  clippy_lints/src/methods/filter_map.rs
  tests/ui/manual_filter_map.fixed
  tests/ui/manual_filter_map.rs
  tests/ui/manual_filter_map.stderr
  tests/ui/manual_find_map.fixed
  tests/ui/manual_find_map.rs
  tests/ui/manual_find_map.stderr
Labels: S-waiting-on-review

#8941 improve [`for_loops_over_fallibles`] to detect the usage of iter, iter_mut and into_iterator
  clippy_lints/src/loops/for_loops_over_fallibles.rs
  clippy_lints/src/loops/mod.rs
  tests/ui/for_loops_over_fallibles.rs
  tests/ui/for_loops_over_fallibles.stderr
  tests/ui/manual_map_option.fixed
  tests/ui/manual_map_option.rs
  tests/ui/manual_map_option.stderr
Labels: S-waiting-on-review

#8951 Some refactoring in `needless_late_init`
  clippy_lints/src/needless_late_init.rs
Labels: S-waiting-on-review

#8933 Add new lint [`needless_parens_on_range_literals`]
  CHANGELOG.md
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_style.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/needless_parens_on_range_literals.rs
  tests/ui/almost_complete_letter_range.fixed
  tests/ui/almost_complete_letter_range.rs
  tests/ui/almost_complete_letter_range.stderr
  tests/ui/needless_parens_on_range_literals.fixed
  tests/ui/needless_parens_on_range_literals.rs
  tests/ui/needless_parens_on_range_literals.stderr
Labels: S-waiting-on-review

#8944 List configuration values can now be extended instead of replaced
  clippy_lints/src/utils/conf.rs
  tests/ui-toml/blacklisted_names_append/blacklisted_names.rs
  tests/ui-toml/blacklisted_names_append/blacklisted_names.stderr
  tests/ui-toml/blacklisted_names_append/clippy.toml
  tests/ui-toml/blacklisted_names_replace/blacklisted_names.rs
  tests/ui-toml/blacklisted_names_replace/blacklisted_names.stderr
  tests/ui-toml/blacklisted_names_replace/clippy.toml
  tests/ui-toml/doc_valid_idents_append/clippy.toml
  tests/ui-toml/doc_valid_idents_append/doc_markdown.rs
  tests/ui-toml/doc_valid_idents_append/doc_markdown.stderr
  tests/ui-toml/doc_valid_idents_replace/clippy.toml
  tests/ui-toml/doc_valid_idents_replace/doc_markdown.rs
  tests/ui-toml/doc_valid_idents_replace/doc_markdown.stderr
Labels: S-waiting-on-review

#7359 Clippy book
  .gitignore
  CONTRIBUTING.md
  book/README.md
  book/book.toml
  book/src/README.md
  book/src/SUMMARY.md
  book/src/configuration.md
  book/src/continuous_integration/README.md
  book/src/continuous_integration/github_actions.md
  book/src/continuous_integration/travis.md
  book/src/development/README.md
  book/src/development/adding_lints.md
  book/src/development/basics.md
  book/src/development/common_tools_writing_lints.md
  book/src/development/infrastructure/README.md
  book/src/development/infrastructure/backport.md
  book/src/development/infrastructure/book.md
  book/src/development/infrastructure/changelog_update.md
  book/src/development/infrastructure/release.md
  book/src/development/infrastructure/sync.md
  book/src/development/proposals/README.md
  book/src/development/proposals/roadmap-2021.md
  book/src/installation.md
  book/src/lints.md
  book/src/usage.md
  clippy_dev/src/update_lints.rs
Labels: S-waiting-on-review

#8960 Changes to `iter_overeager_cloned`
  clippy_lints/src/methods/iter_overeager_cloned.rs
  clippy_lints/src/methods/mod.rs
  clippy_utils/src/ty.rs
  tests/ui/iter_overeager_cloned.fixed
  tests/ui/iter_overeager_cloned.rs
  tests/ui/iter_overeager_cloned.stderr
Labels: S-waiting-on-review

#8950 Fixes for `derive_partial_eq_without_eq`
  clippy_lints/src/derive.rs
  tests/ui/derive_partial_eq_without_eq.fixed
  tests/ui/derive_partial_eq_without_eq.rs
  tests/ui/derive_partial_eq_without_eq.stderr
Labels: S-waiting-on-review

#8907 fix(lint): check const context
  clippy_lints/src/checked_conversions.rs
  tests/ui/checked_conversions.fixed
  tests/ui/checked_conversions.rs
Labels: S-waiting-on-review

#8979 Correct some `#[clippy::version]`s
  clippy_lints/src/casts/mod.rs
  clippy_lints/src/doc.rs
  clippy_lints/src/index_refutable_slice.rs
  clippy_lints/src/loops/mod.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/needless_late_init.rs
  clippy_lints/src/octal_escapes.rs
  clippy_lints/src/only_used_in_recursion.rs
  clippy_lints/src/redundant_slicing.rs
  clippy_lints/src/single_char_lifetime_names.rs
Labels: S-waiting-on-review

#8983 Add tests for some fixed `redundant_closure` issues
  tests/ui/eta.fixed
  tests/ui/eta.rs
Labels: S-waiting-on-review

#8997 Fix `clap` deprecation warnings
  clippy_dev/src/lint.rs
  clippy_dev/src/main.rs
  clippy_dev/src/new_lint.rs
  clippy_dev/src/serve.rs
  lintcheck/src/config.rs
Labels: S-waiting-on-review

#8901 Rework `branches_sharing_code`
  clippy_lints/src/copies.rs
  clippy_utils/src/hir_utils.rs
  clippy_utils/src/lib.rs
  tests/ui/branches_sharing_code/false_positives.rs
  tests/ui/branches_sharing_code/shared_at_bottom.stderr
  tests/ui/branches_sharing_code/shared_at_top.stderr
  tests/ui/branches_sharing_code/shared_at_top_and_bottom.stderr
Labels: S-waiting-on-review

#8999 Remove error-pattern comments
  clippy_lints/src/lib.rs
  tests/ui-toml/bad_toml/conf_bad_toml.rs
  tests/ui-toml/bad_toml_type/conf_bad_type.rs
  tests/ui-toml/conf_deprecated_key/conf_deprecated_key.rs
  tests/ui-toml/good_toml_no_false_negatives/conf_no_false_negatives.rs
  tests/ui-toml/toml_unknown_key/conf_unknown_key.rs
Labels: S-waiting-on-review

#8964 Warn about read into zero-length `Vec`
  CHANGELOG.md
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_correctness.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/read_zero_byte_vec.rs
  tests/ui/read_zero_byte_vec.rs
  tests/ui/read_zero_byte_vec.stderr
Labels: S-waiting-on-review

#8989 feat(lint): add default_iter_empty
  CHANGELOG.md
  clippy_lints/src/default_instead_of_iter_empty.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_style.rs
  clippy_lints/src/lib.rs
  clippy_utils/src/paths.rs
  tests/ui/default_instead_of_iter_empty.fixed
  tests/ui/default_instead_of_iter_empty.rs
  tests/ui/default_instead_of_iter_empty.stderr
Labels: S-waiting-on-review

#9016 Use `RefCell` in `needless_return` tests
  tests/ui/needless_return.fixed
  tests/ui/needless_return.rs
  tests/ui/needless_return.stderr
Labels: S-waiting-on-review

#9023 Add description meta tag for lint list
  util/gh-pages/index.html
Labels: S-waiting-on-review

#9025 unused_async: lint async methods
  clippy_lints/src/unused_async.rs
  tests/ui/methods.rs
  tests/ui/methods.stderr
  tests/ui/should_impl_trait/corner_cases.rs
  tests/ui/unused_async.rs
  tests/ui/unused_async.stderr
Labels: S-waiting-on-review

#9006 feat(fix): ignore `todo!` and `unimplemented!` in `if_same_then_else`
  clippy_utils/src/hir_utils.rs
  tests/ui/if_same_then_else.rs
  tests/ui/if_same_then_else.stderr
Labels: S-waiting-on-review

#9017 Example for `WHILE_LET_ON_ITERATOR`
  clippy_lints/src/loops/mod.rs
Labels: S-waiting-on-review

#9026 put parentheses around neg_multiply suggestion if needed
  clippy_lints/src/neg_multiply.rs
  tests/ui/neg_multiply.fixed
  tests/ui/neg_multiply.rs
  tests/ui/neg_multiply.stderr
Labels: S-waiting-on-review

#9028 confirm using chain in collapsible_span_lint_calls
  clippy_lints/src/utils/internal_lints.rs
  tests/ui-internal/collapsible_span_lint_calls.fixed
  tests/ui-internal/collapsible_span_lint_calls.rs
Labels: S-waiting-on-review

#9034 Example for VEC_RESIZE_TO_ZERO
  clippy_lints/src/vec_resize_to_zero.rs
Labels: S-waiting-on-review

#8953 add vec.capacity() to [`slow_vec_initialization`] detection
  clippy_lints/src/slow_vector_initialization.rs
  tests/ui/slow_vector_initialization.rs
  tests/ui/slow_vector_initialization.stderr
Labels: S-waiting-on-review

#9036 Check for `--force-warn` in Clippy's driver run condition
  src/driver.rs
Labels: S-waiting-on-review

#9037 Fix `extra_unused_lifetimes` false positive
  clippy_lints/src/lifetimes.rs
Labels: S-waiting-on-review

#9031 Add [`manual_rem_euclid`] lint
  CHANGELOG.md
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_complexity.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_rem_euclid.rs
  clippy_utils/src/msrvs.rs
  tests/ui/auxiliary/macro_rules.rs
  tests/ui/manual_rem_euclid.fixed
  tests/ui/manual_rem_euclid.rs
  tests/ui/manual_rem_euclid.stderr
  tests/ui/min_rust_version_attr.rs
  tests/ui/min_rust_version_attr.stderr
Labels: S-waiting-on-review

#9015 ignore item in `thread_local!` macro
  clippy_lints/src/non_copy_const.rs
  tests/ui/declare_interior_mutable_const/others.rs
Labels: S-waiting-on-review

#8985 Lint `[single_match]` on `Option` matches
  clippy_lints/src/matches/single_match.rs
  tests/ui/single_match.stderr
  tests/ui/single_match_else.rs
  tests/ui/single_match_else.stderr
Labels: S-waiting-on-review

#9055 update node.js version in `remark.yml`
  .github/workflows/remark.yml
Labels: S-waiting-on-review

#9032 enum_variant_names should ignore when all prefixes are _
  clippy_lints/src/enum_variants.rs
  tests/ui/enum_variants.rs
  tests/ui/enum_variants.stderr
Labels: S-waiting-on-review

#8871 Add `cargo dev deprecate`
  clippy_dev/Cargo.toml
  clippy_dev/src/main.rs
  clippy_dev/src/new_lint.rs
  clippy_dev/src/update_lints.rs
  clippy_lints/src/deprecated_lints.rs
  clippy_lints/src/lib.register_internal.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/internal_lints.rs
  clippy_lints/src/utils/internal_lints/metadata_collector.rs
  tests/compile-test.rs
  tests/ui-internal/default_deprecation_reason.rs
  tests/ui-internal/default_deprecation_reason.stderr
Labels: S-waiting-on-review

#9054 STRING_ADD example
  clippy_lints/src/strings.rs
Labels: S-waiting-on-review

#8990 Fix `let_undescore_lock` false-positive when binding without locking
  clippy_lints/src/let_underscore.rs
  clippy_utils/src/paths.rs
  tests/ui/let_underscore_lock.rs
  tests/ui/let_underscore_lock.stderr
Labels: S-waiting-on-review

#8972 feat(new lint): new lint `manual_retain`
  CHANGELOG.md
  README.md
  book/src/README.md
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_perf.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_retain.rs
  clippy_utils/src/msrvs.rs
  clippy_utils/src/paths.rs
  tests/ui/manual_retain.fixed
  tests/ui/manual_retain.rs
  tests/ui/manual_retain.stderr
Labels: S-waiting-on-review

#8649 add [`manual_find`] lint for function return case
  CHANGELOG.md
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_complexity.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/loops/manual_find.rs
  clippy_lints/src/loops/mod.rs
  clippy_lints/src/non_expressive_names.rs
  tests/ui/manual_find.rs
  tests/ui/manual_find.stderr
  tests/ui/manual_find_fixable.fixed
  tests/ui/manual_find_fixable.rs
  tests/ui/manual_find_fixable.stderr
  tests/ui/while_let_on_iterator.fixed
  tests/ui/while_let_on_iterator.rs
  tests/ui/while_let_on_iterator.stderr
Labels: S-waiting-on-author

#9045 Fix example `SELF_ASSIGNMENT`
  clippy_lints/src/self_assignment.rs
Labels: S-waiting-on-review

#8639 `trivially_copy_pass_by_ref` fixes
  clippy_lints/src/lib.rs
  clippy_lints/src/pass_by_ref_or_value.rs
  clippy_utils/src/ty.rs
  tests/ui/trivially_copy_pass_by_ref.rs
  tests/ui/trivially_copy_pass_by_ref.stderr
Labels: S-waiting-on-review

#8774 try reading rust-version from Cargo.toml
  Cargo.toml
  README.md
  clippy_lints/src/lib.rs
  tests/compile-test.rs
  tests/ui-cargo/cargo_rust_version/fail_both_diff/Cargo.toml
  tests/ui-cargo/cargo_rust_version/fail_both_diff/clippy.toml
  tests/ui-cargo/cargo_rust_version/fail_both_diff/src/main.rs
  tests/ui-cargo/cargo_rust_version/fail_both_diff/src/main.stderr
  tests/ui-cargo/cargo_rust_version/fail_both_same/Cargo.toml
  tests/ui-cargo/cargo_rust_version/fail_both_same/clippy.toml
  tests/ui-cargo/cargo_rust_version/fail_both_same/src/main.rs
  tests/ui-cargo/cargo_rust_version/fail_both_same/src/main.stderr
  tests/ui-cargo/cargo_rust_version/fail_cargo/Cargo.toml
  tests/ui-cargo/cargo_rust_version/fail_cargo/src/main.rs
  tests/ui-cargo/cargo_rust_version/fail_cargo/src/main.stderr
  tests/ui-cargo/cargo_rust_version/fail_clippy/Cargo.toml
  tests/ui-cargo/cargo_rust_version/fail_clippy/clippy.toml
  tests/ui-cargo/cargo_rust_version/fail_clippy/src/main.rs
  tests/ui-cargo/cargo_rust_version/fail_clippy/src/main.stderr
  tests/ui-cargo/cargo_rust_version/fail_file_attr/Cargo.toml
  tests/ui-cargo/cargo_rust_version/fail_file_attr/clippy.toml
  tests/ui-cargo/cargo_rust_version/fail_file_attr/src/main.rs
  tests/ui-cargo/cargo_rust_version/fail_file_attr/src/main.stderr
  tests/ui-cargo/cargo_rust_version/pass_both_same/Cargo.toml
  tests/ui-cargo/cargo_rust_version/pass_both_same/clippy.toml
  tests/ui-cargo/cargo_rust_version/pass_both_same/src/main.rs
  tests/ui-cargo/cargo_rust_version/pass_cargo/Cargo.toml
  tests/ui-cargo/cargo_rust_version/pass_cargo/src/main.rs
  tests/ui-cargo/cargo_rust_version/pass_clippy/Cargo.toml
  tests/ui-cargo/cargo_rust_version/pass_clippy/clippy.toml
  tests/ui-cargo/cargo_rust_version/pass_clippy/src/main.rs
  tests/ui-cargo/cargo_rust_version/pass_file_attr/Cargo.toml
  tests/ui-cargo/cargo_rust_version/pass_file_attr/src/main.rs
  tests/ui-cargo/cargo_rust_version/warn_both_diff/Cargo.toml
  tests/ui-cargo/cargo_rust_version/warn_both_diff/clippy.toml
  tests/ui-cargo/cargo_rust_version/warn_both_diff/src/main.rs
  tests/ui-cargo/cargo_rust_version/warn_both_diff/src/main.stderr
  tests/ui-cargo/multiple_config_files/warn/src/main.stderr
Labels: S-waiting-on-review

#8921 Add `Operators` lint pass
  clippy_lints/src/assign_ops.rs
  clippy_lints/src/double_comparison.rs
  clippy_lints/src/duration_subsec.rs
  clippy_lints/src/eq_op.rs
  clippy_lints/src/erasing_op.rs
  clippy_lints/src/float_equality_without_abs.rs
  clippy_lints/src/integer_division.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_complexity.rs
  clippy_lints/src/lib.register_correctness.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_pedantic.rs
  clippy_lints/src/lib.register_perf.rs
  clippy_lints/src/lib.register_restriction.rs
  clippy_lints/src/lib.register_style.rs
  clippy_lints/src/lib.register_suspicious.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/misc.rs
  clippy_lints/src/needless_bitwise_bool.rs
  clippy_lints/src/numeric_arithmetic.rs
  clippy_lints/src/operators/absurd_extreme_comparisons.rs
  clippy_lints/src/operators/assign_op_pattern.rs
  clippy_lints/src/operators/bit_mask.rs
  clippy_lints/src/operators/cmp_nan.rs
  clippy_lints/src/operators/cmp_owned.rs
  clippy_lints/src/operators/double_comparison.rs
  clippy_lints/src/operators/duration_subsec.rs
  clippy_lints/src/operators/eq_op.rs
  clippy_lints/src/operators/erasing_op.rs
  clippy_lints/src/operators/float_cmp.rs
  clippy_lints/src/operators/float_equality_without_abs.rs
  clippy_lints/src/operators/identity_op.rs
  clippy_lints/src/operators/integer_division.rs
  clippy_lints/src/operators/misrefactored_assign_op.rs
  clippy_lints/src/operators/mod.rs
  clippy_lints/src/operators/modulo_arithmetic.rs
  clippy_lints/src/operators/modulo_one.rs
  clippy_lints/src/operators/needless_bitwise_bool.rs
  clippy_lints/src/operators/numeric_arithmetic.rs
  clippy_lints/src/operators/op_ref.rs
  clippy_lints/src/operators/ptr_eq.rs
  clippy_lints/src/operators/self_assignment.rs
  clippy_lints/src/operators/verbose_bit_mask.rs
  clippy_lints/src/ptr_eq.rs
  clippy_lints/src/self_assignment.rs
  tests/ui/zero_div_zero.rs
  tests/ui/zero_div_zero.stderr
Labels: S-waiting-on-review

#8355 Add lint `explicit_auto_deref` take 2
  CHANGELOG.md
  clippy_dev/src/update_lints.rs
  clippy_lints/src/dereference.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_complexity.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/matches/match_same_arms.rs
  clippy_lints/src/matches/match_single_binding.rs
  clippy_lints/src/matches/match_str_case_mismatch.rs
  clippy_lints/src/matches/redundant_pattern_match.rs
  clippy_lints/src/non_expressive_names.rs
  clippy_lints/src/ptr.rs
  clippy_lints/src/redundant_static_lifetimes.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/ty.rs
  tests/ui/explicit_auto_deref.fixed
  tests/ui/explicit_auto_deref.rs
  tests/ui/explicit_auto_deref.stderr
  tests/ui/explicit_deref_methods.fixed
  tests/ui/explicit_deref_methods.rs
  tests/ui/explicit_deref_methods.stderr
  tests/ui/needless_borrow.fixed
  tests/ui/needless_borrow.rs
  tests/ui/needless_borrow.stderr
  tests/ui/needless_borrow_pat.rs
  tests/ui/ref_binding_to_reference.rs
  tests/ui/search_is_some_fixable_none.fixed
  tests/ui/search_is_some_fixable_none.rs
  tests/ui/search_is_some_fixable_some.fixed
  tests/ui/search_is_some_fixable_some.rs
  tests/ui/useless_asref.fixed
  tests/ui/useless_asref.rs
  tests/ui/useless_asref.stderr
Labels: S-waiting-on-author

#8981 Add details about how significant drop in match scrutinees can cause deadlocks
  clippy_lints/src/matches/mod.rs
  clippy_lints/src/matches/significant_drop_in_scrutinee.rs
  tests/ui/significant_drop_in_scrutinee.rs
  tests/ui/significant_drop_in_scrutinee.stderr
Labels: S-waiting-on-author

#9043 `extra_unused_lifetimes` add FP test case emitting from derived attributes.
  tests/ui/auxiliary/proc_macro_derive.rs
  tests/ui/extra_unused_lifetimes.rs
  tests/ui/extra_unused_lifetimes.stderr
Labels: S-waiting-on-review

#8666 Don't lint `while_let_loop` when significant drop order would change
  clippy_lints/src/loops/while_let_loop.rs
  clippy_lints/src/matches/redundant_pattern_match.rs
  clippy_utils/src/visitors.rs
  tests/ui/while_let_loop.rs
Labels: S-waiting-on-review

#9068 fix typo in Clippy Lints page
  clippy_lints/src/large_const_arrays.rs
  clippy_lints/src/matches/mod.rs
Labels: S-waiting-on-review

#9070 Make sure bors success depends on metadata_collection
  .github/workflows/clippy_bors.yml
Labels: S-waiting-on-review

#9071 Uncomment test for #8734
  tests/ui/map_flatten_fixable.fixed
  tests/ui/map_flatten_fixable.rs
  tests/ui/map_flatten_fixable.stderr
Labels: S-waiting-on-review

#9074 Fix false-positive in `equatable_if_let`
  clippy_lints/src/equatable_if_let.rs
  tests/ui/auxiliary/macro_rules.rs
  tests/ui/equatable_if_let.fixed
  tests/ui/equatable_if_let.rs
  tests/ui/equatable_if_let.stderr
Labels: S-waiting-on-review

#9058 Changelog for Rust 1.62 :t-rex:
  CHANGELOG.md
Labels: S-blocked

#9078 Fix broken hyperlink in documentation
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-review

#9075 Add `dev deprecate` to the development basics
  book/src/development/basics.md
Labels: S-waiting-on-review
