Repository rust-lang/rust-clippy, pull requests merged in 2022-02, with the labels that each got.

#8330 Update Changelog
  CHANGELOG.md
Labels: S-waiting-on-review

#8387 Fix ICE in `ptr_arg`
  clippy_lints/src/ptr.rs
  tests/ui/crashes/ice-8386.rs
Labels: S-waiting-on-review

#8370 Format `if_chain` invocations in clippy_utils
  clippy_utils/src/consts.rs
  clippy_utils/src/higher.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/macros.rs
Labels: S-waiting-on-review

#8382 [explicit_counter_loop] suggests `.into_iter()`, despite that triggering [into_iter_on_ref] in some cases
  clippy_lints/src/loops/utils.rs
  tests/ui/explicit_counter_loop.stderr
  tests/ui/manual_flatten.rs
  tests/ui/manual_flatten.stderr
Labels: S-waiting-on-review

#8376 [`chars_next_cmp`] Fix unescaped suggestion
  clippy_lints/src/methods/chars_cmp_with_unwrap.rs
  tests/ui/starts_ends_with.fixed
  tests/ui/starts_ends_with.rs
  tests/ui/starts_ends_with.stderr
Labels: S-waiting-on-review

#8372 make unwrap_used also trigger on .get().unwrap()
  clippy_lints/src/methods/mod.rs
  tests/ui/get_unwrap.fixed
  tests/ui/get_unwrap.rs
  tests/ui/get_unwrap.stderr
Labels: S-waiting-on-review

#8365 Add `explicit_write` suggestions for `write!`s with format args
  clippy_lints/src/explicit_write.rs
  clippy_utils/src/macros.rs
  tests/ui/expect_fun_call.fixed
  tests/ui/expect_fun_call.rs
  tests/ui/expect_fun_call.stderr
  tests/ui/explicit_write.fixed
  tests/ui/explicit_write.rs
  tests/ui/explicit_write.stderr
  tests/ui/explicit_write_non_rustfix.rs
  tests/ui/explicit_write_non_rustfix.stderr
  tests/ui/manual_assert.edition2018.fixed
  tests/ui/manual_assert.edition2018.stderr
  tests/ui/manual_assert.edition2021.fixed
  tests/ui/manual_assert.edition2021.stderr
  tests/ui/manual_assert.rs
Labels: S-waiting-on-review

#8398 Add lint `transmute_undefined_repr`
  CHANGELOG.md
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_correctness.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/transmute/mod.rs
  clippy_lints/src/transmute/transmute_float_to_int.rs
  clippy_lints/src/transmute/transmute_int_to_bool.rs
  clippy_lints/src/transmute/transmute_int_to_char.rs
  clippy_lints/src/transmute/transmute_int_to_float.rs
  clippy_lints/src/transmute/transmute_num_to_bytes.rs
  clippy_lints/src/transmute/transmute_ptr_to_ptr.rs
  clippy_lints/src/transmute/transmute_ptr_to_ref.rs
  clippy_lints/src/transmute/transmute_ref_to_ref.rs
  clippy_lints/src/transmute/transmute_undefined_repr.rs
  clippy_lints/src/transmute/transmutes_expressible_as_ptr_casts.rs
  clippy_lints/src/transmute/useless_transmute.rs
  tests/ui/crashes/ice-4968.rs
  tests/ui/transmute_undefined_repr.rs
  tests/ui/transmute_undefined_repr.stderr
Labels: S-waiting-on-review

#8326 warn if we find multiple clippy configs
  clippy_lints/src/utils/conf.rs
  tests/ui-cargo/multiple_config_files/no_warn/Cargo.toml
  tests/ui-cargo/multiple_config_files/no_warn/clippy.toml
  tests/ui-cargo/multiple_config_files/no_warn/src/main.rs
  tests/ui-cargo/multiple_config_files/warn/.clippy.toml
  tests/ui-cargo/multiple_config_files/warn/Cargo.toml
  tests/ui-cargo/multiple_config_files/warn/clippy.toml
  tests/ui-cargo/multiple_config_files/warn/src/main.rs
  tests/ui-cargo/multiple_config_files/warn/src/main.stderr
Labels: S-waiting-on-review

#8400 Split matches
  clippy_lints/src/matches.rs
  clippy_lints/src/matches/infalliable_detructuring_match.rs
  clippy_lints/src/matches/match_as_ref.rs
  clippy_lints/src/matches/match_bool.rs
  clippy_lints/src/matches/match_like_matches.rs
  clippy_lints/src/matches/match_ref_pats.rs
  clippy_lints/src/matches/match_same_arms.rs
  clippy_lints/src/matches/match_single_binding.rs
  clippy_lints/src/matches/match_wild_enum.rs
  clippy_lints/src/matches/match_wild_err_arm.rs
  clippy_lints/src/matches/mod.rs
  clippy_lints/src/matches/overlapping_arms.rs
  clippy_lints/src/matches/redundant_pattern_match.rs
  clippy_lints/src/matches/rest_pat_in_fully_bound_struct.rs
  clippy_lints/src/matches/single_match.rs
  clippy_lints/src/matches/wild_in_or_pats.rs
Labels: S-waiting-on-review

#8374 Support `cargo dev bless` for tests with revisions
  clippy_dev/src/bless.rs
  tests/compile-test.rs
  tests/ui/non_expressive_names.stdout
Labels: S-waiting-on-review

#8404 Factor out ui_test suite
  clippy_utils/src/lib.rs
  tests/compile-test.rs
  tests/ui/eq_op.rs
  tests/ui/eq_op.stderr
  tests/ui_test/eq_op.rs
Labels: S-waiting-on-review

#8411 Migrate `dbg_macro` to late pass
  clippy_lints/src/dbg_macro.rs
  clippy_lints/src/lib.rs
  tests/ui/dbg_macro.rs
  tests/ui/dbg_macro.stderr
Labels: S-waiting-on-review

#8418 Downgrade transmute_undefined_repr to nursery
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_correctness.rs
  clippy_lints/src/lib.register_nursery.rs
  clippy_lints/src/transmute/mod.rs
Labels: S-waiting-on-review

#8421 Replace a few paths with diagnostic items
  clippy_lints/src/derive.rs
  clippy_lints/src/duration_subsec.rs
  clippy_lints/src/infinite_iter.rs
  clippy_lints/src/minmax.rs
  clippy_lints/src/types/borrowed_box.rs
  clippy_utils/src/paths.rs
Labels: S-waiting-on-review

#8429 Document `pub` requirement for `new_without_default` lint
  clippy_lints/src/new_without_default.rs
  tests/ui/new_without_default.rs
  tests/ui/new_without_default.stderr
Labels: S-waiting-on-review

#8427 Merge cargo lints
  clippy_lints/src/cargo/common_metadata.rs
  clippy_lints/src/cargo/feature_name.rs
  clippy_lints/src/cargo/mod.rs
  clippy_lints/src/cargo/multiple_crate_versions.rs
  clippy_lints/src/cargo/wildcard_dependencies.rs
  clippy_lints/src/cargo_common_metadata.rs
  clippy_lints/src/feature_name.rs
  clippy_lints/src/lib.register_cargo.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/multiple_crate_versions.rs
  clippy_lints/src/wildcard_dependencies.rs
  clippy_utils/src/lib.rs
Labels: S-waiting-on-review

#8425 Fix `transmute_undefined_repr` with single field `#[repr(C)]` structs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_correctness.rs
  clippy_lints/src/lib.register_nursery.rs
  clippy_lints/src/transmute/mod.rs
  clippy_lints/src/transmute/transmute_undefined_repr.rs
  tests/ui/transmute_undefined_repr.rs
Labels: S-waiting-on-review

#8188 new lint: `recursive_format_impl`
  CHANGELOG.md
  clippy_lints/src/format_args.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_correctness.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/recursive_format_impl.rs
  clippy_lints/src/to_string_in_display.rs
  clippy_utils/src/macros.rs
  clippy_utils/src/paths.rs
  tests/ui/recursive_format_impl.rs
  tests/ui/recursive_format_impl.stderr
  tests/ui/rename.fixed
  tests/ui/rename.rs
  tests/ui/rename.stderr
  tests/ui/to_string_in_display.rs
  tests/ui/to_string_in_display.stderr
Labels: S-waiting-on-review

#8433 Don't lint Default::default if it is the udpate syntax base
  clippy_lints/src/default.rs
  tests/ui/default_trait_access.fixed
  tests/ui/default_trait_access.rs
Labels: S-waiting-on-review

#8441 Don't lint `needless_borrow` in method receiver positions
  clippy_lints/src/dereference.rs
  tests/ui/needless_borrow.fixed
  tests/ui/needless_borrow.rs
  tests/ui/needless_borrow.stderr
Labels: S-waiting-on-review

#8442 trigger `ptr_as_ptr` inside macros
  clippy_lints/src/casts/mod.rs
  tests/ui/auxiliary/macro_rules.rs
  tests/ui/ptr_as_ptr.fixed
  tests/ui/ptr_as_ptr.rs
  tests/ui/ptr_as_ptr.stderr
Labels: S-waiting-on-review

#8381 Lint enum-to-int casts with `cast_possible_truncation`
  CHANGELOG.md
  clippy_lints/src/casts/cast_possible_truncation.rs
  clippy_lints/src/casts/mod.rs
  clippy_lints/src/casts/utils.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_suspicious.rs
  clippy_lints/src/lib.rs
  clippy_utils/src/ty.rs
  tests/ui/cast.rs
  tests/ui/cast.stderr
Labels: S-waiting-on-review

#8440 Some more fixes for `transmute_undefined_repr`
  clippy_lints/src/casts/cast_ptr_alignment.rs
  clippy_lints/src/transmute/transmute_undefined_repr.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/ty.rs
  tests/ui/transmute_undefined_repr.rs
  tests/ui/transmute_undefined_repr.stderr
Labels: S-waiting-on-review

#8443 Don't lint `match` expressions with `cfg`ed arms
  clippy_lints/src/matches/match_like_matches.rs
  clippy_lints/src/matches/match_same_arms.rs
  clippy_lints/src/matches/match_single_binding.rs
  clippy_lints/src/matches/mod.rs
  clippy_lints/src/matches/redundant_pattern_match.rs
  tests/ui/match_as_ref.fixed
  tests/ui/match_as_ref.rs
  tests/ui/match_bool.rs
  tests/ui/match_expr_like_matches_macro.fixed
  tests/ui/match_expr_like_matches_macro.rs
  tests/ui/match_same_arms2.rs
  tests/ui/match_single_binding.fixed
  tests/ui/match_single_binding.rs
  tests/ui/match_single_binding.stderr
  tests/ui/single_match.rs
Labels: S-waiting-on-author

#8451 tests: default to more threads for ui-tests
  Cargo.toml
  tests/compile-test.rs
Labels: S-needs-discussion, S-waiting-on-review

#8466 False positive redundant_closure when using ref pattern in closure params
  clippy_lints/src/eta_reduction.rs
  tests/ui/eta.fixed
  tests/ui/eta.rs
Labels: S-waiting-on-review

#8474 Replace some more paths with diagnostic items
  clippy_lints/src/drop_forget_ref.rs
  clippy_lints/src/manual_bits.rs
  clippy_lints/src/mem_forget.rs
  clippy_lints/src/mem_replace.rs
  clippy_lints/src/methods/uninit_assumed_init.rs
  clippy_lints/src/redundant_clone.rs
  clippy_lints/src/size_of_in_element_count.rs
  clippy_lints/src/undropped_manually_drops.rs
  clippy_utils/src/macros.rs
  clippy_utils/src/paths.rs
Labels: S-waiting-on-review

#8253 Add `print_in_format_impl` lint
  CHANGELOG.md
  clippy_lints/src/format_impl.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_correctness.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_suspicious.rs
  clippy_lints/src/lib.rs
  tests/ui/print_in_format_impl.rs
  tests/ui/print_in_format_impl.stderr
Labels: S-waiting-on-review

#8453 fix false positives of large_enum_variant
  clippy_lints/src/large_enum_variant.rs
  tests/ui/large_enum_variant.rs
  tests/ui/large_enum_variant.stderr
Labels: S-waiting-on-review

#8464 Fix `ptr_arg`
  clippy_lints/src/ptr.rs
  tests/ui/ptr_arg.rs
Labels: S-waiting-on-review

#8476 Update edition in rustfmt.toml
  rustfmt.toml
Labels: S-waiting-on-review

#8479 Fix some `unnecessary_filter_map` false positives
  clippy_lints/src/methods/unnecessary_filter_map.rs
  clippy_lints/src/methods/unnecessary_iter_cloned.rs
  clippy_lints/src/methods/utils.rs
  tests/ui/unnecessary_filter_map.rs
  tests/ui/unnecessary_filter_map.stderr
Labels: S-waiting-on-review
