Repository rust-lang/rust-clippy, pull requests merged in 2022-10, with the labels that each got.

#9568 rustc_tool_utils: bump version in anticipation of a new release
  Cargo.toml
  rustc_tools_util/Cargo.toml
  rustc_tools_util/README.md
  rustc_tools_util/src/lib.rs
Labels: S-waiting-on-review

#9567 avoid doc-link-with-quotes in code blocks
  clippy_lints/src/doc.rs
  clippy_lints/src/doc_link_with_quotes.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_pedantic.rs
  clippy_lints/src/lib.rs
  tests/ui/doc_link_with_quotes.rs
  tests/ui/doc_link_with_quotes.stderr
Labels: S-waiting-on-review

#9569 use rustc_tools_util dependency from crates.io instead of this repo.
  Cargo.toml
Labels: S-waiting-on-review

#9484 Implement `manual_clamp` lint
  CHANGELOG.md
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_complexity.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_clamp.rs
  clippy_lints/src/utils/conf.rs
  clippy_utils/src/msrvs.rs
  src/docs.rs
  src/docs/manual_clamp.txt
  tests/ui/manual_clamp.rs
  tests/ui/manual_clamp.stderr
  tests/ui/min_max.rs
  tests/ui/min_max.stderr
  tests/ui/min_rust_version_attr.rs
  tests/ui/min_rust_version_attr.stderr
Labels: S-waiting-on-review

#9509 Fix sorting in ` cargo dev update_lints` script
  clippy_dev/src/update_lints.rs
Labels: S-waiting-on-review

#9573 lint nested patterns and slice patterns in `needless_borrowed_reference`
  clippy_lints/src/manual_clamp.rs
  clippy_lints/src/map_unit_fn.rs
  clippy_lints/src/methods/manual_ok_or.rs
  clippy_lints/src/needless_borrowed_ref.rs
  src/docs/needless_borrowed_reference.txt
  tests/ui/needless_borrowed_ref.fixed
  tests/ui/needless_borrowed_ref.rs
  tests/ui/needless_borrowed_ref.stderr
Labels: S-waiting-on-review

#9571 use `is_integer_literal` more
  clippy_lints/src/bool_to_int_with_if.rs
  clippy_lints/src/checked_conversions.rs
  clippy_lints/src/from_str_radix_10.rs
  clippy_lints/src/implicit_saturating_sub.rs
  clippy_lints/src/methods/get_last_with_len.rs
  clippy_lints/src/misc.rs
  clippy_lints/src/operators/arithmetic_side_effects.rs
  clippy_lints/src/operators/numeric_arithmetic.rs
  clippy_lints/src/slow_vector_initialization.rs
  clippy_lints/src/transmute/transmuting_null.rs
  clippy_lints/src/uninit_vec.rs
Labels: S-waiting-on-review

#9577 [`unnecessary_cast`] add parenthesis when negative number uses a method
  clippy_lints/src/casts/unnecessary_cast.rs
  tests/ui/unnecessary_cast.fixed
  tests/ui/unnecessary_cast.rs
  tests/ui/unnecessary_cast.stderr
Labels: S-waiting-on-review

#9479 [`manual_assert`]: Preserve comments in the suggestion
  clippy_lints/src/manual_assert.rs
  clippy_utils/src/lib.rs
  tests/ui/manual_assert.edition2018.fixed
  tests/ui/manual_assert.edition2018.stderr
  tests/ui/manual_assert.edition2021.fixed
  tests/ui/manual_assert.edition2021.stderr
  tests/ui/manual_assert.rs
Labels: S-waiting-on-review

#9576 let unnecessary_cast work for trivial non_literal expressions
  clippy_lints/src/casts/unnecessary_cast.rs
  tests/ui/floating_point_exp.fixed
  tests/ui/floating_point_exp.rs
  tests/ui/floating_point_exp.stderr
  tests/ui/floating_point_log.fixed
  tests/ui/floating_point_log.rs
  tests/ui/floating_point_logbase.fixed
  tests/ui/floating_point_logbase.rs
  tests/ui/floating_point_logbase.stderr
  tests/ui/floating_point_powf.fixed
  tests/ui/floating_point_powf.rs
  tests/ui/floating_point_powf.stderr
  tests/ui/floating_point_powi.fixed
  tests/ui/floating_point_powi.rs
  tests/ui/floating_point_powi.stderr
  tests/ui/manual_bits.fixed
  tests/ui/manual_bits.rs
  tests/ui/manual_bits.stderr
  tests/ui/ptr_offset_with_cast.fixed
  tests/ui/ptr_offset_with_cast.rs
  tests/ui/ptr_offset_with_cast.stderr
  tests/ui/unnecessary_cast.fixed
  tests/ui/unnecessary_cast.rs
  tests/ui/unnecessary_cast.stderr
Labels: S-waiting-on-review

#9574 Remove unused `.fixed` files, only run asm_syntax doctests on x86
  clippy_lints/src/asm_syntax.rs
  tests/ui/manual_assert.fixed
  tests/ui/option_take_on_temporary.fixed
Labels: S-waiting-on-review

#7962 Fix and improve `match_type_on_diagnostic_item`
  clippy_lints/src/await_holding_invalid.rs
  clippy_lints/src/if_then_some_else_none.rs
  clippy_lints/src/infinite_iter.rs
  clippy_lints/src/inherent_to_string.rs
  clippy_lints/src/lib.register_internal.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/loops/manual_find.rs
  clippy_lints/src/loops/manual_flatten.rs
  clippy_lints/src/loops/while_let_on_iterator.rs
  clippy_lints/src/manual_retain.rs
  clippy_lints/src/matches/collapsible_match.rs
  clippy_lints/src/matches/manual_map.rs
  clippy_lints/src/matches/manual_unwrap_or.rs
  clippy_lints/src/matches/match_as_ref.rs
  clippy_lints/src/matches/needless_match.rs
  clippy_lints/src/matches/redundant_pattern_match.rs
  clippy_lints/src/matches/try_err.rs
  clippy_lints/src/mem_replace.rs
  clippy_lints/src/methods/filetype_is_file.rs
  clippy_lints/src/methods/inefficient_to_string.rs
  clippy_lints/src/methods/iter_on_single_or_empty_collections.rs
  clippy_lints/src/methods/manual_ok_or.rs
  clippy_lints/src/methods/manual_str_repeat.rs
  clippy_lints/src/methods/option_map_or_none.rs
  clippy_lints/src/methods/or_then_unwrap.rs
  clippy_lints/src/methods/unnecessary_filter_map.rs
  clippy_lints/src/methods/useless_asref.rs
  clippy_lints/src/minmax.rs
  clippy_lints/src/needless_question_mark.rs
  clippy_lints/src/non_octal_unix_permissions.rs
  clippy_lints/src/option_if_let_else.rs
  clippy_lints/src/partialeq_to_none.rs
  clippy_lints/src/question_mark.rs
  clippy_lints/src/slow_vector_initialization.rs
  clippy_lints/src/unnecessary_owned_empty_strings.rs
  clippy_lints/src/unnecessary_wraps.rs
  clippy_lints/src/unused_io_amount.rs
  clippy_lints/src/useless_conversion.rs
  clippy_lints/src/utils/internal_lints.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/paths.rs
  tests/ui-internal/auxiliary/paths.rs
  tests/ui-internal/match_type_on_diag_item.rs
  tests/ui-internal/match_type_on_diag_item.stderr
  tests/ui-internal/unnecessary_def_path.fixed
  tests/ui-internal/unnecessary_def_path.rs
  tests/ui-internal/unnecessary_def_path.stderr
Labels: S-waiting-on-review

#8762 Replace `expr_visitor` with `for_each_expr`
  clippy_lints/src/blocks_in_if_conditions.rs
  clippy_lints/src/cognitive_complexity.rs
  clippy_lints/src/functions/must_use.rs
  clippy_lints/src/functions/not_unsafe_ptr_arg_deref.rs
  clippy_lints/src/implicit_return.rs
  clippy_lints/src/methods/str_splitn.rs
  clippy_lints/src/methods/unnecessary_filter_map.rs
  clippy_lints/src/needless_late_init.rs
  clippy_lints/src/operators/assign_op_pattern.rs
  clippy_lints/src/panic_in_result_fn.rs
  clippy_lints/src/read_zero_byte_vec.rs
  clippy_lints/src/returns.rs
  clippy_lints/src/suspicious_trait_impl.rs
  clippy_lints/src/unwrap_in_result.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/macros.rs
  clippy_utils/src/ptr.rs
  clippy_utils/src/usage.rs
  clippy_utils/src/visitors.rs
Labels: S-waiting-on-review

#9580 let `upper_case_acronyms` check the enum name
  clippy_lints/src/upper_case_acronyms.rs
  tests/ui/upper_case_acronyms.rs
  tests/ui/upper_case_acronyms.stderr
Labels: S-waiting-on-review

#9549 new `implicit_saturating_add` lint
  CHANGELOG.md
  clippy_lints/src/implicit_saturating_add.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_style.rs
  clippy_lints/src/lib.rs
  src/docs.rs
  src/docs/implicit_saturating_add.txt
  tests/ui/implicit_saturating_add.fixed
  tests/ui/implicit_saturating_add.rs
  tests/ui/implicit_saturating_add.stderr
Labels: S-waiting-on-review

#9581 `suboptimal_flops` lint for multiply and subtract
  clippy_lints/src/floating_point_arithmetic.rs
  tests/ui/floating_point_mul_add.fixed
  tests/ui/floating_point_mul_add.rs
  tests/ui/floating_point_mul_add.stderr
  tests/ui/floating_point_powi.fixed
  tests/ui/floating_point_powi.rs
  tests/ui/floating_point_powi.stderr
Labels: S-waiting-on-review

#9559 Fix #9544
  clippy_lints/src/operators/arithmetic_side_effects.rs
  tests/ui/arithmetic_side_effects.rs
  tests/ui/arithmetic_side_effects.stderr
Labels: S-waiting-on-review

#9587 [arithmetic-side-effects] Do not ignore literal references
  clippy_lints/src/operators/arithmetic_side_effects.rs
  tests/ui/arithmetic_side_effects.rs
  tests/ui/arithmetic_side_effects.stderr
Labels: S-waiting-on-review

#9495 Add `disallowed_macros` lint
  CHANGELOG.md
  clippy_lints/src/await_holding_invalid.rs
  clippy_lints/src/disallowed_macros.rs
  clippy_lints/src/disallowed_methods.rs
  clippy_lints/src/disallowed_types.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_style.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/missing_enforced_import_rename.rs
  clippy_lints/src/utils/conf.rs
  clippy_lints/src/utils/internal_lints.rs
  clippy_utils/src/lib.rs
  src/docs.rs
  src/docs/disallowed_macros.txt
  tests/ui-toml/disallowed_macros/auxiliary/macros.rs
  tests/ui-toml/disallowed_macros/clippy.toml
  tests/ui-toml/disallowed_macros/disallowed_macros.rs
  tests/ui-toml/disallowed_macros/disallowed_macros.stderr
  tests/ui-toml/toml_disallowed_methods/clippy.toml
  tests/ui-toml/toml_disallowed_methods/conf_disallowed_methods.rs
  tests/ui-toml/toml_disallowed_methods/conf_disallowed_methods.stderr
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
Labels: S-waiting-on-review

#9586 FormatArgsExpn: Find comma spans and ignore weird proc macro spans
  clippy_lints/src/format_args.rs
  clippy_lints/src/write.rs
  clippy_utils/src/macros.rs
  tests/ui/expect_fun_call.fixed
  tests/ui/expect_fun_call.rs
  tests/ui/expect_fun_call.stderr
  tests/ui/uninlined_format_args.fixed
  tests/ui/uninlined_format_args.rs
  tests/ui/uninlined_format_args.stderr
Labels: S-waiting-on-review

#9599 Add a temporary workaround for multiline formart arg inlining
  clippy_lints/src/format_args.rs
  tests/ui/uninlined_format_args.fixed
  tests/ui/uninlined_format_args.stderr
Labels: S-waiting-on-review

#9601 [`match_single_binding`] Add curlies for more cases to fix suggestion causes error
  clippy_lints/src/matches/match_single_binding.rs
  tests/ui/match_single_binding.fixed
  tests/ui/match_single_binding.rs
  tests/ui/match_single_binding.stderr
Labels: S-waiting-on-review

#9595 Replace if_chain with let chains in `clippy::author` output
  clippy_lints/src/utils/author.rs
  tests/ui/author.stdout
  tests/ui/author/blocks.stdout
  tests/ui/author/call.stdout
  tests/ui/author/if.stdout
  tests/ui/author/issue_3849.stdout
  tests/ui/author/loop.stdout
  tests/ui/author/matches.stdout
  tests/ui/author/repeat.stdout
  tests/ui/author/struct.stdout
Labels: S-waiting-on-review

#9585 extend `box-default` lint, add suggestion
  clippy_lints/src/box_default.rs
  clippy_utils/src/lib.rs
  src/docs/box_default.txt
  tests/ui/box_default.fixed
  tests/ui/box_default.rs
  tests/ui/box_default.stderr
Labels: S-waiting-on-review

#9451 Add `manual_filter` lint for `Option`
  CHANGELOG.md
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_complexity.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/matches/manual_filter.rs
  clippy_lints/src/matches/manual_map.rs
  clippy_lints/src/matches/manual_utils.rs
  clippy_lints/src/matches/mod.rs
  clippy_utils/src/sugg.rs
  src/docs.rs
  src/docs/manual_filter.txt
  tests/ui/manual_filter.fixed
  tests/ui/manual_filter.rs
  tests/ui/manual_filter.stderr
Labels: S-waiting-on-review

#9386 Further enhance `needless_borrow`, mildly refactor `redundant_clone`
  clippy_dev/src/serve.rs
  clippy_dev/src/update_lints.rs
  clippy_lints/src/dereference.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/nonstandard_macro_braces.rs
  clippy_lints/src/redundant_clone.rs
  clippy_utils/src/attrs.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/mir/maybe_storage_live.rs
  clippy_utils/src/mir/mod.rs
  clippy_utils/src/mir/possible_borrower.rs
  clippy_utils/src/mir/possible_origin.rs
  clippy_utils/src/mir/transitive_relation.rs
  clippy_utils/src/paths.rs
  lintcheck/src/main.rs
  tests/compile-test.rs
  tests/ui/needless_borrow.fixed
  tests/ui/needless_borrow.rs
  tests/ui/needless_borrow.stderr
  tests/ui/unnecessary_to_owned.fixed
  tests/ui/unnecessary_to_owned.rs
  tests/versioncheck.rs
Labels: S-waiting-on-review

#9572 Add `as_ptr_cast_mut` lint
  CHANGELOG.md
  clippy_lints/src/casts/as_ptr_cast_mut.rs
  clippy_lints/src/casts/mod.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_nursery.rs
  src/docs.rs
  src/docs/as_ptr_cast_mut.txt
  tests/ui/as_ptr_cast_mut.rs
  tests/ui/as_ptr_cast_mut.stderr
Labels: S-waiting-on-review

#9616 Add Default to Clippy Lints Lint groups
  util/gh-pages/index.html
  util/gh-pages/script.js
Labels: S-waiting-on-review

#9629 Replace manual let else patterns with let else
  clippy_dev/src/setup/intellij.rs
  clippy_dev/src/update_lints.rs
  clippy_lints/src/derive.rs
  clippy_lints/src/disallowed_methods.rs
  clippy_lints/src/entry.rs
  clippy_lints/src/eta_reduction.rs
  clippy_lints/src/functions/too_many_lines.rs
  clippy_lints/src/invalid_upcast_comparisons.rs
  clippy_lints/src/large_enum_variant.rs
  clippy_lints/src/loops/while_let_on_iterator.rs
  clippy_lints/src/matches/manual_utils.rs
  clippy_lints/src/matches/match_same_arms.rs
  clippy_lints/src/methods/into_iter_on_ref.rs
  clippy_lints/src/methods/manual_saturating_arithmetic.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/str_splitn.rs
  clippy_lints/src/misc_early/literal_suffix.rs
  clippy_lints/src/misc_early/mixed_case_hex_literals.rs
  clippy_lints/src/mismatching_type_param_order.rs
  clippy_lints/src/mixed_read_write_in_expression.rs
  clippy_lints/src/needless_for_each.rs
  clippy_lints/src/non_copy_const.rs
  clippy_lints/src/non_octal_unix_permissions.rs
  clippy_lints/src/ptr.rs
  clippy_lints/src/ptr_offset_with_cast.rs
  clippy_lints/src/shadow.rs
  clippy_lints/src/types/rc_buffer.rs
  clippy_lints/src/types/redundant_allocation.rs
  clippy_lints/src/unnested_or_patterns.rs
  clippy_lints/src/unused_io_amount.rs
  clippy_lints/src/useless_conversion.rs
  clippy_lints/src/utils/internal_lints.rs
Labels: S-waiting-on-review

#9605 fix: uninlined_format_args shouldn't inline panic! before 2021ed
  clippy_lints/src/format_args.rs
  tests/ui/uninlined_format_args.fixed
  tests/ui/uninlined_format_args.rs
  tests/ui/uninlined_format_args.stderr
  tests/ui/uninlined_format_args_2018.fixed
  tests/ui/uninlined_format_args_2018.rs
  tests/ui/uninlined_format_args_2018.stderr
  tests/ui/uninlined_format_args_2021.fixed
  tests/ui/uninlined_format_args_2021.rs
  tests/ui/uninlined_format_args_2021.stderr
Labels: S-waiting-on-review

#9633 update Applicability of `rc_buffer` lint from `MachineApplicable` to `Unspecified`
  clippy_lints/src/types/rc_buffer.rs
Labels: S-waiting-on-review

#9617 add `cast-nan-to-int` lint
  CHANGELOG.md
  clippy_lints/src/casts/cast_nan_to_int.rs
  clippy_lints/src/casts/mod.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_suspicious.rs
  src/docs.rs
  src/docs/cast_nan_to_int.txt
  tests/ui/cast_nan_to_int.rs
  tests/ui/cast_nan_to_int.stderr
Labels: S-waiting-on-review

#9590 Fix to_string_in_format_args in parens
  clippy_lints/src/format_args.rs
  tests/ui/format_args.fixed
  tests/ui/format_args.rs
  tests/ui/format_args.stderr
Labels: S-waiting-on-review

#9600 Change uninlined_format_args into a style lint
  clippy_lints/src/format_args.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_pedantic.rs
  clippy_lints/src/lib.register_style.rs
Labels: S-waiting-on-review

#9584 add tests in `implicit_saturating_sub` lint
  clippy_lints/src/implicit_saturating_sub.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_pedantic.rs
  clippy_lints/src/lib.register_style.rs
  tests/ui/implicit_saturating_sub.fixed
  tests/ui/implicit_saturating_sub.rs
  tests/ui/implicit_saturating_sub.stderr
Labels: S-waiting-on-review

#9640 Fix edition revision ui tests
  tests/ui/manual_assert.edition2018.fixed
  tests/ui/manual_assert.edition2018.stderr
  tests/ui/manual_assert.edition2021.fixed
  tests/ui/manual_assert.rs
  tests/ui/match_wild_err_arm.edition2021.stderr
  tests/ui/match_wild_err_arm.rs
  tests/ui/match_wild_err_arm.stderr
  tests/ui/uninlined_format_args_2018.rs
  tests/ui/uninlined_format_args_panic.edition2018.fixed
  tests/ui/uninlined_format_args_panic.edition2018.stderr
  tests/ui/uninlined_format_args_panic.edition2021.fixed
  tests/ui/uninlined_format_args_panic.edition2021.stderr
  tests/ui/uninlined_format_args_panic.rs
Labels: S-waiting-on-review

#9644 add missing comma
  CONTRIBUTING.md
Labels: S-waiting-on-review, invalid

#9643 Book: Small grammar + link a11y change
  book/src/development/basics.md
Labels: S-waiting-on-review, invalid

#9645 Don't lint `ptr_arg` when used as an incompatible trait object
  clippy_lints/src/ptr.rs
  tests/ui/ptr_arg.rs
  tests/ui/ptr_arg.stderr
Labels: S-waiting-on-review

#9649 Add a suggestion and a note about orphan rules for `from_over_into`
  clippy_lints/src/from_over_into.rs
  tests/ui/from_over_into.fixed
  tests/ui/from_over_into.rs
  tests/ui/from_over_into.stderr
  tests/ui/from_over_into_unfixable.rs
  tests/ui/from_over_into_unfixable.stderr
Labels: S-waiting-on-review

#9655 fix `box-default` linting `no_std` non-boxes
  clippy_lints/src/box_default.rs
  tests/ui/box_default_no_std.rs
Labels: S-waiting-on-review

#9636 [`default_numeric_fallback`] do not lint on constants
  clippy_lints/src/default_numeric_fallback.rs
  tests/ui/default_numeric_fallback_f64.fixed
  tests/ui/default_numeric_fallback_f64.rs
  tests/ui/default_numeric_fallback_f64.stderr
  tests/ui/default_numeric_fallback_i32.fixed
  tests/ui/default_numeric_fallback_i32.rs
  tests/ui/default_numeric_fallback_i32.stderr
Labels: S-waiting-on-review

#9566 Expand internal lint `unnecessary_def_path`
  clippy_lints/src/booleans.rs
  clippy_lints/src/comparison_chain.rs
  clippy_lints/src/functions/must_use.rs
  clippy_lints/src/let_underscore.rs
  clippy_lints/src/lib.register_internal.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/loops/needless_range_loop.rs
  clippy_lints/src/manual_async_fn.rs
  clippy_lints/src/manual_clamp.rs
  clippy_lints/src/matches/single_match.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/option_as_ref_deref.rs
  clippy_lints/src/methods/or_fun_call.rs
  clippy_lints/src/neg_cmp_op_on_partial_ord.rs
  clippy_lints/src/operators/cmp_owned.rs
  clippy_lints/src/unit_return_expecting_ord.rs
  clippy_lints/src/utils/internal_lints.rs
  clippy_lints/src/utils/internal_lints/clippy_lints_internal.rs
  clippy_lints/src/utils/internal_lints/collapsible_calls.rs
  clippy_lints/src/utils/internal_lints/compiler_lint_functions.rs
  clippy_lints/src/utils/internal_lints/if_chain_style.rs
  clippy_lints/src/utils/internal_lints/interning_defined_symbol.rs
  clippy_lints/src/utils/internal_lints/invalid_paths.rs
  clippy_lints/src/utils/internal_lints/lint_without_lint_pass.rs
  clippy_lints/src/utils/internal_lints/metadata_collector.rs
  clippy_lints/src/utils/internal_lints/msrv_attr_impl.rs
  clippy_lints/src/utils/internal_lints/outer_expn_data_pass.rs
  clippy_lints/src/utils/internal_lints/produce_ice.rs
  clippy_lints/src/utils/internal_lints/unnecessary_def_path.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/paths.rs
  tests/ui-internal/custom_ice_message.stderr
  tests/ui-internal/invalid_paths.rs
  tests/ui-internal/unnecessary_def_path.fixed
  tests/ui-internal/unnecessary_def_path.rs
  tests/ui-internal/unnecessary_def_path_hardcoded_path.rs
  tests/ui-internal/unnecessary_def_path_hardcoded_path.stderr
Labels: S-waiting-on-review

#9658 Add new lint `partial_pub_fields`
  CHANGELOG.md
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_restriction.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/partial_pub_fields.rs
  src/docs.rs
  src/docs/partial_pub_fields.txt
  tests/ui/partial_pub_fields.rs
  tests/ui/partial_pub_fields.stderr
Labels: S-waiting-on-review

#9652 [`zero_prefixed_literal`] Do not advise to use octal form if not possible
  clippy_lints/src/misc_early/zero_prefixed_literal.rs
  tests/ui/literals.rs
  tests/ui/literals.stderr
Labels: S-waiting-on-review

#9609 [`unnecessary_cast`] Do not lint negative hexadecimal literals when cast as floats
  clippy_lints/src/casts/unnecessary_cast.rs
  clippy_utils/src/numeric_literal.rs
  tests/ui/unnecessary_cast.fixed
  tests/ui/unnecessary_cast.rs
Labels: S-waiting-on-review

#9637 Add `unused_format_specs` lint
  CHANGELOG.md
  clippy_lints/src/format_args.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_complexity.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_utils/src/macros.rs
  src/docs.rs
  src/docs/unused_format_specs.txt
  tests/ui/unused_format_specs.fixed
  tests/ui/unused_format_specs.rs
  tests/ui/unused_format_specs.stderr
  tests/ui/unused_format_specs_unfixable.rs
  tests/ui/unused_format_specs_unfixable.stderr
Labels: S-waiting-on-review

#9634 Update Applicability of `redundant_allocation` lint from `MachineApplicable` to `MaybeIncorrect`
  clippy_lints/src/types/redundant_allocation.rs
Labels: S-waiting-on-review

#9670 Add `missing_trait_methods` lint
  CHANGELOG.md
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_restriction.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/missing_trait_methods.rs
  src/docs.rs
  src/docs/missing_trait_methods.txt
  tests/ui/missing_trait_methods.rs
  tests/ui/missing_trait_methods.stderr
Labels: S-waiting-on-review

#9685 [`collapsible_match`] specify field name when destructuring structs
  clippy_lints/src/matches/collapsible_match.rs
  tests/ui/collapsible_match.rs
  tests/ui/collapsible_match.stderr
Labels: S-waiting-on-review

#9691 Add `lintcheck` to packages linted by `dogfood` test
  lintcheck/src/config.rs
  lintcheck/src/driver.rs
  lintcheck/src/main.rs
  lintcheck/src/recursive.rs
  tests/dogfood.rs
Labels: S-waiting-on-review

#9622 fix `box-default` ignoring trait objects' types
  clippy_lints/src/box_default.rs
  tests/ui/box_default.fixed
  tests/ui/box_default.rs
  tests/ui/box_default.stderr
Labels: S-waiting-on-review

#9686 [`unwrap_used`], [`expect_used`] do not lint in `test` cfg
  clippy_lints/src/methods/expect_used.rs
  clippy_lints/src/methods/unwrap_used.rs
  clippy_lints/src/utils/conf.rs
  tests/ui-toml/expect_used/expect_used.rs
  tests/ui-toml/unwrap_used/unwrap_used.rs
  tests/ui-toml/unwrap_used/unwrap_used.stderr
Labels: S-waiting-on-review

#9654 Enable test no_std_main_recursion
  tests/ui/crate_level_checks/no_std_main_recursion.rs
Labels: S-waiting-on-review

#9697 Mark `let_underscore_lock` and `let_underscore_drop` as uplifted
  clippy_lints/src/let_underscore.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_pedantic.rs
  clippy_lints/src/renamed_lints.rs
  lintcheck/src/main.rs
  src/docs.rs
  src/docs/let_underscore_drop.txt
  src/docs/let_underscore_lock.txt
  tests/ui/let_underscore_drop.rs
  tests/ui/let_underscore_drop.stderr
  tests/ui/let_underscore_lock.rs
  tests/ui/let_underscore_lock.stderr
  tests/ui/map_flatten_fixable.fixed
  tests/ui/map_flatten_fixable.rs
  tests/ui/map_flatten_fixable.stderr
  tests/ui/rename.fixed
  tests/ui/rename.rs
  tests/ui/rename.stderr
Labels: S-waiting-on-review

#9689 fix: support `map_or` for `or_fun_call` lint
  clippy_lints/src/methods/or_fun_call.rs
  tests/ui/manual_ok_or.fixed
  tests/ui/manual_ok_or.rs
  tests/ui/manual_ok_or.stderr
  tests/ui/or_fun_call.fixed
  tests/ui/or_fun_call.rs
  tests/ui/or_fun_call.stderr
Labels: S-waiting-on-review

#9630 Fix allow_attributes_without_reason applying to external crate macros
  clippy_lints/src/attrs.rs
Labels: S-waiting-on-review

#9368 Improvement for `equatable_if_let`
  clippy_lints/src/equatable_if_let.rs
  tests/ui/equatable_if_let.fixed
  tests/ui/equatable_if_let.rs
  tests/ui/equatable_if_let.stderr
Labels: S-waiting-on-review

#9690 add `from_raw_with_void_ptr` lint
  CHANGELOG.md
  clippy_lints/src/from_raw_with_void_ptr.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_suspicious.rs
  clippy_lints/src/lib.rs
  src/docs.rs
  src/docs/from_raw_with_void_ptr.txt
  tests/ui/from_raw_with_void_ptr.rs
  tests/ui/from_raw_with_void_ptr.stderr
Labels: S-waiting-on-review

#8437 Add lint to tell about let else pattern
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/dereference.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_let_else.rs
  clippy_lints/src/utils/conf.rs
  clippy_utils/src/consts.rs
  clippy_utils/src/hir_utils.rs
  clippy_utils/src/msrvs.rs
  src/docs/manual_let_else.txt
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
  tests/ui/manual_let_else.rs
  tests/ui/manual_let_else.stderr
  tests/ui/manual_let_else_match.rs
  tests/ui/manual_let_else_match.stderr
Labels: S-blocked

#9667 add new lint `seek_to_start_instead_of_rewind `
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/seek_to_start_instead_of_rewind.rs
  clippy_utils/src/msrvs.rs
  clippy_utils/src/paths.rs
  src/docs/seek_to_start_instead_of_rewind.txt
  tests/ui/seek_to_start_instead_of_rewind.fixed
  tests/ui/seek_to_start_instead_of_rewind.rs
  tests/ui/seek_to_start_instead_of_rewind.stderr
Labels: S-waiting-on-review

#9704 [`use_self`] fix FP when trait impl defined in macro
  clippy_lints/src/use_self.rs
  tests/ui/use_self_trait.fixed
  tests/ui/use_self_trait.rs
Labels: S-waiting-on-review

#9700 Update `from_raw_with_void_ptr` to support types other than `Box`
  clippy_lints/src/from_raw_with_void_ptr.rs
  tests/ui/from_raw_with_void_ptr.rs
  tests/ui/from_raw_with_void_ptr.stderr
Labels: S-waiting-on-review

#9709 chore: remove unnecessary files
  src/docs/manual_let_else.txt
  src/docs/seek_to_start_instead_of_rewind.txt
Labels: S-waiting-on-review

#9692 make ignored internally mutable types for `mutable-key` configurable
  clippy_lints/src/lib.rs
  clippy_lints/src/mut_key.rs
  clippy_lints/src/utils/conf.rs
  clippy_utils/src/lib.rs
  tests/ui-toml/mut_key/clippy.toml
  tests/ui-toml/mut_key/mut_key.rs
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
Labels: S-waiting-on-review

#9707 Track `clippy.toml` and `Cargo.toml` in `file_depinfo`
  clippy_dev/Cargo.toml
  clippy_dev/src/lint.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/conf.rs
  lintcheck/src/main.rs
  src/driver.rs
Labels: S-waiting-on-review

#9712 Remove `lib.register_*` and `src/docs*` in `cargo dev update_lints`
  clippy_dev/src/update_lints.rs
Labels: S-waiting-on-review

#9681 feat: add new lint `seek_from_current`
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/seek_from_current.rs
  clippy_utils/src/msrvs.rs
  clippy_utils/src/paths.rs
  tests/ui/seek_from_current.fixed
  tests/ui/seek_from_current.rs
  tests/ui/seek_from_current.stderr
Labels: S-waiting-on-review

#9723 Fix dupe word typos
  clippy_lints/src/matches/significant_drop_in_scrutinee.rs
  clippy_utils/src/ty.rs
  tests/ui/manual_flatten.rs
  tests/ui/mut_range_bound.rs
  tests/ui/mut_range_bound.stderr
Labels: S-waiting-on-review

#9717 Remove note mentioning configuration changes need cargo clean
  README.md
Labels: S-waiting-on-review

#9674 Fix `needless_borrow` false positive
  clippy_lints/src/dereference.rs
  tests/ui/needless_borrow.fixed
  tests/ui/needless_borrow.rs
Labels: S-waiting-on-review

#9728 move `UNINLINED_FORMAT_ARGS` to pedantic
  clippy_lints/src/format_args.rs
Labels: S-waiting-on-review, beta-nominated

#9722 `question_mark` don't lint on `if let Err` with `else`
  clippy_lints/src/question_mark.rs
  tests/ui/question_mark.fixed
  tests/ui/question_mark.rs
  tests/ui/question_mark.stderr
Labels: S-waiting-on-review

#9726 [`use_self`] fix suggestion when full path to struct was given
  clippy_lints/src/use_self.rs
  tests/ui-cargo/cargo_rust_version/fail_both_diff/src/main.stderr
  tests/ui-cargo/cargo_rust_version/fail_both_same/src/main.stderr
  tests/ui-cargo/cargo_rust_version/fail_cargo/src/main.stderr
  tests/ui-cargo/cargo_rust_version/fail_clippy/src/main.stderr
  tests/ui-cargo/cargo_rust_version/fail_file_attr/src/main.stderr
  tests/ui/use_self_trait.fixed
  tests/ui/use_self_trait.rs
  tests/ui/use_self_trait.stderr
Labels: S-waiting-on-review

#9733 Ensure new_ret_no_self is not fired if impl Trait<Self> is returned.
  clippy_lints/src/methods/mod.rs
  clippy_utils/src/ty.rs
  tests/ui/new_ret_no_self.rs
  tests/ui/new_ret_no_self.stderr
Labels: S-waiting-on-review

#9741 fix the `string-extend-chars` suggestion on slice
  clippy_lints/src/methods/string_extend_chars.rs
  tests/ui/string_extend.fixed
  tests/ui/string_extend.rs
  tests/ui/string_extend.stderr
Labels: S-waiting-on-review

#9711 Fix `needless_borrow` false positive #9710
  clippy_lints/src/dereference.rs
  tests/ui/needless_borrow.fixed
  tests/ui/needless_borrow.rs
Labels: S-waiting-on-review

#9648 fix `undocumented-unsafe-blocks` false positive
  clippy_lints/src/undocumented_unsafe_blocks.rs
  tests/ui/undocumented_unsafe_blocks.rs
  tests/ui/undocumented_unsafe_blocks.stderr
Labels: S-waiting-on-review

#9738 [`bool_to_int_with_if`] do not lint in const context
  clippy_lints/src/bool_to_int_with_if.rs
  tests/ui/bool_to_int_with_if.fixed
  tests/ui/bool_to_int_with_if.rs
  tests/ui/bool_to_int_with_if.stderr
Labels: S-waiting-on-review

#9714 Fix `bool_to_int_with_if` false positive with `if let`
  clippy_lints/src/bool_to_int_with_if.rs
  tests/ui/bool_to_int_with_if.fixed
  tests/ui/bool_to_int_with_if.rs
  tests/ui/bool_to_int_with_if.stderr
Labels: S-waiting-on-review

#9755 Warn when `clippy::restriction` is enabled via the command line
  clippy_lints/src/attrs.rs
  tests/ui/blanket_clippy_restriction_lints.rs
  tests/ui/blanket_clippy_restriction_lints.stderr
Labels: S-waiting-on-review

#9747 [`option_if_let_else`] do not lint if any arm has guard
  clippy_lints/src/option_if_let_else.rs
  tests/ui/option_if_let_else.fixed
  tests/ui/option_if_let_else.rs
Labels: S-waiting-on-review

#9734 Fix Clippy Test badge
  README.md
Labels: S-waiting-on-review

#9506 Add lint for confusing use of `^` instead of `.pow`
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/suspicious_xor_used_as_pow.rs
  tests/ui/eq_op.rs
  tests/ui/eq_op.stderr
  tests/ui/suspicious_xor_used_as_pow.rs
  tests/ui/suspicious_xor_used_as_pow.stderr
Labels: S-waiting-on-review
