Repository rust-lang/rust-clippy, pull requests merged in 2022-04, with the labels that each got.

#8616 single_element_loop: handle arrays for Edition2021
  clippy_lints/src/loops/single_element_loop.rs
  tests/ui/single_element_loop.fixed
  tests/ui/single_element_loop.rs
  tests/ui/single_element_loop.stderr
Labels: S-waiting-on-review

#8611 Handle relative paths in module_files lints
  clippy_lints/src/module_style.rs
  tests/ui-cargo/module_style/fail_mod/src/main.stderr
  tests/ui-cargo/module_style/fail_no_mod/src/main.stderr
Labels: S-waiting-on-review

#8605 Remove deps
  Cargo.toml
  clippy_dev/Cargo.toml
  clippy_dev/src/lib.rs
  clippy_dev/src/new_lint.rs
  clippy_dev/src/update_lints.rs
  tests/versioncheck.rs
Labels: S-waiting-on-review

#8594 add `empty_structs_with_brackets`
  CHANGELOG.md
  clippy_lints/src/empty_structs_with_brackets.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_restriction.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/use_self.rs
  tests/ui-toml/struct_excessive_bools/test.rs
  tests/ui/case_sensitive_file_extension_comparisons.rs
  tests/ui/crashes/ice-2774.rs
  tests/ui/crashes/ice-6179.rs
  tests/ui/crashes/ice-6792.rs
  tests/ui/crashes/needless_lifetimes_impl_trait.rs
  tests/ui/crashes/regressions.rs
  tests/ui/default_numeric_fallback_f64.fixed
  tests/ui/default_numeric_fallback_f64.rs
  tests/ui/default_numeric_fallback_i32.fixed
  tests/ui/default_numeric_fallback_i32.rs
  tests/ui/drop_forget_copy.rs
  tests/ui/empty_structs_with_brackets.fixed
  tests/ui/empty_structs_with_brackets.rs
  tests/ui/empty_structs_with_brackets.stderr
  tests/ui/fn_params_excessive_bools.rs
  tests/ui/implicit_clone.rs
  tests/ui/iter_nth_zero.fixed
  tests/ui/iter_nth_zero.rs
  tests/ui/large_types_passed_by_value.rs
  tests/ui/let_and_return.rs
  tests/ui/let_underscore_must_use.rs
  tests/ui/manual_async_fn.fixed
  tests/ui/manual_async_fn.rs
  tests/ui/manual_unwrap_or.fixed
  tests/ui/manual_unwrap_or.rs
  tests/ui/map_unit_fn.rs
  tests/ui/min_rust_version_attr.rs
  tests/ui/missing_inline.rs
  tests/ui/module_name_repetitions.rs
  tests/ui/module_name_repetitions.stderr
  tests/ui/needless_arbitrary_self_type_unfixable.rs
  tests/ui/needless_lifetimes.rs
  tests/ui/no_effect.rs
  tests/ui/or_then_unwrap.fixed
  tests/ui/or_then_unwrap.rs
  tests/ui/ptr_arg.rs
  tests/ui/recursive_format_impl.rs
  tests/ui/redundant_allocation.rs
  tests/ui/redundant_allocation_fixable.fixed
  tests/ui/redundant_allocation_fixable.rs
  tests/ui/redundant_static_lifetimes.fixed
  tests/ui/redundant_static_lifetimes.rs
  tests/ui/same_item_push.rs
  tests/ui/trait_duplication_in_bounds.rs
  tests/ui/unsafe_derive_deserialize.rs
  tests/ui/unsafe_removed_from_name.rs
  tests/ui/unused_self.rs
  tests/ui/use_self.fixed
  tests/ui/use_self.rs
  tests/ui/useless_attribute.fixed
  tests/ui/useless_attribute.rs
Labels: S-waiting-on-review

#8450 Rework `undocumented_unsafe_blocks`
  clippy_lints/src/lib.rs
  clippy_lints/src/undocumented_unsafe_blocks.rs
  tests/ui/auxiliary/proc_macro_unsafe.rs
  tests/ui/crashes/ice-7868.stderr
  tests/ui/undocumented_unsafe_blocks.rs
  tests/ui/undocumented_unsafe_blocks.stderr
Labels: S-waiting-on-review

#8632 Don't lint `cast_ptr_alignment` when used for unaligned reads and writes
  clippy_lints/src/casts/cast_ptr_alignment.rs
  clippy_utils/src/paths.rs
  tests/ui/cast_alignment.rs
  tests/ui/cast_alignment.stderr
Labels: S-waiting-on-review

#8633 Escape `mod.rs` file mentions to avoid links in our documentation
  clippy_lints/src/module_style.rs
Labels: S-waiting-on-review

#8607 Allow running `cargo dev lint` on a package directory
  clippy_dev/Cargo.toml
  clippy_dev/src/bless.rs
  clippy_dev/src/lib.rs
  clippy_dev/src/lint.rs
  clippy_dev/src/main.rs
Labels: S-waiting-on-review

#8620 Run fmt test before compile-test/dogfood
  tests/check-fmt.rs
Labels: S-waiting-on-review

#8403 fix misspelling in diagnostic message of `bytes_nth`
  clippy_lints/src/methods/bytes_nth.rs
  tests/ui/bytes_nth.stderr
Labels: S-waiting-on-review

#8636 Add documentation on how to do a minimal changelog update
  doc/release.md
Labels: S-waiting-on-review

#8588 `indexing_slicing` should not fire if a valid array index comes from a constant function that is evaluated at compile-time
  clippy_lints/src/indexing_slicing.rs
  tests/ui/indexing_slicing_index.rs
  tests/ui/indexing_slicing_index.stderr
Labels: S-waiting-on-review

#8596 Fix unnecessary_cast suggestion for type aliasses
  clippy_lints/src/casts/unnecessary_cast.rs
  tests/ui/unnecessary_cast.rs
  tests/ui/unnecessary_cast_fixable.fixed
  tests/ui/unnecessary_cast_fixable.rs
Labels: S-waiting-on-review

#8612 Suggest from_utf8_unchecked in const contexts
  clippy_lints/src/transmute/transmute_ref_to_ref.rs
  tests/ui/transmute.rs
  tests/ui/transmute.stderr
Labels: S-waiting-on-review

#8644 update unnecessary_join documentation
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-review

#8606 Add [`err_expect`] lint
  clippy_lints/src/methods/err_expect.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/utils/conf.rs
  clippy_utils/src/msrvs.rs
  tests/ui/err_expect.fixed
  tests/ui/err_expect.rs
  tests/ui/err_expect.stderr
  tests/ui/min_rust_version_attr.rs
  tests/ui/min_rust_version_attr.stderr
Labels: S-waiting-on-author

#8630 Add lints `drop_non_drop` and `forget_non_drop`
  CHANGELOG.md
  clippy_lints/src/drop_forget_ref.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_correctness.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_suspicious.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/undropped_manually_drops.rs
  tests/ui/drop_forget_copy.stderr
  tests/ui/drop_non_drop.rs
  tests/ui/drop_non_drop.stderr
  tests/ui/drop_ref.rs
  tests/ui/forget_non_drop.rs
  tests/ui/forget_non_drop.stderr
  tests/ui/forget_ref.rs
  tests/ui/redundant_clone.fixed
  tests/ui/redundant_clone.rs
Labels: S-waiting-on-review

#8635 Add a lint to detect cast to unsigned for abs() and suggest unsigned_…
  CHANGELOG.md
  clippy_lints/src/casts/cast_abs_to_unsigned.rs
  clippy_lints/src/casts/mod.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_suspicious.rs
  clippy_lints/src/utils/conf.rs
  clippy_utils/src/msrvs.rs
  tests/ui/cast.rs
  tests/ui/cast_abs_to_unsigned.fixed
  tests/ui/cast_abs_to_unsigned.rs
  tests/ui/cast_abs_to_unsigned.stderr
  tests/ui/min_rust_version_attr.rs
  tests/ui/min_rust_version_attr.stderr
Labels: S-waiting-on-review

#8657 Allow raw lint descriptions
  CHANGELOG.md
  clippy_dev/src/update_lints.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_style.rs
Labels: S-waiting-on-review

#8619 ignore `&x | &y` in unnested_or_patterns
  clippy_lints/src/unnested_or_patterns.rs
  tests/ui/unnested_or_patterns.fixed
  tests/ui/unnested_or_patterns.rs
  tests/ui/unnested_or_patterns.stderr
Labels: S-waiting-on-review

#8648 Fix `unsound_collection_transmute`
  clippy_lints/src/transmute/utils.rs
  tests/ui/transmute_collection.rs
Labels: S-waiting-on-review

#8669 fix comments in test for split_once
  tests/ui/manual_split_once.fixed
  tests/ui/manual_split_once.rs
Labels: S-waiting-on-review

#8664 Allow passing `--remove` to `cargo dev setup <SUBCOMMAND>`
  clippy_dev/src/main.rs
Labels: S-waiting-on-review

#8631 Remove overlap between `manual_split_once` and `needless_splitn`
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/str_splitn.rs
  tests/ui/crashes/ice-8250.stderr
  tests/ui/manual_split_once.fixed
  tests/ui/manual_split_once.rs
  tests/ui/manual_split_once.stderr
  tests/ui/needless_splitn.fixed
  tests/ui/needless_splitn.rs
  tests/ui/needless_splitn.stderr
Labels: S-waiting-on-review

#8671 fix typo
  clippy_lints/src/drop_forget_ref.rs
  tests/ui/drop_non_drop.stderr
Labels: S-waiting-on-review

#8660 `unnecessary_owned_empty_strings`
  CHANGELOG.md
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_style.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/unnecessary_owned_empty_strings.rs
  clippy_utils/src/paths.rs
  tests/ui/unnecessary_owned_empty_strings.fixed
  tests/ui/unnecessary_owned_empty_strings.rs
  tests/ui/unnecessary_owned_empty_strings.stderr
Labels: S-waiting-on-review

#8668 Don't lint `iter_with_drain` on references
  clippy_lints/src/methods/iter_with_drain.rs
  tests/ui/iter_with_drain.fixed
  tests/ui/iter_with_drain.rs
Labels: S-waiting-on-review

#8673 Fix `same_functions_in_if_condition` FP
  clippy_utils/src/hir_utils.rs
  tests/ui/same_functions_in_if_condition.rs
  tests/ui/same_functions_in_if_condition.stderr
Labels: S-waiting-on-review

#8667 Don't lint various match lints when expanded by a proc-macro
  clippy_lints/src/matches/mod.rs
  clippy_utils/src/source.rs
  tests/ui/auxiliary/proc_macro_with_span.rs
  tests/ui/single_match_else.rs
  tests/ui/single_match_else.stderr
Labels: S-waiting-on-review

#8624 New lint `is_digit_ascii_radix`
  CHANGELOG.md
  clippy_lints/src/case_sensitive_file_extension_comparisons.rs
  clippy_lints/src/doc.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_style.rs
  clippy_lints/src/methods/is_digit_ascii_radix.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/misc_early/mod.rs
  clippy_lints/src/non_expressive_names.rs
  clippy_utils/src/msrvs.rs
  clippy_utils/src/numeric_literal.rs
  tests/ui/is_digit_ascii_radix.fixed
  tests/ui/is_digit_ascii_radix.rs
  tests/ui/is_digit_ascii_radix.stderr
  tests/ui/to_digit_is_some.fixed
  tests/ui/to_digit_is_some.rs
  tests/ui/to_digit_is_some.stderr
Labels: S-waiting-on-review

#8686 Fix ICE in `undocumented_unsafe_blocks`
  clippy_lints/src/undocumented_unsafe_blocks.rs
  tests/ui/crashes/auxiliary/ice-8681-aux.rs
  tests/ui/crashes/ice-8681.rs
Labels: S-waiting-on-review

#8691 Prevent infinite (exponential) recursion in only_used_in_recursion
  clippy_lints/src/only_used_in_recursion.rs
Labels: S-waiting-on-review

#8645 Don't lint `manual_non_exhaustive` when the enum variant is used
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_non_exhaustive.rs
  tests/ui/manual_non_exhaustive_enum.rs
  tests/ui/manual_non_exhaustive_enum.stderr
  tests/ui/manual_non_exhaustive_struct.rs
  tests/ui/manual_non_exhaustive_struct.stderr
Labels: S-waiting-on-review

#8647 Only lint `mut_from_ref` when unsafe code is used
  clippy_lints/src/ptr.rs
  clippy_utils/src/visitors.rs
  tests/ui/mut_from_ref.rs
  tests/ui/mut_from_ref.stderr
Labels: S-waiting-on-review

#8692 fix unnecessary_to_owned about msrv
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/unnecessary_to_owned.rs
  tests/ui/unnecessary_to_owned.fixed
  tests/ui/unnecessary_to_owned.rs
  tests/ui/unnecessary_to_owned.stderr
Labels: S-waiting-on-review

#8670 `pub_use` restriction
  CHANGELOG.md
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_restriction.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/pub_use.rs
  tests/ui/pub_use.rs
  tests/ui/pub_use.stderr
Labels: S-waiting-on-review

#8676 Check for loops/closures in `local_used_after_expr`
  clippy_lints/src/eta_reduction.rs
  clippy_utils/src/usage.rs
  tests/ui/eta.fixed
  tests/ui/eta.rs
  tests/ui/eta.stderr
  tests/ui/needless_option_as_deref.fixed
  tests/ui/needless_option_as_deref.rs
Labels: S-waiting-on-review

#8677 Add `usize` cast to `clippy::manual_bits` suggestion
  clippy_lints/src/manual_bits.rs
  tests/ui/manual_bits.fixed
  tests/ui/manual_bits.rs
  tests/ui/manual_bits.stderr
Labels: S-waiting-on-review

#8626 New lint `format_add_strings`
  CHANGELOG.md
  clippy_dev/src/new_lint.rs
  clippy_dev/src/update_lints.rs
  clippy_lints/src/format_push_string.rs
  clippy_lints/src/inconsistent_struct_constructor.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_perf.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/trait_bounds.rs
  clippy_utils/src/sugg.rs
  lintcheck/src/main.rs
  tests/ui/format_push_string.rs
  tests/ui/format_push_string.stderr
  tests/ui/identity_op.rs
  tests/ui/identity_op.stderr
Labels: S-waiting-on-review

#8614 assertions_on_constants: ignore indirect `cfg!`
  clippy_utils/src/consts.rs
  tests/ui/assertions_on_constants.rs
Labels: S-waiting-on-review

#8563 Don't lint `let_unit_value` when needed for type inferenece
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_pedantic.rs
  clippy_lints/src/lib.register_style.rs
  clippy_lints/src/unit_types/let_unit_value.rs
  clippy_lints/src/unit_types/mod.rs
  clippy_utils/src/visitors.rs
  tests/ui-internal/interning_defined_symbol.fixed
  tests/ui-internal/interning_defined_symbol.rs
  tests/ui-toml/functions_maxlines/test.rs
  tests/ui-toml/functions_maxlines/test.stderr
  tests/ui/cast_alignment.rs
  tests/ui/cast_slice_different_sizes.rs
  tests/ui/cast_slice_different_sizes.stderr
  tests/ui/crashes/ice-5944.rs
  tests/ui/default_numeric_fallback_f64.fixed
  tests/ui/default_numeric_fallback_f64.rs
  tests/ui/default_numeric_fallback_f64.stderr
  tests/ui/default_numeric_fallback_i32.fixed
  tests/ui/default_numeric_fallback_i32.rs
  tests/ui/default_numeric_fallback_i32.stderr
  tests/ui/doc_unsafe.rs
  tests/ui/doc_unsafe.stderr
  tests/ui/iter_overeager_cloned.fixed
  tests/ui/iter_overeager_cloned.rs
  tests/ui/let_underscore_drop.rs
  tests/ui/let_underscore_drop.stderr
  tests/ui/let_unit.fixed
  tests/ui/let_unit.rs
  tests/ui/let_unit.stderr
  tests/ui/needless_for_each_fixable.fixed
  tests/ui/needless_for_each_fixable.rs
  tests/ui/needless_for_each_fixable.stderr
  tests/ui/needless_late_init.rs
  tests/ui/needless_late_init.stderr
  tests/ui/non_expressive_names.rs
  tests/ui/option_if_let_else.fixed
  tests/ui/option_if_let_else.rs
  tests/ui/option_if_let_else.stderr
  tests/ui/or_then_unwrap.fixed
  tests/ui/or_then_unwrap.rs
  tests/ui/panicking_macros.rs
  tests/ui/shadow.rs
  tests/ui/shadow.stderr
  tests/ui/similar_names.rs
  tests/ui/similar_names.stderr
  tests/ui/single_char_lifetime_names.rs
  tests/ui/single_char_lifetime_names.stderr
  tests/ui/suspicious_else_formatting.rs
  tests/ui/undocumented_unsafe_blocks.rs
  tests/ui/undocumented_unsafe_blocks.stderr
  tests/ui/uninit.rs
  tests/ui/uninit.stderr
  tests/ui/unit_arg.rs
  tests/ui/unit_arg.stderr
  tests/ui/unit_hash.rs
  tests/ui/unit_hash.stderr
  tests/ui/wildcard_imports.fixed
  tests/ui/wildcard_imports.rs
  tests/ui/wildcard_imports.stderr
Labels: S-waiting-on-review

#8702 Fix typo in comment
  clippy_lints/src/matches/needless_match.rs
Labels: S-waiting-on-review

#8705 Spellcheck
  .github/ISSUE_TEMPLATE/blank_issue.yml
  .github/ISSUE_TEMPLATE/false_negative.yml
  .github/ISSUE_TEMPLATE/false_positive.yml
  .github/workflows/clippy.yml
  clippy_dev/src/setup/mod.rs
  clippy_lints/src/casts/mod.rs
  clippy_lints/src/empty_structs_with_brackets.rs
  clippy_lints/src/index_refutable_slice.rs
  clippy_lints/src/match_result_ok.rs
  clippy_lints/src/matches/infallible_destructuring_match.rs
  clippy_lints/src/matches/match_same_arms.rs
  clippy_lints/src/matches/mod.rs
  clippy_lints/src/matches/needless_match.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/missing_inline.rs
  clippy_lints/src/needless_bitwise_bool.rs
  clippy_lints/src/needless_late_init.rs
  clippy_lints/src/octal_escapes.rs
  clippy_lints/src/option_if_let_else.rs
  clippy_lints/src/suspicious_operation_groupings.rs
  clippy_lints/src/transmute/utils.rs
  clippy_lints/src/types/mod.rs
  clippy_lints/src/unnested_or_patterns.rs
  clippy_lints/src/use_self.rs
  clippy_lints/src/utils/author.rs
  clippy_lints/src/utils/internal_lints.rs
  clippy_lints/src/utils/internal_lints/metadata_collector.rs
  clippy_utils/src/macros.rs
  clippy_utils/src/source.rs
  lintcheck/src/main.rs
  tests/lint_message_convention.rs
  tests/ui-internal/collapsible_span_lint_calls.stderr
  tests/ui/auxiliary/proc_macro_derive.rs
  tests/ui/needless_late_init.stderr
  tests/ui/needless_late_init_fixable.stderr
Labels: S-waiting-on-review

#8698 Changelog for Rust 1.61 :octopus:
  CHANGELOG.md
Labels: S-waiting-on-review

#8706 Fix formatting of `cast_abs_to_unsigned` docs
  clippy_lints/src/casts/mod.rs
Labels: S-waiting-on-review

#8709 lintcheck: fix --fix
  lintcheck/src/main.rs
Labels: S-waiting-on-review

#8665 Introduce needless_option_take lint
  CHANGELOG.md
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_complexity.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/needless_option_take.rs
  tests/ui/needless_option_take.fixed
  tests/ui/needless_option_take.rs
  tests/ui/needless_option_take.stderr
  tests/ui/option_take_on_temporary.fixed
Labels: S-waiting-on-review

#8701 Rework `#[clippy::dump]` attribute for debugging
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/dump_hir.rs
  clippy_lints/src/utils/inspector.rs
  clippy_lints/src/utils/internal_lints/metadata_collector.rs
  clippy_lints/src/utils/mod.rs
  doc/adding_lints.md
Labels: S-needs-discussion, S-waiting-on-review

#8707 Add `await_holding_invalid_type` lint
  CHANGELOG.md
  clippy_lints/src/await_holding_invalid.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_suspicious.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/conf.rs
  tests/ui-toml/await_holding_invalid_type/await_holding_invalid_type.rs
  tests/ui-toml/await_holding_invalid_type/await_holding_invalid_type.stderr
  tests/ui-toml/await_holding_invalid_type/clippy.toml
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
Labels: S-waiting-on-review

#8711 Take over: New lint bytes count to len
  CHANGELOG.md
  clippy_lints/src/bytes_count_to_len.rs
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_complexity.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.rs
  clippy_utils/src/paths.rs
  tests/ui/bytes_count_to_len.fixed
  tests/ui/bytes_count_to_len.rs
  tests/ui/bytes_count_to_len.stderr
Labels: S-waiting-on-review

#8700 Fix needless_match false positive for if-let when the else block doesn't match to given expr
  clippy_lints/src/matches/needless_match.rs
  tests/ui/needless_match.fixed
  tests/ui/needless_match.rs
  tests/ui/needless_match.stderr
Labels: S-waiting-on-review

#8716 Less authoritative stable_sort_primitive message
  clippy_lints/src/lib.register_all.rs
  clippy_lints/src/lib.register_pedantic.rs
  clippy_lints/src/lib.register_perf.rs
  clippy_lints/src/stable_sort_primitive.rs
  tests/ui/stable_sort_primitive.stderr
Labels: S-waiting-on-review

#8571 add `empty_drop`
  CHANGELOG.md
  clippy_lints/src/empty_drop.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_restriction.rs
  clippy_lints/src/lib.rs
  tests/ui/empty_drop.fixed
  tests/ui/empty_drop.rs
  tests/ui/empty_drop.stderr
Labels: S-waiting-on-author

#8729 Fix missing whitespace in `collapsible_else_if` suggestion
  clippy_lints/src/collapsible_if.rs
  tests/ui/collapsible_else_if.fixed
  tests/ui/collapsible_else_if.rs
  tests/ui/collapsible_else_if.stderr
Labels: S-waiting-on-review

#8717 `manual_split_once`: lint manual iteration of `SplitN`
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/str_splitn.rs
  tests/ui/manual_split_once.fixed
  tests/ui/manual_split_once.rs
  tests/ui/manual_split_once.stderr
Labels: S-waiting-on-review

#8731 dogfood: allow unknown lints when not running with `internal` feature
  tests/dogfood.rs
Labels: S-waiting-on-review

#8736 Add macro export exemption to `redundant_pub_crate`
  clippy_lints/src/redundant_pub_crate.rs
  tests/ui/redundant_pub_crate.fixed
  tests/ui/redundant_pub_crate.rs
Labels: S-waiting-on-review

#8738 wrong_self_convention allows `is_*` to take `&mut self`
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/wrong_self_convention.rs
  tests/ui/wrong_self_convention.rs
  tests/ui/wrong_self_convention.stderr
  tests/ui/wrong_self_convention2.rs
Labels: S-waiting-on-review

#8742 mistyped_literal_suffix: improve integer suggestions, avoid wrong float suggestions
  clippy_lints/src/literal_representation.rs
  tests/ui/mistyped_literal_suffix.fixed
  tests/ui/mistyped_literal_suffix.rs
  tests/ui/mistyped_literal_suffix.stderr
Labels: S-waiting-on-review

#8727 Add `large_include_file` lint
  CHANGELOG.md
  clippy_lints/src/large_include_file.rs
  clippy_lints/src/lib.register_lints.rs
  clippy_lints/src/lib.register_restriction.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/conf.rs
  tests/ui-toml/large_include_file/clippy.toml
  tests/ui-toml/large_include_file/large_include_file.rs
  tests/ui-toml/large_include_file/large_include_file.stderr
  tests/ui-toml/large_include_file/too_big.txt
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
Labels: S-waiting-on-review

#8737 Extend `extra_unused_lifetimes` to handle impl lifetimes
  clippy_lints/src/lifetimes.rs
  tests/ui/crashes/ice-2865.rs
  tests/ui/crashes/ice-3151.rs
  tests/ui/extra_unused_lifetimes.rs
  tests/ui/extra_unused_lifetimes.stderr
  tests/ui/impl.rs
  tests/ui/new_without_default.rs
Labels: S-waiting-on-review

#8617 `needless_late_init`: ignore `if let`, `let mut` and significant drops
  clippy_lints/src/matches/redundant_pattern_match.rs
  clippy_lints/src/needless_late_init.rs
  clippy_utils/src/ty.rs
  tests/ui/needless_late_init.rs
  tests/ui/needless_late_init.stderr
  tests/ui/needless_late_init_fixable.fixed
  tests/ui/needless_late_init_fixable.rs
  tests/ui/needless_late_init_fixable.stderr
Labels: S-waiting-on-review

#8743 ignore `redundant_pub_crate` in `useless_attribute`
  clippy_lints/src/attrs.rs
  tests/ui/useless_attribute.fixed
  tests/ui/useless_attribute.rs
  tests/ui/useless_attribute.stderr
Labels: S-waiting-on-review

#8431 `redundant_closure` fix FP on coerced closure
  clippy_lints/src/eta_reduction.rs
  tests/ui/eta.fixed
  tests/ui/eta.rs
  tests/ui/eta.stderr
Labels: S-waiting-on-review

#8764 Update GitHub Actions actions/checkout@v2 to v3
  .github/workflows/clippy.yml
  .github/workflows/clippy_bors.yml
  .github/workflows/clippy_dev.yml
  .github/workflows/deploy.yml
  .github/workflows/remark.yml
Labels: S-waiting-on-review

#8720 fix ICE in `cast_slice_different_sizes`
  clippy_lints/src/casts/cast_slice_different_sizes.rs
  tests/ui/cast_slice_different_sizes.rs
  tests/ui/cast_slice_different_sizes.stderr
Labels: S-waiting-on-review

#8625 Add `cargo dev rename_lint`
  clippy_dev/Cargo.toml
  clippy_dev/src/lib.rs
  clippy_dev/src/main.rs
  clippy_dev/src/update_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/renamed_lints.rs
  tests/ui/deprecated.rs
  tests/ui/deprecated.stderr
  tests/ui/rename.fixed
  tests/ui/rename.rs
  tests/ui/rename.stderr
Labels: S-waiting-on-review

#8767 Add missing quite in `large_include_file` example
  clippy_lints/src/large_include_file.rs
Labels: S-waiting-on-review
