Repository rust-lang/rust-clippy, pull requests merged in 2023-09, with the labels that each got.

#10692 new lint: `missing_asserts_for_indexing`
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/missing_asserts_for_indexing.rs
  tests/ui/missing_asserts_for_indexing.fixed
  tests/ui/missing_asserts_for_indexing.rs
  tests/ui/missing_asserts_for_indexing.stderr
  tests/ui/missing_asserts_for_indexing_unfixable.rs
  tests/ui/missing_asserts_for_indexing_unfixable.stderr
Labels: S-waiting-on-review

#11430 Correctly format `vec!` invocations
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/unit_return_expecting_ord.rs
Labels: S-waiting-on-review

#11427 Bump ui_test
  Cargo.toml
  tests/compile-test.rs
Labels: S-waiting-on-review

#11416 Use multipart suggestions for raw string lints
  clippy_lints/src/raw_strings.rs
  tests/ui/needless_raw_string.fixed
  tests/ui/needless_raw_string.rs
  tests/ui/needless_raw_string.stderr
  tests/ui/needless_raw_string_hashes.fixed
  tests/ui/needless_raw_string_hashes.rs
  tests/ui/needless_raw_string_hashes.stderr
  tests/ui/write_literal_2.stderr
Labels: S-waiting-on-review

#10596 Clippy Book Chapter Updates Reborn: Writing tests
  book/src/SUMMARY.md
  book/src/development/writing_tests.md
Labels: S-waiting-on-review

#10598 Clippy Book Chapter Updates Reborn: Emitting lints
  book/src/SUMMARY.md
  book/src/development/emitting_lints.md
Labels: S-waiting-on-review

#11445 fix some comments
  clippy_utils/src/source.rs
  clippy_utils/src/sugg.rs
  clippy_utils/src/ty/type_certainty/mod.rs
Labels: S-waiting-on-review

#11448 DefaultUnionRepresentation: explain why we only warn about unions with at least 2 non-ZST fields
  clippy_lints/src/default_union_representation.rs
Labels: S-waiting-on-review

#10626 Clippy Book Chapter Updates Reborn: Trait Checking
  book/src/SUMMARY.md
  book/src/development/trait_checking.md
Labels: S-waiting-on-review

#11450 `never_loop` catches `loop { panic!() }`
  clippy_lints/src/loops/never_loop.rs
  tests/ui/crashes/ice-360.rs
  tests/ui/crashes/ice-360.stderr
  tests/ui/empty_loop.rs
  tests/ui/empty_loop.stderr
  tests/ui/iter_out_of_bounds.rs
  tests/ui/iter_out_of_bounds.stderr
  tests/ui/needless_collect_indirect.rs
  tests/ui/needless_collect_indirect.stderr
  tests/ui/never_loop.rs
  tests/ui/never_loop.stderr
  tests/ui/similar_names.rs
  tests/ui/similar_names.stderr
  tests/ui/vec.fixed
  tests/ui/vec.rs
  tests/ui/vec.stderr
Labels: S-waiting-on-review

#11437 [`implied_bounds_in_impls`]: don't ICE on default generic parameter and move to nursery
  clippy_lints/src/implied_bounds_in_impls.rs
  tests/ui/crashes/ice-11422.fixed
  tests/ui/crashes/ice-11422.rs
  tests/ui/crashes/ice-11422.stderr
  tests/ui/implied_bounds_in_impls.fixed
  tests/ui/implied_bounds_in_impls.rs
  tests/ui/implied_bounds_in_impls.stderr
Labels: S-waiting-on-review

#11449 Should be final writing_tests commit
  book/src/development/writing_tests.md
Labels: S-waiting-on-review

#11259 Don't pass extra generic arguments in `needless_borrow`
  clippy_lints/src/dereference.rs
  tests/ui/needless_borrow.fixed
  tests/ui/needless_borrow.rs
Labels: S-waiting-on-review

#11455 skip `todo!()` in `never_loop`
  clippy_lints/src/loops/never_loop.rs
  tests/ui/needless_collect_indirect.rs
  tests/ui/needless_collect_indirect.stderr
  tests/ui/never_loop.rs
  tests/ui/never_loop.stderr
  tests/ui/vec.fixed
  tests/ui/vec.rs
  tests/ui/vec.stderr
Labels: S-waiting-on-review

#11375 fix fp when [`undocumented_unsafe_blocks`] not able to detect comment on globally defined const/static variables
  clippy_lints/src/undocumented_unsafe_blocks.rs
  tests/ui-toml/undocumented_unsafe_blocks/undocumented_unsafe_blocks.rs
Labels: S-waiting-on-review

#11454 Ignore wildcards in function arguments and local bindings
  clippy_lints/src/ignored_unit_patterns.rs
  tests/ui/ignored_unit_patterns.fixed
  tests/ui/ignored_unit_patterns.rs
  tests/ui/ignored_unit_patterns.stderr
Labels: S-waiting-on-review

#11439 Check binary operators and attributes in disallowed_macros
  clippy_lints/src/disallowed_macros.rs
  tests/ui-toml/disallowed_macros/auxiliary/macros.rs
  tests/ui-toml/disallowed_macros/clippy.toml
  tests/ui-toml/disallowed_macros/disallowed_macros.rs
  tests/ui-toml/disallowed_macros/disallowed_macros.stderr
Labels: S-waiting-on-review

#11466 Fix `i686-unknown-linux-gnu` CI job
  .github/workflows/clippy_bors.yml
  tests/compile-test.rs
  tests/ui/cast_size.32bit.stderr
  tests/ui/cast_size.64bit.stderr
  tests/ui/cast_size.rs
  tests/ui/cast_size_32bit.rs
  tests/ui/fn_to_numeric_cast.32bit.stderr
  tests/ui/fn_to_numeric_cast.64bit.stderr
  tests/ui/fn_to_numeric_cast.rs
  tests/ui/fn_to_numeric_cast_32bit.rs
  tests/ui/large_enum_variant.rs
  tests/ui/large_enum_variant.stderr
  tests/ui/result_large_err.rs
  tests/ui/result_large_err.stderr
  tests/ui/single_call_fn.rs
  tests/ui/single_call_fn.stderr
  tests/ui/transmute_32bit.stderr
Labels: S-waiting-on-review

#11451 [`slow_vector_initialization`]: use the source span of vec![] macro and fix another FP
  clippy_lints/src/slow_vector_initialization.rs
  tests/ui/slow_vector_initialization.rs
  tests/ui/slow_vector_initialization.stderr
Labels: S-waiting-on-review

#11462 Preserve literals and range kinds in `manual_range_patterns`
  clippy_lints/src/manual_range_patterns.rs
  tests/ui/manual_range_patterns.fixed
  tests/ui/manual_range_patterns.rs
  tests/ui/manual_range_patterns.stderr
Labels: S-waiting-on-review

#11358 Rename incorrect_impls to non_canonical_impls, move them to warn by default
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/non_canonical_impls.rs
  clippy_lints/src/renamed_lints.rs
  tests/ui/bool_comparison.fixed
  tests/ui/bool_comparison.rs
  tests/ui/clone_on_copy_impl.rs
  tests/ui/derive.rs
  tests/ui/derive.stderr
  tests/ui/derive_ord_xor_partial_ord.rs
  tests/ui/non_canonical_clone_impl.fixed
  tests/ui/non_canonical_clone_impl.rs
  tests/ui/non_canonical_clone_impl.stderr
  tests/ui/non_canonical_partial_ord_impl.fixed
  tests/ui/non_canonical_partial_ord_impl.rs
  tests/ui/non_canonical_partial_ord_impl.stderr
  tests/ui/non_canonical_partial_ord_impl_fully_qual.rs
  tests/ui/non_canonical_partial_ord_impl_fully_qual.stderr
  tests/ui/rename.fixed
  tests/ui/rename.rs
  tests/ui/rename.stderr
  tests/ui/unnecessary_struct_initialization.fixed
  tests/ui/unnecessary_struct_initialization.rs
Labels: S-waiting-on-review

#11459 [`implied_bounds_in_impls`]: include (previously omitted) associated types in suggestion
  clippy_lints/src/implied_bounds_in_impls.rs
  tests/ui/implied_bounds_in_impls.fixed
  tests/ui/implied_bounds_in_impls.rs
  tests/ui/implied_bounds_in_impls.stderr
Labels: S-waiting-on-review

#11477 Auto deref does not apply on union field
  clippy_lints/src/dereference.rs
  tests/ui/explicit_auto_deref.fixed
  tests/ui/explicit_auto_deref.rs
Labels: S-waiting-on-review

#11413 new unnecessary_map_on_constructor lint
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/unnecessary_map_on_constructor.rs
  tests/ui/eta.fixed
  tests/ui/eta.rs
  tests/ui/eta.stderr
  tests/ui/manual_map_option.fixed
  tests/ui/manual_map_option.rs
  tests/ui/manual_map_option.stderr
  tests/ui/option_filter_map.fixed
  tests/ui/option_filter_map.rs
  tests/ui/result_map_unit_fn_unfixable.rs
  tests/ui/unnecessary_map_on_constructor.fixed
  tests/ui/unnecessary_map_on_constructor.rs
  tests/ui/unnecessary_map_on_constructor.stderr
Labels: S-waiting-on-review

#11473 Ignore span's parents in `collect_ast_format_args`/`find_format_args`
  clippy_utils/src/macros.rs
Labels: S-waiting-on-review, beta-nominated

#11452 [`len_without_is_empty`]: follow type alias to find inherent `is_empty` method
  clippy_lints/src/len_zero.rs
  tests/ui/len_without_is_empty.rs
  tests/ui/len_without_is_empty.stderr
Labels: S-waiting-on-review

#11497 Remove `derive_new` test dependency
  Cargo.toml
  tests/compile-test.rs
  tests/ui/redundant_field_names.fixed
  tests/ui/redundant_field_names.rs
  tests/ui/redundant_field_names.stderr
Labels: S-waiting-on-review

#11444 Return a value from find_format_args instead of using a callback
  clippy_lints/src/explicit_write.rs
  clippy_lints/src/format.rs
  clippy_lints/src/format_args.rs
  clippy_lints/src/format_impl.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/methods/expect_fun_call.rs
  clippy_lints/src/utils/format_args_collector.rs
  clippy_lints/src/write.rs
  clippy_utils/src/macros.rs
Labels: S-waiting-on-review

#11505 Truncate files when opening in metadata-collector
  clippy_lints/src/utils/internal_lints/metadata_collector.rs
Labels: S-waiting-on-review

#11504 Ignore closures for some type lints
  clippy_lints/src/types/mod.rs
  tests/ui/redundant_allocation.rs
  tests/ui/vec_box_sized.fixed
  tests/ui/vec_box_sized.rs
Labels: S-waiting-on-review

#11484 [`extra_unused_type_parameters`]: Fix edge case FP for parameters in where bounds
  clippy_lints/src/extra_unused_type_parameters.rs
  tests/ui/extra_unused_type_parameters.fixed
  tests/ui/extra_unused_type_parameters.rs
Labels: S-waiting-on-review

#11506 fix filter_map_bool_then with a bool reference
  clippy_lints/src/methods/filter_map_bool_then.rs
  tests/ui/filter_map_bool_then.fixed
  tests/ui/filter_map_bool_then.rs
  tests/ui/filter_map_bool_then.stderr
Labels: S-waiting-on-review

#11483 new lint: `path_ends_with_ext`
  CHANGELOG.md
  book/src/lint_configuration.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/path_ends_with_ext.rs
  clippy_lints/src/utils/conf.rs
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
  tests/ui/path_ends_with_ext.fixed
  tests/ui/path_ends_with_ext.rs
  tests/ui/path_ends_with_ext.stderr
Labels: S-waiting-on-review

#11301 [`useless_conversion`]: don't lint if type parameter has unsatisfiable bounds for `.into_iter()` receiver
  clippy_lints/src/useless_conversion.rs
  tests/ui/useless_conversion.fixed
  tests/ui/useless_conversion.rs
  tests/ui/useless_conversion.stderr
Labels: S-waiting-on-review

#11507 trigger [`transmute_null_to_fn`] on chain of casts
  clippy_lints/src/transmute/transmute_null_to_fn.rs
  tests/ui/transmute_null_to_fn.rs
  tests/ui/transmute_null_to_fn.stderr
Labels: S-waiting-on-review

#11509 fix FP of let_unit_value on async fn args
  clippy_lints/src/unit_types/let_unit_value.rs
  tests/ui/let_unit.fixed
  tests/ui/let_unit.rs
Labels: S-waiting-on-review

#11468 add extra `byref` checking for the guard's local
  clippy_lints/src/matches/redundant_guards.rs
  tests/ui/redundant_guards.fixed
  tests/ui/redundant_guards.rs
  tests/ui/redundant_guards.stderr
Labels: S-waiting-on-review

#11511 Split `needless_borrow` into two lints
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/dereference.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/needless_borrows_for_generic_args.rs
  clippy_utils/src/mir/mod.rs
  tests/ui/needless_borrow.fixed
  tests/ui/needless_borrow.rs
  tests/ui/needless_borrow.stderr
  tests/ui/needless_borrows_for_generic_args.fixed
  tests/ui/needless_borrows_for_generic_args.rs
  tests/ui/needless_borrows_for_generic_args.stderr
  tests/ui/regex.rs
  tests/ui/regex.stderr
  tests/ui/unnecessary_to_owned.fixed
  tests/ui/unnecessary_to_owned.rs
Labels: S-waiting-on-review

#11523 used_underscore_bindings: respect lint levels on the binding definition
  clippy_lints/src/misc.rs
  clippy_utils/src/lib.rs
  tests/ui/used_underscore_binding.rs
  tests/ui/used_underscore_binding.stderr
Labels: S-waiting-on-review

#11517 fix ICE by `u64::try_from(<u128>)`
  clippy_lints/src/casts/cast_possible_truncation.rs
  tests/ui/cast.rs
Labels: S-waiting-on-review

#11526 Add redundant_as_str lint
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/redundant_as_str.rs
  tests/ui/redundant_as_str.fixed
  tests/ui/redundant_as_str.rs
  tests/ui/redundant_as_str.stderr
Labels: S-waiting-on-review

#11530 Move zero_ptr to the casts module
  clippy_lints/src/casts/mod.rs
  clippy_lints/src/casts/zero_ptr.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/misc.rs
Labels: S-waiting-on-review

#11516 fix cast_lossless with macro call
  clippy_lints/src/casts/cast_lossless.rs
  tests/ui/cast_lossless_integer.fixed
  tests/ui/cast_lossless_integer.rs
  tests/ui/cast_lossless_integer.stderr
Labels: S-waiting-on-review

#11492 Fix mutaby used async function argument in closure for `needless_pass_by_ref_mut`
  clippy_lints/src/needless_pass_by_ref_mut.rs
  tests/ui/needless_pass_by_ref_mut.rs
  tests/ui/needless_pass_by_ref_mut.stderr
Labels: S-waiting-on-review

#11170 Change defaults of `accept-comment-above-statement` and `accept-comment-above-attributes`
  book/src/lint_configuration.md
  clippy_lints/src/utils/conf.rs
  tests/ui-toml/undocumented_unsafe_blocks/clippy.toml
  tests/ui-toml/undocumented_unsafe_blocks/default/clippy.toml
  tests/ui-toml/undocumented_unsafe_blocks/disabled/clippy.toml
  tests/ui-toml/undocumented_unsafe_blocks/undocumented_unsafe_blocks.default.stderr
  tests/ui-toml/undocumented_unsafe_blocks/undocumented_unsafe_blocks.disabled.stderr
  tests/ui-toml/undocumented_unsafe_blocks/undocumented_unsafe_blocks.rs
  tests/ui/undocumented_unsafe_blocks.rs
Labels: S-waiting-on-review

#11522 [`redundant_guards`]: lint if the pattern is on the left side
  clippy_lints/src/matches/redundant_guards.rs
  tests/ui/redundant_guards.fixed
  tests/ui/redundant_guards.rs
  tests/ui/redundant_guards.stderr
Labels: S-waiting-on-review

#11551 fixed fp caused by moving &mut reference inside of a closure
  clippy_lints/src/needless_pass_by_ref_mut.rs
  tests/ui/needless_pass_by_ref_mut.rs
  tests/ui/needless_pass_by_ref_mut.stderr
Labels: S-waiting-on-review

#11553 Fix large_futures example
  clippy_lints/src/large_futures.rs
Labels: S-waiting-on-review

#11552 prevent ice when threshold is 0 and enum has no variants
  clippy_lints/src/enum_variants.rs
  tests/ui-toml/enum_variants_threshold0/clippy.toml
  tests/ui-toml/enum_variants_threshold0/enum_variants_name_threshold.rs
Labels: S-waiting-on-review

#11563 Rustup
  clippy_lints/Cargo.toml
  clippy_lints/src/await_holding_invalid.rs
  clippy_lints/src/dereference.rs
  clippy_lints/src/derive.rs
  clippy_lints/src/doc.rs
  clippy_lints/src/enum_clike.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/matches/overlapping_arms.rs
  clippy_lints/src/non_copy_const.rs
  clippy_lints/src/operators/arithmetic_side_effects.rs
  clippy_lints/src/operators/numeric_arithmetic.rs
  clippy_lints/src/raw_strings.rs
  clippy_lints/src/redundant_closure_call.rs
  clippy_lints/src/suspicious_operation_groupings.rs
  clippy_lints/src/undocumented_unsafe_blocks.rs
  clippy_lints/src/unnested_or_patterns.rs
  clippy_lints/src/utils/internal_lints/interning_defined_symbol.rs
  clippy_lints/src/utils/internal_lints/unnecessary_def_path.rs
  clippy_utils/src/ast_utils.rs
  clippy_utils/src/consts.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/source.rs
  clippy_utils/src/ty.rs
  clippy_utils/src/ty/type_certainty/mod.rs
  rust-toolchain
  tests/ui-toml/await_holding_invalid_type/await_holding_invalid_type.rs
  tests/ui-toml/await_holding_invalid_type/await_holding_invalid_type.stderr
  tests/ui-toml/disallowed_macros/disallowed_macros.stderr
  tests/ui-toml/suppress_lint_in_const/test.stderr
  tests/ui/allow_attributes.fixed
  tests/ui/allow_attributes.rs
  tests/ui/arithmetic_side_effects.rs
  tests/ui/await_holding_lock.stderr
  tests/ui/await_holding_refcell_ref.stderr
  tests/ui/blanket_clippy_restriction_lints.stderr
  tests/ui/box_default.fixed
  tests/ui/box_default.rs
  tests/ui/crashes/ice-6251.stderr
  tests/ui/doc/doc-fixable.fixed
  tests/ui/doc/doc-fixable.rs
  tests/ui/doc/doc-fixable.stderr
  tests/ui/doc/unbalanced_ticks.rs
  tests/ui/doc/unbalanced_ticks.stderr
  tests/ui/doc_errors.rs
  tests/ui/doc_errors.stderr
  tests/ui/future_not_send.rs
  tests/ui/future_not_send.stderr
  tests/ui/indexing_slicing_index.stderr
  tests/ui/needless_doc_main.rs
  tests/ui/needless_doc_main.stderr
  tests/ui/write_literal_2.stderr
Labels: S-waiting-on-review

#11495 Add colored help to be consistent with Cargo
  Cargo.toml
  src/driver.rs
  src/main.rs
Labels: S-waiting-on-review, I-nominated

#11557 Add msrv test template for `cargo dev new_lint --msrv`
  clippy_dev/src/new_lint.rs
Labels: S-waiting-on-review

#11564 Test that each config value exists in a test clippy.toml
  clippy_lints/Cargo.toml
  clippy_lints/src/utils/conf.rs
Labels: S-waiting-on-review

#10300 Do not lint when imported item contains underscore
  clippy_lints/src/wildcard_imports.rs
  tests/ui/wildcard_imports.fixed
  tests/ui/wildcard_imports.rs
  tests/ui/wildcard_imports.stderr
  tests/ui/wildcard_imports_2021.edition2018.fixed
  tests/ui/wildcard_imports_2021.edition2018.stderr
  tests/ui/wildcard_imports_2021.edition2021.fixed
  tests/ui/wildcard_imports_2021.edition2021.stderr
  tests/ui/wildcard_imports_2021.rs
Labels: S-waiting-on-author

#11556 Add `manual_hash_one` lint
  CHANGELOG.md
  book/src/lint_configuration.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_hash_one.rs
  clippy_lints/src/utils/conf.rs
  clippy_utils/src/msrvs.rs
  clippy_utils/src/visitors.rs
  tests/ui/manual_hash_one.fixed
  tests/ui/manual_hash_one.rs
  tests/ui/manual_hash_one.stderr
Labels: S-waiting-on-review

#11569 Describe the type of string in raw_strings lints
  clippy_lints/src/raw_strings.rs
  tests/ui/needless_raw_string.fixed
  tests/ui/needless_raw_string.rs
  tests/ui/needless_raw_string.stderr
  tests/ui/needless_raw_string_hashes.stderr
  tests/ui/write_literal_2.rs
  tests/ui/write_literal_2.stderr
Labels: S-waiting-on-review

#11574 Mention that `missing_assert_message` lint ignores test functions
  clippy_lints/src/missing_assert_message.rs
Labels: S-waiting-on-review

#11415 Move `needless_raw_string_hashes` to `pedantic`
  clippy_lints/src/raw_strings.rs
Labels: S-waiting-on-review, beta-nominated

#11576 write_literal: Fix index of the remaining positional arguments
  clippy_lints/src/write.rs
  tests/ui/print_literal.fixed
  tests/ui/print_literal.rs
  tests/ui/print_literal.stderr
  tests/ui/write_literal.fixed
  tests/ui/write_literal.rs
  tests/ui/write_literal.stderr
  tests/ui/write_literal_2.rs
  tests/ui/write_literal_2.stderr
Labels: S-waiting-on-review

#11565 mir_to_const improvements
  clippy_lints/src/enum_clike.rs
  clippy_lints/src/matches/overlapping_arms.rs
  clippy_utils/src/consts.rs
  clippy_utils/src/lib.rs
Labels: S-waiting-on-review

#11527 new lint: `iter_without_into_iter`
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/iter_without_into_iter.rs
  clippy_lints/src/lib.rs
  tests/ui/iter_without_into_iter.rs
  tests/ui/iter_without_into_iter.stderr
Labels: S-waiting-on-review

#11582 Add missing lint description headers
  clippy_lints/src/allow_attributes.rs
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-review

#11580 [`manual_let_else`]: only omit block if span is from same ctxt
  clippy_lints/src/manual_let_else.rs
  tests/ui/manual_let_else_match.fixed
  tests/ui/manual_let_else_match.rs
  tests/ui/manual_let_else_match.stderr
Labels: S-waiting-on-review

#11587 new lint: `into_iter_without_iter`
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/iter_without_into_iter.rs
  tests/ui/into_iter_without_iter.rs
  tests/ui/into_iter_without_iter.stderr
Labels: S-waiting-on-review
