Repository rust-lang/rust-clippy, pull requests merged in 2023-06, with the labels that each got.

#10857 Explain which paths clippy searches for configuration in docs
  book/src/configuration.md
  book/src/development/adding_lints.md
  clippy_lints/src/utils/conf.rs
Labels: S-waiting-on-review

#10607 Add spans to `clippy.toml` error messages
  Cargo.toml
  clippy_lints/Cargo.toml
  clippy_lints/src/lib.rs
  clippy_lints/src/nonstandard_macro_braces.rs
  clippy_lints/src/utils/conf.rs
  lintcheck/Cargo.toml
  src/driver.rs
  tests/ui-toml/bad_toml/conf_bad_toml.stderr
  tests/ui-toml/bad_toml_type/conf_bad_type.stderr
  tests/ui-toml/conf_deprecated_key/conf_deprecated_key.stderr
  tests/ui-toml/duplicated_keys/clippy.toml
  tests/ui-toml/duplicated_keys/duplicated_keys.stderr
  tests/ui-toml/duplicated_keys_deprecated/clippy.toml
  tests/ui-toml/duplicated_keys_deprecated/duplicated_keys.rs
  tests/ui-toml/duplicated_keys_deprecated/duplicated_keys.stderr
  tests/ui-toml/duplicated_keys_deprecated_2/clippy.toml
  tests/ui-toml/duplicated_keys_deprecated_2/duplicated_keys.rs
  tests/ui-toml/duplicated_keys_deprecated_2/duplicated_keys.stderr
  tests/ui-toml/toml_unknown_key/clippy.toml
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
Labels: S-waiting-on-review

#10871 Rustup
  Cargo.toml
  clippy_lints/Cargo.toml
  clippy_lints/src/casts/cast_ref_to_mut.rs
  clippy_lints/src/casts/mod.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/dereference.rs
  clippy_lints/src/drop_forget_ref.rs
  clippy_lints/src/eta_reduction.rs
  clippy_lints/src/invalid_utf8_in_unchecked.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/methods/needless_collect.rs
  clippy_lints/src/methods/unnecessary_to_owned.rs
  clippy_lints/src/missing_const_for_fn.rs
  clippy_lints/src/missing_fields_in_debug.rs
  clippy_lints/src/multiple_unsafe_ops_per_block.rs
  clippy_lints/src/needless_pass_by_value.rs
  clippy_lints/src/renamed_lints.rs
  clippy_lints/src/strings.rs
  clippy_lints/src/unnecessary_wraps.rs
  clippy_utils/Cargo.toml
  clippy_utils/src/consts.rs
  clippy_utils/src/diagnostics.rs
  clippy_utils/src/paths.rs
  clippy_utils/src/sugg.rs
  declare_clippy_lint/Cargo.toml
  rust-toolchain
  tests/ui-internal/custom_ice_message.rs
  tests/ui-internal/custom_ice_message.stderr
  tests/ui/cast_ref_to_mut.rs
  tests/ui/cast_ref_to_mut.stderr
  tests/ui/invalid_utf8_in_unchecked.rs
  tests/ui/invalid_utf8_in_unchecked.stderr
  tests/ui/mem_forget.rs
  tests/ui/multiple_unsafe_ops_per_block.rs
  tests/ui/rename.fixed
  tests/ui/rename.rs
  tests/ui/rename.stderr
Labels: S-waiting-on-review

#10860 add checking for cfg(features = ...)
  CHANGELOG.md
  clippy_lints/src/attrs.rs
  clippy_lints/src/declared_lints.rs
  tests/ui/cfg_features.rs
  tests/ui/cfg_features.stderr
Labels: S-waiting-on-review

#10862 Update *Current stable* text in `CHANGELOG.md`
  CHANGELOG.md
Labels: S-waiting-on-review

#10699 Clippy Book Chapter Updates Reborn: Refresh Lint Configuration's looks
  book/src/lint_configuration.md
  clippy_lints/src/utils/internal_lints/metadata_collector.rs
  clippy_lints/src/utils/mod.rs
Labels: S-waiting-on-review

#10821 Emit `unnecessary_cast` on raw pointers as well
  clippy_lints/src/casts/mod.rs
  clippy_lints/src/casts/unnecessary_cast.rs
  tests/ui/as_ptr_cast_mut.rs
  tests/ui/cast_slice_different_sizes.rs
  tests/ui/crashes/ice-1782.rs
  tests/ui/from_raw_with_void_ptr.rs
  tests/ui/from_raw_with_void_ptr.stderr
  tests/ui/transmute_ptr_to_ref.fixed
  tests/ui/transmute_ptr_to_ref.rs
  tests/ui/unnecessary_cast.fixed
  tests/ui/unnecessary_cast.rs
  tests/ui/unnecessary_cast.stderr
Labels: S-waiting-on-review

#10834 Use URL parameters for filter states
  util/gh-pages/index.html
  util/gh-pages/script.js
Labels: S-waiting-on-review

#10879 [`ptr_cast_constness`]: Only lint on casts which don't change type
  clippy_lints/src/casts/ptr_cast_constness.rs
  tests/ui/ptr_cast_constness.fixed
  tests/ui/ptr_cast_constness.rs
  tests/ui/ptr_cast_constness.stderr
Labels: S-waiting-on-review

#10866 manual_let_else: support struct patterns
  clippy_lints/src/manual_let_else.rs
  tests/ui/manual_let_else.rs
  tests/ui/manual_let_else.stderr
  tests/ui/manual_let_else_match.rs
  tests/ui/manual_let_else_match.stderr
Labels: S-waiting-on-review

#10814 new lint: `explicit_into_iter_fn_arg`
  clippy_lints/src/booleans.rs
  clippy_lints/src/loops/manual_memcpy.rs
  clippy_lints/src/useless_conversion.rs
  tests/ui/auxiliary/proc_macro_derive.rs
  tests/ui/useless_conversion.fixed
  tests/ui/useless_conversion.rs
  tests/ui/useless_conversion.stderr
Labels: S-waiting-on-review

#10881 [`useless_conversion`]: pluralize if there are multiple `.into_iter()` calls
  clippy_lints/src/useless_conversion.rs
  tests/ui/useless_conversion.stderr
Labels: S-waiting-on-review

#10760 Standard lint formulations
  clippy_lints/Cargo.toml
  clippy_lints/src/casts/mod.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/default_constructed_unit_structs.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/loops/mod.rs
  clippy_lints/src/matches/mod.rs
  clippy_lints/src/utils/internal_lints.rs
  clippy_lints/src/utils/internal_lints/almost_standard_lint_formulation.rs
  tests/ui-internal/check_formulation.rs
  tests/ui-internal/check_formulation.stderr
Labels: S-waiting-on-review

#10855 Fix suggestion on fully qualified syntax
  clippy_lints/src/dereference.rs
  tests/ui/explicit_deref_methods.fixed
  tests/ui/explicit_deref_methods.rs
  tests/ui/explicit_deref_methods.stderr
Labels: S-waiting-on-review

#10853 Ignore fix for `from_over_into` if the target type contains a `Self` reference
  clippy_lints/src/from_over_into.rs
  tests/ui/from_over_into_unfixable.rs
  tests/ui/from_over_into_unfixable.stderr
Labels: S-waiting-on-review

#10869 [`allow_attributes`, `allow_attributes_without_reason`]: Ignore attributes from procedural macros
  clippy_lints/src/allow_attributes.rs
  clippy_lints/src/attrs.rs
  clippy_utils/src/check_proc_macro.rs
  tests/ui/allow_attributes.fixed
  tests/ui/allow_attributes.rs
  tests/ui/allow_attributes.stderr
  tests/ui/allow_attributes_false_positive.rs
  tests/ui/allow_attributes_without_reason.rs
  tests/ui/allow_attributes_without_reason.stderr
Labels: S-waiting-on-review

#10826 Add lints for disallowing usage of `to_xx_bytes` and `from_xx_bytes`
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/endian_bytes.rs
  clippy_lints/src/lib.rs
  tests/ui/endian_bytes.rs
  tests/ui/endian_bytes.stderr
Labels: S-waiting-on-review

#10888 Remove `CARGO_UNSTABLE_SPARSE_REGISTRY` env from ci
  .github/workflows/clippy.yml
  .github/workflows/clippy_bors.yml
  .github/workflows/clippy_dev.yml
Labels: S-waiting-on-review

#10873 Move `redundant_clone` to `nursery`
  clippy_lints/src/redundant_clone.rs
  tests/ui/redundant_clone.fixed
  tests/ui/redundant_clone.rs
  tests/ui/redundant_clone.stderr
  tests/ui/unnecessary_to_owned.fixed
  tests/ui/unnecessary_to_owned.rs
Labels: S-waiting-on-review, beta-nominated

#10705 Add a test that checks for old style test headers
  tests/headers.rs
  tests/ui/crashes/ice-10645.rs
  tests/ui/crashes/ice-10645.stderr
  tests/ui/crashes/ice-4968.rs
  tests/ui/expect_tool_lint_rfc_2383.rs
  tests/ui/expect_tool_lint_rfc_2383.stderr
Labels: S-waiting-on-review

#10864 [`unnecessary_lazy_eval`]: don't lint on types with deref impl
  clippy_utils/src/eager_or_lazy.rs
  tests/ui/unnecessary_lazy_eval.fixed
  tests/ui/unnecessary_lazy_eval.rs
  tests/ui/unnecessary_lazy_eval.stderr
Labels: S-waiting-on-review

#10859 Bring up Rust lang #37612 as a known problem for let_and_return
  clippy_lints/src/returns.rs
Labels: S-waiting-on-review

#10570 Add redundant type annotations lint
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/redundant_type_annotations.rs
  tests/ui/redundant_type_annotations.rs
  tests/ui/redundant_type_annotations.stderr
Labels: S-waiting-on-review

#10564 make cast_possible_wrap work correctly for 16 bit {u,i}size
  clippy_lints/src/casts/cast_possible_wrap.rs
  clippy_lints/src/casts/mod.rs
  tests/ui/cast.rs
  tests/ui/cast.stderr
Labels: S-waiting-on-review

#10865 [`let_with_type_underscore`]: Don't emit on locals from procedural macros
  clippy_lints/src/let_with_type_underscore.rs
  tests/ui/let_with_type_underscore.rs
  tests/ui/let_with_type_underscore.stderr
Labels: S-waiting-on-review, beta-nominated

#10896 consider autoderef through user-defined `Deref` in `eager_or_lazy`
  clippy_utils/src/eager_or_lazy.rs
  tests/ui/unnecessary_lazy_eval.fixed
  tests/ui/unnecessary_lazy_eval.rs
  tests/ui/unnecessary_lazy_eval.stderr
Labels: S-waiting-on-review

#10897 [`missing_fields_in_debug`]: don't ICE when self type is a generic param
  clippy_lints/src/missing_fields_in_debug.rs
Labels: S-waiting-on-review

#10904 `suspicious_else_formatting`: Don't warn if there is a comment between else and curly bracket
  clippy_lints/src/formatting.rs
  tests/ui/suspicious_else_formatting.rs
Labels: S-waiting-on-review

#10898 Adds new lint `arc_with_non_send_or_sync`
  CHANGELOG.md
  clippy_lints/src/arc_with_non_send_sync.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  tests/ui/arc_with_non_send_sync.rs
  tests/ui/arc_with_non_send_sync.stderr
Labels: S-waiting-on-review

#10905 [`redundant_closure`]: special case inclusive ranges
  clippy_lints/src/eta_reduction.rs
  tests/ui/eta.fixed
  tests/ui/eta.rs
  tests/ui/eta.stderr
Labels: S-waiting-on-review

#10909 Fix `useless_vec` suggestion in `for _ in vec![..]`
  clippy_lints/src/lib.rs
  clippy_lints/src/vec.rs
  tests/ui/vec.fixed
  tests/ui/vec.rs
  tests/ui/vec.stderr
Labels: S-waiting-on-review

#10910 Ignore more pointer types in `unnecessary_cast`
  clippy_lints/src/casts/unnecessary_cast.rs
  tests/ui/unnecessary_cast.fixed
  tests/ui/unnecessary_cast.rs
  tests/ui/unnecessary_cast.stderr
Labels: S-waiting-on-review

#10785 Fix `diverging_sub_expression` not checking body of block
  clippy_lints/src/mixed_read_write_in_expression.rs
  tests/ui/diverging_sub_expression.rs
  tests/ui/diverging_sub_expression.stderr
  tests/ui/never_loop.stderr
Labels: S-waiting-on-review

#10918 Fix `excessive_nesting` example
  clippy_lints/src/excessive_nesting.rs
Labels: S-waiting-on-review

#10907 Direct towards late passes in `cargo dev new_lint`
  clippy_dev/src/main.rs
  clippy_dev/src/new_lint.rs
Labels: S-waiting-on-review

#10914 handle exponent without digits in `numeric_literal`
  clippy_utils/src/numeric_literal.rs
  rustfmt.toml
  tests/ui/crashes/ice-10912.rs
  tests/ui/crashes/ice-10912.stderr
Labels: S-waiting-on-review

#10927 Ignore more type aliases in unnecessary_cast
  clippy_lints/src/casts/unnecessary_cast.rs
  tests/ui/unnecessary_cast.fixed
  tests/ui/unnecessary_cast.rs
  tests/ui/unnecessary_cast.stderr
Labels: S-waiting-on-review

#10416 Extend `explicit_iter_loop` and `explicit_into_iter_loop`
  clippy_lints/src/attrs.rs
  clippy_lints/src/default_numeric_fallback.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/lifetimes.rs
  clippy_lints/src/loops/explicit_into_iter_loop.rs
  clippy_lints/src/loops/explicit_iter_loop.rs
  clippy_lints/src/loops/mod.rs
  clippy_lints/src/loops/same_item_push.rs
  clippy_lints/src/macro_use.rs
  clippy_lints/src/matches/match_wild_err_arm.rs
  clippy_lints/src/matches/significant_drop_in_scrutinee.rs
  clippy_lints/src/matches/try_err.rs
  clippy_lints/src/misc_early/mixed_case_hex_literals.rs
  clippy_lints/src/mismatching_type_param_order.rs
  clippy_lints/src/returns.rs
  clippy_lints/src/significant_drop_tightening.rs
  clippy_lints/src/trait_bounds.rs
  clippy_lints/src/utils/internal_lints/interning_defined_symbol.rs
  clippy_utils/src/msrvs.rs
  clippy_utils/src/qualify_min_const_fn.rs
  clippy_utils/src/ty.rs
  clippy_utils/src/usage.rs
  lintcheck/src/main.rs
  tests/ui/explicit_counter_loop.rs
  tests/ui/explicit_counter_loop.stderr
  tests/ui/explicit_into_iter_loop.fixed
  tests/ui/explicit_into_iter_loop.rs
  tests/ui/explicit_into_iter_loop.stderr
  tests/ui/explicit_iter_loop.fixed
  tests/ui/explicit_iter_loop.rs
  tests/ui/explicit_iter_loop.stderr
  tests/ui/for_loop_fixable.fixed
  tests/ui/for_loop_fixable.rs
  tests/ui/for_loop_fixable.stderr
  tests/ui/for_loop_unfixable.rs
  tests/ui/for_loop_unfixable.stderr
  tests/ui/iter_next_loop.rs
  tests/ui/iter_next_loop.stderr
  tests/ui/needless_collect.fixed
  tests/ui/needless_collect.rs
  tests/ui/needless_range_loop.rs
Labels: S-waiting-on-review

#10894 [`type_repetition_in_bounds`]: Don't lint on derived code
  clippy_lints/src/trait_bounds.rs
  clippy_utils/src/check_proc_macro.rs
  tests/ui/type_repetition_in_bounds.rs
  tests/ui/type_repetition_in_bounds.stderr
Labels: S-waiting-on-review

#10916 New lint [`min_ident_chars`]
  CHANGELOG.md
  book/src/lint_configuration.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/min_ident_chars.rs
  clippy_lints/src/utils/conf.rs
  clippy_utils/src/check_proc_macro.rs
  tests/ui-toml/min_ident_chars/auxiliary/extern_types.rs
  tests/ui-toml/min_ident_chars/clippy.toml
  tests/ui-toml/min_ident_chars/min_ident_chars.rs
  tests/ui-toml/min_ident_chars/min_ident_chars.stderr
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
  tests/ui/min_ident_chars.rs
  tests/ui/min_ident_chars.stderr
Labels: S-waiting-on-review

#10827 new lint: `large_stack_frames`
  CHANGELOG.md
  book/src/lint_configuration.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/large_stack_frames.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/conf.rs
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
  tests/ui/large_stack_frames.rs
  tests/ui/large_stack_frames.stderr
Labels: S-waiting-on-review

#10911 Don't linting `as_conversions` in proc macros
  clippy_lints/src/as_conversions.rs
  clippy_lints/src/lib.rs
  tests/ui/as_conversions.rs
  tests/ui/as_conversions.stderr
Labels: S-waiting-on-review

#10935 Don't lint non-statement/faux empty `needless_if`s
  clippy_lints/src/needless_if.rs
  tests/ui/needless_if.fixed
  tests/ui/needless_if.rs
  tests/ui/needless_if.stderr
Labels: S-waiting-on-review

#10889 Add configuration values auto markdown links to `CHANGELOG.md`
  CHANGELOG.md
  clippy_lints/src/utils/internal_lints/metadata_collector.rs
  clippy_lints/src/utils/mod.rs
Labels: S-waiting-on-review

#10891 [`missing_const_for_fn`]: Ensure dropped locals are `~const Destruct`
  clippy_utils/src/lib.rs
  clippy_utils/src/qualify_min_const_fn.rs
  tests/ui/missing_const_for_fn/cant_be_const.rs
  tests/ui/missing_const_for_fn/could_be_const.rs
  tests/ui/missing_const_for_fn/could_be_const.stderr
Labels: S-waiting-on-review

#10947 Improve suggestion for [`needless_lifetimes`]
  clippy_lints/src/lifetimes.rs
  tests/ui/crashes/ice-2774.stderr
  tests/ui/crashes/needless_lifetimes_impl_trait.stderr
  tests/ui/issue_4266.stderr
  tests/ui/needless_lifetimes.stderr
Labels: S-waiting-on-review

#10945 [`no_effect`]: Suggest adding `return` if applicable
  clippy_lints/src/no_effect.rs
  tests/ui/no_effect_return.rs
  tests/ui/no_effect_return.stderr
Labels: S-waiting-on-review

#10919 [`map_unwrap_or`]: don't lint when referenced variable is moved
  clippy_lints/src/methods/option_map_unwrap_or.rs
  tests/ui/map_unwrap_or.rs
Labels: S-waiting-on-review

#10950 [`needless_doctest_main`]: ignore `main()` in `no_test` code fences
  clippy_lints/src/doc.rs
  tests/ui/doc/needless_doctest_main.rs
Labels: S-waiting-on-review

#10954 [`derivable_impls`]: don't lint if `default()` call expr unsize-coerces to trait object
  clippy_lints/src/derivable_impls.rs
  tests/ui/derivable_impls.fixed
  tests/ui/derivable_impls.rs
Labels: S-waiting-on-review

#10934 new lint [`single_range_in_vec_init`]
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/single_range_in_vec_init.rs
  tests/ui/single_element_loop.fixed
  tests/ui/single_element_loop.rs
  tests/ui/single_element_loop.stderr
  tests/ui/single_range_in_vec_init.rs
  tests/ui/single_range_in_vec_init.stderr
  tests/ui/while_let_on_iterator.fixed
  tests/ui/while_let_on_iterator.rs
  tests/ui/while_let_on_iterator.stderr
Labels: S-waiting-on-review

#10931 [`unnecessary_fold`]: suggest turbofish if necessary
  clippy_lints/src/methods/unnecessary_fold.rs
  tests/ui/unnecessary_fold.fixed
  tests/ui/unnecessary_fold.rs
  tests/ui/unnecessary_fold.stderr
Labels: S-waiting-on-review

#10840 from_over_into: Show suggestions for non-Self expanded paths
  clippy_lints/src/from_over_into.rs
  tests/ui/from_over_into.fixed
  tests/ui/from_over_into.rs
  tests/ui/from_over_into.stderr
  tests/ui/from_over_into_unfixable.rs
Labels: S-waiting-on-review

#10946 [`match_same_arms`]: don't lint if `non_exhaustive_omitted_patterns`
  clippy_lints/src/matches/match_same_arms.rs
  clippy_lints/src/matches/mod.rs
  tests/ui/match_same_arms_non_exhaustive.rs
  tests/ui/match_same_arms_non_exhaustive.stderr
Labels: S-waiting-on-review

#10835 new lint: `drain_collect`
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/methods/drain_collect.rs
  clippy_lints/src/methods/mod.rs
  tests/ui/drain_collect.fixed
  tests/ui/drain_collect.rs
  tests/ui/drain_collect.stderr
  tests/ui/iter_with_drain.fixed
  tests/ui/iter_with_drain.rs
Labels: S-waiting-on-author

#10925 add lint [`incorrect_clone_impl_on_copy_type`]
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/incorrect_impls.rs
  clippy_lints/src/lib.rs
  tests/ui/clone_on_copy_impl.rs
  tests/ui/derive.rs
  tests/ui/incorrect_clone_impl_on_copy_type.fixed
  tests/ui/incorrect_clone_impl_on_copy_type.rs
  tests/ui/incorrect_clone_impl_on_copy_type.stderr
  tests/ui/unnecessary_struct_initialization.fixed
  tests/ui/unnecessary_struct_initialization.rs
Labels: S-waiting-on-review

#10953 [`missing_panics_doc`]: pickup expect method
  clippy_dev/src/fmt.rs
  clippy_dev/src/lib.rs
  clippy_dev/src/new_lint.rs
  clippy_lints/src/doc.rs
  tests/ui/missing_panics_doc.rs
  tests/ui/missing_panics_doc.stderr
Labels: S-waiting-on-review

#10965 Make `--explain` subcommand return 1 for missing lints
  clippy_lints/src/lib.rs
  src/main.rs
Labels: S-waiting-on-review

#10942 Ignore more type aliases in `unnecessary_cast`
  clippy_lints/src/casts/unnecessary_cast.rs
  tests/ui/auxiliary/extern_fake_libc.rs
  tests/ui/unnecessary_cast.fixed
  tests/ui/unnecessary_cast.rs
  tests/ui/unnecessary_cast.stderr
Labels: S-waiting-on-review

#10876 Adapt versions.html file to cleaned up gh-pages
  util/gh-pages/versions.html
Labels: S-waiting-on-review

#10973 Fix version.py after deleting v* dirs
  util/versions.py
Labels: S-waiting-on-review

#10976 Make [`missing_panics_doc`] not lint for `todo!()`
  clippy_lints/src/doc.rs
  tests/ui/auxiliary/macro_rules.rs
  tests/ui/missing_panics_doc.rs
  tests/ui/missing_panics_doc.stderr
Labels: S-waiting-on-review

#10951 new lint [`single_call_fn`]
  CHANGELOG.md
  book/src/lint_configuration.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/single_call_fn.rs
  clippy_lints/src/utils/conf.rs
  tests/ui/single_call_fn.rs
  tests/ui/single_call_fn.stderr
Labels: S-waiting-on-review

#10980 Fix `find_format_arg_expr` when incremental compilation is enabled
  clippy_utils/src/macros.rs
  tests/ui/to_string_in_format_args_incremental.fixed
  tests/ui/to_string_in_format_args_incremental.rs
  tests/ui/to_string_in_format_args_incremental.stderr
Labels: S-waiting-on-review

#10793 [`arithmetic_side_effects`] Fix #10792
  clippy_lints/src/enum_clike.rs
  clippy_lints/src/floating_point_arithmetic.rs
  clippy_lints/src/matches/overlapping_arms.rs
  clippy_lints/src/minmax.rs
  clippy_lints/src/operators/float_cmp.rs
  clippy_lints/src/ranges.rs
  clippy_utils/src/consts.rs
  clippy_utils/src/lib.rs
  tests/ui/arithmetic_side_effects.rs
Labels: S-waiting-on-review

#10930 [`redundant_closure_call`]: handle nested closures
  clippy_lints/src/lib.rs
  clippy_lints/src/redundant_closure_call.rs
  tests/ui/redundant_closure_call_fixable.fixed
  tests/ui/redundant_closure_call_fixable.rs
  tests/ui/redundant_closure_call_fixable.stderr
Labels: S-waiting-on-review

#10992 `items_after_test_module`: Ignore in-proc-macros items
  clippy_lints/src/items_after_test_module.rs
Labels: S-waiting-on-review

#10989 Use placeref abstraction
  clippy_lints/src/redundant_clone.rs
  clippy_utils/src/qualify_min_const_fn.rs
  tests/ui/missing_const_for_fn/cant_be_const.rs
Labels: S-waiting-on-review

#10986 Allow safety comment above attributes
  CHANGELOG.md
  book/src/lint_configuration.md
  clippy_lints/src/lib.rs
  clippy_lints/src/undocumented_unsafe_blocks.rs
  clippy_lints/src/utils/conf.rs
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
  tests/ui-toml/undocumented_unsafe_blocks/clippy.toml
  tests/ui-toml/undocumented_unsafe_blocks/undocumented_unsafe_blocks.rs
  tests/ui-toml/undocumented_unsafe_blocks/undocumented_unsafe_blocks.stderr
Labels: S-waiting-on-review

#10999 Add WebAssembly to allowed idents
  book/src/lint_configuration.md
  clippy_lints/src/utils/conf.rs
Labels: S-waiting-on-review

#11000 add WebAssembly to test
  tests/ui/doc/doc-fixable.fixed
  tests/ui/doc/doc-fixable.rs
  tests/ui/doc/doc-fixable.stderr
Labels: S-waiting-on-review

#10948 [`borrow_as_ptr`]: Ignore temporaries
  clippy_lints/src/casts/borrow_as_ptr.rs
  tests/ui/borrow_as_ptr.fixed
  tests/ui/borrow_as_ptr.rs
  tests/ui/borrow_as_ptr.stderr
Labels: S-waiting-on-review

#10993 Don't lint [`iter_nth_zero`] in `next`
  clippy_lints/src/methods/iter_nth.rs
  clippy_lints/src/methods/iter_nth_zero.rs
  tests/ui/iter_nth.stderr
  tests/ui/iter_nth_zero.fixed
  tests/ui/iter_nth_zero.rs
Labels: S-waiting-on-review

#10979 [`get_unwrap`]: include a borrow in the suggestion if argument is not an integer literal
  clippy_lints/src/methods/get_unwrap.rs
  tests/ui/get_unwrap.fixed
  tests/ui/get_unwrap.rs
  tests/ui/get_unwrap.stderr
Labels: S-waiting-on-review

#10994 [`type_repetition_in_bounds`]: respect MSRV for combining bounds
  book/src/lint_configuration.md
  clippy_lints/src/lib.rs
  clippy_lints/src/trait_bounds.rs
  clippy_lints/src/utils/conf.rs
  clippy_utils/src/msrvs.rs
  tests/ui/type_repetition_in_bounds.rs
  tests/ui/type_repetition_in_bounds.stderr
Labels: S-waiting-on-review

#11019 [`ptr_arg`]: Don't lint when return type uses `Cow`'s lifetime
  clippy_lints/src/ptr.rs
  tests/ui/ptr_arg.rs
  tests/ui/ptr_arg.stderr
Labels: S-waiting-on-review

#11021 [`format_push_string`]: look through `match` and `if` expressions
  clippy_lints/src/format_push_string.rs
  tests/ui/format_push_string.rs
  tests/ui/format_push_string.stderr
Labels: S-waiting-on-review

#11022 Avoid linting `extra_unused_type_parameters` on procedural macros
  clippy_lints/src/extra_unused_type_parameters.rs
  tests/ui/extra_unused_type_parameters.fixed
  tests/ui/extra_unused_type_parameters.rs
  tests/ui/extra_unused_type_parameters.stderr
Labels: S-waiting-on-review

#10996 Lint `mem_forget` if any fields are `Drop`
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/drop_forget_ref.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/mem_forget.rs
  tests/ui/mem_forget.rs
  tests/ui/mem_forget.stderr
Labels: S-waiting-on-review

#11005 Check if `if` conditions always evaluate to true in `never_loop`
  clippy_lints/src/loops/never_loop.rs
  clippy_utils/src/consts.rs
  tests/ui/large_futures.rs
  tests/ui/large_futures.stderr
  tests/ui/never_loop.rs
  tests/ui/never_loop.stderr
Labels: S-waiting-on-review

#11027 Update changelog's data ranges
  CHANGELOG.md
  book/src/development/infrastructure/changelog_update.md
Labels: S-waiting-on-review

#11009 Don't lint code from external macros for 8 lints
  clippy_lints/src/misc_early/mod.rs
  tests/ui/patterns.fixed
  tests/ui/patterns.rs
  tests/ui/patterns.stderr
  tests/ui/unneeded_field_pattern.rs
  tests/ui/unneeded_field_pattern.stderr
  tests/ui/unneeded_wildcard_pattern.fixed
  tests/ui/unneeded_wildcard_pattern.rs
  tests/ui/unneeded_wildcard_pattern.stderr
Labels: S-waiting-on-review

#10884 New lint [`needless_raw_string_hashes`]
  CHANGELOG.md
  book/src/lint_configuration.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/raw_strings.rs
  clippy_lints/src/utils/conf.rs
  clippy_lints/src/utils/internal_lints/almost_standard_lint_formulation.rs
  src/main.rs
  tests/compile-test.rs
  tests/lint_message_convention.rs
  tests/ui-toml/toml_disallowed_methods/conf_disallowed_methods.rs
  tests/ui-toml/toml_disallowed_methods/conf_disallowed_methods.stderr
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
  tests/ui/format.fixed
  tests/ui/format.rs
  tests/ui/format.stderr
  tests/ui/needless_raw_string.fixed
  tests/ui/needless_raw_string.rs
  tests/ui/needless_raw_string.stderr
  tests/ui/needless_raw_string_hashes.fixed
  tests/ui/needless_raw_string_hashes.rs
  tests/ui/needless_raw_string_hashes.stderr
  tests/ui/regex.rs
  tests/ui/regex.stderr
  tests/ui/single_char_add_str.fixed
  tests/ui/single_char_add_str.rs
  tests/ui/single_char_add_str.stderr
  tests/ui/single_char_pattern.fixed
  tests/ui/single_char_pattern.rs
  tests/ui/string_lit_as_bytes.fixed
  tests/ui/string_lit_as_bytes.rs
  tests/ui/write_literal_2.rs
  tests/ui/write_literal_2.stderr
Labels: S-waiting-on-author

#11041 Fix compile-test under cargo nextest
  tests/compile-test.rs
Labels: S-waiting-on-review

#11039 Add `BLESS` for compile-test and some cleanup
  book/src/development/adding_lints.md
  clippy_test_deps/Cargo.toml
  tests/compile-test.rs
Labels: S-waiting-on-review

#10968 new lint: `manual_range_patterns`
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_range_patterns.rs
  tests/ui/manual_range_patterns.fixed
  tests/ui/manual_range_patterns.rs
  tests/ui/manual_range_patterns.stderr
  tests/ui/unnested_or_patterns.fixed
  tests/ui/unnested_or_patterns.rs
  tests/ui/unnested_or_patterns.stderr
  tests/ui/unnested_or_patterns2.fixed
  tests/ui/unnested_or_patterns2.rs
  tests/ui/unnested_or_patterns2.stderr
Labels: S-waiting-on-review

#11043 Use substring matching for TESTNAME
  tests/compile-test.rs
Labels: S-waiting-on-review

#10967 New lints ['`needless_pub_self`], [`pub_with_shorthand`] and [`pub_without_shorthand`]
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/visibility.rs
  tests/ui/manual_async_fn.fixed
  tests/ui/manual_async_fn.rs
  tests/ui/needless_pub_self.fixed
  tests/ui/needless_pub_self.rs
  tests/ui/needless_pub_self.stderr
  tests/ui/pub_with_shorthand.fixed
  tests/ui/pub_with_shorthand.rs
  tests/ui/pub_with_shorthand.stderr
  tests/ui/pub_without_shorthand.fixed
  tests/ui/pub_without_shorthand.rs
  tests/ui/pub_without_shorthand.stderr
Labels: S-waiting-on-review

#11042 [`unused_async`]: don't lint if function is part of a trait
  clippy_lints/src/unused_async.rs
  clippy_utils/src/lib.rs
  tests/ui/unused_async.rs
  tests/ui/unused_async.stderr
Labels: S-waiting-on-review

#11035 [`option_if_let_else`]: suggest `.as_ref()` if scrutinee is of type `&Option<_>`
  clippy_lints/src/option_if_let_else.rs
  tests/ui/option_if_let_else.fixed
  tests/ui/option_if_let_else.rs
  tests/ui/option_if_let_else.stderr
Labels: S-waiting-on-review

#11001 [`question_mark`]: don't lint inside of `try` block
  clippy_lints/src/lib.rs
  clippy_lints/src/question_mark.rs
  tests/ui/question_mark.fixed
  tests/ui/question_mark.rs
  tests/ui/question_mark.stderr
Labels: S-waiting-on-review

#11013 New lint [`redundant_at_rest_pattern`]
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/methods/needless_collect.rs
  clippy_lints/src/methods/str_splitn.rs
  clippy_lints/src/misc_early/mod.rs
  clippy_lints/src/misc_early/redundant_at_rest_pattern.rs
  clippy_utils/src/sugg.rs
  tests/ui/manual_let_else_match.rs
  tests/ui/manual_let_else_match.stderr
  tests/ui/match_on_vec_items.rs
  tests/ui/redundant_at_rest_pattern.fixed
  tests/ui/redundant_at_rest_pattern.rs
  tests/ui/redundant_at_rest_pattern.stderr
Labels: S-waiting-on-review

#10774 [significant_drop_tightening] Fix #10413
  clippy_lints/src/significant_drop_tightening.rs
  tests/ui/significant_drop_tightening.fixed
  tests/ui/significant_drop_tightening.rs
  tests/ui/significant_drop_tightening.stderr
Labels: S-waiting-on-review

#11051 Make `eq_op` suggest `.is_nan()`
  clippy_lints/src/operators/eq_op.rs
  tests/ui/eq_op.rs
  tests/ui/eq_op.stderr
Labels: S-waiting-on-review
