Repository rust-lang/rust-clippy, pull requests merged in 2023-12, with the labels that each got.

#11898 Allow `allow`ing `upper_case_acronyms` on enum variants
  clippy_lints/src/upper_case_acronyms.rs
  tests/ui/upper_case_acronyms.fixed
  tests/ui/upper_case_acronyms.rs
  tests/ui/upper_case_acronyms.stderr
Labels: S-waiting-on-review

#11597 new lint: `repeat_vec_with_capacity`
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/repeat_vec_with_capacity.rs
  tests/ui/repeat_vec_with_capacity.fixed
  tests/ui/repeat_vec_with_capacity.rs
  tests/ui/repeat_vec_with_capacity.stderr
Labels: S-waiting-on-review

#11837 [`missing_asserts_for_indexing`]: accept length equality checks
  clippy_lints/src/missing_asserts_for_indexing.rs
  tests/ui/missing_asserts_for_indexing.fixed
  tests/ui/missing_asserts_for_indexing.rs
  tests/ui/missing_asserts_for_indexing.stderr
Labels: S-waiting-on-review

#11899 Do not check twice whether `qpath` is a `QPath::TypeRelative` variant
  clippy_lints/src/manual_string_new.rs
Labels: S-waiting-on-review

#11929 Rustup
  .github/workflows/clippy_bors.yml
  rust-toolchain
  src/driver.rs
  tests/integration.rs
  tests/ui-cargo/module_style/fail_mod_remap/Cargo.stderr
  tests/ui-cargo/module_style/fail_no_mod/Cargo.stderr
  tests/ui-cargo/multiple_crate_versions/fail/Cargo.stderr
  tests/ui-cargo/wildcard_dependencies/fail/Cargo.stderr
  tests/ui/needless_raw_string.fixed
  tests/ui/needless_raw_string.rs
  tests/ui/needless_raw_string.stderr
  tests/ui/needless_raw_string_hashes.fixed
  tests/ui/needless_raw_string_hashes.rs
  tests/ui/needless_raw_string_hashes.stderr
Labels: S-waiting-on-review

#11904 Update regex-syntax to support new word boundry assertions
  clippy_lints/Cargo.toml
  tests/ui/regex.rs
Labels: S-waiting-on-review

#11920 docs(explicit_write): add missing backtick to complete code snippet
  clippy_lints/src/explicit_write.rs
Labels: S-waiting-on-bors

#11900 needless_borrows_for_generic_args: Handle when field operand impl Drop
  clippy_lints/src/needless_borrows_for_generic_args.rs
  tests/ui/needless_borrows_for_generic_args.fixed
  tests/ui/needless_borrows_for_generic_args.rs
Labels: S-waiting-on-review

#11913 fix(ptr_as_ptr): handle `std::ptr::null{_mut}`
  clippy_lints/src/casts/ptr_as_ptr.rs
  tests/ui/ptr_as_ptr.fixed
  tests/ui/ptr_as_ptr.rs
  tests/ui/ptr_as_ptr.stderr
Labels: S-waiting-on-review

#11944 Check $CARGO before $PATH
  clippy_dev/src/lint.rs
  clippy_dev/src/serve.rs
  clippy_lints/src/utils/internal_lints/metadata_collector.rs
  lintcheck/src/main.rs
  src/main.rs
Labels: S-waiting-on-review

#11949 Add `blyxyas` to `users_on_vacation`
  triagebot.toml
Labels: S-waiting-on-review

#11538 Fix `is_from_proc_macro` patterns
  clippy_lints/src/as_conversions.rs
  clippy_lints/src/borrow_deref_ref.rs
  clippy_lints/src/manual_float_methods.rs
  clippy_lints/src/methods/unnecessary_lazy_eval.rs
  clippy_lints/src/needless_if.rs
  clippy_lints/src/operators/arithmetic_side_effects.rs
  clippy_lints/src/single_call_fn.rs
  clippy_utils/src/check_proc_macro.rs
  tests/ui/doc_unsafe.rs
  tests/ui/needless_pass_by_ref_mut.rs
  tests/ui/needless_pass_by_ref_mut.stderr
  tests/ui/unnecessary_unsafety_doc.rs
Labels: S-waiting-on-review, beta-nominated

#11878 uninhabited_reference: new lint
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/uninhabited_references.rs
  tests/ui/infallible_destructuring_match.fixed
  tests/ui/infallible_destructuring_match.rs
  tests/ui/uninhabited_references.rs
  tests/ui/uninhabited_references.stderr
Labels: S-waiting-on-review

#11902 Add `ineffective_open_options` lint
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/ineffective_open_options.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/methods/mod.rs
  tests/ui/ineffective_open_options.fixed
  tests/ui/ineffective_open_options.rs
  tests/ui/ineffective_open_options.stderr
Labels: S-waiting-on-review

#11829 new lint to detect infinite loop
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/loops/infinite_loop.rs
  clippy_lints/src/loops/mod.rs
  tests/ui/infinite_loops.rs
  tests/ui/infinite_loops.stderr
Labels: S-waiting-on-review

#11895 Useless vec false positive
  clippy_lints/src/lib.rs
  clippy_lints/src/vec.rs
  tests/ui/vec.fixed
  tests/ui/vec.rs
  tests/ui/vec.stderr
Labels: S-waiting-on-review

#11956 [`doc_markdown`] Recognize words followed by empty parentheses `()` for quoting
  clippy_lints/src/doc/markdown.rs
  clippy_lints/src/missing_asserts_for_indexing.rs
  tests/ui/doc/doc-fixable.fixed
  tests/ui/doc/doc-fixable.rs
  tests/ui/doc/doc-fixable.stderr
Labels: S-waiting-on-review

#11953 Fix binder handling in `unnecessary_to_owned`
  clippy_lints/src/methods/unnecessary_to_owned.rs
  tests/ui/unnecessary_to_owned.fixed
  tests/ui/unnecessary_to_owned.rs
  tests/ui/unnecessary_to_owned.stderr
Labels: S-waiting-on-review, beta-nominated

#11974 [`redundant_pattern_matching`]: lint `if let true`, `while let true`, `matches!(.., true)`
  clippy_lints/src/format_push_string.rs
  clippy_lints/src/loops/manual_flatten.rs
  clippy_lints/src/loops/while_let_on_iterator.rs
  clippy_lints/src/manual_let_else.rs
  clippy_lints/src/matches/collapsible_match.rs
  clippy_lints/src/matches/mod.rs
  clippy_lints/src/matches/redundant_pattern_match.rs
  clippy_lints/src/methods/filter_map.rs
  clippy_lints/src/option_if_let_else.rs
  clippy_lints/src/question_mark.rs
  clippy_lints/src/utils/author.rs
  clippy_utils/src/higher.rs
  tests/ui/author/loop.rs
  tests/ui/branches_sharing_code/shared_at_bottom.rs
  tests/ui/branches_sharing_code/shared_at_bottom.stderr
  tests/ui/collapsible_if.fixed
  tests/ui/collapsible_if.rs
  tests/ui/collapsible_if.stderr
  tests/ui/if_then_some_else_none.rs
  tests/ui/if_then_some_else_none.stderr
  tests/ui/needless_if.fixed
  tests/ui/needless_if.rs
  tests/ui/needless_if.stderr
  tests/ui/nonminimal_bool.rs
  tests/ui/nonminimal_bool.stderr
  tests/ui/redundant_pattern_matching_if_let_true.fixed
  tests/ui/redundant_pattern_matching_if_let_true.rs
  tests/ui/redundant_pattern_matching_if_let_true.stderr
Labels: S-waiting-on-review

#11938 Add new `unconditional_recursion` lint
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/unconditional_recursion.rs
  tests/ui/unconditional_recursion.rs
  tests/ui/unconditional_recursion.stderr
Labels: S-waiting-on-review

#11977 don't visit nested bodies in `is_const_evaluatable`
  clippy_utils/src/visitors.rs
  tests/ui/crashes/ice-11939.rs
Labels: S-waiting-on-review

#11869 New Lint: `result_filter_map` / Mirror of `option_filter_map`
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/methods/filter_map.rs
  clippy_lints/src/methods/mod.rs
  tests/ui/option_filter_map.fixed
  tests/ui/option_filter_map.rs
  tests/ui/option_filter_map.stderr
  tests/ui/result_filter_map.fixed
  tests/ui/result_filter_map.rs
  tests/ui/result_filter_map.stderr
Labels: S-waiting-on-review

#11966 Do not lint `assertions_on_constants` for `const _: () = assert!(expr)`
  clippy_lints/src/assertions_on_constants.rs
  tests/ui/assertions_on_constants.rs
  tests/ui/assertions_on_constants.stderr
Labels: S-waiting-on-review

#11947 fix: broken GitHub corner
  util/gh-pages/index.html
Labels: S-waiting-on-review

#11991 stop [`bool_comparison`]'s suggestion from consuming parentheses
  clippy_lints/src/needless_bool.rs
  tests/ui/bool_comparison.fixed
  tests/ui/bool_comparison.rs
  tests/ui/bool_comparison.stderr
Labels: S-waiting-on-review

#11998 Check whether out of bound when access a known length array with a constant index
  clippy_lints/src/indexing_slicing.rs
  tests/ui-toml/suppress_lint_in_const/test.rs
  tests/ui-toml/suppress_lint_in_const/test.stderr
  tests/ui/crashes/ice-5497.rs
  tests/ui/crashes/ice-5497.stderr
  tests/ui/get_unwrap.fixed
  tests/ui/get_unwrap.rs
  tests/ui/get_unwrap.stderr
  tests/ui/indexing_slicing_index.rs
  tests/ui/indexing_slicing_index.stderr
Labels: S-waiting-on-review

#12000 Fixing some other typos
  clippy_lints/src/default_constructed_unit_structs.rs
  clippy_lints/src/implied_bounds_in_impls.rs
  clippy_lints/src/ineffective_open_options.rs
Labels: S-waiting-on-review

#11871 Extend `UNNECESSARY_TO_OWNED` to handle `split`
  clippy_lints/src/methods/unnecessary_to_owned.rs
  tests/ui/unnecessary_to_owned_on_split.fixed
  tests/ui/unnecessary_to_owned_on_split.rs
  tests/ui/unnecessary_to_owned_on_split.stderr
Labels: S-waiting-on-review

#11999 fix typo in infinite loop lint
  clippy_lints/src/loops/infinite_loop.rs
  tests/ui/infinite_loops.stderr
Labels: S-waiting-on-review

#11994 [`question_mark`]: also trigger on `return` statements
  clippy_lints/src/matches/manual_utils.rs
  clippy_lints/src/matches/redundant_pattern_match.rs
  clippy_lints/src/question_mark.rs
  clippy_lints/src/undocumented_unsafe_blocks.rs
  tests/ui/manual_let_else_question_mark.fixed
  tests/ui/manual_let_else_question_mark.rs
  tests/ui/manual_let_else_question_mark.stderr
Labels: S-waiting-on-review

#11997 Move `uninhabited_references` to `nursery`
  clippy_lints/src/uninhabited_references.rs
Labels: S-waiting-on-review, beta-nominated

#12011 Remove me from `users_on_vacation`
  triagebot.toml
Labels: S-waiting-on-review

#11967 Do not consider `async { (impl IntoFuture).await }` as redundant
  clippy_lints/src/redundant_async_block.rs
  tests/ui/redundant_async_block.fixed
  tests/ui/redundant_async_block.rs
Labels: S-waiting-on-review

#12004 New lints `iter_filter_is_some` and `iter_filter_is_ok`
  CHANGELOG.md
  clippy_config/src/msrvs.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/methods/filter_map.rs
  clippy_lints/src/methods/iter_filter.rs
  clippy_lints/src/methods/mod.rs
  tests/ui/iter_filter_is_ok.fixed
  tests/ui/iter_filter_is_ok.rs
  tests/ui/iter_filter_is_ok.stderr
  tests/ui/iter_filter_is_some.fixed
  tests/ui/iter_filter_is_some.rs
  tests/ui/iter_filter_is_some.stderr
Labels: S-waiting-on-review

#12019 Changelog for Rust 1.75 :christmas_tree:
  CHANGELOG.md
  clippy_lints/src/iter_without_into_iter.rs
  clippy_lints/src/manual_hash_one.rs
Labels: S-waiting-on-review

#12022 Fix typo in changelog for 1.75
  CHANGELOG.md
Labels: S-waiting-on-review

#12018 [doc_markdown]: Add "WebGL2", "WebGPU" to default `doc_valid_idents`
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  tests/ui/doc/doc-fixable.fixed
  tests/ui/doc/doc-fixable.rs
Labels: S-waiting-on-review

#11981 new lint: `eager_transmute`
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/transmute/eager_transmute.rs
  clippy_lints/src/transmute/mod.rs
  tests/ui/eager_transmute.fixed
  tests/ui/eager_transmute.rs
  tests/ui/eager_transmute.stderr
Labels: S-waiting-on-review

#12029 6459: Check for redundant `matches!` with `Ready`, `Pending`, `V4`, `V6`
  clippy_lints/src/matches/redundant_pattern_match.rs
  tests/ui/redundant_pattern_matching_ipaddr.fixed
  tests/ui/redundant_pattern_matching_ipaddr.rs
  tests/ui/redundant_pattern_matching_ipaddr.stderr
  tests/ui/redundant_pattern_matching_poll.fixed
  tests/ui/redundant_pattern_matching_poll.rs
  tests/ui/redundant_pattern_matching_poll.stderr
Labels: S-waiting-on-review

#12038 Rustup
  Cargo.toml
  clippy_config/Cargo.toml
  clippy_config/src/conf.rs
  clippy_config/src/msrvs.rs
  clippy_lints/Cargo.toml
  clippy_lints/src/async_yields_async.rs
  clippy_lints/src/await_holding_invalid.rs
  clippy_lints/src/doc/needless_doctest_main.rs
  clippy_lints/src/item_name_repetitions.rs
  clippy_lints/src/len_zero.rs
  clippy_lints/src/manual_async_fn.rs
  clippy_lints/src/manual_non_exhaustive.rs
  clippy_lints/src/methods/iter_kv_map.rs
  clippy_lints/src/missing_const_for_fn.rs
  clippy_lints/src/needless_continue.rs
  clippy_lints/src/needless_question_mark.rs
  clippy_lints/src/redundant_async_block.rs
  clippy_lints/src/redundant_closure_call.rs
  clippy_lints/src/redundant_else.rs
  clippy_lints/src/suspicious_operation_groupings.rs
  clippy_lints/src/unnested_or_patterns.rs
  clippy_lints/src/unused_async.rs
  clippy_lints/src/utils/author.rs
  clippy_utils/Cargo.toml
  clippy_utils/src/ast_utils.rs
  clippy_utils/src/attrs.rs
  clippy_utils/src/check_proc_macro.rs
  clippy_utils/src/diagnostics.rs
  clippy_utils/src/sugg.rs
  declare_clippy_lint/Cargo.toml
  rust-toolchain
  src/driver.rs
  tests/ui-internal/disallow_struct_span_lint.rs
  tests/ui-internal/disallow_struct_span_lint.stderr
  tests/ui/author/blocks.stdout
  tests/ui/author/macro_in_closure.stdout
  tests/ui/author/macro_in_loop.stdout
  tests/ui/needless_question_mark.fixed
  tests/ui/needless_question_mark.rs
  tests/ui/needless_question_mark.stderr
  triagebot.toml
Labels: S-waiting-on-review

#12041 Remove mitigations for incorrect node args
  clippy_lints/src/methods/unnecessary_to_owned.rs
Labels: S-waiting-on-review

#10283 feature: add new lint `pub_underscore_fields`
  CHANGELOG.md
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  clippy_config/src/types.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/pub_underscore_fields.rs
  tests/ui-toml/pub_underscore_fields/all_pub_fields/clippy.toml
  tests/ui-toml/pub_underscore_fields/exported/clippy.toml
  tests/ui-toml/pub_underscore_fields/pub_underscore_fields.all_pub_fields.stderr
  tests/ui-toml/pub_underscore_fields/pub_underscore_fields.exported.stderr
  tests/ui-toml/pub_underscore_fields/pub_underscore_fields.rs
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
Labels: S-waiting-on-review

#12054 add external macro checks to `iter_without_into_iter` and `into_iter_without_iter`
  clippy_lints/src/iter_without_into_iter.rs
  tests/ui/into_iter_without_iter.rs
  tests/ui/into_iter_without_iter.stderr
  tests/ui/iter_without_into_iter.rs
  tests/ui/iter_without_into_iter.stderr
Labels: S-waiting-on-review

#12008 make [`mutex_atomic`] more type aware
  clippy_lints/src/mutex_atomic.rs
  tests/ui/mutex_atomic.rs
  tests/ui/mutex_atomic.stderr
Labels: S-waiting-on-review

#11865 feat: add `manual_is_variant_and` lint
  CHANGELOG.md
  clippy_config/src/msrvs.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lines_filter_map_ok.rs
  clippy_lints/src/methods/manual_is_variant_and.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/option_map_unwrap_or.rs
  clippy_lints/src/methods/path_ends_with_ext.rs
  tests/ui/manual_is_variant_and.fixed
  tests/ui/manual_is_variant_and.rs
  tests/ui/manual_is_variant_and.stderr
Labels: S-waiting-on-review

#11957 don't lint [`default_numeric_fallback`] on return and local assigned macro calls with type stated
  clippy_lints/src/default_numeric_fallback.rs
  tests/ui/default_numeric_fallback_f64.fixed
  tests/ui/default_numeric_fallback_f64.rs
  tests/ui/default_numeric_fallback_f64.stderr
  tests/ui/default_numeric_fallback_i32.fixed
  tests/ui/default_numeric_fallback_i32.rs
  tests/ui/default_numeric_fallback_i32.stderr
Labels: S-waiting-on-review

#12047 New Lint: empty_enum_variants_with_brackets
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/empty_with_brackets.rs
  clippy_lints/src/lib.rs
  tests/ui/empty_enum_variants_with_brackets.fixed
  tests/ui/empty_enum_variants_with_brackets.rs
  tests/ui/empty_enum_variants_with_brackets.stderr
Labels: S-waiting-on-review

#11980 Extend UNCONDITIONAL_RECURSION to check for ToString implementations
  clippy_lints/src/unconditional_recursion.rs
  tests/ui/unconditional_recursion.rs
  tests/ui/unconditional_recursion.stderr
Labels: S-waiting-on-author

#12053 Fix typo in new_lint.rs
  clippy_dev/src/new_lint.rs
Labels: S-waiting-on-review

#11987 Issue 8733: Suggest `str.lines` when splitting at hard-coded newlines
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/str_split.rs
  tests/ui/str_split.fixed
  tests/ui/str_split.rs
  tests/ui/str_split.stderr
Labels: S-waiting-on-review

#12065 Add `.front()` to `get_first` lint description
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-review
