Repository rust-lang/rust-clippy, pull requests merged in 2023-01, with the labels that each got.

#10110 Fix FN in `needless_return`
  clippy_lints/src/returns.rs
  tests/ui/needless_return.fixed
  tests/ui/needless_return.rs
  tests/ui/needless_return.stderr
Labels: S-waiting-on-review

#10146 Correct Gankra's name in the linkedlist lint
  clippy_lints/src/types/mod.rs
Labels: S-waiting-on-review

#10139 chore: fix identation of `if_chain` in `filter_map`
  clippy_lints/src/methods/filter_map.rs
Labels: S-waiting-on-review

#10138 Fix typo in `unused_self` diagnostic message
  clippy_lints/src/unused_self.rs
  tests/ui/unused_self.stderr
Labels: S-waiting-on-review

#10143 don't lint field_reassign when field in closure
  clippy_lints/src/copies.rs
  clippy_lints/src/default.rs
  clippy_lints/src/loops/needless_range_loop.rs
  clippy_utils/src/lib.rs
  tests/ui/field_reassign_with_default.rs
Labels: E-help-wanted, S-waiting-on-review

#10141 fix empty_structs_with_brackets suggestion errors
  clippy_lints/src/empty_structs_with_brackets.rs
Labels: S-waiting-on-review

#10135 Fix typo in installation instructions
  book/src/installation.md
Labels: S-waiting-on-review

#10140 chore: add simple comment for `get_enclosing_block`
  clippy_utils/src/lib.rs
Labels: S-waiting-on-review

#10159 Make the iter_kv_map lint handle ref/mut annotations.
  clippy_lints/src/methods/iter_kv_map.rs
  tests/ui/iter_kv_map.fixed
  tests/ui/iter_kv_map.rs
  tests/ui/iter_kv_map.stderr
Labels: S-waiting-on-review

#10161 Expand derivable-impls to cover enums with a default unit variant.
  clippy_lints/src/derivable_impls.rs
  tests/ui/derivable_impls.fixed
  tests/ui/derivable_impls.rs
  tests/ui/derivable_impls.stderr
Labels: S-waiting-on-review

#10142 [`drop_ref`]: don't lint idiomatic in match arm
  clippy_lints/src/drop_forget_ref.rs
  tests/ui/drop_ref.rs
  tests/ui/drop_ref.stderr
Labels: S-waiting-on-review

#10137 reword dbg_macro labels
  clippy_lints/src/dbg_macro.rs
  tests/ui-toml/dbg_macro/dbg_macro.stderr
  tests/ui/dbg_macro.stderr
Labels: S-waiting-on-review

#10160 trim paths in `default_trait_access`/`clone_on_copy` suggestions
  clippy_lints/src/default.rs
  clippy_lints/src/methods/clone_on_copy.rs
  tests/ui/clone_on_copy.stderr
  tests/ui/default_trait_access.fixed
  tests/ui/default_trait_access.stderr
  tests/ui/unnecessary_clone.stderr
Labels: S-waiting-on-review

#10153 trim paths in `box_default`
  clippy_lints/src/box_default.rs
  tests/ui/box_default.fixed
  tests/ui/box_default.stderr
Labels: S-waiting-on-review

#10112 [arithmetic-side-effects] Consider negative numbers and add more tests
  clippy_lints/src/operators/arithmetic_side_effects.rs
  clippy_utils/src/lib.rs
  tests/ui-toml/arithmetic_side_effects_allowed/arithmetic_side_effects_allowed.rs
  tests/ui/arithmetic_side_effects.rs
  tests/ui/arithmetic_side_effects.stderr
Labels: S-waiting-on-review

#10168 [#10167] Clarify that the lint only works if x eq. y in a `for` loop.
  clippy_lints/src/ranges.rs
Labels: S-waiting-on-review

#10164 Restrict suggestion of deriving Default for enums to MSRV 1.62.
  clippy_lints/src/derivable_impls.rs
  clippy_lints/src/lib.rs
  clippy_utils/src/msrvs.rs
Labels: S-waiting-on-review

#10162 Fix FP of single-element-loop
  clippy_lints/src/loops/single_element_loop.rs
  clippy_utils/src/visitors.rs
  tests/ui/single_element_loop.fixed
  tests/ui/single_element_loop.rs
  tests/ui/single_element_loop.stderr
Labels: S-waiting-on-review

#10174 hotfix: remove `ITER_COUNT` since it is not called
  clippy_utils/src/paths.rs
Labels: S-waiting-on-review

#10181 add a test against #10089
  tests/ui/box_default.fixed
  tests/ui/box_default.rs
  tests/ui/box_default.stderr
Labels: S-waiting-on-review

#10170 [arithmetic_side_effects] Add more tests related to custom types
  tests/ui/arithmetic_side_effects.rs
  tests/ui/arithmetic_side_effects.stderr
Labels: S-waiting-on-review

#10166 unused_self: Don't trigger if the method body contains todo!()
  clippy_lints/src/unused_self.rs
  tests/ui/unused_self.rs
Labels: S-waiting-on-review

#10189 expl_impl_clone_on_copy: ignore packed structs with type/const params
  clippy_lints/src/derive.rs
  tests/ui/derive.rs
Labels: S-waiting-on-review

#10179 trim paths in `suspicious_to_owned`
  clippy_lints/src/methods/suspicious_to_owned.rs
  tests/ui/suspicious_to_owned.stderr
Labels: S-waiting-on-review

#10149 Don't pass `--sysroot` twice if SYSROOT is set
  .github/driver.sh
  src/driver.rs
  tests/integration.rs
Labels: S-waiting-on-review

#10191 Rustup
  clippy_dev/src/lib.rs
  clippy_lints/src/casts/cast_slice_different_sizes.rs
  clippy_lints/src/dereference.rs
  clippy_lints/src/escape.rs
  clippy_lints/src/index_refutable_slice.rs
  clippy_lints/src/loops/same_item_push.rs
  clippy_lints/src/manual_async_fn.rs
  clippy_lints/src/manual_rem_euclid.rs
  clippy_lints/src/matches/match_single_binding.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/mixed_read_write_in_expression.rs
  clippy_lints/src/mut_mut.rs
  clippy_lints/src/needless_arbitrary_self_type.rs
  clippy_lints/src/needless_pass_by_value.rs
  clippy_lints/src/non_copy_const.rs
  clippy_lints/src/pass_by_ref_or_value.rs
  clippy_lints/src/ptr.rs
  clippy_lints/src/redundant_static_lifetimes.rs
  clippy_lints/src/ref_option_ref.rs
  clippy_lints/src/transmute/transmute_ptr_to_ref.rs
  clippy_lints/src/types/mod.rs
  clippy_lints/src/types/type_complexity.rs
  clippy_lints/src/types/utils.rs
  clippy_lints/src/unit_types/unit_arg.rs
  clippy_lints/src/unnecessary_wraps.rs
  clippy_lints/src/utils/internal_lints/lint_without_lint_pass.rs
  clippy_lints/src/utils/internal_lints/metadata_collector.rs
  clippy_lints/src/utils/internal_lints/unnecessary_def_path.rs
  clippy_utils/src/ast_utils.rs
  clippy_utils/src/hir_utils.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/sugg.rs
  clippy_utils/src/ty.rs
  rust-toolchain
  tests/ui/async_yields_async.stderr
  tests/ui/crashes/ice-6254.rs
  tests/ui/crashes/ice-6255.rs
  tests/ui/crashes/ice-6256.rs
  tests/ui/result_map_unit_fn_unfixable.stderr
Labels: S-waiting-on-review

#10192 Partially revert #9701
  clippy_lints/src/dereference.rs
  clippy_lints/src/redundant_clone.rs
  clippy_utils/src/mir/possible_borrower.rs
  tests/ui/needless_borrow.fixed
  tests/ui/needless_borrow.rs
  tests/ui/needless_borrow.stderr
  tests/ui/redundant_clone.fixed
  tests/ui/redundant_clone.rs
  tests/ui/redundant_clone.stderr
Labels: S-waiting-on-review

#10194 Move `unchecked_duration_subtraction` to pedantic
  clippy_lints/src/instant_subtraction.rs
Labels: S-waiting-on-review, beta-nominated

#10201 Add missing arguments to `new_lint` example of `cargo` lints
  book/src/development/adding_lints.md
Labels: S-waiting-on-review

#10038 `cast_possible_truncation` Suggest TryFrom when truncation possible
  clippy_lints/src/casts/cast_possible_truncation.rs
  clippy_lints/src/casts/mod.rs
  tests/ui/cast.rs
  tests/ui/cast.stderr
  tests/ui/cast_size.stderr
Labels: S-waiting-on-review

#10199 Document lint configuration values in Clippy's book
  .github/workflows/clippy_bors.yml
  README.md
  book/src/SUMMARY.md
  book/src/configuration.md
  book/src/development/adding_lints.md
  book/src/lint_configuration.md
  clippy_lints/src/utils/conf.rs
  clippy_lints/src/utils/internal_lints/metadata_collector.rs
Labels: S-waiting-on-review

#10187 [needless_return]: Remove all semicolons on suggestion
  clippy_lints/src/returns.rs
  clippy_utils/src/lib.rs
  tests/ui/needless_return.fixed
  tests/ui/needless_return.rs
  tests/ui/needless_return.stderr
Labels: S-waiting-on-review

#10213 Improve the changelog update documentation
  book/src/development/infrastructure/changelog_update.md
Labels: S-waiting-on-review

#10206 Add `multiple_unsafe_ops_per_block` lint
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/multiple_unsafe_ops_per_block.rs
  tests/ui/multiple_unsafe_ops_per_block.rs
  tests/ui/multiple_unsafe_ops_per_block.stderr
Labels: A-lint, S-waiting-on-review, L-restriction

#10214 Changelog for Rust 1.67 :lady_beetle:
  CHANGELOG.md
  clippy_lints/src/doc.rs
  clippy_lints/src/from_raw_with_void_ptr.rs
  clippy_lints/src/instant_subtraction.rs
  clippy_lints/src/let_underscore.rs
  clippy_lints/src/manual_is_ascii_check.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/suspicious_xor_used_as_pow.rs
Labels: S-waiting-on-review

#10216 Fix spelling inconsistence of `mdBook`
  book/src/development/infrastructure/book.md
Labels: S-waiting-on-review

#10221 Tiny typo: `eg.` -> `e.g.`
  src/main.rs
Labels: S-waiting-on-review

#10106 Fix FP in `unnecessary_safety_comment`
  clippy_lints/src/undocumented_unsafe_blocks.rs
  tests/ui/unnecessary_safety_comment.rs
Labels: S-waiting-on-review

#10226 Improve span for module_name_repetitions
  clippy_lints/src/enum_variants.rs
  tests/ui/module_name_repetitions.stderr
Labels: S-waiting-on-review

#10232 Mark Rust 1.67 as released in the changelog
  CHANGELOG.md
Labels: S-waiting-on-review

#10237 Fix styling in documentation for `suspicious_xor_used_as_pow` lint
  clippy_lints/src/suspicious_xor_used_as_pow.rs
Labels: S-waiting-on-review

#10242 Rustup
  Cargo.toml
  clippy_lints/Cargo.toml
  clippy_lints/src/attrs.rs
  clippy_lints/src/derive.rs
  clippy_lints/src/fallible_impl_from.rs
  clippy_lints/src/format_args.rs
  clippy_lints/src/from_over_into.rs
  clippy_lints/src/future_not_send.rs
  clippy_lints/src/inherent_impl.rs
  clippy_lints/src/len_zero.rs
  clippy_lints/src/loops/while_immutable_condition.rs
  clippy_lints/src/methods/unnecessary_to_owned.rs
  clippy_lints/src/missing_inline.rs
  clippy_lints/src/missing_trait_methods.rs
  clippy_lints/src/needless_pass_by_value.rs
  clippy_lints/src/non_send_fields_in_send_ty.rs
  clippy_lints/src/only_used_in_recursion.rs
  clippy_lints/src/pass_by_ref_or_value.rs
  clippy_lints/src/transmute/utils.rs
  clippy_lints/src/use_self.rs
  clippy_utils/Cargo.toml
  clippy_utils/src/macros.rs
  clippy_utils/src/sugg.rs
  clippy_utils/src/ty.rs
  declare_clippy_lint/Cargo.toml
  rust-toolchain
  tests/ui-internal/unnecessary_def_path_hardcoded_path.stderr
  tests/ui/crashes/ice-6252.stderr
  tests/ui/def_id_nocore.rs
Labels: S-waiting-on-review

#10231 `invalid_regex`: Show full error when string value doesn't match source
  clippy_lints/src/regex.rs
  tests/ui/regex.rs
  tests/ui/regex.stderr
Labels: S-waiting-on-review

#10248 Missing config
  book/src/lint_configuration.md
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/utils/conf.rs
Labels: S-waiting-on-review

#10254 needless_range_loop: improve documentation
  clippy_lints/src/loops/mod.rs
  clippy_lints/src/loops/needless_range_loop.rs
  tests/ui/needless_range_loop.stderr
Labels: S-waiting-on-review

#10260 `multiple_unsafe_ops_per_block`: Don't lint in external macros
  clippy_lints/src/multiple_unsafe_ops_per_block.rs
  tests/ui/auxiliary/macro_rules.rs
  tests/ui/multiple_unsafe_ops_per_block.rs
  tests/ui/multiple_unsafe_ops_per_block.stderr
Labels: S-waiting-on-review

#10257 needless_lifetimes: lint local macros
  clippy_lints/src/lifetimes.rs
  tests/ui/auxiliary/macro_rules.rs
  tests/ui/needless_lifetimes.rs
  tests/ui/needless_lifetimes.stderr
Labels: S-waiting-on-review

#10225 [`unused_io_amount`]: Lint with `is_ok` and `is_err`
  clippy_lints/src/unused_io_amount.rs
  tests/ui/unused_io_amount.rs
  tests/ui/unused_io_amount.stderr
Labels: S-waiting-on-review

#10265 Mark uninlined_format_args as pedantic
  clippy_lints/src/format_args.rs
Labels: S-waiting-on-review
