Repository rust-lang/rust-clippy, pull requests merged in 2023-11, with the labels that each got.

#10404 Add `unused_enumerate_index` lint
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/loops/for_kv_map.rs
  clippy_lints/src/loops/mod.rs
  clippy_lints/src/loops/unused_enumerate_index.rs
  clippy_lints/src/methods/iter_kv_map.rs
  clippy_utils/src/lib.rs
  tests/ui/unused_enumerate_index.fixed
  tests/ui/unused_enumerate_index.rs
  tests/ui/unused_enumerate_index.stderr
Labels: S-waiting-on-review, hacktoberfest-accepted

#11744 Fix get_first false negative for VecDeque
  clippy_lints/src/methods/get_first.rs
  tests/ui/get_first.fixed
  tests/ui/get_first.rs
  tests/ui/get_first.stderr
Labels: S-waiting-on-review

#11743 Fix `dbg_macro` semi span calculation
  clippy_lints/src/dbg_macro.rs
  tests/ui/dbg_macro/auxiliary/submodule.rs
  tests/ui/dbg_macro/dbg_macro.rs
  tests/ui/dbg_macro/dbg_macro.stderr
Labels: S-waiting-on-review

#11756 [`unused_enumerate_index`]: don't ICE on empty tuples
  clippy_lints/src/loops/unused_enumerate_index.rs
  tests/ui/crashes/ice-11755.rs
Labels: S-waiting-on-review

#11758 update references of old `msrvs` and `conf` paths
  book/src/development/adding_lints.md
  clippy_dev/src/new_lint.rs
  clippy_lints/src/types/mod.rs
Labels: S-waiting-on-review

#11736 Make SpanlessEq more consistent
  clippy_utils/src/hir_utils.rs
Labels: S-waiting-on-review

#11772 [arc_with_non_send_sync] Improve suggested resolution
  clippy_lints/src/arc_with_non_send_sync.rs
  tests/ui/arc_with_non_send_sync.rs
  tests/ui/arc_with_non_send_sync.stderr
Labels: S-waiting-on-review

#11779 [`mod_module_files`] Don't emit lint for mod.rs in tests
  clippy_lints/src/module_style.rs
Labels: S-waiting-on-review

#11780 Disable `vec_box` when using different allocators
  clippy_lints/src/types/vec_box.rs
  clippy_utils/src/paths.rs
  tests/ui/vec_box_sized.fixed
  tests/ui/vec_box_sized.rs
  tests/ui/vec_box_sized.stderr
Labels: S-waiting-on-review

#11790 Destructure `Conf` in `register_lints`
  CONTRIBUTING.md
  book/src/development/adding_lints.md
  book/src/development/defining_lints.md
  clippy_config/src/types.rs
  clippy_lints/src/disallowed_names.rs
  clippy_lints/src/doc.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/nonstandard_macro_braces.rs
  clippy_lints/src/pass_by_ref_or_value.rs
  clippy_lints/src/raw_strings.rs
  src/driver.rs
Labels: S-waiting-on-review

#11792 [`map_identity`]: respect match ergonomics
  clippy_utils/src/lib.rs
  tests/ui/map_identity.fixed
  tests/ui/map_identity.rs
  tests/ui/map_identity.stderr
Labels: S-waiting-on-review

#11767 Add type details to unnecessary_fallible_conversions note
  clippy_lints/src/methods/unnecessary_fallible_conversions.rs
  tests/ui/unnecessary_fallible_conversions.stderr
  tests/ui/unnecessary_fallible_conversions_unfixable.stderr
Labels: S-waiting-on-review

#11508 Lint `needless_borrow` and `explicit_auto_deref` on most union field accesses
  clippy_lints/src/dereference.rs
  clippy_utils/src/ty.rs
  tests/ui/explicit_auto_deref.fixed
  tests/ui/explicit_auto_deref.rs
  tests/ui/explicit_auto_deref.stderr
  tests/ui/needless_borrow.fixed
  tests/ui/needless_borrow.rs
  tests/ui/needless_borrow.stderr
Labels: S-waiting-on-review

#11787 Fixes to `manual_let_else`'s divergence check
  clippy_lints/src/manual_let_else.rs
  clippy_utils/src/lib.rs
  tests/ui/manual_let_else.rs
  tests/ui/manual_let_else.stderr
Labels: S-waiting-on-review

#11760 Don't check for late-bound vars, check for escaping bound vars
  clippy_utils/src/ty.rs
  tests/ui/crashes/ice-11230.rs
Labels: S-waiting-on-review

#11798 move `suspicious_doc_comments` to doc pass
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/doc.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/suspicious_doc_comments.rs
Labels: S-waiting-on-review

#11800 Removing @Centri3 from reviewer rotation
  triagebot.toml
Labels: S-waiting-on-review

#11778 fix: [manual_memcpy] reduce indexing suggestions when array length is equal to loop range
  clippy_lints/src/loops/manual_memcpy.rs
  tests/ui/manual_memcpy/without_loop_counters.rs
  tests/ui/manual_memcpy/without_loop_counters.stderr
Labels: S-waiting-on-review

#11810 add help text where missing to lints
  clippy_lints/src/casts/cast_possible_wrap.rs
  clippy_lints/src/module_style.rs
Labels: S-waiting-on-review

#11804 [`impl_trait_in_params`]: avoid ICE when function with `impl Trait` type has no parameters
  clippy_lints/src/functions/impl_trait_in_params.rs
  tests/ui/crashes/ice-11803.rs
  tests/ui/crashes/ice-11803.stderr
Labels: S-waiting-on-review

#11811 disallow calls to `LintContext::struct_span_lint` and `TyCtxt::struct_span_lint_hir`
  clippy.toml
  clippy_utils/src/diagnostics.rs
  tests/ui-internal/disallow_struct_span_lint.rs
  tests/ui-internal/disallow_struct_span_lint.stderr
Labels: S-waiting-on-review

#11806 Changelog for Rust 1.74 🎃
  CHANGELOG.md
  clippy_lints/src/attrs.rs
  clippy_lints/src/implied_bounds_in_impls.rs
  clippy_lints/src/missing_asserts_for_indexing.rs
  clippy_lints/src/needless_borrows_for_generic_args.rs
  clippy_lints/src/reserve_after_initialization.rs
  clippy_lints/src/unnecessary_map_on_constructor.rs
Labels: S-waiting-on-review

#11824 Update rust-cache GHA in deploy workflow
  .github/workflows/deploy.yml
Labels: S-waiting-on-review

#11828 Fix typo
  clippy_lints/src/unnecessary_map_on_constructor.rs
Labels: S-waiting-on-review

#11821 Extend `maybe_misused_cfg` lint over `cfg(test)`
  clippy_lints/src/attrs.rs
  tests/ui/cfg_features.fixed
  tests/ui/cfg_features.rs
  tests/ui/cfg_features.stderr
Labels: S-waiting-on-review

#11002 teach `eager_or_lazy` about panicky arithmetic operations
  clippy_lints/src/matches/match_same_arms.rs
  clippy_utils/src/consts.rs
  clippy_utils/src/eager_or_lazy.rs
  tests/ui/unnecessary_lazy_eval.fixed
  tests/ui/unnecessary_lazy_eval.rs
  tests/ui/unnecessary_lazy_eval.stderr
Labels: S-waiting-on-review

#11826 Fix typos in recent lint documentation.
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/unnecessary_map_on_constructor.rs
Labels: S-waiting-on-review

#11782 Make `macro_use_imports` lint ordering more stable
  clippy_lints/src/macro_use.rs
  tests/ui/macro_use_imports.stderr
Labels: S-waiting-on-review

#11691 Lint `flatten()` under `lines_filter_map_ok`
  clippy_lints/src/lines_filter_map_ok.rs
  tests/ui/lines_filter_map_ok.fixed
  tests/ui/lines_filter_map_ok.rs
  tests/ui/lines_filter_map_ok.stderr
Labels: S-waiting-on-review

#11781 Verify Borrow<T> semantics for types that implement Hash, Borrow<str> and Borrow<[u8]>.
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/impl_hash_with_borrow_str_and_bytes.rs
  clippy_lints/src/lib.rs
  tests/ui/impl_hash_with_borrow_str_and_bytes.rs
  tests/ui/impl_hash_with_borrow_str_and_bytes.stderr
Labels: S-waiting-on-author, S-waiting-on-review, has-merge-commits

#11840 Improve maybe misused cfg
  clippy_lints/src/attrs.rs
  tests/ui/cfg_features.fixed
  tests/ui/cfg_features.rs
  tests/ui/cfg_features.stderr
Labels: S-waiting-on-review

#11453 New lint `clippy::join_absolute_paths`
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/methods/join_absolute_paths.rs
  clippy_lints/src/methods/mod.rs
  tests/ui/join_absolute_paths.rs
  tests/ui/join_absolute_paths.stderr
Labels: S-waiting-on-review

#11801 Split `doc.rs` up into a subdirectory
  clippy_lints/src/doc/link_with_quotes.rs
  clippy_lints/src/doc/markdown.rs
  clippy_lints/src/doc/missing_headers.rs
  clippy_lints/src/doc/mod.rs
  clippy_lints/src/doc/needless_doctest_main.rs
  clippy_lints/src/doc/suspicious_doc_comments.rs
  tests/ui/doc_link_with_quotes.rs
  tests/ui/doc_link_with_quotes.stderr
Labels: S-waiting-on-review, I-nominated

#11842 Add new `check_private_items` config
  CHANGELOG.md
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  clippy_lints/src/doc/missing_headers.rs
  clippy_lints/src/doc/mod.rs
  clippy_lints/src/lib.rs
  tests/ui-toml/private-doc-errors/clippy.toml
  tests/ui-toml/private-doc-errors/doc_lints.rs
  tests/ui-toml/private-doc-errors/doc_lints.stderr
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
Labels: S-waiting-on-review

#11627 [`needless_return_with_question_mark`]: don't lint if never type is used for coercion
  clippy_lints/src/returns.rs
  tests/ui/needless_return_with_question_mark.fixed
  tests/ui/needless_return_with_question_mark.rs
  tests/ui/needless_return_with_question_mark.stderr
Labels: S-waiting-on-review

#11849 Add tests for issues #10285, #10286, #10289, #10287
  tests/ui/transmute_ptr_to_ptr.fixed
  tests/ui/transmute_ptr_to_ptr.rs
  tests/ui/transmute_ptr_to_ptr.stderr
  tests/ui/transmute_ref_to_ref.rs
  tests/ui/transmute_ref_to_ref.stderr
Labels: S-waiting-on-review

#11844 Remove underscore check for `manual_non_exhaustive` lint
  clippy_lints/src/manual_non_exhaustive.rs
  tests/ui/manual_non_exhaustive_enum.rs
  tests/ui/manual_non_exhaustive_enum.stderr
  tests/ui/manual_non_exhaustive_struct.stderr
Labels: S-waiting-on-review

#11757 Fix iter_kv_map false positive into_keys and into_values suggestion
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  clippy_config/src/msrvs.rs
  clippy_lints/src/methods/iter_kv_map.rs
  clippy_lints/src/methods/mod.rs
  tests/ui/iter_kv_map.fixed
  tests/ui/iter_kv_map.rs
  tests/ui/iter_kv_map.stderr
Labels: S-waiting-on-review

#11857 Add documentation update hint using `cargo collect-metadata`
  book/src/development/adding_lints.md
Labels: S-waiting-on-review

#11845 Extend `result_map_or_into_option` lint to handle `Result::map_or_else(|_| None, Some)`
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/result_map_or_else_none.rs
  tests/ui/result_map_or_into_option.fixed
  tests/ui/result_map_or_into_option.rs
  tests/ui/result_map_or_into_option.stderr
Labels: S-waiting-on-review

#11860 Improve error messages format
  clippy_lints/src/methods/map_unwrap_or.rs
  clippy_lints/src/methods/option_as_ref_deref.rs
  clippy_lints/src/methods/option_map_or_none.rs
  clippy_lints/src/methods/option_map_unwrap_or.rs
  tests/ui/map_unwrap_or.stderr
  tests/ui/map_unwrap_or_fixable.stderr
  tests/ui/option_as_ref_deref.stderr
  tests/ui/option_map_or_none.stderr
  tests/ui/result_map_or_into_option.fixed
  tests/ui/result_map_or_into_option.rs
  tests/ui/result_map_or_into_option.stderr
Labels: S-waiting-on-review

#11859 [`missing_asserts_for_indexing`]: work with bodies instead of blocks separately
  clippy_lints/src/missing_asserts_for_indexing.rs
  tests/ui/missing_asserts_for_indexing_unfixable.rs
  tests/ui/missing_asserts_for_indexing_unfixable.stderr
Labels: S-waiting-on-review

#11850 [`deprecated_semver`]: Allow `#[deprecated(since = "TBD")]`
  clippy_lints/src/attrs.rs
  tests/ui/attrs.rs
Labels: S-waiting-on-review

#11863 Nit re `matches!` formatting
  clippy_lints/src/eta_reduction.rs
Labels: S-waiting-on-review

#11862 suggest alternatives to iterate an array of ranges
  clippy_lints/src/loops/single_element_loop.rs
  tests/ui/single_element_loop.fixed
  tests/ui/single_element_loop.stderr
Labels: S-waiting-on-review

#11866 Simplify code for `result_map_or_else_none`
  clippy_lints/src/methods/result_map_or_else_none.rs
Labels: S-waiting-on-review

#11864 Create new lint `option_map_or_err_ok`
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/option_map_or_err_ok.rs
  tests/ui/manual_ok_or.stderr
  tests/ui/option_map_or_err_ok.fixed
  tests/ui/option_map_or_err_ok.rs
  tests/ui/option_map_or_err_ok.stderr
Labels: S-waiting-on-review

#11875 Fix `box_default` behaviour with empty `vec![]` coming from macro arg
  clippy_lints/src/box_default.rs
  tests/ui/box_default.fixed
  tests/ui/box_default.rs
Labels: S-waiting-on-review

#11867 Move `implied_bounds_in_impls` back to complexity
  clippy_lints/src/implied_bounds_in_impls.rs
Labels: S-waiting-on-review

#11877 `TypeckResults::node_type()` can be used inside of bodies
  book/src/development/type_checking.md
Labels: S-waiting-on-review

#11879 `manual_try_fold`: check that `fold` is really `Iterator::fold`
  clippy_lints/src/methods/manual_try_fold.rs
  tests/ui/manual_try_fold.rs
Labels: S-waiting-on-review

#11836 Don't suggest `a.mul_add(b, c)` if parameters are not float
  clippy_lints/src/floating_point_arithmetic.rs
  tests/ui/floating_point_mul_add.fixed
  tests/ui/floating_point_mul_add.rs
Labels: S-waiting-on-review

#11892 rename `DocMarkdown` pass to `Documentation`
  clippy_lints/src/doc/mod.rs
  clippy_lints/src/lib.rs
Labels: S-waiting-on-review

#11363 [`redundant_closure_call`]: avoid duplicated `async` keyword when triggering on closure that returns `async` block
  clippy_lints/src/redundant_closure_call.rs
  tests/ui/redundant_closure_call_fixable.fixed
  tests/ui/redundant_closure_call_fixable.rs
  tests/ui/redundant_closure_call_fixable.stderr
Labels: S-waiting-on-review

#11818 [`redundant_guards`]: catch `is_empty`, `starts_with` and `ends_with` on slices and `str`s
  clippy_lints/src/manual_async_fn.rs
  clippy_lints/src/matches/redundant_guards.rs
  tests/ui/redundant_guards.fixed
  tests/ui/redundant_guards.rs
  tests/ui/redundant_guards.stderr
Labels: S-waiting-on-review
