Repository rust-lang/rust-clippy, pull requests merged in 2023-02, with the labels that each got.

#10256 Fix version declared for semicolon_inside_block and semicolon_outside…
  clippy_lints/src/semicolon_block.rs
Labels: S-waiting-on-review

#10270 Update dependencies `cargo_metadata` and `clap`
  Cargo.toml
  clippy_dev/Cargo.toml
  clippy_dev/src/main.rs
  clippy_lints/Cargo.toml
  lintcheck/Cargo.toml
Labels: S-waiting-on-review

#10250 wildcard_enum_match_arm lint takes the enum origin into account
  clippy_lints/src/matches/match_wild_enum.rs
  tests/ui/match_wildcard_for_single_variants.fixed
  tests/ui/match_wildcard_for_single_variants.stderr
  tests/ui/wildcard_enum_match_arm.fixed
  tests/ui/wildcard_enum_match_arm.stderr
Labels: S-waiting-on-review

#10276 Don't depend on FormatArgsExpn in ManualAssert.
  clippy_lints/src/manual_assert.rs
  tests/ui/manual_assert.edition2018.fixed
  tests/ui/manual_assert.edition2018.stderr
Labels: S-waiting-on-review

#10028 Add `extra_unused_type_parameters` lint
  CHANGELOG.md
  README.md
  book/src/README.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/extra_unused_type_parameters.rs
  clippy_lints/src/lib.rs
  tests/ui/extra_unused_type_parameters.rs
  tests/ui/extra_unused_type_parameters.stderr
  tests/ui/needless_lifetimes.fixed
  tests/ui/needless_lifetimes.rs
  tests/ui/needless_lifetimes.stderr
  tests/ui/new_without_default.rs
  tests/ui/new_without_default.stderr
  tests/ui/redundant_field_names.fixed
  tests/ui/redundant_field_names.rs
  tests/ui/seek_to_start_instead_of_rewind.fixed
  tests/ui/seek_to_start_instead_of_rewind.rs
  tests/ui/type_repetition_in_bounds.rs
  tests/ui/type_repetition_in_bounds.stderr
Labels: S-waiting-on-review

#10295 fix(suspicious_to_owned): use span_suggestions to suggest both intents
  clippy_lints/src/methods/suspicious_to_owned.rs
  tests/ui/suspicious_to_owned.stderr
Labels: S-waiting-on-review

#10293 Negate suggestions when needed in `bool_assert_comparison`
  clippy_lints/src/bool_assert_comparison.rs
  tests/ui/bool_assert_comparison.fixed
  tests/ui/bool_assert_comparison.rs
  tests/ui/bool_assert_comparison.stderr
Labels: S-waiting-on-review

#10292 Make `[clippy::dump]` support trait items
  clippy_lints/src/utils/dump_hir.rs
Labels: S-waiting-on-review

#10314 Fix CLI of clippy_dev
  clippy_dev/src/main.rs
Labels: S-waiting-on-review

#10330 cast_possible_truncation: issue proper help message
  clippy_lints/src/casts/cast_possible_truncation.rs
  tests/ui/cast.stderr
  tests/ui/cast_size.stderr
Labels: S-waiting-on-review

#10333 lintcheck: fix clap panic
  lintcheck/src/config.rs
Labels: S-waiting-on-review

#10310 [arithmetic_side_effects] Fix #10209
  clippy_lints/src/operators/arithmetic_side_effects.rs
  tests/ui/arithmetic_side_effects.rs
  tests/ui/arithmetic_side_effects.stderr
Labels: S-waiting-on-review

#10317 Add `suspicious_command_arg_space` lint
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/suspicious_command_arg_space.rs
  clippy_utils/src/paths.rs
  tests/ui/suspicious_command_arg_space.rs
  tests/ui/suspicious_command_arg_space.stderr
Labels: S-waiting-on-review

#10177 Almost swapped
  clippy_lints/src/swap.rs
  tests/ui/swap.fixed
  tests/ui/swap.rs
  tests/ui/swap.stderr
Labels: S-waiting-on-review

#10334 book: move warning to the right place
  book/src/development/infrastructure/backport.md
  book/src/development/infrastructure/sync.md
Labels: S-waiting-on-review

#10311 [never_loop] Fix #10304
  clippy_lints/src/loops/never_loop.rs
  tests/ui/never_loop.rs
  tests/ui/never_loop.stderr
Labels: S-waiting-on-review

#10346 Do not base map_entry lint suggestion on expanded code
  clippy_lints/src/entry.rs
  tests/ui/entry.fixed
  tests/ui/entry.rs
Labels: S-waiting-on-review

#10332 manual_let_else: let/else is not divergent by default
  clippy_lints/src/manual_let_else.rs
  tests/ui/manual_let_else.rs
Labels: S-waiting-on-review

#10345 fix [`needless_return`] incorrect suggestion when returning if sequence
  clippy_lints/src/returns.rs
  tests/ui/needless_return.fixed
  tests/ui/needless_return.rs
  tests/ui/needless_return.stderr
Labels: S-waiting-on-review

#10343 uninlined_format_args: do not inline argument with generic parameters
  clippy_lints/src/format_args.rs
  tests/ui/uninlined_format_args.fixed
  tests/ui/uninlined_format_args.rs
Labels: S-waiting-on-review

#10321 Fix false positives for `extra_unused_type_parameters`
  clippy_lints/src/extra_unused_type_parameters.rs
  tests/ui/extra_unused_type_parameters.rs
  tests/ui/extra_unused_type_parameters.stderr
  tests/ui/type_repetition_in_bounds.rs
  tests/ui/type_repetition_in_bounds.stderr
Labels: S-waiting-on-review, I-nominated

#10338 Ignore synthetic type parameters for `extra_unused_type_parameters`
  clippy_lints/src/extra_unused_type_parameters.rs
  tests/ui/extra_unused_type_parameters.rs
  tests/ui/extra_unused_type_parameters.stderr
Labels: S-waiting-on-review

#10353 Change unusual_byte_groupings to require byte groupings of equal size
  clippy_lints/src/literal_representation.rs
  tests/ui/large_digit_groups.fixed
  tests/ui/large_digit_groups.stderr
  tests/ui/literals.stderr
  tests/ui/unreadable_literal.fixed
  tests/ui/unreadable_literal.stderr
Labels: S-waiting-on-review

#10163 [significant_drop_tightening] Add MVP
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/significant_drop_tightening.rs
  tests/ui/significant_drop_tightening.fixed
  tests/ui/significant_drop_tightening.rs
  tests/ui/significant_drop_tightening.stderr
Labels: S-waiting-on-review

#10356 Add `let_underscore_untyped`
  CHANGELOG.md
  clippy_dev/src/new_lint.rs
  clippy_dev/src/update_lints.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/entry.rs
  clippy_lints/src/inconsistent_struct_constructor.rs
  clippy_lints/src/let_underscore.rs
  clippy_lints/src/literal_representation.rs
  clippy_lints/src/module_style.rs
  clippy_utils/src/numeric_literal.rs
  clippy_utils/src/sugg.rs
  lintcheck/src/main.rs
  tests/ui/let_underscore_untyped.rs
  tests/ui/let_underscore_untyped.stderr
  tests/ui/map_flatten_fixable.fixed
  tests/ui/map_flatten_fixable.rs
  tests/ui/map_flatten_fixable.stderr
  tests/ui/methods.rs
  tests/ui/methods.stderr
Labels: S-waiting-on-review

#10342 Add question-mark-used lint
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/question_mark_used.rs
  tests/ui/question_mark_used.rs
  tests/ui/question_mark_used.stderr
Labels: S-waiting-on-review

#10360 Add the `transmute_int_to_non_zero` lint
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/transmute/mod.rs
  clippy_lints/src/transmute/transmute_int_to_non_zero.rs
  tests/ui/transmute_int_to_non_zero.rs
  tests/ui/transmute_int_to_non_zero.stderr
Labels: S-waiting-on-review

#10357 Stop doc_markdown requiring backticks on links to external websites
  clippy_lints/src/doc.rs
  tests/ui/doc/doc-fixable.fixed
  tests/ui/doc/doc-fixable.rs
  tests/ui/doc/doc-fixable.stderr
Labels: S-waiting-on-review

#10361 Stop bytes_nth from suggesting code that does not compile
  clippy_lints/src/methods/bytes_nth.rs
  tests/ui/bytes_nth.fixed
  tests/ui/bytes_nth.rs
  tests/ui/bytes_nth.stderr
Labels: S-waiting-on-review

#10336 manual_let_else: do not suggest semantically different replacements
  clippy_lints/src/manual_let_else.rs
  tests/ui/manual_let_else_match.rs
  tests/ui/manual_let_else_match.stderr
Labels: S-waiting-on-review

#10363 [significant_drop_tightening] Ignore inexpensive statements
  clippy_lints/src/significant_drop_tightening.rs
  tests/ui/significant_drop_tightening.fixed
  tests/ui/significant_drop_tightening.rs
  tests/ui/significant_drop_tightening.stderr
Labels: S-waiting-on-review

#10368 [significant_drop_tightening] Evaluate the return expression of a block
  clippy_lints/src/significant_drop_tightening.rs
  tests/ui/significant_drop_tightening.fixed
  tests/ui/significant_drop_tightening.rs
  tests/ui/significant_drop_tightening.stderr
Labels: S-waiting-on-review

#10382 Box::default(): do not omit the type of the removed trait object
  clippy_lints/src/box_default.rs
  tests/ui/box_default.fixed
  tests/ui/box_default.rs
  tests/ui/box_default.stderr
Labels: S-waiting-on-review

#10303 Add configuration to lint missing docs of `pub(crate)` items
  book/src/lint_configuration.md
  clippy_lints/src/lib.rs
  clippy_lints/src/missing_doc.rs
  clippy_lints/src/utils/conf.rs
  tests/ui-toml/pub_crate_missing_docs/clippy.toml
  tests/ui-toml/pub_crate_missing_docs/pub_crate_missing_doc.rs
  tests/ui-toml/pub_crate_missing_docs/pub_crate_missing_doc.stderr
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
Labels: S-waiting-on-review

#10197 Add `impl_trait_in_params` lint
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/functions/impl_trait_in_params.rs
  clippy_lints/src/functions/mod.rs
  tests/ui/impl_trait_in_params.rs
  tests/ui/impl_trait_in_params.stderr
Labels: S-waiting-on-review

#10380 Ignore lifetimes from differing contexts in `needless_lifetimes`
  clippy_lints/src/lifetimes.rs
  tests/ui/needless_lifetimes.fixed
  tests/ui/needless_lifetimes.rs
Labels: S-waiting-on-review

#10386 Normalize projections types when checking `explicit_auto_deref`
  clippy_lints/src/dereference.rs
  clippy_utils/src/ty.rs
  tests/ui/explicit_auto_deref.fixed
  tests/ui/explicit_auto_deref.rs
Labels: S-waiting-on-review

#10385 Update readme description of `restriction` lints to dissuade casual use.
  README.md
Labels: S-waiting-on-review

#10392 Fix more false positives for `extra_unused_type_parameters`
  clippy_lints/src/extra_unused_type_parameters.rs
  clippy_lints/src/lib.rs
  tests/ui/extra_unused_type_parameters.rs
  tests/ui/extra_unused_type_parameters.stderr
  tests/ui/new_without_default.rs
  tests/ui/new_without_default.stderr
  tests/ui/redundant_field_names.fixed
  tests/ui/redundant_field_names.rs
Labels: S-waiting-on-review

#10369 Add new lint no_mangle_with_rust_abi
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/no_mangle_with_rust_abi.rs
  tests/ui/must_use_candidates.fixed
  tests/ui/must_use_candidates.rs
  tests/ui/no_mangle_with_rust_abi.fixed
  tests/ui/no_mangle_with_rust_abi.rs
  tests/ui/no_mangle_with_rust_abi.stderr
Labels: S-waiting-on-review

#10391 Fix test function checker in `unwrap_used`, `expect_used`
  book/src/lint_configuration.md
  clippy_lints/src/methods/expect_used.rs
  clippy_lints/src/methods/unwrap_used.rs
  clippy_lints/src/utils/conf.rs
  tests/ui-toml/expect_used/expect_used.rs
  tests/ui-toml/unwrap_used/unwrap_used.rs
  tests/ui-toml/unwrap_used/unwrap_used.stderr
Labels: S-waiting-on-review

#10401 Do not panic when analyzing the malformed origin of a format string
  clippy_utils/src/macros.rs
  tests/ui/format.fixed
  tests/ui/format.rs
  tests/ui/format.stderr
Labels: S-waiting-on-review

#10375 Do not suggest using Self in const generic parameters
  clippy_lints/src/use_self.rs
  tests/ui/use_self.fixed
  tests/ui/use_self.rs
Labels: S-waiting-on-review

#10400 chore: remove unneeded rustfmt skip
  tests/ui/trailing_empty_array.rs
Labels: S-waiting-on-review

#10408 exit lint: potentualy -> potentially
  clippy_lints/src/exit.rs
Labels: S-waiting-on-review

#10419 Fixing typos
  book/src/development/proposals/syntax-tree-patterns.md
  clippy_lints/src/functions/impl_trait_in_params.rs
  clippy_lints/src/functions/misnamed_getters.rs
  clippy_lints/src/matches/mod.rs
  clippy_utils/src/lib.rs
  tests/ui/impl_trait_in_params.stderr
  tests/ui/implicit_clone.fixed
  tests/ui/implicit_clone.rs
  tests/ui/new_ret_no_self.rs
Labels: S-waiting-on-review

#10423 Fix array-size-threshold config deserialization error
  book/src/lint_configuration.md
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/conf.rs
  tests/ui-toml/array_size_threshold/array_size_threshold.rs
  tests/ui-toml/array_size_threshold/array_size_threshold.stderr
  tests/ui-toml/array_size_threshold/clippy.toml
  tests/ui/crashes/ice-10044.rs
  tests/ui/crashes/ice-10044.stderr
  tests/ui/large_stack_arrays.rs
  tests/ui/large_stack_arrays.stderr
Labels: S-waiting-on-review, beta-nominated

#10405 Fix ICE in `multiple_unsafe_ops_per_block`
  clippy_lints/src/multiple_unsafe_ops_per_block.rs
  tests/ui/multiple_unsafe_ops_per_block.rs
  tests/ui/multiple_unsafe_ops_per_block.stderr
Labels: S-waiting-on-review

#10418 Run dogfood to completion
  tests/dogfood.rs
Labels: S-waiting-on-review

#10324 Scope `missing_docs_in_private_items` to only private items
  clippy_lints/src/missing_doc.rs
  tests/ui/missing_doc.stderr
  tests/ui/missing_doc_impl.stderr
Labels: S-waiting-on-review

#10425 Two small documentation improvements
  clippy_lints/src/functions/mod.rs
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-review

#10427 Update version attribute for 1.68 lints
  CHANGELOG.md
  clippy_lints/src/almost_complete_range.rs
  clippy_lints/src/fn_null_check.rs
  clippy_lints/src/permissions_set_readonly_false.rs
  clippy_lints/src/size_of_ref.rs
  clippy_lints/src/transmute/mod.rs
Labels: S-waiting-on-review
