Repository rust-lang/rust-clippy, pull requests merged in 2024-07, with the labels that each got.

#12970 fix wrong msrv import in `new_lint` template
  clippy_dev/src/new_lint.rs
Labels: S-waiting-on-review

#12983 Implement a lint to replace manual bit rotations with rotate_left/rot…
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_rotate.rs
  tests/ui/manual_rotate.fixed
  tests/ui/manual_rotate.rs
  tests/ui/manual_rotate.stderr
Labels: S-waiting-on-review

#13025 `manual_inspect`: fix `clippy::version` from 1.78.0 to 1.81.0
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-review

#13026 Fix doc for INEFFECTIVE_BIT_MASK and VERBOSE_BIT_MASK
  clippy_lints/src/operators/mod.rs
Labels: S-waiting-on-review

#13017 Image-related valid idents
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
Labels: S-waiting-on-review

#12840 Don't lint `assertions_on_constants` on any const assertions
  clippy_lints/src/assertions_on_constants.rs
  clippy_lints/src/default_numeric_fallback.rs
  clippy_lints/src/no_effect.rs
  clippy_utils/src/lib.rs
  tests/ui/assertions_on_constants.rs
  tests/ui/assertions_on_constants.stderr
  tests/ui/unnecessary_operation.fixed
  tests/ui/unnecessary_operation.rs
  tests/ui/unnecessary_operation.stderr
Labels: S-waiting-on-review

#13029 build: Skip installing rust-docs with minimal rustup profile
  rust-toolchain
Labels: S-waiting-on-review

#13030 Fix #12964 - false positive with `into_iter_without_iter`
  clippy_utils/src/ty.rs
  tests/ui/into_iter_without_iter.rs
Labels: S-waiting-on-review

#13010 doc_markdown: detect escaped `` ` `` when checking unmatched
  clippy_lints/src/doc/mod.rs
  tests/ui/doc/unbalanced_ticks.rs
  tests/ui/doc/unbalanced_ticks.stderr
Labels: S-waiting-on-review

#11647 Honor `avoid-breaking-exported-api` in `needless_pass_by_ref_mut`
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  clippy_lints/src/needless_pass_by_ref_mut.rs
  tests/ui-toml/needless_pass_by_ref_mut/clippy.toml
  tests/ui-toml/needless_pass_by_ref_mut/needless_pass_by_ref_mut.fixed
  tests/ui-toml/needless_pass_by_ref_mut/needless_pass_by_ref_mut.rs
  tests/ui-toml/needless_pass_by_ref_mut/needless_pass_by_ref_mut.stderr
  tests/ui/needless_pass_by_ref_mut.rs
  tests/ui/needless_pass_by_ref_mut.stderr
  tests/ui/needless_pass_by_ref_mut2.fixed
  tests/ui/needless_pass_by_ref_mut2.rs
  tests/ui/needless_pass_by_ref_mut2.stderr
Labels: S-waiting-on-author

#12976 Fix some false-positive cases of `explicit_auto_deref`
  clippy_lints/src/dereference.rs
  clippy_utils/src/lib.rs
  tests/ui/explicit_auto_deref.fixed
  tests/ui/explicit_auto_deref.rs
  tests/ui/explicit_auto_deref.stderr
Labels: S-waiting-on-review

#13027 `needless_return`: Support `#[expect]` on the return statement
  clippy_lints/src/returns.rs
  tests/ui/needless_return.fixed
  tests/ui/needless_return.rs
  tests/ui/needless_return.stderr
Labels: S-waiting-on-review

#12873 Add new lint `hashset_insert_after_contains`
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/set_contains_or_insert.rs
  tests/ui/set_contains_or_insert.rs
  tests/ui/set_contains_or_insert.stderr
Labels: S-waiting-on-review

#10155 Add new lint for byte char slices
  CHANGELOG.md
  clippy_lints/src/byte_char_slices.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  tests/ui/byte_char_slices.fixed
  tests/ui/byte_char_slices.rs
  tests/ui/byte_char_slices.stderr
Labels: S-waiting-on-review

#13037 [`missing_const_for_fn`]: fix suggestions for fn with abi that requires `const_extern_fn` feature
  clippy_config/src/msrvs.rs
  clippy_lints/src/missing_const_for_fn.rs
  tests/ui/missing_const_for_fn/cant_be_const.rs
  tests/ui/missing_const_for_fn/could_be_const.fixed
  tests/ui/missing_const_for_fn/could_be_const.rs
  tests/ui/missing_const_for_fn/could_be_const.stderr
  tests/ui/missing_const_for_fn/could_be_const_with_const_extern_fn.fixed
  tests/ui/missing_const_for_fn/could_be_const_with_const_extern_fn.rs
  tests/ui/missing_const_for_fn/could_be_const_with_const_extern_fn.stderr
Labels: S-waiting-on-review

#11656 [`unnecessary_to_owned`]: catch `to_owned` on byte slice to create temporary `&str`
  clippy_lints/src/methods/unnecessary_to_owned.rs
  clippy_utils/src/paths.rs
  tests/ui/unnecessary_to_owned.fixed
  tests/ui/unnecessary_to_owned.rs
  tests/ui/unnecessary_to_owned.stderr
Labels: S-waiting-on-review

#13047 Refactor `disallowed_script_idents`
  clippy_lints/src/disallowed_script_idents.rs
Labels: S-waiting-on-review

#13049 Remove `is_in_test_module_or_function`
  clippy_lints/src/disallowed_names.rs
  clippy_lints/src/functions/impl_trait_in_params.rs
  clippy_lints/src/incompatible_msrv.rs
  clippy_lints/src/methods/unwrap_expect_used.rs
  clippy_lints/src/missing_assert_message.rs
  clippy_lints/src/wildcard_imports.rs
  clippy_lints/src/write.rs
  clippy_utils/src/lib.rs
  tests/ui/disallowed_names.rs
  tests/ui/wildcard_imports.fixed
  tests/ui/wildcard_imports.rs
  tests/ui/wildcard_imports.stderr
  tests/ui/wildcard_imports_2021.edition2018.fixed
  tests/ui/wildcard_imports_2021.edition2018.stderr
  tests/ui/wildcard_imports_2021.edition2021.fixed
  tests/ui/wildcard_imports_2021.edition2021.stderr
  tests/ui/wildcard_imports_2021.rs
Labels: S-waiting-on-review

#11293 feat: add cfg_not_test lint
  CHANGELOG.md
  clippy_lints/src/cfg_not_test.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  tests/ui/cfg_not_test.rs
  tests/ui/cfg_not_test.stderr
Labels: S-waiting-on-review

#12974 Rename thread_local_initializer_can_be_made_const to missing_const_for_thread_local
  CHANGELOG.md
  clippy_config/src/msrvs.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/missing_const_for_thread_local.rs
  clippy_lints/src/renamed_lints.rs
  tests/ui/missing_const_for_thread_local.fixed
  tests/ui/missing_const_for_thread_local.rs
  tests/ui/missing_const_for_thread_local.stderr
  tests/ui/rename.fixed
  tests/ui/rename.rs
  tests/ui/rename.stderr
Labels: S-waiting-on-review

#13055 Only check for `automatically_derived` on impl blocks
  clippy_lints/src/default.rs
  clippy_lints/src/misc.rs
  clippy_lints/src/no_effect.rs
  clippy_utils/src/lib.rs
Labels: S-waiting-on-review

#12966 Clarify that `modulo_one` only applies to ints
  clippy_lints/src/operators/mod.rs
Labels: S-waiting-on-review

#13048 Refactor `disallowed_methods` and narrow span
  clippy_lints/src/disallowed_methods.rs
  tests/ui-internal/disallow_span_lint.stderr
  tests/ui-toml/toml_disallowed_methods/conf_disallowed_methods.stderr
Labels: S-waiting-on-review

#13052 Lintcheck: Add `--warn-all` and make it the CI default
  .github/workflows/lintcheck.yml
  lintcheck/README.md
  lintcheck/src/config.rs
  lintcheck/src/main.rs
Labels: S-waiting-on-review

#13068 Rework `init_numbered_fields`
  clippy_lints/src/init_numbered_fields.rs
  clippy_lints/src/lib.rs
  tests/ui/init_numbered_fields.fixed
  tests/ui/init_numbered_fields.rs
  tests/ui/init_numbered_fields.stderr
Labels: S-waiting-on-review

#13045 [`missing_const_for_fn`]: fix FP when arg ty is impl trait alias ty
  clippy_lints/src/missing_const_for_fn.rs
  tests/ui/missing_const_for_fn/cant_be_const.rs
  tests/ui/missing_const_for_fn/could_be_const.fixed
  tests/ui/missing_const_for_fn/could_be_const.rs
  tests/ui/missing_const_for_fn/could_be_const.stderr
Labels: S-waiting-on-review

#13064 Reduce the size of lintcheck JSON output
  lintcheck/Cargo.toml
  lintcheck/src/driver.rs
  lintcheck/src/json.rs
  lintcheck/src/main.rs
  lintcheck/src/recursive.rs
Labels: S-waiting-on-review

#12870 `significant_drop_in_scrutinee`: Trigger lint also for scrutinees in `while let` and `if let`
  clippy_lints/src/matches/mod.rs
  clippy_lints/src/matches/significant_drop_in_scrutinee.rs
  tests/ui/significant_drop_in_scrutinee.rs
  tests/ui/significant_drop_in_scrutinee.stderr
Labels: S-waiting-on-review

#13042 `almost_complete_range`: Delay suggestion creation.
  clippy_lints/src/almost_complete_range.rs
Labels: S-waiting-on-review

#13043 Refactor `assigning_clones`
  clippy_lints/src/assigning_clones.rs
Labels: S-waiting-on-review

#13044 Refactor `bool_to_int_with_if`
  clippy_lints/src/bool_to_int_with_if.rs
Labels: S-waiting-on-review

#13056 Remove internal `compiler_lint_functions` lint
  clippy.toml
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/internal_lints.rs
  clippy_lints/src/utils/internal_lints/compiler_lint_functions.rs
Labels: S-waiting-on-review

#13069 Misc refactorings part 4
  clippy_lints/src/len_zero.rs
  clippy_lints/src/let_if_seq.rs
  clippy_lints/src/let_underscore.rs
  clippy_lints/src/let_with_type_underscore.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/literal_representation.rs
  clippy_lints/src/manual_bits.rs
  clippy_lints/src/manual_float_methods.rs
  clippy_lints/src/manual_let_else.rs
  clippy_lints/src/manual_main_separator_str.rs
  clippy_lints/src/manual_non_exhaustive.rs
  clippy_lints/src/manual_range_patterns.rs
  clippy_lints/src/manual_rem_euclid.rs
  clippy_lints/src/manual_retain.rs
  clippy_lints/src/manual_slice_size_calculation.rs
  clippy_lints/src/manual_strip.rs
  clippy_lints/src/manual_unwrap_or_default.rs
  clippy_lints/src/map_unit_fn.rs
  clippy_lints/src/minmax.rs
Labels: S-waiting-on-review

#13080 Lintcheck: Refactor structs and only take one version per crate
  lintcheck/lintcheck_crates.toml
  lintcheck/src/input.rs
  lintcheck/src/main.rs
  lintcheck/src/output.rs
  lintcheck/src/popular_crates.rs
  lintcheck/src/recursive.rs
Labels: S-waiting-on-review

#13079 Fix guidance of [`float_cmp`] and [`float_cmp_const`] to not incorrectly recommend `f__::EPSILON` as the error margin.
  clippy_lints/src/operators/float_cmp.rs
  clippy_lints/src/operators/mod.rs
  tests/ui/float_cmp.rs
  tests/ui/float_cmp.stderr
  tests/ui/float_cmp_const.rs
  tests/ui/float_cmp_const.stderr
Labels: S-waiting-on-review

#12944 Fix and rename `overflow_check_conditional`
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/overflow_check_conditional.rs
  clippy_lints/src/panicking_overflow_checks.rs
  clippy_lints/src/renamed_lints.rs
  tests/ui/overflow_check_conditional.rs
  tests/ui/overflow_check_conditional.stderr
  tests/ui/panicking_overflow_checks.rs
  tests/ui/panicking_overflow_checks.stderr
  tests/ui/rename.fixed
  tests/ui/rename.rs
  tests/ui/rename.stderr
Labels: S-waiting-on-review

#12984 Fix doc nits
  clippy_lints/src/await_holding_invalid.rs
  clippy_lints/src/casts/mod.rs
  clippy_lints/src/casts/ptr_as_ptr.rs
  clippy_lints/src/endian_bytes.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/same_name_method.rs
  tests/ui-toml/await_holding_invalid_type/await_holding_invalid_type.stderr
  tests/ui/await_holding_lock.rs
  tests/ui/await_holding_lock.stderr
  tests/ui/await_holding_refcell_ref.rs
  tests/ui/await_holding_refcell_ref.stderr
  tests/ui/crashes/ice-12616.stderr
  tests/ui/ptr_as_ptr.stderr
Labels: S-waiting-on-review

#13081 Fix `iter_next_loop.rs` ui test
  tests/ui/iter_next_loop.rs
  tests/ui/iter_next_loop.stderr
Labels: S-waiting-on-review

#13086 Rustup
  clippy_lints/src/assigning_clones.rs
  clippy_lints/src/doc/mod.rs
  clippy_lints/src/empty_with_brackets.rs
  clippy_lints/src/eta_reduction.rs
  clippy_lints/src/future_not_send.rs
  clippy_lints/src/implied_bounds_in_impls.rs
  clippy_lints/src/methods/type_id_on_box.rs
  clippy_lints/src/needless_maybe_sized.rs
  clippy_lints/src/non_copy_const.rs
  clippy_lints/src/suspicious_operation_groupings.rs
  clippy_lints/src/unconditional_recursion.rs
  clippy_utils/src/ast_utils.rs
  clippy_utils/src/qualify_min_const_fn.rs
  clippy_utils/src/ty.rs
  rust-toolchain
  tests/ui/dbg_macro/dbg_macro.stderr
  tests/ui/dbg_macro/dbg_macro_unfixable.stderr
  tests/ui/manual_split_once.stderr
  tests/ui/missing_const_for_fn/could_be_const.fixed
  tests/ui/missing_const_for_fn/could_be_const.rs
  tests/ui/missing_const_for_fn/could_be_const.stderr
  tests/ui/or_fun_call.fixed
  tests/ui/or_fun_call.stderr
  tests/ui/significant_drop_tightening.stderr
Labels: S-waiting-on-review

#12656 Add 'Expand All' & 'Collapse All' to the website
  util/gh-pages/index.html
  util/gh-pages/script.js
Labels: S-waiting-on-review

#13089 Fix syntax errors in example code (clippy::cast_nan_to_int)
  clippy_lints/src/casts/mod.rs
Labels: S-waiting-on-review

#13090 [`unwrap_or_default`]: skip warning when calling inside of suggested method's implementation
  clippy_lints/src/methods/or_fun_call.rs
  tests/ui/or_fun_call.fixed
  tests/ui/or_fun_call.rs
Labels: S-waiting-on-review

#13061 Fix `manual_unwrap_or` false positive
  clippy_lints/src/matches/manual_unwrap_or.rs
  tests/ui/manual_unwrap_or.fixed
  tests/ui/manual_unwrap_or.rs
Labels: S-waiting-on-review

#13046 Refactor `checked_conversions`
  clippy_lints/src/checked_conversions.rs
Labels: S-waiting-on-review

#13093 Add more doc-valid-idents
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  tests/ui/doc/doc-fixable.fixed
  tests/ui/doc/doc-fixable.rs
  tests/ui/doc/doc-fixable.stderr
Labels: S-waiting-on-review

#13098 Bump ui_test version
  Cargo.toml
  tests/compile-test.rs
  tests/ui-toml/max_suggested_slice_pattern_length/index_refutable_slice.fixed
  tests/ui-toml/max_suggested_slice_pattern_length/index_refutable_slice.rs
  tests/ui-toml/max_suggested_slice_pattern_length/index_refutable_slice.stderr
  tests/ui/crashes/ice-3717.fixed
  tests/ui/crashes/ice-3717.rs
  tests/ui/crashes/ice-3717.stderr
  tests/ui/derivable_impls.fixed
  tests/ui/derivable_impls.rs
  tests/ui/derivable_impls.stderr
  tests/ui/index_refutable_slice/if_let_slice_binding.fixed
  tests/ui/index_refutable_slice/if_let_slice_binding.rs
  tests/ui/index_refutable_slice/if_let_slice_binding.stderr
  tests/ui/index_refutable_slice/slice_indexing_in_macro.fixed
  tests/ui/index_refutable_slice/slice_indexing_in_macro.rs
  tests/ui/index_refutable_slice/slice_indexing_in_macro.stderr
  tests/ui/let_unit.fixed
  tests/ui/let_unit.rs
  tests/ui/let_unit.stderr
  tests/ui/manual_assert.edition2018.fixed
  tests/ui/manual_assert.edition2018.stderr
  tests/ui/manual_assert.edition2021.fixed
  tests/ui/manual_assert.edition2021.stderr
  tests/ui/manual_assert.rs
  tests/ui/manual_async_fn.fixed
  tests/ui/manual_async_fn.rs
  tests/ui/manual_async_fn.stderr
  tests/ui/manual_split_once.fixed
  tests/ui/manual_split_once.rs
  tests/ui/manual_split_once.stderr
  tests/ui/match_same_arms2.fixed
  tests/ui/match_same_arms2.rs
  tests/ui/match_same_arms2.stderr
  tests/ui/significant_drop_tightening.fixed
  tests/ui/significant_drop_tightening.rs
  tests/ui/significant_drop_tightening.stderr
  tests/ui/unnecessary_iter_cloned.fixed
  tests/ui/unnecessary_iter_cloned.rs
  tests/ui/unnecessary_iter_cloned.stderr
  tests/ui/unnecessary_to_owned.fixed
  tests/ui/unnecessary_to_owned.rs
  tests/ui/unnecessary_to_owned.stderr
Labels: S-waiting-on-review

#13102 Fix `needless_option_as_deref` false-positive on struct literals
  clippy_utils/src/lib.rs
  tests/ui/needless_option_as_deref.fixed
  tests/ui/needless_option_as_deref.rs
Labels: S-waiting-on-review

#13096 fix [`excessive_precision`] suggestions on floats written in scientific notation
  clippy_utils/src/numeric_literal.rs
  tests/ui/excessive_precision.fixed
  tests/ui/excessive_precision.rs
  tests/ui/excessive_precision.stderr
Labels: S-waiting-on-review

#13100 Show progress while running dogfood test
  .cargo/config.toml
  Cargo.toml
  tests/dogfood.rs
Labels: S-waiting-on-review

#13116 Lint `zero_repeat_side_effects` only if array length is a literal zero
  clippy_lints/src/zero_repeat_side_effects.rs
  tests/ui/zero_repeat_side_effects.fixed
  tests/ui/zero_repeat_side_effects.rs
  tests/ui/zero_repeat_side_effects.stderr
Labels: S-waiting-on-review

#13117 Fix wrong suggestion for `single_element_loop` where parens were missing
  clippy_lints/src/loops/single_element_loop.rs
  tests/ui/single_element_loop.fixed
  tests/ui/single_element_loop.rs
  tests/ui/single_element_loop.stderr
Labels: S-waiting-on-review

#13104 Lintcheck: Add URL to lint emission place in diff
  lintcheck/lintcheck_crates.toml
  lintcheck/src/driver.rs
  lintcheck/src/input.rs
  lintcheck/src/json.rs
  lintcheck/src/main.rs
  lintcheck/src/output.rs
  lintcheck/src/recursive.rs
Labels: S-waiting-on-review

#13129 Add xFrednet back to Clippy's reviewer roulette
  triagebot.toml
Labels: S-waiting-on-review

#13124 Lintcheck: Update crates and expand CI testset to 200 crates
  .github/workflows/lintcheck.yml
  lintcheck/ci_crates.toml
  lintcheck/lintcheck_crates.toml
  lintcheck/src/input.rs
  lintcheck/src/main.rs
  lintcheck/src/output.rs
Labels: S-waiting-on-review

#13131 Reduce typo count.
  clippy_lints/src/matches/significant_drop_in_scrutinee.rs
  clippy_lints/src/returns.rs
  lintcheck/src/output.rs
  tests/ui/deref_addrof.fixed
  tests/ui/deref_addrof.rs
  tests/ui/missing_const_for_fn/could_be_const.fixed
  tests/ui/missing_const_for_fn/could_be_const.rs
  tests/ui/zero_repeat_side_effects.fixed
  tests/ui/zero_repeat_side_effects.rs
Labels: S-waiting-on-review

#11700 [`pathbuf_init_then_push`]: Checks for calls to `push` immediately a…
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/pathbuf_init_then_push.rs
  tests/integration.rs
  tests/ui/path_buf_push_overwrite.fixed
  tests/ui/path_buf_push_overwrite.rs
  tests/ui/path_buf_push_overwrite.stderr
  tests/ui/pathbuf_init_then_push.fixed
  tests/ui/pathbuf_init_then_push.rs
  tests/ui/pathbuf_init_then_push.stderr
  tests/ui/redundant_clone.fixed
  tests/ui/redundant_clone.rs
  tests/ui/redundant_clone.stderr
Labels: S-waiting-on-author

#13133 Lintcheck: Cleanup of Lintcheck's CI summery
  lintcheck/src/json.rs
  lintcheck/src/main.rs
  lintcheck/src/output.rs
  lintcheck/src/recursive.rs
Labels: S-waiting-on-review

#12772 add lint for recreation of an entire struct
  clippy_lints/src/unnecessary_struct_initialization.rs
  tests/ui/unnecessary_struct_initialization.fixed
  tests/ui/unnecessary_struct_initialization.rs
  tests/ui/unnecessary_struct_initialization.stderr
Labels: S-waiting-on-review

#13065 Misc refactorings part 2
  clippy_lints/src/double_parens.rs
  clippy_lints/src/endian_bytes.rs
  clippy_lints/src/excessive_bools.rs
  clippy_lints/src/extra_unused_type_parameters.rs
  clippy_lints/src/future_not_send.rs
  clippy_lints/src/if_let_mutex.rs
  clippy_lints/src/if_not_else.rs
  clippy_lints/src/if_then_some_else_none.rs
  clippy_lints/src/ignored_unit_patterns.rs
  clippy_lints/src/inconsistent_struct_constructor.rs
  clippy_lints/src/index_refutable_slice.rs
  clippy_lints/src/indexing_slicing.rs
  clippy_lints/src/infinite_iter.rs
Labels: S-waiting-on-review

#13072 Misc refactorings part 5
  clippy_lints/src/misc.rs
  clippy_lints/src/mismatching_type_param_order.rs
  clippy_lints/src/mut_mut.rs
  clippy_lints/src/needless_borrowed_ref.rs
  clippy_lints/src/needless_for_each.rs
  clippy_lints/src/neg_cmp_op_on_partial_ord.rs
  clippy_lints/src/option_env_unwrap.rs
  clippy_lints/src/permissions_set_readonly_false.rs
  clippy_lints/src/raw_strings.rs
  tests/ui/toplevel_ref_arg.fixed
  tests/ui/toplevel_ref_arg.rs
Labels: S-waiting-on-review

#13050 Misc refactorings
  clippy_lints/src/arc_with_non_send_sync.rs
  clippy_lints/src/borrow_deref_ref.rs
  clippy_lints/src/collapsible_if.rs
  clippy_lints/src/collection_is_never_read.rs
  clippy_lints/src/crate_in_macro_def.rs
  clippy_lints/src/else_if_without_else.rs
  clippy_lints/src/empty_enum.rs
  clippy_lints/src/equatable_if_let.rs
  clippy_lints/src/error_impl_error.rs
  clippy_lints/src/exhaustive_items.rs
  clippy_lints/src/exit.rs
  clippy_lints/src/float_literal.rs
  clippy_lints/src/from_over_into.rs
  clippy_lints/src/from_str_radix_10.rs
Labels: S-waiting-on-review

#13148 Lintcheck: Support underscores replacement in URL crate names
  lintcheck/src/input.rs
Labels: S-waiting-on-review

#13143 Suggest `.cast`/`.cast_const`/`.cast_mut` in `transmute_ptr_as_ptr`
  clippy_lints/src/casts/ptr_cast_constness.rs
  clippy_lints/src/transmute/mod.rs
  clippy_lints/src/transmute/transmute_ptr_to_ptr.rs
  tests/ui/ptr_cast_constness.fixed
  tests/ui/ptr_cast_constness.rs
  tests/ui/ptr_cast_constness.stderr
  tests/ui/transmute_ptr_to_ptr.fixed
  tests/ui/transmute_ptr_to_ptr.rs
  tests/ui/transmute_ptr_to_ptr.stderr
  tests/ui/transmutes_expressible_as_ptr_casts.fixed
  tests/ui/transmutes_expressible_as_ptr_casts.stderr
Labels: S-waiting-on-review

#13154 Temporarily remove myself from reviewer rotation
  triagebot.toml
Labels: S-waiting-on-review

#13151 Fix running compile-test under cargo nextest
  tests/compile-test.rs
Labels: S-waiting-on-review

#13153 Make `BindInsteadOfMap` a struct
  clippy.toml
  clippy_lints/src/methods/bind_instead_of_map.rs
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-review

#12830 Use ControlFlow in more places
  clippy_lints/src/lib.rs
  clippy_lints/src/lifetimes.rs
  clippy_lints/src/loops/mut_range_bound.rs
  clippy_lints/src/loops/while_immutable_condition.rs
  clippy_lints/src/methods/option_map_unwrap_or.rs
  clippy_lints/src/redundant_closure_call.rs
  clippy_lints/src/unconditional_recursion.rs
  clippy_lints/src/unused_peekable.rs
  clippy_utils/src/visitors.rs
Labels: S-waiting-on-review, performance-project

#13125 Changelog for Clippy 1.80 🌞
  CHANGELOG.md
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  clippy_lints/src/functions/mod.rs
Labels: S-waiting-on-review

#13157 Rustup
  Cargo.toml
  clippy_config/Cargo.toml
  clippy_lints/Cargo.toml
  clippy_lints/src/eta_reduction.rs
  clippy_lints/src/functions/must_use.rs
  clippy_lints/src/future_not_send.rs
  clippy_lints/src/inherent_impl.rs
  clippy_lints/src/large_stack_arrays.rs
  clippy_lints/src/min_ident_chars.rs
  clippy_lints/src/misc_early/mod.rs
  clippy_lints/src/no_effect.rs
  clippy_lints/src/non_copy_const.rs
  clippy_lints/src/returns.rs
  clippy_lints/src/trailing_empty_array.rs
  clippy_lints/src/trait_bounds.rs
  clippy_lints/src/types/type_complexity.rs
  clippy_lints/src/unnested_or_patterns.rs
  clippy_lints/src/utils/author.rs
  clippy_lints/src/zero_repeat_side_effects.rs
  clippy_utils/Cargo.toml
  clippy_utils/src/hir_utils.rs
  clippy_utils/src/lib.rs
  declare_clippy_lint/Cargo.toml
  rust-toolchain
  tests/ui/author/repeat.stdout
  tests/ui/track-diagnostics.stderr
Labels: S-waiting-on-review

#13156 Remove unnecessary `res` field in `for_each_expr` visitors
  clippy_utils/src/visitors.rs
Labels: S-waiting-on-review

#12892 needless_borrows_for_generic_args: Fix for &mut
  clippy_lints/src/needless_borrows_for_generic_args.rs
  tests/ui/needless_borrows_for_generic_args.fixed
  tests/ui/needless_borrows_for_generic_args.rs
Labels: S-waiting-on-review

#12473 Fix handling of `Deref` in `assigning_clones`
  clippy_lints/src/assigning_clones.rs
  tests/ui/assigning_clones.fixed
  tests/ui/assigning_clones.rs
  tests/ui/assigning_clones.stderr
Labels: S-waiting-on-author

#13144 Make restriction lint's use `span_lint_and_then` (i -> p)
  clippy_lints/src/asm_syntax.rs
  clippy_lints/src/drop_forget_ref.rs
  clippy_lints/src/float_literal.rs
  clippy_lints/src/inherent_impl.rs
  clippy_lints/src/large_include_file.rs
  clippy_lints/src/let_underscore.rs
  clippy_lints/src/methods/map_err_ignore.rs
  clippy_lints/src/missing_assert_message.rs
  clippy_lints/src/missing_trait_methods.rs
  clippy_lints/src/mixed_read_write_in_expression.rs
  clippy_lints/src/module_style.rs
  clippy_lints/src/operators/integer_division.rs
  clippy_lints/src/partial_pub_fields.rs
  clippy_lints/src/pattern_type_mismatch.rs
  clippy_lints/src/pub_use.rs
  clippy_lints/src/unicode.rs
  clippy_lints/src/visibility.rs
  tests/ui/excessive_precision.stderr
  tests/ui/lossy_float_literal.stderr
  tests/ui/needless_pub_self.stderr
Labels: S-waiting-on-review

#13164 Bump ui_test version -> 0.25
  Cargo.toml
  tests/compile-test.rs
Labels: S-waiting-on-review

#13130 Avoid ref when using format!
  clippy_lints/src/approx_const.rs
  clippy_lints/src/default.rs
  clippy_lints/src/methods/open_options.rs
  clippy_lints/src/methods/wrong_self_convention.rs
  clippy_lints/src/no_effect.rs
  clippy_lints/src/types/borrowed_box.rs
Labels: S-waiting-on-review

#13165 chore: fix some comments
  clippy_lints/src/from_str_radix_10.rs
  clippy_lints/src/loops/mod.rs
  clippy_lints/src/missing_const_for_fn.rs
  clippy_lints/src/pathbuf_init_then_push.rs
  clippy_lints/src/returns.rs
  tests/ui/unwrap_expect_used.rs
Labels: S-waiting-on-review

#13168 Make `std_instead_of_core` somewhat MSRV aware
  clippy_lints/src/lib.rs
  clippy_lints/src/std_instead_of_core.rs
  tests/ui/std_instead_of_core.fixed
  tests/ui/std_instead_of_core.rs
  tests/ui/std_instead_of_core.stderr
Labels: S-waiting-on-review, beta-nominated

#13053 Add `BTreeSet` detection to the `set_contains_or_insert` lint
  clippy_lints/src/lib.rs
  clippy_lints/src/set_contains_or_insert.rs
  tests/ui/set_contains_or_insert.rs
  tests/ui/set_contains_or_insert.stderr
Labels: S-waiting-on-review

#13149 Fix while_let_on_iterator dropping loop label when applying fix.
  clippy_lints/src/loops/while_let_on_iterator.rs
  clippy_utils/src/higher.rs
  tests/ui/while_let_on_iterator.fixed
  tests/ui/while_let_on_iterator.rs
  tests/ui/while_let_on_iterator.stderr
Labels: S-waiting-on-review

#13159 `missing_trait_methods`: lint methods in definition order
  clippy_lints/src/missing_trait_methods.rs
  tests/ui/missing_trait_methods.rs
  tests/ui/missing_trait_methods.stderr
Labels: S-waiting-on-review

#13166 Fix display of configs in clippy doc page
  clippy_config/src/metadata.rs
  clippy_lints/src/utils/internal_lints/metadata_collector.rs
Labels: S-waiting-on-review

#13176 Fix fix under loop may dropping loop label when applying fix.
  clippy_lints/src/loops/explicit_counter_loop.rs
  clippy_lints/src/loops/mod.rs
  clippy_utils/src/higher.rs
  tests/ui/explicit_counter_loop.rs
  tests/ui/explicit_counter_loop.stderr
  tests/ui/for_kv_map.fixed
  tests/ui/for_kv_map.rs
  tests/ui/for_kv_map.stderr
Labels: S-waiting-on-review

#13173 Misc changes to `clippy_config`
  book/src/lint_configuration.md
  clippy_config/Cargo.toml
  clippy_config/src/conf.rs
  clippy_config/src/lib.rs
  clippy_config/src/metadata.rs
  clippy_dev/src/fmt.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/utils/internal_lints/metadata_collector.rs
Labels: S-waiting-on-review

#13179 Clean up clippy lints page JS source code
  util/gh-pages/script.js
Labels: S-waiting-on-review

#13174 Emit `if_let_mutex` in presence of other mutexes
  clippy_lints/src/if_let_mutex.rs
  tests/ui/if_let_mutex.rs
  tests/ui/if_let_mutex.stderr
Labels: S-waiting-on-review

#13178 Add possibility to focus on search input using keyboard
  util/gh-pages/index.html
  util/gh-pages/script.js
Labels: S-waiting-on-review

#13182 Remove some miscellaneous `#[allow]`s
  clippy_dev/src/serve.rs
  clippy_lints/src/incompatible_msrv.rs
  clippy_lints/src/indexing_slicing.rs
  clippy_lints/src/infinite_iter.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/methods/iter_kv_map.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/only_used_in_recursion.rs
  clippy_utils/src/lib.rs
Labels: S-waiting-on-review

#13177 Fix broken list for lints config
  clippy_config/src/metadata.rs
  clippy_lints/src/utils/internal_lints/metadata_collector.rs
Labels: S-waiting-on-review

#13195 Fix false positive for `missing_backticks` in footnote references
  clippy_lints/src/doc/mod.rs
  tests/ui/doc/footnote_issue_13183.rs
Labels: S-waiting-on-review
