Repository rust-lang/rust-clippy, pull requests merged in 2024-06, with the labels that each got.

#12868 chore: fix some comments
  tests/ui/double_neg.rs
  tests/ui/infinite_loops.rs
  tests/ui/iter_over_hash_type.rs
Labels: S-waiting-on-review

#12871 Modify str_to_string to be machine-applicable
  clippy_lints/src/strings.rs
  tests/ui/str_to_string.fixed
  tests/ui/str_to_string.stderr
Labels: S-waiting-on-review

#12815 Add `needless_character_iteration` lint
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/needless_character_iteration.rs
  clippy_lints/src/methods/unnecessary_result_map_or_else.rs
  clippy_lints/src/methods/utils.rs
  tests/ui/needless_character_iteration.fixed
  tests/ui/needless_character_iteration.rs
  tests/ui/needless_character_iteration.stderr
Labels: S-waiting-on-review

#12875 Deprecate `maybe_misused_cfg` and `mismatched_target_os`
  clippy_lints/src/attrs/maybe_misused_cfg.rs
  clippy_lints/src/attrs/mismatched_target_os.rs
  clippy_lints/src/attrs/mod.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/deprecated_lints.rs
  clippy_lints/src/lib.deprecated.rs
  tests/ui/cfg_features.fixed
  tests/ui/cfg_features.rs
  tests/ui/cfg_features.stderr
  tests/ui/deprecated.rs
  tests/ui/deprecated.stderr
  tests/ui/mismatched_target_os_non_unix.fixed
  tests/ui/mismatched_target_os_non_unix.rs
  tests/ui/mismatched_target_os_non_unix.stderr
  tests/ui/mismatched_target_os_unix.fixed
  tests/ui/mismatched_target_os_unix.rs
  tests/ui/mismatched_target_os_unix.stderr
  tests/ui/unnecessary_clippy_cfg.rs
  tests/ui/unnecessary_clippy_cfg.stderr
Labels: S-waiting-on-review

#12885 Using Clippy as a proper noun when refering to the unique entity Clippy
  README.md
  book/src/configuration.md
  book/src/development/basics.md
  book/src/development/defining_lints.md
  book/src/development/proposals/syntax-tree-patterns.md
  clippy_dummy/PUBLISH.md
  clippy_dummy/crates-readme.md
  lintcheck/README.md
Labels: S-waiting-on-review

#12884 Only run `suboptimal_flops` on inherent method calls
  clippy_lints/src/floating_point_arithmetic.rs
  clippy_utils/src/lib.rs
  tests/ui/floating_point_log.fixed
  tests/ui/floating_point_log.rs
Labels: S-waiting-on-review

#12886 Fix false positive for `needless_character_iteration` lint
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/needless_character_iteration.rs
  tests/ui/needless_character_iteration.fixed
  tests/ui/needless_character_iteration.rs
  tests/ui/needless_character_iteration.stderr
Labels: S-waiting-on-review

#12700 [`overly_complex_bool_expr`]: Fix trigger wrongly on never type
  clippy_lints/src/booleans.rs
  tests/ui/overly_complex_bool_expr.fixed
  tests/ui/overly_complex_bool_expr.rs
Labels: S-waiting-on-review

#10632 Add `needless_maybe_sized` lint
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/needless_maybe_sized.rs
  tests/ui-toml/type_repetition_in_bounds/main.rs
  tests/ui-toml/type_repetition_in_bounds/main.stderr
  tests/ui/auxiliary/proc_macros.rs
  tests/ui/needless_maybe_sized.fixed
  tests/ui/needless_maybe_sized.rs
  tests/ui/needless_maybe_sized.stderr
  tests/ui/type_repetition_in_bounds.rs
  tests/ui/type_repetition_in_bounds.stderr
Labels: S-waiting-on-review

#12827 `lint_groups_priority`: ignore lints & groups at the same level
  clippy_lints/src/cargo/lint_groups_priority.rs
  tests/ui-cargo/lint_groups_priority/fail/Cargo.stderr
  tests/ui-cargo/lint_groups_priority/fail/Cargo.toml
  tests/ui-cargo/lint_groups_priority/pass/Cargo.toml
Labels: S-waiting-on-review

#12897 Lint `manual_unwrap_or_default` for Result as well
  clippy_lints/src/manual_unwrap_or_default.rs
  tests/ui/manual_unwrap_or_default.fixed
  tests/ui/manual_unwrap_or_default.rs
  tests/ui/manual_unwrap_or_default.stderr
  tests/ui/useless_conversion_try.rs
  tests/ui/useless_conversion_try.stderr
Labels: S-waiting-on-review

#12877 Handle const effects inherited from parent correctly in `type_certainty`
  clippy_utils/src/ty/type_certainty/mod.rs
  tests/ui/or_fun_call.fixed
  tests/ui/or_fun_call.rs
Labels: S-waiting-on-review

#12822 Make `for_each_expr` visit closures by default, rename the old version `for_each_expr_without_closures`
  clippy_lints/src/blocks_in_conditions.rs
  clippy_lints/src/casts/cast_sign_loss.rs
  clippy_lints/src/casts/unnecessary_cast.rs
  clippy_lints/src/cognitive_complexity.rs
  clippy_lints/src/collection_is_never_read.rs
  clippy_lints/src/copies.rs
  clippy_lints/src/functions/must_use.rs
  clippy_lints/src/functions/not_unsafe_ptr_arg_deref.rs
  clippy_lints/src/implicit_return.rs
  clippy_lints/src/matches/redundant_guards.rs
  clippy_lints/src/matches/redundant_pattern_match.rs
  clippy_lints/src/methods/collapsible_str_replace.rs
  clippy_lints/src/methods/str_splitn.rs
  clippy_lints/src/methods/unnecessary_filter_map.rs
  clippy_lints/src/methods/unnecessary_iter_cloned.rs
  clippy_lints/src/missing_asserts_for_indexing.rs
  clippy_lints/src/missing_fields_in_debug.rs
  clippy_lints/src/multiple_unsafe_ops_per_block.rs
  clippy_lints/src/needless_late_init.rs
  clippy_lints/src/needless_pass_by_ref_mut.rs
  clippy_lints/src/operators/assign_op_pattern.rs
  clippy_lints/src/panic_in_result_fn.rs
  clippy_lints/src/redundant_async_block.rs
  clippy_lints/src/returns.rs
  clippy_lints/src/suspicious_trait_impl.rs
  clippy_lints/src/undocumented_unsafe_blocks.rs
  clippy_lints/src/unused_self.rs
  clippy_lints/src/unwrap_in_result.rs
  clippy_lints/src/zero_repeat_side_effects.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/macros.rs
  clippy_utils/src/ptr.rs
  clippy_utils/src/usage.rs
  clippy_utils/src/visitors.rs
  tests/ui/missing_fields_in_debug.rs
  tests/ui/missing_fields_in_debug.stderr
  tests/ui/panic_in_result_fn.rs
  tests/ui/panic_in_result_fn.stderr
  tests/ui/unwrap_in_result.rs
  tests/ui/unwrap_in_result.stderr
Labels: S-waiting-on-review

#12844 Fix `to_string_in_format_args` with macro call receiver
  clippy_lints/src/format_args.rs
  tests/ui/format_args.fixed
  tests/ui/format_args.rs
  tests/ui/format_args.stderr
Labels: S-waiting-on-review

#12889 Changelog for Clippy 1.79 🎓
  CHANGELOG.md
  clippy_lints/src/attrs/mod.rs
  clippy_lints/src/integer_division_remainder_used.rs
  clippy_lints/src/legacy_numeric_constants.rs
  clippy_lints/src/manual_unwrap_or_default.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/transmute/mod.rs
  clippy_lints/src/zero_repeat_side_effects.rs
Labels: S-waiting-on-review

#12901 [`match_same_arms`]: add a test case with lifetimes
  tests/ui/match_same_arms2.fixed
  tests/ui/match_same_arms2.rs
  tests/ui/match_same_arms2.stderr
Labels: S-waiting-on-review

#12851 Add required parentheses around method receiver
  clippy_lints/src/methods/search_is_some.rs
  clippy_lints/src/needless_bool.rs
  clippy_utils/src/lib.rs
  tests/ui/needless_bool/fixable.fixed
  tests/ui/needless_bool/fixable.rs
  tests/ui/needless_bool/fixable.stderr
Labels: S-waiting-on-review

#12900 Remove `lazy_static` mention
  clippy_lints/src/non_copy_const.rs
  tests/ui/crashes/ice-9445.rs
  tests/ui/crashes/ice-9445.stderr
  tests/ui/crashes/mut_mut_macro.rs
  tests/ui/declare_interior_mutable_const/enums.stderr
  tests/ui/declare_interior_mutable_const/others.stderr
  tests/ui/declare_interior_mutable_const/traits.stderr
Labels: S-waiting-on-review

#12805 Don't lint blocks in closures for blocks_in_conditions
  clippy_lints/src/blocks_in_conditions.rs
  tests/ui/blocks_in_conditions.fixed
  tests/ui/blocks_in_conditions.rs
  tests/ui/blocks_in_conditions_closure.rs
  tests/ui/blocks_in_conditions_closure.stderr
Labels: S-waiting-on-review

#12904 Normalize type aliases when checking significant drops.
  clippy_lints/src/significant_drop_tightening.rs
Labels: S-waiting-on-review

#12913 Filter from first typed symbol on gh-pages
  util/gh-pages/script.js
Labels: S-waiting-on-review

#12915 Handle single chars with `to_string()` for `single_char_add_str`
  clippy_lints/src/methods/single_char_insert_string.rs
  clippy_lints/src/methods/single_char_push_string.rs
  tests/ui/single_char_add_str.fixed
  tests/ui/single_char_add_str.rs
  tests/ui/single_char_add_str.stderr
Labels: S-waiting-on-review

#12912 Don't lint indexing_slicing lints on proc macros
  clippy_lints/src/indexing_slicing.rs
  tests/ui/indexing_slicing_index.rs
  tests/ui/indexing_slicing_index.stderr
  tests/ui/indexing_slicing_slice.rs
  tests/ui/indexing_slicing_slice.stderr
Labels: S-waiting-on-review

#12849 Add lint to check manual pattern char comparison
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/float_literal.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/path_buf_push_overwrite.rs
  clippy_lints/src/methods/single_char_insert_string.rs
  clippy_lints/src/methods/single_char_pattern.rs
  clippy_lints/src/methods/single_char_push_string.rs
  clippy_lints/src/methods/utils.rs
  clippy_lints/src/misc_early/zero_prefixed_literal.rs
  clippy_lints/src/string_patterns.rs
  clippy_utils/src/source.rs
  tests/ui/manual_pattern_char_comparison.fixed
  tests/ui/manual_pattern_char_comparison.rs
  tests/ui/manual_pattern_char_comparison.stderr
  tests/ui/search_is_some.rs
  tests/ui/search_is_some.stderr
Labels: S-final-comment-period

#12681 Let `qualify_min_const_fn` deal with drop terminators
  clippy_lints/src/missing_const_for_fn.rs
  clippy_utils/src/qualify_min_const_fn.rs
  tests/ui/missing_const_for_fn/could_be_const.rs
  tests/ui/missing_const_for_fn/could_be_const.stderr
Labels: S-waiting-on-review

#12855 Fix typos of author lint
  clippy_lints/src/utils/author.rs
  tests/ui/author.stdout
  tests/ui/author/blocks.stdout
  tests/ui/author/call.stdout
  tests/ui/author/if.stdout
  tests/ui/author/issue_3849.stdout
  tests/ui/author/loop.stdout
  tests/ui/author/macro_in_closure.stdout
  tests/ui/author/matches.stdout
Labels: S-waiting-on-review

#12921 Rustup
  Cargo.toml
  clippy_config/Cargo.toml
  clippy_lints/Cargo.toml
  clippy_lints/src/default_numeric_fallback.rs
  clippy_lints/src/dereference.rs
  clippy_lints/src/doc/needless_doctest_main.rs
  clippy_lints/src/eta_reduction.rs
  clippy_lints/src/future_not_send.rs
  clippy_lints/src/implicit_hasher.rs
  clippy_lints/src/implied_bounds_in_impls.rs
  clippy_lints/src/large_const_arrays.rs
  clippy_lints/src/large_stack_arrays.rs
  clippy_lints/src/len_zero.rs
  clippy_lints/src/macro_metavars_in_unsafe.rs
  clippy_lints/src/manual_async_fn.rs
  clippy_lints/src/matches/overlapping_arms.rs
  clippy_lints/src/methods/iter_on_single_or_empty_collections.rs
  clippy_lints/src/methods/option_map_unwrap_or.rs
  clippy_lints/src/needless_borrows_for_generic_args.rs
  clippy_lints/src/non_copy_const.rs
  clippy_lints/src/only_used_in_recursion.rs
  clippy_lints/src/operators/mod.rs
  clippy_lints/src/ptr.rs
  clippy_lints/src/question_mark.rs
  clippy_lints/src/single_call_fn.rs
  clippy_lints/src/transmute/missing_transmute_annotations.rs
  clippy_lints/src/unconditional_recursion.rs
  clippy_lints/src/unit_return_expecting_ord.rs
  clippy_lints/src/utils/author.rs
  clippy_lints/src/utils/internal_lints/lint_without_lint_pass.rs
  clippy_lints/src/utils/internal_lints/metadata_collector.rs
  clippy_lints/src/zero_repeat_side_effects.rs
  clippy_utils/Cargo.toml
  clippy_utils/src/ast_utils.rs
  clippy_utils/src/consts.rs
  clippy_utils/src/hir_utils.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/ty.rs
  declare_clippy_lint/Cargo.toml
  rust-toolchain
  tests/ui/arithmetic_side_effects.stderr
  tests/ui/cfg_attr_rustfmt.fixed
  tests/ui/cfg_attr_rustfmt.rs
  tests/ui/std_instead_of_core.fixed
  tests/ui/std_instead_of_core.rs
  tests/ui/std_instead_of_core.stderr
  tests/ui/tabs_in_doc_comments.stderr
  tests/ui/unicode.stderr
Labels: S-waiting-on-review

#12880 Fix doc nits
  clippy_lints/src/allow_attributes.rs
  clippy_lints/src/arc_with_non_send_sync.rs
  clippy_lints/src/attrs/mod.rs
  clippy_lints/src/loops/mod.rs
  clippy_lints/src/needless_for_each.rs
Labels: S-waiting-on-review

#12756 Avoid emitting `assigning_clones` when cloned data borrows from the place to clone into
  clippy_lints/src/assigning_clones.rs
  clippy_utils/src/mir/possible_borrower.rs
  tests/ui/assigning_clones.fixed
  tests/ui/assigning_clones.rs
Labels: S-waiting-on-review

#12937 Add MSRV for manual_pattern_char_comparison
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/string_patterns.rs
  tests/ui/manual_pattern_char_comparison.fixed
  tests/ui/manual_pattern_char_comparison.rs
  tests/ui/manual_pattern_char_comparison.stderr
Labels: S-waiting-on-review

#10398 Run a diff of lintcheck against the merge base for pull requests
  .github/workflows/lintcheck.yml
  lintcheck/Cargo.toml
  lintcheck/src/config.rs
  lintcheck/src/json.rs
  lintcheck/src/main.rs
Labels: S-waiting-on-review

#12939 Merge lintcheck popular-crates bin as a subcommand
  lintcheck/Cargo.toml
  lintcheck/README.md
  lintcheck/src/config.rs
  lintcheck/src/main.rs
  lintcheck/src/popular-crates.rs
  lintcheck/src/popular_crates.rs
Labels: S-waiting-on-review

#12893 Add field_scoped_visibility_modifiers lint
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/field_scoped_visibility_modifiers.rs
  clippy_lints/src/lib.rs
  tests/ui/field_scoped_visibility_modifiers.rs
  tests/ui/field_scoped_visibility_modifiers.stderr
Labels: S-waiting-on-review

#12287 Add lint `manual_inspect`
  CHANGELOG.md
  clippy_config/src/msrvs.rs
  clippy_lints/src/casts/ref_as_ptr.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/dereference.rs
  clippy_lints/src/methods/manual_inspect.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/needless_borrows_for_generic_args.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/source.rs
  clippy_utils/src/ty.rs
  tests/ui/copy_iterator.rs
  tests/ui/copy_iterator.stderr
  tests/ui/manual_inspect.fixed
  tests/ui/manual_inspect.rs
  tests/ui/manual_inspect.stderr
Labels: S-waiting-on-author

#12938 Fix minor typo
  book/src/usage.md
Labels: S-waiting-on-review

#12943 Use symbols when raising range expressions.
  clippy_utils/src/higher.rs
Labels: S-waiting-on-review

#12947 Pause assignments to @xFrednet for summer break :beach_umbrella:
  triagebot.toml
Labels: S-waiting-on-review

#12903 Fix ICE in `upper_case_acronyms`
  clippy_lints/src/upper_case_acronyms.rs
  tests/ui/crashes/ice-12284.rs
Labels: S-waiting-on-review

#12945 Rework `octal_escapes`
  clippy_lints/src/octal_escapes.rs
  tests/ui/octal_escapes.rs
  tests/ui/octal_escapes.stderr
Labels: S-waiting-on-review

#12906 Lint `manual_unwrap_or` for it let cases
  clippy_lints/src/matches/manual_unwrap_or.rs
  clippy_lints/src/matches/mod.rs
  tests/ui/manual_unwrap_or.fixed
  tests/ui/manual_unwrap_or.rs
  tests/ui/manual_unwrap_or.stderr
  tests/ui/manual_unwrap_or_default.fixed
  tests/ui/manual_unwrap_or_default.rs
  tests/ui/match_result_ok.fixed
  tests/ui/match_result_ok.rs
  tests/ui/match_result_ok.stderr
  tests/ui/option_if_let_else.fixed
  tests/ui/option_if_let_else.rs
  tests/ui/option_if_let_else.stderr
Labels: S-waiting-on-review

#12953 Add myself back to reviewer rotation
  triagebot.toml
Labels: S-waiting-on-review

#12655 Add applicability filter to lint list page
  util/gh-pages/index.html
  util/gh-pages/script.js
Labels: S-waiting-on-review

#12942 Add more types to `is_from_proc_macro`
  clippy_lints/src/allow_attributes.rs
  clippy_lints/src/attrs/allow_attributes_without_reason.rs
  clippy_utils/src/check_proc_macro.rs
Labels: S-waiting-on-review

#12963 Don't lint `implicit_return` on proc macros
  clippy_lints/src/implicit_return.rs
  tests/ui/implicit_return.fixed
  tests/ui/implicit_return.rs
  tests/ui/implicit_return.stderr
Labels: S-waiting-on-review

#12368 Unnecessary call to min/max method
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/unnecessary_min_or_max.rs
  clippy_utils/src/consts.rs
  tests/ui/auxiliary/external_consts.rs
  tests/ui/cast.rs
  tests/ui/cast.stderr
  tests/ui/unnecessary_min_or_max.fixed
  tests/ui/unnecessary_min_or_max.rs
  tests/ui/unnecessary_min_or_max.stderr
Labels: S-final-comment-period

#12972 Add new span related utils
  clippy_lints/src/cognitive_complexity.rs
  clippy_lints/src/copies.rs
  clippy_lints/src/implicit_hasher.rs
  clippy_lints/src/matches/single_match.rs
  clippy_lints/src/methods/manual_inspect.rs
  clippy_lints/src/missing_doc.rs
  clippy_lints/src/multiple_bound_locations.rs
  clippy_lints/src/needless_else.rs
  clippy_lints/src/needless_if.rs
  clippy_lints/src/non_octal_unix_permissions.rs
  clippy_lints/src/octal_escapes.rs
  clippy_lints/src/ranges.rs
  clippy_utils/src/consts.rs
  clippy_utils/src/hir_utils.rs
  clippy_utils/src/source.rs
Labels: S-waiting-on-review

#12961 Fix incorrect suggestion for `manual_unwrap_or_default`
  clippy_lints/src/manual_unwrap_or_default.rs
  tests/ui/manual_unwrap_or_default.fixed
  tests/ui/manual_unwrap_or_default.rs
Labels: S-waiting-on-review

#12965 resolve `clippy::invalid_paths` on `bool::then`
  clippy_lints/src/utils/internal_lints/invalid_paths.rs
  clippy_utils/src/paths.rs
Labels: S-waiting-on-review

#12985 use short message format in integration test
  tests/integration.rs
Labels: S-waiting-on-review

#12930 [`missing_const_for_fn`]: add machine-applicable suggestion
  clippy_lints/src/missing_const_for_fn.rs
  tests/ui/missing_const_for_fn/could_be_const.fixed
  tests/ui/missing_const_for_fn/could_be_const.stderr
Labels: S-waiting-on-review

#12986 Cache lintcheck binary in ci
  .github/workflows/lintcheck.yml
  lintcheck/src/main.rs
Labels: S-waiting-on-review

#12995 Fix doc_markdown DevOps false positive
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
Labels: S-waiting-on-review

#12992 bump strip-ansi-escapes
  lintcheck/Cargo.toml
  lintcheck/src/main.rs
Labels: S-waiting-on-review

#13002 doc_lazy_continuation: blank comment line for gap
  clippy_lints/src/doc/lazy_continuation.rs
  clippy_lints/src/doc/mod.rs
  tests/ui/doc/doc_lazy_blank_line.fixed
  tests/ui/doc/doc_lazy_blank_line.rs
  tests/ui/doc/doc_lazy_blank_line.stderr
  tests/ui/doc/doc_lazy_blockquote.fixed
  tests/ui/doc/doc_lazy_blockquote.rs
  tests/ui/doc/doc_lazy_blockquote.stderr
  tests/ui/doc/doc_lazy_list.fixed
  tests/ui/doc/doc_lazy_list.rs
  tests/ui/doc/doc_lazy_list.stderr
Labels: S-waiting-on-review

#13006 Add error message to manual_inspect lint
  clippy_lints/src/methods/manual_inspect.rs
  tests/ui/manual_inspect.stderr
Labels: S-waiting-on-review
