Repository rust-lang/rust-clippy, pull requests merged in 2024-03, with the labels that each got.

#12276 Fix FP in `threadlocal!` when falling back to `os_local`
  clippy_lints/src/thread_local_initializer_can_be_made_const.rs
  tests/ui/thread_local_initializer_can_be_made_const.fixed
  tests/ui/thread_local_initializer_can_be_made_const.rs
  tests/ui/thread_local_initializer_can_be_made_const.stderr
Labels: S-waiting-on-review, beta-nominated

#12010 fix: `manual_memcpy` wrong indexing for multi dimensional arrays
  clippy_lints/src/loops/manual_memcpy.rs
  tests/ui/manual_memcpy/without_loop_counters.rs
  tests/ui/manual_memcpy/without_loop_counters.stderr
Labels: S-waiting-on-review

#12218 Document manifest options
  src/main.rs
Labels: S-waiting-on-review

#12394 Refactor lints in clippy_lints::attrs into separate submodules/files
  clippy_lints/src/attrs.rs
  clippy_lints/src/attrs/allow_attributes_without_reason.rs
  clippy_lints/src/attrs/blanket_clippy_restriction_lints.rs
  clippy_lints/src/attrs/deprecated_cfg_attr.rs
  clippy_lints/src/attrs/deprecated_semver.rs
  clippy_lints/src/attrs/empty_line_after.rs
  clippy_lints/src/attrs/inline_always.rs
  clippy_lints/src/attrs/maybe_misused_cfg.rs
  clippy_lints/src/attrs/mismatched_target_os.rs
  clippy_lints/src/attrs/mixed_attributes_style.rs
  clippy_lints/src/attrs/mod.rs
  clippy_lints/src/attrs/non_minimal_cfg.rs
  clippy_lints/src/attrs/should_panic_without_expect.rs
  clippy_lints/src/attrs/unnecessary_clippy_cfg.rs
  clippy_lints/src/attrs/useless_attribute.rs
  clippy_lints/src/attrs/utils.rs
Labels: S-waiting-on-review

#12400 [`let_underscore_untyped`]: fix false positive on async function
  clippy_lints/src/let_underscore.rs
  tests/ui/let_underscore_untyped.rs
Labels: S-waiting-on-review

#12406 Dedup std_instead_of_core by using first segment span for uniqueness
  clippy_lints/src/std_instead_of_core.rs
  tests/ui/std_instead_of_core.fixed
  tests/ui/std_instead_of_core.rs
  tests/ui/std_instead_of_core.stderr
Labels: S-waiting-on-review

#12405 Added msrv to threadlocal initializer check
  clippy_config/src/msrvs.rs
  clippy_lints/src/thread_local_initializer_can_be_made_const.rs
  tests/ui/thread_local_initializer_can_be_made_const.fixed
  tests/ui/thread_local_initializer_can_be_made_const.rs
Labels: S-waiting-on-review

#12403 Pointers cannot be converted to integers at compile time
  clippy_lints/src/transmute/mod.rs
  clippy_lints/src/transmute/transmutes_expressible_as_ptr_casts.rs
  tests/ui/transmutes_expressible_as_ptr_casts.fixed
  tests/ui/transmutes_expressible_as_ptr_casts.rs
Labels: S-waiting-on-review

#12393 fix [`derive_partial_eq_without_eq`] FP on trait projection
  clippy_lints/src/derive.rs
  tests/ui/derive_partial_eq_without_eq.fixed
  tests/ui/derive_partial_eq_without_eq.rs
  tests/ui/derive_partial_eq_without_eq.stderr
Labels: S-waiting-on-review

#12341 Check for try blocks in `question_mark` more consistently
  clippy_lints/src/question_mark.rs
  tests/ui/manual_let_else.rs
  tests/ui/manual_let_else.stderr
  tests/ui/question_mark.fixed
  tests/ui/question_mark.rs
Labels: S-waiting-on-review

#12409 [`identity_op`]: Fix duplicate diagnostics
  clippy_lints/src/operators/identity_op.rs
  tests/ui/identity_op.fixed
  tests/ui/identity_op.rs
  tests/ui/identity_op.stderr
Labels: S-waiting-on-review

#12416 Add missing header for `manual_is_variant_and`
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-review

#12288 Add documentation on trait checking and type construction
  book/src/development/trait_checking.md
  book/src/development/type_checking.md
Labels: S-waiting-on-review

#12419 Handle plural acronyms in `doc_markdown`
  clippy_lints/src/doc/markdown.rs
  tests/ui/doc/doc-fixable.fixed
  tests/ui/doc/doc-fixable.rs
  tests/ui/doc/doc-fixable.stderr
Labels: S-waiting-on-review

#12423 Don't emit "missing backticks" lint if the element is wrapped in `<code>` HTML tags
  clippy_lints/src/doc/markdown.rs
  clippy_lints/src/doc/mod.rs
  tests/ui/doc/issue_9473.fixed
  tests/ui/doc/issue_9473.rs
  tests/ui/doc/issue_9473.stderr
Labels: S-waiting-on-review

#12413 [`misrefactored_assign_op`]: Fix duplicate diagnostics
  clippy_lints/src/operators/misrefactored_assign_op.rs
  tests/ui/assign_ops2.rs
  tests/ui/assign_ops2.stderr
Labels: S-waiting-on-review

#12077 Add `assigning_clones` lint
  CHANGELOG.md
  clippy_lints/src/assigning_clones.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_utils/src/sugg.rs
  tests/missing-test-files.rs
  tests/ui/assigning_clones.fixed
  tests/ui/assigning_clones.rs
  tests/ui/assigning_clones.stderr
  tests/ui/field_reassign_with_default.rs
  tests/ui/field_reassign_with_default.stderr
  tests/ui/manual_memcpy/without_loop_counters.rs
  tests/ui/manual_memcpy/without_loop_counters.stderr
  tests/ui/non_canonical_clone_impl.fixed
  tests/ui/non_canonical_clone_impl.rs
  tests/ui/non_canonical_clone_impl.stderr
Labels: S-waiting-on-review

#12401 Remove double expr lint
  clippy_lints/src/booleans.rs
  tests/ui/nonminimal_bool.rs
  tests/ui/nonminimal_bool.stderr
Labels: S-waiting-on-review

#12429 Don't lint `redundant_field_names` across macro boundaries
  clippy_lints/src/redundant_field_names.rs
  tests/ui/redundant_field_names.fixed
  tests/ui/redundant_field_names.rs
  tests/ui/redundant_field_names.stderr
Labels: S-waiting-on-review

#12310 New lint `const_is_empty`
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/methods/is_empty.rs
  clippy_lints/src/methods/mod.rs
  clippy_utils/src/consts.rs
  tests/ui/bool_assert_comparison.fixed
  tests/ui/bool_assert_comparison.rs
  tests/ui/const_is_empty.rs
  tests/ui/const_is_empty.stderr
  tests/ui/len_zero.fixed
  tests/ui/len_zero.rs
  tests/ui/len_zero.stderr
  tests/ui/needless_bitwise_bool.fixed
  tests/ui/needless_bitwise_bool.rs
  tests/ui/needless_bitwise_bool.stderr
  tests/ui/redundant_as_str.fixed
  tests/ui/redundant_as_str.rs
  tests/ui/redundant_as_str.stderr
Labels: S-waiting-on-review

#12443 [`no_effect_replace`]: Fix duplicate diagnostics
  clippy_lints/src/methods/no_effect_replace.rs
  tests/ui/no_effect_replace.rs
  tests/ui/no_effect_replace.stderr
Labels: S-waiting-on-review

#12442 [`mut_mut`]: Fix duplicate diags
  clippy_lints/src/mut_mut.rs
  tests/ui/mut_mut.rs
  tests/ui/mut_mut.stderr
Labels: S-waiting-on-review

#12446 use `span_lint_hir` instead of `span_lint` in more lints
  clippy_lints/src/let_if_seq.rs
  clippy_lints/src/mut_mut.rs
  clippy_lints/src/read_zero_byte_vec.rs
  clippy_lints/src/redundant_closure_call.rs
  clippy_lints/src/returns.rs
  clippy_lints/src/unused_io_amount.rs
  clippy_lints/src/unused_peekable.rs
  tests/ui/let_if_seq.rs
  tests/ui/let_if_seq.stderr
  tests/ui/mut_mut.rs
  tests/ui/needless_return.fixed
  tests/ui/needless_return.rs
  tests/ui/read_zero_byte_vec.rs
  tests/ui/unused_io_amount.rs
  tests/ui/unused_peekable.rs
Labels: S-waiting-on-review

#12449 Add new lint `zero_repeat_side_effects`
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/zero_repeat_side_effects.rs
  tests/ui/zero_repeat_side_effects.fixed
  tests/ui/zero_repeat_side_effects.rs
  tests/ui/zero_repeat_side_effects.stderr
Labels: S-waiting-on-review

#12447 Fix #12438 std_instead_of_core regression
  clippy_lints/src/std_instead_of_core.rs
  tests/ui/std_instead_of_core.fixed
  tests/ui/std_instead_of_core.stderr
Labels: S-waiting-on-review

#12440 Add new `manual_unwrap_or_default` lint
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_unwrap_or_default.rs
  tests/ui/manual_let_else.rs
  tests/ui/manual_let_else.stderr
  tests/ui/manual_unwrap_or.fixed
  tests/ui/manual_unwrap_or.rs
  tests/ui/manual_unwrap_or.stderr
  tests/ui/manual_unwrap_or_default.fixed
  tests/ui/manual_unwrap_or_default.rs
  tests/ui/manual_unwrap_or_default.stderr
  tests/ui/match_result_ok.fixed
  tests/ui/match_result_ok.rs
  tests/ui/option_if_let_else.fixed
  tests/ui/option_if_let_else.rs
  tests/ui/option_if_let_else.stderr
  tests/ui/option_option.rs
  tests/ui/single_match.fixed
  tests/ui/single_match.rs
  tests/ui/single_match.stderr
Labels: S-waiting-on-review

#12445 add documentation to the `span_lint_hir` functions
  clippy.toml
  clippy_utils/src/diagnostics.rs
  tests/ui-internal/disallow_span_lint.stderr
Labels: S-waiting-on-review

#12458 [`seek_from_current`]: readability improvements
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-review

#12448 [`single_match`]: Fix duplicate diagnostics
  clippy_lints/src/matches/single_match.rs
  tests/ui/single_match.fixed
  tests/ui/single_match.rs
  tests/ui/single_match.stderr
  tests/ui/single_match_else.fixed
  tests/ui/single_match_else.rs
  tests/ui/single_match_else.stderr
Labels: S-waiting-on-review

#12378 Add new `duplicated_attributes` lint
  CHANGELOG.md
  clippy_dev/src/update_lints.rs
  clippy_lints/src/attrs/duplicated_attributes.rs
  clippy_lints/src/attrs/mod.rs
  clippy_lints/src/declared_lints.rs
  tests/ui/allow_attributes_without_reason.rs
  tests/ui/allow_attributes_without_reason.stderr
  tests/ui/duplicated_attributes.rs
  tests/ui/duplicated_attributes.stderr
  tests/ui/empty_line_after_doc_comments.rs
  tests/ui/empty_line_after_outer_attribute.rs
  tests/ui/mixed_attributes_style.rs
  tests/ui/mixed_attributes_style.stderr
  tests/ui/rename.fixed
  tests/ui/rename.rs
  tests/ui/rename.stderr
Labels: S-waiting-on-review

#12452 [`manual_retain`]: Fix duplicate diagnostics
  clippy_lints/src/manual_retain.rs
  tests/ui/manual_retain.fixed
  tests/ui/manual_retain.rs
  tests/ui/manual_retain.stderr
Labels: S-waiting-on-review

#12469 chore: fix some typos
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/wildcard_imports.rs
Labels: S-waiting-on-review

#11287 [`cast_lossless`]: Suggest type alias instead of the aliased type
  clippy_lints/src/casts/cast_lossless.rs
  clippy_lints/src/casts/mod.rs
  tests/ui/cast_lossless_bool.fixed
  tests/ui/cast_lossless_bool.rs
  tests/ui/cast_lossless_bool.stderr
  tests/ui/cast_lossless_float.fixed
  tests/ui/cast_lossless_float.rs
  tests/ui/cast_lossless_float.stderr
  tests/ui/cast_lossless_integer.fixed
  tests/ui/cast_lossless_integer.rs
  tests/ui/cast_lossless_integer.stderr
Labels: S-waiting-on-review

#12466 fix [`empty_docs`] trigger in proc-macro
  clippy_lints/src/doc/mod.rs
  tests/ui/auxiliary/proc_macro_attr.rs
  tests/ui/empty_docs.rs
  tests/ui/empty_docs.stderr
Labels: S-waiting-on-review

#12459 lint when calling the blanket `Into` impl from a `From` impl
  clippy_lints/src/unconditional_recursion.rs
  clippy_utils/src/lib.rs
  tests/ui/unconditional_recursion.rs
  tests/ui/unconditional_recursion.stderr
Labels: S-waiting-on-review

#12470 filetime::FileTime::now() is new in 0.2.9
  Cargo.toml
Labels: S-waiting-on-review

#12282 Handle false positive with `map_clone` lint
  clippy_lints/src/methods/map_clone.rs
  tests/ui/map_clone.fixed
  tests/ui/map_clone.rs
  tests/ui/map_clone.stderr
Labels: S-waiting-on-review

#12386 [`use_self`]: Make it aware of lifetimes
  clippy_lints/src/use_self.rs
  tests/ui/use_self.fixed
  tests/ui/use_self.rs
  tests/ui/use_self.stderr
Labels: S-waiting-on-review

#12472 Don't emit `doc_markdown` lint for missing backticks if it's inside a quote
  clippy_lints/src/doc/markdown.rs
  clippy_lints/src/doc/mod.rs
  tests/ui/doc/issue_10262.fixed
  tests/ui/doc/issue_10262.rs
  tests/ui/doc/issue_10262.stderr
Labels: S-waiting-on-review

#12432 [`unused_enumerate_index`]: trigger on method calls
  clippy_lints/src/loops/unused_enumerate_index.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/unused_enumerate_index.rs
  clippy_utils/src/paths.rs
  tests/ui/unused_enumerate_index.fixed
  tests/ui/unused_enumerate_index.rs
  tests/ui/unused_enumerate_index.stderr
Labels: S-waiting-on-review

#12493 fix span calculation for non-ascii in `needless_return`
  clippy_lints/src/returns.rs
  tests/ui/crashes/ice-12491.fixed
  tests/ui/crashes/ice-12491.rs
  tests/ui/crashes/ice-12491.stderr
Labels: S-waiting-on-review

#12441 [`else_if_without_else`]: Fix duplicate diagnostics
  clippy_lints/src/else_if_without_else.rs
  tests/ui/else_if_without_else.rs
  tests/ui/else_if_without_else.stderr
Labels: S-waiting-on-review

#12479 move `readonly_write_lock` to perf
  clippy_lints/src/methods/mod.rs
  tests/ui/await_holding_lock.rs
  tests/ui/await_holding_lock.stderr
Labels: S-waiting-on-review

#12450 [`option_option`]: Fix duplicate diagnostics
  clippy_lints/src/types/mod.rs
  tests/ui/option_option.rs
  tests/ui/option_option.stderr
Labels: S-waiting-on-review

#12451 new restriction lint: `integer_division_remainder_used`
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/integer_division_remainder_used.rs
  clippy_lints/src/lib.rs
  tests/ui/integer_division_remainder_used.rs
  tests/ui/integer_division_remainder_used.stderr
Labels: S-waiting-on-review

#12498 [`map_entry`]: call the visitor on the local's `else` block
  clippy_lints/src/entry.rs
  tests/ui/entry.fixed
  tests/ui/entry.rs
  tests/ui/entry.stderr
Labels: S-waiting-on-review

#12510 chore: fix typo
  clippy_lints/src/functions/mod.rs
Labels: S-waiting-on-review

#12511 `assigning_clones` should respect MSRV
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  clippy_config/src/msrvs.rs
  clippy_lints/src/assigning_clones.rs
  clippy_lints/src/lib.rs
  tests/ui/assigning_clones.fixed
  tests/ui/assigning_clones.rs
  tests/ui/assigning_clones.stderr
Labels: S-waiting-on-review

#12516 Make `assigning_clones` MSRV check more precise
  clippy_lints/src/assigning_clones.rs
  tests/ui/assigning_clones.fixed
  tests/ui/assigning_clones.rs
  tests/ui/assigning_clones.stderr
Labels: S-waiting-on-review

#12496 Disable `cast_lossless` when casting to u128 from any (u)int type
  clippy_lints/src/casts/cast_lossless.rs
  tests/ui/cast_lossless_integer.fixed
  tests/ui/cast_lossless_integer.rs
  tests/ui/cast_lossless_integer.stderr
Labels: S-waiting-on-review

#12509 Changelog for Clippy 1.77 :school:
  CHANGELOG.md
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/thread_local_initializer_can_be_made_const.rs
  clippy_lints/src/transmute/mod.rs
  clippy_lints/src/unconditional_recursion.rs
Labels: S-waiting-on-review

#12520 Add xFrednet back to the reviewing rotation :tada:
  triagebot.toml
Labels: S-waiting-on-review

#12523 Fix documentation typo "appects" > "affects"
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-review

#12522 Correct version for incompatible_msrv
  clippy_lints/src/incompatible_msrv.rs
Labels: S-waiting-on-review

#12526 Mention `size_hint()` effect in `flat_map_option` lint documentation.
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-review

#12508 Fix infinite loop in `cast_sign_loss` when peeling unwrap method calls
  clippy_lints/src/casts/cast_sign_loss.rs
  tests/ui/cast.rs
  tests/ui/cast.stderr
Labels: S-waiting-on-review

#12529 Do not warn on .map(_::clone) for Arc, Rc, and their weak variants
  clippy_lints/src/methods/map_clone.rs
  tests/ui/map_clone.fixed
  tests/ui/map_clone.rs
Labels: S-waiting-on-review

#12532 Add necessary parentheses to `manual_unwrap_or_default` lint output
  clippy_lints/src/manual_unwrap_or_default.rs
  tests/ui/manual_unwrap_or_default.fixed
  tests/ui/manual_unwrap_or_default.rs
  tests/ui/manual_unwrap_or_default.stderr
Labels: S-waiting-on-review

#12534 Fix typo in exhaustive_items.rs
  clippy_lints/src/exhaustive_items.rs
Labels: S-waiting-on-review

#12486 don't lint [`mixed_attributes_style`] when mixing docs and other attrs
  clippy_lints/src/attrs/mixed_attributes_style.rs
  clippy_lints/src/attrs/mod.rs
  tests/ui/mixed_attributes_style.rs
  tests/ui/mixed_attributes_style.stderr
  tests/ui/mixed_attributes_style/auxiliary/submodule.rs
  tests/ui/mixed_attributes_style/global_allow.rs
  tests/ui/mixed_attributes_style/mod_declaration.rs
  tests/ui/mixed_attributes_style/mod_declaration.stderr
Labels: S-waiting-on-review

#12535 `useless_asref`: do not lint `.as_ref().map(Arc::clone)`
  clippy_lints/src/methods/map_clone.rs
  clippy_lints/src/methods/useless_asref.rs
  clippy_utils/src/ty.rs
  tests/ui/useless_asref.fixed
  tests/ui/useless_asref.rs
  tests/ui/useless_asref.stderr
Labels: S-waiting-on-review

#12239 Add `missing_transmute_annotations` lint
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/transmute/missing_transmute_annotations.rs
  clippy_lints/src/transmute/mod.rs
  tests/ui/author/issue_3849.rs
  tests/ui/auxiliary/macro_rules.rs
  tests/ui/blocks_in_conditions.fixed
  tests/ui/blocks_in_conditions.rs
  tests/ui/blocks_in_conditions.stderr
  tests/ui/crashes/ice-1782.rs
  tests/ui/eager_transmute.fixed
  tests/ui/eager_transmute.rs
  tests/ui/missing_const_for_fn/could_be_const.rs
  tests/ui/missing_transmute_annotations.fixed
  tests/ui/missing_transmute_annotations.rs
  tests/ui/missing_transmute_annotations.stderr
  tests/ui/ptr_cast_constness.fixed
  tests/ui/ptr_cast_constness.rs
  tests/ui/ptr_cast_constness.stderr
  tests/ui/transmute.rs
  tests/ui/transmute.stderr
  tests/ui/transmute_collection.rs
  tests/ui/transmute_collection.stderr
  tests/ui/transmute_float_to_int.fixed
  tests/ui/transmute_float_to_int.rs
  tests/ui/transmute_float_to_int.stderr
  tests/ui/transmute_int_to_char.fixed
  tests/ui/transmute_int_to_char.rs
  tests/ui/transmute_int_to_char.stderr
  tests/ui/transmute_int_to_char_no_std.fixed
  tests/ui/transmute_int_to_char_no_std.rs
  tests/ui/transmute_int_to_char_no_std.stderr
  tests/ui/transmute_int_to_non_zero.fixed
  tests/ui/transmute_int_to_non_zero.rs
  tests/ui/transmute_int_to_non_zero.stderr
  tests/ui/transmute_null_to_fn.rs
  tests/ui/transmute_ptr_to_ptr.fixed
  tests/ui/transmute_ptr_to_ptr.rs
  tests/ui/transmute_ptr_to_ref.fixed
  tests/ui/transmute_ptr_to_ref.rs
  tests/ui/transmute_ptr_to_ref.stderr
  tests/ui/transmute_ref_to_ref.rs
  tests/ui/transmute_ref_to_ref_no_std.rs
  tests/ui/transmute_undefined_repr.rs
  tests/ui/transmute_undefined_repr.stderr
  tests/ui/transmutes_expressible_as_ptr_casts.fixed
  tests/ui/transmutes_expressible_as_ptr_casts.rs
  tests/ui/transmuting_null.rs
  tests/ui/uninhabited_references.rs
  tests/ui/uninhabited_references.stderr
  tests/ui/use_self.fixed
  tests/ui/use_self.rs
  tests/ui/use_self.stderr
Labels: S-waiting-on-review

#12557 Remove unnecessary dot in the 'unconditional recursion' lint description
  clippy_lints/src/unconditional_recursion.rs
Labels: S-waiting-on-review

#12549 fix: `suspicious_else_formatting` false positive when else is included …
  clippy_lints/src/formatting.rs
  tests/ui/suspicious_else_formatting.rs
Labels: S-waiting-on-review

#12558 [`let_and_return`]: avoid linting when code between last stmt and return expr is cfg'd out
  clippy_lints/src/matches/mod.rs
  clippy_lints/src/returns.rs
  clippy_utils/src/attrs.rs
  tests/ui/let_and_return.fixed
  tests/ui/let_and_return.rs
Labels: S-waiting-on-review

#12536 `manual_assert`: do not add extra semicolon
  clippy_lints/src/manual_assert.rs
  clippy_lints/src/needless_bool.rs
  clippy_utils/src/lib.rs
  tests/ui/manual_assert.edition2018.fixed
  tests/ui/manual_assert.edition2018.stderr
  tests/ui/manual_assert.edition2021.fixed
  tests/ui/manual_assert.edition2021.stderr
  tests/ui/manual_assert.rs
Labels: S-waiting-on-review

#12554 Change applicability of `assigning_clones` to `Unspecified`
  clippy_lints/src/assigning_clones.rs
Labels: S-waiting-on-review

#12540 Remove `unwrap` from `match_trait_method`
  clippy_utils/src/lib.rs
Labels: S-waiting-on-review

#12481 RFC: Document Clippy's teams and team duties
  book/src/SUMMARY.md
  book/src/development/the_team.md
Labels: S-needs-discussion, A-documentation, S-waiting-on-review, I-nominated

#12555 Don't emit `duplicated_attribute` lint on "complex" `cfg`s
  clippy_lints/src/attrs/duplicated_attributes.rs
  tests/ui/duplicated_attributes.rs
  tests/ui/duplicated_attributes.stderr
Labels: S-waiting-on-review

#12572 Move `mixed_attributes_style` to style
  clippy_lints/src/attrs/mod.rs
Labels: S-waiting-on-review

#12570 allow [`manual_unwrap_or_default`] in const function
  clippy_lints/src/manual_unwrap_or_default.rs
  tests/ui/manual_unwrap_or_default.fixed
  tests/ui/manual_unwrap_or_default.rs
Labels: S-waiting-on-review

#12582 `large_stack_frames`: print total size and largest component.
  clippy_lints/src/large_stack_frames.rs
  tests/ui-toml/large_stack_frames/large_stack_frames.rs
  tests/ui-toml/large_stack_frames/large_stack_frames.stderr
  tests/ui/large_stack_frames.rs
  tests/ui/large_stack_frames.stderr
Labels: S-waiting-on-review

#12587 Fix typo in comment
  clippy_lints/src/serde_api.rs
Labels: S-waiting-on-review

#12543 restrict manual_clamp to const case, bring it out of nursery
  clippy_lints/src/manual_clamp.rs
  tests/ui/manual_clamp.fixed
  tests/ui/manual_clamp.rs
  tests/ui/manual_clamp.stderr
Labels: S-waiting-on-review

#12579 fix [`manual_unwrap_or_default`] suggestion ignoring side-effects
  clippy_lints/src/manual_unwrap_or_default.rs
  tests/ui/manual_unwrap_or_default.fixed
  tests/ui/manual_unwrap_or_default.rs
Labels: S-waiting-on-review

#12563 make sure checked type implements `Try` trait when linting [`question_mark`]
  clippy_lints/src/question_mark.rs
  tests/ui/question_mark.fixed
  tests/ui/question_mark.rs
  tests/ui/question_mark.stderr
Labels: S-waiting-on-review

#11350 [`type_id_on_box`]: lint on any `Box<dyn _>`
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/type_id_on_box.rs
  tests/ui/type_id_on_box.fixed
  tests/ui/type_id_on_box.rs
  tests/ui/type_id_on_box.stderr
  tests/ui/type_id_on_box_unfixable.rs
  tests/ui/type_id_on_box_unfixable.stderr
Labels: S-waiting-on-review

#12562 Allow `filter_map_identity` when the closure is typed
  clippy_lints/src/methods/filter_map_identity.rs
  tests/ui/filter_map_identity.fixed
  tests/ui/filter_map_identity.rs
  tests/ui/filter_map_identity.stderr
Labels: S-waiting-on-review
