Repository rust-lang/rust-clippy, pull requests merged in 2024-01, with the labels that each got.

#12026 New Lint: [`thread_local_initializer_can_be_made_const`]
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/thread_local_initializer_can_be_made_const.rs
  tests/ui/thread_local_initializer_can_be_made_const.fixed
  tests/ui/thread_local_initializer_can_be_made_const.rs
  tests/ui/thread_local_initializer_can_be_made_const.stderr
Labels: S-waiting-on-review, has-merge-commits

#12079 Fix some typos
  book/src/development/macro_expansions.md
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/missing_asserts_for_indexing.rs
  clippy_lints/src/no_effect.rs
  clippy_lints/src/serde_api.rs
  clippy_lints/src/wildcard_imports.rs
  clippy_utils/src/ty/type_certainty/mod.rs
  tests/ui/as_conversions.rs
  tests/ui/default_numeric_fallback_i32.fixed
  tests/ui/default_numeric_fallback_i32.rs
  tests/ui/redundant_as_str.fixed
  tests/ui/redundant_as_str.rs
  tests/ui/regex.rs
  tests/ui/struct_fields.rs
  tests/ui/useless_conversion.fixed
  tests/ui/useless_conversion.rs
Labels: S-waiting-on-review

#12056 Fixes: #12050 - `identity_op` correctly suggests a deference for coerced references
  clippy_lints/src/operators/identity_op.rs
  tests/ui/identity_op.fixed
  tests/ui/identity_op.rs
  tests/ui/identity_op.stderr
Labels: S-waiting-on-review

#12062 Fix false positive `unconditional_recursion`
  clippy_lints/src/unconditional_recursion.rs
  tests/ui/unconditional_recursion.rs
  tests/ui/unconditional_recursion.stderr
Labels: S-waiting-on-review

#12071 Remove deadlinks from `unchecked_duration_subtraction`
  clippy_lints/src/instant_subtraction.rs
Labels: S-waiting-on-review

#12031 Lint nested binary operations and handle field projections in `eager_transmute`
  clippy_lints/src/transmute/eager_transmute.rs
  tests/ui/eager_transmute.fixed
  tests/ui/eager_transmute.rs
  tests/ui/eager_transmute.stderr
Labels: S-waiting-on-review

#12086 Update copyright year for Clippy (2024 edition)
  COPYRIGHT
  LICENSE-APACHE
  LICENSE-MIT
  README.md
  rustc_tools_util/README.md
Labels: S-waiting-on-review

#12025 Include GitLab in the CI section of the clippy doc book
  book/src/SUMMARY.md
  book/src/continuous_integration/gitlab.md
Labels: S-waiting-on-review

#12088 fix: metadata-collector lists wrong affected lints
  clippy_config/src/conf.rs
  clippy_config/src/metadata.rs
Labels: S-waiting-on-review

#12090 Extend `unconditional_recursion` lint to check for `Default` trait implementation
  clippy_lints/src/lib.rs
  clippy_lints/src/unconditional_recursion.rs
  tests/ui/unconditional_recursion.rs
  tests/ui/unconditional_recursion.stderr
Labels: S-waiting-on-review

#12051 new lint: `option_as_ref_cloned`
  CHANGELOG.md
  README.md
  book/src/README.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/option_as_ref_cloned.rs
  tests/ui/option_as_ref_cloned.fixed
  tests/ui/option_as_ref_cloned.rs
  tests/ui/option_as_ref_cloned.stderr
Labels: S-waiting-on-review

#12091 Add .as_ref() to suggestion to remove .to_string()
  clippy_lints/src/methods/unnecessary_to_owned.rs
  tests/ui/unnecessary_to_owned_on_split.fixed
  tests/ui/unnecessary_to_owned_on_split.rs
  tests/ui/unnecessary_to_owned_on_split.stderr
Labels: S-waiting-on-review

#12066 Don't look for safety comments in doc tests
  clippy_lints/src/undocumented_unsafe_blocks.rs
  tests/ui/unnecessary_safety_comment.rs
Labels: S-waiting-on-review

#12036 Polish `missing_enforced_import_renames` documentation
  clippy_lints/src/missing_enforced_import_rename.rs
Labels: S-waiting-on-review

#12099 Don't emit `struct_field_names` lint if all fields are booleans and don't start with the type's name
  clippy_lints/src/item_name_repetitions.rs
  tests/ui/struct_fields.rs
  tests/ui/struct_fields.stderr
Labels: S-waiting-on-review

#12097 don't change eagerness for struct literal syntax with significant drop
  clippy_utils/src/eager_or_lazy.rs
  tests/ui/unnecessary_lazy_eval.fixed
  tests/ui/unnecessary_lazy_eval.rs
  tests/ui/unnecessary_lazy_eval.stderr
Labels: S-waiting-on-review

#12104 Extend `map_clone` lint to also work on non-explicit closures
  clippy_lints/src/methods/map_clone.rs
  clippy_utils/src/macros.rs
  tests/ui/useless_asref.fixed
  tests/ui/useless_asref.rs
  tests/ui/useless_asref.stderr
Labels: S-waiting-on-review

#11972 Do not suggest `[T; n]` instead of `vec![T; n]` if `T` is not `Copy`
  clippy_lints/src/vec.rs
  tests/ui/vec.fixed
  tests/ui/vec.rs
Labels: S-waiting-on-review

#11883 improve [`cast_sign_loss`], to skip warning on always positive expressions
  clippy_lints/src/casts/cast_sign_loss.rs
  tests/ui/cast.rs
  tests/ui/cast.stderr
Labels: S-waiting-on-review

#12108 Do not suggest `bool::then()` and `bool::then_some` in `const` contexts
  clippy_lints/src/if_then_some_else_none.rs
  tests/ui/if_then_some_else_none.rs
Labels: S-waiting-on-review

#12109 Handle "calls" inside the closure as well in `map_clone` lint
  clippy_lints/src/methods/map_clone.rs
  tests/ui/map_clone.fixed
  tests/ui/map_clone.rs
  tests/ui/map_clone.stderr
Labels: S-waiting-on-review

#12080 Fixed ICE introduced in #12004
  clippy_lints/src/methods/filter_map.rs
  clippy_lints/src/methods/iter_filter.rs
  tests/ui/iter_filter_is_ok.fixed
  tests/ui/iter_filter_is_ok.rs
  tests/ui/iter_filter_is_ok.stderr
  tests/ui/iter_filter_is_some.fixed
  tests/ui/iter_filter_is_some.rs
  tests/ui/iter_filter_is_some.stderr
Labels: S-waiting-on-review, beta-nominated

#12049 fix/issue#11243: allow 3-digit-grouped binary in non_octal_unix_permissions
  clippy_lints/src/non_octal_unix_permissions.rs
  tests/ui/non_octal_unix_permissions.fixed
  tests/ui/non_octal_unix_permissions.rs
  tests/ui/non_octal_unix_permissions.stderr
Labels: S-waiting-on-author, S-waiting-on-review

#12105 Extend `useless_asref` lint on `map(clone)`
  clippy_lints/src/methods/map_clone.rs
  clippy_lints/src/methods/useless_asref.rs
  tests/ui/map_clone.fixed
  tests/ui/map_clone.rs
  tests/ui/map_clone.stderr
  tests/ui/useless_asref.fixed
  tests/ui/useless_asref.rs
  tests/ui/useless_asref.stderr
Labels: S-waiting-on-review

#12127 Remove giraffate from the reviewer rotation
  triagebot.toml
Labels: S-waiting-on-review

#12130 Rustup
  clippy_config/src/msrvs.rs
  clippy_lints/src/casts/unnecessary_cast.rs
  clippy_lints/src/copies.rs
  clippy_lints/src/doc/missing_headers.rs
  clippy_lints/src/doc/needless_doctest_main.rs
  clippy_lints/src/entry.rs
  clippy_lints/src/implicit_hasher.rs
  clippy_lints/src/implicit_return.rs
  clippy_lints/src/manual_clamp.rs
  clippy_lints/src/matches/collapsible_match.rs
  clippy_lints/src/matches/match_like_matches.rs
  clippy_lints/src/matches/needless_match.rs
  clippy_lints/src/matches/redundant_guards.rs
  clippy_lints/src/matches/redundant_pattern_match.rs
  clippy_lints/src/methods/drain_collect.rs
  clippy_lints/src/methods/iter_overeager_cloned.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/option_map_unwrap_or.rs
  clippy_lints/src/methods/redundant_as_str.rs
  clippy_lints/src/methods/unnecessary_to_owned.rs
  clippy_lints/src/mixed_read_write_in_expression.rs
  clippy_lints/src/mut_key.rs
  clippy_lints/src/non_copy_const.rs
  clippy_lints/src/question_mark.rs
  clippy_lints/src/transmute/transmute_int_to_non_zero.rs
  clippy_lints/src/transmute/transmute_undefined_repr.rs
  clippy_lints/src/utils/author.rs
  clippy_utils/src/attrs.rs
  clippy_utils/src/hir_utils.rs
  clippy_utils/src/lib.rs
  rust-toolchain
  tests/ui/borrow_interior_mutable_const/auxiliary/helper.rs
  tests/ui/crashes/ice-6251.stderr
  tests/ui/crashes/ice-6252.stderr
  tests/ui/format.fixed
  tests/ui/format.rs
  tests/ui/format.stderr
  tests/ui/from_iter_instead_of_collect.fixed
  tests/ui/from_iter_instead_of_collect.rs
  tests/ui/must_use_candidates.fixed
  tests/ui/must_use_candidates.rs
  tests/ui/must_use_candidates.stderr
  tests/ui/numbered_fields.fixed
  tests/ui/numbered_fields.rs
  tests/ui/numbered_fields.stderr
  tests/ui/option_if_let_else.fixed
  tests/ui/option_if_let_else.rs
  tests/ui/option_if_let_else.stderr
  tests/ui/unreadable_literal.fixed
  tests/ui/unreadable_literal.rs
  tests/ui/unreadable_literal.stderr
Labels: S-waiting-on-review

#12132 I'm not on vacation (again)
  triagebot.toml
Labels: S-waiting-on-review

#12129 Fix suggestion for `map_clone` lint on types implementing `Copy`
  clippy_lints/src/methods/map_clone.rs
  tests/ui/map_clone.fixed
  tests/ui/map_clone.rs
  tests/ui/map_clone.stderr
Labels: S-waiting-on-review

#12137 Fix false positive in `PartialEq` check in `unconditional_recursion` lint
  clippy_lints/src/unconditional_recursion.rs
  tests/ui/unconditional_recursion.rs
  tests/ui/unconditional_recursion.stderr
Labels: S-waiting-on-review

#12140 Improve help message for `search_is_some` lint
  clippy_lints/src/methods/search_is_some.rs
  tests/ui/crashes/ice-9041.stderr
  tests/ui/search_is_some.stderr
  tests/ui/search_is_some_fixable_none.stderr
  tests/ui/search_is_some_fixable_some.stderr
Labels: S-waiting-on-review

#12074 Make `HirEqInterExpr::eq_block` take comments into account while checking if two blocks are equal
  clippy_utils/src/hir_utils.rs
  tests/ui/branches_sharing_code/shared_at_top.rs
  tests/ui/branches_sharing_code/shared_at_top.stderr
  tests/ui/branches_sharing_code/valid_if_blocks.rs
  tests/ui/branches_sharing_code/valid_if_blocks.stderr
  tests/ui/if_same_then_else.rs
  tests/ui/if_same_then_else.stderr
  tests/ui/if_same_then_else2.rs
  tests/ui/if_same_then_else2.stderr
  tests/ui/match_same_arms2.rs
  tests/ui/match_same_arms2.stderr
Labels: S-waiting-on-review

#12114 ['arc_with_non_send_sync`] documentation edits
  clippy_lints/src/arc_with_non_send_sync.rs
Labels: S-waiting-on-review

#12141 from_over_into: suggest a correct conversion to ()
  clippy_lints/src/from_over_into.rs
  tests/ui/from_over_into.fixed
  tests/ui/from_over_into.rs
  tests/ui/from_over_into.stderr
Labels: S-waiting-on-review

#12136 [`useless_asref`]: check that the clone receiver is the parameter
  clippy_lints/src/methods/useless_asref.rs
  tests/ui/useless_asref.fixed
  tests/ui/useless_asref.rs
  tests/ui/useless_asref.stderr
Labels: S-waiting-on-review

#11926 Add "OpenTelemetry" to default `doc_valid_idents`
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  tests/ui/doc/doc-fixable.fixed
  tests/ui/doc/doc-fixable.rs
Labels: S-waiting-on-review

#11945 Try to improve wording and fix dead link in description of arc_with_non_send_sync lint.
  clippy_lints/src/arc_with_non_send_sync.rs
Labels: S-waiting-on-review

#11608 Add suspicious_open_options lint.
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/open_options.rs
  clippy_utils/src/paths.rs
  tests/ui/ineffective_open_options.fixed
  tests/ui/ineffective_open_options.rs
  tests/ui/open_options.rs
  tests/ui/open_options.stderr
  tests/ui/open_options_fixable.fixed
  tests/ui/open_options_fixable.rs
  tests/ui/open_options_fixable.stderr
  tests/ui/seek_to_start_instead_of_rewind.fixed
  tests/ui/seek_to_start_instead_of_rewind.rs
  tests/ui/seek_to_start_instead_of_rewind.stderr
Labels: S-waiting-on-review

#11766 `read_zero_byte_vec` refactor for better heuristics
  clippy_lints/src/read_zero_byte_vec.rs
  tests/ui/read_zero_byte_vec.rs
  tests/ui/read_zero_byte_vec.stderr
Labels: S-waiting-on-review

#12155 Correctly handle type relative in trait_duplication_in_bounds lint
  clippy_lints/src/trait_bounds.rs
  tests/ui/trait_duplication_in_bounds.fixed
  tests/ui/trait_duplication_in_bounds.rs
Labels: S-waiting-on-review

#12146 Fix [`multiple_crate_versions`] to correctly normalize package names to avoid missing the local one
  clippy_lints/src/cargo/multiple_crate_versions.rs
  tests/ui-cargo/multiple_crate_versions/12145_with_dashes/Cargo.stderr
  tests/ui-cargo/multiple_crate_versions/12145_with_dashes/Cargo.toml
  tests/ui-cargo/multiple_crate_versions/12145_with_dashes/src/main.rs
Labels: S-waiting-on-review

#12168 [`default_numeric_fallback`]: improve const context detection
  clippy_lints/src/default_numeric_fallback.rs
  tests/ui/default_numeric_fallback_i32.fixed
  tests/ui/default_numeric_fallback_i32.rs
Labels: S-waiting-on-review

#12167 fix FP on [`semicolon_if_nothing_returned`]
  clippy_lints/src/semicolon_if_nothing_returned.rs
  tests/ui/auxiliary/proc_macro_attr.rs
  tests/ui/semicolon_if_nothing_returned.fixed
  tests/ui/semicolon_if_nothing_returned.rs
  tests/ui/semicolon_if_nothing_returned.stderr
Labels: S-waiting-on-review

#12173 blocks_in_conditions: do not warn if condition comes from macro
  clippy_lints/src/blocks_in_conditions.rs
  tests/ui/blocks_in_conditions.fixed
  tests/ui/blocks_in_conditions.rs
Labels: S-waiting-on-review

#12125 Fix error warning span for issue12045
  clippy_lints/src/no_effect.rs
  tests/ui/no_effect.stderr
Labels: S-waiting-on-review

#12147 Find function path references early in the same lint pass
  clippy_lints/src/needless_pass_by_ref_mut.rs
Labels: S-waiting-on-review

#12144 Add . to end of lint lists in configuration + Fix typo in pub_underscore_fields_behavior
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  clippy_config/src/types.rs
  clippy_lints/src/pub_underscore_fields.rs
  tests/ui-toml/pub_underscore_fields/exported/clippy.toml
Labels: S-waiting-on-review

#12172 no_effect_underscore_binding: _ prefixed variables can be used
  clippy_lints/src/lib.rs
  clippy_lints/src/no_effect.rs
  tests/ui/no_effect.rs
Labels: S-waiting-on-review

#12005 `unused_io_amount` captures `Ok(_)`s
  clippy_lints/src/unused_io_amount.rs
  tests/ui/unused_io_amount.rs
  tests/ui/unused_io_amount.stderr
Labels: S-waiting-on-review

#12170 Improve wording for suggestion messages
  clippy_lints/src/loops/same_item_push.rs
  clippy_lints/src/methods/join_absolute_paths.rs
  clippy_lints/src/methods/manual_saturating_arithmetic.rs
  clippy_lints/src/methods/option_as_ref_deref.rs
  clippy_lints/src/methods/option_map_or_err_ok.rs
  clippy_lints/src/methods/option_map_or_none.rs
  clippy_lints/src/methods/result_map_or_else_none.rs
  clippy_lints/src/methods/single_char_pattern.rs
  clippy_lints/src/methods/unnecessary_join.rs
  clippy_lints/src/utils/internal_lints/almost_standard_lint_formulation.rs
  tests/ui-internal/check_formulation.stderr
  tests/ui/join_absolute_paths.stderr
  tests/ui/manual_ok_or.stderr
  tests/ui/manual_saturating_arithmetic.stderr
  tests/ui/option_as_ref_deref.stderr
  tests/ui/option_map_or_err_ok.stderr
  tests/ui/option_map_or_none.stderr
  tests/ui/result_map_or_into_option.stderr
  tests/ui/same_item_push.stderr
  tests/ui/single_char_pattern.stderr
  tests/ui/unnecessary_join.stderr
Labels: S-waiting-on-review

#12153 Don't emit `derive_partial_eq_without_eq` lint if the type has the `non_exhaustive` attribute
  clippy_lints/src/derive.rs
  clippy_utils/src/attrs.rs
  tests/ui/derive_partial_eq_without_eq.fixed
  tests/ui/derive_partial_eq_without_eq.rs
Labels: S-waiting-on-review

#12183 respect `#[allow]` attributes in `single_call_fn` lint
  clippy_lints/src/single_call_fn.rs
  tests/ui/single_call_fn.rs
Labels: S-waiting-on-review

#12179 [`multiple_crate_versions`]: add a configuration option for allowed duplicate crates
  CHANGELOG.md
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  clippy_lints/src/cargo/mod.rs
  clippy_lints/src/cargo/multiple_crate_versions.rs
  clippy_lints/src/lib.rs
  tests/ui-cargo/multiple_crate_versions/12176_allow_duplicate_crates/Cargo.toml
  tests/ui-cargo/multiple_crate_versions/12176_allow_duplicate_crates/clippy.toml
  tests/ui-cargo/multiple_crate_versions/12176_allow_duplicate_crates/src/main.rs
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
Labels: S-waiting-on-review

#12180 Suggest existing configuration option if one is found
  clippy_config/src/conf.rs
  clippy_config/src/lib.rs
  tests/ui-toml/toml_unknown_key/clippy.toml
  tests/ui-toml/toml_unknown_key/conf_unknown_key.rs
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
Labels: S-waiting-on-review

#12202 Avoid linting redundant closure when callee is marked `#[track_caller]`
  clippy_lints/src/eta_reduction.rs
  tests/ui/eta.fixed
  tests/ui/eta.rs
  tests/ui/eta.stderr
Labels: S-waiting-on-review

#12160 Warn if an item coming from more recent version than MSRV is used
  CHANGELOG.md
  clippy_config/src/msrvs.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/incompatible_msrv.rs
  clippy_lints/src/lib.rs
  tests/ui-toml/min_rust_version/min_rust_version.fixed
  tests/ui-toml/min_rust_version/min_rust_version.rs
  tests/ui/incompatible_msrv.rs
  tests/ui/incompatible_msrv.stderr
Labels: S-waiting-on-review

#12082 Fixed FP in `redundant_closure_call` when closures are passed to macros
  clippy_lints/src/redundant_closure_call.rs
  tests/ui/redundant_closure_call_fixable.fixed
  tests/ui/redundant_closure_call_fixable.rs
Labels: S-waiting-on-review

#12178 Don't warn about modulo arithmetic when comparing to zero
  CHANGELOG.md
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/operators/mod.rs
  clippy_lints/src/operators/modulo_arithmetic.rs
  tests/ui-toml/modulo_arithmetic/clippy.toml
  tests/ui-toml/modulo_arithmetic/modulo_arithmetic.rs
  tests/ui-toml/modulo_arithmetic/modulo_arithmetic.stderr
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
  tests/ui/modulo_arithmetic_integral.rs
Labels: S-waiting-on-review

#12122 add to_string_trait_impl lint
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/returns.rs
  clippy_lints/src/to_string_trait_impl.rs
  tests/ui/format_args.fixed
  tests/ui/format_args.rs
  tests/ui/format_args.stderr
  tests/ui/to_string_trait_impl.rs
  tests/ui/to_string_trait_impl.stderr
  tests/ui/unconditional_recursion.rs
  tests/ui/unconditional_recursion.stderr
  tests/ui/unnecessary_to_owned.fixed
  tests/ui/unnecessary_to_owned.rs
  tests/ui/unnecessary_to_owned.stderr
  tests/ui/unnecessary_to_owned_on_split.fixed
  tests/ui/unnecessary_to_owned_on_split.rs
  tests/ui/unnecessary_to_owned_on_split.stderr
Labels: S-waiting-on-review

#12169 Add new `unnecessary_result_map_or_else` lint
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/methods/map_unwrap_or.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/unnecessary_result_map_or_else.rs
  tests/ui/unnecessary_result_map_or_else.fixed
  tests/ui/unnecessary_result_map_or_else.rs
  tests/ui/unnecessary_result_map_or_else.stderr
Labels: S-waiting-on-review

#12206 [`never_loop`]: recognize desugared `try` blocks
  clippy_lints/src/loops/never_loop.rs
  tests/ui/never_loop.rs
Labels: S-waiting-on-review

#12083 Fix/Issue11932: assert* in multi-condition after unrolling will cause lint `nonminimal_bool` emit warning
  clippy_lints/src/booleans.rs
  tests/ui/nonminimal_bool.rs
Labels: S-waiting-on-review

#12084 fix: incorrect suggestions generated by `manual_retain` lint
  clippy_lints/src/manual_retain.rs
  tests/ui/manual_retain.fixed
  tests/ui/manual_retain.rs
  tests/ui/manual_retain.stderr
Labels: S-waiting-on-review

#12021 FP: `needless_return_with_question_mark` with implicit Error Conversion
  clippy_lints/src/returns.rs
  tests/ui/needless_return_with_question_mark.fixed
  tests/ui/needless_return_with_question_mark.rs
Labels: S-waiting-on-review

#11370 [fix] [`redundant_closure_for_method_calls`] Suggest relative paths for local modules
  clippy_lints/src/eta_reduction.rs
  clippy_utils/src/lib.rs
  tests/ui/eta.fixed
  tests/ui/eta.rs
  tests/ui/eta.stderr
Labels: S-waiting-on-review

#12203 Makes clippy-driver check for --sysroot in arg files
  .github/driver.sh
  src/driver.rs
Labels: S-waiting-on-review

#12210 Add regression ui test for #2371
  clippy_lints/src/methods/unnecessary_fold.rs
  tests/ui/unnecessary_fold.fixed
  tests/ui/unnecessary_fold.rs
  tests/ui/unnecessary_fold.stderr
Labels: S-waiting-on-review

#11832 Add `lint_groups_priority` lint
  CHANGELOG.md
  clippy_lints/src/cargo/lint_groups_priority.rs
  clippy_lints/src/cargo/mod.rs
  clippy_lints/src/declared_lints.rs
  tests/ui-cargo/lint_groups_priority/fail/Cargo.stderr
  tests/ui-cargo/lint_groups_priority/fail/Cargo.toml
  tests/ui-cargo/lint_groups_priority/fail/src/lib.rs
  tests/ui-cargo/lint_groups_priority/pass/Cargo.toml
  tests/ui-cargo/lint_groups_priority/pass/src/lib.rs
Labels: S-waiting-on-review
