Repository rust-lang/rust-clippy, pull requests merged in 2024-05, with the labels that each got.

#12687 Don't suggest `Box::default()` in functions with differing generics
  clippy_lints/src/box_default.rs
  tests/ui/box_default.fixed
  tests/ui/box_default.rs
  tests/ui/box_default.stderr
Labels: S-waiting-on-review

#11988 fix suggestion error for [`manual_is_ascii_check`] with missing type
  clippy_lints/src/manual_is_ascii_check.rs
  tests/ui/manual_is_ascii_check.fixed
  tests/ui/manual_is_ascii_check.rs
  tests/ui/manual_is_ascii_check.stderr
Labels: S-waiting-on-review

#12735 Changelog for Clippy 1.78 :magic_wand:
  CHANGELOG.md
  clippy_lints/src/assigning_clones.rs
  clippy_lints/src/cargo/mod.rs
  clippy_lints/src/casts/mod.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/multiple_bound_locations.rs
  clippy_lints/src/to_string_trait_impl.rs
Labels: S-waiting-on-review

#12746 Bump ui_test to 0.23
  Cargo.toml
  tests/compile-test.rs
Labels: S-waiting-on-review

#12515 fix `for x in y unsafe { }`
  clippy_lints/src/needless_for_each.rs
  tests/ui/needless_for_each_fixable.fixed
  tests/ui/needless_for_each_fixable.rs
Labels: S-waiting-on-review

#12743 Remove `dead_code` paths
  clippy_utils/src/paths.rs
Labels: S-waiting-on-review

#12745 Suggest collapsing nested or patterns if the MSRV allows it
  clippy_lints/src/matches/collapsible_match.rs
  clippy_lints/src/matches/mod.rs
  clippy_lints/src/matches/redundant_guards.rs
  tests/ui/collapsible_match.rs
  tests/ui/collapsible_match.stderr
  tests/ui/redundant_guards.fixed
  tests/ui/redundant_guards.rs
  tests/ui/redundant_guards.stderr
Labels: S-waiting-on-review

#12750 `assigning_clones`: add empty line to doc
  clippy_lints/src/assigning_clones.rs
Labels: S-waiting-on-review

#12567 Fix `FormatArgs` storage when `-Zthreads` > 1
  clippy_lints/src/explicit_write.rs
  clippy_lints/src/format.rs
  clippy_lints/src/format_args.rs
  clippy_lints/src/format_impl.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/methods/expect_fun_call.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/utils/format_args_collector.rs
  clippy_lints/src/write.rs
  clippy_utils/src/macros.rs
Labels: S-waiting-on-review

#12742 Don't lint assigning_clones on nested late init locals
  clippy_lints/src/assigning_clones.rs
  clippy_utils/src/lib.rs
  tests/ui/assigning_clones.fixed
  tests/ui/assigning_clones.rs
  tests/ui/assigning_clones.stderr
Labels: S-waiting-on-review

#12755 Allow more attributes in `clippy::useless_attribute`
  clippy_lints/src/attrs/mod.rs
  clippy_lints/src/attrs/useless_attribute.rs
  tests/ui-toml/toml_disallowed_types/conf_disallowed_types.rs
  tests/ui/useless_attribute.fixed
  tests/ui/useless_attribute.rs
Labels: S-waiting-on-review

#12650 fix false positive in Issue/12098 because lack of consideration of mutable caller
  clippy_lints/src/methods/unnecessary_iter_cloned.rs
  tests/ui/unnecessary_iter_cloned.fixed
  tests/ui/unnecessary_iter_cloned.rs
  tests/ui/unnecessary_iter_cloned.stderr
Labels: S-waiting-on-review

#12783 fix: use hir_with_context to produce correct snippets for assigning_clones
  clippy_lints/src/assigning_clones.rs
  tests/ui/assigning_clones.fixed
  tests/ui/assigning_clones.rs
  tests/ui/assigning_clones.stderr
Labels: S-waiting-on-review

#12780 Ignore `_to_string` lints in code `from_expansion`
  clippy_lints/src/strings.rs
Labels: S-waiting-on-review

#12770 Add new lint `doc_lazy_continuation`
  CHANGELOG.md
  clippy_lints/src/casts/cast_sign_loss.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/doc/lazy_continuation.rs
  clippy_lints/src/doc/mod.rs
  clippy_lints/src/manual_clamp.rs
  clippy_lints/src/methods/iter_filter.rs
  clippy_lints/src/methods/iter_kv_map.rs
  clippy_lints/src/methods/utils.rs
  clippy_lints/src/needless_continue.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/source.rs
  clippy_utils/src/sugg.rs
  tests/ui/doc/doc_lazy_blockquote.fixed
  tests/ui/doc/doc_lazy_blockquote.rs
  tests/ui/doc/doc_lazy_blockquote.stderr
  tests/ui/doc/doc_lazy_list.fixed
  tests/ui/doc/doc_lazy_list.rs
  tests/ui/doc/doc_lazy_list.stderr
Labels: S-waiting-on-review

#12620 Handle `rustc_on_unimplemented` in duplicated_attributes
  clippy_lints/src/attrs/duplicated_attributes.rs
  tests/ui/duplicated_attributes.rs
Labels: S-waiting-on-review

#12730 Lint direct priority conflicts in `[workspace.lints]`
  clippy_lints/src/cargo/lint_groups_priority.rs
  tests/ui-cargo/lint_groups_priority/fail/Cargo.stderr
  tests/ui-cargo/lint_groups_priority/fail/Cargo.toml
Labels: S-waiting-on-review

#12787 make [`from_str_radix_10`] skip constant context
  clippy_lints/src/from_str_radix_10.rs
  tests/ui/from_str_radix_10.fixed
  tests/ui/from_str_radix_10.rs
  tests/ui/from_str_radix_10.stderr
Labels: S-waiting-on-review

#11540 add new lint that disallow renaming parameters in trait functions
  CHANGELOG.md
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/functions/mod.rs
  clippy_lints/src/functions/renamed_function_params.rs
  clippy_lints/src/lib.rs
  tests/ui-toml/renamed_function_params/default/clippy.toml
  tests/ui-toml/renamed_function_params/extend/clippy.toml
  tests/ui-toml/renamed_function_params/renamed_function_params.default.stderr
  tests/ui-toml/renamed_function_params/renamed_function_params.extend.stderr
  tests/ui-toml/renamed_function_params/renamed_function_params.rs
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
Labels: S-waiting-on-author

#12107 new lint: `macro_metavars_in_unsafe`
  CHANGELOG.md
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/macro_metavars_in_unsafe.rs
  tests/ui-toml/macro_metavars_in_unsafe/default/test.rs
  tests/ui-toml/macro_metavars_in_unsafe/default/test.stderr
  tests/ui-toml/macro_metavars_in_unsafe/private/clippy.toml
  tests/ui-toml/macro_metavars_in_unsafe/private/test.rs
  tests/ui-toml/macro_metavars_in_unsafe/private/test.stderr
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
Labels: S-waiting-on-author

#12764 `significant_drop_in_scrutinee`: Fix false positives due to false drops of place expressions
  clippy_lints/src/matches/significant_drop_in_scrutinee.rs
  tests/ui/significant_drop_in_scrutinee.rs
  tests/ui/significant_drop_in_scrutinee.stderr
Labels: S-waiting-on-review

#12798 Don't lint path statements in no_effect
  clippy_lints/src/no_effect.rs
  tests/ui/no_effect.rs
  tests/ui/no_effect.stderr
Labels: S-waiting-on-review

#12779 `assigning_clones`: move to `pedantic` so it is allow by default
  clippy_lints/src/assigning_clones.rs
Labels: S-needs-discussion, S-waiting-on-review

#12790 Fix #12760
  clippy_lints/src/doc/missing_headers.rs
  clippy_lints/src/doc/mod.rs
  tests/ui/missing_panics_doc.rs
Labels: S-waiting-on-review

#12706 less aggressive needless_borrows_for_generic_args
  clippy_lints/src/needless_borrows_for_generic_args.rs
  tests/ui/needless_borrows_for_generic_args.fixed
  tests/ui/needless_borrows_for_generic_args.rs
  tests/ui/needless_borrows_for_generic_args.stderr
Labels: S-waiting-on-review

#12713 make sure the msrv for `const_raw_ptr_deref` is met when linting [`missing_const_for_fn`]
  clippy_config/src/msrvs.rs
  clippy_utils/src/qualify_min_const_fn.rs
  tests/ui/missing_const_for_fn/cant_be_const.rs
  tests/ui/missing_const_for_fn/could_be_const.rs
  tests/ui/missing_const_for_fn/could_be_const.stderr
Labels: S-waiting-on-review

#12812 Manually set library paths in .github/driver.sh
  .github/driver.sh
  .github/workflows/clippy.yml
  .github/workflows/clippy_bors.yml
Labels: S-waiting-on-review

#12803 Add configuration option for ignoring `panic!()` in tests
  CHANGELOG.md
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/panic_unimplemented.rs
  tests/ui-toml/panic/clippy.toml
  tests/ui-toml/panic/panic.rs
  tests/ui-toml/panic/panic.stderr
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
Labels: S-waiting-on-review

#12813 Rustup
  clippy_lints/src/default_union_representation.rs
  clippy_lints/src/dereference.rs
  clippy_lints/src/derive.rs
  clippy_lints/src/escape.rs
  clippy_lints/src/future_not_send.rs
  clippy_lints/src/implied_bounds_in_impls.rs
  clippy_lints/src/iter_without_into_iter.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/loops/mut_range_bound.rs
  clippy_lints/src/manual_assert.rs
  clippy_lints/src/matches/significant_drop_in_scrutinee.rs
  clippy_lints/src/methods/iter_overeager_cloned.rs
  clippy_lints/src/methods/unnecessary_to_owned.rs
  clippy_lints/src/mismatching_type_param_order.rs
  clippy_lints/src/needless_borrows_for_generic_args.rs
  clippy_lints/src/needless_pass_by_ref_mut.rs
  clippy_lints/src/needless_pass_by_value.rs
  clippy_lints/src/operators/assign_op_pattern.rs
  clippy_lints/src/operators/cmp_owned.rs
  clippy_lints/src/redundant_closure_call.rs
  clippy_lints/src/semicolon_if_nothing_returned.rs
  clippy_lints/src/single_component_path_imports.rs
  clippy_lints/src/transmute/eager_transmute.rs
  clippy_lints/src/transmute/mod.rs
  clippy_lints/src/transmute/transmute_int_to_non_zero.rs
  clippy_lints/src/unit_return_expecting_ord.rs
  clippy_lints/src/unnecessary_self_imports.rs
  clippy_lints/src/unsafe_removed_from_name.rs
  clippy_lints/src/unwrap.rs
  clippy_utils/src/ast_utils.rs
  clippy_utils/src/hir_utils.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/qualify_min_const_fn.rs
  clippy_utils/src/sugg.rs
  clippy_utils/src/ty.rs
  clippy_utils/src/ty/type_certainty/mod.rs
  clippy_utils/src/usage.rs
  lintcheck/src/config.rs
  rust-toolchain
  tests/ui/almost_complete_range.fixed
  tests/ui/almost_complete_range.rs
  tests/ui/almost_complete_range.stderr
  tests/ui/arithmetic_side_effects.rs
  tests/ui/eager_transmute.fixed
  tests/ui/eager_transmute.rs
  tests/ui/eager_transmute.stderr
  tests/ui/manual_range_patterns.fixed
  tests/ui/manual_range_patterns.rs
  tests/ui/manual_range_patterns.stderr
  tests/ui/match_overlapping_arm.rs
  tests/ui/match_overlapping_arm.stderr
  tests/ui/match_wild_err_arm.rs
  tests/ui/match_wild_err_arm.stderr
  tests/ui/transmute_int_to_non_zero.fixed
  tests/ui/transmute_int_to_non_zero.rs
  tests/ui/transmute_int_to_non_zero.stderr
Labels: S-waiting-on-review

#12818 doc_lazy_continuation: do not warn on End events
  clippy_lints/src/doc/mod.rs
  tests/ui/doc/doc_lazy_list.fixed
  tests/ui/doc/doc_lazy_list.rs
  tests/ui/doc/doc_lazy_list.stderr
Labels: S-waiting-on-review

#12765 Add new lint `while_float`
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/loops/mod.rs
  clippy_lints/src/loops/while_float.rs
  tests/ui/while_float.rs
  tests/ui/while_float.stderr
Labels: S-waiting-on-review

#12804 fulfill expectations in `check_unsafe_derive_deserialize`
  clippy_lints/src/derive.rs
  tests/ui/unsafe_derive_deserialize.rs
  tests/ui/unsafe_derive_deserialize.stderr
Labels: S-waiting-on-review

#12398 bug fix: lint numbered_fields message error
  clippy_lints/src/init_numbered_fields.rs
  tests/ui/numbered_fields.fixed
  tests/ui/numbered_fields.rs
  tests/ui/numbered_fields.stderr
Labels: S-waiting-on-review

#12833 Rephrase and expand `empty_enum` documentation.
  clippy_lints/src/empty_enum.rs
Labels: S-waiting-on-review

#12841 fulfill expectations in `check_partial_eq_without_eq`
  clippy_lints/src/derive.rs
  tests/ui/derive_partial_eq_without_eq.fixed
  tests/ui/derive_partial_eq_without_eq.rs
  tests/ui/derive_partial_eq_without_eq.stderr
Labels: S-waiting-on-review

#12836 feat: `Quick Fix` for `bare URLs`
  clippy_lints/src/doc/markdown.rs
  tests/ui/doc/doc-fixable.fixed
  tests/ui/doc/doc-fixable.rs
  tests/ui/doc/doc-fixable.stderr
Labels: S-waiting-on-review

#12809 Correctly handle closing parens in `missing_backticks` doc lint
  clippy_lints/src/doc/markdown.rs
  tests/ui/doc/issue_12795.fixed
  tests/ui/doc/issue_12795.rs
  tests/ui/doc/issue_12795.stderr
Labels: S-waiting-on-review

#12740 `significant_drop_in_scrutinee`: Trigger lint only if lifetime allows early significant drop
  clippy_lints/src/matches/significant_drop_in_scrutinee.rs
  tests/ui/significant_drop_in_scrutinee.rs
  tests/ui/significant_drop_in_scrutinee.stderr
Labels: S-waiting-on-review

#12842 add parentheses to [`let_and_return`]'s suggestion
  clippy_lints/src/dereference.rs
  clippy_lints/src/needless_bool.rs
  clippy_lints/src/returns.rs
  clippy_utils/src/lib.rs
  tests/ui/let_and_return.fixed
  tests/ui/let_and_return.rs
  tests/ui/let_and_return.stderr
  tests/ui/needless_return.fixed
  tests/ui/needless_return.rs
  tests/ui/needless_return.stderr
Labels: S-waiting-on-review

#12852 book: Fix example code
  book/src/configuration.md
Labels: S-waiting-on-review

#12843 Fix `unnecessary_to_owned` interaction with macro expansion
  clippy_lints/src/methods/unnecessary_iter_cloned.rs
  clippy_lints/src/methods/utils.rs
  tests/ui/unnecessary_iter_cloned.fixed
  tests/ui/unnecessary_iter_cloned.rs
  tests/ui/unnecessary_iter_cloned.stderr
  tests/ui/unnecessary_to_owned.stderr
Labels: S-waiting-on-review

#12823 Suppress `iter_on_empty_collections` if the iterator's concrete type is relied upon
  clippy_lints/src/methods/iter_on_single_or_empty_collections.rs
  tests/ui/iter_on_empty_collections.fixed
  tests/ui/iter_on_empty_collections.rs
  tests/ui/iter_on_empty_collections.stderr
Labels: S-waiting-on-review

#12867 Rustup
  clippy_dev/src/lib.rs
  clippy_lints/src/derive.rs
  clippy_lints/src/doc/missing_headers.rs
  clippy_lints/src/doc/mod.rs
  clippy_lints/src/eta_reduction.rs
  clippy_lints/src/functions/misnamed_getters.rs
  clippy_lints/src/functions/not_unsafe_ptr_arg_deref.rs
  clippy_lints/src/inherent_to_string.rs
  clippy_lints/src/iter_without_into_iter.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/needless_collect.rs
  clippy_lints/src/multiple_unsafe_ops_per_block.rs
  clippy_lints/src/new_without_default.rs
  clippy_lints/src/ptr.rs
  clippy_lints/src/transmute/transmute_undefined_repr.rs
  clippy_lints/src/undocumented_unsafe_blocks.rs
  clippy_utils/src/ast_utils.rs
  clippy_utils/src/check_proc_macro.rs
  clippy_utils/src/consts.rs
  clippy_utils/src/diagnostics.rs
  clippy_utils/src/hir_utils.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/mir/possible_borrower.rs
  clippy_utils/src/qualify_min_const_fn.rs
  clippy_utils/src/ty.rs
  clippy_utils/src/ty/type_certainty/mod.rs
  clippy_utils/src/visitors.rs
  rust-toolchain
  src/driver.rs
  tests/compile-test.rs
  tests/dogfood.rs
  tests/lint_message_convention.rs
  tests/ui-internal/disallow_span_lint.rs
  tests/ui-internal/disallow_span_lint.stderr
  tests/ui/arithmetic_side_effects.stderr
  tests/ui/into_iter_on_ref.fixed
  tests/ui/into_iter_on_ref.rs
  tests/ui/into_iter_on_ref.stderr
  tests/ui/ptr_arg.rs
  tests/workspace.rs
Labels: S-waiting-on-review

#12864 ignore array from `deref_addrof` lint
  clippy_lints/src/reference.rs
  tests/ui/deref_addrof.fixed
  tests/ui/deref_addrof.rs
  tests/ui/deref_addrof.stderr
Labels: S-waiting-on-review

#12857 fix: let non_canonical_impls skip proc marco
  clippy_lints/src/non_canonical_impls.rs
  tests/ui/auxiliary/proc_macro_derive.rs
  tests/ui/non_canonical_clone_impl.fixed
  tests/ui/non_canonical_clone_impl.rs
  tests/ui/non_canonical_clone_impl.stderr
Labels: S-waiting-on-review

#12865 fix [`redundant_closure`] suggesting incorrect code with `F: Fn()`
  clippy_lints/src/eta_reduction.rs
  tests/ui/eta.fixed
  tests/ui/eta.rs
  tests/ui/eta.stderr
Labels: S-waiting-on-review

#12488 Disable `indexing_slicing` for custom Index impls
  clippy_lints/src/indexing_slicing.rs
  clippy_lints/src/iter_without_into_iter.rs
  clippy_utils/src/ty.rs
  tests/ui/indexing_slicing_slice.rs
  tests/ui/indexing_slicing_slice.stderr
Labels: S-waiting-on-review
