Repository rust-lang/rust-clippy, pull requests merged in 2024-02, with the labels that each got.

#12217 Fixed FP in `unused_io_amount` for Ok(lit), unrachable! and unwrap de…
  clippy_lints/src/unused_io_amount.rs
  tests/ui/unused_io_amount.rs
  tests/ui/unused_io_amount.stderr
Labels: S-waiting-on-review

#12219 Avoid deleting labeled blocks
  clippy_lints/src/no_effect.rs
  tests/ui/unnecessary_operation.fixed
  tests/ui/unnecessary_operation.rs
Labels: S-waiting-on-review

#12224 Changelog for Clippy 1.76 🐈
  CHANGELOG.md
  clippy_lints/src/doc/mod.rs
  clippy_lints/src/iter_over_hash_type.rs
  clippy_lints/src/loops/mod.rs
  clippy_lints/src/repeat_vec_with_capacity.rs
Labels: S-waiting-on-review

#11919 new lint: `manual_c_str_literals`
  CHANGELOG.md
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  clippy_config/src/msrvs.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/methods/manual_c_str_literals.rs
  clippy_lints/src/methods/mod.rs
  tests/ui/manual_c_str_literals.fixed
  tests/ui/manual_c_str_literals.rs
  tests/ui/manual_c_str_literals.stderr
  tests/ui/strlen_on_c_strings.fixed
  tests/ui/strlen_on_c_strings.rs
Labels: S-waiting-on-review

#12227 [`redundant_locals`]: take by-value closure captures into account
  clippy_lints/src/redundant_locals.rs
  tests/ui/redundant_locals.rs
  tests/ui/redundant_locals.stderr
Labels: S-waiting-on-review

#12235 Fix release year in CHANGELOG.md
  CHANGELOG.md
Labels: S-waiting-on-review

#11812 Return `Some` from `walk_to_expr_usage` more
  clippy_utils/src/lib.rs
  clippy_utils/src/ty.rs
  tests/ui/ignored_unit_patterns.fixed
  tests/ui/ignored_unit_patterns.rs
  tests/ui/ignored_unit_patterns.stderr
  tests/ui/needless_borrow.fixed
  tests/ui/needless_borrow.rs
  tests/ui/needless_borrow.stderr
  tests/ui/while_let_on_iterator.fixed
  tests/ui/while_let_on_iterator.rs
  tests/ui/while_let_on_iterator.stderr
Labels: S-waiting-on-review

#12216 Fix false positive in `redundant_type_annotations` lint
  clippy_lints/src/redundant_type_annotations.rs
  tests/ui/redundant_type_annotations.rs
  tests/ui/redundant_type_annotations.stderr
Labels: S-waiting-on-review

#12177 [`unconditional_recursion`]: compare by `Ty`s instead of `DefId`s
  clippy_lints/src/unconditional_recursion.rs
  tests/ui/unconditional_recursion.rs
Labels: S-waiting-on-review

#12246 Rustup
  Cargo.toml
  clippy_config/Cargo.toml
  clippy_dev/src/update_lints.rs
  clippy_lints/Cargo.toml
  clippy_lints/src/dereference.rs
  clippy_lints/src/methods/iter_nth_zero.rs
  clippy_lints/src/min_ident_chars.rs
  clippy_lints/src/operators/arithmetic_side_effects.rs
  clippy_lints/src/returns.rs
  clippy_lints/src/transmute/transmute_int_to_non_zero.rs
  clippy_lints/src/transmute/utils.rs
  clippy_lints/src/utils/author.rs
  clippy_utils/Cargo.toml
  declare_clippy_lint/Cargo.toml
  rust-toolchain
  tests/ui/author/blocks.stdout
  tests/ui/crashes/ice-6254.rs
  tests/ui/crashes/ice-6254.stderr
  tests/ui/expect_tool_lint_rfc_2383.rs
  tests/ui/expect_tool_lint_rfc_2383.stderr
  tests/ui/modulo_one.rs
  tests/ui/modulo_one.stderr
  tests/ui/same_name_method.rs
  tests/ui/same_name_method.stderr
Labels: S-waiting-on-review

#12251 Temporary review vacation to focus on performance
  triagebot.toml
Labels: S-waiting-on-review

#12070 Fix issue #12034: add autofixes for unnecessary_fallible_conversions
  clippy_lints/src/methods/unnecessary_fallible_conversions.rs
  tests/ui/unnecessary_fallible_conversions.fixed
  tests/ui/unnecessary_fallible_conversions.rs
  tests/ui/unnecessary_fallible_conversions.stderr
Labels: S-waiting-on-review

#12258 [`similar_names`]: don't raise if the first character is different
  clippy_lints/src/item_name_repetitions.rs
  clippy_lints/src/non_expressive_names.rs
  clippy_lints/src/operators/double_comparison.rs
  clippy_lints/src/operators/op_ref.rs
  clippy_utils/src/ast_utils.rs
  clippy_utils/src/hir_utils.rs
  clippy_utils/src/qualify_min_const_fn.rs
  tests/ui/approx_const.rs
  tests/ui/approx_const.stderr
  tests/ui/similar_names.rs
  tests/ui/similar_names.stderr
Labels: S-waiting-on-review

#12264 [`to_string_trait_impl`]: avoid linting if the impl is a specialization
  clippy_lints/src/to_string_trait_impl.rs
  tests/ui/to_string_trait_impl.rs
  tests/ui/to_string_trait_impl.stderr
Labels: S-waiting-on-review

#12261 Don't lint `incompatible_msrv` in test code
  clippy_lints/src/incompatible_msrv.rs
  tests/ui/incompatible_msrv.rs
Labels: S-waiting-on-review

#12272 Fix broken URL in `Lint Configuration`
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
Labels: S-waiting-on-review

#12040 stop linting [`blocks_in_conditions`] on `match` with weird attr macro case
  clippy_lints/src/blocks_in_conditions.rs
  tests/ui/auxiliary/proc_macro_attr.rs
  tests/ui/blocks_in_conditions.fixed
  tests/ui/blocks_in_conditions.rs
  tests/ui/blocks_in_conditions.stderr
Labels: S-waiting-on-review

#12269 Refactor `implied_bounds_in_impls` lint
  clippy_lints/src/implied_bounds_in_impls.rs
Labels: S-waiting-on-review

#12274 Minor refactor format-impls
  clippy_lints/src/format_impl.rs
Labels: S-waiting-on-review

#12231 Add y21 to the review rotation
  triagebot.toml
Labels: S-waiting-on-review

#12248 Extend `NONMINIMAL_BOOL` lint
  clippy_lints/src/booleans.rs
  tests/ui/bool_comparison.fixed
  tests/ui/bool_comparison.rs
  tests/ui/nonminimal_bool.rs
  tests/ui/nonminimal_bool.stderr
Labels: S-waiting-on-review

#12267 Don't allow derive macros to silence `disallowed_macros`
  clippy_lints/src/disallowed_macros.rs
  tests/ui-toml/disallowed_macros/auxiliary/proc_macros.rs
  tests/ui-toml/disallowed_macros/clippy.toml
  tests/ui-toml/disallowed_macros/disallowed_macros.rs
  tests/ui-toml/disallowed_macros/disallowed_macros.stderr
Labels: S-waiting-on-review

#12266 fix: ICE when array index exceeds usize
  clippy_lints/src/indexing_slicing.rs
  tests/ui/crashes/ice-12253.rs
Labels: S-waiting-on-review, beta-nominated

#12283 Minor refactor format-args
  clippy_lints/src/format_args.rs
Labels: S-waiting-on-review

#12278 [`mem_replace_with_default`] No longer triggers on unused expression
  clippy_lints/src/mem_replace.rs
  tests/ui/mem_replace.fixed
  tests/ui/mem_replace.rs
  tests/ui/mem_replace.stderr
  tests/ui/mem_replace_macro.rs
  tests/ui/mem_replace_macro.stderr
Labels: S-waiting-on-review

#11881 [`implied_bounds_in_impls`]: avoid linting on overlapping associated tys
  clippy_lints/src/implied_bounds_in_impls.rs
  tests/ui/implied_bounds_in_impls.fixed
  tests/ui/implied_bounds_in_impls.rs
  tests/ui/implied_bounds_in_impls.stderr
Labels: S-waiting-on-review

#12275 [`incompatible_msrv`]: allow expressions that come from desugaring
  clippy_lints/src/incompatible_msrv.rs
  tests/ui/incompatible_msrv.rs
  tests/ui/incompatible_msrv.stderr
Labels: S-waiting-on-review

#12285 Ignore imported items in `min_ident_chars`
  clippy_lints/src/min_ident_chars.rs
  tests/ui-toml/min_ident_chars/auxiliary/extern_types.rs
  tests/ui-toml/min_ident_chars/min_ident_chars.rs
  tests/ui-toml/min_ident_chars/min_ident_chars.stderr
Labels: S-waiting-on-review

#12293 [`case_sensitive_file_extension_comparisons`]: Don't trigger on digits-only extensions
  clippy_lints/src/methods/case_sensitive_file_extension_comparisons.rs
  tests/ui/case_sensitive_file_extension_comparisons.fixed
  tests/ui/case_sensitive_file_extension_comparisons.rs
Labels: S-waiting-on-review

#12296 fix: documentation of `blocks_in_conditions` lint
  clippy_lints/src/blocks_in_conditions.rs
Labels: S-waiting-on-review

#10903 [`new_without_default`]: Now emits on const fns
  clippy_lints/src/new_without_default.rs
  tests/ui/new_without_default.fixed
  tests/ui/new_without_default.rs
  tests/ui/new_without_default.stderr
Labels: S-waiting-on-author

#12294 Check trait items in `min_ident_chars`
  clippy_lints/src/min_ident_chars.rs
  tests/ui/min_ident_chars.rs
  tests/ui/min_ident_chars.stderr
Labels: S-waiting-on-review

#12305 Ensure ASM syntax detect `global_asm!` and `asm!` only on x86 architectures
  clippy_lints/src/asm_syntax.rs
  tests/ui/asm_syntax.stderr
  tests/ui/asm_syntax_not_x86.rs
  tests/ui/asm_syntax_x86.i686.stderr
  tests/ui/asm_syntax_x86.rs
  tests/ui/asm_syntax_x86.x86_64.stderr
Labels: S-waiting-on-review

#12309 fix: make `#[allow]` work on field for `pub_underscore_fields`
  clippy_lints/src/pub_underscore_fields.rs
  tests/ui-toml/pub_underscore_fields/pub_underscore_fields.rs
Labels: S-waiting-on-review

#12313 Upgrade anstream to 0.6.0
  Cargo.toml
Labels: S-waiting-on-review

#12059 Fix issue 11223: add check for identical guards in lint `match_same_arms`
  clippy_lints/src/casts/cast_possible_truncation.rs
  clippy_lints/src/matches/match_same_arms.rs
  tests/ui/match_same_arms2.rs
  tests/ui/match_same_arms2.stderr
Labels: S-waiting-on-review

#12314 Default test output conflict handling to error
  tests/compile-test.rs
Labels: S-waiting-on-review

#12323 Fix: no_effect_underscore_binding fires on ignored parameters of async fns
  clippy_lints/src/no_effect.rs
  tests/ui/no_effect_async_fn.rs
  tests/ui/no_effect_async_fn.stderr
Labels: S-waiting-on-review

#12324 Extend `unnecessary_to_owned` to handle `Borrow` trait in map types
  clippy_config/src/conf.rs
  clippy_lints/src/methods/unnecessary_to_owned.rs
  clippy_lints/src/min_ident_chars.rs
  tests/ui/unnecessary_to_owned.fixed
  tests/ui/unnecessary_to_owned.rs
  tests/ui/unnecessary_to_owned.stderr
Labels: S-waiting-on-review

#12317 Add check for 'in_external_macro' and 'is_from_proc_macro' inside
  clippy_lints/src/loops/infinite_loop.rs
  tests/ui/infinite_loops.rs
  tests/ui/infinite_loops.stderr
Labels: S-waiting-on-review

#12303 Add `unnecessary_clippy_cfg` lint
  CHANGELOG.md
  clippy_lints/src/attrs.rs
  clippy_lints/src/declared_lints.rs
  tests/ui/unnecessary_clippy_cfg.rs
  tests/ui/unnecessary_clippy_cfg.stderr
Labels: S-waiting-on-review

#12332 Coming back to reviewer rotation
  triagebot.toml
Labels: S-waiting-on-review

#12333 Allow unused_imports, and unused_import_braces on `use`
  clippy_lints/src/attrs.rs
  tests/ui/useless_attribute.fixed
  tests/ui/useless_attribute.rs
Labels: S-waiting-on-review

#12322 Be careful with expressions with attributes
  clippy_lints/src/unused_unit.rs
  tests/ui/unused_unit.fixed
  tests/ui/unused_unit.rs
Labels: S-waiting-on-review

#12259 Add new `multiple_bound_locations` lint
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/multiple_bound_locations.rs
  tests/ui/multiple_bound_locations.rs
  tests/ui/multiple_bound_locations.stderr
  tests/ui/trait_duplication_in_bounds_unfixable.rs
  tests/ui/trait_duplication_in_bounds_unfixable.stderr
  tests/ui/type_repetition_in_bounds.rs
  tests/ui/unnecessary_cast.fixed
  tests/ui/unnecessary_cast.rs
  tests/ui/unnecessary_cast.stderr
Labels: S-waiting-on-review

#12345 Pause PR assignments for xFrednet :)
  triagebot.toml
Labels: S-waiting-on-review

#12346 bump itertools to 0.12
  Cargo.toml
  clippy_dev/Cargo.toml
  clippy_lints/Cargo.toml
  clippy_utils/Cargo.toml
  declare_clippy_lint/Cargo.toml
Labels: S-waiting-on-review

#12339 Add new `unnecessary_get_then_check` lint
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/unnecessary_get_then_check.rs
  lintcheck/src/main.rs
  tests/ui/iter_filter_is_some.fixed
  tests/ui/iter_filter_is_some.rs
  tests/ui/iter_filter_is_some.stderr
  tests/ui/unnecessary_get_then_check.fixed
  tests/ui/unnecessary_get_then_check.rs
  tests/ui/unnecessary_get_then_check.stderr
Labels: S-waiting-on-review

#12336 FIX(12243): redundant_guards
  clippy_lints/src/matches/redundant_guards.rs
  tests/ui/redundant_guards.fixed
  tests/ui/redundant_guards.rs
  tests/ui/redundant_guards.stderr
Labels: S-waiting-on-review

#12348 Remove `clippy_utils::get_parent_node`
  clippy_lints/src/box_default.rs
  clippy_lints/src/casts/unnecessary_cast.rs
  clippy_lints/src/collection_is_never_read.rs
  clippy_lints/src/dereference.rs
  clippy_lints/src/drop_forget_ref.rs
  clippy_lints/src/iter_not_returning_iterator.rs
  clippy_lints/src/matches/needless_match.rs
  clippy_lints/src/methods/clone_on_copy.rs
  clippy_lints/src/methods/needless_collect.rs
  clippy_lints/src/needless_bool.rs
  clippy_lints/src/needless_pass_by_ref_mut.rs
  clippy_lints/src/no_effect.rs
  clippy_lints/src/non_canonical_impls.rs
  clippy_lints/src/only_used_in_recursion.rs
  clippy_lints/src/question_mark.rs
  clippy_lints/src/redundant_closure_call.rs
  clippy_lints/src/strlen_on_c_strings.rs
  clippy_lints/src/undocumented_unsafe_blocks.rs
  clippy_lints/src/unit_types/let_unit_value.rs
  clippy_utils/src/lib.rs
Labels: S-waiting-on-review

#12256 Merge `single_call_fn` post-crate visitor into lint pass
  clippy_lints/src/lib.rs
  clippy_lints/src/single_call_fn.rs
  tests/ui/single_call_fn.rs
  tests/ui/single_call_fn.stderr
Labels: S-waiting-on-review

#12308 Look for `implied_bounds_in_impls` in more positions
  clippy_lints/src/implied_bounds_in_impls.rs
  tests/ui/implied_bounds_in_impls.fixed
  tests/ui/implied_bounds_in_impls.rs
  tests/ui/implied_bounds_in_impls.stderr
Labels: S-waiting-on-review

#12350 style: sync GitHub Corner colors
  util/gh-pages/index.html
Labels: S-waiting-on-review

#12353 add cargo.toml lint section way of adding lints in the book
  book/src/configuration.md
Labels: S-waiting-on-review

#12355 [`box_default`]: Preserve required path segments
  clippy_lints/src/box_default.rs
  tests/ui/box_default.fixed
  tests/ui/box_default.rs
  tests/ui/box_default.stderr
Labels: S-waiting-on-review

#12342 Empty docs
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/doc/mod.rs
  clippy_lints/src/manual_is_ascii_check.rs
  clippy_lints/src/methods/filter_map.rs
  clippy_lints/src/question_mark.rs
  clippy_lints/src/slow_vector_initialization.rs
  tests/ui/empty_docs.rs
  tests/ui/empty_docs.stderr
  tests/ui/semicolon_if_nothing_returned.fixed
  tests/ui/semicolon_if_nothing_returned.rs
  tests/ui/semicolon_if_nothing_returned.stderr
Labels: S-waiting-on-review

#12116 fix suggestion error in [`useless_vec`]
  clippy_lints/src/vec.rs
  tests/ui/vec.fixed
  tests/ui/vec.rs
  tests/ui/vec.stderr
Labels: S-waiting-on-review

#11136 [`read_line_without_trim`]: detect string literal comparison and `.ends_with()` calls
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/read_line_without_trim.rs
  tests/ui/read_line_without_trim.fixed
  tests/ui/read_line_without_trim.rs
  tests/ui/read_line_without_trim.stderr
Labels: S-waiting-on-review

#12126 Fix sign-handling bugs and false negatives in `cast_sign_loss`
  clippy_lints/src/casts/cast_sign_loss.rs
  tests/ui/cast.rs
  tests/ui/cast.stderr
Labels: S-waiting-on-review

#12363 lower `bstr` version requirement to `1.6.0`
  Cargo.toml
  tests/ui/crashes/ice-6255.rs
  tests/ui/declare_interior_mutable_const/others.rs
  tests/ui/declare_interior_mutable_const/others.stderr
  tests/ui/declare_interior_mutable_const/traits.rs
  tests/ui/declare_interior_mutable_const/traits.stderr
  tests/ui/struct_fields.rs
  tests/ui/struct_fields.stderr
  tests/ui/unconditional_recursion.rs
  tests/ui/unconditional_recursion.stderr
Labels: S-waiting-on-review

#12365 [`unnecessary_cast`]: Avoid breaking precedence
  clippy_lints/src/casts/unnecessary_cast.rs
  tests/ui/unnecessary_cast.fixed
  tests/ui/unnecessary_cast.rs
  tests/ui/unnecessary_cast.stderr
Labels: S-waiting-on-review

#12362 [`map_entry`]: Check insert expression for map use
  clippy_lints/src/entry.rs
  tests/ui/entry.fixed
  tests/ui/entry.rs
Labels: S-waiting-on-review

#12375 Improve `is_lint_level` code
  clippy_lints/src/attrs.rs
Labels: S-waiting-on-review

#12372 Fix `nonminimal_bool` lint regression
  clippy_lints/src/booleans.rs
  tests/ui/nonminimal_bool.rs
Labels: S-waiting-on-review

#12374 Show duplicate diagnostics in UI tests by default
  tests/compile-test.rs
  tests/ui-internal/custom_ice_message.stderr
  tests/ui/assign_ops2.rs
  tests/ui/assign_ops2.stderr
  tests/ui/else_if_without_else.rs
  tests/ui/else_if_without_else.stderr
  tests/ui/identity_op.fixed
  tests/ui/identity_op.rs
  tests/ui/identity_op.stderr
  tests/ui/indexing_slicing_index.rs
  tests/ui/indexing_slicing_index.stderr
  tests/ui/manual_retain.fixed
  tests/ui/manual_retain.rs
  tests/ui/manual_retain.stderr
  tests/ui/many_single_char_names.rs
  tests/ui/many_single_char_names.stderr
  tests/ui/min_rust_version_invalid_attr.rs
  tests/ui/min_rust_version_invalid_attr.stderr
  tests/ui/mut_mut.rs
  tests/ui/mut_mut.stderr
  tests/ui/no_effect_replace.rs
  tests/ui/no_effect_replace.stderr
  tests/ui/nonminimal_bool.rs
  tests/ui/nonminimal_bool.stderr
  tests/ui/nonminimal_bool_methods.fixed
  tests/ui/nonminimal_bool_methods.rs
  tests/ui/nonminimal_bool_methods.stderr
  tests/ui/option_option.rs
  tests/ui/option_option.stderr
  tests/ui/ptr_as_ptr.fixed
  tests/ui/ptr_as_ptr.rs
  tests/ui/ptr_as_ptr.stderr
  tests/ui/renamed_builtin_attr.fixed
  tests/ui/renamed_builtin_attr.rs
  tests/ui/renamed_builtin_attr.stderr
  tests/ui/single_match.fixed
  tests/ui/single_match.rs
  tests/ui/single_match.stderr
  tests/ui/single_match_else.fixed
  tests/ui/single_match_else.rs
  tests/ui/single_match_else.stderr
  tests/ui/std_instead_of_core.fixed
  tests/ui/std_instead_of_core.rs
  tests/ui/std_instead_of_core.stderr
  tests/ui/suspicious_operation_groupings.fixed
  tests/ui/suspicious_operation_groupings.rs
  tests/ui/suspicious_operation_groupings.stderr
  tests/ui/type_complexity.rs
  tests/ui/type_complexity.stderr
  tests/ui/unknown_attribute.rs
  tests/ui/unknown_attribute.stderr
Labels: S-waiting-on-review

#12380 [`redundant_closure_call`]: Don't lint if closure origins from a macro
  clippy_lints/src/redundant_closure_call.rs
  tests/ui/redundant_closure_call_fixable.fixed
  tests/ui/redundant_closure_call_fixable.rs
Labels: S-waiting-on-review

#12344 Alphabetize configuration options and lints in Clippy documentation
  CHANGELOG.md
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  clippy_config/src/metadata.rs
Labels: S-waiting-on-review

#12354 Add new `mixed_attributes_style` lint
  CHANGELOG.md
  clippy_lints/src/attrs.rs
  clippy_lints/src/declared_lints.rs
  tests/ui/empty_docs.rs
  tests/ui/empty_docs.stderr
  tests/ui/mixed_attributes_style.rs
  tests/ui/mixed_attributes_style.stderr
Labels: S-waiting-on-review

#12382 Bump macOS CI version to 13
  .github/driver.sh
  .github/workflows/clippy.yml
  .github/workflows/clippy_bors.yml
Labels: S-waiting-on-review
