Repository rust-lang/rust-clippy, pull requests merged in 2024-09, with the labels that each got.

#13325 Provide more clear example for `WRONG_SELF_CONVENTION`
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-review

#13247 Add new check for passing pointers to an `asm!` block with `nomem` option
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/pointers_in_nomem_asm_block.rs
  tests/ui/pointers_in_nomem_asm_block.rs
  tests/ui/pointers_in_nomem_asm_block.stderr
Labels: S-waiting-on-author

#13263 move `manual_c_str_literals` to complexity
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-review

#13332 Minor code simplification
  clippy_lints/src/attrs/allow_attributes_without_reason.rs
  clippy_utils/src/sugg.rs
Labels: S-waiting-on-review

#13343 Bump actions/download-artifact from 3 to 4
  .github/workflows/clippy_bors.yml
Labels: S-waiting-on-review

#13323 Changelog for Clippy 1.81 :beginner:
  CHANGELOG.md
  clippy_lints/src/byte_char_slices.rs
  clippy_lints/src/cfg_not_test.rs
  clippy_lints/src/field_scoped_visibility_modifiers.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/needless_maybe_sized.rs
  clippy_lints/src/set_contains_or_insert.rs
  clippy_lints/src/string_patterns.rs
Labels: S-waiting-on-review

#13347 Rustup
  Cargo.toml
  clippy_config/Cargo.toml
  clippy_lints/Cargo.toml
  clippy_lints/src/implied_bounds_in_impls.rs
  clippy_lints/src/methods/type_id_on_box.rs
  clippy_lints/src/needless_maybe_sized.rs
  clippy_lints/src/unused_io_amount.rs
  clippy_utils/Cargo.toml
  declare_clippy_lint/Cargo.toml
  rust-toolchain
  tests/ui/floating_point_abs.fixed
  tests/ui/floating_point_abs.rs
  tests/ui/floating_point_abs.stderr
  tests/ui/floating_point_mul_add.fixed
  tests/ui/floating_point_mul_add.rs
  tests/ui/floating_point_mul_add.stderr
  tests/ui/floating_point_rad.fixed
  tests/ui/floating_point_rad.rs
  tests/ui/floating_point_rad.stderr
  tests/ui/needless_lifetimes.stderr
  tests/ui/ptr_arg.stderr
Labels: S-waiting-on-review

#13345 Only lint `manual_non_exhaustive` for exported types
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_non_exhaustive.rs
  tests/ui/manual_non_exhaustive_enum.rs
  tests/ui/manual_non_exhaustive_enum.stderr
  tests/ui/manual_non_exhaustive_struct.rs
  tests/ui/manual_non_exhaustive_struct.stderr
Labels: S-waiting-on-review

#12987 [`manual_div_ceil`]: init
  CHANGELOG.md
  clippy_config/src/conf.rs
  clippy_config/src/msrvs.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_div_ceil.rs
  tests/ui/manual_div_ceil.fixed
  tests/ui/manual_div_ceil.rs
  tests/ui/manual_div_ceil.stderr
  tests/ui/manual_div_ceil_with_feature.fixed
  tests/ui/manual_div_ceil_with_feature.rs
  tests/ui/manual_div_ceil_with_feature.stderr
Labels: S-waiting-on-review

#13352 Correct version of `too_long_first_doc_paragraph`
  clippy_lints/src/doc/mod.rs
Labels: S-waiting-on-review

#13327 Add new lint `manual_is_power_of_two`
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_is_power_of_two.rs
  tests/ui/manual_is_power_of_two.fixed
  tests/ui/manual_is_power_of_two.rs
  tests/ui/manual_is_power_of_two.stderr
Labels: S-waiting-on-review

#13167 Added new `non_zero_suggestions` lint
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/non_zero_suggestions.rs
  tests/ui/non_zero_suggestions.fixed
  tests/ui/non_zero_suggestions.rs
  tests/ui/non_zero_suggestions.stderr
  tests/ui/non_zero_suggestions_unfixable.rs
  tests/ui/non_zero_suggestions_unfixable.stderr
Labels: S-waiting-on-review

#13214 Fix [`needless_return`] false negative
  clippy_lints/src/returns.rs
  clippy_lints/src/useless_conversion.rs
  tests/ui/needless_return.fixed
  tests/ui/needless_return.rs
  tests/ui/needless_return.stderr
Labels: S-waiting-on-review

#13324 [`single_match`, `single_match_else`] fix suggestion when match irrefutable
  clippy_lints/src/matches/single_match.rs
  tests/ui/single_match.fixed
  tests/ui/single_match.rs
  tests/ui/single_match.stderr
  tests/ui/single_match_else.fixed
  tests/ui/single_match_else.rs
  tests/ui/single_match_else.stderr
Labels: S-waiting-on-review

#13370 Fix possible typo in `ptr_arg` lint
  clippy_lints/src/ptr.rs
Labels: S-waiting-on-review

#13374 Remove unnecessary symbols and add missing symbols
  clippy_lints/src/methods/unnecessary_to_owned.rs
  tests/ui/crashes/ice-3969.rs
  tests/ui/crashes/ice-6251.rs
  tests/ui/floating_point_arithmetic_nostd.rs
  tests/ui/unsafe_removed_from_name.rs
Labels: S-waiting-on-review

#13367 Visit struct fields recursively in uninit fallback check
  clippy_utils/src/ty.rs
  tests/ui/uninit_vec.rs
  tests/ui/uninit_vec.stderr
Labels: S-waiting-on-review

#13368 Bump ui_test
  Cargo.toml
  tests/compile-test.rs
  tests/ui/asm_syntax_not_x86.rs
  tests/ui/asm_syntax_x86.rs
  tests/ui/asm_syntax_x86.stderr
  tests/ui/crashes/ice-7410.rs
  tests/ui/crate_level_checks/entrypoint_recursion.rs
  tests/ui/crate_level_checks/no_std_main_recursion.rs
  tests/ui/def_id_nocore.rs
  tests/ui/empty_loop_no_std.rs
  tests/ui/enum_clike_unportable_variant.rs
  tests/ui/macro_use_imports.fixed
  tests/ui/macro_use_imports.rs
  tests/ui/macro_use_imports_expect.rs
  tests/ui/mixed_attributes_style.rs
  tests/ui/mixed_attributes_style.stderr
  tests/ui/non_octal_unix_permissions.fixed
  tests/ui/non_octal_unix_permissions.rs
  tests/ui/result_large_err.rs
  tests/ui/single_call_fn.rs
  tests/ui/transmute_32bit.rs
  tests/ui/transmute_64bit.rs
Labels: S-waiting-on-review

#13379 Fix doc for `while_let_loop`
  clippy_lints/src/loops/mod.rs
Labels: S-waiting-on-review

#13344 Expand missing_transmute_annotations docs
  clippy_lints/src/transmute/mod.rs
Labels: S-waiting-on-review

#13369 Special-case suggestions for null pointers constness cast
  clippy_lints/src/casts/mod.rs
  clippy_lints/src/casts/ptr_cast_constness.rs
  tests/ui/ptr_cast_constness.fixed
  tests/ui/ptr_cast_constness.rs
  tests/ui/ptr_cast_constness.stderr
Labels: S-waiting-on-review

#13386 Not trigger `duplicated_attributes` on duplicate reasons
  clippy_lints/src/attrs/duplicated_attributes.rs
  tests/ui/duplicated_attributes.rs
Labels: S-waiting-on-review

#13390 Make it clearer that the suggestion is an alternative one
  clippy_lints/src/needless_pass_by_value.rs
  tests/ui/crashes/needless_pass_by_value-w-late-bound.stderr
  tests/ui/needless_pass_by_value.stderr
Labels: S-waiting-on-review

#13377 fix: Fixed incorrect comment form suggestion for too_long_first_doc_paragraph lint
  clippy_lints/src/doc/too_long_first_doc_paragraph.rs
  tests/ui/too_long_first_doc_paragraph.rs
  tests/ui/too_long_first_doc_paragraph.stderr
Labels: S-waiting-on-review

#13313 Look at adjusted types instead of fn signature types in `ptr_arg`
  clippy_lints/src/ptr.rs
  tests/ui/ptr_arg.rs
  tests/ui/ptr_arg.stderr
Labels: S-waiting-on-review

#13382 [`missing_panics_doc`] Fix #13381
  clippy_lints/src/panic_in_result_fn.rs
  tests/ui/panic_in_result_fn.rs
Labels: S-waiting-on-review

#13415 End my vacation
  triagebot.toml
Labels: S-waiting-on-review

#13414 Generate versions HTML directly
  .github/deploy.sh
  util/gh-pages/versions.html
  util/versions.py
Labels: S-waiting-on-review

#13421 Initial impl of `unnecessary_first_then_check`
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/unnecessary_first_then_check.rs
  tests/ui/unnecessary_first_then_check.fixed
  tests/ui/unnecessary_first_then_check.rs
  tests/ui/unnecessary_first_then_check.stderr
Labels: S-waiting-on-review

#13384 Remove unused `collect_metadata` function
  tests/dogfood.rs
Labels: S-waiting-on-review

#13392 Clarify example for `type_complexity`
  clippy_lints/src/types/mod.rs
Labels: S-waiting-on-review

#13409 Fix `if_then_some_else_none` sugg missing closure intro
  clippy_lints/src/if_then_some_else_none.rs
  tests/ui/if_then_some_else_none.fixed
  tests/ui/if_then_some_else_none.rs
  tests/ui/if_then_some_else_none.stderr
Labels: S-waiting-on-review

#13322 Unused trait imports (formerly anonymous trait import)
  CHANGELOG.md
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  clippy_config/src/msrvs.rs
  clippy_lints/src/attrs/useless_attribute.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/unused_trait_names.rs
  tests/ui/unused_trait_names.fixed
  tests/ui/unused_trait_names.rs
  tests/ui/unused_trait_names.stderr
Labels: S-final-comment-period

#13408 Build quine-mc_cluskey with `opt-level=3` in dev builds
  Cargo.toml
Labels: S-waiting-on-review

#13439 Use contiguous spans for empty_line_after_* suggestion
  clippy_lints/src/doc/empty_line_after.rs
  tests/ui/empty_line_after/outer_attribute.1.fixed
  tests/ui/empty_line_after/outer_attribute.2.fixed
  tests/ui/empty_line_after/outer_attribute.rs
  tests/ui/empty_line_after/outer_attribute.stderr
Labels: S-waiting-on-review, I-sync-blocker

#13431 Split def_path_res into two parts
  clippy_lints/src/regex.rs
  clippy_utils/src/lib.rs
Labels: S-waiting-on-review

#13432 Lint comparison to empty slice using `PartialEq` methods
  clippy_lints/src/len_zero.rs
  tests/ui/comparison_to_empty.fixed
  tests/ui/comparison_to_empty.rs
  tests/ui/comparison_to_empty.stderr
Labels: S-waiting-on-review

#13446 Update actions/setup-node to v4
  .github/workflows/remark.yml
Labels: S-waiting-on-review

#13452 `invalid_null_ptr_usage`: fix false positives for `std::ptr::slice_from_raw_parts` functions
  clippy_lints/src/ptr.rs
  tests/ui/invalid_null_ptr_usage.fixed
  tests/ui/invalid_null_ptr_usage.rs
  tests/ui/invalid_null_ptr_usage.stderr
Labels: S-waiting-on-review

#13453 Use std_or_core to determine the correct prefix
  clippy_lints/src/casts/borrow_as_ptr.rs
  clippy_lints/src/casts/ref_as_ptr.rs
  clippy_lints/src/loops/missing_spin_loop.rs
Labels: S-waiting-on-review

#13393 fix: Specifying reason in expect(clippy::needless_return) no longer triggers false positive
  clippy_lints/src/returns.rs
  tests/ui/needless_return.fixed
  tests/ui/needless_return.rs
Labels: S-waiting-on-review

#13456 fix(clippy_lints/matches): wildcard_in_or_patterns will no longer be triggered for types annotated with #[nonexhaustive]
  clippy_lints/src/matches/mod.rs
  clippy_lints/src/matches/wild_in_or_pats.rs
  tests/ui/wild_in_or_pats.rs
  tests/ui/wild_in_or_pats.stderr
Labels: S-waiting-on-review

#13468 Ignore `--print`/`-Vv` requests in `clippy-driver`
  src/driver.rs
Labels: S-waiting-on-review

#13471 Remove method call receiver special casing in `unused_async` lint
  clippy_lints/src/unused_async.rs
  tests/ui/unused_async.rs
  tests/ui/unused_async.stderr
Labels: S-waiting-on-review

#13336 Suggest `Option<&T>` instead of `&Option<T>`
  CHANGELOG.md
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/functions/mod.rs
  clippy_lints/src/functions/ref_option.rs
  tests/ui/ref_option/all/clippy.toml
  tests/ui/ref_option/private/clippy.toml
  tests/ui/ref_option/ref_option.all.fixed
  tests/ui/ref_option/ref_option.all.stderr
  tests/ui/ref_option/ref_option.private.fixed
  tests/ui/ref_option/ref_option.private.stderr
  tests/ui/ref_option/ref_option.rs
  tests/ui/ref_option/ref_option_traits.all.stderr
  tests/ui/ref_option/ref_option_traits.private.stderr
  tests/ui/ref_option/ref_option_traits.rs
Labels: S-waiting-on-review

#13469 Convert `&Option<T>` to `Option<&T>`
  clippy_lints/src/cargo/common_metadata.rs
  clippy_lints/src/functions/mod.rs
  clippy_lints/src/unnested_or_patterns.rs
  clippy_utils/src/ast_utils.rs
  clippy_utils/src/hir_utils.rs
  lintcheck/src/main.rs
  src/driver.rs
Labels: S-waiting-on-review
