Repository rust-lang/rust-clippy, pull requests merged in 2024-10, with the labels that each got.

#13462 `zombie_processes`: consider `wait()` calls in nested bodies
  clippy_lints/src/zombie_processes.rs
  tests/ui/zombie_processes.rs
Labels: S-waiting-on-review

#13122 Fix `mut_mutex_lock` when reference not ultimately mutable
  clippy_lints/src/methods/mut_mutex_lock.rs
  tests/ui/mut_mutex_lock.fixed
  tests/ui/mut_mutex_lock.rs
  tests/ui/mut_mutex_lock.stderr
Labels: S-waiting-on-review

#13443 Simplify negative `Option::{is_some_and,is_none_or}`
  clippy_config/src/msrvs.rs
  clippy_lints/src/booleans.rs
  clippy_lints/src/lib.rs
  tests/ui/nonminimal_bool_methods.fixed
  tests/ui/nonminimal_bool_methods.rs
  tests/ui/nonminimal_bool_methods.stderr
  tests/ui/nonminimal_bool_methods_unfixable.rs
  tests/ui/nonminimal_bool_methods_unfixable.stderr
Labels: S-waiting-on-review

#13493 Compare trait references in `trait_duplication_in_bounds` correctly
  clippy_lints/src/trait_bounds.rs
  clippy_utils/src/hir_utils.rs
  tests/ui/trait_duplication_in_bounds.fixed
  tests/ui/trait_duplication_in_bounds.rs
  tests/ui/trait_duplication_in_bounds.stderr
Labels: S-waiting-on-review

#13505 lintcheck: bump futures* crates to 0.3.31
  lintcheck/ci_crates.toml
Labels: S-waiting-on-review

#13412 Implement lint for regex::Regex compilation inside a loop
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/regex.rs
  tests/ui/regex.rs
  tests/ui/regex.stderr
Labels: S-final-comment-period

#13485 Reduce default 'large array' threshold
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  clippy_lints/src/large_stack_arrays.rs
  clippy_lints/src/methods/mod.rs
  tests/ui-toml/array_size_threshold/array_size_threshold.stderr
  tests/ui/large_const_arrays.fixed
  tests/ui/large_const_arrays.rs
  tests/ui/large_stack_arrays.rs
  tests/ui/large_stack_arrays.stderr
Labels: S-waiting-on-review

#13506 unused_result_ok: added in Clippy 1.82.0, not 1.70.0
  clippy_lints/src/unused_result_ok.rs
Labels: S-waiting-on-review

#13513 Style: do not defensively use `saturating_sub()`
  clippy_lints/src/loops/infinite_loop.rs
Labels: S-waiting-on-review

#13496 Show interior mutability chain in `mutable_key_type`
  clippy_lints/src/mut_key.rs
  clippy_utils/src/ty.rs
  tests/ui/mut_key.stderr
Labels: S-waiting-on-review

#13329 rustc_tools_util: rerun when git commit changes
  Cargo.toml
  rustc_tools_util/CHANGELOG.md
  rustc_tools_util/Cargo.toml
  rustc_tools_util/README.md
  rustc_tools_util/src/lib.rs
Labels: S-waiting-on-review

#13512 `infinite_loop`: continuing an outer loop leaves the inner loop
  clippy_lints/src/loops/infinite_loop.rs
  tests/ui/infinite_loops.rs
  tests/ui/infinite_loops.stderr
Labels: S-waiting-on-review

#13504 Check for needless raw strings in `format_args!()` template as well
  clippy_dev/src/new_lint.rs
  clippy_lints/src/raw_strings.rs
  clippy_lints/src/rc_clone_in_vec_init.rs
  lintcheck/src/json.rs
  tests/config-metadata.rs
  tests/ui/needless_raw_string.fixed
  tests/ui/needless_raw_string.rs
  tests/ui/needless_raw_string.stderr
  tests/ui/needless_raw_string_hashes.fixed
  tests/ui/needless_raw_string_hashes.rs
  tests/ui/needless_raw_string_hashes.stderr
Labels: S-waiting-on-review

#13464 Don't warn on proc macro generated code in `needless_return`
  clippy_lints/src/returns.rs
  clippy_utils/src/check_proc_macro.rs
  tests/ui/dbg_macro/dbg_macro.fixed
  tests/ui/dbg_macro/dbg_macro.rs
  tests/ui/needless_return.fixed
  tests/ui/needless_return.rs
  tests/ui/needless_return.stderr
Labels: S-waiting-on-review, beta-nominated

#13530 Back from burnout
  triagebot.toml
Labels: S-waiting-on-review

#13533 Fix span issue on `implicit_saturating_sub`
  clippy_lints/src/implicit_saturating_sub.rs
  tests/ui/implicit_saturating_sub.fixed
  tests/ui/implicit_saturating_sub.rs
  tests/ui/implicit_saturating_sub.stderr
  tests/ui/manual_arithmetic_check.fixed
  tests/ui/manual_arithmetic_check.stderr
Labels: S-waiting-on-review

#13534 Fix large_stack_arrays triggering when nesting const items
  clippy_lints/src/large_stack_arrays.rs
  tests/ui/large_stack_arrays.rs
  tests/ui/large_stack_arrays.stderr
Labels: S-waiting-on-review

#13532 Only emit `manual_c_str_literals` in >= Edition 2021
  clippy_lints/src/methods/manual_c_str_literals.rs
  tests/ui/manual_c_str_literals.edition2021.fixed
  tests/ui/manual_c_str_literals.edition2021.stderr
  tests/ui/manual_c_str_literals.rs
Labels: S-waiting-on-review

#13269 Rewrite lints page
  .github/deploy.sh
  .gitignore
  Cargo.toml
  clippy_dev/src/serve.rs
  rinja.toml
  tests/compile-test.rs
  util/gh-pages/index.html
  util/gh-pages/index_template.html
  util/gh-pages/script.js
  util/gh-pages/style.css
  util/gh-pages/theme.js
Labels: S-waiting-on-review

#13528 Improved wording of or_fun_call lint
  clippy_lints/src/methods/expect_fun_call.rs
  clippy_lints/src/methods/or_fun_call.rs
  tests/ui/expect_fun_call.stderr
  tests/ui/or_fun_call.fixed
  tests/ui/or_fun_call.rs
  tests/ui/or_fun_call.stderr
  tests/ui/unwrap_or.fixed
  tests/ui/unwrap_or.rs
  tests/ui/unwrap_or.stderr
Labels: S-waiting-on-review

#13537 Mark unnecessary_first_then_check and byte_char_slices as Applicable
  clippy_lints/src/byte_char_slices.rs
  clippy_lints/src/methods/unnecessary_first_then_check.rs
Labels: S-waiting-on-review

#13510 Cleanup `const_float_classify`
  clippy_config/src/msrvs.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_float_methods.rs
  tests/ui/manual_float_methods.rs
  tests/ui/manual_float_methods.stderr
Labels: S-waiting-on-review

#13540 Check MethodCall/Call arg count earlier or at all
  clippy_lints/src/box_default.rs
  clippy_lints/src/casts/cast_abs_to_unsigned.rs
  clippy_lints/src/casts/cast_ptr_alignment.rs
  clippy_lints/src/create_dir.rs
  clippy_lints/src/default.rs
  clippy_lints/src/exit.rs
  clippy_lints/src/explicit_write.rs
  clippy_lints/src/floating_point_arithmetic.rs
  clippy_lints/src/format_impl.rs
  clippy_lints/src/if_let_mutex.rs
  clippy_lints/src/large_futures.rs
  clippy_lints/src/len_zero.rs
  clippy_lints/src/loops/manual_while_let_some.rs
  clippy_lints/src/loops/same_item_push.rs
  clippy_lints/src/main_recursion.rs
  clippy_lints/src/manual_bits.rs
  clippy_lints/src/manual_is_power_of_two.rs
  clippy_lints/src/manual_slice_size_calculation.rs
  clippy_lints/src/manual_string_new.rs
  clippy_lints/src/matches/redundant_pattern_match.rs
  clippy_lints/src/matches/try_err.rs
  clippy_lints/src/methods/clone_on_copy.rs
  clippy_lints/src/methods/iter_filter.rs
  clippy_lints/src/methods/manual_c_str_literals.rs
  clippy_lints/src/methods/manual_saturating_arithmetic.rs
  clippy_lints/src/methods/map_clone.rs
  clippy_lints/src/methods/needless_collect.rs
  clippy_lints/src/methods/or_fun_call.rs
  clippy_lints/src/methods/read_line_without_trim.rs
  clippy_lints/src/methods/readonly_write_lock.rs
  clippy_lints/src/methods/seek_from_current.rs
  clippy_lints/src/methods/seek_to_start_instead_of_rewind.rs
  clippy_lints/src/methods/single_char_insert_string.rs
  clippy_lints/src/methods/single_char_push_string.rs
  clippy_lints/src/methods/str_splitn.rs
  clippy_lints/src/methods/uninit_assumed_init.rs
  clippy_lints/src/methods/useless_asref.rs
  clippy_lints/src/missing_asserts_for_indexing.rs
  clippy_lints/src/mut_reference.rs
  clippy_lints/src/non_canonical_impls.rs
  clippy_lints/src/non_zero_suggestions.rs
  clippy_lints/src/operators/float_cmp.rs
  clippy_lints/src/ptr_offset_with_cast.rs
  clippy_lints/src/question_mark.rs
  clippy_lints/src/returns.rs
  clippy_lints/src/significant_drop_tightening.rs
  clippy_lints/src/size_of_in_element_count.rs
  clippy_lints/src/slow_vector_initialization.rs
  clippy_lints/src/strings.rs
  clippy_lints/src/to_digit_is_some.rs
  clippy_lints/src/unit_types/unit_arg.rs
  clippy_lints/src/unnecessary_map_on_constructor.rs
  clippy_lints/src/unnecessary_owned_empty_strings.rs
  clippy_lints/src/unused_io_amount.rs
  clippy_lints/src/unwrap.rs
  clippy_lints/src/useless_conversion.rs
  clippy_lints/src/utils/internal_lints/collapsible_calls.rs
  clippy_lints/src/vec.rs
  clippy_utils/src/consts.rs
Labels: S-waiting-on-review

#13542 [`implicit_saturating_sub`] Fix suggestion with a less volatile approach
  clippy_lints/src/implicit_saturating_sub.rs
  tests/ui/implicit_saturating_sub.fixed
  tests/ui/implicit_saturating_sub.rs
  tests/ui/implicit_saturating_sub.stderr
  tests/ui/manual_arithmetic_check.fixed
  tests/ui/manual_arithmetic_check.stderr
Labels: S-waiting-on-review

#13487 Fix lint `manual_slice_size_calculation` when a slice is ref more than once
  clippy_lints/src/manual_slice_size_calculation.rs
  tests/ui/manual_slice_size_calculation.fixed
  tests/ui/manual_slice_size_calculation.rs
  tests/ui/manual_slice_size_calculation.stderr
Labels: S-waiting-on-review

#13551 Move `too_long_first_doc_paragraph` to `nursery`
  clippy_lints/src/doc/mod.rs
Labels: S-waiting-on-review, beta-nominated

#13553 Change the category of `manual_is_power_of_two` to `pedantic`
  clippy_lints/src/manual_is_power_of_two.rs
Labels: S-waiting-on-review

#13554 Documentation fixes
  clippy_lints/src/methods/mod.rs
  util/gh-pages/index_template.html
Labels: S-waiting-on-review

#13525 Changelog for Clippy 1.82 :airplane:
  CHANGELOG.md
  clippy_lints/src/pathbuf_init_then_push.rs
Labels: S-waiting-on-review

#13561 Rustup
  Cargo.toml
  clippy_config/Cargo.toml
  clippy_lints/Cargo.toml
  clippy_lints/src/attrs/allow_attributes_without_reason.rs
  clippy_lints/src/attrs/blanket_clippy_restriction_lints.rs
  clippy_lints/src/attrs/mod.rs
  clippy_lints/src/attrs/non_minimal_cfg.rs
  clippy_lints/src/attrs/useless_attribute.rs
  clippy_lints/src/attrs/utils.rs
  clippy_lints/src/cfg_not_test.rs
  clippy_lints/src/extra_unused_type_parameters.rs
  clippy_lints/src/implied_bounds_in_impls.rs
  clippy_lints/src/index_refutable_slice.rs
  clippy_lints/src/len_zero.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/lifetimes.rs
  clippy_lints/src/loops/needless_range_loop.rs
  clippy_lints/src/manual_async_fn.rs
  clippy_lints/src/matches/significant_drop_in_scrutinee.rs
  clippy_lints/src/missing_asserts_for_indexing.rs
  clippy_lints/src/missing_doc.rs
  clippy_lints/src/missing_inline.rs
  clippy_lints/src/module_style.rs
  clippy_lints/src/needless_maybe_sized.rs
  clippy_lints/src/needless_pass_by_ref_mut.rs
  clippy_lints/src/returns.rs
  clippy_lints/src/swap.rs
  clippy_lints/src/trait_bounds.rs
  clippy_lints/src/types/borrowed_box.rs
  clippy_lints/src/types/type_complexity.rs
  clippy_lints/src/use_self.rs
  clippy_lints/src/utils/internal_lints/lint_without_lint_pass.rs
  clippy_utils/Cargo.toml
  clippy_utils/src/ast_utils.rs
  clippy_utils/src/check_proc_macro.rs
  clippy_utils/src/hir_utils.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/mir/possible_borrower.rs
  clippy_utils/src/source.rs
  rust-toolchain
  tests/ui-toml/unwrap_used/unwrap_used.fixed
  tests/ui-toml/unwrap_used/unwrap_used.rs
  tests/ui-toml/unwrap_used/unwrap_used.stderr
  tests/ui/crashes/ice-12284.rs
  tests/ui/doc/doc-fixable.fixed
  tests/ui/doc/doc-fixable.rs
  tests/ui/get_unwrap.fixed
  tests/ui/get_unwrap.rs
  tests/ui/get_unwrap.stderr
  tests/ui/transmute_float_to_int.fixed
  tests/ui/transmute_float_to_int.rs
  tests/ui/transmutes_expressible_as_ptr_casts.fixed
  tests/ui/transmutes_expressible_as_ptr_casts.rs
Labels: S-waiting-on-review

#13539 Allow to go through clippy lints page without javascript
  tests/compile-test.rs
  util/gh-pages/index_template.html
  util/gh-pages/script.js
  util/gh-pages/style.css
Labels: S-waiting-on-review

#13543 Add internal lint to check for slow symbol comparisons
  book/src/development/common_tools_writing_lints.md
  book/src/development/method_checking.md
  clippy_lints/src/casts/cast_ptr_alignment.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/explicit_write.rs
  clippy_lints/src/from_raw_with_void_ptr.rs
  clippy_lints/src/implicit_hasher.rs
  clippy_lints/src/infinite_iter.rs
  clippy_lints/src/iter_without_into_iter.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_hash_one.rs
  clippy_lints/src/manual_is_ascii_check.rs
  clippy_lints/src/matches/redundant_guards.rs
  clippy_lints/src/methods/filter_map.rs
  clippy_lints/src/methods/needless_collect.rs
  clippy_lints/src/methods/read_line_without_trim.rs
  clippy_lints/src/methods/unnecessary_filter_map.rs
  clippy_lints/src/minmax.rs
  clippy_lints/src/missing_fields_in_debug.rs
  clippy_lints/src/non_octal_unix_permissions.rs
  clippy_lints/src/operators/float_cmp.rs
  clippy_lints/src/ptr_offset_with_cast.rs
  clippy_lints/src/question_mark.rs
  clippy_lints/src/slow_vector_initialization.rs
  clippy_lints/src/strings.rs
  clippy_lints/src/transmute/eager_transmute.rs
  clippy_lints/src/utils/internal_lints.rs
  clippy_lints/src/utils/internal_lints/lint_without_lint_pass.rs
  clippy_lints/src/utils/internal_lints/msrv_attr_impl.rs
  clippy_lints/src/utils/internal_lints/slow_symbol_comparisons.rs
  tests/ui-internal/slow_symbol_comparisons.fixed
  tests/ui-internal/slow_symbol_comparisons.rs
  tests/ui-internal/slow_symbol_comparisons.stderr
  tests/ui-internal/unnecessary_symbol_str.fixed
  tests/ui-internal/unnecessary_symbol_str.rs
  tests/ui-internal/unnecessary_symbol_str.stderr
Labels: S-waiting-on-review

#13564 Stop linting manual_bits in any macro invoke
  clippy_lints/src/manual_bits.rs
  tests/ui/manual_bits.fixed
  tests/ui/manual_bits.rs
Labels: S-waiting-on-review

#13569 Fix version for `ref_option`
  clippy_lints/src/functions/mod.rs
Labels: S-waiting-on-review

#13567 Add debug assertions for empty replacements and overlapping spans
  clippy_lints/src/from_over_into.rs
  clippy_lints/src/semicolon_block.rs
  clippy_utils/src/diagnostics.rs
  clippy_utils/src/lib.rs
  tests/ui/semicolon_outside_block.fixed
  tests/ui/semicolon_outside_block.rs
  tests/ui/semicolon_outside_block.stderr
Labels: S-waiting-on-review

#13570 docs: remove stray comma
  util/gh-pages/index_template.html
Labels: S-waiting-on-review

#13588 Fix not working lint anchor (generation and filtering)
  util/gh-pages/index_template.html
  util/gh-pages/script.js
Labels: S-waiting-on-review

#13460 Add units/unit prefixes of frequency to doc-valid-idents
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  tests/ui/doc/doc-fixable.fixed
  tests/ui/doc/doc-fixable.rs
  tests/ui/doc/doc-fixable.stderr
Labels: S-waiting-on-review

#13558 Don't trigger `const_is_empty` for inline const assertions
  clippy_lints/src/methods/is_empty.rs
  tests/ui/const_is_empty.rs
  tests/ui/const_is_empty.stderr
Labels: S-waiting-on-review

#13586 docs: Fix too_long_first_doc_paragraph: line -> paragraph
  clippy_lints/src/doc/mod.rs
Labels: S-waiting-on-review

#13571 Fix indentation of website code snippets
  clippy_config/src/conf.rs
Labels: S-waiting-on-review

#13605 Stop linting unused_io_amount in io traits
  clippy_lints/src/unused_io_amount.rs
  tests/ui/unused_io_amount.rs
Labels: S-waiting-on-review

#13600 borrow_deref_ref: do not trigger on `&raw` references
  clippy_lints/src/borrow_deref_ref.rs
  tests/ui/borrow_deref_ref.fixed
  tests/ui/borrow_deref_ref.rs
Labels: S-waiting-on-review, beta-nominated

#13610 Add test case for `missing_errors_doc` at tests with option `check-private-item=true`
  tests/ui-toml/private-doc-errors/doc_lints.rs
Labels: S-waiting-on-review

#13611 Unvacation giraffate and remove gh-pages -> xFrednet assignment
  triagebot.toml
Labels: S-waiting-on-review

#13548 fix: remove unnecessary filter_map usages
  clippy_lints/src/methods/unnecessary_filter_map.rs
  tests/ui/unnecessary_filter_map.rs
  tests/ui/unnecessary_filter_map.stderr
  tests/ui/unnecessary_find_map.rs
  tests/ui/unnecessary_find_map.stderr
Labels: S-waiting-on-review

#13472 Optimise Msrv for common one item case
  clippy_config/src/lib.rs
  clippy_config/src/msrvs.rs
Labels: S-waiting-on-review

#13338 fix incorrect suggestion for `!(a >= b) as i32 == c`
  clippy_lints/src/booleans.rs
  tests/ui/nonminimal_bool.stderr
  tests/ui/nonminimal_bool_methods.fixed
  tests/ui/nonminimal_bool_methods.rs
  tests/ui/nonminimal_bool_methods.stderr
Labels: S-waiting-on-review

#13614 fix: usage of `a deprecated Node.js version`
  .github/workflows/deploy.yml
Labels: S-waiting-on-review

#13620 Fire large_const_arrays for computed array lengths
  clippy_lints/src/large_const_arrays.rs
  tests/ui/large_const_arrays.fixed
  tests/ui/large_const_arrays.rs
  tests/ui/large_const_arrays.stderr
Labels: S-waiting-on-review

#13437 New lint `needless_as_bytes`
  CHANGELOG.md
  README.md
  book/src/README.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/needless_as_bytes.rs
  tests/ui/needless_as_bytes.fixed
  tests/ui/needless_as_bytes.rs
  tests/ui/needless_as_bytes.stderr
Labels: S-final-comment-period

#13499 New lint `map_all_any_identity`
  CHANGELOG.md
  clippy_lints/src/casts/unnecessary_cast.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/methods/map_all_any_identity.rs
  clippy_lints/src/methods/mod.rs
  tests/ui/map_all_any_identity.fixed
  tests/ui/map_all_any_identity.rs
  tests/ui/map_all_any_identity.stderr
Labels: S-waiting-on-author

#13034 Add new `trivial_map_over_range` lint
  CHANGELOG.md
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  clippy_config/src/msrvs.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/matches/single_match.rs
  clippy_lints/src/methods/map_with_unused_argument_over_ranges.rs
  clippy_lints/src/methods/mod.rs
  tests/ui/map_with_unused_argument_over_ranges.fixed
  tests/ui/map_with_unused_argument_over_ranges.rs
  tests/ui/map_with_unused_argument_over_ranges.stderr
  tests/ui/repeat_vec_with_capacity.fixed
  tests/ui/repeat_vec_with_capacity.rs
  tests/ui/repeat_vec_with_capacity.stderr
  tests/ui/suspicious_map.rs
  tests/ui/suspicious_map.stderr
Labels: S-waiting-on-review

#13599 Fix allow_attributes when expanded from some macros
  clippy_utils/src/check_proc_macro.rs
  tests/ui/allow_attributes.fixed
  tests/ui/allow_attributes.rs
  tests/ui/allow_attributes.stderr
  tests/ui/auxiliary/proc_macro_derive.rs
Labels: S-waiting-on-review

#13633 Add 'CoAP' to doc-valid-idents
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  tests/ui/doc/doc-fixable.fixed
  tests/ui/doc/doc-fixable.rs
Labels: S-waiting-on-review

#13636 Extend `large_include_file` lint to also work on attributes
  clippy_lints/src/large_include_file.rs
  tests/ui-toml/large_include_file/large_include_file.rs
  tests/ui-toml/large_include_file/large_include_file.stderr
Labels: S-waiting-on-review

#13628 Do not use `gen` as a variable name
  clippy_lints/src/functions/ref_option.rs
Labels: S-waiting-on-review

#13634 Cleanup code suggestion for `into_iter_without_iter`
  clippy_lints/src/iter_without_into_iter.rs
  tests/ui/iter_without_into_iter.stderr
Labels: S-waiting-on-review
