Repository rust-lang/rust-clippy, pull requests merged in 2024-08, with the labels that each got.

#13108 Fix `redundant_closure` false positive with closures has return type contains `'static`
  clippy_lints/src/eta_reduction.rs
  tests/ui/eta.fixed
  tests/ui/eta.rs
  tests/ui/eta.stderr
Labels: S-waiting-on-review

#13126 Fix [`redundant_slicing`] when the slice is behind a mutable reference
  clippy_lints/src/redundant_slicing.rs
  tests/ui/deref_by_slicing.fixed
  tests/ui/deref_by_slicing.rs
  tests/ui/deref_by_slicing.stderr
Labels: S-waiting-on-review

#13115 Remove duplicated `peel_middle_ty_refs`
  clippy_lints/src/dereference.rs
  clippy_lints/src/matches/single_match.rs
  clippy_lints/src/methods/implicit_clone.rs
  clippy_lints/src/methods/unnecessary_to_owned.rs
  clippy_lints/src/redundant_slicing.rs
  clippy_lints/src/size_of_ref.rs
  clippy_utils/src/ty.rs
Labels: S-waiting-on-review

#13107 Add test for `try_err` lint within try blocks.
  tests/ui/try_err.fixed
  tests/ui/try_err.rs
Labels: S-waiting-on-review

#13208 Add clarification for from_iter_instead_of_collect
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-review

#13209 Limit number of `nonminimal_bool` ops
  clippy_lints/src/booleans.rs
  tests/ui/nonminimal_bool.rs
Labels: S-waiting-on-review

#13194 fix-typos
  lintcheck/src/input.rs
Labels: S-waiting-on-review

#13213 Remove `multispan_sugg[_with_applicability]`
  clippy_lints/src/loops/for_kv_map.rs
  clippy_lints/src/loops/manual_while_let_some.rs
  clippy_lints/src/loops/needless_range_loop.rs
  clippy_lints/src/loops/unused_enumerate_index.rs
  clippy_lints/src/manual_strip.rs
  clippy_lints/src/matches/match_ref_pats.rs
  clippy_lints/src/methods/bind_instead_of_map.rs
  clippy_lints/src/methods/unused_enumerate_index.rs
  clippy_lints/src/needless_pass_by_value.rs
  clippy_lints/src/operators/op_ref.rs
  clippy_lints/src/semicolon_block.rs
  clippy_lints/src/utils/internal_lints/metadata_collector.rs
  clippy_utils/src/diagnostics.rs
  tests/ui/bind_instead_of_map_multipart.stderr
Labels: S-waiting-on-review

#13180 Simplify lint deprecation
  CHANGELOG.md
  clippy_dev/src/main.rs
  clippy_dev/src/serve.rs
  clippy_dev/src/update_lints.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/deprecated_lints.rs
  clippy_lints/src/lib.deprecated.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/renamed_lints.rs
  clippy_lints/src/utils/internal_lints/lint_without_lint_pass.rs
  clippy_lints/src/utils/internal_lints/metadata_collector.rs
  src/driver.rs
  tests/ui-internal/default_deprecation_reason.rs
  tests/ui-internal/default_deprecation_reason.stderr
  tests/ui/deprecated.rs
  tests/ui/deprecated.stderr
  tests/ui/deprecated_old.rs
  tests/ui/deprecated_old.stderr
  tests/ui/rename.fixed
  tests/ui/rename.rs
  tests/ui/rename.stderr
  util/gh-pages/index.html
Labels: S-waiting-on-review

#13222 Use a deterministic number of digits in rustc_tools_util commit hashes
  rustc_tools_util/src/lib.rs
Labels: S-waiting-on-review

#13210 lintcheck: force warn all lints
  .github/workflows/lintcheck.yml
  lintcheck/src/config.rs
  lintcheck/src/main.rs
Labels: S-waiting-on-review

#13225 Use `-D warnings` instead of `deny-warnings` feature.
  .github/workflows/clippy.yml
  .github/workflows/clippy_bors.yml
  .github/workflows/clippy_dev.yml
  Cargo.toml
  clippy_config/Cargo.toml
  clippy_config/src/lib.rs
  clippy_dev/Cargo.toml
  clippy_dev/src/lib.rs
  clippy_dev/src/main.rs
  clippy_lints/Cargo.toml
  clippy_lints/src/lib.rs
  clippy_utils/Cargo.toml
  clippy_utils/src/lib.rs
  declare_clippy_lint/Cargo.toml
  declare_clippy_lint/src/lib.rs
  lintcheck/Cargo.toml
  rustc_tools_util/Cargo.toml
  rustc_tools_util/src/lib.rs
  src/driver.rs
  src/main.rs
  tests/check-fmt.rs
  tests/compile-test.rs
  tests/dogfood.rs
  tests/integration.rs
  tests/lint_message_convention.rs
  tests/missing-test-files.rs
  tests/versioncheck.rs
  tests/workspace_test/path_dep/Cargo.toml
Labels: S-waiting-on-review

#12150 Add lint for `unused_result_ok`
  CHANGELOG.md
  clippy_dev/src/update_lints.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/unused_result_ok.rs
  tests/ui/unused_result_ok.fixed
  tests/ui/unused_result_ok.rs
  tests/ui/unused_result_ok.stderr
Labels: S-waiting-on-review, S-final-comment-period

#13232 Add path prefixes back when compiling `clippy_dev` and `lintcheck`
  .cargo/config.toml
Labels: S-waiting-on-review

#13234 lintcheck: disable doc links
  lintcheck/src/main.rs
Labels: S-waiting-on-review

#11441 `single_match`: fix checking of explicitly matched enums
  clippy_lints/src/matches/match_wild_enum.rs
  clippy_lints/src/matches/overlapping_arms.rs
  clippy_lints/src/matches/single_match.rs
  tests/ui-toml/excessive_nesting/excessive_nesting.rs
  tests/ui-toml/excessive_nesting/excessive_nesting.stderr
  tests/ui/crashes/ice-6254.rs
  tests/ui/patterns.fixed
  tests/ui/patterns.rs
  tests/ui/single_match.fixed
  tests/ui/single_match.rs
  tests/ui/single_match.stderr
  tests/ui/unneeded_field_pattern.rs
Labels: S-waiting-on-review

#13231 Don't walk the HIR tree when checking for a const context
  clippy_lints/src/bool_to_int_with_if.rs
  clippy_lints/src/casts/cast_lossless.rs
  clippy_lints/src/casts/zero_ptr.rs
  clippy_lints/src/checked_conversions.rs
  clippy_lints/src/comparison_chain.rs
  clippy_lints/src/doc/mod.rs
  clippy_lints/src/floating_point_arithmetic.rs
  clippy_lints/src/from_str_radix_10.rs
  clippy_lints/src/if_then_some_else_none.rs
  clippy_lints/src/manual_clamp.rs
  clippy_lints/src/manual_is_ascii_check.rs
  clippy_lints/src/manual_rem_euclid.rs
  clippy_lints/src/manual_slice_size_calculation.rs
  clippy_lints/src/manual_unwrap_or_default.rs
  clippy_lints/src/matches/match_wild_err_arm.rs
  clippy_lints/src/matches/mod.rs
  clippy_lints/src/matches/redundant_guards.rs
  clippy_lints/src/non_copy_const.rs
  clippy_lints/src/option_if_let_else.rs
  clippy_lints/src/question_mark.rs
  clippy_lints/src/ranges.rs
  clippy_lints/src/swap.rs
  clippy_lints/src/transmute/mod.rs
  clippy_utils/src/lib.rs
Labels: S-waiting-on-review

#13200 Don't use `LateContext` in the constant evaluator
  clippy_lints/src/assertions_on_constants.rs
  clippy_lints/src/casts/cast_nan_to_int.rs
  clippy_lints/src/casts/cast_possible_truncation.rs
  clippy_lints/src/casts/cast_sign_loss.rs
  clippy_lints/src/enum_clike.rs
  clippy_lints/src/floating_point_arithmetic.rs
  clippy_lints/src/if_not_else.rs
  clippy_lints/src/implicit_saturating_add.rs
  clippy_lints/src/index_refutable_slice.rs
  clippy_lints/src/indexing_slicing.rs
  clippy_lints/src/invalid_upcast_comparisons.rs
  clippy_lints/src/loops/while_immutable_condition.rs
  clippy_lints/src/manual_clamp.rs
  clippy_lints/src/manual_float_methods.rs
  clippy_lints/src/manual_rem_euclid.rs
  clippy_lints/src/manual_rotate.rs
  clippy_lints/src/manual_strip.rs
  clippy_lints/src/matches/manual_unwrap_or.rs
  clippy_lints/src/matches/overlapping_arms.rs
  clippy_lints/src/methods/is_digit_ascii_radix.rs
  clippy_lints/src/methods/is_empty.rs
  clippy_lints/src/methods/iter_nth_zero.rs
  clippy_lints/src/methods/iter_skip_zero.rs
  clippy_lints/src/methods/iterator_step_by_zero.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/repeat_once.rs
  clippy_lints/src/methods/str_splitn.rs
  clippy_lints/src/methods/unnecessary_min_or_max.rs
  clippy_lints/src/minmax.rs
  clippy_lints/src/operators/absurd_extreme_comparisons.rs
  clippy_lints/src/operators/arithmetic_side_effects.rs
  clippy_lints/src/operators/bit_mask.rs
  clippy_lints/src/operators/const_comparisons.rs
  clippy_lints/src/operators/duration_subsec.rs
  clippy_lints/src/operators/erasing_op.rs
  clippy_lints/src/operators/float_cmp.rs
  clippy_lints/src/operators/identity_op.rs
  clippy_lints/src/operators/modulo_arithmetic.rs
  clippy_lints/src/operators/numeric_arithmetic.rs
  clippy_lints/src/ranges.rs
  clippy_lints/src/regex.rs
  clippy_lints/src/repeat_vec_with_capacity.rs
  clippy_lints/src/transmute/transmute_null_to_fn.rs
  clippy_lints/src/transmute/transmuting_null.rs
  clippy_lints/src/utils/internal_lints/interning_defined_symbol.rs
  clippy_lints/src/utils/internal_lints/invalid_paths.rs
  clippy_lints/src/vec.rs
  clippy_lints/src/zero_div_zero.rs
  clippy_utils/src/consts.rs
  clippy_utils/src/eager_or_lazy.rs
  clippy_utils/src/higher.rs
  clippy_utils/src/hir_utils.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/source.rs
Labels: S-waiting-on-review

#13236 Rustup
  clippy_lints/src/lib.rs
  clippy_lints/src/lifetimes.rs
  clippy_lints/src/methods/map_clone.rs
  clippy_lints/src/methods/useless_asref.rs
  clippy_lints/src/precedence.rs
  clippy_lints/src/redundant_clone.rs
  clippy_lints/src/trait_bounds.rs
  clippy_lints/src/types/borrowed_box.rs
  clippy_lints/src/types/type_complexity.rs
  clippy_lints/src/unnecessary_wraps.rs
  clippy_utils/src/paths.rs
  rust-toolchain
  tests/compile-test.rs
  tests/ui/from_str_radix_10.fixed
  tests/ui/from_str_radix_10.rs
  tests/ui/from_str_radix_10.stderr
  tests/ui/precedence.fixed
  tests/ui/precedence.rs
  tests/ui/precedence.stderr
  tests/ui/uninit_vec.rs
  tests/ui/uninit_vec.stderr
  tests/ui/unit_return_expecting_ord.rs
  tests/ui/unit_return_expecting_ord.stderr
  tests/ui/unnecessary_cast.fixed
  tests/ui/unnecessary_cast.rs
  tests/ui/unnecessary_literal_unwrap.stderr
  tests/ui/unnecessary_wraps.stderr
Labels: S-waiting-on-review

#13211 Respect allow `inconsistent_struct_constructor` on the struct definition
  clippy_lints/src/inconsistent_struct_constructor.rs
  tests/ui/inconsistent_struct_constructor.fixed
  tests/ui/inconsistent_struct_constructor.rs
  tests/ui/inconsistent_struct_constructor.stderr
Labels: S-waiting-on-review

#13220 [`macro_metavars_in_unsafe`]: recognize metavariables in tail expressions
  clippy_lints/src/macro_metavars_in_unsafe.rs
  tests/ui-toml/macro_metavars_in_unsafe/default/test.rs
  tests/ui-toml/macro_metavars_in_unsafe/default/test.stderr
Labels: S-waiting-on-review

#13163 Fix case where doc_markdown is triggered on words ending with "ified"
  clippy_lints/src/doc/markdown.rs
  tests/ui/doc/doc_markdown-issue_13097.fixed
  tests/ui/doc/doc_markdown-issue_13097.rs
  tests/ui/doc/doc_markdown-issue_13097.stderr
Labels: S-waiting-on-review

#13250 lintcheck: key lints on line start rather than byte start/end
  lintcheck/src/json.rs
  lintcheck/src/output.rs
Labels: S-waiting-on-review

#13187 Add settings menu on clippy lints page
  .github/deploy.sh
  util/gh-pages/index.html
  util/gh-pages/script.js
  util/gh-pages/style.css
Labels: S-waiting-on-review

#13255 Remove more `snippet_opt` calls
  clippy_lints/src/attrs/empty_line_after.rs
  clippy_lints/src/attrs/non_minimal_cfg.rs
  clippy_lints/src/attrs/unnecessary_clippy_cfg.rs
  clippy_lints/src/attrs/useless_attribute.rs
  clippy_lints/src/casts/as_ptr_cast_mut.rs
  clippy_lints/src/manual_async_fn.rs
  clippy_lints/src/matches/single_match.rs
  clippy_lints/src/needless_pass_by_value.rs
  clippy_lints/src/pathbuf_init_then_push.rs
  clippy_lints/src/ptr.rs
  clippy_lints/src/ptr_offset_with_cast.rs
  clippy_lints/src/redundant_clone.rs
  clippy_lints/src/reference.rs
  clippy_lints/src/regex.rs
  clippy_lints/src/returns.rs
  clippy_lints/src/single_range_in_vec_init.rs
  clippy_lints/src/trait_bounds.rs
  clippy_lints/src/unused_unit.rs
  clippy_lints/src/visibility.rs
  clippy_lints/src/write.rs
  clippy_utils/src/consts.rs
  clippy_utils/src/hir_utils.rs
  clippy_utils/src/source.rs
Labels: S-waiting-on-review

#13261 fix code blocks in doc comments inconsistently using 3 or 4 spaces of indentation
  clippy_lints/src/doc/mod.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/utils/internal_lints/metadata_collector.rs
Labels: S-waiting-on-review

#13221 Replace the metadata collector with tests
  .cargo/config.toml
  .github/workflows/clippy_bors.yml
  Cargo.toml
  book/src/development/adding_lints.md
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  clippy_config/src/lib.rs
  clippy_dev/src/update_lints.rs
  clippy_lints/src/cargo/mod.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/doc/mod.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/min_ident_chars.rs
  clippy_lints/src/operators/arithmetic_side_effects.rs
  clippy_lints/src/utils/internal_lints.rs
  clippy_lints/src/utils/internal_lints/metadata_collector.rs
  clippy_lints/src/wildcard_imports.rs
  declare_clippy_lint/src/lib.rs
  tests/compile-test.rs
  tests/config-metadata.rs
  util/gh-pages/index.html
  util/gh-pages/script.js
Labels: S-waiting-on-review

#13265 Fix lint source location github link (missing a letter 'L')
  clippy_lints/src/attrs/mod.rs
  clippy_lints/src/operators/mod.rs
  declare_clippy_lint/src/lib.rs
Labels: S-waiting-on-review

#13253 Clarify suggestion message for unwrap lint
  clippy_lints/src/unwrap.rs
  tests/ui/checked_unwrap/complex_conditionals_nested.stderr
  tests/ui/checked_unwrap/simple_conditionals.stderr
Labels: S-waiting-on-review

#13272 flip1995: 2 week vacation
  triagebot.toml
Labels: S-waiting-on-review

#13274 Fix code snippet in from_str_radix_10 docs
  clippy_lints/src/from_str_radix_10.rs
Labels: S-waiting-on-review

#13273 Disable assigning_clones for tests
  clippy_lints/src/assigning_clones.rs
  tests/ui/assigning_clones.fixed
  tests/ui/assigning_clones.rs
Labels: S-waiting-on-review

#13248 Remove `find_format_arg_expr` AST fallback
  clippy_lints/src/format.rs
  clippy_lints/src/format_args.rs
  clippy_lints/src/format_impl.rs
  clippy_utils/src/macros.rs
Labels: S-waiting-on-review

#13284 Improve `collapsible_match` error message syntax
  clippy_lints/src/matches/collapsible_match.rs
  tests/ui/collapsible_match.stderr
Labels: S-waiting-on-review

#13278 Misc cleanup
  clippy_lints/src/attrs/mod.rs
  clippy_lints/src/cargo/common_metadata.rs
  clippy_lints/src/cargo/multiple_crate_versions.rs
  clippy_lints/src/casts/cast_possible_truncation.rs
  clippy_lints/src/casts/fn_to_numeric_cast_any.rs
  clippy_lints/src/checked_conversions.rs
  clippy_lints/src/cognitive_complexity.rs
  clippy_lints/src/collapsible_if.rs
  clippy_lints/src/collection_is_never_read.rs
  clippy_lints/src/create_dir.rs
  clippy_lints/src/doc/lazy_continuation.rs
  clippy_lints/src/doc/markdown.rs
  clippy_lints/src/else_if_without_else.rs
  clippy_lints/src/empty_enum.rs
  clippy_lints/src/enum_clike.rs
  clippy_lints/src/eta_reduction.rs
  clippy_lints/src/float_literal.rs
  clippy_lints/src/functions/impl_trait_in_params.rs
  clippy_lints/src/functions/must_use.rs
  clippy_lints/src/if_not_else.rs
  clippy_lints/src/implicit_return.rs
  clippy_lints/src/indexing_slicing.rs
  clippy_lints/src/infinite_iter.rs
  clippy_lints/src/inherent_impl.rs
  clippy_lints/src/inline_fn_without_body.rs
  clippy_lints/src/int_plus_one.rs
  clippy_lints/src/item_name_repetitions.rs
  clippy_lints/src/items_after_statements.rs
  clippy_lints/src/large_enum_variant.rs
  clippy_lints/src/legacy_numeric_constants.rs
  clippy_lints/src/literal_representation.rs
  clippy_lints/src/manual_retain.rs
  clippy_lints/src/methods/get_unwrap.rs
  clippy_lints/src/methods/is_digit_ascii_radix.rs
  clippy_lints/src/methods/needless_collect.rs
  clippy_lints/src/mut_key.rs
  clippy_lints/src/mutex_atomic.rs
  clippy_lints/src/needless_bool.rs
  clippy_lints/src/needless_continue.rs
  clippy_lints/src/non_copy_const.rs
  clippy_lints/src/ptr.rs
  clippy_lints/src/size_of_in_element_count.rs
  clippy_lints/src/utils/author.rs
  clippy_utils/src/ty.rs
Labels: S-waiting-on-review

#13288 fix false positive in explicit_iter_loop with msrv
  clippy_config/src/msrvs.rs
  clippy_lints/src/loops/explicit_iter_loop.rs
  tests/ui/explicit_iter_loop.fixed
  tests/ui/explicit_iter_loop.rs
Labels: S-waiting-on-review

#13281 Trigger [`string_slice`] if expression is reference to `&str`
  clippy_lints/src/strings.rs
  tests/ui/string_slice.rs
  tests/ui/string_slice.stderr
Labels: S-waiting-on-review

#13289 fix typo in cfg_not_test lint description
  clippy_lints/src/cfg_not_test.rs
Labels: S-waiting-on-review

#13241 Fix confusing message in double_must_use lint
  clippy_lints/src/functions/must_use.rs
  tests/ui/double_must_use.rs
  tests/ui/double_must_use.stderr
Labels: S-waiting-on-review

#13290 `declare_interior_mutable_const`: Ignore pointer types.
  clippy_lints/src/non_copy_const.rs
  tests/ui/declare_interior_mutable_const/others.rs
  tests/ui/declare_interior_mutable_const/others.stderr
Labels: S-waiting-on-review, beta-nominated

#13295 Fix a couple of typos.
  clippy_lints/src/returns.rs
  clippy_lints/src/use_self.rs
Labels: S-waiting-on-review

#13244 Start removing `snippet_opt` in favor of `get_source_text`
  clippy_lints/src/booleans.rs
  clippy_lints/src/borrow_deref_ref.rs
  clippy_lints/src/format.rs
  clippy_lints/src/format_args.rs
  clippy_lints/src/from_over_into.rs
  clippy_lints/src/int_plus_one.rs
  clippy_lints/src/items_after_test_module.rs
  clippy_lints/src/large_stack_frames.rs
  clippy_lints/src/len_zero.rs
  clippy_lints/src/literal_representation.rs
  clippy_lints/src/manual_float_methods.rs
  clippy_lints/src/manual_hash_one.rs
  clippy_lints/src/manual_non_exhaustive.rs
  clippy_lints/src/manual_range_patterns.rs
  clippy_lints/src/methods/unnecessary_iter_cloned.rs
  clippy_lints/src/misc_early/unneeded_field_pattern.rs
  clippy_lints/src/missing_enforced_import_rename.rs
  clippy_lints/src/needless_if.rs
  clippy_lints/src/needless_late_init.rs
  clippy_lints/src/no_effect.rs
  clippy_lints/src/nonstandard_macro_braces.rs
  clippy_lints/src/operators/assign_op_pattern.rs
  clippy_lints/src/operators/misrefactored_assign_op.rs
  clippy_lints/src/operators/needless_bitwise_bool.rs
  clippy_lints/src/operators/ptr_eq.rs
  clippy_lints/src/unit_types/unit_arg.rs
  clippy_lints/src/utils/format_args_collector.rs
  clippy_utils/src/attrs.rs
  clippy_utils/src/hir_utils.rs
Labels: S-waiting-on-review, performance-project

#13296 Replace more uses of `snippet_opt`.
  clippy_lints/src/casts/cast_lossless.rs
  clippy_lints/src/casts/unnecessary_cast.rs
  clippy_lints/src/casts/zero_ptr.rs
  clippy_lints/src/functions/must_use.rs
  clippy_lints/src/functions/too_many_lines.rs
  clippy_lints/src/matches/manual_unwrap_or.rs
  clippy_lints/src/methods/case_sensitive_file_extension_comparisons.rs
  clippy_lints/src/methods/filter_map_bool_then.rs
  clippy_lints/src/methods/from_iter_instead_of_collect.rs
  clippy_lints/src/methods/join_absolute_paths.rs
  clippy_lints/src/methods/manual_ok_or.rs
  clippy_lints/src/methods/manual_try_fold.rs
  clippy_lints/src/methods/needless_character_iteration.rs
  clippy_lints/src/methods/needless_option_as_deref.rs
  clippy_lints/src/methods/string_lit_chars_any.rs
  clippy_lints/src/methods/unnecessary_get_then_check.rs
  clippy_lints/src/methods/unnecessary_to_owned.rs
  clippy_lints/src/methods/unused_enumerate_index.rs
  clippy_lints/src/vec.rs
  clippy_utils/src/source.rs
Labels: S-waiting-on-review

#12993 Add new `too_long_first_doc_paragraph` first paragraph lint
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/doc/mod.rs
  clippy_lints/src/doc/too_long_first_doc_paragraph.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/macros.rs
  clippy_utils/src/source.rs
  clippy_utils/src/ty.rs
  tests/ui/too_long_first_doc_paragraph-fix.fixed
  tests/ui/too_long_first_doc_paragraph-fix.rs
  tests/ui/too_long_first_doc_paragraph-fix.stderr
  tests/ui/too_long_first_doc_paragraph.rs
  tests/ui/too_long_first_doc_paragraph.stderr
Labels: S-waiting-on-review

#13302 Rustup
  clippy_dev/src/main.rs
  clippy_lints/src/casts/fn_to_numeric_cast.rs
  clippy_lints/src/casts/fn_to_numeric_cast_any.rs
  clippy_lints/src/casts/fn_to_numeric_cast_with_truncation.rs
  clippy_lints/src/default_numeric_fallback.rs
  clippy_lints/src/dereference.rs
  clippy_lints/src/eta_reduction.rs
  clippy_lints/src/methods/map_flatten.rs
  clippy_lints/src/mixed_read_write_in_expression.rs
  clippy_lints/src/multiple_unsafe_ops_per_block.rs
  clippy_lints/src/mut_reference.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/qualify_min_const_fn.rs
  clippy_utils/src/ty.rs
  clippy_utils/src/visitors.rs
  rust-toolchain
  src/main.rs
  tests/config-metadata.rs
  tests/ui/borrow_interior_mutable_const/others.rs
  tests/ui/borrow_interior_mutable_const/others.stderr
  tests/ui/single_match_else.fixed
  tests/ui/single_match_else.rs
  tests/ui/single_match_else.stderr
Labels: S-waiting-on-review

#13285 Diverging subexpression lint should not fire on todo!()
  clippy_lints/src/mixed_read_write_in_expression.rs
  tests/ui/diverging_sub_expression.rs
Labels: S-waiting-on-review

#13113 Ignore underscore-prefixed args for needless_pass_by_value lint
  clippy_lints/src/needless_pass_by_value.rs
  tests/ui/needless_pass_by_value.rs
  tests/ui/needless_pass_by_value.stderr
Labels: S-waiting-on-review

#13300 check std::panic::panic_any in panic lint
  clippy_lints/src/panic_unimplemented.rs
  clippy_utils/src/paths.rs
  tests/ui-toml/panic/panic.rs
  tests/ui-toml/panic/panic.stderr
Labels: S-waiting-on-review

#13294 Add new lint: `used_underscore_items`
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/misc.rs
  tests/ui/auxiliary/external_item.rs
  tests/ui/used_underscore_binding.stderr
  tests/ui/used_underscore_items.rs
  tests/ui/used_underscore_items.stderr
Labels: S-waiting-on-review

#11476 new lint: `zombie_processes`
  CHANGELOG.md
  clippy_dev/src/serve.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/zombie_processes.rs
  clippy_utils/src/paths.rs
  tests/ui/suspicious_command_arg_space.fixed
  tests/ui/suspicious_command_arg_space.rs
  tests/ui/suspicious_command_arg_space.stderr
  tests/ui/zombie_processes.rs
  tests/ui/zombie_processes.stderr
  tests/ui/zombie_processes_fixable.fixed
  tests/ui/zombie_processes_fixable.rs
  tests/ui/zombie_processes_fixable.stderr
Labels: S-final-comment-period

#13235 Use `is_diagnostic_item` for checking a def_id in `unnecessary_min_or_max`.
  clippy_lints/src/methods/unnecessary_min_or_max.rs
  tests/ui/unnecessary_min_or_max.fixed
  tests/ui/unnecessary_min_or_max.rs
Labels: S-waiting-on-review

#12476 Extend `implicit_saturating_sub` lint
  CHANGELOG.md
  clippy_config/src/msrvs.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/implicit_saturating_sub.rs
  clippy_lints/src/lib.rs
  tests/ui/implicit_saturating_sub.fixed
  tests/ui/implicit_saturating_sub.rs
  tests/ui/manual_arithmetic_check-2.rs
  tests/ui/manual_arithmetic_check-2.stderr
  tests/ui/manual_arithmetic_check.fixed
  tests/ui/manual_arithmetic_check.rs
  tests/ui/manual_arithmetic_check.stderr
Labels: S-final-comment-period
