Repository rust-lang/rust-clippy, pull requests merged in 2025-08, with the labels that each got.

#15362 Do not specialize for `if_chain` any longer
  clippy_lints/src/index_refutable_slice.rs
  clippy_test_deps/Cargo.lock
  clippy_test_deps/Cargo.toml
  clippy_utils/src/sym.rs
  tests/compile-test.rs
  tests/ui/index_refutable_slice/slice_indexing_in_macro.fixed
  tests/ui/index_refutable_slice/slice_indexing_in_macro.rs
  tests/ui/index_refutable_slice/slice_indexing_in_macro.stderr
Labels: S-waiting-on-review

#15385 Optimize broken_links by 99.77%
  clippy_lints/src/doc/broken_link.rs
Labels: S-waiting-on-review, G-performance-project

#15386 fix: `let_with_type_underscore` don't eat closing paren in `let (i): _ = 0;`
  clippy_lints/src/let_with_type_underscore.rs
  tests/ui/let_with_type_underscore.fixed
  tests/ui/let_with_type_underscore.rs
  tests/ui/let_with_type_underscore.stderr
Labels: S-waiting-on-review

#15261 `{flat_,}map_identity`: recognize (tuple) struct de- and restructuring
  clippy_utils/src/lib.rs
  tests/ui/map_identity.fixed
  tests/ui/map_identity.rs
  tests/ui/map_identity.stderr
Labels: S-waiting-on-review

#14177 Extend `implicit_clone` to handle `to_string` calls
  .github/driver.sh
  clippy_lints/src/blocks_in_conditions.rs
  clippy_lints/src/copies.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/deprecated_lints.rs
  clippy_lints/src/if_not_else.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_async_fn.rs
  clippy_lints/src/matches/match_single_binding.rs
  clippy_lints/src/matches/single_match.rs
  clippy_lints/src/methods/implicit_clone.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/unnecessary_sort_by.rs
  clippy_lints/src/methods/unnecessary_to_owned.rs
  clippy_lints/src/redundant_else.rs
  clippy_lints/src/strings.rs
  lintcheck/src/input.rs
  lintcheck/src/output.rs
  tests/ui/deprecated.rs
  tests/ui/deprecated.stderr
  tests/ui/implicit_clone.fixed
  tests/ui/implicit_clone.rs
  tests/ui/implicit_clone.stderr
  tests/ui/string_to_string.rs
  tests/ui/string_to_string.stderr
  tests/ui/string_to_string_in_map.fixed
  tests/ui/string_to_string_in_map.rs
  tests/ui/string_to_string_in_map.stderr
Labels: S-waiting-on-review

#15368 Simplify boolean expression in `manual_assert`
  clippy_lints/src/manual_assert.rs
  tests/ui/manual_assert.edition2018.stderr
  tests/ui/manual_assert.edition2021.stderr
Labels: S-waiting-on-review

#15394 fix option-if-let-else lint
  clippy_lints/src/option_if_let_else.rs
  tests/ui/option_if_let_else.fixed
  tests/ui/option_if_let_else.rs
  tests/ui/option_if_let_else.stderr
Labels: S-waiting-on-review

#15401 clean-up `SourceFileRange::as_str`
  clippy_utils/src/source.rs
Labels: S-waiting-on-review

#15390 clean-up `semicolon_inside_block`
  clippy_lints/src/semicolon_block.rs
Labels: S-waiting-on-review

#15407 Fix not showing deprecated lints
  util/gh-pages/script.js
Labels: S-waiting-on-review

#15393 Issues priority
  CONTRIBUTING.md
Labels: S-waiting-on-review

#15317 Split `possible_missing_else` from `suspicious_else_formatting`
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/formatting.rs
  tests/ui/suspicious_else_formatting.rs
  tests/ui/suspicious_else_formatting.stderr
Labels: A-lint

#15413 Do not lint for `wildcard_imports` in external macro
  clippy_lints/src/wildcard_imports.rs
  tests/ui-toml/wildcard_imports/wildcard_imports.fixed
  tests/ui-toml/wildcard_imports/wildcard_imports.rs
  tests/ui-toml/wildcard_imports/wildcard_imports.stderr
Labels: S-waiting-on-review

#15336 expand the issue template for new lints
  .github/ISSUE_TEMPLATE/new_lint.yml
Labels: S-waiting-on-review

#15423 Optimize `needless_bool` lint
  clippy_lints/src/needless_bool.rs
Labels: S-waiting-on-review, G-performance-project

#15427 Fix typo in lint issue template
  .github/ISSUE_TEMPLATE/new_lint.yml
Labels: S-waiting-on-review

#15436 `eta_reduction`: don't refer to ADT constructors as "function"s
  clippy_lints/src/eta_reduction.rs
  tests/ui/eta.fixed
  tests/ui/eta.rs
  tests/ui/eta.stderr
Labels: S-waiting-on-author

#15157 [[infinite_loop] fix infinite loop false positive
  clippy_lints/src/loops/infinite_loop.rs
  tests/ui/infinite_loops.rs
  tests/ui/infinite_loops.stderr
Labels: S-waiting-on-review

#15447 Add "PowerPC" to the list of valid CamelCase strings in docs
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  tests/ui/doc/doc-fixable.fixed
  tests/ui/doc/doc-fixable.rs
Labels: S-waiting-on-review

#15446 `expect_fun_call`: move helper functions out of the main one
  clippy_lints/src/methods/expect_fun_call.rs
Labels: S-waiting-on-review

#15455 doc: use `is_some_and` instead of `map_or(false, _)`
  book/src/development/common_tools_writing_lints.md
Labels: S-waiting-on-review

#15477 move `char_lit_as_u8` under the explicit-cast case
  clippy_lints/src/casts/char_lit_as_u8.rs
  clippy_lints/src/casts/mod.rs
  tests/ui/char_lit_as_u8.fixed
  tests/ui/char_lit_as_u8.rs
  tests/ui/char_lit_as_u8.stderr
  tests/ui/char_lit_as_u8_suggestions.rs
  tests/ui/char_lit_as_u8_suggestions.stderr
  tests/ui/char_lit_as_u8_unfixable.rs
  tests/ui/char_lit_as_u8_unfixable.stderr
Labels: S-waiting-on-review

#15454 Adjust `declare_interior_mutable_const` lint's category
  clippy_lints/src/non_copy_const.rs
Labels: S-waiting-on-review

#15467 `result_large_err`: get `DefId` from `AdtDef` instead of `expect`ing
  clippy_lints/src/functions/result.rs
Labels: S-waiting-on-review

#15432 `unnecessary_operation`: add space between stmts in suggestion
  clippy_lints/src/no_effect.rs
  tests/ui/unnecessary_operation.fixed
  tests/ui/unnecessary_operation.stderr
Labels: S-waiting-on-review

#15489 clean-up `unnecessary_unwrap` a bit
  clippy_lints/src/unwrap.rs
Labels: S-waiting-on-review

#15100 `similar_names` stop linting for 3-char names
  clippy_lints/src/non_expressive_names.rs
  clippy_utils/src/ast_utils/mod.rs
  tests/ui/similar_names.rs
  tests/ui/similar_names.stderr
Labels: S-waiting-on-review

#15503 clean-up `collapsible_if` a bit
  clippy_lints/src/collapsible_if.rs
Labels: S-waiting-on-review

#15508 extract `duplicate_underscore_argument`, and move it into `functions`
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/functions/duplicate_underscore_argument.rs
  clippy_lints/src/functions/mod.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/misc_early/mod.rs
Labels: S-waiting-on-review

#15352 Do not replace `match` by `if` if any arm contains a binding
  clippy_lints/src/matches/match_bool.rs
  tests/ui/match_bool.fixed
  tests/ui/match_bool.rs
Labels: S-waiting-on-review

#15507 `ptr_arg`: clean-up a bit
  clippy_lints/src/ptr.rs
Labels: S-waiting-on-review

#15523 Add myself back to reviewer rotation
  triagebot.toml
Labels: S-waiting-on-review

#15524 `renamed_function_params`: clean-up a bit
  clippy_lints/src/functions/renamed_function_params.rs
Labels: S-waiting-on-review

#15530 chore: remove redundant word in comment
  .github/workflows/feature_freeze.yml
Labels: S-waiting-on-review

#15531 Rustup
  Cargo.toml
  clippy_lints/src/arbitrary_source_item_ordering.rs
  clippy_lints/src/bool_assert_comparison.rs
  clippy_lints/src/copy_iterator.rs
  clippy_lints/src/derivable_impls.rs
  clippy_lints/src/derive.rs
  clippy_lints/src/duplicate_mod.rs
  clippy_lints/src/empty_drop.rs
  clippy_lints/src/empty_line_after.rs
  clippy_lints/src/error_impl_error.rs
  clippy_lints/src/excessive_nesting.rs
  clippy_lints/src/format_impl.rs
  clippy_lints/src/from_over_into.rs
  clippy_lints/src/functions/impl_trait_in_params.rs
  clippy_lints/src/functions/renamed_function_params.rs
  clippy_lints/src/impl_hash_with_borrow_str_and_bytes.rs
  clippy_lints/src/infallible_try_from.rs
  clippy_lints/src/item_name_repetitions.rs
  clippy_lints/src/iter_without_into_iter.rs
  clippy_lints/src/lifetimes.rs
  clippy_lints/src/missing_asserts_for_indexing.rs
  clippy_lints/src/missing_fields_in_debug.rs
  clippy_lints/src/missing_inline.rs
  clippy_lints/src/missing_trait_methods.rs
  clippy_lints/src/non_copy_const.rs
  clippy_lints/src/non_send_fields_in_send_ty.rs
  clippy_lints/src/operators/assign_op_pattern.rs
  clippy_lints/src/operators/op_ref.rs
  clippy_lints/src/partialeq_ne_impl.rs
  clippy_lints/src/redundant_pub_crate.rs
  clippy_lints/src/same_name_method.rs
  clippy_lints/src/serde_api.rs
  clippy_lints/src/single_component_path_imports.rs
  clippy_lints/src/to_string_trait_impl.rs
  clippy_lints/src/unconditional_recursion.rs
  clippy_lints/src/undocumented_unsafe_blocks.rs
  clippy_lints/src/unnested_or_patterns.rs
  clippy_lints/src/write.rs
  clippy_lints_internal/src/derive_deserialize_allowing_unknown.rs
  clippy_utils/README.md
  clippy_utils/src/ast_utils/mod.rs
  clippy_utils/src/check_proc_macro.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/macros.rs
  clippy_utils/src/sym.rs
  clippy_utils/src/visitors.rs
  rust-toolchain.toml
  tests/missing-test-files.rs
  tests/ui/bool_assert_comparison.fixed
  tests/ui/bool_assert_comparison.rs
  tests/ui/bool_assert_comparison.stderr
  tests/ui/checked_unwrap/simple_conditionals.stderr
  tests/ui/const_is_empty.rs
  tests/ui/const_is_empty.stderr
  tests/ui/crashes/ice-6255.rs
  tests/ui/crashes/ice-6255.stderr
  tests/ui/crashes/ice-96721.stderr
  tests/ui/incompatible_msrv.rs
Labels: S-waiting-on-review

#15534 Add 1.89 beta-accepted changes to changelog
  CHANGELOG.md
Labels: S-waiting-on-review

#15450 `is_expr_identity_of_pat`: simplify using `(unordered_)over`
  clippy_utils/src/ast_utils/mod.rs
  clippy_utils/src/hir_utils.rs
  clippy_utils/src/lib.rs
Labels: S-waiting-on-review

#15513 bool_comparison: fix incorrect suggestion with `>`/`<` and macros
  clippy_lints/src/needless_bool.rs
  tests/ui/bool_comparison.fixed
  tests/ui/bool_comparison.rs
  tests/ui/bool_comparison.stderr
Labels: S-waiting-on-review

#15498 `bool_comparison`: no longer lint on `!x != y`
  clippy_lints/src/needless_bool.rs
  tests/ui/bool_comparison.fixed
  tests/ui/bool_comparison.rs
  tests/ui/bool_comparison.stderr
  tests/ui/needless_bool/fixable.stderr
  tests/ui/nonminimal_bool.rs
  tests/ui/nonminimal_bool.stderr
Labels: S-waiting-on-review

#15535 Fix `derivable_impls` suggests wrongly on `derive_const`
  clippy_lints/src/derivable_impls.rs
  clippy_lints/src/matches/significant_drop_in_scrutinee.rs
  tests/ui/derivable_impls.fixed
  tests/ui/derivable_impls.rs
  tests/ui/derivable_impls.stderr
  tests/ui/derivable_impls_derive_const.fixed
  tests/ui/derivable_impls_derive_const.rs
  tests/ui/derivable_impls_derive_const.stderr
Labels: S-waiting-on-review

#15343 fix: `unnested_or_patterns` FP on structs with only shorthand field pats
  clippy_lints/src/unnested_or_patterns.rs
  tests/ui/unnested_or_patterns.fixed
  tests/ui/unnested_or_patterns.rs
  tests/ui/unnested_or_patterns.stderr
Labels: S-waiting-on-review

#15478 clean-up `ptr_cast_constness`
  clippy_lints/src/casts/ptr_cast_constness.rs
Labels: S-waiting-on-review

#15483 fix `or_then_unwrap`: suggestion preserves macro calls
  clippy_lints/src/methods/or_then_unwrap.rs
  tests/ui/or_then_unwrap.fixed
  tests/ui/or_then_unwrap.rs
  tests/ui/or_then_unwrap.stderr
Labels: S-waiting-on-review

#15054 check f16 and f128 in float_equality_without_abs
  clippy_lints/src/operators/float_equality_without_abs.rs
  tests/ui/float_equality_without_abs.rs
  tests/ui/float_equality_without_abs.stderr
Labels: S-waiting-on-review

#15479 split `cast_ptr_alignment`
  clippy_lints/src/casts/cast_ptr_alignment.rs
  clippy_lints/src/casts/mod.rs
Labels: S-waiting-on-review

#15480 `ptr_as_ptr`: move to `if`
  clippy_lints/src/casts/mod.rs
  clippy_lints/src/casts/ptr_as_ptr.rs
Labels: S-waiting-on-review

#15476 Fix `semicolon_inside_block` FP when attribute over expr is not enabled
  clippy_lints/src/semicolon_block.rs
  tests/ui/semicolon_inside_block.fixed
  tests/ui/semicolon_inside_block.rs
  tests/ui/semicolon_inside_block_stmt_expr_attrs.fixed
  tests/ui/semicolon_inside_block_stmt_expr_attrs.rs
  tests/ui/semicolon_inside_block_stmt_expr_attrs.stderr
Labels: S-waiting-on-review

#15549 `unused_unit`: don't lint on closure return types
  clippy_lints/src/unused_unit.rs
  tests/ui/unused_unit.edition2021.fixed
  tests/ui/unused_unit.edition2021.stderr
  tests/ui/unused_unit.edition2024.fixed
  tests/ui/unused_unit.rs
Labels: S-waiting-on-author

#15571 Document `is_unit_expr()`
  clippy_utils/src/lib.rs
Labels: S-waiting-on-review

#14221 fix: `collapsible_match` suggests ref/derefs when needed
  clippy_lints/src/matches/collapsible_match.rs
  clippy_lints/src/matches/mod.rs
  clippy_utils/src/lib.rs
  tests/ui/collapsible_match.rs
  tests/ui/collapsible_match.stderr
  tests/ui/collapsible_match2.stderr
Labels: S-waiting-on-review

#15580 triagebot: Amend a review to include a link to what was changed since
  triagebot.toml
Labels: S-waiting-on-review

#15268 `map_identity`: suggest making the variable mutable when necessary
  clippy_lints/src/methods/map_identity.rs
  tests/ui/map_identity.fixed
  tests/ui/map_identity.rs
  tests/ui/map_identity.stderr
Labels: S-waiting-on-review

#15583 Fix `print_literal` suggests wrongly for inline literal following a numbered arg
  clippy_lints/src/write.rs
  tests/ui/print_literal.fixed
  tests/ui/print_literal.rs
  tests/ui/print_literal.stderr
Labels: S-waiting-on-review

#15486 Fix FP of `needless_range_loop` when meeting multidimensional array
  clippy_lints/src/loops/needless_range_loop.rs
  tests/ui/needless_range_loop.rs
  tests/ui/needless_range_loop.stderr
Labels: S-waiting-on-review

#15014 Get the block content from the proper context
  clippy_lints/src/if_then_some_else_none.rs
  tests/ui/if_then_some_else_none.fixed
  tests/ui/if_then_some_else_none.rs
  tests/ui/if_then_some_else_none.stderr
Labels: S-waiting-on-review

#15591 fix: `assertions_on_result_states` avoid changing return type in more cases
  clippy_lints/src/assertions_on_result_states.rs
  tests/ui/assertions_on_result_states.fixed
  tests/ui/assertions_on_result_states.rs
  tests/ui/assertions_on_result_states.stderr
Labels: S-waiting-on-review
