Repository rust-lang/rust-clippy, pull requests merged in 2025-04, with the labels that each got.

#14516 Fix the primary span of `redundant_pub_crate` when flagging nameless items
  clippy_lints/src/redundant_pub_crate.rs
  tests/ui/redundant_pub_crate.fixed
  tests/ui/redundant_pub_crate.rs
  tests/ui/redundant_pub_crate.stderr
Labels: S-waiting-on-review

#14517 Do not build `tokio-rustls` in the CI for the time being
  .github/workflows/lintcheck.yml
  lintcheck/ci_crates.toml
Labels: S-waiting-on-review

#14397 Validate paths in `disallowed_*` configurations
  clippy.toml
  clippy_config/src/conf.rs
  clippy_config/src/lib.rs
  clippy_config/src/types.rs
  clippy_lints/src/await_holding_invalid.rs
  clippy_lints/src/disallowed_macros.rs
  clippy_lints/src/disallowed_methods.rs
  clippy_lints/src/disallowed_types.rs
  tests/ui-toml/await_holding_invalid_type_with_replacement/await_holding_invalid_type.stderr
  tests/ui-toml/toml_invalid_path/clippy.toml
  tests/ui-toml/toml_invalid_path/conf_invalid_path.rs
  tests/ui-toml/toml_invalid_path/conf_invalid_path.stderr
Labels: S-waiting-on-review

#14529 Fix a typo in derive.rs comment
  clippy_lints/src/derive.rs
Labels: S-waiting-on-review

#14530 Update to new rinja version (askama)
  Cargo.toml
  askama.toml
  tests/compile-test.rs
Labels: S-waiting-on-review

#14538 Changelog for Clippy 1.86 :penguin:
  CHANGELOG.md
Labels: S-waiting-on-review

#14539 Rustup
  Cargo.toml
  clippy_config/Cargo.toml
  clippy_lints/Cargo.toml
  clippy_lints/src/attrs/duplicated_attributes.rs
  clippy_lints/src/casts/unnecessary_cast.rs
  clippy_lints/src/cfg_not_test.rs
  clippy_lints/src/crate_in_macro_def.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/default.rs
  clippy_lints/src/deprecated_lints.rs
  clippy_lints/src/derive.rs
  clippy_lints/src/doc/needless_doctest_main.rs
  clippy_lints/src/duplicate_mod.rs
  clippy_lints/src/empty_line_after.rs
  clippy_lints/src/empty_with_brackets.rs
  clippy_lints/src/escape.rs
  clippy_lints/src/field_scoped_visibility_modifiers.rs
  clippy_lints/src/functions/renamed_function_params.rs
  clippy_lints/src/index_refutable_slice.rs
  clippy_lints/src/lifetimes.rs
  clippy_lints/src/loops/mut_range_bound.rs
  clippy_lints/src/macro_metavars_in_unsafe.rs
  clippy_lints/src/matches/redundant_guards.rs
  clippy_lints/src/methods/is_empty.rs
  clippy_lints/src/misc.rs
  clippy_lints/src/multiple_bound_locations.rs
  clippy_lints/src/needless_pass_by_ref_mut.rs
  clippy_lints/src/needless_pass_by_value.rs
  clippy_lints/src/new_without_default.rs
  clippy_lints/src/operators/arithmetic_side_effects.rs
  clippy_lints/src/operators/numeric_arithmetic.rs
  clippy_lints/src/partial_pub_fields.rs
  clippy_lints/src/ptr.rs
  clippy_lints/src/shadow.rs
  clippy_lints/src/significant_drop_tightening.rs
  clippy_lints/src/single_call_fn.rs
  clippy_lints/src/single_component_path_imports.rs
  clippy_lints/src/unneeded_struct_pattern.rs
  clippy_lints/src/utils/internal_lints/produce_ice.rs
  clippy_lints/src/utils/internal_lints/unsorted_clippy_utils_paths.rs
  clippy_utils/Cargo.toml
  clippy_utils/README.md
  clippy_utils/src/ast_utils/mod.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/macros.rs
  clippy_utils/src/sugg.rs
  rust-toolchain.toml
  tests/ui/crashes/ice-1782.rs
  tests/ui/invalid_null_ptr_usage.fixed
  tests/ui/invalid_null_ptr_usage.rs
  tests/ui/invalid_null_ptr_usage.stderr
  tests/ui/invalid_null_ptr_usage_no_std.fixed
  tests/ui/invalid_null_ptr_usage_no_std.rs
  tests/ui/invalid_null_ptr_usage_no_std.stderr
  tests/ui/rename.fixed
  tests/ui/rename.rs
  tests/ui/rename.stderr
Labels: S-waiting-on-review

#14540 Update versions of 1.86 lints
  clippy_lints/src/manual_option_as_slice.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/non_std_lazy_statics.rs
Labels: S-waiting-on-review

#14108 Fixes for `missing_asserts_for_indexing`
  clippy_lints/src/missing_asserts_for_indexing.rs
  tests/ui/missing_asserts_for_indexing.fixed
  tests/ui/missing_asserts_for_indexing.rs
  tests/ui/missing_asserts_for_indexing_unfixable.rs
  tests/ui/missing_asserts_for_indexing_unfixable.stderr
Labels: S-waiting-on-review

#14563 Enable canonicalization of issue links in triagebot
  triagebot.toml
Labels: S-waiting-on-review

#14527 Ensure that peeling does not recurse into macros
  clippy_lints/src/ptr.rs
  tests/ui/ptr_eq.fixed
  tests/ui/ptr_eq.rs
  tests/ui/ptr_eq.stderr
Labels: S-waiting-on-review, beta-nominated

#14473 fix: `iter_cloned_collect` FP with custom `From`/`IntoIterator` impl
  clippy_lints/src/methods/iter_cloned_collect.rs
  tests/ui/iter_cloned_collect.fixed
  tests/ui/iter_cloned_collect.rs
  tests/ui/iter_cloned_collect.stderr
Labels: S-waiting-on-review

#14482 add `manual_abs_diff` lint
  CHANGELOG.md
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_abs_diff.rs
  clippy_utils/src/msrvs.rs
  tests/ui/manual_abs_diff.fixed
  tests/ui/manual_abs_diff.rs
  tests/ui/manual_abs_diff.stderr
Labels: S-final-comment-period

#14573 Accept `self.cmp(other).into()` as canonical `PartialOrd` impl
  clippy_lints/src/non_canonical_impls.rs
  tests/ui/non_canonical_partial_ord_impl.fixed
  tests/ui/non_canonical_partial_ord_impl.rs
  tests/ui/non_canonical_partial_ord_impl.stderr
Labels: S-waiting-on-review

#14567 Enable GitHub review synchronization with S-waiting-on-* labels
  triagebot.toml
Labels: S-waiting-on-review

#14367 Correctly handle bracketed type in `default_constructed_unit_struct`
  clippy_lints/src/default_constructed_unit_structs.rs
  tests/ui/default_constructed_unit_structs.fixed
  tests/ui/default_constructed_unit_structs.rs
  tests/ui/default_constructed_unit_structs.stderr
Labels: S-waiting-on-review

#14580 Avoid some uses of empty identifiers
  clippy_lints/src/arbitrary_source_item_ordering.rs
Labels: S-waiting-on-review

#14576 Enable no mentions in commits of triagebot
  triagebot.toml
Labels: S-waiting-on-review

#14590 Assign PR touching `triagebot.toml` to Philipp
  triagebot.toml
Labels: S-waiting-on-review

#14591 Reinstate checking of `tokio-rustls` in lintcheck
  lintcheck/ci_crates.toml
Labels: S-waiting-on-review

#14446 `implicit_return`: better handling of asynchronous code
  clippy_lints/src/implicit_return.rs
  clippy_lints/src/redundant_async_block.rs
  clippy_utils/src/lib.rs
  tests/ui/implicit_return.fixed
  tests/ui/implicit_return.rs
  tests/ui/implicit_return.stderr
Labels: S-waiting-on-review

#14237 fix: `redundant_clone` FP in overlapping lifetime
  clippy_lints/src/redundant_clone.rs
  tests/ui/redundant_clone.fixed
  tests/ui/redundant_clone.rs
Labels: S-waiting-on-author

#14579 dogfood: run with `-D clippy::dbg_macro`
  tests/dogfood.rs
Labels: S-waiting-on-review

#14589 book: indicate that at least one error marker is required
  book/src/development/adding_lints.md
Labels: S-waiting-on-review

#14559 Do not propose to auto-derive `Clone` in presence of unsafe fields
  clippy_lints/src/derive.rs
  tests/ui/derive.rs
  tests/ui/derive.stderr
Labels: S-waiting-on-review

#14460 Consecutive returns dont decrease cognitive Complexity level anymore
  clippy_lints/src/cognitive_complexity.rs
  tests/ui/cognitive_complexity.rs
Labels: S-waiting-on-review

#14603 Change Test for Issue 14422 (Cognitive Complexity lowered through mul…
  tests/ui/cognitive_complexity.rs
  tests/ui/cognitive_complexity.stderr
Labels: S-waiting-on-review

#14217 Deprecate `match_on_vec_items` lint
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/deprecated_lints.rs
  clippy_lints/src/matches/match_on_vec_items.rs
  clippy_lints/src/matches/mod.rs
  tests/ui/deprecated.rs
  tests/ui/deprecated.stderr
  tests/ui/match_on_vec_items.rs
  tests/ui/match_on_vec_items.stderr
Labels: S-waiting-on-review

#14604 Fulfill the lint expectation even if allowed at the type level
  clippy_lints/src/len_zero.rs
  tests/ui/len_without_is_empty_expect.rs
  tests/ui/len_without_is_empty_expect.stderr
Labels: S-waiting-on-review

#14463 Various fixes for `manual_is_power_of_two`
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_is_power_of_two.rs
  clippy_utils/src/msrvs.rs
  tests/ui/manual_is_power_of_two.fixed
  tests/ui/manual_is_power_of_two.rs
  tests/ui/manual_is_power_of_two.stderr
Labels: S-waiting-on-review

#14471 Consider nested lifetimes in `mut_from_ref`
  clippy_lints/src/ptr.rs
  tests/ui/mut_from_ref.rs
  tests/ui/mut_from_ref.stderr
Labels: S-waiting-on-review

#14258 `missing_asserts_for_indexing`: consider `assert_eq!()` as well
  clippy_lints/src/missing_asserts_for_indexing.rs
  tests/ui/missing_asserts_for_indexing.fixed
  tests/ui/missing_asserts_for_indexing.rs
  tests/ui/missing_asserts_for_indexing.stderr
  tests/ui/missing_asserts_for_indexing_unfixable.rs
  tests/ui/missing_asserts_for_indexing_unfixable.stderr
Labels: S-waiting-on-review

#14618 Replace stray `println!()` in lint code by `bug!()`
  clippy_lints/src/arbitrary_source_item_ordering.rs
Labels: S-waiting-on-review

#13710 New lint: `redundant_test_prefix`
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/redundant_test_prefix.rs
  clippy_utils/src/lib.rs
  tests/ui/redundant_test_prefix.fixed
  tests/ui/redundant_test_prefix.rs
  tests/ui/redundant_test_prefix.stderr
  tests/ui/redundant_test_prefix_noautofix.rs
  tests/ui/redundant_test_prefix_noautofix.stderr
Labels: S-final-comment-period

#14627 Fix broken CSS for 1.86 lint docs
  rust-1.86.0/index.html
Labels: S-waiting-on-review

#14636 samueltardieu: vacation for ~3 weeks
  triagebot.toml
Labels: S-waiting-on-review

#14586 Build complete usable type from a type-relative prefix
  clippy_lints/src/methods/from_iter_instead_of_collect.rs
  tests/ui/from_iter_instead_of_collect.fixed
  tests/ui/from_iter_instead_of_collect.rs
  tests/ui/from_iter_instead_of_collect.stderr
Labels: S-waiting-on-review

#14629 `bool_to_int_with_if`: properly handle macros
  clippy_lints/src/bool_to_int_with_if.rs
  tests/ui/bool_to_int_with_if.fixed
  tests/ui/bool_to_int_with_if.rs
  tests/ui/bool_to_int_with_if.stderr
Labels: S-waiting-on-review

#14620 Add `note` feature to triagebot's config
  triagebot.toml
Labels: S-waiting-on-review

#14641 Do not recurse forever in `significant_drop_tightening`
  clippy_lints/src/significant_drop_tightening.rs
  tests/ui/crashes/ice-13544-original.rs
  tests/ui/crashes/ice-13544-reduced.rs
Labels: S-waiting-on-review, L-nursery

#14046 New lint: `swap_with_temporary`
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/swap_with_temporary.rs
  tests/ui/swap_with_temporary.fixed
  tests/ui/swap_with_temporary.rs
  tests/ui/swap_with_temporary.stderr
  tests/ui/swap_with_temporary_unfixable.rs
  tests/ui/swap_with_temporary_unfixable.stderr
Labels: S-final-comment-period

#14635 `match_single_binding`: allow macros in scrutinee and patterns
  clippy_lints/src/matches/match_single_binding.rs
  tests/ui/match_single_binding.fixed
  tests/ui/match_single_binding.rs
  tests/ui/match_single_binding.stderr
Labels: S-waiting-on-review

#14647 Rustup
  Cargo.toml
  clippy_dev/src/lib.rs
  clippy_dev/src/update_lints.rs
  clippy_lints/src/assigning_clones.rs
  clippy_lints/src/attrs/deprecated_cfg_attr.rs
  clippy_lints/src/attrs/useless_attribute.rs
  clippy_lints/src/bool_assert_comparison.rs
  clippy_lints/src/booleans.rs
  clippy_lints/src/disallowed_script_idents.rs
  clippy_lints/src/doc/needless_doctest_main.rs
  clippy_lints/src/duplicate_mod.rs
  clippy_lints/src/equatable_if_let.rs
  clippy_lints/src/format_args.rs
  clippy_lints/src/format_push_string.rs
  clippy_lints/src/functions/renamed_function_params.rs
  clippy_lints/src/implicit_saturating_add.rs
  clippy_lints/src/implicit_saturating_sub.rs
  clippy_lints/src/implied_bounds_in_impls.rs
  clippy_lints/src/len_zero.rs
  clippy_lints/src/loops/utils.rs
  clippy_lints/src/macro_metavars_in_unsafe.rs
  clippy_lints/src/macro_use.rs
  clippy_lints/src/matches/match_same_arms.rs
  clippy_lints/src/matches/single_match.rs
  clippy_lints/src/methods/double_ended_iterator_last.rs
  clippy_lints/src/methods/iter_overeager_cloned.rs
  clippy_lints/src/methods/needless_collect.rs
  clippy_lints/src/methods/or_fun_call.rs
  clippy_lints/src/methods/unnecessary_iter_cloned.rs
  clippy_lints/src/methods/unnecessary_to_owned.rs
  clippy_lints/src/missing_trait_methods.rs
  clippy_lints/src/mixed_read_write_in_expression.rs
  clippy_lints/src/module_style.rs
  clippy_lints/src/needless_borrows_for_generic_args.rs
  clippy_lints/src/operators/arithmetic_side_effects.rs
  clippy_lints/src/operators/mod.rs
  clippy_lints/src/raw_strings.rs
  clippy_lints/src/returns.rs
  clippy_lints/src/same_name_method.rs
  clippy_lints/src/suspicious_trait_impl.rs
  clippy_lints/src/swap.rs
  clippy_lints/src/unconditional_recursion.rs
  clippy_lints/src/unnested_or_patterns.rs
  clippy_lints/src/unused_self.rs
  clippy_lints/src/utils/author.rs
  clippy_utils/README.md
  clippy_utils/src/ast_utils/mod.rs
  clippy_utils/src/consts.rs
  clippy_utils/src/hir_utils.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/sugg.rs
  clippy_utils/src/sym.rs
  clippy_utils/src/ty/mod.rs
  rust-toolchain.toml
  src/driver.rs
Labels: S-waiting-on-review

#12971 `empty_enum_variants_with_brackets`: Do not lint reachable enums and enum variants used as functions in the same crate
  clippy_lints/src/empty_with_brackets.rs
  clippy_lints/src/lib.rs
  tests/ui/empty_enum_variants_with_brackets.fixed
  tests/ui/empty_enum_variants_with_brackets.rs
  tests/ui/empty_enum_variants_with_brackets.stderr
Labels: S-waiting-on-author

#14622 `ptr_cast_constness`: show snippet from the right context
  clippy_lints/src/casts/ptr_cast_constness.rs
  tests/ui/ptr_cast_constness.fixed
  tests/ui/ptr_cast_constness.rs
  tests/ui/ptr_cast_constness.stderr
Labels: S-waiting-on-review

#14596 `iter_kv_map`: recognize references on maps as well
  clippy_lints/src/methods/iter_kv_map.rs
  tests/ui/iter_kv_map.fixed
  tests/ui/iter_kv_map.rs
  tests/ui/iter_kv_map.stderr
Labels: S-waiting-on-review

#14408 Make `borrow_as_ptr` flag implicit casts as well
  clippy_lints/src/casts/borrow_as_ptr.rs
  clippy_lints/src/casts/mod.rs
  clippy_lints/src/non_copy_const.rs
  tests/ui/borrow_as_ptr.fixed
  tests/ui/borrow_as_ptr.rs
  tests/ui/borrow_as_ptr.stderr
Labels: S-waiting-on-review

#14650 Replace interning of string literals with preinterned symbols
  book/src/development/common_tools_writing_lints.md
  clippy_lints/src/format_impl.rs
  clippy_lints/src/indexing_slicing.rs
  clippy_lints/src/len_zero.rs
  clippy_lints/src/loops/explicit_iter_loop.rs
  clippy_lints/src/manual_div_ceil.rs
  clippy_lints/src/matches/redundant_pattern_match.rs
  clippy_lints/src/methods/filter_map.rs
  clippy_lints/src/methods/iter_filter.rs
  clippy_lints/src/methods/or_fun_call.rs
  clippy_lints/src/methods/seek_from_current.rs
  clippy_lints/src/methods/seek_to_start_instead_of_rewind.rs
  clippy_lints/src/rc_clone_in_vec_init.rs
  clippy_lints/src/regex.rs
  clippy_lints/src/set_contains_or_insert.rs
  clippy_lints/src/strings.rs
  clippy_lints/src/unwrap.rs
  clippy_lints_internal/src/interning_defined_symbol.rs
  clippy_lints_internal/src/interning_literals.rs
  clippy_lints_internal/src/lib.rs
  clippy_lints_internal/src/slow_symbol_comparisons.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/msrvs.rs
  clippy_utils/src/paths.rs
  clippy_utils/src/sym.rs
  clippy_utils/src/sym_helper.rs
  src/driver.rs
  tests/ui-internal/interning_defined_symbol.fixed
  tests/ui-internal/interning_defined_symbol.rs
  tests/ui-internal/interning_defined_symbol.stderr
  tests/ui-internal/interning_literals.fixed
  tests/ui-internal/interning_literals.rs
  tests/ui-internal/interning_literals.stderr
  tests/ui-internal/interning_literals_unfixable.rs
  tests/ui-internal/interning_literals_unfixable.stderr
  tests/ui-internal/slow_symbol_comparisons.fixed
  tests/ui-internal/slow_symbol_comparisons.rs
  tests/ui-internal/slow_symbol_comparisons.stderr
  tests/ui-internal/unnecessary_symbol_str.fixed
  tests/ui-internal/unnecessary_symbol_str.rs
  tests/ui-internal/unnecessary_symbol_str.stderr
Labels: S-waiting-on-review

#14655 Fix question_mark suggesting when type is behind Deref include parentheses
  clippy_lints/src/question_mark.rs
  tests/ui/question_mark.fixed
  tests/ui/question_mark.rs
  tests/ui/question_mark.stderr
Labels: S-waiting-on-review

#14667 Rustup
  clippy_lints/src/lifetimes.rs
  clippy_lints/src/pattern_type_mismatch.rs
  clippy_lints/src/ptr.rs
  clippy_utils/README.md
  clippy_utils/src/hir_utils.rs
  clippy_utils/src/lib.rs
  rust-toolchain.toml
Labels: S-waiting-on-review

#14526 Restrict the cases where `ptr_eq` triggers
  clippy_lints/src/ptr.rs
  tests/ui/ptr_eq.fixed
  tests/ui/ptr_eq.rs
  tests/ui/ptr_eq.stderr
  tests/ui/ptr_eq_no_std.fixed
  tests/ui/ptr_eq_no_std.rs
  tests/ui/ptr_eq_no_std.stderr
Labels: S-waiting-on-review, beta-nominated

#14671 remove non-existent pathspec from pre-commit hook
  util/etc/pre-commit.sh
Labels: S-waiting-on-review

#14682 Reword `needless_question_mark` diagnostics and docs
  clippy_lints/src/needless_question_mark.rs
  tests/ui/needless_question_mark.stderr
  tests/ui/question_mark.fixed
  tests/ui/question_mark.rs
  tests/ui/question_mark.stderr
Labels: S-waiting-on-review

#14669 style: pull one more `if` into the let-chain
  clippy_lints/src/types/vec_box.rs
Labels: S-waiting-on-review

#14643 fix: `unnecessary_cast` suggests extra brackets when in macro
  clippy_lints/src/casts/unnecessary_cast.rs
  tests/ui/unnecessary_cast.fixed
  tests/ui/unnecessary_cast.rs
  tests/ui/unnecessary_cast.stderr
Labels: S-waiting-on-author

#14504 fix: `equatable_if_let` suggests wrongly when involving reference
  clippy_lints/src/equatable_if_let.rs
  tests/ui/equatable_if_let.fixed
  tests/ui/equatable_if_let.rs
  tests/ui/equatable_if_let.stderr
Labels: S-waiting-on-review

#14666 `manual_div_ceil`: fix suggestions when macro is involved
  clippy_lints/src/manual_div_ceil.rs
  tests/ui/manual_div_ceil.fixed
  tests/ui/manual_div_ceil.rs
  tests/ui/manual_div_ceil.stderr
Labels: S-waiting-on-review

#14679 Replace some `Symbol::as_str` usage
  clippy_lints/src/assigning_clones.rs
  clippy_lints/src/attrs/blanket_clippy_restriction_lints.rs
  clippy_lints/src/attrs/deprecated_cfg_attr.rs
  clippy_lints/src/attrs/deprecated_semver.rs
  clippy_lints/src/casts/cast_abs_to_unsigned.rs
  clippy_lints/src/casts/cast_possible_truncation.rs
  clippy_lints/src/casts/cast_ptr_alignment.rs
  clippy_lints/src/crate_in_macro_def.rs
  clippy_lints/src/floating_point_arithmetic.rs
  clippy_lints/src/from_raw_with_void_ptr.rs
  clippy_lints/src/from_str_radix_10.rs
  clippy_lints/src/implicit_hasher.rs
  clippy_lints/src/infinite_iter.rs
  clippy_lints/src/iter_without_into_iter.rs
  clippy_lints/src/len_zero.rs
  clippy_lints/src/loops/same_item_push.rs
  clippy_lints/src/manual_hash_one.rs
  clippy_lints/src/manual_is_ascii_check.rs
  clippy_lints/src/manual_option_as_slice.rs
  clippy_lints/src/methods/double_ended_iterator_last.rs
  clippy_lints/src/methods/filter_map.rs
  clippy_lints/src/methods/needless_character_iteration.rs
  clippy_lints/src/methods/needless_collect.rs
  clippy_lints/src/methods/read_line_without_trim.rs
  clippy_lints/src/methods/str_split.rs
  clippy_lints/src/methods/unnecessary_filter_map.rs
  clippy_lints/src/methods/unnecessary_to_owned.rs
  clippy_lints/src/minmax.rs
  clippy_lints/src/missing_fields_in_debug.rs
  clippy_lints/src/mixed_read_write_in_expression.rs
  clippy_lints/src/needless_for_each.rs
  clippy_lints/src/non_octal_unix_permissions.rs
  clippy_lints/src/non_zero_suggestions.rs
  clippy_lints/src/operators/float_cmp.rs
  clippy_lints/src/permissions_set_readonly_false.rs
  clippy_lints/src/ptr_offset_with_cast.rs
  clippy_lints/src/question_mark.rs
  clippy_lints/src/slow_vector_initialization.rs
  clippy_lints/src/strings.rs
  clippy_lints/src/to_digit_is_some.rs
  clippy_lints/src/transmute/eager_transmute.rs
  clippy_lints/src/uninit_vec.rs
  clippy_lints/src/unused_self.rs
  clippy_lints/src/unwrap.rs
  clippy_lints/src/write.rs
  clippy_lints_internal/src/lib.rs
  clippy_lints_internal/src/symbols.rs
  clippy_utils/src/higher.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/sym.rs
  tests/ui-internal/symbol_as_str.fixed
  tests/ui-internal/symbol_as_str.rs
  tests/ui-internal/symbol_as_str.stderr
  tests/ui-internal/symbol_as_str_unfixable.rs
  tests/ui-internal/symbol_as_str_unfixable.stderr
Labels: S-waiting-on-review, performance-project
