Repository rust-lang/rust-clippy, pull requests merged in 2025-03, with the labels that each got.

#14310 Extend `{implicit,inverted}_saturating_sub` to expressions
  clippy_lints/src/doc/mod.rs
  clippy_lints/src/implicit_saturating_sub.rs
  tests/ui/implicit_saturating_sub.fixed
  tests/ui/implicit_saturating_sub.rs
  tests/ui/implicit_saturating_sub.stderr
  tests/ui/manual_arithmetic_check-2.rs
  tests/ui/manual_arithmetic_check-2.stderr
Labels: S-waiting-on-review

#14327 Suggest using `#[expect]` to check lint positioning
  clippy_utils/src/diagnostics.rs
Labels: S-waiting-on-review

#14219 `comparison_chain`: `style` → `pedantic`
  clippy_lints/src/comparison_chain.rs
  tests/ui/crashes/if_same_then_else.rs
  tests/ui/ifs_same_cond.rs
  tests/ui/ifs_same_cond.stderr
  tests/ui/same_functions_in_if_condition.rs
  tests/ui/same_functions_in_if_condition.stderr
Labels: S-waiting-on-review

#13888 fix: `undocumented_unsafe_blocks` FP on trait/impl items
  clippy_lints/src/undocumented_unsafe_blocks.rs
  tests/ui-toml/undocumented_unsafe_blocks/undocumented_unsafe_blocks.default.stderr
  tests/ui-toml/undocumented_unsafe_blocks/undocumented_unsafe_blocks.disabled.stderr
  tests/ui-toml/undocumented_unsafe_blocks/undocumented_unsafe_blocks.rs
Labels: S-waiting-on-review

#14314 fix: `map_entry` suggest wrongly when key is not `Copy`
  clippy_lints/src/entry.rs
  tests/ui/entry_unfixable.rs
  tests/ui/entry_unfixable.stderr
Labels: S-waiting-on-review

#14147 needless_collect: avoid warning if non-iterator methods are used
  clippy_lints/src/methods/needless_collect.rs
  tests/ui/needless_collect.fixed
  tests/ui/needless_collect.rs
Labels: S-waiting-on-review

#14339 Lint more cases with `ptr_eq`
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/operators/mod.rs
  clippy_lints/src/operators/ptr_eq.rs
  clippy_lints/src/ptr.rs
  tests/ui/ptr_eq.fixed
  tests/ui/ptr_eq.rs
  tests/ui/ptr_eq.stderr
  tests/ui/ptr_eq_no_std.fixed
  tests/ui/ptr_eq_no_std.rs
  tests/ui/ptr_eq_no_std.stderr
Labels: S-waiting-on-review

#14235 better help for `mixed_case_hex_literals`
  clippy_lints/src/misc_early/mixed_case_hex_literals.rs
  tests/ui/literals.rs
  tests/ui/literals.stderr
Labels: S-waiting-on-review

#14347 don't trigger `unnecessary_debug_formatting` in tests
  clippy_lints/src/format_args.rs
  tests/ui/unnecessary_path_debug_formatting.rs
Labels: S-waiting-on-review

#14349 Walk back to the root context to compute the span
  clippy_lints/src/methods/io_other_error.rs
  tests/ui/io_other_error.fixed
  tests/ui/io_other_error.rs
  tests/ui/io_other_error.stderr
Labels: S-waiting-on-review

#14252 Remove Known problems section for `vec_box`
  clippy_lints/src/types/mod.rs
Labels: S-waiting-on-review

#14355 Use `size_of` from the prelude instead of imported
  clippy_lints/src/manual_bits.rs
  clippy_lints/src/manual_slice_size_calculation.rs
  clippy_lints/src/size_of_in_element_count.rs
  clippy_lints/src/size_of_ref.rs
  tests/ui/manual_bits.stderr
  tests/ui/size_of_ref.stderr
Labels: S-waiting-on-review

#14306 Refactor function after adding a new diagnostic item
  clippy_lints/src/useless_conversion.rs
Labels: S-waiting-on-review

#14076 Make `struct_field_names` check private fields of public structs.
  clippy_lints/src/item_name_repetitions.rs
  tests/ui/struct_fields.rs
  tests/ui/struct_fields.stderr
Labels: S-waiting-on-review

#14243 `unnecessary_to_owned`: don't call `iter()` on a temporary object
  clippy_lints/src/casts/borrow_as_ptr.rs
  clippy_lints/src/methods/unnecessary_to_owned.rs
  clippy_utils/src/lib.rs
  tests/ui/unnecessary_to_owned.fixed
  tests/ui/unnecessary_to_owned.rs
  tests/ui/unnecessary_to_owned.stderr
Labels: S-waiting-on-review

#14351 docs: update rationale for excessive-bools
  clippy_lints/src/excessive_bools.rs
Labels: S-waiting-on-review

#14204 fix: `manual_let_else` missing binding mode
  clippy_lints/src/manual_let_else.rs
  tests/ui/manual_let_else.rs
  tests/ui/manual_let_else.stderr
Labels: S-waiting-on-review

#14329 rename the MSRV alias `MANUAL_DIV_CEIL` to `DIV_CEIL`
  clippy_lints/src/manual_div_ceil.rs
  clippy_utils/src/msrvs.rs
Labels: S-waiting-on-review

#14338 don't trigger `blocks_in_conditions` when the condition contains a `return`
  clippy_lints/src/blocks_in_conditions.rs
  tests/ui/blocks_in_conditions.fixed
  tests/ui/blocks_in_conditions.rs
Labels: S-waiting-on-review

#14379 fix broken theme CSS links in the website
  util/gh-pages/index_template.html
Labels: S-waiting-on-review

#14383 docs: Add documentation to json.rs module
  lintcheck/src/json.rs
Labels: S-waiting-on-review

#14371 fix: `unnecessary_safety_comment` FP on desugared assign
  clippy_lints/src/undocumented_unsafe_blocks.rs
  tests/ui-toml/undocumented_unsafe_blocks/undocumented_unsafe_blocks.default.stderr
  tests/ui-toml/undocumented_unsafe_blocks/undocumented_unsafe_blocks.disabled.stderr
  tests/ui-toml/undocumented_unsafe_blocks/undocumented_unsafe_blocks.rs
Labels: S-waiting-on-review

#14393 Make annotations mandatory for internal ui tests
  Cargo.toml
  clippy_lints/src/utils/internal_lints/produce_ice.rs
  tests/compile-test.rs
  tests/lint_message_convention.rs
  tests/ui-internal/custom_ice_message.rs
  tests/ui-internal/custom_ice_message.stderr
Labels: S-waiting-on-review

#14392 `needless_pass_by_value`: reference the innermost `Option` content
  clippy_lints/src/needless_pass_by_value.rs
  clippy_utils/src/lib.rs
  tests/ui/crashes/needless_pass_by_value-w-late-bound.stderr
  tests/ui/needless_pass_by_value.rs
  tests/ui/needless_pass_by_value.stderr
Labels: S-waiting-on-review

#14216 `incompatible_msrv`: lint function calls with any argument count
  clippy_lints/src/incompatible_msrv.rs
  tests/ui/incompatible_msrv.rs
  tests/ui/incompatible_msrv.stderr
Labels: S-waiting-on-review

#14399 Update copyright year
  COPYRIGHT
  LICENSE-APACHE
  LICENSE-MIT
  README.md
  clippy_utils/README.md
  rustc_tools_util/README.md
Labels: S-waiting-on-review

#14398 Explain `is_from_proc_macro` and `proc_macros` auxiliary crate in the book
  book/src/development/macro_expansions.md
Labels: S-waiting-on-review

#14409 Fix `from_over_into` lint suggesting invalid code
  clippy_lints/src/from_over_into.rs
  tests/ui/from_over_into.fixed
  tests/ui/from_over_into.rs
  tests/ui/from_over_into.stderr
Labels: S-waiting-on-review

#12876 new lint: `doc_comment_double_space_linebreaks`
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/doc/doc_comment_double_space_linebreaks.rs
  clippy_lints/src/doc/mod.rs
  tests/ui/doc/doc_comment_double_space_linebreaks.fixed
  tests/ui/doc/doc_comment_double_space_linebreaks.rs
  tests/ui/doc/doc_comment_double_space_linebreaks.stderr
Labels: S-final-comment-period

#14415 Remove `@xFrednet` from docs :wave:
  book/src/development/the_team.md
Labels: S-waiting-on-review

#14094 fix incorrect suggestions related to parentheses in `needless_return`
  clippy_utils/src/lib.rs
  tests/ui/needless_return.fixed
  tests/ui/needless_return.rs
  tests/ui/needless_return.stderr
Labels: S-waiting-on-review

#14158 question_mark: avoid incorrect suggestion when `ref` binding used
  clippy_lints/src/question_mark.rs
  tests/ui/question_mark.fixed
  tests/ui/question_mark.rs
  tests/ui/question_mark.stderr
Labels: S-waiting-on-review

#14396 Improve `string_to_string` lint in case it is in a map call
  clippy_lints/src/strings.rs
  tests/ui/string_to_string.rs
  tests/ui/string_to_string.stderr
  tests/ui/string_to_string_in_map.fixed
  tests/ui/string_to_string_in_map.rs
  tests/ui/string_to_string_in_map.stderr
Labels: S-waiting-on-review

#14428 Leave assignments for now
  triagebot.toml
Labels: S-waiting-on-review

#14420 Reinstate `single_match`/`single_match_else` lints with comments
  clippy_lints/src/matches/mod.rs
  clippy_lints/src/matches/single_match.rs
  tests/ui/single_match.fixed
  tests/ui/single_match.rs
  tests/ui/single_match.stderr
  tests/ui/single_match_else.fixed
  tests/ui/single_match_else.rs
  tests/ui/single_match_else.stderr
Labels: S-waiting-on-review

#14436 Add MSRV check for `question_mark`
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  clippy_lints/src/question_mark.rs
  clippy_utils/src/msrvs.rs
  tests/ui/question_mark.fixed
  tests/ui/question_mark.rs
  tests/ui/question_mark.stderr
Labels: S-waiting-on-review

#14169 fix suggestion for assignments have enclosing parentheses under `needless_late_init`
  clippy_lints/src/needless_late_init.rs
  tests/ui/needless_late_init.fixed
  tests/ui/needless_late_init.rs
  tests/ui/needless_late_init.stderr
Labels: S-waiting-on-review

#14203 make `never_loop` applicability more flexible
  clippy_lints/src/loops/never_loop.rs
  tests/ui/never_loop.rs
  tests/ui/never_loop.stderr
  tests/ui/never_loop_fixable.fixed
  tests/ui/never_loop_fixable.rs
  tests/ui/never_loop_fixable.stderr
Labels: S-waiting-on-review

#14294 fix: `missing_const_for_fn` FP on unstable const traits
  clippy_utils/src/qualify_min_const_fn.rs
  tests/ui/missing_const_for_fn/cant_be_const.rs
Labels: S-waiting-on-review

#14442 rename `rust-toolchain` to `rust-toolchain.toml`
  book/src/development/basics.md
  book/src/development/infrastructure/sync.md
  clippy_dev/src/main.rs
  clippy_dev/src/setup/toolchain.rs
  clippy_dev/src/sync.rs
  rust-toolchain.toml
Labels: S-waiting-on-review

#14447 expand `neg_multiply` to lint float numbers as well
  clippy_lints/src/neg_multiply.rs
  tests/ui/neg_multiply.fixed
  tests/ui/neg_multiply.rs
  tests/ui/neg_multiply.stderr
Labels: S-waiting-on-review

#14233 Use a lintcheck specific Clippy configuration file in the CI
  .github/workflows/lintcheck.yml
  lintcheck/ci-config/clippy.toml
Labels: S-waiting-on-review

#14405 fix: `manual_find` suggests wrongly when early return
  clippy_lints/src/loops/manual_find.rs
  tests/ui/manual_find.rs
Labels: S-waiting-on-review

#14403 fix: `borrow_deref_ref` suggests wrongly when coerce to mut
  clippy_lints/src/borrow_deref_ref.rs
  tests/ui/borrow_deref_ref.fixed
  tests/ui/borrow_deref_ref.rs
  tests/ui/borrow_deref_ref.stderr
Labels: S-waiting-on-review

#14414 Add comment annotations
  book/src/development/adding_lints.md
  book/src/development/writing_tests.md
Labels: S-waiting-on-review

#14438 set the applicability of `op_ref` to `MachineApplicable`
  clippy_lints/src/operators/op_ref.rs
  tests/ui/op_ref.fixed
  tests/ui/op_ref.rs
Labels: S-waiting-on-review

#14311 Emit `collapsible_match` at the right node
  clippy_lints/src/matches/collapsible_match.rs
  tests/ui/collapsible_match.rs
Labels: S-waiting-on-review

#14268 Add regression tests for `suspicious_doc_comments`
  tests/ui/suspicious_doc_comments.fixed
  tests/ui/suspicious_doc_comments.rs
Labels: S-waiting-on-review

#13931 Add `ignore_without_reason` lint
  CHANGELOG.md
  clippy_lints/src/attrs/mod.rs
  clippy_lints/src/declared_lints.rs
  tests/ui/ignore_without_reason.rs
  tests/ui/ignore_without_reason.stderr
Labels: S-final-comment-period

#14194 Document and improve (a lot) lintcheck --perf
  book/src/SUMMARY.md
  book/src/development/infrastructure/benchmarking.md
  lintcheck/src/main.rs
Labels: S-waiting-on-review

#14231 Lint more cases in `collapsible_if`
  CHANGELOG.md
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  clippy_lints/src/collapsible_if.rs
  clippy_lints/src/lib.rs
  tests/ui-toml/collapsible_if/clippy.toml
  tests/ui-toml/collapsible_if/collapsible_if.fixed
  tests/ui-toml/collapsible_if/collapsible_if.rs
  tests/ui-toml/collapsible_if/collapsible_if.stderr
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
  tests/ui/collapsible_if.fixed
  tests/ui/collapsible_if.rs
  tests/ui/collapsible_if.stderr
Labels: S-waiting-on-review

#14424 fix: `nonminimal_bool` wrongly showed the macro definition
  clippy_lints/src/booleans.rs
  tests/ui/nonminimal_bool.rs
  tests/ui/nonminimal_bool.stderr
Labels: S-waiting-on-review

#14448 set concurrency for the `deploy` job
  .github/workflows/deploy.yml
  book/src/development/infrastructure/release.md
Labels: S-waiting-on-review

#14385 Clarify example for unconditional_recursion
  clippy_lints/src/unconditional_recursion.rs
Labels: S-waiting-on-review

#14283 Use `code` for references to other lints in as_conversions docs
  clippy_lints/src/as_conversions.rs
Labels: S-waiting-on-review

#14468 Add myself to reviewer rotation
  triagebot.toml
Labels: S-waiting-on-review

#14280 Rename `inconsistent_struct_constructor` configuration; don't suggest deprecated configurations
  CHANGELOG.md
  book/src/lint_configuration.md
  clippy.toml
  clippy_config/src/conf.rs
  clippy_lints/src/inconsistent_struct_constructor.rs
  tests/ui-toml/toml_inconsistent_struct_constructor/clippy.toml
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
Labels: S-waiting-on-review

#14466 Fix type error in lint description
  clippy_lints/src/casts/mod.rs
Labels: S-waiting-on-review

#14358 suggest `is_some_and` instead of `map_or` in `case_sensitive_file_extension_comparions`
  clippy_lints/src/methods/case_sensitive_file_extension_comparisons.rs
  clippy_lints/src/methods/mod.rs
  tests/ui/case_sensitive_file_extension_comparisons.fixed
  tests/ui/case_sensitive_file_extension_comparisons.rs
  tests/ui/case_sensitive_file_extension_comparisons.stderr
Labels: S-waiting-on-review

#14160 Move `uninlined_format_args` back to `style`
  clippy_lints/src/format_args.rs
  tests/ui-toml/max_suggested_slice_pattern_length/index_refutable_slice.fixed
  tests/ui-toml/max_suggested_slice_pattern_length/index_refutable_slice.rs
  tests/ui-toml/max_suggested_slice_pattern_length/index_refutable_slice.stderr
  tests/ui/author/macro_in_closure.rs
  tests/ui/author/macro_in_loop.rs
  tests/ui/dbg_macro/dbg_macro.fixed
  tests/ui/dbg_macro/dbg_macro.rs
  tests/ui/dbg_macro/dbg_macro.stderr
  tests/ui/large_futures.fixed
  tests/ui/large_futures.rs
  tests/ui/large_futures.stderr
  tests/ui/manual_inspect.fixed
  tests/ui/manual_inspect.rs
  tests/ui/manual_strip_fixable.fixed
  tests/ui/manual_strip_fixable.rs
  tests/ui/manual_strip_fixable.stderr
  tests/ui/needless_pass_by_ref_mut.rs
  tests/ui/needless_pass_by_ref_mut.stderr
  tests/ui/to_string_in_format_args_incremental.fixed
  tests/ui/to_string_in_format_args_incremental.rs
  tests/ui/to_string_in_format_args_incremental.stderr
  tests/ui/unnecessary_iter_cloned.fixed
  tests/ui/unnecessary_iter_cloned.rs
  tests/ui/unnecessary_operation.fixed
  tests/ui/unnecessary_operation.rs
  tests/ui/unnecessary_operation.stderr
  tests/ui/unnecessary_os_str_debug_formatting.rs
  tests/ui/unnecessary_os_str_debug_formatting.stderr
  tests/ui/unnecessary_path_debug_formatting.rs
  tests/ui/unnecessary_path_debug_formatting.stderr
  tests/ui/unnecessary_to_owned.fixed
  tests/ui/unnecessary_to_owned.rs
  tests/ui/unnecessary_to_owned.stderr
Labels: S-final-comment-period

#14332 Unify `manual_unwrap_or` and `manual_unwrap_or_default` code
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_unwrap_or_default.rs
  clippy_lints/src/matches/manual_unwrap_or.rs
  clippy_lints/src/matches/mod.rs
  clippy_utils/src/higher.rs
  clippy_utils/src/lib.rs
  tests/ui/manual_unwrap_or.fixed
  tests/ui/manual_unwrap_or.rs
  tests/ui/manual_unwrap_or.stderr
  tests/ui/manual_unwrap_or_default.fixed
  tests/ui/manual_unwrap_or_default.rs
  tests/ui/manual_unwrap_or_default.stderr
Labels: S-waiting-on-review

#14451 Apply collapsible if to Clippy sources
  clippy.toml
  clippy_lints/src/escape.rs
  clippy_lints/src/item_name_repetitions.rs
  clippy_lints/src/mem_replace.rs
  clippy_lints/src/methods/map_clone.rs
  clippy_lints/src/methods/seek_from_current.rs
  clippy_lints/src/mixed_read_write_in_expression.rs
  lintcheck/ci-config/clippy.toml
  tests/clippy.toml
Labels: S-waiting-on-review

#14459 Fix various typos in lint messages, descriptions and comments
  clippy_lints/src/attrs/repr_attributes.rs
  clippy_lints/src/copies.rs
  clippy_lints/src/methods/unnecessary_map_or.rs
  clippy_lints/src/non_std_lazy_statics.rs
  clippy_lints/src/shadow.rs
  clippy_lints/src/zombie_processes.rs
  clippy_utils/src/str_utils.rs
  clippy_utils/src/ty/mod.rs
  lintcheck/src/recursive.rs
  tests/ui/non_std_lazy_static/non_std_lazy_static_fixable.fixed
  tests/ui/non_std_lazy_static/non_std_lazy_static_fixable.rs
  tests/ui/non_std_lazy_static/non_std_lazy_static_fixable.stderr
  tests/ui/non_std_lazy_static/non_std_lazy_static_unfixable.rs
  tests/ui/non_std_lazy_static/non_std_lazy_static_unfixable.stderr
  tests/ui/repr_packed_without_abi.stderr
Labels: S-waiting-on-review

#14389 fix: `option_if_let_else` suggests wrongly when coercion requires explicit cast
  clippy_lints/src/option_if_let_else.rs
  tests/ui/option_if_let_else.fixed
  tests/ui/option_if_let_else.rs
Labels: S-waiting-on-review, L-nursery

#14475 chore: fix some comments
  clippy_lints/src/operators/identity_op.rs
  rustc_tools_util/src/lib.rs
Labels: S-waiting-on-review

#14480 Prevent including preceeding whitespaces if line contains non blanks
  clippy_utils/src/source.rs
  tests/ui-toml/collapsible_if/collapsible_if.fixed
  tests/ui-toml/collapsible_if/collapsible_if.stderr
  tests/ui/collapsible_if.fixed
  tests/ui/collapsible_if.rs
  tests/ui/collapsible_if.stderr
  tests/ui/manual_inspect.fixed
  tests/ui/manual_inspect.rs
  tests/ui/manual_inspect.stderr
Labels: S-waiting-on-review

#14247 more natural suggestions for `cmp_owned`
  clippy_lints/src/operators/cmp_owned.rs
  tests/ui/cmp_owned/with_suggestion.fixed
  tests/ui/cmp_owned/with_suggestion.rs
  tests/ui/cmp_owned/with_suggestion.stderr
Labels: S-waiting-on-review

#14458 remove obsolete "Known Problems" in `ok_expect`
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-review

#14381 Do not warn about shadowing in a destructuring assigment
  clippy_lints/src/shadow.rs
  tests/ui/shadow.rs
Labels: S-waiting-on-review

#14487 Do not make incomplete or invalid suggestions
  clippy_lints/src/methods/unnecessary_filter_map.rs
  tests/ui/unnecessary_filter_map.rs
  tests/ui/unnecessary_filter_map.stderr
  tests/ui/unnecessary_find_map.rs
  tests/ui/unnecessary_find_map.stderr
Labels: S-waiting-on-review

#14003 Make missing_const_for_fn operate on non-optimized MIR
  clippy_lints/src/missing_const_for_fn.rs
Labels: S-waiting-on-review

#14497 fix the broken CSS links for all versions of the website
  beta/index.html
  rust-1.52.0/index.html
  rust-1.52.1/index.html
  rust-1.53.0/index.html
  rust-1.54.0/index.html
  rust-1.55.0/index.html
  rust-1.56.0/index.html
  rust-1.56.1/index.html
  rust-1.57.0/index.html
  rust-1.58.0/index.html
  rust-1.58.1/index.html
  rust-1.59.0/index.html
  rust-1.60.0/index.html
  rust-1.61.0/index.html
  rust-1.62.0/index.html
  rust-1.63.0/index.html
  rust-1.64.0/index.html
  rust-1.65.0/index.html
  rust-1.66.0/index.html
  rust-1.67.0/index.html
  rust-1.68.0/index.html
  rust-1.69.0/index.html
  rust-1.70.0/index.html
  rust-1.71.0/index.html
  rust-1.72.0/index.html
  rust-1.73.0/index.html
  rust-1.74.0/index.html
  rust-1.75.0/index.html
  rust-1.76.0/index.html
  rust-1.77.0/index.html
  rust-1.78.0/index.html
  rust-1.79.0/index.html
  rust-1.80.0/index.html
  rust-1.81.0/index.html
  rust-1.82.0/index.html
  rust-1.83.0/index.html
  rust-1.84.0/index.html
  rust-1.85.0/index.html
Labels: S-waiting-on-review

#14401 fix: `unnested_or_patterns` suggests wrongly in `let`
  clippy_lints/src/unnested_or_patterns.rs
  tests/ui/unnested_or_patterns.fixed
  tests/ui/unnested_or_patterns.rs
  tests/ui/unnested_or_patterns.stderr
Labels: S-waiting-on-review

#14500 Don't hardcode repository in changelog CI
  .github/workflows/clippy_changelog.yml
Labels: S-waiting-on-review

#13435 new lint: `char_indices_as_byte_indices`
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/loops/char_indices_as_byte_indices.rs
  clippy_lints/src/loops/mod.rs
  tests/ui/char_indices_as_byte_indices.fixed
  tests/ui/char_indices_as_byte_indices.rs
  tests/ui/char_indices_as_byte_indices.stderr
Labels: S-waiting-on-review

#14506 use `is_automatically_derived()` instead of `has_attr()`
  clippy_lints/src/derivable_impls.rs
  clippy_lints/src/derive.rs
  clippy_lints/src/missing_fields_in_debug.rs
  clippy_lints/src/partialeq_ne_impl.rs
  clippy_lints/src/unconditional_recursion.rs
Labels: S-waiting-on-review

#14107 add `manual_dangling_ptr` lint
  CHANGELOG.md
  clippy_lints/src/casts/manual_dangling_ptr.rs
  clippy_lints/src/casts/mod.rs
  clippy_lints/src/declared_lints.rs
  clippy_utils/src/msrvs.rs
  clippy_utils/src/paths.rs
  tests/ui/manual_dangling_ptr.fixed
  tests/ui/manual_dangling_ptr.rs
  tests/ui/manual_dangling_ptr.stderr
  tests/ui/transmute.rs
  tests/ui/transmute_null_to_fn.rs
  tests/ui/transmute_null_to_fn.stderr
  tests/ui/transmuting_null.rs
  tests/ui/transmuting_null.stderr
Labels: S-waiting-on-review

#14376 Make `visit_map` happy path more evident
  clippy_config/src/conf.rs
Labels: S-waiting-on-review

#14431 expand `obfuscated_if_else` to support `{then(), then_some()}.unwrap_or_default()`
  clippy_lints/src/len_zero.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/obfuscated_if_else.rs
  tests/ui/obfuscated_if_else.fixed
  tests/ui/obfuscated_if_else.rs
  tests/ui/obfuscated_if_else.stderr
Labels: S-waiting-on-review

#14495 Properly handle expansion in `single_match`
  clippy_lints/src/matches/single_match.rs
  tests/ui/single_match.fixed
  tests/ui/single_match.rs
  tests/ui/single_match.stderr
Labels: S-waiting-on-review

#14507 Suggest `./x test src/tools/clippy --bless` when in `rust-lang/rust`
  tests/compile-test.rs
Labels: S-waiting-on-review

#14508 Enable triagebot's merge conflict notifications
  triagebot.toml
Labels: S-waiting-on-review

#14282 correct version attribute for `io_other_error`
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-review
