Repository rust-lang/rust-clippy, pull requests merged in 2025-01, with the labels that each got.

#13871 Check if deref target implements `is_empty` for `len_zero` lint
  clippy_lints/src/eta_reduction.rs
  clippy_lints/src/len_zero.rs
  tests/ui/len_zero.fixed
  tests/ui/len_zero.rs
  tests/ui/len_zero.stderr
Labels: S-waiting-on-review

#13912 Improve `slow_vector_initialization` suggestion
  clippy_lints/src/slow_vector_initialization.rs
  tests/ui/slow_vector_initialization.rs
  tests/ui/slow_vector_initialization.stderr
Labels: S-waiting-on-review

#13922 Add lint for calling `Iterator::last()` on `DoubleEndedIterator`
  CHANGELOG.md
  clippy_lints/src/attrs/mixed_attributes_style.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/methods/double_ended_iterator_last.rs
  clippy_lints/src/methods/mod.rs
  clippy_utils/src/msrvs.rs
  tests/ui/double_ended_iterator_last.fixed
  tests/ui/double_ended_iterator_last.rs
  tests/ui/double_ended_iterator_last.stderr
  tests/ui/infinite_iter.rs
  tests/ui/iter_overeager_cloned.fixed
  tests/ui/iter_overeager_cloned.rs
  tests/ui/iter_overeager_cloned.stderr
  tests/ui/starts_ends_with.fixed
  tests/ui/starts_ends_with.rs
Labels: S-waiting-on-review

#13933 Make CI a little bit safer
  .github/workflows/clippy_dev.yml
  .github/workflows/clippy_mq.yml
  .github/workflows/clippy_pr.yml
  .github/workflows/deploy.yml
  .github/workflows/lintcheck.yml
  .github/workflows/remark.yml
Labels: S-waiting-on-review

#13891 [`needless_continue`]: lint if the last stmt in loop is `continue` recurisvely
  clippy_lints/src/methods/unnecessary_to_owned.rs
  clippy_lints/src/needless_continue.rs
  clippy_lints/src/redundant_else.rs
  clippy_lints/src/transmute/transmute_undefined_repr.rs
  tests/missing-test-files.rs
  tests/ui/needless_continue.rs
  tests/ui/needless_continue.stderr
Labels: S-waiting-on-review

#13911 Only emit `useless_vec` suggestion if the macro does not contain code comments
  clippy_lints/src/vec.rs
  tests/ui/useless_vec.rs
  tests/ui/useless_vec.stderr
Labels: S-waiting-on-review

#13937 Changelog for Clippy 1.84 🧨
  CHANGELOG.md
  book/src/development/infrastructure/changelog_update.md
  clippy_lints/src/manual_ignore_case_cmp.rs
  clippy_lints/src/regex.rs
  clippy_lints/src/unnecessary_literal_bound.rs
Labels: S-waiting-on-review

#13945 Do not trigger `missing_const_for_fn` for tests
  clippy_lints/src/missing_const_for_fn.rs
  tests/ui/missing_const_for_fn/cant_be_const.rs
Labels: S-waiting-on-review

#13747 `clippy::redundant_locals` is not a correctness lint
  clippy_lints/src/redundant_locals.rs
Labels: S-waiting-on-review

#13940 Don't emit machine applicable `map_flatten` lint if there are code comments
  clippy_lints/src/methods/map_flatten.rs
  tests/ui/map_flatten.rs
  tests/ui/map_flatten.stderr
Labels: S-waiting-on-review

#13944 CI: be compatible with both Rustup pre-1.28.0 and 1.28.0
  .github/workflows/clippy_mq.yml
  .github/workflows/clippy_pr.yml
Labels: S-waiting-on-review

#13932 Remove unneeded parentheses in `unnecessary_map_or` lint output
  clippy_lints/src/methods/unnecessary_map_or.rs
  tests/ui/unnecessary_map_or.fixed
  tests/ui/unnecessary_map_or.rs
  tests/ui/unnecessary_map_or.stderr
Labels: S-waiting-on-review

#13905 Do not remove identity mapping if mandatory mutability would be lost
  clippy_lints/src/methods/map_identity.rs
  tests/ui/map_identity.fixed
  tests/ui/map_identity.rs
  tests/ui/map_identity.stderr
Labels: S-waiting-on-review

#13916 Fix type suggestion for manual_is_ascii_check
  clippy_lints/src/manual_is_ascii_check.rs
  tests/ui/manual_is_ascii_check.fixed
  tests/ui/manual_is_ascii_check.rs
  tests/ui/manual_is_ascii_check.stderr
Labels: S-waiting-on-review

#13970 Rustup
  Cargo.toml
  clippy_config/Cargo.toml
  clippy_lints/Cargo.toml
  clippy_lints/src/arbitrary_source_item_ordering.rs
  clippy_lints/src/attrs/utils.rs
  clippy_lints/src/doc/mod.rs
  clippy_lints/src/doc/too_long_first_doc_paragraph.rs
  clippy_lints/src/equatable_if_let.rs
  clippy_lints/src/exit.rs
  clippy_lints/src/extra_unused_type_parameters.rs
  clippy_lints/src/functions/must_use.rs
  clippy_lints/src/functions/result.rs
  clippy_lints/src/implicit_hasher.rs
  clippy_lints/src/lifetimes.rs
  clippy_lints/src/loops/infinite_loop.rs
  clippy_lints/src/matches/match_same_arms.rs
  clippy_lints/src/matches/needless_match.rs
  clippy_lints/src/matches/single_match.rs
  clippy_lints/src/methods/unnecessary_to_owned.rs
  clippy_lints/src/missing_doc.rs
  clippy_lints/src/missing_inline.rs
  clippy_lints/src/mut_key.rs
  clippy_lints/src/no_effect.rs
  clippy_lints/src/no_mangle_with_rust_abi.rs
  clippy_lints/src/ptr.rs
  clippy_lints/src/returns.rs
  clippy_lints/src/unnecessary_box_returns.rs
  clippy_lints/src/utils/author.rs
  clippy_utils/Cargo.toml
  clippy_utils/README.md
  clippy_utils/src/check_proc_macro.rs
  clippy_utils/src/hir_utils.rs
  clippy_utils/src/lib.rs
  rust-toolchain
  tests/ui-internal/custom_ice_message.stderr
  tests/ui-toml/disallowed_macros/disallowed_macros.stderr
Labels: S-waiting-on-review

#13972 Improve `needless_as_bytes` to also detect `str::bytes()`
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/needless_as_bytes.rs
  tests/ui/needless_as_bytes.fixed
  tests/ui/needless_as_bytes.rs
  tests/ui/needless_as_bytes.stderr
Labels: S-waiting-on-review

#13942 Do not intersect spans coming from different contexts
  clippy_lints/src/no_mangle_with_rust_abi.rs
Labels: S-waiting-on-review

#13978 Mention existing labels at CONTRIBUTING
  CONTRIBUTING.md
Labels: S-waiting-on-review

#13976 CI: check the presence of the changelog line in every pull request
  .github/workflows/clippy_changelog.yml
  .github/workflows/clippy_mq.yml
Labels: S-waiting-on-review

#13949 Use diagnostic item instead of path for `core::fmt::Debug`
  clippy_lints/src/missing_fields_in_debug.rs
Labels: S-waiting-on-review

#13980 CI: rerun the changelog check on PR synchronization
  .github/workflows/clippy_changelog.yml
Labels: S-waiting-on-review

#13740 New lint: manual_ok_err
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/matches/manual_ok_err.rs
  clippy_lints/src/matches/mod.rs
  clippy_utils/src/ty/mod.rs
  tests/ui/manual_ok_err.fixed
  tests/ui/manual_ok_err.rs
  tests/ui/manual_ok_err.stderr
Labels: S-waiting-on-review

#13974 Correct version of `literal_string_with_formatting_args`
  clippy_lints/src/literal_string_with_formatting_args.rs
Labels: S-waiting-on-review

#13465 Add new lint `unneeded_struct_pattern`
  CHANGELOG.md
  clippy_lints/src/arbitrary_source_item_ordering.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/unneeded_struct_pattern.rs
  tests/ui/auxiliary/non-exhaustive-enum.rs
  tests/ui/unneeded_struct_pattern.fixed
  tests/ui/unneeded_struct_pattern.rs
  tests/ui/unneeded_struct_pattern.stderr
Labels: S-waiting-on-review

#13952 Do not trigger `redundant_pub_crate` in external macros
  clippy_lints/src/redundant_pub_crate.rs
  tests/ui/redundant_pub_crate.fixed
  tests/ui/redundant_pub_crate.rs
  tests/ui/redundant_pub_crate.stderr
Labels: S-waiting-on-review

#13853 don't suggest to use `cloned` for `Cow` in `unnecessary_to_owned`
  clippy_lints/src/methods/unnecessary_to_owned.rs
  tests/ui/unnecessary_to_owned.fixed
  tests/ui/unnecessary_to_owned.rs
Labels: S-waiting-on-review

#13935 Fix not found links at Book
  book/src/development/common_tools_writing_lints.md
Labels: S-waiting-on-review

#13958 Fix macro name in the Book
  book/src/development/defining_lints.md
Labels: S-waiting-on-review

#13930 Fix link to release tags
  book/src/development/infrastructure/release.md
Labels: S-waiting-on-review

#13955 fix(adding_lints): usage of early vs late lint pass
  book/src/development/adding_lints.md
Labels: A-documentation, S-waiting-on-review

#13947 auto-fix `slow_vector_initialization` in some cases
  clippy_lints/src/slow_vector_initialization.rs
  tests/ui/slow_vector_initialization.fixed
  tests/ui/slow_vector_initialization.rs
Labels: S-waiting-on-review

#13751 Select Rust edition 2024 for compiling Clippy
  .github/workflows/remark.yml
  Cargo.toml
  book/book.toml
  book/src/development/adding_lints.md
  clippy_config/Cargo.toml
  clippy_dev/Cargo.toml
  clippy_dummy/Cargo.toml
  clippy_lints/Cargo.toml
  clippy_utils/Cargo.toml
  lintcheck/Cargo.toml
  rustc_tools_util/Cargo.toml
  rustfmt.toml
  tests/compile-test.rs
  tests/ui/crashes/ice-11422.fixed
  tests/ui/crashes/ice-11422.rs
  tests/ui/crashes/ice-11422.stderr
  tests/ui/implicit_hasher.fixed
  tests/ui/implicit_hasher.rs
  tests/ui/implicit_hasher.stderr
  tests/ui/map_with_unused_argument_over_ranges.fixed
  tests/ui/map_with_unused_argument_over_ranges.rs
Labels: S-waiting-on-review

#13985 Do not look for significant drop inside `.await` expansion
  clippy_lints/src/matches/significant_drop_in_scrutinee.rs
  tests/ui/significant_drop_in_scrutinee.rs
  tests/ui/significant_drop_in_scrutinee.stderr
Labels: S-waiting-on-review

#13951 Suggest `manual_div_ceil` even when right operand is a constant
  clippy_lints/src/manual_div_ceil.rs
  tests/ui/manual_div_ceil.fixed
  tests/ui/manual_div_ceil.rs
  tests/ui/manual_div_ceil.stderr
  tests/ui/manual_div_ceil_with_feature.fixed
  tests/ui/manual_div_ceil_with_feature.rs
  tests/ui/manual_div_ceil_with_feature.stderr
Labels: S-waiting-on-review

#13992 Rust 1.81 and later support elision with explicit self types
  clippy_lints/src/lib.rs
  clippy_lints/src/lifetimes.rs
  clippy_utils/src/msrvs.rs
  tests/ui/needless_lifetimes.fixed
  tests/ui/needless_lifetimes.rs
  tests/ui/needless_lifetimes.stderr
Labels: S-waiting-on-review

#13993 New lint `useless-nonzero-new_unchecked`
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/useless_nonzero_new_unchecked.rs
  clippy_utils/src/msrvs.rs
  tests/ui/useless_nonzero_new_unchecked.fixed
  tests/ui/useless_nonzero_new_unchecked.rs
  tests/ui/useless_nonzero_new_unchecked.stderr
Labels: S-waiting-on-review

#14005 Pause assignments for @xFrednet
  triagebot.toml
Labels: S-waiting-on-review

#14016 fix version search in the website
  util/gh-pages/script.js
Labels: S-waiting-on-review

#13810 Update doc wildcard_dependencies
  clippy_lints/src/cargo/mod.rs
Labels: S-waiting-on-review

#14025 Fix typo in `check_clousure` function name
  clippy_lints/src/eta_reduction.rs
Labels: S-waiting-on-review

#13839 Emit `missing_const_for_fn` for `CONST_MUT_REFS`
  clippy_utils/src/msrvs.rs
  clippy_utils/src/qualify_min_const_fn.rs
  tests/ui/missing_const_for_fn/cant_be_const.rs
  tests/ui/missing_const_for_fn/could_be_const.fixed
  tests/ui/missing_const_for_fn/could_be_const.rs
  tests/ui/missing_const_for_fn/could_be_const.stderr
Labels: S-waiting-on-review

#14014 change `literal_string_with_formatting_args` lint category to nursery
  clippy_lints/src/literal_string_with_formatting_args.rs
Labels: S-waiting-on-review, beta-nominated

#13858 add a new lint for `repeat().take()` that can be replaced with `repeat_n()`
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/doc/lazy_continuation.rs
  clippy_lints/src/methods/manual_repeat_n.rs
  clippy_lints/src/methods/mod.rs
  clippy_utils/src/lib.rs
  tests/ui/from_iter_instead_of_collect.fixed
  tests/ui/from_iter_instead_of_collect.rs
  tests/ui/manual_repeat_n.fixed
  tests/ui/manual_repeat_n.rs
  tests/ui/manual_repeat_n.stderr
  tests/ui/manual_str_repeat.fixed
  tests/ui/manual_str_repeat.rs
  tests/ui/slow_vector_initialization.fixed
  tests/ui/slow_vector_initialization.rs
  tests/ui/slow_vector_initialization.stderr
Labels: S-final-comment-period

#13998 Use clearer multipart suggestions for `unnecessary_map_or` lint
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/unnecessary_map_or.rs
  tests/ui/unnecessary_map_or.stderr
Labels: S-waiting-on-review

#14019 fix: correct suggestion for significant_drop_in_scrutinee in expressions
  clippy_lints/src/matches/significant_drop_in_scrutinee.rs
  tests/ui/significant_drop_in_scrutinee.rs
  tests/ui/significant_drop_in_scrutinee.stderr
Labels: S-waiting-on-review

#14053 don't trigger `needless_late_init` when the first usage is in macro
  clippy_lints/src/needless_late_init.rs
  tests/ui/needless_late_init.fixed
  tests/ui/needless_late_init.rs
Labels: S-waiting-on-review

#14047 `short_circuit_statement`: handle macros and parenthesis better
  clippy_lints/src/misc.rs
  tests/ui/short_circuit_statement.fixed
  tests/ui/short_circuit_statement.rs
  tests/ui/short_circuit_statement.stderr
Labels: S-waiting-on-review

#13987 Suggest using `Vec::extend()` in `same_item_push`
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  clippy_lints/src/loops/mod.rs
  clippy_lints/src/loops/same_item_push.rs
  tests/ui/same_item_push.rs
  tests/ui/same_item_push.stderr
Labels: S-waiting-on-review

#14039 `match_bool`: fix suggestion if guard is present
  clippy_lints/src/matches/match_bool.rs
  tests/ui/match_bool.fixed
  tests/ui/match_bool.rs
  tests/ui/match_bool.stderr
Labels: S-waiting-on-review

#14062 `arithmetic_side_effects`: check adjusted expression types
  clippy_lints/src/operators/arithmetic_side_effects.rs
  tests/ui/arithmetic_side_effects.rs
  tests/ui/arithmetic_side_effects.stderr
Labels: S-waiting-on-review

#14040 Fix out-of-date comment
  clippy_lints/src/methods/unnecessary_sort_by.rs
Labels: S-waiting-on-review

#14035 Add necessary adjustments to suggestion to remove redundant `.into_iter()` calls
  clippy_lints/src/useless_conversion.rs
  tests/ui/useless_conversion.fixed
  tests/ui/useless_conversion.rs
  tests/ui/useless_conversion.stderr
Labels: S-waiting-on-review

#14055 docs: fix verbose-bit-mask example
  clippy_lints/src/operators/mod.rs
Labels: S-waiting-on-review

#13770 add new lint `non_std_lazy_statics`
  CHANGELOG.md
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/non_std_lazy_statics.rs
  clippy_utils/src/msrvs.rs
  tests/ui/non_std_lazy_static/auxiliary/lazy_static.rs
  tests/ui/non_std_lazy_static/auxiliary/once_cell.rs
  tests/ui/non_std_lazy_static/non_std_lazy_static_fixable.fixed
  tests/ui/non_std_lazy_static/non_std_lazy_static_fixable.rs
  tests/ui/non_std_lazy_static/non_std_lazy_static_fixable.stderr
  tests/ui/non_std_lazy_static/non_std_lazy_static_no_std.rs
  tests/ui/non_std_lazy_static/non_std_lazy_static_other_once_cell.rs
  tests/ui/non_std_lazy_static/non_std_lazy_static_unfixable.rs
  tests/ui/non_std_lazy_static/non_std_lazy_static_unfixable.stderr
Labels: S-waiting-on-review

#14021 trigger `obfuscated_if_else` for `.then(..).unwrap_or(..)`
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/obfuscated_if_else.rs
  tests/ui/obfuscated_if_else.fixed
  tests/ui/obfuscated_if_else.rs
  tests/ui/obfuscated_if_else.stderr
Labels: S-waiting-on-review

#14069 set default PR messages to fail the changelog CI
  .github/workflows/clippy_changelog.yml
Labels: S-waiting-on-review

#14081 fixed a missing description of the MSRV option for `manual_repeat_n`
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
Labels: S-waiting-on-review

#14078 Remove "Known problems" section for `borrow_interior_mutable_const`
  clippy_lints/src/non_copy_const.rs
Labels: S-waiting-on-review

#14002 New lint `sliced_string_as_bytes`
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/sliced_string_as_bytes.rs
  tests/ui/bytes_nth.fixed
  tests/ui/bytes_nth.rs
  tests/ui/bytes_nth.stderr
  tests/ui/sliced_string_as_bytes.fixed
  tests/ui/sliced_string_as_bytes.rs
  tests/ui/sliced_string_as_bytes.stderr
Labels: S-waiting-on-review

#13999 correct suggestions in `no_std`
  clippy_lints/src/eta_reduction.rs
  clippy_lints/src/methods/drain_collect.rs
  clippy_lints/src/methods/map_with_unused_argument_over_ranges.rs
  clippy_lints/src/repeat_vec_with_capacity.rs
  clippy_lints/src/single_range_in_vec_init.rs
  tests/ui/drain_collect_nostd.fixed
  tests/ui/drain_collect_nostd.rs
  tests/ui/drain_collect_nostd.stderr
  tests/ui/eta_nostd.fixed
  tests/ui/eta_nostd.rs
  tests/ui/eta_nostd.stderr
  tests/ui/map_with_unused_argument_over_ranges_nostd.fixed
  tests/ui/map_with_unused_argument_over_ranges_nostd.rs
  tests/ui/map_with_unused_argument_over_ranges_nostd.stderr
  tests/ui/repeat_vec_with_capacity_nostd.fixed
  tests/ui/repeat_vec_with_capacity_nostd.rs
  tests/ui/repeat_vec_with_capacity_nostd.stderr
Labels: S-waiting-on-review

#14061 proper applicability for `obfuscated_if_else`
  clippy_lints/src/methods/obfuscated_if_else.rs
  tests/ui/obfuscated_if_else.fixed
  tests/ui/obfuscated_if_else.rs
  tests/ui/obfuscated_if_else.stderr
Labels: S-waiting-on-review

#13711 Add new lint `doc_overindented_list_items`
  CHANGELOG.md
  README.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/doc/lazy_continuation.rs
  clippy_lints/src/doc/mod.rs
  tests/ui/doc/doc_lazy_list.fixed
  tests/ui/doc/doc_lazy_list.rs
  tests/ui/doc/doc_lazy_list.stderr
  tests/ui/doc/doc_overindented_list_items.fixed
  tests/ui/doc/doc_overindented_list_items.rs
  tests/ui/doc/doc_overindented_list_items.stderr
Labels: S-waiting-on-review

#14084 exclude some directories from `Lintcheck` CI
  .github/workflows/lintcheck.yml
Labels: S-waiting-on-review

#14042 `needless_option_take`: add autofix
  clippy_lints/src/methods/needless_option_take.rs
  tests/ui/needless_option_take.fixed
  tests/ui/needless_option_take.stderr
Labels: S-waiting-on-review

#13990 Fix escaping problem in `write_literal` and `print_literal` lint suggestion
  clippy_lints/src/write.rs
  tests/ui/print_literal.fixed
  tests/ui/print_literal.rs
  tests/ui/print_literal.stderr
  tests/ui/write_literal.fixed
  tests/ui/write_literal.rs
  tests/ui/write_literal.stderr
Labels: S-waiting-on-review

#13894 Move `format_push_string` and `format_collect` to pedantic
  clippy_dev/src/new_lint.rs
  clippy_lints/src/endian_bytes.rs
  clippy_lints/src/format_push_string.rs
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-review

#13936 autofix for `redundant_else` lint
  clippy_lints/src/redundant_else.rs
  tests/ui/redundant_else.fixed
  tests/ui/redundant_else.stderr
Labels: S-waiting-on-review

#14105 Include generic arguments when suggesting a closure η-reduction
  clippy_lints/src/eta_reduction.rs
  tests/ui/eta.fixed
  tests/ui/eta.rs
  tests/ui/eta.stderr
Labels: S-waiting-on-review

#14051 feat: new lint for `and_then` when returning Option or Result
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/return_and_then.rs
  clippy_lints/src/methods/unnecessary_lazy_eval.rs
  tests/ui/return_and_then.fixed
  tests/ui/return_and_then.rs
  tests/ui/return_and_then.stderr
Labels: S-waiting-on-review

#14117 `sliced_string_as_bytes`: fix typo in lint description
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-review

#14103 Do not remove semicolon if it changes the block type
  clippy_lints/src/unnecessary_semicolon.rs
  tests/ui/unnecessary_semicolon.edition2021.fixed
  tests/ui/unnecessary_semicolon.edition2024.fixed
  tests/ui/unnecessary_semicolon.rs
Labels: S-waiting-on-review
