Repository rust-lang/rust-clippy, pull requests merged in 2025-07, with the labels that each got.

#15177 Activate feature freeze automated notice
  .github/workflows/feature_freeze.yml
Labels: S-waiting-on-review

#15167 Polishing changelog update doc
  book/src/development/infrastructure/backport.md
  book/src/development/infrastructure/changelog_update.md
Labels: S-waiting-on-review

#15146 doc_nested_refdefs: do not falsely report checkboxes as refdefs
  clippy_lints/src/doc/mod.rs
  tests/ui/doc/doc_nested_refdef_list_item.fixed
  tests/ui/doc/doc_nested_refdef_list_item.rs
  tests/ui/doc/doc_nested_refdef_list_item.stderr
Labels: S-waiting-on-review

#14916 Add Triagebot's `concern` capability to the Clippy repository
  triagebot.toml
Labels: S-waiting-on-review

#15207 bump termize
  Cargo.toml
Labels: S-waiting-on-review

#15140 Reduce page size and number of DOM elements on clippy lints page
  util/gh-pages/index_template.html
  util/gh-pages/style.css
Labels: S-waiting-on-review

#15208 Simplify clippy lints page further
  util/gh-pages/index_template.html
  util/gh-pages/script.js
  util/gh-pages/style.css
Labels: S-waiting-on-review

#15214 Not on vacation, again!
  triagebot.toml
Labels: S-waiting-on-review

#15182 Do not remove `as` if it changes the type
  clippy_lints/src/no_effect.rs
  tests/ui/unnecessary_operation.fixed
  tests/ui/unnecessary_operation.rs
Labels: S-waiting-on-review

#15144 fix: redundant_closure_call lint for closures with block
  clippy_lints/src/redundant_closure_call.rs
  tests/ui/redundant_closure_call_fixable.fixed
  tests/ui/redundant_closure_call_fixable.rs
  tests/ui/redundant_closure_call_fixable.stderr
Labels: S-waiting-on-review

#15179 FIX: NegMultiply should preserve parenthesis when method is called
  clippy_lints/src/neg_multiply.rs
  tests/ui/neg_multiply.fixed
  tests/ui/neg_multiply.rs
  tests/ui/neg_multiply.stderr
Labels: S-waiting-on-review

#15118 Handle potentially-shadowing bindings in `manual_let_else`
  clippy_lints/src/manual_let_else.rs
  tests/ui/manual_let_else_match.fixed
  tests/ui/manual_let_else_match.rs
  tests/ui/manual_let_else_match.stderr
Labels: S-waiting-on-review

#15115 Properly check that an expression might be the one returned
  clippy_lints/src/methods/return_and_then.rs
  clippy_utils/src/lib.rs
  tests/ui/return_and_then.fixed
  tests/ui/return_and_then.rs
  tests/ui/return_and_then.stderr
Labels: S-waiting-on-review, beta-nominated

#15073 or_fun_call: also lint `and` method for Option/Result
  clippy_lints/src/methods/or_fun_call.rs
  tests/ui/or_fun_call.fixed
  tests/ui/or_fun_call.rs
  tests/ui/or_fun_call.stderr
Labels: S-waiting-on-review

#14816 Create summary comment for lintcheck runs
  .github/workflows/lintcheck.yml
  .github/workflows/lintcheck_summary.yml
  lintcheck/src/config.rs
  lintcheck/src/json.rs
  lintcheck/src/main.rs
Labels: S-waiting-on-review

#14874 triagebot: enable issue transfer
  triagebot.toml
Labels: S-waiting-on-review

#15181 Do not remove method call if type is adjusted
  clippy_lints/src/methods/unnecessary_map_or.rs
  tests/ui/unnecessary_map_or.fixed
  tests/ui/unnecessary_map_or.rs
  tests/ui/unnecessary_map_or.stderr
Labels: S-waiting-on-review

#15206 Fix `manual_is_variant_and` condition generation
  clippy_lints/src/methods/manual_is_variant_and.rs
  tests/ui/manual_is_variant_and.fixed
  tests/ui/manual_is_variant_and.rs
  tests/ui/manual_is_variant_and.stderr
Labels: S-waiting-on-review, beta-nominated, I-suggestion-causes-bug

#15070 Fix multiple problems in #15063
  clippy_lints/src/needless_bool.rs
  clippy_lints/src/operators/op_ref.rs
  tests/ui/needless_bool_assign.fixed
  tests/ui/needless_bool_assign.rs
  tests/ui/needless_bool_assign.stderr
  tests/ui/op_ref.fixed
  tests/ui/op_ref.rs
  tests/ui/op_ref.stderr
Labels: S-waiting-on-review

#15231 Cleanup feature_freeze workflow
  .github/workflows/feature_freeze.yml
Labels: S-waiting-on-review

#15218 Fix few typos
  clippy_lints/src/disallowed_macros.rs
  tests/ui/auxiliary/external_item.rs
  tests/ui/used_underscore_items.rs
Labels: S-waiting-on-review

#15074 or_fun_call: lint method calls inside map_or first arg
  clippy_lints/src/methods/or_fun_call.rs
  clippy_lints/src/needless_pass_by_value.rs
  clippy_utils/src/diagnostics.rs
  tests/ui/or_fun_call.fixed
  tests/ui/or_fun_call.rs
  tests/ui/or_fun_call.stderr
Labels: S-waiting-on-review

#15191 fix `legacy_numeric_constants` suggestion when call is wrapped in parens
  clippy_lints/src/legacy_numeric_constants.rs
  tests/ui/legacy_numeric_constants.fixed
  tests/ui/legacy_numeric_constants.rs
  tests/ui/legacy_numeric_constants.stderr
Labels: S-waiting-on-review

#15228 Add `uninlined_format_args` example for `{:?}`
  clippy_lints/src/format_args.rs
Labels: S-waiting-on-review

#15229 `{flat_,}map_identity`: recognize `|[x, y]| [x, y]` as an identity function as well
  clippy_utils/src/lib.rs
  tests/ui/flat_map_identity.fixed
  tests/ui/flat_map_identity.rs
  tests/ui/flat_map_identity.stderr
  tests/ui/map_identity.fixed
  tests/ui/map_identity.rs
  tests/ui/map_identity.stderr
Labels: S-waiting-on-review

#15236 Fix `approx_const` for some new cases
  clippy_lints/src/approx_const.rs
  tests/ui/approx_const.rs
  tests/ui/approx_const.stderr
Labels: S-waiting-on-review

#15239 Update manual_is_variant_and documentation to include equality comparison
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-review

#15265 Fix `manual_abs_diff` suggests wrongly behind refs
  clippy_lints/src/manual_abs_diff.rs
  tests/ui/manual_abs_diff.fixed
  tests/ui/manual_abs_diff.rs
  tests/ui/manual_abs_diff.stderr
Labels: S-waiting-on-review

#15264 Fix `manual_assert` suggests wrongly for macros
  clippy_lints/src/manual_assert.rs
  tests/ui/manual_assert.edition2018.stderr
  tests/ui/manual_assert.edition2021.stderr
  tests/ui/manual_assert.rs
Labels: S-waiting-on-review

#15205 Fix manual is multiple of
  clippy_lints/src/operators/manual_is_multiple_of.rs
  clippy_utils/src/ty/type_certainty/mod.rs
  tests/ui/manual_is_multiple_of.fixed
  tests/ui/manual_is_multiple_of.rs
  tests/ui/manual_is_multiple_of.stderr
Labels: S-waiting-on-review

#15122 Fix expect_fun_call producing invalid suggestions
  clippy_lints/src/methods/expect_fun_call.rs
  tests/ui/expect_fun_call.fixed
  tests/ui/expect_fun_call.rs
  tests/ui/expect_fun_call.stderr
Labels: S-waiting-on-review

#15271 `ineffective_open_options`: remove `method_call` use
  clippy_lints/src/ineffective_open_options.rs
Labels: S-waiting-on-review

#15274 `useless_conversion`: move all the impl to the same lint pass
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/useless_conversion.rs
Labels: S-waiting-on-review

#15278 gh-pages: reduce page size by skipping spaces
  util/gh-pages/index_template.html
Labels: S-waiting-on-review

#15250 Use `$RUSTC` instead of `rustc` to get version if var is available
  rustc_tools_util/src/lib.rs
Labels: S-waiting-on-review

#15105 Fix `ptr_arg` suggests changes when it's actually better not to bother
  clippy_lints/src/ptr.rs
  tests/ui/ptr_arg.rs
  tests/ui/ptr_arg.stderr
Labels: S-waiting-on-review

#15287 Move `uninlined_format_args` to `pedantic`
  clippy_lints/src/format_args.rs
Labels: S-waiting-on-review

#14432 Propose to exchange ranges only when it is safe to do so
  clippy_lints/src/cognitive_complexity.rs
  clippy_lints/src/doc/mod.rs
  clippy_lints/src/methods/manual_inspect.rs
  clippy_lints/src/ranges.rs
  tests/ui/range_plus_minus_one.fixed
  tests/ui/range_plus_minus_one.rs
  tests/ui/range_plus_minus_one.stderr
Labels: S-waiting-on-review

#14433 Various improvements to the `incompatible_msrv` lint
  clippy_lints/src/incompatible_msrv.rs
  tests/ui-toml/check_incompatible_msrv_in_tests/check_incompatible_msrv_in_tests.enabled.stderr
  tests/ui/checked_conversions.fixed
  tests/ui/checked_conversions.rs
  tests/ui/checked_conversions.stderr
  tests/ui/incompatible_msrv.rs
  tests/ui/incompatible_msrv.stderr
Labels: S-waiting-on-review

#15289 Fix `ptr_as_ptr` suggests wrongly with turbo fish
  clippy_lints/src/casts/ptr_as_ptr.rs
  tests/ui/ptr_as_ptr.fixed
  tests/ui/ptr_as_ptr.rs
  tests/ui/ptr_as_ptr.stderr
Labels: S-waiting-on-review

#15296 Warn about types not meeting MSRV
  clippy_lints/src/incompatible_msrv.rs
  tests/ui/incompatible_msrv.rs
  tests/ui/incompatible_msrv.stderr
Labels: C-bug, S-waiting-on-author, I-false-negative

#15297 Warn about `const` instability wrt MSRV
  clippy_lints/src/incompatible_msrv.rs
  tests/ui/incompatible_msrv.rs
  tests/ui/incompatible_msrv.stderr
Labels: C-bug, S-waiting-on-review, I-false-negative

#15310 Simplify `must_use_candidate` spans
  clippy_lints/src/functions/must_use.rs
  tests/ui/must_use_candidates.fixed
  tests/ui/must_use_candidates.stderr
Labels: S-waiting-on-review

#15314 Fix `needless_range_loop` FP on array literals
  clippy_lints/src/loops/needless_range_loop.rs
  tests/ui/needless_range_loop.rs
Labels: S-waiting-on-review

#15048 Fix `filter_map_bool_then` wrongly suggests macro definitions
  clippy_lints/src/methods/filter_map_bool_then.rs
  tests/ui/filter_map_bool_then.fixed
  tests/ui/filter_map_bool_then.rs
  tests/ui/filter_map_bool_then.stderr
Labels: S-waiting-on-review

#15124 Fix capacity overflow in `single_match` with deref patterns
  clippy_lints/src/matches/single_match.rs
  tests/ui/single_match_else_deref_patterns.fixed
  tests/ui/single_match_else_deref_patterns.rs
  tests/ui/single_match_else_deref_patterns.stderr
Labels: S-waiting-on-review

#15241 Fixed issue #15192
  clippy_lints/src/large_enum_variant.rs
  tests/ui-toml/enum_variant_size/enum_variant_size.stderr
  tests/ui/large_enum_variant.32bit.stderr
  tests/ui/large_enum_variant.64bit.stderr
  tests/ui/large_enum_variant_no_std.rs
  tests/ui/large_enum_variant_no_std.stderr
Labels: S-waiting-on-review

#15306 fix: ignore pattern_type_mismatch when external macro owns the match
  clippy_lints/src/pattern_type_mismatch.rs
  tests/ui/pattern_type_mismatch/auxiliary/external.rs
  tests/ui/pattern_type_mismatch/syntax.rs
  tests/ui/pattern_type_mismatch/syntax.stderr
Labels: S-waiting-on-review

#15318 Fix false positive in useless_attribute with redundant_imports
  clippy_lints/src/attrs/useless_attribute.rs
  clippy_utils/src/sym.rs
  tests/ui/useless_attribute.fixed
  tests/ui/useless_attribute.rs
Labels: S-waiting-on-review

#15319 Fix `module_name_repetitions` FP on exported macros
  clippy_lints/src/item_name_repetitions.rs
  tests/ui/module_name_repetitions.rs
Labels: S-waiting-on-review

#15267 Fix `if_then_some_else_none` FP when require type coercion
  clippy_lints/src/if_then_some_else_none.rs
  clippy_utils/src/lib.rs
  tests/ui/if_then_some_else_none.fixed
  tests/ui/if_then_some_else_none.rs
  tests/ui/if_then_some_else_none.stderr
  tests/ui/if_then_some_else_none_unfixable.rs
  tests/ui/if_then_some_else_none_unfixable.stderr
Labels: S-waiting-on-author

#15355 Fix `empty_structs_with_brackets` suggests wrongly on generics
  clippy_lints/src/empty_with_brackets.rs
  tests/ui/empty_structs_with_brackets.fixed
  tests/ui/empty_structs_with_brackets.rs
  tests/ui/empty_structs_with_brackets.stderr
Labels: S-waiting-on-review

#15345 fix: `unnecessary_map_or` don't add parens if the parent expr comes f…
  clippy_lints/src/methods/unnecessary_map_or.rs
  tests/ui/unnecessary_map_or.fixed
  tests/ui/unnecessary_map_or.rs
  tests/ui/unnecessary_map_or.stderr
Labels: S-waiting-on-review

#15085 Fix `let_unit_value` suggests wrongly for format macros
  clippy_lints/src/lib.rs
  clippy_lints/src/unit_types/let_unit_value.rs
  clippy_lints/src/unit_types/mod.rs
  tests/ui/let_unit.fixed
  tests/ui/let_unit.rs
  tests/ui/let_unit.stderr
Labels: S-waiting-on-review

#15357 Fix typo non_std_lazy_statics.rs
  clippy_lints/src/non_std_lazy_statics.rs
Labels: S-waiting-on-review

#15358 Fix `cast-lossless` should not suggest when casting type is from macro input
  clippy_lints/src/casts/cast_lossless.rs
  tests/ui/cast_lossless_integer_unfixable.rs
Labels: S-waiting-on-review

#15175 Do not autofix comments containing bare CR
  clippy_lints/src/four_forward_slashes.rs
  tests/ui/four_forward_slashes_bare_cr.rs
  tests/ui/four_forward_slashes_bare_cr.stderr
Labels: S-waiting-on-review

#15013 Fix `iter_on_single_items` FP on function pointers and let stmts
  clippy_lints/src/methods/iter_on_single_or_empty_collections.rs
  clippy_utils/src/ty/mod.rs
  tests/ui/iter_on_single_items.fixed
  tests/ui/iter_on_single_items.rs
Labels: S-waiting-on-review

#15366 Optimize some usages of `!!` and `--` in suggestions
  clippy_lints/src/floating_point_arithmetic.rs
  clippy_utils/src/sugg.rs
  tests/ui/nonminimal_bool.rs
  tests/ui/nonminimal_bool.stderr
Labels: S-waiting-on-review

#15371 Output lintcheck summary HTML markdown in order
  lintcheck/src/json.rs
Labels: S-waiting-on-review
