Repository rust-lang/rust-clippy, pull requests merged in 2025-06, with the labels that each got.

#14792 new restriction lint: pointer_format
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/format_args.rs
  tests/ui/pointer_format.rs
  tests/ui/pointer_format.stderr
Labels: S-waiting-on-author, S-final-comment-period

#14948 Do not count deprecated lints in lint total
  util/gh-pages/script.js
Labels: S-waiting-on-review

#14957 Use `None::<u64>` instead of `0` to denote an absence of value
  clippy_lints/src/casts/cast_lossless.rs
  clippy_lints/src/casts/cast_possible_truncation.rs
  clippy_lints/src/casts/cast_possible_wrap.rs
  clippy_lints/src/casts/cast_precision_loss.rs
  clippy_lints/src/casts/fn_to_numeric_cast.rs
  clippy_lints/src/casts/fn_to_numeric_cast_with_truncation.rs
  clippy_lints/src/casts/utils.rs
Labels: S-waiting-on-review

#14759 `missing_const_for_fn`: consider constness of instance
  clippy_utils/src/qualify_min_const_fn.rs
  tests/ui/missing_const_for_fn/const_trait.fixed
  tests/ui/missing_const_for_fn/const_trait.rs
  tests/ui/missing_const_for_fn/const_trait.stderr
Labels: S-waiting-on-review

#14963 Use interned strings when possible, for efficiency purposes
  clippy_lints/src/attrs/deprecated_cfg_attr.rs
  clippy_lints/src/casts/cast_ptr_alignment.rs
  clippy_lints/src/if_let_mutex.rs
  clippy_lints/src/implicit_saturating_sub.rs
  clippy_lints/src/manual_clamp.rs
  clippy_lints/src/manual_string_new.rs
  clippy_lints/src/match_result_ok.rs
  clippy_lints/src/matches/match_str_case_mismatch.rs
  clippy_lints/src/methods/iter_kv_map.rs
  clippy_lints/src/methods/manual_saturating_arithmetic.rs
  clippy_lints/src/methods/needless_collect.rs
  clippy_lints/src/methods/open_options.rs
  clippy_lints/src/methods/str_splitn.rs
  clippy_lints/src/multiple_bound_locations.rs
  clippy_lints/src/pathbuf_init_then_push.rs
  clippy_lints/src/ptr.rs
  clippy_lints/src/read_zero_byte_vec.rs
  clippy_lints/src/reserve_after_initialization.rs
  clippy_lints/src/serde_api.rs
  clippy_lints/src/strings.rs
  clippy_lints/src/transmute/missing_transmute_annotations.rs
  clippy_lints/src/types/borrowed_box.rs
  clippy_lints/src/unused_io_amount.rs
  clippy_lints/src/unused_result_ok.rs
  clippy_lints/src/unused_unit.rs
  clippy_lints/src/vec_init_then_push.rs
  clippy_lints/src/wildcard_imports.rs
  clippy_utils/src/sym.rs
Labels: S-waiting-on-review

#14910 Remove incremental test, disable incremental for cargo tests
  tests/compile-test.rs
  tests/ui/to_string_in_format_args_incremental.fixed
  tests/ui/to_string_in_format_args_incremental.rs
  tests/ui/to_string_in_format_args_incremental.stderr
Labels: S-waiting-on-review

#14976 Do not lint macro generated codes
  clippy_lints/src/disallowed_names.rs
  tests/ui/disallowed_names.rs
  tests/ui/disallowed_names.stderr
Labels: S-waiting-on-review

#14812 Introduce coerce_container_to_any
  CHANGELOG.md
  clippy_lints/src/coerce_container_to_any.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  tests/ui/coerce_container_to_any.fixed
  tests/ui/coerce_container_to_any.rs
  tests/ui/coerce_container_to_any.stderr
Labels: S-waiting-on-review

#14965 Do not recurse indefinitely while checking for inner mutability
  clippy_utils/src/ty/mod.rs
  tests/ui/crashes/ice-14935.rs
Labels: S-waiting-on-review

#14962 Fix false positive for unused_unit
  clippy_lints/src/unused_unit.rs
  tests/ui/unused_unit.edition2021.fixed
  tests/ui/unused_unit.edition2024.fixed
  tests/ui/unused_unit.rs
Labels: S-waiting-on-review

#15012 Add missing word to `cloned_ref_to_slice_refs` docs
  clippy_lints/src/cloned_ref_to_slice_refs.rs
Labels: S-waiting-on-review

#15015 Invert suggestion if pointer is tested for non-nullness
  clippy_lints/src/ptr.rs
  tests/ui/cmp_null.fixed
  tests/ui/cmp_null.rs
  tests/ui/cmp_null.stderr
Labels: S-waiting-on-review

#15017 Fix `match_single_binding` misses curlies on type signatures
  clippy_lints/src/matches/match_single_binding.rs
  tests/ui/match_single_binding.fixed
  tests/ui/match_single_binding.rs
  tests/ui/match_single_binding.stderr
Labels: S-waiting-on-review

#14881 Fix `unit_arg` suggests wrongly for `Default::default`
  clippy_lints/src/default.rs
  clippy_lints/src/unit_types/unit_arg.rs
  clippy_utils/src/lib.rs
  tests/ui/unit_arg.rs
  tests/ui/unit_arg.stderr
  tests/ui/unit_arg_empty_blocks.fixed
  tests/ui/unit_arg_empty_blocks.rs
  tests/ui/unit_arg_empty_blocks.stderr
  tests/ui/unit_arg_fixable.fixed
  tests/ui/unit_arg_fixable.rs
  tests/ui/unit_arg_fixable.stderr
Labels: S-waiting-on-review

#15044 Rustup
  clippy_lints/src/arbitrary_source_item_ordering.rs
  clippy_lints/src/disallowed_types.rs
  clippy_lints/src/empty_with_brackets.rs
  clippy_lints/src/enum_clike.rs
  clippy_lints/src/excessive_bools.rs
  clippy_lints/src/exhaustive_items.rs
  clippy_lints/src/functions/result.rs
  clippy_lints/src/item_name_repetitions.rs
  clippy_lints/src/large_const_arrays.rs
  clippy_lints/src/large_enum_variant.rs
  clippy_lints/src/legacy_numeric_constants.rs
  clippy_lints/src/macro_use.rs
  clippy_lints/src/manual_non_exhaustive.rs
  clippy_lints/src/min_ident_chars.rs
  clippy_lints/src/missing_enforced_import_rename.rs
  clippy_lints/src/missing_fields_in_debug.rs
  clippy_lints/src/non_std_lazy_statics.rs
  clippy_lints/src/pub_underscore_fields.rs
  clippy_lints/src/redundant_pub_crate.rs
  clippy_lints/src/trailing_empty_array.rs
  clippy_lints/src/types/mod.rs
  clippy_lints/src/unnested_or_patterns.rs
  clippy_lints/src/unused_trait_names.rs
  clippy_lints/src/upper_case_acronyms.rs
  clippy_lints/src/wildcard_imports.rs
  clippy_lints_internal/src/almost_standard_lint_formulation.rs
  clippy_lints_internal/src/lint_without_lint_pass.rs
  clippy_utils/README.md
  clippy_utils/src/ast_utils/mod.rs
  clippy_utils/src/check_proc_macro.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/paths.rs
  clippy_utils/src/qualify_min_const_fn.rs
  rust-toolchain.toml
  tests/ui/explicit_iter_loop.fixed
  tests/ui/explicit_iter_loop.rs
  tests/ui/iter_next_loop.rs
  tests/ui/iter_not_returning_iterator.rs
  tests/ui/map_flatten.rs
  tests/ui/map_flatten_fixable.fixed
  tests/ui/map_flatten_fixable.rs
  tests/ui/map_flatten_fixable.stderr
  tests/ui/methods.rs
  tests/ui/needless_lifetimes.fixed
  tests/ui/needless_lifetimes.rs
  tests/ui/ptr_arg.rs
  tests/ui/ptr_arg.stderr
  tests/ui/significant_drop_in_scrutinee.rs
  tests/ui/trivially_copy_pass_by_ref.fixed
  tests/ui/trivially_copy_pass_by_ref.rs
  tests/ui/trivially_copy_pass_by_ref.stderr
  tests/ui/use_self.fixed
  tests/ui/use_self.rs
Labels: S-waiting-on-review

#14906 Fix `collapsible_else_if` FP on conditionally compiled stmt
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  clippy_lints/src/collapsible_if.rs
  clippy_lints/src/loops/same_item_push.rs
  clippy_lints/src/single_component_path_imports.rs
  clippy_lints/src/undocumented_unsafe_blocks.rs
  clippy_utils/src/lib.rs
  tests/ui-toml/collapsible_if/collapsible_else_if.fixed
  tests/ui-toml/collapsible_if/collapsible_else_if.rs
  tests/ui-toml/collapsible_if/collapsible_else_if.stderr
  tests/ui/collapsible_else_if.fixed
  tests/ui/collapsible_else_if.rs
  tests/ui/collapsible_if.fixed
  tests/ui/collapsible_if.rs
Labels: S-waiting-on-review

#15052 Fix `needless_doctest_main` panic when doctest is invalid
  clippy_lints/src/doc/needless_doctest_main.rs
  tests/ui/doc/needless_doctest_main.rs
Labels: S-waiting-on-review

#15040 Remove unneeded lifetime
  clippy_utils/src/lib.rs
Labels: S-waiting-on-review

#13696 Add lint for broken doc links
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/doc/broken_link.rs
  clippy_lints/src/doc/mod.rs
  tests/ui/doc_broken_link.rs
  tests/ui/doc_broken_link.stderr
Labels: S-waiting-on-review

#15065 docs: add link to span_lint in diagnostics.rs.
  clippy_utils/src/diagnostics.rs
Labels: S-waiting-on-review

#14684 Prepare to split `clippy_lints`
  Cargo.toml
  clippy_dev/src/release.rs
  clippy_dev/src/update_lints.rs
  clippy_dev/src/utils.rs
  clippy_lints/Cargo.toml
  clippy_lints/src/declare_clippy_lint.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/floating_point_arithmetic.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_let_else.rs
  clippy_lints/src/needless_parens_on_range_literals.rs
  clippy_lints/src/question_mark_used.rs
  clippy_lints/src/read_zero_byte_vec.rs
  declare_clippy_lint/Cargo.toml
  declare_clippy_lint/src/lib.rs
  src/driver.rs
  tests/compile-test.rs
  tests/dogfood.rs
  tests/versioncheck.rs
Labels: S-waiting-on-review

#15022 Fix `exhaustive_structs` FP on structs with default valued field
  clippy_lints/src/exhaustive_items.rs
  tests/ui/exhaustive_items.fixed
  tests/ui/exhaustive_items.rs
  tests/ui/exhaustive_items.stderr
Labels: S-waiting-on-review

#15080 Check MSRV before suggesting applying `const` to a function
  clippy_utils/src/msrvs.rs
  clippy_utils/src/qualify_min_const_fn.rs
  tests/ui/missing_const_for_fn/could_be_const.fixed
  tests/ui/missing_const_for_fn/could_be_const.rs
  tests/ui/missing_const_for_fn/could_be_const.stderr
Labels: S-waiting-on-review

#15081 Fix typo
  clippy_lints/src/attrs/mod.rs
Labels: S-waiting-on-review

#15082 Fix `clippy::question_mark` on let-else with cfg
  clippy_lints/src/question_mark.rs
  tests/ui/question_mark.fixed
  tests/ui/question_mark.rs
Labels: S-waiting-on-review

#15083 Fix `non_copy_const` ICE
  clippy_lints/src/non_copy_const.rs
  tests/ui/borrow_interior_mutable_const.rs
Labels: S-waiting-on-review

#15078 Fix suggestion-cases-error of `empty_line_after_outer_attr`
  clippy_lints/src/empty_line_after.rs
  tests/ui/empty_line_after/outer_attribute.1.fixed
  tests/ui/empty_line_after/outer_attribute.2.fixed
  tests/ui/empty_line_after/outer_attribute.rs
  tests/ui/empty_line_after/outer_attribute.stderr
Labels: S-waiting-on-review

#15076 Fix `branches_sharing_code` suggests misleadingly when in assignment
  clippy_lints/src/copies.rs
  tests/ui/branches_sharing_code/shared_at_bottom.rs
  tests/ui/branches_sharing_code/shared_at_bottom.stderr
Labels: S-waiting-on-review

#15053 Fix `manual_ok_err` suggests wrongly with references
  clippy_lints/src/matches/manual_ok_err.rs
  tests/ui/manual_ok_err.fixed
  tests/ui/manual_ok_err.rs
  tests/ui/manual_ok_err.stderr
Labels: S-waiting-on-review

#15030 [PERF] Don't spawn so many compilers (3/2) (19m -> 250k)
  clippy_lints/src/doc/needless_doctest_main.rs
  tests/ui/doc/needless_doctest_main.rs
  tests/ui/doc/needless_doctest_main.stderr
Labels: S-waiting-on-review, performance-project

#14983 `Sugg`: do not parenthesize a double unary operator
  clippy_utils/src/sugg.rs
  tests/ui/nonminimal_bool.stderr
Labels: S-waiting-on-review

#14967 Fix false positive of `borrow_deref_ref`
  clippy_lints/src/borrow_deref_ref.rs
  tests/ui/borrow_deref_ref.fixed
  tests/ui/borrow_deref_ref.rs
  tests/ui/borrow_deref_ref.stderr
Labels: S-waiting-on-review

#15071 or_fun_call: lint more methods
  clippy_dev/src/lint.rs
  clippy_dev/src/serve.rs
  clippy_lints/src/attrs/utils.rs
  clippy_lints/src/methods/or_fun_call.rs
  clippy_utils/src/sym.rs
  lintcheck/src/main.rs
  src/main.rs
  tests/ui/or_fun_call.fixed
  tests/ui/or_fun_call.rs
  tests/ui/or_fun_call.stderr
Labels: S-waiting-on-review, L-nursery

#15001 Add MSRV test for `unnecessary_debug_formatting` with `OsStr`
  tests/ui/unnecessary_os_str_debug_formatting.rs
  tests/ui/unnecessary_os_str_debug_formatting.stderr
Labels: S-waiting-on-review

#15125 changelog: link to the correct PR
  CHANGELOG.md
Labels: S-waiting-on-review

#15130 Add beta-accepted to CHANGELOG for 1.88
  CHANGELOG.md
Labels: S-waiting-on-review

#15148 Rustup
  Cargo.toml
  clippy_config/Cargo.toml
  clippy_dev/src/update_lints.rs
  clippy_lints/Cargo.toml
  clippy_lints/src/attrs/inline_always.rs
  clippy_lints/src/bool_assert_comparison.rs
  clippy_lints/src/casts/manual_dangling_ptr.rs
  clippy_lints/src/casts/unnecessary_cast.rs
  clippy_lints/src/coerce_container_to_any.rs
  clippy_lints/src/dereference.rs
  clippy_lints/src/doc/doc_suspicious_footnotes.rs
  clippy_lints/src/doc/needless_doctest_main.rs
  clippy_lints/src/eta_reduction.rs
  clippy_lints/src/functions/must_use.rs
  clippy_lints/src/inline_fn_without_body.rs
  clippy_lints/src/loops/single_element_loop.rs
  clippy_lints/src/manual_option_as_slice.rs
  clippy_lints/src/matches/manual_utils.rs
  clippy_lints/src/methods/io_other_error.rs
  clippy_lints/src/methods/unnecessary_to_owned.rs
  clippy_lints/src/missing_inline.rs
  clippy_lints/src/needless_borrows_for_generic_args.rs
  clippy_lints/src/needless_pass_by_value.rs
  clippy_lints/src/neg_multiply.rs
  clippy_lints/src/no_mangle_with_rust_abi.rs
  clippy_lints/src/pass_by_ref_or_value.rs
  clippy_lints/src/redundant_slicing.rs
  clippy_lints/src/return_self_not_must_use.rs
  clippy_lints/src/single_range_in_vec_init.rs
  clippy_lints/src/to_digit_is_some.rs
  clippy_lints/src/transmute/transmutes_expressible_as_ptr_casts.rs
  clippy_lints/src/unnested_or_patterns.rs
  clippy_lints/src/useless_concat.rs
  clippy_utils/Cargo.toml
  clippy_utils/README.md
  clippy_utils/src/lib.rs
  clippy_utils/src/paths.rs
  clippy_utils/src/qualify_min_const_fn.rs
  clippy_utils/src/sym.rs
  clippy_utils/src/ty/mod.rs
  declare_clippy_lint/Cargo.toml
  rust-toolchain.toml
  src/driver.rs
  tests/ui/author/macro_in_closure.stdout
  tests/ui/author/macro_in_loop.stdout
  tests/ui/def_id_nocore.rs
  tests/ui/def_id_nocore.stderr
  tests/ui/large_stack_frames.rs
  tests/ui/large_stack_frames.stderr
  tests/ui/manual_inspect.fixed
  tests/ui/manual_inspect.rs
  tests/ui/manual_inspect.stderr
  tests/ui/single_range_in_vec_init.rs
  tests/ui/single_range_in_vec_init.stderr
Labels: S-waiting-on-review

#15152 `zero_ptr`: lint in `const` context as well
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  clippy_lints/src/casts/mod.rs
  clippy_lints/src/casts/zero_ptr.rs
  clippy_utils/src/msrvs.rs
  tests/ui/zero_ptr.fixed
  tests/ui/zero_ptr.rs
  tests/ui/zero_ptr.stderr
Labels: C-bug, S-waiting-on-review, I-false-negative
