Repository rust-lang/rust-clippy, pull requests merged in 2025-10, with the labels that each got.

#15746 Do not suggest using a `if let` chain if it is not supported
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  clippy_lints/src/collapsible_if.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/unwrap.rs
  clippy_utils/src/lib.rs
  tests/ui/checked_unwrap/if_let_chains.rs
  tests/ui/checked_unwrap/if_let_chains.stderr
Labels: S-waiting-on-review

#15797 `map_identity`: simplify lint emission
  clippy_lints/src/methods/map_identity.rs
Labels: S-waiting-on-review

#15721 split `copies` lints each into its own module
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/ifs/branches_sharing_code.rs
  clippy_lints/src/ifs/if_same_then_else.rs
  clippy_lints/src/ifs/ifs_same_cond.rs
  clippy_lints/src/ifs/mod.rs
  clippy_lints/src/ifs/same_functions_in_if_cond.rs
  clippy_lints/src/lib.rs
Labels: S-waiting-on-review

#15791 Fix `let_unit_value` suggests wrongly for field init shorthand
  clippy_lints/src/unit_types/let_unit_value.rs
  tests/ui/let_unit.fixed
  tests/ui/let_unit.rs
  tests/ui/let_unit.stderr
Labels: S-waiting-on-review

#15814 fix(zero_repeat_side_effects): better identify exprs with side effects
  clippy_lints/src/zero_repeat_side_effects.rs
  tests/ui/zero_repeat_side_effects.fixed
  tests/ui/zero_repeat_side_effects.rs
  tests/ui/zero_repeat_side_effects.stderr
Labels: S-waiting-on-review

#15773 Const eval changes
  clippy_lints/src/assertions_on_constants.rs
  clippy_lints/src/enum_clike.rs
  clippy_lints/src/floating_point_arithmetic.rs
  clippy_lints/src/if_not_else.rs
  clippy_lints/src/implicit_saturating_add.rs
  clippy_lints/src/invalid_upcast_comparisons.rs
  clippy_lints/src/manual_float_methods.rs
  clippy_lints/src/manual_rem_euclid.rs
  clippy_lints/src/manual_rotate.rs
  clippy_lints/src/manual_strip.rs
  clippy_lints/src/matches/manual_unwrap_or.rs
  clippy_lints/src/matches/overlapping_arms.rs
  clippy_lints/src/methods/ip_constant.rs
  clippy_lints/src/methods/is_digit_ascii_radix.rs
  clippy_lints/src/methods/iter_nth_zero.rs
  clippy_lints/src/methods/iter_skip_zero.rs
  clippy_lints/src/methods/repeat_once.rs
  clippy_lints/src/methods/str_splitn.rs
  clippy_lints/src/methods/unnecessary_min_or_max.rs
  clippy_lints/src/minmax.rs
  clippy_lints/src/operators/arithmetic_side_effects.rs
  clippy_lints/src/operators/const_comparisons.rs
  clippy_lints/src/operators/duration_subsec.rs
  clippy_lints/src/operators/erasing_op.rs
  clippy_lints/src/operators/float_cmp.rs
  clippy_lints/src/operators/identity_op.rs
  clippy_lints/src/operators/manual_is_multiple_of.rs
  clippy_lints/src/operators/modulo_arithmetic.rs
  clippy_lints/src/operators/numeric_arithmetic.rs
  clippy_lints/src/ranges.rs
  clippy_lints/src/zero_div_zero.rs
  clippy_utils/src/consts.rs
  clippy_utils/src/higher.rs
  clippy_utils/src/hir_utils.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/paths.rs
  clippy_utils/src/sym.rs
  tests/ui/assertions_on_constants.rs
  tests/ui/assertions_on_constants.stderr
  tests/ui/const_comparisons.rs
  tests/ui/const_comparisons.stderr
  tests/ui/const_is_empty.rs
  tests/ui/const_is_empty.stderr
  tests/ui/duration_subsec.fixed
  tests/ui/duration_subsec.rs
  tests/ui/duration_subsec.stderr
  tests/ui/floating_point_log.fixed
  tests/ui/floating_point_log.rs
  tests/ui/floating_point_log.stderr
  tests/ui/ip_constant.fixed
  tests/ui/ip_constant.rs
  tests/ui/ip_constant.stderr
  tests/ui/manual_float_methods.rs
  tests/ui/manual_float_methods.stderr
  tests/ui/manual_strip.stderr
  tests/ui/repeat_once.fixed
  tests/ui/repeat_once.rs
  tests/ui/repeat_once.stderr
Labels: S-waiting-on-author

#15796 `redundant_pattern_match`: clean-up
  clippy_lints/src/matches/redundant_pattern_match.rs
Labels: S-waiting-on-review

#15804 Cleanup `should_implement_trait` lint code
  clippy_lints/src/methods/should_implement_trait.rs
Labels: S-waiting-on-review

#15822 Fixed some lint deprecated versions in the documentation
  clippy_lints/src/deprecated_lints.rs
Labels: S-waiting-on-review, beta-nominated

#15625 Use expect for lint warnings
  clippy_config/src/conf.rs
  clippy_config/src/types.rs
  clippy_dev/src/dogfood.rs
  clippy_dev/src/main.rs
  clippy_dev/src/new_lint.rs
  clippy_lints/src/arbitrary_source_item_ordering.rs
  clippy_lints/src/deprecated_lints.rs
  clippy_lints/src/doc/mod.rs
  clippy_lints/src/eta_reduction.rs
  clippy_lints/src/format.rs
  clippy_lints/src/format_args.rs
  clippy_lints/src/functions/must_use.rs
  clippy_lints/src/functions/ref_option.rs
  clippy_lints/src/implicit_saturating_sub.rs
  clippy_lints/src/lifetimes.rs
  clippy_lints/src/loops/mod.rs
  clippy_lints/src/loops/never_loop.rs
  clippy_lints/src/matches/collapsible_match.rs
  clippy_lints/src/methods/clone_on_copy.rs
  clippy_lints/src/methods/filter_map.rs
  clippy_lints/src/methods/map_all_any_identity.rs
  clippy_lints/src/methods/mod.rs
  clippy_lints/src/methods/search_is_some.rs
  clippy_lints/src/methods/str_splitn.rs
  clippy_lints/src/methods/unnecessary_to_owned.rs
  clippy_lints/src/methods/wrong_self_convention.rs
  clippy_lints/src/needless_maybe_sized.rs
  clippy_lints/src/needless_pass_by_ref_mut.rs
  clippy_lints/src/only_used_in_recursion.rs
  clippy_lints/src/operators/bit_mask.rs
  clippy_lints/src/swap.rs
  clippy_lints/src/trait_bounds.rs
  clippy_lints/src/types/mod.rs
  clippy_lints/src/undocumented_unsafe_blocks.rs
  clippy_lints/src/utils/author.rs
  clippy_utils/src/ast_utils/mod.rs
  clippy_utils/src/check_proc_macro.rs
  clippy_utils/src/consts.rs
  clippy_utils/src/higher.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/mir/mod.rs
  clippy_utils/src/mir/possible_borrower.rs
  clippy_utils/src/mir/possible_origin.rs
  clippy_utils/src/source.rs
  clippy_utils/src/ty/mod.rs
  clippy_utils/src/ty/type_certainty/mod.rs
  clippy_utils/src/visitors.rs
  lintcheck/src/config.rs
  lintcheck/src/input.rs
  lintcheck/src/main.rs
  src/driver.rs
  src/main.rs
  tests/compile-test.rs
  tests/symbols-used.rs
Labels: S-waiting-on-review

#15608 fix(collapsible_match): exclude binding modes from struct field pattern suggestions
  clippy_lints/src/matches/collapsible_match.rs
  tests/ui/collapsible_match.rs
  tests/ui/collapsible_match.stderr
Labels: S-waiting-on-review

#14953 Add `replace_box` lint
  CHANGELOG.md
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/replace_box.rs
  tests/ui/replace_box.fixed
  tests/ui/replace_box.rs
  tests/ui/replace_box.stderr
Labels: S-waiting-on-author, S-final-comment-period

#15834 `replace_box`: clean-up a bit
  clippy_lints/src/replace_box.rs
Labels: S-waiting-on-review
