Repository rust-lang/rust-clippy, pull requests merged in 2025-05, with the labels that each got.

#14721 Rustup
  clippy_lints/src/dereference.rs
  clippy_lints/src/missing_const_for_fn.rs
  clippy_utils/README.md
  clippy_utils/src/hir_utils.rs
  clippy_utils/src/source.rs
  rust-toolchain.toml
  tests/ui/blocks_in_conditions.fixed
  tests/ui/blocks_in_conditions.rs
  tests/ui/blocks_in_conditions.stderr
  tests/ui/checked_unwrap/simple_conditionals.stderr
  tests/ui/crashes/ice-1782.rs
  tests/ui/needless_if.fixed
  tests/ui/needless_if.rs
  tests/ui/needless_if.stderr
  tests/ui/needless_late_init.fixed
  tests/ui/needless_late_init.rs
  tests/ui/needless_late_init.stderr
  tests/ui/ptr_eq.fixed
  tests/ui/ptr_eq.rs
  tests/ui/ptr_eq.stderr
  tests/ui/transmute.rs
  tests/ui/transmute.stderr
  tests/ui/transmute_float_to_int.fixed
  tests/ui/transmute_float_to_int.rs
  tests/ui/transmute_int_to_char.fixed
  tests/ui/transmute_int_to_char.rs
  tests/ui/transmute_int_to_char_no_std.fixed
  tests/ui/transmute_int_to_char_no_std.rs
Labels: S-waiting-on-review

#14717 Remove `is_normalizable`
  clippy_lints/src/casts/manual_dangling_ptr.rs
  clippy_lints/src/transmute/eager_transmute.rs
  clippy_lints/src/zero_sized_map_values.rs
  clippy_utils/src/ty/mod.rs
Labels: S-waiting-on-review

#14642 Fix `new_lint` clippy command
  clippy_dev/src/new_lint.rs
Labels: S-waiting-on-review

#14733 Don't warn about unloaded crates
  clippy_config/src/types.rs
  tests/ui-toml/toml_unloaded_crate/clippy.toml
  tests/ui-toml/toml_unloaded_crate/conf_unloaded_crate.rs
  tests/ui-toml/toml_unloaded_crate/conf_unloaded_crate.stderr
Labels: S-waiting-on-review

#14720 fix: `unused_async` FP on default impl
  clippy_lints/src/unused_async.rs
  tests/ui/unused_async.rs
Labels: S-waiting-on-review

#14736 Read PR body from event in clippy_changelog action
  .github/workflows/clippy_changelog.yml
Labels: S-waiting-on-review

#14737 Remove myself from users on vacation
  triagebot.toml
Labels: S-waiting-on-review

#14731 Fix `manual_unwrap_or_default` FP on ref binding
  clippy_lints/src/matches/manual_unwrap_or.rs
  tests/ui/manual_unwrap_or_default.fixed
  tests/ui/manual_unwrap_or_default.rs
Labels: S-waiting-on-review

#14730 Fix `collapsible_if` FP on block stmt before expr
  clippy_lints/src/collapsible_if.rs
  tests/ui/collapsible_if.fixed
  tests/ui/collapsible_if.rs
Labels: S-waiting-on-author, beta-nominated

#14738 Remove some unused `#![feature]`s
  clippy_config/src/lib.rs
  clippy_dev/src/lib.rs
  clippy_lints/src/lib.rs
  clippy_lints_internal/Cargo.toml
  clippy_lints_internal/src/lib.rs
  clippy_utils/src/lib.rs
  lintcheck/src/main.rs
  src/driver.rs
  tests/compile-test.rs
  tests/ui/bool_to_int_with_if.fixed
  tests/ui/bool_to_int_with_if.rs
  tests/ui/bool_to_int_with_if.stderr
  tests/ui/comparison_to_empty.fixed
  tests/ui/comparison_to_empty.rs
  tests/ui/comparison_to_empty.stderr
  tests/ui/needless_if.fixed
  tests/ui/needless_if.rs
  tests/ui/needless_if.stderr
  tests/ui/redundant_pattern_matching_option.fixed
  tests/ui/redundant_pattern_matching_option.rs
Labels: S-waiting-on-review

#14453 add allow_unused config to missing_docs_in_private_items
  CHANGELOG.md
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  clippy_lints/src/missing_doc.rs
  tests/ui-toml/missing_docs_allow_unused/clippy.toml
  tests/ui-toml/missing_docs_allow_unused/missing_docs_allow_unused.rs
  tests/ui-toml/missing_docs_allow_unused/missing_docs_allow_unused.stderr
  tests/ui-toml/toml_unknown_key/conf_unknown_key.stderr
Labels: S-waiting-on-review

#14619 `item_name_repetitions`: exclude enum variants with identical path components
  clippy_lints/src/item_name_repetitions.rs
  tests/ui/enum_variants.rs
Labels: S-waiting-on-review

#14575 `unwrap_used`, `expect_used`: accept macro result as receiver
  clippy_lints/src/methods/mod.rs
  tests/ui/unwrap_expect_used.rs
  tests/ui/unwrap_expect_used.stderr
Labels: S-waiting-on-review

#14745 Replace `Symbol::as_str` usage in `match` expressions
  clippy_lints/src/attrs/useless_attribute.rs
  clippy_lints/src/bool_assert_comparison.rs
  clippy_lints/src/floating_point_arithmetic.rs
  clippy_lints/src/manual_ignore_case_cmp.rs
  clippy_lints/src/manual_option_as_slice.rs
  clippy_lints/src/methods/case_sensitive_file_extension_comparisons.rs
  clippy_lints/src/methods/manual_c_str_literals.rs
  clippy_lints/src/methods/needless_collect.rs
  clippy_lints/src/mutable_debug_assertion.rs
  clippy_lints/src/operators/eq_op.rs
  clippy_lints/src/panic_in_result_fn.rs
  clippy_lints/src/panic_unimplemented.rs
  clippy_lints/src/returns.rs
  clippy_lints/src/strings.rs
  clippy_lints/src/unit_types/unit_cmp.rs
  clippy_lints/src/unused_io_amount.rs
  clippy_lints/src/write.rs
  clippy_lints_internal/src/symbols.rs
  clippy_utils/src/sym.rs
  tests/ui-internal/interning_literals.stderr
  tests/ui-internal/interning_literals_unfixable.stderr
  tests/ui-internal/symbol_as_str.fixed
  tests/ui-internal/symbol_as_str.rs
  tests/ui-internal/symbol_as_str.stderr
  tests/ui-internal/symbol_as_str_unfixable.stderr
Labels: S-waiting-on-review, performance-project

#14746 Fix diagnostic paths printed by dogfood test
  tests/dogfood.rs
Labels: S-waiting-on-review

#14749 Make `let_with_type_underscore` help message into a suggestion
  clippy_lints/src/let_with_type_underscore.rs
  tests/ui/let_with_type_underscore.fixed
  tests/ui/let_with_type_underscore.stderr
Labels: S-waiting-on-review

#14732 Fix `manual_let_else` FN when diverges on simple enum variant
  clippy_lints/src/manual_let_else.rs
  tests/ui/manual_let_else.rs
  tests/ui/manual_let_else.stderr
Labels: S-waiting-on-review

#14765 Allow any rust-lang team member to close an issue with rustbot
  triagebot.toml
Labels: S-waiting-on-review

#14766 Use `cargo dev setup toolchain` in install from source docs
  book/src/development/basics.md
Labels: S-waiting-on-review

#14703 remove superseded lints
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/deprecated_lints.rs
  clippy_lints/src/transmute/mod.rs
  clippy_lints/src/transmute/transmute_float_to_int.rs
  clippy_lints/src/transmute/transmute_int_to_char.rs
  clippy_lints/src/transmute/transmute_int_to_float.rs
  clippy_lints/src/transmute/transmute_num_to_bytes.rs
  tests/ui/rename.fixed
  tests/ui/rename.rs
  tests/ui/rename.stderr
  tests/ui/transmute.rs
  tests/ui/transmute.stderr
  tests/ui/transmute_float_to_int.fixed
  tests/ui/transmute_float_to_int.rs
  tests/ui/transmute_float_to_int.stderr
  tests/ui/transmute_int_to_char.fixed
  tests/ui/transmute_int_to_char.rs
  tests/ui/transmute_int_to_char.stderr
  tests/ui/transmute_int_to_char_no_std.fixed
  tests/ui/transmute_int_to_char_no_std.rs
  tests/ui/transmute_int_to_char_no_std.stderr
Labels: S-waiting-on-review, beta-nominated

#14761 `unwrap.rs` cleanup
  clippy_lints/src/unwrap.rs
Labels: S-waiting-on-review

#14664 Fix integer_division false negative for NonZero denominators
  clippy_lints/src/operators/integer_division.rs
  tests/ui/integer_division.rs
  tests/ui/integer_division.stderr
Labels: S-waiting-on-review

#14771 `char::is_digit()` is const-stable only since Rust 1.87
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/to_digit_is_some.rs
  clippy_utils/src/msrvs.rs
  tests/ui/to_digit_is_some.fixed
  tests/ui/to_digit_is_some.rs
  tests/ui/to_digit_is_some.stderr
Labels: S-waiting-on-review

#14770 Fix `unnecessary_unwrap` emitted twice in closure (#14763)
  clippy_lints/src/unwrap.rs
  tests/ui/checked_unwrap/simple_conditionals.rs
  tests/ui/checked_unwrap/simple_conditionals.stderr
Labels: S-waiting-on-review

#14772 Resolve through local re-exports in `lookup_path`
  clippy_utils/src/paths.rs
  tests/ui-toml/toml_disallowed_methods/clippy.toml
  tests/ui-toml/toml_disallowed_methods/conf_disallowed_methods.rs
  tests/ui-toml/toml_disallowed_methods/conf_disallowed_methods.stderr
Labels: S-waiting-on-review

#14776 Fix ICE in `missing_const_for_fn`
  clippy_lints/src/missing_const_for_fn.rs
  tests/ui/crashes/missing_const_for_fn_14774.fixed
  tests/ui/crashes/missing_const_for_fn_14774.rs
  tests/ui/crashes/missing_const_for_fn_14774.stderr
Labels: S-waiting-on-review, beta-nominated

#14784 Use `tempfile::TempDir::keep()` instead of deprecated `into_path()`
  Cargo.toml
  tests/integration.rs
Labels: S-waiting-on-review

#14780 book: modify FnKind::Fn matching
  book/src/development/adding_lints.md
Labels: S-waiting-on-review

#13979 Add new `confusing_method_to_numeric_cast` lint
  CHANGELOG.md
  clippy_lints/src/casts/confusing_method_to_numeric_cast.rs
  clippy_lints/src/casts/mod.rs
  clippy_lints/src/declared_lints.rs
  tests/ui/confusing_method_to_numeric_cast.fixed
  tests/ui/confusing_method_to_numeric_cast.rs
  tests/ui/confusing_method_to_numeric_cast.stderr
Labels: S-waiting-on-author

#14783 `return_and_then`: only lint returning expressions
  clippy_lints/src/methods/return_and_then.rs
  tests/ui/return_and_then.fixed
  tests/ui/return_and_then.rs
  tests/ui/return_and_then.stderr
Labels: S-waiting-on-review

#14752 Fix messages for `type_repetition_in_bounds`
  clippy_lints/src/trait_bounds.rs
  tests/ui-toml/type_repetition_in_bounds/main.rs
  tests/ui-toml/type_repetition_in_bounds/main.stderr
  tests/ui/type_repetition_in_bounds.rs
  tests/ui/type_repetition_in_bounds.stderr
Labels: S-waiting-on-review

#14785 Update "Changelog update walkthrough" section
  book/src/development/infrastructure/changelog_update.md
Labels: S-waiting-on-review

#14788 Do not use `clippy_utils` from UI tests
  Cargo.toml
  tests/ui/let_underscore_untyped.rs
  tests/ui/let_underscore_untyped.stderr
Labels: S-waiting-on-review

#14284 Add new lint: `cloned_ref_to_slice_refs`
  CHANGELOG.md
  clippy_lints/src/cloned_ref_to_slice_refs.rs
  clippy_lints/src/declared_lints.rs
  clippy_lints/src/lib.rs
  clippy_utils/src/msrvs.rs
  tests/ui/cloned_ref_to_slice_refs.fixed
  tests/ui/cloned_ref_to_slice_refs.rs
  tests/ui/cloned_ref_to_slice_refs.stderr
Labels: S-waiting-on-review

#14740 Post `non_std_lazy_statics` type warnings onto the right node
  clippy_lints/src/non_std_lazy_statics.rs
  tests/ui/non_std_lazy_static/non_std_lazy_static_fixable.fixed
  tests/ui/non_std_lazy_static/non_std_lazy_static_fixable.rs
Labels: S-waiting-on-review

#14616 `clippy_dev` refactor
  clippy_dev/src/deprecate_lint.rs
  clippy_dev/src/dogfood.rs
  clippy_dev/src/fmt.rs
  clippy_dev/src/lib.rs
  clippy_dev/src/main.rs
  clippy_dev/src/new_lint.rs
  clippy_dev/src/release.rs
  clippy_dev/src/rename_lint.rs
  clippy_dev/src/sync.rs
  clippy_dev/src/update_lints.rs
  clippy_dev/src/utils.rs
  clippy_lints/src/deprecated_lints.rs
Labels: S-waiting-on-review

#14815 Rustup
  Cargo.toml
  clippy_config/Cargo.toml
  clippy_dev/src/utils.rs
  clippy_lints/Cargo.toml
  clippy_lints/src/non_copy_const.rs
  clippy_lints/src/wildcard_imports.rs
  clippy_utils/Cargo.toml
  clippy_utils/README.md
  clippy_utils/src/ty/mod.rs
  rust-toolchain.toml
  tests/ui/author/macro_in_closure.stdout
  tests/ui/author/macro_in_loop.stdout
  tests/ui/double_ended_iterator_last.fixed
  tests/ui/double_ended_iterator_last.rs
  tests/ui/double_ended_iterator_last.stderr
  tests/ui/double_ended_iterator_last_unfixable.rs
  tests/ui/double_ended_iterator_last_unfixable.stderr
  tests/ui/wildcard_imports.fixed
  tests/ui/wildcard_imports.stderr
  tests/ui/wildcard_imports_2021.edition2018.fixed
  tests/ui/wildcard_imports_2021.edition2018.stderr
  tests/ui/wildcard_imports_2021.edition2021.fixed
  tests/ui/wildcard_imports_2021.edition2021.stderr
Labels: S-waiting-on-review

#14800 Fix false positive of `useless_conversion` when using `.into_iter().any()`
  clippy_lints/src/useless_conversion.rs
  tests/ui/useless_conversion.fixed
  tests/ui/useless_conversion.rs
  tests/ui/useless_conversion.stderr
Labels: S-waiting-on-review

#14811 comparison_chain: do not lint on 2 blocks expression
  clippy_lints/src/comparison_chain.rs
  tests/ui/comparison_chain.rs
  tests/ui/comparison_chain.stderr
Labels: S-waiting-on-review

#14777 `unnecessary_wraps`: do not include the whole body in the lint span
  clippy_lints/src/unnecessary_wraps.rs
  tests/ui/unnecessary_wraps.stderr
Labels: S-waiting-on-review

#14808 Reenable linting on UFCS `deref` calls
  clippy_lints/src/dereference.rs
  tests/ui/explicit_deref_methods.fixed
  tests/ui/explicit_deref_methods.rs
  tests/ui/explicit_deref_methods.stderr
Labels: S-waiting-on-review

#13207 Rewrite `non_copy_const`
  clippy_lints/src/non_copy_const.rs
  clippy_utils/src/ty/mod.rs
  tests/ui/auxiliary/interior_mutable_const.rs
  tests/ui/borrow_interior_mutable_const.rs
  tests/ui/borrow_interior_mutable_const.stderr
  tests/ui/borrow_interior_mutable_const/enums.rs
  tests/ui/borrow_interior_mutable_const/enums.stderr
  tests/ui/borrow_interior_mutable_const/others.rs
  tests/ui/borrow_interior_mutable_const/others.stderr
  tests/ui/borrow_interior_mutable_const/projections.rs
  tests/ui/borrow_interior_mutable_const/projections.stderr
  tests/ui/borrow_interior_mutable_const/traits.rs
  tests/ui/borrow_interior_mutable_const/traits.stderr
  tests/ui/crashes/ice-12979.1.fixed
  tests/ui/crashes/ice-12979.2.fixed
  tests/ui/crashes/ice-12979.rs
  tests/ui/crashes/ice-12979.stderr
  tests/ui/crashes/ice-9445.rs
  tests/ui/crashes/ice-9445.stderr
  tests/ui/declare_interior_mutable_const.rs
  tests/ui/declare_interior_mutable_const.stderr
  tests/ui/declare_interior_mutable_const/enums.rs
  tests/ui/declare_interior_mutable_const/enums.stderr
  tests/ui/declare_interior_mutable_const/others.rs
  tests/ui/declare_interior_mutable_const/others.stderr
  tests/ui/declare_interior_mutable_const/traits.rs
  tests/ui/declare_interior_mutable_const/traits.stderr
Labels: S-waiting-on-review

#14633 Extend `cargo dev rename_lint`
  clippy_dev/Cargo.toml
  clippy_dev/src/deprecate_lint.rs
  clippy_dev/src/lib.rs
  clippy_dev/src/rename_lint.rs
  clippy_dev/src/update_lints.rs
  clippy_dev/src/utils.rs
  clippy_lints/src/deprecated_lints.rs
  tests/ui/deprecated.rs
  tests/ui/deprecated.stderr
  tests/ui/rename.fixed
  tests/ui/rename.rs
  tests/ui/rename.stderr
Labels: S-waiting-on-review

#14610 Skip inner ordering checking in presence of `#[repr(…)]`
  clippy_lints/src/arbitrary_source_item_ordering.rs
  tests/ui-toml/arbitrary_source_item_ordering/ordering_mixed.default.stderr
  tests/ui-toml/arbitrary_source_item_ordering/ordering_mixed.default_exp.stderr
  tests/ui-toml/arbitrary_source_item_ordering/ordering_mixed.ord_within.stderr
  tests/ui-toml/arbitrary_source_item_ordering/ordering_mixed.rs
Labels: S-waiting-on-review

#14824 excessive_precision: Fix false positive when exponent has leading zero
  clippy_lints/src/float_literal.rs
  tests/ui/excessive_precision.fixed
  tests/ui/excessive_precision.rs
  tests/ui/excessive_precision.stderr
Labels: S-waiting-on-review

#14638 Refactor and speed up `cargo dev fmt`
  Cargo.toml
  clippy_config/Cargo.toml
  clippy_dev/Cargo.toml
  clippy_dev/src/fmt.rs
  clippy_dev/src/lib.rs
  clippy_dev/src/main.rs
  clippy_dev/src/release.rs
  clippy_dev/src/update_lints.rs
  clippy_dev/src/utils.rs
  clippy_lints/Cargo.toml
  clippy_utils/Cargo.toml
  tests/ui/skip_rustfmt/non_expressive_names_error_recovery.fixed
  tests/ui/skip_rustfmt/non_expressive_names_error_recovery.rs
  tests/ui/skip_rustfmt/non_expressive_names_error_recovery.stderr
Labels: S-blocked

#14702 Misc changes
  clippy_lints/src/cognitive_complexity.rs
  clippy_lints/src/copies.rs
  clippy_lints/src/extra_unused_type_parameters.rs
  clippy_lints/src/functions/must_use.rs
  clippy_lints/src/functions/result.rs
  clippy_lints/src/implicit_hasher.rs
  clippy_lints/src/inherent_to_string.rs
  clippy_lints/src/lifetimes.rs
  clippy_lints/src/methods/manual_inspect.rs
  clippy_lints/src/missing_const_for_fn.rs
  clippy_lints/src/mut_key.rs
  clippy_lints/src/operators/assign_op_pattern.rs
  clippy_lints/src/suspicious_trait_impl.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/source.rs
  tests/ui-toml/collapsible_if/collapsible_if.fixed
  tests/ui-toml/collapsible_if/collapsible_if.stderr
  tests/ui/manual_inspect.fixed
  tests/ui/manual_inspect.stderr
Labels: S-waiting-on-review

#14623 `empty_struct_with_brackets`: do not lint code coming from macro expansion
  clippy_lints/src/empty_with_brackets.rs
  tests/ui/empty_structs_with_brackets.fixed
  tests/ui/empty_structs_with_brackets.rs
Labels: S-waiting-on-review

#14835 Fixing minor typo in book
  book/src/development/basics.md
Labels: S-waiting-on-review

#14830 Do not call `TyCtxt::type_of()` on a trait
  clippy_lints/src/methods/useless_asref.rs
  tests/ui/useless_asref.fixed
  tests/ui/useless_asref.rs
Labels: S-waiting-on-review, beta-nominated

#14839 Add a reason to/remove some `//@no-rustfix` annotations
  tests/ui/assign_ops.fixed
  tests/ui/assign_ops.rs
  tests/ui/assign_ops.stderr
  tests/ui/assign_ops2.rs
  tests/ui/cast.rs
  tests/ui/cast_size.rs
  tests/ui/checked_unwrap/complex_conditionals_nested.rs
  tests/ui/checked_unwrap/simple_conditionals.rs
  tests/ui/comparison_chain.rs
  tests/ui/dbg_macro/dbg_macro_unfixable.rs
  tests/ui/double_ended_iterator_last_unfixable.rs
  tests/ui/entry_unfixable.rs
  tests/ui/entry_unfixable.stderr
  tests/ui/explicit_counter_loop.rs
  tests/ui/filter_map_bool_then_unfixable.rs
  tests/ui/filter_map_bool_then_unfixable.stderr
  tests/ui/impl_trait_in_params.rs
  tests/ui/infinite_loop.rs
  tests/ui/infinite_loop.stderr
  tests/ui/infinite_loops.rs
  tests/ui/into_iter_without_iter.rs
  tests/ui/iter_out_of_bounds.rs
  tests/ui/iter_out_of_bounds.stderr
  tests/ui/misrefactored_assign_op.1.fixed
  tests/ui/misrefactored_assign_op.2.fixed
  tests/ui/misrefactored_assign_op.rs
  tests/ui/misrefactored_assign_op.stderr
Labels: S-waiting-on-review

#14834 fix: `unnecessary_to_owned` FP when map key is a reference
  clippy_lints/src/methods/unnecessary_to_owned.rs
  tests/ui/unnecessary_to_owned.fixed
  tests/ui/unnecessary_to_owned.rs
Labels: S-waiting-on-review

#14844 Docs: Use spaces in `good first issue` label
  CONTRIBUTING.md
  book/src/development/the_team.md
  triagebot.toml
Labels: S-waiting-on-review

#14594 Check if dropping an expression may have indirect side-effects
  clippy_lints/src/no_effect.rs
  tests/ui/no_effect.rs
  tests/ui/single_range_in_vec_init.rs
Labels: S-waiting-on-review

#14851 Remove obsolete restriction in code
  src/driver.rs
Labels: S-waiting-on-review

#14852 Access items through `rustc_session` instead of `rustc_lint_defs`
  clippy_lints_internal/src/almost_standard_lint_formulation.rs
  clippy_lints_internal/src/collapsible_calls.rs
  clippy_lints_internal/src/derive_deserialize_allowing_unknown.rs
  clippy_lints_internal/src/lib.rs
  clippy_lints_internal/src/lint_without_lint_pass.rs
  clippy_lints_internal/src/msrv_attr_impl.rs
  clippy_lints_internal/src/outer_expn_data_pass.rs
  clippy_lints_internal/src/produce_ice.rs
  clippy_lints_internal/src/symbols.rs
  clippy_lints_internal/src/unnecessary_def_path.rs
  clippy_lints_internal/src/unsorted_clippy_utils_paths.rs
Labels: S-waiting-on-review

#14757 `needless_match`: do not pretend that `return` is not significant in an expression
  clippy_lints/src/matches/needless_match.rs
  tests/ui/needless_match.fixed
  tests/ui/needless_match.rs
  tests/ui/needless_match.stderr
Labels: S-waiting-on-review

#14837 Fix ICE while computing type layout
  clippy_lints/src/zero_sized_map_values.rs
  tests/ui/crashes/ice-6840.rs
  tests/ui/zero_sized_hashmap_values.rs
  tests/ui/zero_sized_hashmap_values.stderr
Labels: S-waiting-on-review, beta-nominated

#14790 Make lint span smaller for needless return
  clippy_lints/src/returns.rs
  tests/ui/crashes/ice-12491.fixed
  tests/ui/crashes/ice-12491.rs
  tests/ui/crashes/ice-12491.stderr
  tests/ui/needless_return.fixed
  tests/ui/needless_return.rs
  tests/ui/needless_return.stderr
Labels: S-waiting-on-review

#14631 Various macro fixes for loop lints
  clippy_lints/src/loops/explicit_into_iter_loop.rs
  clippy_lints/src/loops/explicit_iter_loop.rs
  clippy_lints/src/loops/mod.rs
  tests/ui/explicit_into_iter_loop.fixed
  tests/ui/explicit_into_iter_loop.rs
  tests/ui/explicit_into_iter_loop.stderr
  tests/ui/explicit_iter_loop.fixed
  tests/ui/explicit_iter_loop.rs
  tests/ui/explicit_iter_loop.stderr
  tests/ui/iter_next_loop.rs
  tests/ui/iter_next_loop.stderr
Labels: S-waiting-on-review

#14804 Fixes `manual_slice_size_computation` ICE and triggers in `const` context
  book/src/lint_configuration.md
  clippy_config/src/conf.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/manual_slice_size_calculation.rs
  clippy_utils/src/msrvs.rs
  tests/ui/manual_slice_size_calculation.fixed
  tests/ui/manual_slice_size_calculation.rs
  tests/ui/manual_slice_size_calculation.stderr
Labels: S-waiting-on-review

#14860 Rustup
  clippy_dev/src/sync.rs
  clippy_lints/src/approx_const.rs
  clippy_lints/src/arbitrary_source_item_ordering.rs
  clippy_lints/src/attrs/repr_attributes.rs
  clippy_lints/src/booleans.rs
  clippy_lints/src/default_union_representation.rs
  clippy_lints/src/doc/suspicious_doc_comments.rs
  clippy_lints/src/doc/too_long_first_doc_paragraph.rs
  clippy_lints/src/format_args.rs
  clippy_lints/src/incompatible_msrv.rs
  clippy_lints/src/lib.rs
  clippy_lints/src/std_instead_of_core.rs
  clippy_lints_internal/src/derive_deserialize_allowing_unknown.rs
  clippy_lints_internal/src/lib.rs
  clippy_lints_internal/src/outer_expn_data_pass.rs
  clippy_lints_internal/src/unnecessary_def_path.rs
  clippy_utils/README.md
  clippy_utils/src/lib.rs
  clippy_utils/src/msrvs.rs
  clippy_utils/src/qualify_min_const_fn.rs
  rust-toolchain.toml
Labels: S-waiting-on-review

#14862 Improve speed of `cargo dev fmt`
  clippy_dev/src/fmt.rs
  clippy_dev/src/main.rs
  clippy_dev/src/rename_lint.rs
  clippy_dev/src/update_lints.rs
  clippy_dev/src/utils.rs
  rustfmt.toml
  tests/ui/non_expressive_names_error_recovery.fixed
  tests/ui/non_expressive_names_error_recovery.rs
  tests/ui/non_expressive_names_error_recovery.stderr
Labels: S-waiting-on-review

#14693 [Perf] Optimize documentation lints **a lot** (1/2) (18% -> 10%)
  clippy_lints/src/doc/markdown.rs
  clippy_lints/src/doc/mod.rs
  tests/ui/doc/doc_markdown-issue_13097.fixed
  tests/ui/doc/doc_markdown-issue_13097.rs
  tests/ui/doc/doc_markdown-issue_13097.stderr
Labels: S-waiting-on-review, performance-project

#14735 Fix `needless_for_each` suggests wrongly when closure has no braces
  clippy_lints/src/needless_for_each.rs
  lintcheck/src/output.rs
  tests/ui/needless_for_each_fixable.fixed
  tests/ui/needless_for_each_fixable.rs
  tests/ui/needless_for_each_fixable.stderr
Labels: S-waiting-on-author

#14884 Remove compiletest headers test
  tests/headers.rs
Labels: S-waiting-on-review

#14886 Fix `assign_op_pattern` FP on unstable const trait
  clippy_lints/src/operators/assign_op_pattern.rs
  clippy_lints/src/operators/mod.rs
  clippy_utils/src/qualify_min_const_fn.rs
  tests/ui/assign_ops.fixed
  tests/ui/assign_ops.rs
  tests/ui/assign_ops.stderr
Labels: S-waiting-on-review

#14888 Update `askama` to `0.14.0` version
  Cargo.toml
Labels: S-waiting-on-review

#14892 Fix `manual_find` suggests wrongly when return type needs adjustment
  clippy_lints/src/loops/manual_find.rs
  tests/ui/manual_find_fixable.fixed
  tests/ui/manual_find_fixable.rs
  tests/ui/manual_find_fixable.stderr
Labels: S-waiting-on-review

#14890 refactor(mut_reference): replace `match` with `if-let` to reduce nesting
  clippy_lints/src/mut_reference.rs
Labels: S-waiting-on-review

#14646 Extend `manual_is_variant_and lint` to check for boolean map comparisons
  clippy_lints/src/methods/manual_is_variant_and.rs
  clippy_lints/src/methods/mod.rs
  tests/ui/manual_is_variant_and.fixed
  tests/ui/manual_is_variant_and.rs
  tests/ui/manual_is_variant_and.stderr
Labels: S-waiting-on-author

#14909 Mark myself as on vacation until June 30
  triagebot.toml
Labels: S-waiting-on-review

#14908 [book] fix the trait checking example code
  book/src/development/trait_checking.md
Labels: S-waiting-on-review

#14798 `needless_return`: look inside `else if` parts as well
  clippy_lints/src/panic_unimplemented.rs
  clippy_lints/src/returns.rs
  tests/ui/needless_return.fixed
  tests/ui/needless_return.rs
  tests/ui/needless_return.stderr
Labels: S-waiting-on-review

#14905 Optimize `unit_return_expecting_ord`
  clippy_lints/src/unit_return_expecting_ord.rs
Labels: S-waiting-on-author

#14917 Improve wording of `manual_contains` docs
  clippy_lints/src/methods/mod.rs
Labels: S-waiting-on-review

#14901 Show total count lints
  util/gh-pages/index_template.html
  util/gh-pages/script.js
Labels: S-waiting-on-review

#14898 clean-up `modulo_arithmetic`
  clippy_lints/src/operators/modulo_arithmetic.rs
Labels: S-waiting-on-review

#14937 Fix `dbg_macro` fail to handle async coroutine desugar
  clippy_lints/src/dbg_macro.rs
  tests/ui/dbg_macro/dbg_macro.fixed
  tests/ui/dbg_macro/dbg_macro.rs
  tests/ui/dbg_macro/dbg_macro.stderr
Labels: S-waiting-on-review

#14938 Rustup
  clippy_lints/src/arc_with_non_send_sync.rs
  clippy_lints/src/derive.rs
  clippy_lints/src/eta_reduction.rs
  clippy_lints/src/field_scoped_visibility_modifiers.rs
  clippy_lints/src/functions/ref_option.rs
  clippy_lints/src/index_refutable_slice.rs
  clippy_lints/src/let_underscore.rs
  clippy_lints/src/manual_string_new.rs
  clippy_lints/src/matches/manual_unwrap_or.rs
  clippy_lints/src/matches/redundant_pattern_match.rs
  clippy_lints/src/matches/significant_drop_in_scrutinee.rs
  clippy_lints/src/methods/needless_collect.rs
  clippy_lints/src/methods/or_fun_call.rs
  clippy_lints/src/methods/unnecessary_sort_by.rs
  clippy_lints/src/methods/unnecessary_to_owned.rs
  clippy_lints/src/needless_borrows_for_generic_args.rs
  clippy_lints/src/non_send_fields_in_send_ty.rs
  clippy_lints/src/only_used_in_recursion.rs
  clippy_lints/src/partial_pub_fields.rs
  clippy_lints/src/returns.rs
  clippy_lints/src/significant_drop_tightening.rs
  clippy_lints/src/tuple_array_conversions.rs
  clippy_lints/src/use_self.rs
  clippy_lints_internal/src/msrv_attr_impl.rs
  clippy_utils/README.md
  clippy_utils/src/ast_utils/mod.rs
  clippy_utils/src/consts.rs
  clippy_utils/src/lib.rs
  clippy_utils/src/qualify_min_const_fn.rs
  clippy_utils/src/sugg.rs
  clippy_utils/src/ty/mod.rs
  clippy_utils/src/ty/type_certainty/mod.rs
  rust-toolchain.toml
  tests/ui/auxiliary/proc_macro_attr.rs
  tests/ui/auxiliary/proc_macro_derive.rs
  tests/ui/cast.rs
  tests/ui/cast.stderr
  tests/ui/crashes/auxiliary/proc_macro_crash.rs
  tests/ui/duplicated_attributes.rs
Labels: S-waiting-on-review
